C-Menu: exec.c File Reference
exec.c File Reference
Functions to execute external commands.
#include <cm.h>
#include <errno.h>
#include <fcntl.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <termios.h>
#include <unistd.h>
Functions
int full_screen_fork_exec (char **argv)
Execute a command in full screen mode.
int full_screen_shell (char *shellCmdPtr)
Execute a shell command in full screen mode.
int shell (char *shellCmdPtr)
Execute a shell command.
int fork_exec (char **argv)
Fork and exec a command.
void abend (int ec, char *s)
Abnormal program termination.
void user_end ()
Program terminated by user.
int nf_error (int ec, char *s)
Display error message and wait for key press.
Variables
int eargc
char * eargv [MAXARGS]
char earg_str [MAXLEN]
Detailed Description
Functions to execute external commands.
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file exec.c.
Function Documentation
abend()
void abend (int ec, char * s)
Abnormal program termination.
Parameters
ec Exit code
s Error message
Definition at line 1058 of file dwin.c.
fork_exec()
int fork_exec (char ** argv)
Fork and exec a command.
Parameters
argv - array of arguments for the command to execute
Returns
the return code from the executed command, or -1 on error
Note
Captures and restores terminal settings around the fork and exec.
Sets signal handlers to default in the child process.
Waits for the child process to complete in the parent process.
Handles errors from fork and execvp, and reports child exit status.
Restores curses mode and keypad settings after execution.
Restores window states after execution.
Uses a temporary string buffer tmp_str for error messages.
Uses Perror for error reporting.
Uses sig_dfl_mode and sig_prog_mode for signal handling.
Uses capture_curses_tioctl and restore_curses_tioctl for terminal settings.
Uses restore_shell_tioctl for shell terminal settings.
Uses waitpid to wait for the child process.
Uses WIFEXITED, WEXITSTATUS, WIFSIGNALED, and WTERMSIG to interpret child status.
Uses keypad to manage keypad mode in curses.
Uses restore_wins to restore window states.
Uses errno for error codes.
Uses pid_t for process IDs.
Uses standard file descriptors STDIN_FILENO, STDOUT_FILENO, STDERR_FILENO.
Uses execvp for executing the command.
Uses fork for creating a new process.
Uses ssnprintf for formatting error messages.
Uses switch-case for handling fork results.
Uses default shell if SHELL environment variable is not set.
Definition at line 124 of file exec.c.
References capture_curses_tioctl(), MAXLEN, Perror(), restore_curses_tioctl(), restore_shell_tioctl(), restore_wins(), sig_dfl_mode(), sig_prog_mode(), ssnprintf(), and tmp_str.
Referenced by full_screen_fork_exec(), and shell().
full_screen_fork_exec()
int full_screen_fork_exec (char ** argv)
Execute a command in full screen mode.
Parameters
argv - array of arguments for the command to execute
Returns
the return code from the executed command
Note
Clear the screen,
move the cursor to the bottom, and refresh the screen before executing the command.
After the command completes, clear the screen, move the cursor to the top, refresh the screen, and restore the windows.
Definition at line 40 of file exec.c.
References fork_exec(), and restore_wins().
Referenced by menu_cmd_processor().
full_screen_shell()
int full_screen_shell (char * shellCmdPtr)
Execute a shell command in full screen mode.
Parameters
shellCmdPtr - pointer to the shell command string
Returns
the return code from the executed shell command
Note
Clear the screen, move the cursor to the top, and refresh the screen before executing the shell command.
After the command completes, restore the windows.
Definition at line 61 of file exec.c.
References restore_wins(), and shell().
Referenced by menu_cmd_processor(), and view_cmd_processor().
nf_error()
int nf_error (int ec, char * s)
Display error message and wait for key press.
Parameters
ec Error code
s Error message
Definition at line 1037 of file dwin.c.
References di_getch().
shell()
int shell (char * shellCmdPtr)
Execute a shell command.
Parameters
shellCmdPtr - pointer to the shell command string
Returns
the return code from the executed shell command
Note
Executes the command string using the user's shell.
If the SHELL environment variable is not set, use /bin/sh.
Definition at line 77 of file exec.c.
References DEFAULTSHELL, fork_exec(), and MAXARGS.
Referenced by form_exec_cmd(), full_screen_shell(), lp(), and view_cmd_processor().
user_end()
void user_end ()
Program terminated by user.
Definition at line 1046 of file dwin.c.
Variable Documentation
earg_str
char earg_str[MAXLEN]
earg - general use argument string general use argument string, for external commands or error messages
Definition at line 23 of file exec.c.
Referenced by enter_file_spec(), form_calculate(), form_exec_cmd(), and menu_cmd_processor().
eargc
int eargc
general use argument count, for external commands or error messages
Definition at line 21 of file exec.c.
Referenced by display_pick_help(), enter_file_spec(), form_engine(), menu_cmd_processor(), and view_display_help().
eargv
char* eargv[MAXARGS]
eargv - argument vector for external commands, or error messages
Definition at line 22 of file exec.c.
Referenced by display_pick_help(), enter_file_spec(), form_calculate(), form_engine(), menu_cmd_processor(), and view_display_help().