C-Menu: src/form_engine.c File Reference
form_engine.c File Reference
The working part of C-Menu Form.
#include <common.h>
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <termios.h>
#include <unistd.h>
#include <wait.h>
Macros
#define D_COMMENT '#'
#define D_CMD '!'
#define D_FIELD 'F'
#define D_TEXT 'T'
#define D_HELP '?'
#define D_HEADER 'H'
#define D_CALC 'C'
#define D_QUERY 'Q'
Functions
unsigned int form_display_screen (Init *init)
Display the form on the screen, including text elements and fields, and set up the form window based on the form configuration.
void form_display_fields (Form *form)
Display form fields on the screen, populating field values and formatting them according to the form configuration.
void form_display_chyron (Form *form)
Display the chyron (status line) at the bottom of the form window, showing available commands and their corresponding function keys.
int form_enter_fields (Form *form)
Handle user input for field entry, allowing navigation between fields and looping until an exit action is selected.
int form_parse_desc (Form *form)
Parse the form description file to populate the Form data structure with field definitions, text elements, and other configuration specified in the description file.
int form_read_data (Form *form)
Read initial data for form fields from a specified input source, such as a file or standard input, and populate the form fields with the data.
int form_write (Form *form)
Write form field values to a specified output destination, such as a file or standard output, based on the form configuration and user input.
void form_usage ()
Display usage information for the form, including available options and commands, to assist users in understanding how to interact with the form.
int form_desc_error (int in_line_num, char *in_buf, char *em)
Handle errors encountered while parsing the form description file, providing detailed error messages that include the file name, line number, and the specific error encountered.
int form_exec_cmd (Form *form)
Execute a provider command specified in the form description file, passing form field values as arguments, and optionally redirecting output to a file.
int form_calculate (Init *init)
Handle integration with an external program for calculation, allowing the user to execute a provider command and read results back into the form fields.
int form_end_fields (Init *init)
Handle post-processing after field entry, allowing user to edit data, execute a provider command, or write data to an output file.
int init_form (Init *init, int argc, char **argv, int begy, int begx)
Initialize form data structure and parse description file.
int form_engine (Init *init)
Form main processing loop.
int form_yx_to_fidx (Form *, int, int)
Detailed Description
The working part of C-Menu Form.
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file form_engine.c.
Macro Definition Documentation
D_CALC
#define D_CALC 'C'
Definition at line 26 of file form_engine.c.
Referenced by form_parse_desc().
D_CMD
#define D_CMD '!'
Definition at line 21 of file form_engine.c.
Referenced by form_parse_desc().
D_COMMENT
#define D_COMMENT '#'
Definition at line 20 of file form_engine.c.
Referenced by form_parse_desc().
D_FIELD
#define D_FIELD 'F'
Definition at line 22 of file form_engine.c.
Referenced by form_parse_desc().
D_HEADER
#define D_HEADER 'H'
Definition at line 25 of file form_engine.c.
Referenced by form_parse_desc().
D_HELP
#define D_HELP '?'
Definition at line 24 of file form_engine.c.
Referenced by form_parse_desc().
D_QUERY
#define D_QUERY 'Q'
Definition at line 27 of file form_engine.c.
Referenced by form_parse_desc().
D_TEXT
#define D_TEXT 'T'
Definition at line 23 of file form_engine.c.
Referenced by form_parse_desc().
Function Documentation
form_calculate()
int form_calculate (Init * init)
Handle integration with an external program for calculation, allowing the user to execute a provider command and read results back into the form fields.
Parameters
init A pointer to the Init structure containing form data and state.
Returns
An integer status code indicating the next action for the form processing loop (e.g., P_CONTINUE, P_CANCEL, P_ACCEPT, P_HELP).
This function provides integration with external programs. The requirements are:
The form description file must have a line starting with 'C' to indicate that the form supports calculation.
The form description file must specify the provider command using a line starting with '!' followed by the command and its arguments.
The external program must be able to accept field data from a file, from standard input, or as command line parameters.
The external program must output the calculated field values in a format that can be read by the form (e.g., one value per line), either to a file or to standard output.
The sequence of operations is as follows:
The 'C' option causes Form to pause and display an KEY_F(5) Calculate option on the chyron.
The user can then cancel the operation by pressing KEY_F(9) or activate the calculate option by pressing KEY_F(5).
Form outputs its data to file, standard output, or as command line parameters.
Form executes the external program.
The external program processes the data and outputs the results.
Form reads the results and populates the appropriate form fields.
Form presents the user with an option to edit the data, and the sequence restarts at 1.
This function forks and executes the provider executable as a child process, creates a pipe to read the output from the provider command, reads the output, and updates the Form fields.
Definition at line 262 of file form_engine.c.
{
    int i, c, rc;
    char earg_str[MAXLEN + 1];
    char *eargv[MAXARGS];
    char file_spec[MAXLEN];
    bool loop = true;
    pid_t pid;
    int pipe_fd[2];
    form = init->form;
    wmove(form->win, form->lines - 1, 0);
    wclrtoeol(form->win);
    unset_chyron_key(form->chyron, 18);
    unset_chyron_key(form->chyron, 10);
    set_chyron_key(form->chyron, 5, "F5 Calculate", KEY_F(5));
    while (loop) {
        form_display_chyron(form);
        click_y = click_x = -1;
        tcflush(2, TCIFLUSH);
        c = xwgetch(form->win, form->chyron);
        switch (c) {
        case KEY_F(1):
            return P_HELP;
        case KEY_F(5):
            if (form->f_out_spec)
                form_write(form);
            if (form->f_provider_cmd) {
                strnz__cpy(earg_str, form->provider_cmd, MAXLEN - 1);
                for (i = 0; i < form->fcnt; i++) {
                    strnz__cat(earg_str, " ", MAXLEN - 1);
                    strnz__cat(earg_str, form->field[i]->accept_s, MAXLEN - 1);
                }
                str_to_args(eargv, earg_str, MAXARGS);
                strnz__cpy(file_spec, eargv[0], MAXLEN - 1);
                base_name(eargv[0], file_spec);
                if (pipe(pipe_fd) == -1) {
                    Perror("pipe(pipe_fd) failed in init_form");
                    return (1);
                }
                if ((pid = fork()) == -1) {
                    Perror("fork() failed in init_form");
                    return (1);
                }
                if (pid == 0) { // Child
                    close(pipe_fd[P_READ]);
                    dup2(pipe_fd[P_WRITE], STDOUT_FILENO);
                    close(pipe_fd[P_WRITE]);
                    execvp(eargv[0], eargv);
                    ssnprintf(em0, MAXLEN, "%s, line: %d", __FILE__,
                              __LINE__ - 2);
                    strnz__cpy(em1, "execvp(", MAXLEN - 1);
                    strnz__cat(em1, eargv[0], MAXLEN - 1);
                    strnz__cat(em1, ", ", MAXLEN - 1);
                    strnz__cat(em1, earg_str, MAXLEN - 1);
                    strnz__cat(em1, ")", MAXLEN - 1);
                    strerror_r(errno, em2, MAXLEN);
                    display_error(em0, em1, em2, nullptr);
                    exit(EXIT_FAILURE);
                } // Back to parent
                close(pipe_fd[P_WRITE]);
                form->in_fp = fdopen(pipe_fd[P_READ], "rb");
                form->f_in_pipe = true;
                form_read_data(form);
                close(pipe_fd[P_READ]);
                waitpid(pid, nullptr, 0);
                form_display_fields(form);
                set_chyron_key(form->chyron, 8, "F5 Edit", KEY_F(5));
                set_chyron_key(form->chyron, 10, "F10 Commit", KEY_F(10));
                continue;
            }
            break;
        case KEY_F(8):
            if (is_set_chyron_key(form->chyron, 8)) {
                loop = false;
                rc = P_CONTINUE;
                break;
            }
            continue;
        case KEY_F(9):
            loop = false;
            rc = P_CANCEL;
            break;
        case KEY_F(10):
            loop = false;
            rc = P_ACCEPT;
            break;
        case KEY_MOUSE:
            break;
        default:
            break;
        }
    }
    unset_chyron_key(form->chyron, 8);
    unset_chyron_key(form->chyron, 5);
    form_display_chyron(form);
    return rc;
}
References base_name(), click_x, click_y, display_error(), earg_str, eargv, em0, em1, em2, form, form_display_chyron(), form_display_fields(), form_read_data(), form_write(), init, is_set_chyron_key(), MAXLEN, Perror(), pipe_fd, set_chyron_key(), ssnprintf(), str_to_args(), strnz__cat(), strnz__cpy(), unset_chyron_key(), and xwgetch().
Referenced by form_engine().
form_desc_error()
int form_desc_error (int in_line_num, char * in_buf, char * em)
Handle errors encountered while parsing the form description file, providing detailed error messages that include the file name, line number, and the specific error encountered.
Parameters
in_line_num The line number in the description file where the error occurred.
in_buf The content of the line that caused the error, for context.
em A specific error message describing the nature of the error.
Returns
An integer status code indicating how the user responded to the error message (e.g., which key they pressed to acknowledge the error).
Definition at line 872 of file form_engine.c.
{
    int cmd_key;
    ssnprintf(em0, MAXLEN - 1, "%s: %s", __FILE__, em);
    ssnprintf(em1, MAXLEN - 1, "Desc file: %s, line: %d", form->mapp_spec,
              in_line_num);
    strnz__cpy(em2, in_buf, MAXLEN - 1);
    cmd_key = display_error(em0, em1, em2, nullptr);
    return cmd_key;
}
References cmd_key, display_error(), em0, em1, em2, form, MAXLEN, ssnprintf(), and strnz__cpy().
Referenced by form_parse_desc().
form_display_chyron()
void form_display_chyron (Form * form)
Display the chyron (status line) at the bottom of the form window, showing available commands and their corresponding function keys.
Parameters
form A pointer to the Form structure containing form data and state.
Definition at line 509 of file form_engine.c.
{
    compile_chyron(form->chyron);
    wattron(form->win, WA_REVERSE);
    mvwaddstr(form->win, form->lines - 1, 0, form->chyron->s);
    wattroff(form->win, WA_REVERSE);
    wclrtoeol(form->win);
    wmove(form->win, form->lines - 1, form->chyron->l);
}
References compile_chyron(), and form.
Referenced by form_accept_field(), form_calculate(), form_display_fields(), and form_end_fields().
form_display_fields()
void form_display_fields (Form * form)
Display form fields on the screen, populating field values and formatting them according to the form configuration.
Parameters
form A pointer to the Form structure containing form data and state.
Note
This function iterates through the defined form fields, formats their display values based on the specified fill character and field length, and renders them on the form window. It also updates the chyron with available commands for user interaction.
Definition at line 484 of file form_engine.c.
{
    int n;
    char fill_char = form->fill_char[0];
    for (n = 0; n < form->fcnt; n++) {
        if (form->field[n]->col + form->field[n]->len + 2 > form->cols)
            form->field[n]->len = form->cols - (form->field[n]->col + 2);
        strnfill(form->field[n]->filler_s, fill_char, form->field[n]->len);
        strnz(form->field[n]->display_s, form->field[n]->len);
        form_display_field_n(form, n);
#ifdef DEBUG
        wrefresh(form->win);
#endif
    }
    form->chyron = new_chyron();
    set_chyron_key(form->chyron, 1, "F1 Help", KEY_F(1));
    set_chyron_key(form->chyron, 9, "F9 Cancel", KEY_F(9));
    set_chyron_key(form->chyron, 10, "F10 Continue", KEY_F(10));
    compile_chyron(form->chyron);
    form_display_chyron(form);
    return;
}
References compile_chyron(), form, form_display_chyron(), form_display_field_n(), new_chyron(), set_chyron_key(), strnfill(), and strnz().
Referenced by form_calculate(), and form_display_screen().
form_display_screen()
unsigned int form_display_screen (Init * init)
Display the form on the screen, including text elements and fields, and set up the form window based on the form configuration.
Parameters
init A pointer to the Init structure containing form data and state.
Returns
0 on success, or a non-zero value if an error occurs while creating the form window or rendering the form elements.
Definition at line 434 of file form_engine.c.
{
    int n;
    char tmp_str[MAXLEN];
    form = init->form;
    form->lines = 0;
    for (n = 0; n < form->dcnt; n++)
        if (form->text[n]->line > form->lines)
            form->lines = form->text[n]->line;
    for (n = 0; n < form->fcnt; n++)
        if (form->field[n]->line > form->lines)
            form->lines = form->field[n]->line;
    form->lines += 3;
    if (form->lines > (LINES - form->begy))
        form->lines = LINES - form->begy;
    for (n = 0; n < form->fcnt; n++) {
        if (form->field[n]->line >= (form->lines - 2))
            form->fcnt = n;
    }
    form->cols += 2;
    if (form->cols > (COLS - form->begx - 3))
        form->cols = COLS - form->begx - 3;
    if (win_new(form->lines, form->cols, form->begy, form->begx, form->title,
                0)) {
        strnz__cpy(tmp_str, "kwin_new failed: ", MAXLEN - 1);
        strnz__cat(tmp_str, form->title, MAXLEN - 1);
        Perror(tmp_str);
        return (1);
    }
    // immedok(form->win, TRUE);
    form->win = win_win[win_ptr];
    form->box = win_box[win_ptr];
    for (n = 0; n < form->dcnt; n++) {
        strnz(form->text[n]->str, form->cols - 3);
        mvwaddstr(form->win, form->text[n]->line, form->text[n]->col,
                  form->text[n]->str);
#ifdef DEBUG
        wrefresh(form->win);
#endif
    }
    form_display_fields(form);
    return 0;
}
References form, form_display_fields(), init, MAXLEN, Perror(), strnz(), strnz__cat(), strnz__cpy(), tmp_str, win_box, win_new(), win_ptr, and win_win.
Referenced by form_engine().
form_end_fields()
int form_end_fields (Init * init)
Handle post-processing after field entry, allowing user to edit data, execute a provider command, or write data to an output file.
Parameters
init A pointer to the Init structure containing form data and state.
Returns
An integer status code indicating the next action for the form processing loop (e.g., P_CONTINUE, P_CANCEL, P_ACCEPT, P_HELP).
Definition at line 180 of file form_engine.c.
{
    bool loop = true;
    int c, rc;
    click_y = click_x = -1;
    form = init->form;
    wmove(form->win, form->lines - 1, 0);
    wclrtoeol(form->win);
    unset_chyron_key(form->chyron, 18);
    set_chyron_key(form->chyron, 8, "F8 Edit", KEY_F(8));
    set_chyron_key(form->chyron, 10, "F10 Commit", KEY_F(10));
    rc = -1;
    while (loop) {
        if (rc == -1) {
            form_display_chyron(form);
            tcflush(2, TCIFLUSH);
            c = xwgetch(form->win, form->chyron);
        }
        switch (c) {
        case KEY_F(1):
            return P_HELP;
        case KEY_F(8):
            if (is_set_chyron_key(form->chyron, 8)) {
                loop = false;
                rc = P_CONTINUE;
                break;
            }
            continue;
        case KEY_F(9):
            loop = false;
            rc = P_CANCEL;
            break;
        case KEY_F(10):
            loop = false;
            rc = P_ACCEPT;
            break;
        case KEY_MOUSE:
            continue;
        default:
            break;
        }
    }
    unset_chyron_key(form->chyron, 8);
    form_display_chyron(form);
    return rc;
}
References click_x, click_y, form, form_display_chyron(), init, is_set_chyron_key(), set_chyron_key(), unset_chyron_key(), and xwgetch().
Referenced by form_engine().
form_engine()
int form_engine (Init * init)
Form main processing loop.
Parameters
init A pointer to the Init structure containing form data and state.
Returns
0 on successful completion, or a non-zero value if the user cancels the form or if an error occurs during processing.
Parse the form description file to populate the form data structure.
Read any initial data for the form fields from a specified input source.
Display the form on the screen with the initial field values.
Enter a loop to handle user input for field entry, calculation, help, and cancellation: a. If the user selects the accept action, perform any necessary calculations or post-processing, and then either return to field entry or exit the loop if the form is accepted. b. If the user selects the help action, display the help screen and return to the form after the user exits the help screen. c. If the user selects the cancel action, exit the loop and return a cancel status.
Definition at line 106 of file form_engine.c.
{
    char tmp_str[MAXLEN];
    int form_action;
    form = init->form;
    if (form == nullptr) {
        Perror("FORM: form data structure is nullptr");
    }
    if (form_parse_desc(form)) {
        destroy_form(init);
        return 0;
    }
    form_read_data(form);
    form_display_screen(init);
    form->fidx = 0;
    form_action = 0;
    while (1) {
        if (form_action == 0 || form_action == P_CONTINUE)
            form_action = form_enter_fields(form);
        switch (form_action) {
        case P_ACCEPT:
            if (form->f_calculate)
                form_action = form_calculate(init);
            else
                form_action = form_end_fields(init);
            if (form_action == P_HELP || form_action == P_CANCEL ||
                form_action == P_CONTINUE || form_action == P_END)
                continue;
            if (form_action == P_ACCEPT) {
                form_action = P_END;
                continue;
            }
            break;
        case P_END:
            if (form->f_out_spec || form->out_spec[0] != '\0')
                form_write(form);
            if (form->f_receiver_cmd) {
                form_exec_cmd(form);
                form_action = P_CONTINUE;
                continue;
            }
            return 0;
        case P_HELP:
            eargv[0] = strdup("mview");
            strnz__cpy(tmp_str, "~/menuapp/help/form.help", MAXLEN - 1);
            expand_tilde(tmp_str, MAXLEN - 1);
            eargv[1] = strdup(tmp_str);
            eargv[2] = nullptr;
            eargc = 2;
            zero_opt_args(init);
            parse_opt_args(init, eargc, eargv);
            init->lines = 30;
            init->cols = 60;
            init->begy = menu->begy + 1;
            init->begx = menu->begx + 4;
            strnz__cpy(init->title, "Form Help", MAXLEN - 1);
            mview(init, eargc, eargv);
            restore_wins();
            form_action = P_CONTINUE;
            break;
        case P_CANCEL:
            return P_CANCEL;
        default:
            form_action = P_CONTINUE;
            break;
        }
    }
    return 0;
}
References destroy_form(), eargc, eargv, expand_tilde(), form, form_calculate(), form_display_screen(), form_end_fields(), form_enter_fields(), form_exec_cmd(), form_parse_desc(), form_read_data(), form_write(), init, MAXLEN, menu, mview(), parse_opt_args(), Perror(), restore_wins(), strnz__cpy(), tmp_str, and zero_opt_args().
Referenced by init_form().
form_enter_fields()
int form_enter_fields (Form * form)
Handle user input for field entry, allowing navigation between fields and looping until an exit action is selected.
Parameters
form A pointer to the Form structure containing form data and state.
Returns
An integer status code indicating the next action for the form processing loop (e.g., P_ACCEPT, P_HELP, P_CALC, P_CANCEL).
Note
This function manages user input for field entry, including navigation between fields and handling of special keys for accepting, canceling, requesting help, or performing calculations. The function loops until the user selects an exit action (e.g., accept or cancel).
Definition at line 369 of file form_engine.c.
{
    if (form->fidx < 0)
        return (-1);
    while (1) {
        cmd_key = form_accept_field(form);
        wrefresh(form->win);
        switch (cmd_key) {
        case KEY_F(10):
            return (P_ACCEPT);
        case KEY_F(1):
            return (P_HELP);
        case KEY_F(5):
            if (form->f_calculate)
                return (P_CALC);
            break;
        case KEY_F(9):
            return (P_CANCEL);
        case KEY_UP:
            if (form->fidx != 0)
                form->fidx--;
            break;
        case '\r':
        case KEY_ENTER:
            if (form->fidx < form->fcnt - 1)
                form->fidx++;
            else if (form->fidx == form->fcnt - 1)
                return (P_ACCEPT);
            break;
        case KEY_DOWN:
            if (form->fidx < form->fcnt - 1)
                form->fidx++;
            else if (form->fidx == form->fcnt - 1)
                return (P_ACCEPT);
            break;
        case KEY_MOUSE:
            break;
        default:
            break;
        }
    }
}
References cmd_key, form, and form_accept_field().
Referenced by form_engine().
form_exec_cmd()
int form_exec_cmd (Form * form)
Execute a provider command specified in the form description file, passing form field values as arguments, and optionally redirecting output to a file.
Parameters
form A pointer to the Form structure containing form data and state.
Returns
0 on success, or a non-zero value if an error occurs while constructing or executing the command.
Definition at line 790 of file form_engine.c.
{
    char earg_str[MAXLEN + 1];
    int i;
    strnz__cpy(earg_str, form->receiver_cmd, MAXLEN - 1);
    for (i = 0; i < form->fcnt; i++) {
        strnz__cat(earg_str, " ", MAXLEN - 1);
        strnz__cat(earg_str, form->field[i]->accept_s, MAXLEN - 1);
    }
    if (form->f_out_spec && form->f_calculate) {
        strnz__cat(earg_str, " >", MAXLEN - 1);
        strnz__cat(earg_str, form->out_spec, MAXLEN - 1);
    }
    shell(earg_str);
    return 0;
}
References earg_str, form, MAXLEN, shell(), strnz__cat(), and strnz__cpy().
Referenced by form_engine().
form_parse_desc()
int form_parse_desc (Form * form)
Parse the form description file to populate the Form data structure with field definitions, text elements, and other configuration specified in the description file.
Parameters
form A pointer to the Form structure containing form data and state.
Returns
0 on success, or a non-zero value if an error occurs while parsing the description file (e.g., file not found, invalid format, missing directives).
Definition at line 524 of file form_engine.c.
{
    FILE *form_desc_fp;
    char *token;
    char *s;
    int cols = 0;
    int i, l;
    int in_line_num = 0;
    char in_buf[BUFSIZ];
    char tmp_buf[BUFSIZ];
    char *tmp_buf_p;
    char tmp_str[BUFSIZ];
    char delim[5];
    char directive;
    form_desc_fp = fopen(form->mapp_spec, "r");
    if (form_desc_fp == nullptr) {
        ssnprintf(em0, MAXLEN - 1, "%s, line: %d", __FILE__, __LINE__ - 2);
        strnz__cpy(em1, "fopen ", MAXLEN - 1);
        strnz__cat(em1, form->mapp_spec, MAXLEN - 1);
        strerror_r(errno, em2, MAXLEN);
        display_error(em0, em1, em2, nullptr);
        return (1);
    }
    for (i = 0; i < MAXFIELDS; i++) {
        form->field[i] = (Field *)calloc(1, sizeof(Field));
        if (!form->field[i]) {
            sprintf(tmp_str, "FORM: calloc failed for fields");
            abend(EXIT_FAILURE, tmp_str);
        }
    }
    for (i = 0; i < MAXFIELDS; i++) {
        form->text[i] = (Text *)calloc(1, sizeof(Text));
        if (!form->field[i]) {
            sprintf(tmp_str, "FORM: calloc failed for text");
            abend(EXIT_FAILURE, tmp_str);
        }
    }
    form->didx = 0;
    form->fidx = 0;
    form->fcnt = 0;
    form->cols = 34;
    while ((fgets(in_buf, MAXLEN, form_desc_fp)) != nullptr) {
        s = in_buf;
        in_line_num++;
        l = trim(in_buf);
        if (l == 0)
            continue;
        if (*s == D_COMMENT)
            continue;
        delim[0] = '\n';
        delim[1] = in_buf[1];
        delim[2] = '\0';
        strnz__cpy(tmp_buf, in_buf, MAXLEN - 1);
        tmp_buf_p = tmp_buf;
        if (!(token = strtok(tmp_buf_p, delim))) {
            continue;
        }
        directive = *token;
        switch ((int)directive) {
        case D_COMMENT:
            break;
        case D_CALC:
            form->f_calculate = true;
            break;
        case D_QUERY:
            form->f_query = true;
            break;
        case D_CMD:
            if (!(token = strtok(nullptr, delim))) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: receiver_cmd delimiter");
                continue;
            }
            strnz__cpy(form->receiver_cmd, token, MAXLEN - 1);
            break;
        case D_HELP:
            if (!(token = strtok(nullptr, delim))) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: help_spec delimiter");
            }
            strnz__cpy(form->help_spec, token, MAXLEN - 1);
            break;
        case D_FIELD:
            if (form->field[form->fidx] == nullptr) {
                sprintf(tmp_str, "FORM: calloc failed for fields");
                abend(EXIT_FAILURE, tmp_str);
            }
            if (!(token = strtok(nullptr, delim))) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: line number delimiter");
                return 1;
            }
            form->field[form->fidx]->line = atoi(token);
            if (form->field[form->fidx]->line < 0 ||
                form->field[form->fidx]->line >= MAXFIELDS) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: invalid line number");
                return 1;
            }
            if (!(token = strtok(nullptr, delim))) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: column number delimiter");
                return 1;
            }
            form->field[form->fidx]->col = atoi(token);
            if (form->field[form->fidx]->col < 0 ||
                form->field[form->fidx]->col >= TBL_COLS) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: invalid column number");
                break;
            }
            if (!(token = strtok(nullptr, delim))) {
                strnz__cpy(tmp_str, in_buf, MAXLEN - 1);
                form_desc_error(in_line_num, tmp_str, "FORM: length delimiter");
                break;
            }
            form->field[form->fidx]->len = atoi(token);
            if (form->field[form->fidx]->len < 0 ||
                form->field[form->fidx]->len > TBL_COLS) {
                form_desc_error(in_line_num, in_buf, "FORM: invalid length");
                break;
            }
            if (!(token = strtok(nullptr, delim))) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: validation code delimiter");
                break;
            }
            form->field[form->fidx]->ff = -1;
            for (i = 0; i < FF_INVALID; i++) {
                str_to_lower(token);
                str_to_lower(ff_tbl[i]);
                if (!strcmp(token, ff_tbl[i])) {
                    form->field[form->fidx]->ff = i;
                    break;
                }
            }
            if (form->field[form->fidx]->ff < 0 ||
                form->field[form->fidx]->ff >= FF_INVALID) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: invalid format code");
                break;
            }
            cols =
                form->field[form->fidx]->col + form->field[form->fidx]->len + 1;
            if (cols > form->cols)
                form->cols = cols;
            form->fidx++;
            form->fcnt = form->fidx;
            break;
        case D_TEXT:
            if (form->text[form->didx] == nullptr) {
                sprintf(tmp_str, "FORM: calloc failed for text");
                abend(EXIT_FAILURE, tmp_str);
            }
            if (!(token = strtok(nullptr, delim))) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: line number delimiter");
                break;
            }
            form->text[form->didx]->line = atoi(token);
            if (form->text[form->didx]->line < 0 ||
                form->text[form->didx]->line >= MAXFIELDS) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: invalid line number");
                break;
            }
            if (!(token = strtok(nullptr, delim))) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: column number delimiter");
                break;
            }
            form->text[form->didx]->col = atoi(token);
            if (form->text[form->didx]->col < 0 ||
                form->text[form->didx]->col >= TBL_COLS) {
                form_desc_error(in_line_num, in_buf,
                                "FORM: invalid column number");
                break;
            }
            if (!(token = strtok(nullptr, delim))) {
                form_desc_error(in_line_num, in_buf, "FORM: text delimiter");
                break;
            }
            strnz__cpy(form->text[form->didx]->str, token, MAXLEN - 1);
            form->text[form->didx]->len = strlen(form->text[form->didx]->str);
            if (form->text[form->didx]->len < 0 ||
                form->text[form->didx]->len > TBL_COLS) {
                form_desc_error(in_line_num, in_buf, "FORM: invalid length");
                break;
            }
            cols =
                form->text[form->didx]->col + form->text[form->didx]->len + 1;
            if (cols > form->cols)
                form->cols = cols;
            form->didx++;
            form->dcnt = form->didx;
            break;
        case D_HEADER:
            if ((token = strtok(nullptr, delim))) {
                strnz__cpy(form->title, token, MAXLEN - 1);
            }
            break;
        default:
            form_desc_error(in_line_num, in_buf, "invalid directive");
            break;
        }
    }
    fclose(form_desc_fp);
    if (form->didx < 1 && form->fidx < 1) {
        ssnprintf(em0, MAXLEN - 1, "%s, line: %d", __FILE__, __LINE__);
        ssnprintf(em1, MAXLEN - 1, "%s", "Error in description file:");
        ssnprintf(em2, MAXLEN - 1, "%s", form->mapp_spec);
        display_error(em0, em1, em2, nullptr);
        return (1);
    }
    return (0);
}
References abend(), D_CALC, D_CMD, D_COMMENT, D_FIELD, D_HEADER, D_HELP, D_QUERY, D_TEXT, display_error(), em0, em1, em2, ff_tbl, form, form_desc_error(), MAXLEN, ssnprintf(), str_to_lower(), strnz__cat(), strnz__cpy(), tmp_str, and trim().
Referenced by form_engine().
form_read_data()
int form_read_data (Form * form)
Read initial data for form fields from a specified input source, such as a file or standard input, and populate the form fields with the data.
Parameters
form A pointer to the Form structure containing form data and state.
Returns
0 on success, or a non-zero value if an error occurs while reading the data or if the specified input source is invalid or empty.
Definition at line 745 of file form_engine.c.
{
    struct stat sb;
    char in_buf[MAXLEN];
    char field[MAXLEN];
    if (!form->f_in_pipe) {
        if (form->f_in_spec && form->in_spec[0] != '\0') {
            if ((lstat(form->in_spec, &sb) == -1) || (sb.st_size == 0) ||
                ((form->in_fp = fopen(form->in_spec, "rb")) == nullptr)) {
                strnz__cat(em0, form->in_spec, MAXLEN - 1);
                // if (errno)
                // strerror_r(errno, em1, MAXLEN - 1);
                // else
                if (sb.st_size == 0)
                    strnz__cpy(em1, "File is empty", MAXLEN - 1);
                else
                    strnz__cpy(em1, "File does not exist", MAXLEN - 1);
                strnz__cpy(em2, "Fields will be blank or zero", MAXLEN - 1);
                cmd_key = display_error(em0, em1, em2, nullptr);
                if (cmd_key == KEY_F(9))
                    return (1);
            }
            if (form->in_fp == nullptr)
                return (1);
        } else
            return (0);
    }
    form->fidx = 0;
    if (form->in_fp != nullptr) {
        while ((fgets(in_buf, MAXLEN, form->in_fp)) != nullptr) {
            if (form->fidx < MAXFIELDS)
                strnz__cpy(field, in_buf, MAXLEN - 1);
            form_fmt_field(form, field);
            form->fidx++;
        }
        fclose(form->in_fp);
    }
    return (0);
}
References cmd_key, display_error(), em0, em1, em2, form, form_fmt_field(), MAXLEN, strnz__cat(), and strnz__cpy().
Referenced by form_calculate(), and form_engine().
form_usage()
void form_usage ()
Display usage information for the form, including available options and commands, to assist users in understanding how to interact with the form.
Note
This function generates a usage message based on the options defined for the form and displays it to the user, typically when they request help or when an error occurs. The usage information includes details about the form's configuration, available commands, and how to navigate and interact with the form fields.
Definition at line 858 of file form_engine.c.
                  {
    dump_opts_by_use("Form: usage: ", "..f.");
    (void)fprintf(stderr, "\n");
    Perror("press any key to continue");
}
References dump_opts_by_use(), and Perror().
form_write()
int form_write (Form * form)
Write form field values to a specified output destination, such as a file or standard output, based on the form configuration and user input.
Parameters
form A pointer to the Form structure containing form data and state.
Returns
0 on success, or a non-zero value if an error occurs while writing the data or if the specified output destination is invalid.
Definition at line 810 of file form_engine.c.
{
    int n;
    if (form->out_spec[0] == '\0' || strcmp(form->out_spec, "-") == 0 ||
        strcmp(form->out_spec, "/dev/stdout") == 0) {
        strnz__cpy(form->out_spec, "/dev/stdout", MAXLEN - 1);
        close(form->out_fd);
        form->out_fd = open(form->out_spec, O_CREAT | O_RDWR | O_TRUNC, 0644);
        if (form->out_fd == -1) {
            ssnprintf(em0, MAXLEN - 1, "%s, line: %d", __FILE__, __LINE__ - 1);
            strnz__cpy(em1, "open ", MAXLEN - 1);
            strnz__cat(em1, form->out_spec, MAXLEN - 1);
            strerror_r(errno, em2, MAXLEN);
            display_error(em0, em1, em2, nullptr);
            return (1);
        }
        dup2(form->out_fd, STDOUT_FILENO);
        form->out_fp = fdopen(STDOUT_FILENO, "w");
        form->f_out_spec = true;
        form->f_out_pipe = true;
    } else {
        if ((form->out_fp = fopen(form->out_spec, "w")) == nullptr) {
            ssnprintf(em0, MAXLEN - 1, "%s, line: %d", __FILE__, __LINE__ - 1);
            strerror_r(errno, em2, MAXLEN);
            display_error(em0, em1, em2, nullptr);
            return (1);
        }
    }
    if (form->out_fp == nullptr) {
        ssnprintf(em0, MAXLEN - 1, "%s, line: %d", __FILE__, __LINE__ - 1);
        strnz__cpy(em1, "fopen ", MAXLEN - 1);
        strnz__cat(em1, form->out_spec, MAXLEN - 1);
        strerror_r(errno, em2, MAXLEN);
        display_error(em0, em1, em2, nullptr);
        return (1);
    }
    for (n = 0; n < form->fcnt; n++)
        fprintf(form->out_fp, "%s\n", form->field[n]->accept_s);
    if (form->out_fp != nullptr)
        fclose(form->out_fp);
    return (0);
}
References display_error(), em0, em1, em2, form, MAXLEN, ssnprintf(), strnz__cat(), and strnz__cpy().
Referenced by form_calculate(), and form_engine().
form_yx_to_fidx()
int form_yx_to_fidx (Form * form, int y, int x)
Definition at line 419 of file form_engine.c.
{
    for (int i = 0; i < form->fcnt; i++) {
        if (y == form->field[i]->line && x >= form->field[i]->col &&
            x < form->field[i]->col + form->field[i]->len) {
            return i;
        }
    }
    return -1; // No field found at the given coordinates
}
References form.
Referenced by form_accept_field().
init_form()
int init_form (Init * init, int argc, char ** argv, int begy, int begx)
Initialize form data structure and parse description file.
Parameters
init A pointer to the Init structure containing form data and state.
argc The number of command line arguments passed to the form.
argv The array of command line arguments passed to the form.
begy The y-coordinate for the top-left corner of the form window.
begx The x-coordinate for the top-left corner of the form window.
Returns
0 on success, or a non-zero value if an error occurs during
Definition at line 53 of file form_engine.c.
{
    int rc;
    char tmp_str[MAXLEN];
    if (init->form != nullptr)
        destroy_form(init);
    init->form = new_form(init, argc, argv, begy, begx);
    form = init->form;
    if (!form->f_mapp_spec) {
        if (form->mapp_spec[0] == '\0') {
            rc = Perror("Error: No form specification file given");
        } else {
            strnz__cpy(tmp_str, "form->mapp_spec: ", MAXLEN - 1);
            strnz__cat(tmp_str, form->mapp_spec, MAXLEN - 1);
            strnz__cat(tmp_str, " not found", MAXLEN - 1);
            rc = Perror(tmp_str);
        }
        return rc;
    }
    if (begy != 0)
        form->begy = begy;
    if (begx != 0)
        form->begx = begx;
    if ((form->f_in_spec && (form->in_spec[0] == '\0')) ||
        (strcmp(form->in_spec, "-") == 0) ||
        strcmp(form->in_spec, "/dev/stdin") == 0) {
        strnz__cpy(form->in_spec, "/dev/stdin", MAXLEN - 1);
        form->f_in_pipe = true;
    }
    if (form->title[0] == '\0')
        strnz__cpy(form->title, form->in_spec, MAXLEN - 1);
    rc = form_engine(init);
    if (form->win)
        win_del();
    destroy_form(init);
    return rc;
}
References destroy_form(), form, form_engine(), init, MAXLEN, new_form(), Perror(), strnz__cat(), strnz__cpy(), tmp_str, and win_del().
Referenced by enter_file_spec(), main(), and menu_cmd_processor().