C-Menu: sig.c File Reference
sig.c File Reference
signal handling for interrupt signals
#include <cm.h>
#include <signal.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <termios.h>
#include <unistd.h>
Functions
void sig_dfl_mode ()
Set signal handlers to default behavior.
void sig_prog_mode ()
Set up signal handlers for interrupt signals.
void signal_handler (int sig_num)
Signal handler for interrupt signals.
bool handle_signal (int sig_num)
Handle received signals and prompt user for action.
Variables
volatile sig_atomic_t sig_received = 0
bool f_curses_open = false
Detailed Description
signal handling for interrupt signals
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file sig.c.
Function Documentation
handle_signal()
bool handle_signal (int sig_num)
Handle received signals and prompt user for action.
Definition at line 105 of file sig.c.
References em0, em1, em2, f_curses_open, MAXLEN, restore_shell_tioctl(), sig_received, ssnprintf(), and strnz__cpy().
Referenced by xwgetch().
sig_dfl_mode()
void sig_dfl_mode ()
Set signal handlers to default behavior.
Examples
/usr/local/src/cmenu/src/enterstr.c.
Definition at line 23 of file sig.c.
Referenced by abend(), destroy_curses(), fork_exec(), main(), and user_end().
sig_prog_mode()
void sig_prog_mode ()
Set up signal handlers for interrupt signals.
Upon receiving an interrupt signal (SIGINT, SIGTERM, SIGQUIT), the program will prompt the user to either exit the program or continue execution. If the user chooses to exit, a confirmation prompt will be displayed. If the user opts to continue, the program will resume normal operation.
Examples
/usr/local/src/cmenu/src/enterstr.c.
Definition at line 42 of file sig.c.
References abend(), and signal_handler().
Referenced by exec_objects(), fork_exec(), init_pick(), and main().
signal_handler()
void signal_handler (int sig_num)
Signal handler for interrupt signals.
Definition at line 72 of file sig.c.
References shell_tioctl, and sig_received.
Referenced by sig_prog_mode().
Variable Documentation
f_curses_open
bool f_curses_open = false
curses mode is active
Definition at line 20 of file sig.c.
Referenced by destroy_curses(), display_error(), handle_signal(), open_curses(), and Perror().
sig_received
volatile sig_atomic_t sig_received = 0
Definition at line 18 of file sig.c.
Referenced by handle_signal(), handle_signal(), signal_handler(), and xwgetch().