var dir_c08f3ec0691ba02b6584d24d99d5c274 =
[
    [ "box.c", "d2/dd1/box_8c.html", "d2/dd1/box_8c" ],
    [ "box2.c", "d3/d58/box2_8c.html", "d3/d58/box2_8c" ],
    [ "ckeys.c", "d8/d13/ckeys_8c.html", "d8/d13/ckeys_8c" ],
    [ "colors.c", "d3/d13/colors_8c.html", "d3/d13/colors_8c" ],
    [ "curskeys.c", "d2/d51/notcurses_2curskeys_8c.html", "d2/d51/notcurses_2curskeys_8c" ],
    [ "dwin.c", "d8/de8/notcurses_2dwin_8c.html", "d8/de8/notcurses_2dwin_8c" ],
    [ "dxwgetch.c", "df/dce/dxwgetch_8c.html", "df/dce/dxwgetch_8c" ],
    [ "example.c", "d6/dac/example_8c.html", "d6/dac/example_8c" ],
    [ "floodfill.c", "d4/d20/floodfill_8c.html", "d4/d20/floodfill_8c" ],
    [ "fmt_line.c", "d0/d49/fmt__line_8c.html", "d0/d49/fmt__line_8c" ],
    [ "highlight.c", "d4/d89/highlight_8c.html", "d4/d89/highlight_8c" ],
    [ "init_view.c", "d0/de9/notcurses_2init__view_8c.html", "d0/de9/notcurses_2init__view_8c" ],
    [ "input_loop.c", "dc/d74/input__loop_8c.html", "dc/d74/input__loop_8c" ],
    [ "inspect_cell.c", "d9/dda/inspect__cell_8c.html", "d9/dda/inspect__cell_8c" ],
    [ "multimedia.c", "da/d1d/multimedia_8c.html", "da/d1d/multimedia_8c" ],
    [ "nc.h", "dc/d9a/nc_8h.html", "dc/d9a/nc_8h" ],
    [ "not_input.c", "d2/d26/not__input_8c.html", "d2/d26/not__input_8c" ],
    [ "parse_menu_desc.c", "d2/d24/notcurses_2parse__menu__desc_8c.html", "d2/d24/notcurses_2parse__menu__desc_8c" ],
    [ "redraw.c", "df/d55/redraw_8c.html", "df/d55/redraw_8c" ],
    [ "render.c", "dc/dcf/render_8c.html", "dc/dcf/render_8c" ],
    [ "render_menu.c", "d4/d02/render__menu_8c.html", "d4/d02/render__menu_8c" ],
    [ "resize.c", "d7/df1/resize_8c.html", "d7/df1/resize_8c" ],
    [ "ui_draw_with_channels.c", "d2/d8b/ui__draw__with__channels_8c.html", "d2/d8b/ui__draw__with__channels_8c" ],
    [ "ui_mvaddcell.c", "df/d8a/ui__mvaddcell_8c.html", "df/d8a/ui__mvaddcell_8c" ],
    [ "wattron.c", "d2/dae/wattron_8c.html", "d2/dae/wattron_8c" ]
];