var searchData=
[
  ['y_0',['y',['../d4/dfe/a02688.html#a2fde63e6a8fc2c5c997c4328f6f17bbf',1,'Pick::y'],['../dd/dee/a02700.html#a672605a27ab0de7bb229dab49a9b892a',1,'UiEvent::y'],['../d7/deb/a02724.html#a03824f3c5073f5bde5ad401eb9dcc449',1,'UiRect::y'],['../d0/d1f/a02748.html#a1a9a0c1c2215f1fb65020b6882050056',1,'UiSurfaceMeta::y']]],
  ['y_5foffset_1',['y_offset',['../d4/dfe/a02688.html#aec7435ce89bc03350e81754b70e9da1c',1,'Pick']]],
  ['yellow_2',['yellow',['../d9/d4d/a02840.html#a5bffe7b9a0c00ae106a9379c9606c127',1,'SIO']]],
  ['you_20can_20find_20the_20grammars_20on_20the_20tree_20sitter_20github_20page_3a_20tree_20sitter_20grammars_3',['- In addition to tree-sitter-cli, you will also need to have the tree-sitter grammars for the languages you want to highlight installed. You can find the grammars on the tree-sitter GitHub page: &lt;a href=&quot;https://github.com/tree-sitter-grammars&quot;&gt;Tree-Sitter Grammars&lt;/a&gt;',['../da/dbe/a03091.html#autotoc_md--in-addition-to-tree-sitter-cli-you-will-also-need-to-have-the-tree-sitter-grammars-for-the-languages-you-want-to-highlight-installed-you-can-find-the-grammars-on-the-tree-sitter-github-page-tree-sitter-grammarshttpsgithubcomtree-sitter-grammars',1,'']]],
  ['you_20can_20t_20stop_20typing_20vi_4',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../db/dbc/a03114.html#if-you-cant-stop-typing-vi',1,'']]],
  ['you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_5',['you encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../d7/d54/a03089.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../dc/d45/a03085.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d9/d5e/a03086.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d4/d6e/a03099.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['you_20want_20to_20highlight_20installed_20you_20can_20find_20the_20grammars_20on_20the_20tree_20sitter_20github_20page_3a_20tree_20sitter_20grammars_6',['- In addition to tree-sitter-cli, you will also need to have the tree-sitter grammars for the languages you want to highlight installed. You can find the grammars on the tree-sitter GitHub page: &lt;a href=&quot;https://github.com/tree-sitter-grammars&quot;&gt;Tree-Sitter Grammars&lt;/a&gt;',['../da/dbe/a03091.html#autotoc_md--in-addition-to-tree-sitter-cli-you-will-also-need-to-have-the-tree-sitter-grammars-for-the-languages-you-want-to-highlight-installed-you-can-find-the-grammars-on-the-tree-sitter-github-page-tree-sitter-grammarshttpsgithubcomtree-sitter-grammars',1,'']]],
  ['you_20will_20also_20need_20to_20have_20the_20tree_20sitter_20grammars_20for_20the_20languages_20you_20want_20to_20highlight_20installed_20you_20can_20find_20the_20grammars_20on_20the_20tree_20sitter_20github_20page_3a_20tree_20sitter_20grammars_7',['- In addition to tree-sitter-cli, you will also need to have the tree-sitter grammars for the languages you want to highlight installed. You can find the grammars on the tree-sitter GitHub page: &lt;a href=&quot;https://github.com/tree-sitter-grammars&quot;&gt;Tree-Sitter Grammars&lt;/a&gt;',['../da/dbe/a03091.html#autotoc_md--in-addition-to-tree-sitter-cli-you-will-also-need-to-have-the-tree-sitter-grammars-for-the-languages-you-want-to-highlight-installed-you-can-find-the-grammars-on-the-tree-sitter-github-page-tree-sitter-grammarshttpsgithubcomtree-sitter-grammars',1,'']]],
  ['your_20changes_8',['2. Make Your Changes',['../df/d92/a03097.html#autotoc_md2-make-your-changes',1,'']]],
  ['your_20environment_9',['Your Environment',['../df/d92/a03097.html#autotoc_md1-set-up-your-environment',1,'1. Set Up Your Environment'],['../dd/d50/a03088.html#set-up-your-environment',1,'Set Up Your Environment']]],
  ['your_20terminal_20emulator_10',['Your Terminal Emulator',['../d9/d5e/a03086.html#customize-your-terminal-emulator',1,'Customize Your Terminal Emulator'],['../d4/d6e/a03099.html#customize-your-terminal-emulator-1',1,'Customize Your Terminal Emulator']]],
  ['youtube_20in_20firefox_11',['Youtube (in Firefox)',['../da/dbe/a03091.html#youtube-in-firefox',1,'']]],
  ['yyyy_12',['yyyy',['../d4/d61/a02588.html#ae1211f3e54dfb60f12092c58ff86f344',1,'Date']]]
];
