var searchData=
[
  ['y_0',['y',['../dc/dcb/a02648.html#a03824f3c5073f5bde5ad401eb9dcc449',1,'UiRect::y'],['../d0/d9f/a02672.html#a1a9a0c1c2215f1fb65020b6882050056',1,'UiSurfaceMeta::y'],['../d0/d5a/a02784.html#a2fde63e6a8fc2c5c997c4328f6f17bbf',1,'Pick::y']]],
  ['y_5foffset_1',['y_offset',['../d0/d5a/a02784.html#aec7435ce89bc03350e81754b70e9da1c',1,'Pick']]],
  ['yellow_2',['yellow',['../df/d25/a02764.html#a5bffe7b9a0c00ae106a9379c9606c127',1,'SIO']]],
  ['you_20can_20find_20the_20grammars_20on_20the_20tree_20sitter_20github_20page_3a_20tree_20sitter_20grammars_3',['- In addition to tree-sitter-cli, you will also need to have the tree-sitter grammars for the languages you want to highlight installed. You can find the grammars on the tree-sitter GitHub page: &lt;a href=&quot;https://github.com/tree-sitter-grammars&quot;&gt;Tree-Sitter Grammars&lt;/a&gt;',['../d4/d47/a03050.html#autotoc_md--in-addition-to-tree-sitter-cli-you-will-also-need-to-have-the-tree-sitter-grammars-for-the-languages-you-want-to-highlight-installed-you-can-find-the-grammars-on-the-tree-sitter-github-page-tree-sitter-grammarshttpsgithubcomtree-sitter-grammars',1,'']]],
  ['you_20can_20t_20stop_20typing_20vi_4',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../dd/d7c/a03072.html#if-you-cant-stop-typing-vi',1,'']]],
  ['you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_5',['you encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../d7/d8c/a03049.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d1/df6/a03045.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d2/df1/a03057.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d1/dff/a03046.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['you_20want_20to_20highlight_20installed_20you_20can_20find_20the_20grammars_20on_20the_20tree_20sitter_20github_20page_3a_20tree_20sitter_20grammars_6',['- In addition to tree-sitter-cli, you will also need to have the tree-sitter grammars for the languages you want to highlight installed. You can find the grammars on the tree-sitter GitHub page: &lt;a href=&quot;https://github.com/tree-sitter-grammars&quot;&gt;Tree-Sitter Grammars&lt;/a&gt;',['../d4/d47/a03050.html#autotoc_md--in-addition-to-tree-sitter-cli-you-will-also-need-to-have-the-tree-sitter-grammars-for-the-languages-you-want-to-highlight-installed-you-can-find-the-grammars-on-the-tree-sitter-github-page-tree-sitter-grammarshttpsgithubcomtree-sitter-grammars',1,'']]],
  ['you_20will_20also_20need_20to_20have_20the_20tree_20sitter_20grammars_20for_20the_20languages_20you_20want_20to_20highlight_20installed_20you_20can_20find_20the_20grammars_20on_20the_20tree_20sitter_20github_20page_3a_20tree_20sitter_20grammars_7',['- In addition to tree-sitter-cli, you will also need to have the tree-sitter grammars for the languages you want to highlight installed. You can find the grammars on the tree-sitter GitHub page: &lt;a href=&quot;https://github.com/tree-sitter-grammars&quot;&gt;Tree-Sitter Grammars&lt;/a&gt;',['../d4/d47/a03050.html#autotoc_md--in-addition-to-tree-sitter-cli-you-will-also-need-to-have-the-tree-sitter-grammars-for-the-languages-you-want-to-highlight-installed-you-can-find-the-grammars-on-the-tree-sitter-github-page-tree-sitter-grammarshttpsgithubcomtree-sitter-grammars',1,'']]],
  ['your_20changes_8',['2. Make Your Changes',['../df/d0c/a03055.html#autotoc_md2-make-your-changes',1,'']]],
  ['your_20environment_9',['Your Environment',['../df/d0c/a03055.html#autotoc_md1-set-up-your-environment',1,'1. Set Up Your Environment'],['../dc/d92/a03048.html#set-up-your-environment',1,'Set Up Your Environment']]],
  ['your_20terminal_20emulator_10',['Your Terminal Emulator',['../d2/df1/a03057.html#customize-your-terminal-emulator',1,'Customize Your Terminal Emulator'],['../d1/dff/a03046.html#customize-your-terminal-emulator-1',1,'Customize Your Terminal Emulator']]],
  ['youtube_20in_20firefox_11',['Youtube (in Firefox)',['../d4/d47/a03050.html#youtube-in-firefox',1,'']]],
  ['yyyy_12',['yyyy',['../dc/d32/a02556.html#ae1211f3e54dfb60f12092c58ff86f344',1,'Date']]]
];
