var searchData=
[
  ['early_20life_0',['Early Life',['../dc/dc0/a03087.html#early-life',1,'']]],
  ['edit_20c_20files_20in_20current_20directory_1',['Edit c Files in Current Directory',['../d9/d5f/a03109.html#edit-c-files-in-current-directory',1,'Edit .c Files in Current Directory'],['../d9/dc2/a03106.html#edit-c-files-in-current-directory-1',1,'Edit .c Files in Current Directory']]],
  ['edit_20c_20menu_20description_20files_2',['Edit C-Menu Description Files',['../da/dbe/a03091.html#edit-c-menu-description-files',1,'']]],
  ['editing_3',['Form for Data Entry and Editing',['../da/d4a/a03107.html#form-for-data-entry-and-editing',1,'']]],
  ['editor_4',['Editor',['../da/d4a/a03107.html#example-manual-page-using-editor',1,'Example Manual Page Using Editor'],['../da/d4a/a03107.html#log-file-with-editor',1,'Log File With Editor']]],
  ['editor_5',['Form field editor',['../d7/d54/a03089.html#form-field-editor',1,'']]],
  ['editor_20loop_6',['editor loop',['../db/dab/a02567.html#line-editor-loop',1,'Line editor loop'],['../db/dab/a02567.html#line-editor-loop-1',1,'Line editor loop']]],
  ['editor_20settings_7',['Terminal and Editor Settings',['../db/dbc/a03114.html#terminal-and-editor-settings',1,'']]],
  ['elapsed_20extremely_20fast_8',['fd - 0.16 elapsed - &quot;Extremely Fast&quot;',['../index.html#fd---016-elapsed---extremely-fast',1,'']]],
  ['elapsed_20ridiculously_20fast_9',['lf - 0.10 elapsed - &quot;Ridiculously Fast&quot;',['../index.html#lf---010-elapsed---ridiculously-fast',1,'']]],
  ['elapsed_20very_20fast_10',['find - 0.82 elapsed - &quot;Very Fast&quot;',['../index.html#find---082-elapsed---very-fast',1,'']]],
  ['elements_20of_20c_20menu_11',['Elements of C-Menu',['../da/d4a/a03107.html#elements-of-c-menu',1,'']]],
  ['emulator_12',['Emulator',['../d9/d5e/a03086.html#customize-your-terminal-emulator',1,'Customize Your Terminal Emulator'],['../d4/d6e/a03099.html#customize-your-terminal-emulator-1',1,'Customize Your Terminal Emulator']]],
  ['encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_13',['encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../d7/d54/a03089.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../dc/d45/a03085.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d9/d5e/a03086.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d4/d6e/a03099.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['enforcement_14',['Enforcement',['../de/d98/a03096.html#enforcement',1,'']]],
  ['enhancements_15',['1.1.0 - Feature Enhancements',['../de/dd1/a03112.html#autotoc_md110---feature-enhancements',1,'']]],
  ['enjoy_20using_20c_20menu_20if_20you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_16',['Enjoy using C Menu If you encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../d7/d54/a03089.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../dc/d45/a03085.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d9/d5e/a03086.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d4/d6e/a03099.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['enterchr_17',['enterchr',['../d2/d8b/a03090.html#enterchr',1,'']]],
  ['entered_20and_20the_20file_20was_20highlighted_20with_20tudyx_20s_20tree_20sitter_20log_20grammar_20which_20is_20available_20at_20tudyx_20s_20log_20grammar_18',['A search term, &quot;transport&quot; was entered and the file was highlighted with Tudyx&apos;s tree-sitter-log grammar, which is available at &lt;a href=&quot;https://github.com/Tudyx/tree-sitter-log.git&quot;&gt;Tudyx&apos;s log grammar&lt;/a&gt;',['../da/dbe/a03091.html#a-search-term-transport-was-entered-and-the-file-was-highlighted-with-tudyxs-tree-sitter-log-grammar-which-is-available-at-tudyxs-log-grammarhttpsgithubcomtudyxtree-sitter-loggit',1,'']]],
  ['enterstr_19',['enterstr',['../d2/d8b/a03090.html#enterstr',1,'']]],
  ['entry_20and_20editing_20',['Form for Data Entry and Editing',['../da/d4a/a03107.html#form-for-data-entry-and-editing',1,'']]],
  ['environment_21',['Environment',['../df/d92/a03097.html#autotoc_md1-set-up-your-environment',1,'1. Set Up Your Environment'],['../dd/d50/a03088.html#set-up-your-environment',1,'Set Up Your Environment']]],
  ['environment_20configuration_22',['Environment Configuration',['../d0/d9b/a03103.html#environment-configuration',1,'']]],
  ['environment_20variables_23',['Environment Variables',['../d7/d54/a03089.html#c-menu-environment-variables',1,'C-Menu Environment Variables'],['../db/dbc/a03114.html#helpful-c-menu-environment-variables',1,'Helpful C-Menu Environment Variables'],['../db/dbc/a03114.html#system-specific-environment-variables',1,'System Specific Environment Variables']]],
  ['escape_20delay_24',['Curses Escape Delay',['../db/dbc/a03114.html#curses-escape-delay',1,'']]],
  ['etc_25',['Drop-down and Pop-up Menus, Forms, Pickers, Views, Ckeys, etc',['../d5/d3a/a03100.html#drop-down-and-pop-up-menus-forms-pickers-views-ckeys-etc',1,'']]],
  ['example_26',['C-Menu configuration file example',['../d7/d54/a03089.html#c-menu-configuration-file-example',1,'']]],
  ['example_20application_20menu_27',['Example Application Menu',['../d9/dc2/a03106.html#example-application-menu',1,'']]],
  ['example_20applications_20menu_28',['C-Menu Example Applications Menu',['../d7/d54/a03089.html#c-menu-example-applications-menu',1,'']]],
  ['example_20manual_20page_29',['Example Manual Page',['../da/d4a/a03107.html#example-manual-page',1,'']]],
  ['example_20manual_20page_20using_20editor_30',['Example Manual Page Using Editor',['../da/d4a/a03107.html#example-manual-page-using-editor',1,'']]],
  ['example_20programs_31',['C-Menu Trivial Example Programs',['../d2/d8b/a03090.html#c-menu-trivial-example-programs',1,'']]],
  ['example_20terminal_20configurations_32',['Example Terminal Configurations',['../d9/d5e/a03086.html#example-terminal-configurations',1,'Example Terminal Configurations'],['../d4/d6e/a03099.html#example-terminal-configurations-1',1,'Example Terminal Configurations']]],
  ['example_20use_20cases_33',['Exercises - Example Use Cases',['../de/dd1/a03112.html#exercises---example-use-cases',1,'']]],
  ['examples_34',['EXAMPLES',['../d0/d75/a03105.html#examples-4',1,'EXAMPLES'],['../d0/d2b/a03095.html#examples-1',1,'EXAMPLES'],['../d0/d2b/a03095.html#examples-3',1,'EXAMPLES'],['../da/d19/a03094.html#examples-2',1,'EXAMPLES'],['../da/dc0/a03104.html#examples-6',1,'EXAMPLES'],['../da/d19/a03094.html#examples-5',1,'EXAMPLES'],['../d0/dcd/a03113.html#examples-8',1,'EXAMPLES']]],
  ['examples_35',['Examples',['../d5/d43/a03101.html#examples',1,'Examples'],['../df/d9e/a03111.html#examples-7',1,'Examples'],['../index.html#examples-9',1,'Examples']]],
  ['executable_36',['Executable',['../d9/d5e/a03086.html#alternate-bash-executable',1,'Alternate Bash Executable'],['../d4/d6e/a03099.html#alternate-bash-executable-1',1,'Alternate Bash Executable']]],
  ['executables_37',['Executables',['../d5/d3a/a03100.html#menu-form---integrating-external-executables',1,'Menu Form - Integrating External Executables'],['../d5/d3a/a03100.html#static-executables',1,'Static Executables']]],
  ['execution_38',['Detached Execution',['../da/dbe/a03091.html#detached-execution',1,'']]],
  ['execution_20vs_20shell_39',['EXECUTION VS SHELL',['../d0/d2b/a03095.html#function-call-vs-direct-execution-vs-shell',1,'FUNCTION CALL VS DIRECT EXECUTION VS SHELL'],['../da/d19/a03094.html#function-call-vs-direct-execution-vs-shell-1',1,'FUNCTION CALL VS DIRECT EXECUTION VS SHELL']]],
  ['exercise_201_3a_20system_20configurations_40',['Exercise 1: System Configurations',['../d8/db1/a03098.html#exercise-1-system-configurations',1,'']]],
  ['exercises_41',['Exercises',['../da/d4a/a03107.html#c-menu-exercises',1,'C-Menu Exercises'],['../d8/db1/a03098.html#rustlings-exercises',1,'Rustlings Exercises']]],
  ['exercises_42',['exercises',['../d8/db1/a03098.html',1,'']]],
  ['exercises_20example_20use_20cases_43',['Exercises - Example Use Cases',['../de/dd1/a03112.html#exercises---example-use-cases',1,'']]],
  ['exit_20applications_44',['Exit Applications',['../da/dbe/a03091.html#exit-applications',1,'']]],
  ['expected_20output_45',['Expected Output',['../d2/da6/a03117.html#expected-output',1,'']]],
  ['expression_20file_20finder_46',['lf - A Regular Expression File Finder',['../df/d64/a03110.html#lf---a-regular-expression-file-finder',1,'']]],
  ['expressions_47',['lf - List Files Using Regular Expressions',['../da/d4a/a03107.html#lf---list-files-using-regular-expressions',1,'']]],
  ['external_20executables_48',['Menu Form - Integrating External Executables',['../d5/d3a/a03100.html#menu-form---integrating-external-executables',1,'']]],
  ['extras_49',['extras',['../d4/d6e/a03099.html',1,'']]],
  ['extremely_20fast_50',['fd - 0.16 elapsed - &quot;Extremely Fast&quot;',['../index.html#fd---016-elapsed---extremely-fast',1,'']]],
  ['eza_20instead_20of_20ls_51',['Use lsd or eza instead of ls',['../db/dbc/a03114.html#use-lsd-or-eza-instead-of-ls',1,'']]]
];
