var searchData=
[
  ['f_20and_0',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../d6/dfe/a01366.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['faq_1',['FAQ',['../d6/dfe/a01366.html',1,'']]],
  ['fast_20but_20i_20rely_20on_20find_20s_20features_2',['lf is fast, but I rely on find&apos;s features',['../d6/dfe/a01366.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['feature_20enhancements_3',['1.1.0 - Feature Enhancements',['../d6/d4d/a01371.html#autotoc_md110---feature-enhancements',1,'']]],
  ['features_4',['Features',['../d1/d17/a01369.html#_new-features_',1,'&lt;b&gt;&lt;em&gt;NEW Features&lt;/em&gt;&lt;/b&gt;'],['../d1/d17/a01369.html#features',1,'Features'],['../d1/d17/a01369.html#form-key-features',1,'Form Key Features'],['../d1/d17/a01369.html#key-features',1,'Key Features'],['../d2/d1f/a01361.html#rsh-safety-features',1,'RSH Safety Features'],['../d1/d17/a01369.html#view---other-features',1,'View - Other Features']]],
  ['features_5',['lf is fast, but I rely on find&apos;s features',['../d6/dfe/a01366.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_6',['feel free to open an issue on the C Menu GitHub repository',['../d2/d1f/a01361.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d9/d79/a01360.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d7/d81/a01365.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['field_20delimiters_7',['Field Delimiters',['../d2/d1f/a01361.html#form-field-delimiters',1,'Form Field Delimiters'],['../d6/dfe/a01366.html#menu-form---field-delimiters',1,'Menu Form - Field Delimiters']]],
  ['field_20editor_8',['Form field editor',['../d2/d1f/a01361.html#form-field-editor',1,'']]],
  ['fields_9',['Fields',['../da/dab/a01362.html#fields',1,'']]],
  ['file_10',['File',['../da/dab/a01362.html#description-file',1,'Description File'],['../da/dab/a01362.html#menu-description-file',1,'Menu Description File'],['../d1/d17/a01369.html#sample-menu-description-file',1,'Sample Menu Description File'],['../d7/d38/a01373.html#suppression-file',1,'Suppression File']]],
  ['file_20example_11',['C-Menu configuration file example',['../d2/d1f/a01361.html#c-menu-configuration-file-example',1,'']]],
  ['file_20finder_12',['File Finder',['../da/dab/a01362.html#lf---a-regular-expression-file-finder',1,'lf - A Regular Expression File Finder'],['../dd/d0c/a01368.html#lf---a-regular-expression-file-finder-1',1,'lf - A Regular Expression File Finder']]],
  ['file_20format_13',['Menu Description File Format',['../d2/d1f/a01361.html#menu-description-file-format',1,'']]],
  ['file_20in_20view_14',['Large Log File in View',['../d1/d17/a01369.html#large-log-file-in-view',1,'']]],
  ['file_20layout_15',['C-Menu File Layout',['../d2/d1f/a01361.html#c-menu-file-layout',1,'']]],
  ['file_20structure_16',['C-Menu&apos;s File Structure',['../d6/dfe/a01366.html#c-menus-file-structure',1,'']]],
  ['file_20with_20editor_17',['Log File With Editor',['../d1/d17/a01369.html#log-file-with-editor',1,'']]],
  ['file_20with_20view_18',['Screenshot of the Same File With View',['../d1/d17/a01369.html#screenshot-of-the-same-file-with-view',1,'']]],
  ['files_19',['Files',['../df/d0b/a01372.html#c-menu-desktop-files',1,'C-Menu Desktop Files'],['../d9/d79/a01360.html#c-menu-header-files',1,'C-Menu Header Files'],['../d6/dfe/a01366.html#menu-lf---where-are-my-header-files',1,'Menu lf - Where Are My Header Files?'],['../d6/dfe/a01366.html#pick---selecting-multiple-files',1,'Pick - Selecting Multiple Files']]],
  ['files_20',['View - A pager for viewing files',['../dd/d0c/a01368.html#view---a-pager-for-viewing-files',1,'']]],
  ['files_20in_20current_20directory_21',['Files in Current Directory',['../da/dab/a01362.html#edit-c-files-in-current-directory',1,'Edit .c Files in Current Directory'],['../da/dab/a01362.html#edit-c-files-in-current-directory-1',1,'Edit .c Files in Current Directory']]],
  ['files_20using_20regular_20expressions_22',['lf - List Files Using Regular Expressions',['../d1/d17/a01369.html#lf---list-files-using-regular-expressions',1,'']]],
  ['files_20with_20multiple_20suffixes_23',['Can lf match files with multiple suffixes',['../d6/dfe/a01366.html#can-lf-match-files-with-multiple-suffixes',1,'']]],
  ['find_20s_20features_24',['lf is fast, but I rely on find&apos;s features',['../d6/dfe/a01366.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['finder_25',['Finder',['../da/dab/a01362.html#lf---a-regular-expression-file-finder',1,'lf - A Regular Expression File Finder'],['../dd/d0c/a01368.html#lf---a-regular-expression-file-finder-1',1,'lf - A Regular Expression File Finder']]],
  ['finish_20the_20installation_26',['Finish the installation',['../dd/d0c/a01368.html#finish-the-installation',1,'']]],
  ['fixed_27',['Fixed',['../dd/d8b/a01363.html#fixed',1,'']]],
  ['folke_28',['Folke',['../d7/d81/a01365.html#ai-overview-of-developer-folke',1,'AI Overview of Developer Folke'],['../d7/d81/a01365.html#folke',1,'Folke']]],
  ['folke_20s_20lazyvim_29',['To Install Folke&apos;s LazyVim',['../d7/d81/a01365.html#to-install-folkes-lazyvim',1,'']]],
  ['folke_20s_20snacks_20nvim_30',['Folke&apos;s Snacks.nvim',['../d7/d81/a01365.html#folkes-snacksnvim',1,'']]],
  ['folke_20s_20snacks_20nvim_20colorizer_31',['To Install Folke&apos;s Snacks.nvim-colorizer',['../d7/d81/a01365.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['fonts_32',['Fonts',['../d7/d81/a01365.html#fonts',1,'']]],
  ['footprint_33',['Performance and Footprint',['../dd/d0c/a01368.html#performance-and-footprint',1,'']]],
  ['for_20api_20documentation_20and_20user_20guide_34',['Roadmap for API Documentation and User Guide',['../d9/d79/a01360.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['for_20data_20entry_20and_20editing_35',['Form for Data Entry and Editing',['../d1/d17/a01369.html#form-for-data-entry-and-editing',1,'']]],
  ['for_20lf_36',['&lt;b&gt;&lt;em&gt;New Options for lf&lt;/em&gt;&lt;/b&gt;',['../d1/d17/a01369.html#_new-options-for-lf_',1,'']]],
  ['for_20linux_20x86_5f64_37',['C-Menu Binaries for Linux x86_64',['../dd/d0c/a01368.html#c-menu-binaries-for-linux-x86_64',1,'']]],
  ['for_20viewing_20files_38',['View - A pager for viewing files',['../dd/d0c/a01368.html#view---a-pager-for-viewing-files',1,'']]],
  ['form_39',['Form',['../da/dab/a01362.html#c-menu-form',1,'C-Menu Form'],['../dd/d0c/a01368.html#form',1,'Form'],['../d6/d4d/a01371.html#form-1',1,'Form'],['../index.html#form-2',1,'Form']]],
  ['form_20data_20types_40',['Form Data Types',['../d2/d1f/a01361.html#form-data-types',1,'Form Data Types'],['../da/dab/a01362.html#form-data-types-1',1,'Form Data Types'],['../d1/d17/a01369.html#form-data-types-2',1,'Form Data Types'],['../d6/dfe/a01366.html#menu-form---data-types',1,'Menu Form - Data Types']]],
  ['form_20field_20delimiters_41',['Form Field Delimiters',['../d2/d1f/a01361.html#form-field-delimiters',1,'Form Field Delimiters'],['../d6/dfe/a01366.html#menu-form---field-delimiters',1,'Menu Form - Field Delimiters']]],
  ['form_20field_20editor_42',['Form field editor',['../d2/d1f/a01361.html#form-field-editor',1,'']]],
  ['form_20for_20data_20entry_20and_20editing_43',['Form for Data Entry and Editing',['../d1/d17/a01369.html#form-for-data-entry-and-editing',1,'']]],
  ['form_20h_20pick_20h_20and_20view_20h_44',['include/menu.h, form.h, pick.h, and view.h',['../d9/d79/a01360.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['form_20integrating_20external_20executables_45',['Menu Form - Integrating External Executables',['../d6/dfe/a01366.html#menu-form---integrating-external-executables',1,'']]],
  ['form_20key_20features_46',['Form Key Features',['../d1/d17/a01369.html#form-key-features',1,'']]],
  ['form_20line_20syntax_47',['Form Line Syntax',['../d2/d1f/a01361.html#form-line-syntax',1,'']]],
  ['form_20line_20type_20specifiers_48',['Form Line Type Specifiers',['../d2/d1f/a01361.html#form-line-type-specifiers',1,'']]],
  ['form_20line_20type_20speecifiers_20h_20t_20f_20and_49',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../d6/dfe/a01366.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['form_20options_50',['Form Options',['../d2/d1f/a01361.html#form-options',1,'']]],
  ['form_20pick_20and_20view_20api_51',['Menu, Form, Pick, and View API',['../d6/dfe/a01366.html#menu-form-pick-and-view-api',1,'']]],
  ['form_20pick_20view_20c_20keys_20rsh_20and_20lf_52',['Menu, Form, Pick, View, C-Keys, RSH, and lf',['../d1/d17/a01369.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'']]],
  ['format_53',['Menu Description File Format',['../d2/d1f/a01361.html#menu-description-file-format',1,'']]],
  ['forms_20pickers_20views_20ckeys_20etc_54',['Drop-down and Pop-up Menus, Forms, Pickers, Views, Ckeys, etc',['../d6/dfe/a01366.html#drop-down-and-pop-up-menus-forms-pickers-views-ckeys-etc',1,'']]],
  ['forward_55',['Searching Forward',['../d2/d1f/a01361.html#searching-forward',1,'']]],
  ['free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_56',['free to open an issue on the C Menu GitHub repository',['../d2/d1f/a01361.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d9/d79/a01360.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d7/d81/a01365.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['from_20github_57',['Download From Github',['../d6/dfe/a01366.html#download-from-github',1,'']]],
  ['from_20source_58',['Build C-Menu from Source',['../dd/d0c/a01368.html#build-c-menu-from-source',1,'']]],
  ['full_20screen_20root_20shell_59',['Full Screen Root Shell',['../da/dab/a01362.html#full-screen-root-shell',1,'']]]
];
