var searchData=
[
  ['name_0',['NAME',['../d9/db0/a01437.html#name',1,'NAME'],['../d5/dd0/a01438.html#name-1',1,'NAME'],['../d9/d6f/a01445.html#name-2',1,'NAME']]],
  ['name_20c_20menu_20application_20builder_1',['NAME C-Menu Application Builder',['../d1/d3b/a01429.html#name-c-menu-application-builder',1,'']]],
  ['navigation_2',['View Navigation',['../dc/de6/a01426.html#view-navigation',1,'']]],
  ['neovim_3',['Neovim',['../df/d31/a01440.html#_new-api-integration-with-neovim_',1,'&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;'],['../dc/d85/a01436.html#completions-in-neovim',1,'Completions in Neovim'],['../db/dff/a01432.html#neovim',1,'Neovim']]],
  ['neovim_20configuration_4',['Neovim Configuration',['../db/dff/a01432.html#neovim-configuration',1,'']]],
  ['neovim_20linkage_20to_20the_20c_20menu_20api_5',['Neovim Linkage to the C-Menu API',['../db/dff/a01432.html#neovim-linkage-to-the-c-menu-api',1,'']]],
  ['neovim_20unicode_20art_20in_20snacks_20nvim_6',['To Use the Neovim Unicode Art in Snacks.nvim',['../db/dff/a01432.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['new_20api_20integration_20with_20neovim_7',['&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;',['../df/d31/a01440.html#_new-api-integration-with-neovim_',1,'']]],
  ['new_20features_20for_20lf_8',['New Features for lf',['../d6/d65/a01443.html#new-features-for-lf',1,'New Features for lf'],['../index.html#new-features-for-lf-1',1,'New Features for lf']]],
  ['new_20options_20for_20lf_9',['&lt;b&gt;&lt;em&gt;New Options for lf&lt;/em&gt;&lt;/b&gt;',['../df/d31/a01440.html#_new-options-for-lf_',1,'']]],
  ['new_20themes_10',['Creating New Themes',['../df/d75/a01447.html#creating-new-themes',1,'']]],
  ['norcalli_11',['AI Overview of Developer Norcalli',['../db/dff/a01432.html#ai-overview-of-developer-norcalli',1,'']]],
  ['norcalli_20colorizer_12',['Norcalli Colorizer',['../db/dff/a01432.html#norcalli-colorizer',1,'']]],
  ['norcalli_20s_20nvim_20colorizer_20lua_13',['To Install Norcalli&apos;s nvim-colorizer.lua',['../db/dff/a01432.html#to-install-norcallis-nvim-colorizerlua',1,'']]],
  ['not_20required_20but_20recommended_14',['Not Required, But Recommended',['../dc/de6/a01426.html#not-required-but-recommended',1,'']]],
  ['note_15',['NOTE',['../d9/d6f/a01445.html#note',1,'']]],
  ['note_20about_20gmtime_5fr_16',['Important note about &lt;span class=&quot;tt&quot;&gt;gmtime_r()&lt;/span&gt;',['../d3/d95/a01435.html#important-note-about-gmtime_r',1,'']]],
  ['notes_17',['Notes',['../d6/d65/a01443.html#security-notes',1,'Security Notes'],['../index.html#security-notes-1',1,'Security Notes']]],
  ['numbering_18',['View Line Numbering',['../df/d31/a01440.html#view-line-numbering',1,'']]],
  ['nvim_19',['nvim',['../db/dff/a01432.html#folkes-snacksnvim',1,'Folke&apos;s Snacks.nvim'],['../db/dff/a01432.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'To Use the Neovim Unicode Art in Snacks.nvim']]],
  ['nvim_20colorizer_20',['To Install Folke&apos;s Snacks.nvim-colorizer',['../db/dff/a01432.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['nvim_20colorizer_20lua_21',['To Install Norcalli&apos;s nvim-colorizer.lua',['../db/dff/a01432.html#to-install-norcallis-nvim-colorizerlua',1,'']]]
];
