var searchData=
[
  ['a_20box_20window_0',['View In a Box Window',['../d2/d8e/a01315.html#view-in-a-box-window',1,'']]],
  ['a_20pager_20for_20viewing_20files_1',['View - A pager for viewing files',['../d4/d49/a01316.html#view---a-pager-for-viewing-files',1,'']]],
  ['a_20picker_2',['Pick - A Picker',['../df/db8/a01317.html#pick---a-picker',1,'']]],
  ['a_20regular_20expression_20file_20finder_3',['lf - A Regular Expression File Finder',['../d4/d49/a01316.html#lf---a-regular-expression-file-finder',1,'']]],
  ['a_20root_20shell_20alternative_4',['RSH - A Root Shell Alternative',['../d4/d49/a01316.html#rsh---a-root-shell-alternative',1,'']]],
  ['a_20use_20case_5',['RSH - A Use Case',['../da/d79/a01310.html#rsh---a-use-case',1,'']]],
  ['a_20user_20interface_20toolkit_6',['C-Menu - A User Interface Toolkit',['../d4/d49/a01316.html',1,'']]],
  ['about_20c_20menu_20and_20r_20menu_7',['About C-Menu and R-Menu',['../d9/de6/a01314.html#about-c-menu-and-r-menu',1,'']]],
  ['added_8',['Added',['../d7/d41/a01312.html#added',1,'']]],
  ['addendum_9',['C-Menu-Addendum',['../da/d79/a01310.html',1,'']]],
  ['additional_20resources_10',['Additional Resources',['../d9/de6/a01314.html#additional-resources',1,'']]],
  ['address_20space_11',['Demand Paged Virtual Address Space',['../df/db8/a01317.html#demand-paged-virtual-address-space',1,'']]],
  ['against_20c_20menu_12',['Running Valgrind Against C-Menu',['../d9/d5c/a01321.html',1,'']]],
  ['ai_20overview_20of_20developer_20folke_13',['AI Overview of Developer Folke',['../d9/de6/a01314.html#ai-overview-of-developer-folke',1,'']]],
  ['ai_20overview_20of_20developer_20norcalli_14',['AI Overview of Developer Norcalli',['../d9/de6/a01314.html#ai-overview-of-developer-norcalli',1,'']]],
  ['aids_20soap_20box_15',['Visual Aids Soap-box',['../d2/d8e/a01315.html#visual-aids-soap-box',1,'']]],
  ['alacritty_16',['Alacritty',['../df/dec/a01320.html#alacritty',1,'']]],
  ['alacritty_20and_20kitty_17',['Alacritty and Kitty',['../de/d90/a01313.html#alacritty-and-kitty',1,'']]],
  ['alacritty_20configuration_18',['Alacritty Configuration',['../d9/de6/a01314.html#alacritty-configuration',1,'']]],
  ['alternate_20bash_20executable_19',['Alternate Bash Executable',['../d9/de6/a01314.html#alternate-bash-executable',1,'']]],
  ['alternative_20',['RSH - A Root Shell Alternative',['../d4/d49/a01316.html#rsh---a-root-shell-alternative',1,'']]],
  ['an_20issue_20on_20the_20c_20menu_20github_20repository_21',['an issue on the C Menu GitHub repository',['../da/d79/a01310.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d4/d49/a01316.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../db/d4b/a01309.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d9/de6/a01314.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['and_22',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../d2/d8e/a01315.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['and_20color_20manual_20pages_23',['View and Color Manual Pages',['../df/db8/a01317.html#view-and-color-manual-pages',1,'']]],
  ['and_20editing_24',['Form for Data Entry and Editing',['../df/db8/a01317.html#form-for-data-entry-and-editing',1,'']]],
  ['and_20editor_20settings_25',['Terminal and Editor Settings',['../df/dec/a01320.html#terminal-and-editor-settings',1,'']]],
  ['and_20footprint_26',['Summary - Performance and Footprint',['../d4/d49/a01316.html#summary---performance-and-footprint',1,'']]],
  ['and_20gawk_27',['High Precision Math With C-Menu and Gawk',['../d2/d8e/a01315.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['and_20kitty_28',['Alacritty and Kitty',['../de/d90/a01313.html#alacritty-and-kitty',1,'']]],
  ['and_20lf_29',['Menu, Form, Pick, View, C-Keys, RSH, and lf',['../df/db8/a01317.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'']]],
  ['and_20macos_30',['Installing Rust On Linux and macOS',['../d9/de6/a01314.html#installing-rust-on-linux-and-macos',1,'']]],
  ['and_20optimizations_31',['Design Philosophy and Optimizations',['../d6/dfa/a01318.html#design-philosophy-and-optimizations',1,'']]],
  ['and_20pop_20up_20menus_20forms_20pickers_20views_20ckeys_20etc_32',['Drop-down and Pop-up Menus, Forms, Pickers, Views, Ckeys, etc',['../d2/d8e/a01315.html#drop-down-and-pop-up-menus-forms-pickers-views-ckeys-etc',1,'']]],
  ['and_20r_20menu_33',['About C-Menu and R-Menu',['../d9/de6/a01314.html#about-c-menu-and-r-menu',1,'']]],
  ['and_20serialization_34',['Asynchronous Communication and Serialization',['../d1/d72/a01319.html#asynchronous-communication-and-serialization',1,'']]],
  ['and_20user_20guide_35',['Roadmap for API Documentation and User Guide',['../db/d4b/a01309.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['and_20version_20h_36',['include/version.h and version.h',['../db/d4b/a01309.html#includeversionh-and-versionh',1,'']]],
  ['and_20view_20api_37',['Menu, Form, Pick, and View API',['../d2/d8e/a01315.html#menu-form-pick-and-view-api',1,'']]],
  ['and_20view_20h_38',['include/menu.h, form.h, pick.h, and view.h',['../db/d4b/a01309.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_39',['any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../da/d79/a01310.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d4/d49/a01316.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../db/d4b/a01309.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d9/de6/a01314.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['api_40',['API',['../db/d4b/a01309.html',1,'API'],['../d4/d49/a01316.html#c-menu-api',1,'C-Menu API'],['../df/db8/a01317.html#c-menu-api-1',1,'C-Menu API'],['../d2/d8e/a01315.html#menu-form-pick-and-view-api',1,'Menu, Form, Pick, and View API'],['../d9/de6/a01314.html#neovim-linkage-to-the-c-menu-api',1,'Neovim Linkage to the C-Menu API']]],
  ['api_20completions_20in_20neovim_41',['C-Menu API Completions in Neovim',['../d4/d49/a01316.html#c-menu-api-completions-in-neovim',1,'']]],
  ['api_20documentation_20and_20user_20guide_42',['Roadmap for API Documentation and User Guide',['../db/d4b/a01309.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['api_20integration_20with_20neovim_43',['&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;',['../df/db8/a01317.html#_new-api-integration-with-neovim_',1,'']]],
  ['api_20organization_44',['API Organization',['../db/d4b/a01309.html#api-organization',1,'']]],
  ['applications_20menu_45',['C-Menu Example Applications Menu',['../da/d79/a01310.html#c-menu-example-applications-menu',1,'']]],
  ['are_20my_20header_20files_46',['Menu lf - Where Are My Header Files?',['../d2/d8e/a01315.html#menu-lf---where-are-my-header-files',1,'']]],
  ['art_20in_20snacks_20nvim_47',['To Use the Neovim Unicode Art in Snacks.nvim',['../d9/de6/a01314.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['asynchronous_20communication_20and_20serialization_48',['Asynchronous Communication and Serialization',['../d1/d72/a01319.html#asynchronous-communication-and-serialization',1,'']]]
];
