var searchData=
[
  ['t_20f_20and_0',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../dc/de0/a01302.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['t_20stop_20typing_20vi_1',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../d7/d8c/a01306.html#if-you-cant-stop-typing-vi',1,'']]],
  ['t_20work_2',['Some Menu Selections Don&apos;t work',['../dc/de0/a01302.html#some-menu-selections-dont-work',1,'']]],
  ['table_20of_20contents_3',['Table of Contents',['../d4/d34/a01298.html#table-of-contents',1,'Table of Contents'],['../d8/dc5/a01300.html#table-of-contents-1',1,'Table of Contents'],['../d3/d07/a01301.html#table-of-contents-2',1,'Table of Contents'],['../dc/de0/a01302.html#table-of-contents-3',1,'Table of Contents'],['../d6/dae/a01304.html#table-of-contents-4',1,'Table of Contents'],['../d7/d8c/a01306.html#table-of-contents-5',1,'Table of Contents'],['../index.html#table-of-contents-6',1,'Table of Contents']]],
  ['target_20recommended_4',['Using the Makefile target (recommended)',['../d2/d4c/a01307.html#using-the-makefile-target-recommended',1,'']]],
  ['tasks_20to_20complete_20before_200_203_200_5',['0.2.9 Tasks to Complete before 0.3.0',['../dc/d9e/a01305.html#autotoc_md029-tasks-to-complete-before-030',1,'']]],
  ['terminal_20and_20editor_20settings_6',['Terminal and Editor Settings',['../d7/d8c/a01306.html#terminal-and-editor-settings',1,'']]],
  ['terminal_20configurations_7',['Terminal Configurations',['../d3/d07/a01301.html#example-terminal-configurations',1,'Example Terminal Configurations'],['../d7/d8c/a01306.html#terminal-configurations',1,'Terminal Configurations']]],
  ['terminal_20emulator_8',['Customize Your Terminal Emulator',['../d3/d07/a01301.html#customize-your-terminal-emulator',1,'']]],
  ['testing_20tree_20sitter_9',['Testing Tree-Sitter',['../d3/d07/a01301.html#testing-tree-sitter',1,'']]],
  ['the_20c_20menu_20api_10',['Neovim Linkage to the C-Menu API',['../d3/d07/a01301.html#neovim-linkage-to-the-c-menu-api',1,'']]],
  ['the_20c_20menu_20github_20repository_11',['the C Menu GitHub repository',['../d4/d34/a01298.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d6/d07/a01303.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../index.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-4',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../dc/d8c/a01297.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d3/d07/a01301.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['the_20horizon_12',['0.3.0 On the Horizon',['../dc/d9e/a01305.html#autotoc_md030-on-the-horizon',1,'']]],
  ['the_20icon_13',['What&apos;s the Icon?',['../dc/de0/a01302.html#whats-the-icon',1,'']]],
  ['the_20installation_14',['the installation',['../d6/d07/a01303.html#finish-the-installation',1,'Finish the installation'],['../index.html#finish-the-installation-1',1,'Finish the installation']]],
  ['the_20installment_20loan_20calculator_15',['Menu - Using the Installment Loan Calculator',['../dc/de0/a01302.html#menu---using-the-installment-loan-calculator',1,'']]],
  ['the_20makefile_20target_20recommended_16',['Using the Makefile target (recommended)',['../d2/d4c/a01307.html#using-the-makefile-target-recommended',1,'']]],
  ['the_20neovim_20unicode_20art_20in_20snacks_20nvim_17',['To Use the Neovim Unicode Art in Snacks.nvim',['../d3/d07/a01301.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['the_20same_20file_20with_20view_18',['Screenshot of the Same File With View',['../d6/dae/a01304.html#screenshot-of-the-same-file-with-view',1,'']]],
  ['through_20obscurity_19',['Security Through Obscurity',['../d7/d8c/a01306.html#security-through-obscurity',1,'']]],
  ['to_20colorize_20html_20color_20codes_20',['View - How to Colorize HTML Color Codes',['../dc/de0/a01302.html#view---how-to-colorize-html-color-codes',1,'']]],
  ['to_20colorize_20manual_20pages_21',['View - How to Colorize Manual Pages',['../dc/de0/a01302.html#view---how-to-colorize-manual-pages',1,'']]],
  ['to_20complete_20before_200_203_200_22',['0.2.9 Tasks to Complete before 0.3.0',['../dc/d9e/a01305.html#autotoc_md029-tasks-to-complete-before-030',1,'']]],
  ['to_20customize_20colors_23',['View - How to Customize Colors',['../dc/de0/a01302.html#view---how-to-customize-colors',1,'']]],
  ['to_20delete_20by_20inode_24',['Menu - What Happened to Delete by Inode',['../dc/de0/a01302.html#menu---what-happened-to-delete-by-inode',1,'']]],
  ['to_20get_20c_20menu_25',['to get C Menu',['../dc/d8c/a01297.html#how-to-get-c-menu',1,'How to get C-Menu'],['../d4/d34/a01298.html#how-to-get-c-menu-1',1,'How to get C-Menu'],['../d3/d07/a01301.html#how-to-get-c-menu-2',1,'How to get C-Menu']]],
  ['to_20install_20folke_20s_20lazyvim_26',['To Install Folke&apos;s LazyVim',['../d3/d07/a01301.html#to-install-folkes-lazyvim',1,'']]],
  ['to_20install_20folke_20s_20snacks_20nvim_20colorizer_27',['To Install Folke&apos;s Snacks.nvim-colorizer',['../d3/d07/a01301.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['to_20install_20norcalli_20s_20nvim_20colorizer_20lua_28',['To Install Norcalli&apos;s nvim-colorizer.lua',['../d3/d07/a01301.html#to-install-norcallis-nvim-colorizerlua',1,'']]],
  ['to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_29',['to open an issue on the C Menu GitHub repository',['../d4/d34/a01298.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d6/d07/a01303.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../index.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-4',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../dc/d8c/a01297.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d3/d07/a01301.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['to_20run_30',['How to Run',['../d2/d4c/a01307.html#how-to-run',1,'']]],
  ['to_20the_20c_20menu_20api_31',['Neovim Linkage to the C-Menu API',['../d3/d07/a01301.html#neovim-linkage-to-the-c-menu-api',1,'']]],
  ['to_20use_20the_20neovim_20unicode_20art_20in_20snacks_20nvim_32',['To Use the Neovim Unicode Art in Snacks.nvim',['../d3/d07/a01301.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['to_20use_20tree_20sitter_20with_20view_33',['View - How to Use Tree-Sitter with View',['../dc/de0/a01302.html#view---how-to-use-tree-sitter-with-view',1,'']]],
  ['toolkit_34',['Toolkit',['../d6/d07/a01303.html',1,'C-Menu - A User Interface Toolkit'],['../index.html',1,'C-Menu - A User Interface Toolkit']]],
  ['tree_20sitter_35',['Tree Sitter',['../d3/d07/a01301.html#testing-tree-sitter',1,'Testing Tree-Sitter'],['../d3/d07/a01301.html#tree-sitter',1,'Tree-Sitter'],['../d7/d8c/a01306.html#tree-sitter-1',1,'Tree-Sitter']]],
  ['tree_20sitter_20cli_36',['Tree Sitter CLI',['../dc/de0/a01302.html#install-tree-sitter-cli',1,'Install Tree-Sitter-CLI'],['../d3/d07/a01301.html#tree-sitter-cli',1,'Tree-Sitter-CLI']]],
  ['tree_20sitter_20cli_20on_20linux_37',['Tree-Sitter-CLI On Linux',['../d3/d07/a01301.html#tree-sitter-cli-on-linux',1,'']]],
  ['tree_20sitter_20cli_20on_20macos_38',['Tree-Sitter-CLI On macOS',['../d3/d07/a01301.html#tree-sitter-cli-on-macos',1,'']]],
  ['tree_20sitter_20cli_20on_20windows_39',['Tree-Sitter-CLI On Windows',['../d3/d07/a01301.html#tree-sitter-cli-on-windows',1,'']]],
  ['tree_20sitter_20config_20json_40',['Tree-Sitter config.json',['../d7/d8c/a01306.html#tree-sitter-configjson',1,'']]],
  ['tree_20sitter_20on_20linux_41',['Tree-Sitter On Linux',['../d3/d07/a01301.html#tree-sitter-on-linux',1,'']]],
  ['tree_20sitter_20on_20macos_42',['Tree-Sitter On macOS',['../d3/d07/a01301.html#tree-sitter-on-macos',1,'']]],
  ['tree_20sitter_20on_20windows_43',['Tree-Sitter On Windows',['../d3/d07/a01301.html#tree-sitter-on-windows',1,'']]],
  ['tree_20sitter_20parsers_44',['Tree-Sitter Parsers',['../d3/d07/a01301.html#tree-sitter-parsers',1,'']]],
  ['tree_20sitter_20parsers_20on_20linux_45',['Tree-Sitter Parsers On Linux',['../d3/d07/a01301.html#tree-sitter-parsers-on-linux',1,'']]],
  ['tree_20sitter_20parsers_20on_20macos_46',['Tree-Sitter Parsers On macOS',['../d3/d07/a01301.html#tree-sitter-parsers-on-macos',1,'']]],
  ['tree_20sitter_20parsers_20on_20windows_47',['Tree-Sitter Parsers On Windows',['../d3/d07/a01301.html#tree-sitter-parsers-on-windows',1,'']]],
  ['tree_20sitter_20with_20view_48',['View - How to Use Tree-Sitter with View',['../dc/de0/a01302.html#view---how-to-use-tree-sitter-with-view',1,'']]],
  ['troubleshooting_49',['Troubleshooting',['../d4/d34/a01298.html#troubleshooting',1,'']]],
  ['truecolor_20support_50',['TrueColor Support',['../dc/de0/a01302.html#truecolor-support',1,'']]],
  ['type_20specifiers_51',['Form Line Type Specifiers',['../d4/d34/a01298.html#form-line-type-specifiers',1,'']]],
  ['type_20speecifiers_20h_20t_20f_20and_52',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../dc/de0/a01302.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['types_53',['Types',['../d4/d34/a01298.html#form-data-types',1,'Form Data Types'],['../d6/dae/a01304.html#form-data-types-1',1,'Form Data Types'],['../dc/de0/a01302.html#menu-form---data-types',1,'Menu Form - Data Types']]],
  ['typing_20vi_54',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../d7/d8c/a01306.html#if-you-cant-stop-typing-vi',1,'']]]
];
