var searchData=
[
  ['obscurity_0',['Security Through Obscurity',['../d7/da4/md_snippets.html#security-through-obscurity',1,'']]],
  ['of_20c_20menu_1',['Elements of C-Menu',['../d0/d30/md_README.html#elements-of-c-menu',1,'']]],
  ['of_20contents_2',['of Contents',['../de/d82/md_C-Menu-UG.html#table-of-contents',1,'Table of Contents'],['../dc/db0/md_extras.html#table-of-contents-1',1,'Table of Contents'],['../d5/d77/md_FAQ.html#table-of-contents-2',1,'Table of Contents'],['../d0/d30/md_README.html#table-of-contents-3',1,'Table of Contents'],['../d7/da4/md_snippets.html#table-of-contents-4',1,'Table of Contents']]],
  ['of_20ls_3',['Use lsd instead of ls',['../d7/da4/md_snippets.html#use-lsd-instead-of-ls',1,'']]],
  ['of_20the_20same_20file_20with_20view_4',['Screenshot of the Same File With View',['../d0/d30/md_README.html#screenshot-of-the-same-file-with-view',1,'']]],
  ['on_20linux_5',['On Linux',['../dc/db0/md_extras.html#bat-on-linux',1,'Bat On Linux'],['../dc/db0/md_extras.html#ghostty-on-linux',1,'Ghostty On Linux'],['../dc/db0/md_extras.html#lsd-on-linux',1,'lsd On Linux'],['../dc/db0/md_extras.html#ripgrep-on-linux',1,'Ripgrep On Linux'],['../dc/db0/md_extras.html#tree-sitter-on-linux',1,'Tree-Sitter On Linux'],['../dc/db0/md_extras.html#tree-sitter-parsers-on-linux',1,'Tree-Sitter Parsers On Linux'],['../dc/db0/md_extras.html#tree-sitter-cli-on-linux',1,'Tree-Sitter-CLI On Linux']]],
  ['on_20linux_20and_20macos_6',['Installing Rust On Linux and macOS',['../dc/db0/md_extras.html#installing-rust-on-linux-and-macos',1,'']]],
  ['on_20macos_7',['On macOS',['../dc/db0/md_extras.html#bat-on-macos',1,'Bat On macOS'],['../dc/db0/md_extras.html#ghostty-on-macos',1,'Ghostty On macOS'],['../dc/db0/md_extras.html#lsd-on-macos',1,'lsd On macOS'],['../dc/db0/md_extras.html#ripgrep-on-macos',1,'Ripgrep On macOS'],['../dc/db0/md_extras.html#tree-sitter-on-macos',1,'Tree-Sitter On macOS'],['../dc/db0/md_extras.html#tree-sitter-parsers-on-macos',1,'Tree-Sitter Parsers On macOS'],['../dc/db0/md_extras.html#tree-sitter-cli-on-macos',1,'Tree-Sitter-CLI On macOS']]],
  ['on_20the_20c_20menu_20github_20repository_8',['🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.',['../d4/def/md_INSTALL.html#autotoc_md--enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'']]],
  ['on_20windows_9',['On Windows',['../dc/db0/md_extras.html#bat-on-windows',1,'Bat On Windows'],['../dc/db0/md_extras.html#ghostty-on-windows',1,'Ghostty On Windows'],['../dc/db0/md_extras.html#lsd-on-windows',1,'lsd On Windows'],['../dc/db0/md_extras.html#ripgrep-on-windows',1,'Ripgrep On Windows'],['../dc/db0/md_extras.html#tree-sitter-on-windows',1,'Tree-Sitter On Windows'],['../dc/db0/md_extras.html#tree-sitter-parsers-on-windows',1,'Tree-Sitter Parsers On Windows'],['../dc/db0/md_extras.html#tree-sitter-cli-on-windows',1,'Tree-Sitter-CLI On Windows']]],
  ['open_20an_20issue_20on_20the_20c_20menu_20github_20repository_10',['🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.',['../d4/def/md_INSTALL.html#autotoc_md--enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'']]],
  ['option_201_20build_20c_20menu_20using_20cmake_20directly_11',['Option 1 - Build C-Menu Using CMake Directly',['../d4/def/md_INSTALL.html#option-1---build-c-menu-using-cmake-directly',1,'']]],
  ['option_202_20build_20c_20menu_20with_20provided_20scripts_12',['Option 2 - Build C-Menu with Provided Scripts',['../d4/def/md_INSTALL.html#option-2---build-c-menu-with-provided-scripts',1,'']]],
  ['option_203_20build_20c_20menu_20using_20makefile_13',['Option 3 - Build C-Menu Using Makefile',['../d4/def/md_INSTALL.html#option-3---build-c-menu-using-makefile',1,'']]],
  ['options_14',['Options',['../de/d82/md_C-Menu-UG.html#c-menu-options',1,'C-Menu Options'],['../de/d82/md_C-Menu-UG.html#form-options',1,'Form Options'],['../de/d82/md_C-Menu-UG.html#pick-options',1,'Pick Options'],['../de/d82/md_C-Menu-UG.html#view-options',1,'View Options']]],
  ['or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_15',['🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.',['../d4/def/md_INSTALL.html#autotoc_md--enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'']]],
  ['other_20features_16',['View - Other Features',['../d0/d30/md_README.html#view---other-features',1,'']]],
  ['output_17',['Sorted lf Output',['../d5/d77/md_FAQ.html#sorted-lf-output',1,'']]]
];
