var searchData=
[
  ['c_20keys_20diagnose_20keyboard_20mouse_20input_0',['C-Keys - Diagnose Keyboard/Mouse Input',['../index.html#c-keys---diagnose-keyboardmouse-input',1,'']]],
  ['c_20keys_20rsh_20and_20lf_1',['Menu, Form, Pick, View, C-Keys, RSH, and lf',['../index.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'']]],
  ['c_20menu_2',['C Menu',['../d2/da6/a01210.html',1,'Augmenting C-Menu'],['../dc/db6/a01212.html#build-c-menu',1,'Build C-Menu'],['../index.html#elements-of-c-menu',1,'Elements of C-Menu'],['../d5/dad/a01207.html#starting-c-menu',1,'Starting C-Menu']]],
  ['c_20menu_20and_20gawk_3',['High Precision Math With C-Menu and Gawk',['../d1/d34/a01211.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['c_20menu_20and_20r_20menu_4',['About C-Menu and R-Menu',['../d2/da6/a01210.html#about-c-menu-and-r-menu',1,'']]],
  ['c_20menu_20api_5',['C Menu API',['../index.html#c-menu-api',1,'C-Menu API'],['../d2/da6/a01210.html#neovim-linkage-to-the-c-menu-api',1,'Neovim Linkage to the C-Menu API']]],
  ['c_20menu_20bashrc_20configuration_6',['C-Menu bashrc Configuration',['../d5/d32/a01214.html#c-menu-bashrc-configuration',1,'']]],
  ['c_20menu_20configuration_7',['C-Menu Configuration',['../d5/d32/a01214.html#c-menu-configuration-1',1,'']]],
  ['c_20menu_20configuration_8',['C-Menu configuration',['../d5/dad/a01207.html#c-menu-configuration',1,'']]],
  ['c_20menu_20configuration_20file_20example_9',['C-Menu configuration file example',['../d5/dad/a01207.html#c-menu-configuration-file-example',1,'']]],
  ['c_20menu_20desktop_20files_10',['C-Menu Desktop Files',['../d5/d32/a01214.html#c-menu-desktop-files',1,'']]],
  ['c_20menu_20documents_11',['Other C-Menu Documents',['../index.html#other-c-menu-documents',1,'']]],
  ['c_20menu_20environment_20variables_12',['Helpful C-Menu Environment Variables',['../d5/d32/a01214.html#helpful-c-menu-environment-variables',1,'']]],
  ['c_20menu_20exercises_13',['C-Menu Exercises',['../index.html#c-menu-exercises',1,'']]],
  ['c_20menu_20file_20layout_14',['C-Menu File Layout',['../d5/dad/a01207.html#c-menu-file-layout',1,'']]],
  ['c_20menu_20form_15',['C-Menu Form',['../d5/dad/a01207.html#c-menu-form',1,'']]],
  ['c_20menu_20github_20repository_16',['C Menu GitHub repository',['../dc/d9e/a01206.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d5/dad/a01207.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../de/d04/a01209.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d2/da6/a01210.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d1/d34/a01211.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-4',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../dc/db6/a01212.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-5',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['c_20menu_20header_20files_17',['C-Menu Header Files',['../dc/d9e/a01206.html#c-menu-header-files',1,'']]],
  ['c_20menu_20if_20you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_18',['C Menu If you encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../dc/d9e/a01206.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d5/dad/a01207.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../de/d04/a01209.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d2/da6/a01210.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d1/d34/a01211.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-4',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../dc/db6/a01212.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-5',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['c_20menu_20introduction_19',['C-Menu Introduction',['../index.html#c-menu-introduction',1,'']]],
  ['c_20menu_20menu_20',['Programming C-Menu Menu',['../d5/dad/a01207.html#programming-c-menu-menu',1,'']]],
  ['c_20menu_20on_20github_21',['C Menu on Github',['../index.html#get-c-menu-on-github',1,'Get C-Menu on Github'],['../dc/d9e/a01206.html#get-c-menu-on-github-1',1,'Get C-Menu on Github'],['../d5/dad/a01207.html#get-c-menu-on-github-2',1,'Get C-Menu on Github'],['../d2/da6/a01210.html#get-c-menu-on-github-3',1,'Get C-Menu on Github']]],
  ['c_20menu_20options_22',['C-Menu Options',['../d5/dad/a01207.html#c-menu-options',1,'']]],
  ['c_20menu_20pick_23',['C-Menu Pick',['../d5/dad/a01207.html#c-menu-pick',1,'']]],
  ['c_20menu_20roadmap_24',['C-Menu ROADMAP',['../d5/d54/a01213.html',1,'']]],
  ['c_20menu_20s_20file_20structure_25',['C-Menu&apos;s File Structure',['../d1/d34/a01211.html#c-menus-file-structure',1,'']]],
  ['c_20menu_20startup_20with_20mm_26',['C-Menu Startup with &quot;mm&quot;',['../d5/d32/a01214.html#c-menu-startup-with-mm',1,'']]],
  ['c_20menu_20using_20cmake_20directly_27',['Option 1 - Build C-Menu Using CMake Directly',['../dc/db6/a01212.html#option-1---build-c-menu-using-cmake-directly',1,'']]],
  ['c_20menu_20using_20makefile_28',['Option 3 - Build C-Menu Using Makefile',['../dc/db6/a01212.html#option-3---build-c-menu-using-makefile',1,'']]],
  ['c_20menu_20view_29',['C-Menu View',['../d5/dad/a01207.html#c-menu-view',1,'']]],
  ['c_20menu_20with_20provided_20scripts_30',['Option 2 - Build C-Menu with Provided Scripts',['../dc/db6/a01212.html#option-2---build-c-menu-with-provided-scripts',1,'']]],
  ['calculator_31',['Menu - Using the Installment Loan Calculator',['../d1/d34/a01211.html#menu---using-the-installment-loan-calculator',1,'']]],
  ['can_20t_20stop_20typing_20vi_32',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../d5/d32/a01214.html#if-you-cant-stop-typing-vi',1,'']]],
  ['case_33',['RSH - A Use Case',['../d5/dad/a01207.html#rsh---a-use-case',1,'']]],
  ['cases_34',['Exercises - Example Use Cases',['../d5/d54/a01213.html#exercises---example-use-cases',1,'']]],
  ['changelog_35',['Changelog',['../d9/d31/a01208.html',1,'']]],
  ['channel_20gamma_20correction_36',['3-Channel Gamma Correction',['../index.html#autotoc_md3-channel-gamma-correction',1,'']]],
  ['ckeys_20etc_37',['Drop-down and Pop-up Menus, Forms, Pickers, Views, Ckeys, etc.',['../d1/d34/a01211.html#drop-down-and-pop-up-menus-forms-pickers-views-ckeys-etc',1,'']]],
  ['cli_38',['CLI',['../d1/d34/a01211.html#install-tree-sitter-cli',1,'Install Tree-Sitter-CLI'],['../d2/da6/a01210.html#tree-sitter-cli',1,'Tree-Sitter-CLI']]],
  ['cli_20on_20linux_39',['Tree-Sitter-CLI On Linux',['../d2/da6/a01210.html#tree-sitter-cli-on-linux',1,'']]],
  ['cli_20on_20macos_40',['Tree-Sitter-CLI On macOS',['../d2/da6/a01210.html#tree-sitter-cli-on-macos',1,'']]],
  ['cli_20on_20windows_41',['Tree-Sitter-CLI On Windows',['../d2/da6/a01210.html#tree-sitter-cli-on-windows',1,'']]],
  ['cm_20h_42',['include/cm.h',['../dc/d9e/a01206.html#includecmh',1,'']]],
  ['cmake_20directly_43',['Option 1 - Build C-Menu Using CMake Directly',['../dc/db6/a01212.html#option-1---build-c-menu-using-cmake-directly',1,'']]],
  ['codes_44',['View - How to Colorize HTML Color Codes',['../d1/d34/a01211.html#view---how-to-colorize-html-color-codes',1,'']]],
  ['color_20codes_45',['View - How to Colorize HTML Color Codes',['../d1/d34/a01211.html#view---how-to-colorize-html-color-codes',1,'']]],
  ['color_20manual_20pages_46',['View and Color Manual Pages',['../index.html#view-and-color-manual-pages',1,'']]],
  ['colorize_20html_20color_20codes_47',['View - How to Colorize HTML Color Codes',['../d1/d34/a01211.html#view---how-to-colorize-html-color-codes',1,'']]],
  ['colorize_20manual_20pages_48',['View - How to Colorize Manual Pages',['../d1/d34/a01211.html#view---how-to-colorize-manual-pages',1,'']]],
  ['colorizer_49',['Norcalli Colorizer',['../d2/da6/a01210.html#norcalli-colorizer',1,'']]],
  ['colorizer_50',['To Install Folke&apos;s Snacks.nvim-colorizer',['../d2/da6/a01210.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['colorizer_20lua_51',['To Install Norcalli&apos;s nvim-colorizer.lua',['../d2/da6/a01210.html#to-install-norcallis-nvim-colorizerlua',1,'']]],
  ['colors_52',['View - How to Customize Colors',['../d1/d34/a01211.html#view---how-to-customize-colors',1,'']]],
  ['common_20h_53',['include/common.h',['../dc/d9e/a01206.html#includecommonh',1,'']]],
  ['communications_54',['Menu - Interprocess Communications',['../d1/d34/a01211.html#menu---interprocess-communications',1,'']]],
  ['compatibility_55',['Version Compatibility',['../dc/d9e/a01206.html#version-compatibility',1,'']]],
  ['conclusion_56',['Conclusion',['../d2/da6/a01210.html#conclusion',1,'']]],
  ['config_20json_57',['Tree-Sitter config.json',['../d5/d32/a01214.html#tree-sitter-configjson',1,'']]],
  ['configuration_58',['Configuration',['../d2/da6/a01210.html#alacritty-configuration',1,'Alacritty Configuration'],['../d5/d32/a01214.html#c-menu-bashrc-configuration',1,'C-Menu bashrc Configuration'],['../d5/d32/a01214.html#c-menu-configuration-1',1,'C-Menu Configuration'],['../index.html#configuration',1,'Configuration'],['../de/d04/a01209.html#ghostty-configuration',1,'Ghostty Configuration'],['../d2/da6/a01210.html#ghostty-configuration-1',1,'Ghostty Configuration'],['../d2/da6/a01210.html#kitty-configuration',1,'Kitty Configuration'],['../d2/da6/a01210.html#neovim-configuration',1,'Neovim Configuration'],['../de/d04/a01209.html#sddm-background-configuration',1,'SDDM Background Configuration'],['../d2/da6/a01210.html#shell-configuration',1,'Shell Configuration']]],
  ['configuration_59',['C-Menu configuration',['../d5/dad/a01207.html#c-menu-configuration',1,'']]],
  ['configuration_20file_20example_60',['C-Menu configuration file example',['../d5/dad/a01207.html#c-menu-configuration-file-example',1,'']]],
  ['configuration_20snippets_61',['Configuration snippets',['../d5/d32/a01214.html',1,'']]],
  ['configurations_62',['Configurations',['../d2/da6/a01210.html#example-terminal-configurations',1,'Example Terminal Configurations'],['../de/d04/a01209.html#exercise-1-system-configurations',1,'Exercise 1: System Configurations'],['../d5/d32/a01214.html#terminal-configurations',1,'Terminal Configurations'],['../d2/da6/a01210.html#useful-configurations',1,'Useful Configurations']]],
  ['contents_63',['Contents',['../d5/dad/a01207.html#table-of-contents-1',1,'Table of Contents'],['../d2/da6/a01210.html#table-of-contents-2',1,'Table of Contents'],['../d1/d34/a01211.html#table-of-contents-3',1,'Table of Contents'],['../d5/d32/a01214.html#table-of-contents-4',1,'Table of Contents']]],
  ['contents_3a_64',['Table of Contents:',['../index.html#table-of-contents',1,'']]],
  ['correction_65',['3-Channel Gamma Correction',['../index.html#autotoc_md3-channel-gamma-correction',1,'']]],
  ['curses_20escape_20delay_66',['Curses Escape Delay',['../d5/d32/a01214.html#curses-escape-delay',1,'']]],
  ['custom_20highlights_67',['Custom Highlights',['../d2/da6/a01210.html#custom-highlights',1,'']]],
  ['customize_20colors_68',['View - How to Customize Colors',['../d1/d34/a01211.html#view---how-to-customize-colors',1,'']]],
  ['customize_20your_20terminal_20emulator_69',['Customize Your Terminal Emulator',['../d2/da6/a01210.html#customize-your-terminal-emulator',1,'']]]
];
