var searchData=
[
  ['edit_20c_20files_20in_20current_20directory_0',['Edit c Files in Current Directory',['../da/dab/a01362.html#edit-c-files-in-current-directory',1,'Edit .c Files in Current Directory'],['../da/dab/a01362.html#edit-c-files-in-current-directory-1',1,'Edit .c Files in Current Directory']]],
  ['editing_1',['Form for Data Entry and Editing',['../d1/d17/a01369.html#form-for-data-entry-and-editing',1,'']]],
  ['editor_2',['Editor',['../d1/d17/a01369.html#example-manual-page-using-editor',1,'Example Manual Page Using Editor'],['../d1/d17/a01369.html#log-file-with-editor',1,'Log File With Editor']]],
  ['editor_3',['Form field editor',['../d2/d1f/a01361.html#form-field-editor',1,'']]],
  ['editor_20loop_4',['Line editor loop',['../da/dfb/a01174.html#line-editor-loop',1,'']]],
  ['editor_20settings_5',['Terminal and Editor Settings',['../df/d0b/a01372.html#terminal-and-editor-settings',1,'']]],
  ['elements_20of_20c_20menu_6',['Elements of C-Menu',['../d1/d17/a01369.html#elements-of-c-menu',1,'']]],
  ['emulator_7',['Customize Your Terminal Emulator',['../d7/d81/a01365.html#customize-your-terminal-emulator',1,'']]],
  ['encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_8',['encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../d2/d1f/a01361.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d9/d79/a01360.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d7/d81/a01365.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['enhancements_9',['1.1.0 - Feature Enhancements',['../d6/d4d/a01371.html#autotoc_md110---feature-enhancements',1,'']]],
  ['enjoy_20using_20c_20menu_20if_20you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_10',['Enjoy using C Menu If you encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../d2/d1f/a01361.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d9/d79/a01360.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d7/d81/a01365.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['entry_20and_20editing_11',['Form for Data Entry and Editing',['../d1/d17/a01369.html#form-for-data-entry-and-editing',1,'']]],
  ['environment_20variables_12',['Environment Variables',['../d2/d1f/a01361.html#c-menu-environment-variables',1,'C-Menu Environment Variables'],['../df/d0b/a01372.html#helpful-c-menu-environment-variables',1,'Helpful C-Menu Environment Variables'],['../df/d0b/a01372.html#system-specific-environment-variables',1,'System Specific Environment Variables']]],
  ['escape_20delay_13',['Curses Escape Delay',['../df/d0b/a01372.html#curses-escape-delay',1,'']]],
  ['etc_14',['Drop-down and Pop-up Menus, Forms, Pickers, Views, Ckeys, etc',['../d6/dfe/a01366.html#drop-down-and-pop-up-menus-forms-pickers-views-ckeys-etc',1,'']]],
  ['example_15',['C-Menu configuration file example',['../d2/d1f/a01361.html#c-menu-configuration-file-example',1,'']]],
  ['example_20application_20menu_16',['Example Application Menu',['../da/dab/a01362.html#example-application-menu',1,'']]],
  ['example_20applications_20menu_17',['C-Menu Example Applications Menu',['../d2/d1f/a01361.html#c-menu-example-applications-menu',1,'']]],
  ['example_20manual_20page_18',['Example Manual Page',['../d1/d17/a01369.html#example-manual-page',1,'']]],
  ['example_20manual_20page_20using_20editor_19',['Example Manual Page Using Editor',['../d1/d17/a01369.html#example-manual-page-using-editor',1,'']]],
  ['example_20terminal_20configurations_20',['Example Terminal Configurations',['../d7/d81/a01365.html#example-terminal-configurations',1,'']]],
  ['example_20use_20cases_21',['Exercises - Example Use Cases',['../d6/d4d/a01371.html#exercises---example-use-cases',1,'']]],
  ['examples_22',['Examples',['../da/dab/a01362.html#examples',1,'Examples'],['../index.html#examples-1',1,'Examples']]],
  ['executable_23',['Alternate Bash Executable',['../d7/d81/a01365.html#alternate-bash-executable',1,'']]],
  ['executables_24',['Executables',['../d6/dfe/a01366.html#menu-form---integrating-external-executables',1,'Menu Form - Integrating External Executables'],['../d6/dfe/a01366.html#multiple-executables',1,'Multiple Executables'],['../d6/dfe/a01366.html#static-executables',1,'Static Executables']]],
  ['exercise_201_3a_20system_20configurations_25',['Exercise 1: System Configurations',['../de/d1f/a01364.html#exercise-1-system-configurations',1,'']]],
  ['exercises_26',['Exercises',['../d1/d17/a01369.html#c-menu-exercises',1,'C-Menu Exercises'],['../de/d1f/a01364.html#rustlings-exercises',1,'Rustlings Exercises']]],
  ['exercises_27',['exercises',['../de/d1f/a01364.html',1,'']]],
  ['exercises_20example_20use_20cases_28',['Exercises - Example Use Cases',['../d6/d4d/a01371.html#exercises---example-use-cases',1,'']]],
  ['expected_20output_29',['Expected Output',['../d7/d38/a01373.html#expected-output',1,'']]],
  ['expression_20file_20finder_30',['Expression File Finder',['../da/dab/a01362.html#lf---a-regular-expression-file-finder',1,'lf - A Regular Expression File Finder'],['../dd/d0c/a01368.html#lf---a-regular-expression-file-finder-1',1,'lf - A Regular Expression File Finder']]],
  ['expressions_31',['lf - List Files Using Regular Expressions',['../d1/d17/a01369.html#lf---list-files-using-regular-expressions',1,'']]],
  ['external_20executables_32',['Menu Form - Integrating External Executables',['../d6/dfe/a01366.html#menu-form---integrating-external-executables',1,'']]],
  ['extras_33',['extras',['../d7/d81/a01365.html',1,'']]],
  ['eza_20instead_20of_20ls_34',['Use lsd or eza instead of ls',['../df/d0b/a01372.html#use-lsd-or-eza-instead-of-ls',1,'']]]
];
