var searchData=
[
  ['a_20box_20window_0',['View In a Box Window',['../dd/d8b/a01363.html#view-in-a-box-window',1,'']]],
  ['a_20pager_20for_20viewing_20files_1',['View - A pager for viewing files',['../d7/d81/a01365.html#view---a-pager-for-viewing-files',1,'']]],
  ['a_20picker_2',['Pick - A Picker',['../d6/dfe/a01366.html#pick---a-picker',1,'']]],
  ['a_20regular_20expression_20file_20finder_3',['A Regular Expression File Finder',['../dc/d4b/a01359.html#lf---a-regular-expression-file-finder',1,'lf - A Regular Expression File Finder'],['../d7/d81/a01365.html#lf---a-regular-expression-file-finder-1',1,'lf - A Regular Expression File Finder']]],
  ['a_20root_20shell_20alternative_4',['A Root Shell Alternative',['../dc/d4b/a01359.html#rsh---a-root-shell-alternative',1,'RSH - A Root Shell Alternative'],['../d7/d81/a01365.html#rsh---a-root-shell-alternative-1',1,'RSH - A Root Shell Alternative']]],
  ['a_20use_20case_5',['RSH - A Use Case',['../de/d5c/a01358.html#rsh---a-use-case',1,'']]],
  ['a_20user_20interface_20toolkit_6',['C-Menu - A User Interface Toolkit',['../d7/d81/a01365.html',1,'']]],
  ['about_20c_20menu_7',['Breaking News About C-Menu',['../index.html#breaking-news-about-c-menu',1,'']]],
  ['about_20c_20menu_20and_20r_20menu_8',['About C-Menu and R-Menu',['../da/dab/a01362.html#about-c-menu-and-r-menu',1,'']]],
  ['about_20gmtime_5fr_9',['Important note about &lt;span class=&quot;tt&quot;&gt;gmtime_r()&lt;/span&gt;',['../de/d1f/a01364.html#important-note-about-gmtime_r',1,'']]],
  ['added_10',['Added',['../d9/d79/a01360.html#added',1,'']]],
  ['addendum_11',['C-Menu-Addendum',['../de/d5c/a01358.html',1,'']]],
  ['additional_20resources_12',['Additional Resources',['../da/dab/a01362.html#additional-resources',1,'']]],
  ['address_20space_13',['Demand Paged Virtual Address Space',['../d6/dfe/a01366.html#demand-paged-virtual-address-space',1,'']]],
  ['against_20c_20menu_14',['Running Valgrind Against C-Menu',['../d8/dbe/a01370.html',1,'']]],
  ['ai_20overview_20of_20developer_20folke_15',['AI Overview of Developer Folke',['../da/dab/a01362.html#ai-overview-of-developer-folke',1,'']]],
  ['ai_20overview_20of_20developer_20norcalli_16',['AI Overview of Developer Norcalli',['../da/dab/a01362.html#ai-overview-of-developer-norcalli',1,'']]],
  ['aids_20soap_20box_17',['Visual Aids Soap-box',['../dd/d8b/a01363.html#visual-aids-soap-box',1,'']]],
  ['alacritty_18',['Alacritty',['../d1/d17/a01369.html#alacritty',1,'']]],
  ['alacritty_20and_20kitty_19',['Alacritty and Kitty',['../d2/d1f/a01361.html#alacritty-and-kitty',1,'']]],
  ['alacritty_20configuration_20',['Alacritty Configuration',['../da/dab/a01362.html#alacritty-configuration',1,'']]],
  ['alternate_20bash_20executable_21',['Alternate Bash Executable',['../da/dab/a01362.html#alternate-bash-executable',1,'']]],
  ['alternative_22',['Alternative',['../dc/d4b/a01359.html#rsh---a-root-shell-alternative',1,'RSH - A Root Shell Alternative'],['../d7/d81/a01365.html#rsh---a-root-shell-alternative-1',1,'RSH - A Root Shell Alternative']]],
  ['an_20issue_20on_20the_20c_20menu_20github_20repository_23',['an issue on the C Menu GitHub repository',['../de/d5c/a01358.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../df/d10/a01357.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../da/dab/a01362.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['and_24',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../dd/d8b/a01363.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['and_20color_20manual_20pages_25',['View and Color Manual Pages',['../d6/dfe/a01366.html#view-and-color-manual-pages',1,'']]],
  ['and_20comments_26',['User Choices, Commands, and comments',['../dc/d4b/a01359.html#user-choices-commands-and-comments',1,'']]],
  ['and_20editing_27',['Form for Data Entry and Editing',['../d6/dfe/a01366.html#form-for-data-entry-and-editing',1,'']]],
  ['and_20editor_20settings_28',['Terminal and Editor Settings',['../d1/d17/a01369.html#terminal-and-editor-settings',1,'']]],
  ['and_20footprint_29',['Performance and Footprint',['../d7/d81/a01365.html#performance-and-footprint',1,'']]],
  ['and_20gawk_30',['High Precision Math With C-Menu and Gawk',['../dd/d8b/a01363.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['and_20kitty_31',['Alacritty and Kitty',['../d2/d1f/a01361.html#alacritty-and-kitty',1,'']]],
  ['and_20lf_32',['Menu, Form, Pick, View, C-Keys, RSH, and lf',['../d6/dfe/a01366.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'']]],
  ['and_20macos_33',['Installing Rust On Linux and macOS',['../da/dab/a01362.html#installing-rust-on-linux-and-macos',1,'']]],
  ['and_20optimizations_34',['Design Philosophy and Optimizations',['../dd/d86/a01367.html#design-philosophy-and-optimizations',1,'']]],
  ['and_20pop_20up_20menus_20forms_20pickers_20views_20ckeys_20etc_35',['Drop-down and Pop-up Menus, Forms, Pickers, Views, Ckeys, etc',['../dd/d8b/a01363.html#drop-down-and-pop-up-menus-forms-pickers-views-ckeys-etc',1,'']]],
  ['and_20r_20menu_36',['About C-Menu and R-Menu',['../da/dab/a01362.html#about-c-menu-and-r-menu',1,'']]],
  ['and_20requirements_37',['Platform and Requirements',['../index.html#platform-and-requirements',1,'']]],
  ['and_20serialization_38',['Asynchronous Communication and Serialization',['../dd/d0c/a01368.html#asynchronous-communication-and-serialization',1,'']]],
  ['and_20user_20guide_39',['Roadmap for API Documentation and User Guide',['../df/d10/a01357.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['and_20version_20h_40',['include/version.h and version.h',['../df/d10/a01357.html#includeversionh-and-versionh',1,'']]],
  ['and_20view_20api_41',['Menu, Form, Pick, and View API',['../dd/d8b/a01363.html#menu-form-pick-and-view-api',1,'']]],
  ['and_20view_20h_42',['include/menu.h, form.h, pick.h, and view.h',['../df/d10/a01357.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_43',['any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../de/d5c/a01358.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../df/d10/a01357.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../da/dab/a01362.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['api_44',['API',['../df/d10/a01357.html',1,'API'],['../d7/d81/a01365.html#api',1,'API'],['../d6/dfe/a01366.html#c-menu-api',1,'C-Menu API'],['../dd/d8b/a01363.html#menu-form-pick-and-view-api',1,'Menu, Form, Pick, and View API'],['../da/dab/a01362.html#neovim-linkage-to-the-c-menu-api',1,'Neovim Linkage to the C-Menu API']]],
  ['api_20documentation_20and_20user_20guide_45',['Roadmap for API Documentation and User Guide',['../df/d10/a01357.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['api_20integration_20with_20neovim_46',['&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;',['../d6/dfe/a01366.html#_new-api-integration-with-neovim_',1,'']]],
  ['api_20organization_47',['API Organization',['../df/d10/a01357.html#api-organization',1,'']]],
  ['application_20menu_48',['Example Application Menu',['../dc/d4b/a01359.html#example-application-menu',1,'']]],
  ['applications_20menu_49',['C-Menu Example Applications Menu',['../de/d5c/a01358.html#c-menu-example-applications-menu',1,'']]],
  ['are_20my_20header_20files_50',['Menu lf - Where Are My Header Files?',['../dd/d8b/a01363.html#menu-lf---where-are-my-header-files',1,'']]],
  ['art_20in_20snacks_20nvim_51',['To Use the Neovim Unicode Art in Snacks.nvim',['../da/dab/a01362.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['asynchronous_20communication_20and_20serialization_52',['Asynchronous Communication and Serialization',['../dd/d0c/a01368.html#asynchronous-communication-and-serialization',1,'']]]
];
