var searchData=
[
  ['a_20box_20window_0',['View In a Box Window',['../d7/def/a01538.html#view-in-a-box-window',1,'']]],
  ['a_20bug_1',['🐛 How to Report a Bug',['../dc/d93/a01535.html#autotoc_md-how-to-report-a-bug',1,'']]],
  ['a_20feature_2',['💡 How to Suggest a Feature',['../dc/d93/a01535.html#autotoc_md-how-to-suggest-a-feature',1,'']]],
  ['a_20pager_20for_20viewing_20files_3',['View - A pager for viewing files',['../d5/dc8/a01541.html#view---a-pager-for-viewing-files',1,'']]],
  ['a_20picker_4',['Pick - A Picker',['../dd/dba/a01545.html#pick---a-picker',1,'']]],
  ['a_20pull_20request_5',['4. Open a Pull Request',['../dc/d93/a01535.html#autotoc_md4-open-a-pull-request',1,'']]],
  ['a_20regular_20expression_20file_20finder_6',['A Regular Expression File Finder',['../d5/dc8/a01541.html#lf---a-regular-expression-file-finder',1,'lf - A Regular Expression File Finder'],['../d7/d1d/a01554.html#lf---a-regular-expression-file-finder-1',1,'lf - A Regular Expression File Finder']]],
  ['a_20root_20shell_20alternative_7',['A Root Shell Alternative',['../d5/dc8/a01541.html#rsh---a-root-shell-alternative',1,'RSH - A Root Shell Alternative'],['../d7/d1d/a01554.html#rsh---a-root-shell-alternative-1',1,'RSH - A Root Shell Alternative']]],
  ['a_20use_20case_8',['RSH - A Use Case',['../d4/d62/a01531.html#rsh---a-use-case',1,'']]],
  ['a_20user_20interface_20toolkit_9',['C-Menu - A User Interface Toolkit',['../d5/dc8/a01541.html',1,'']]],
  ['about_20c_20menu_20and_20r_20menu_10',['About C-Menu and R-Menu',['../df/d3f/a01537.html#about-c-menu-and-r-menu',1,'']]],
  ['about_20gmtime_5fr_11',['Important note about &lt;span class=&quot;tt&quot;&gt;gmtime_r()&lt;/span&gt;',['../d3/d4c/a01540.html#important-note-about-gmtime_r',1,'']]],
  ['access_20to_20rsh_12',['RESTRICT ACCESS TO RSH',['../d8/daf/a01550.html#restrict-access-to-rsh',1,'']]],
  ['addendum_13',['C-Menu-Addendum',['../d4/d62/a01531.html',1,'']]],
  ['additional_20resources_14',['Additional Resources',['../df/d3f/a01537.html#additional-resources',1,'']]],
  ['address_20space_15',['Demand Paged Virtual Address Space',['../dd/dba/a01545.html#demand-paged-virtual-address-space',1,'']]],
  ['against_20c_20menu_16',['Running Valgrind Against C-Menu',['../de/d2c/a01553.html',1,'']]],
  ['ai_20overview_20of_20developer_20folke_17',['AI Overview of Developer Folke',['../df/d3f/a01537.html#ai-overview-of-developer-folke',1,'']]],
  ['ai_20overview_20of_20developer_20norcalli_18',['AI Overview of Developer Norcalli',['../df/d3f/a01537.html#ai-overview-of-developer-norcalli',1,'']]],
  ['aids_20soap_20box_19',['Visual Aids Soap-box',['../d7/def/a01538.html#visual-aids-soap-box',1,'']]],
  ['alacritty_20',['Alacritty',['../d5/df4/a01551.html#alacritty',1,'']]],
  ['alacritty_20and_20kitty_21',['Alacritty and Kitty',['../d0/da6/a01536.html#alacritty-and-kitty',1,'']]],
  ['alacritty_20configuration_22',['Alacritty Configuration',['../df/d3f/a01537.html#alacritty-configuration',1,'']]],
  ['also_23',['ALSO',['../dc/d2d/a01534.html#see-also',1,'SEE ALSO'],['../d6/d02/a01542.html#see-also-1',1,'SEE ALSO'],['../db/d08/a01543.html#see-also-2',1,'SEE ALSO'],['../d8/daf/a01550.html#see-also-4',1,'SEE ALSO']]],
  ['also_24',['also',['../da/dc7/a01548.html#see-also-3',1,'See also'],['../index.html#see-also-5',1,'See also']]],
  ['alternate_20bash_20executable_25',['Alternate Bash Executable',['../df/d3f/a01537.html#alternate-bash-executable',1,'']]],
  ['alternative_26',['Alternative',['../d5/dc8/a01541.html#rsh---a-root-shell-alternative',1,'RSH - A Root Shell Alternative'],['../d7/d1d/a01554.html#rsh---a-root-shell-alternative-1',1,'RSH - A Root Shell Alternative']]],
  ['an_20issue_20on_20the_20c_20menu_20github_20repository_27',['an issue on the C Menu GitHub repository',['../d4/d62/a01531.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../db/dce/a01529.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../df/d3f/a01537.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['ancillary_20components_28',['ANCILLARY COMPONENTS',['../dc/d2d/a01534.html#ancillary-components',1,'']]],
  ['and_29',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../d7/def/a01538.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['and_20color_20manual_20pages_30',['View and Color Manual Pages',['../dd/dba/a01545.html#view-and-color-manual-pages',1,'']]],
  ['and_20comments_31',['and comments',['../dc/d0c/a01532.html#user-choices-commands-and-comments',1,'User Choices, Commands, and comments'],['../d6/d83/a01544.html#user-choices-commands-and-comments-1',1,'User Choices, Commands, and comments']]],
  ['and_20editing_32',['Form for Data Entry and Editing',['../dd/dba/a01545.html#form-for-data-entry-and-editing',1,'']]],
  ['and_20editor_20settings_33',['Terminal and Editor Settings',['../d5/df4/a01551.html#terminal-and-editor-settings',1,'']]],
  ['and_20footprint_34',['Performance and Footprint',['../d5/dc8/a01541.html#performance-and-footprint',1,'']]],
  ['and_20gawk_35',['High Precision Math With C-Menu and Gawk',['../d7/def/a01538.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['and_20kitty_36',['Alacritty and Kitty',['../d0/da6/a01536.html#alacritty-and-kitty',1,'']]],
  ['and_20lf_37',['Menu, Form, Pick, View, C-Keys, RSH, and lf',['../dd/dba/a01545.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'']]],
  ['and_20macos_38',['Installing Rust On Linux and macOS',['../df/d3f/a01537.html#installing-rust-on-linux-and-macos',1,'']]],
  ['and_20optimizations_39',['Design Philosophy and Optimizations',['../d9/da1/a01546.html#design-philosophy-and-optimizations',1,'']]],
  ['and_20pop_20up_20menus_20forms_20pickers_20views_20ckeys_20etc_40',['Drop-down and Pop-up Menus, Forms, Pickers, Views, Ckeys, etc',['../d7/def/a01538.html#drop-down-and-pop-up-menus-forms-pickers-views-ckeys-etc',1,'']]],
  ['and_20push_41',['3. Commit and Push',['../dc/d93/a01535.html#autotoc_md3-commit-and-push',1,'']]],
  ['and_20r_20menu_42',['About C-Menu and R-Menu',['../df/d3f/a01537.html#about-c-menu-and-r-menu',1,'']]],
  ['and_20requirements_43',['and Requirements',['../da/dc7/a01548.html#platform-and-requirements',1,'Platform and Requirements'],['../index.html#platform-and-requirements-1',1,'Platform and Requirements']]],
  ['and_20serialization_44',['Asynchronous Communication and Serialization',['../d3/d1b/a01549.html#asynchronous-communication-and-serialization',1,'']]],
  ['and_20user_20guide_45',['Roadmap for API Documentation and User Guide',['../db/dce/a01529.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['and_20version_20h_46',['include/version.h and version.h',['../db/dce/a01529.html#includeversionh-and-versionh',1,'']]],
  ['and_20view_20api_47',['Menu, Form, Pick, and View API',['../d7/def/a01538.html#menu-form-pick-and-view-api',1,'']]],
  ['and_20view_20h_48',['include/menu.h, form.h, pick.h, and view.h',['../db/dce/a01529.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['announcement_49',['C-Menu-0.2.9 Announcement',['../index.html#c-menu-029-announcement',1,'']]],
  ['any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_50',['any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../d4/d62/a01531.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../db/dce/a01529.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../df/d3f/a01537.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['api_51',['API',['../db/dce/a01529.html',1,'API'],['../d5/dc8/a01541.html#api',1,'API'],['../dd/dba/a01545.html#c-menu-api',1,'C-Menu API'],['../d7/def/a01538.html#menu-form-pick-and-view-api',1,'Menu, Form, Pick, and View API'],['../df/d3f/a01537.html#neovim-linkage-to-the-c-menu-api',1,'Neovim Linkage to the C-Menu API']]],
  ['api_20documentation_20and_20user_20guide_52',['Roadmap for API Documentation and User Guide',['../db/dce/a01529.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['api_20integration_20with_20neovim_53',['&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;',['../dd/dba/a01545.html#_new-api-integration-with-neovim_',1,'']]],
  ['api_20organization_54',['API Organization',['../db/dce/a01529.html#api-organization',1,'']]],
  ['application_20builder_55',['NAME C-Menu Application Builder',['../dc/d2d/a01534.html#name-c-menu-application-builder',1,'']]],
  ['application_20menu_56',['Application Menu',['../dc/d0c/a01532.html#example-application-menu',1,'Example Application Menu'],['../d6/d83/a01544.html#example-application-menu-1',1,'Example Application Menu']]],
  ['applications_20menu_57',['C-Menu Example Applications Menu',['../d4/d62/a01531.html#c-menu-example-applications-menu',1,'']]],
  ['are_20my_20header_20files_58',['Menu lf - Where Are My Header Files?',['../d7/def/a01538.html#menu-lf---where-are-my-header-files',1,'']]],
  ['art_20in_20snacks_20nvim_59',['To Use the Neovim Unicode Art in Snacks.nvim',['../df/d3f/a01537.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['as_20the_20default_60',['Setting the New Theme as the Default',['../d0/db9/a01552.html#setting-the-new-theme-as-the-default',1,'']]],
  ['asynchronous_20communication_20and_20serialization_61',['Asynchronous Communication and Serialization',['../d3/d1b/a01549.html#asynchronous-communication-and-serialization',1,'']]],
  ['authority_62',['ROOT AUTHORITY',['../d8/daf/a01550.html#root-authority',1,'']]]
];
