var searchData=
[
  ['icon_0',['What&apos;s the Icon?',['../de/de9/a00322.html#whats-the-icon',1,'']]],
  ['if_20you_20can_20t_20stop_20typing_20vi_1',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../d4/d8f/a00324.html#if-you-cant-stop-typing-vi',1,'']]],
  ['if_20you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_2',['If you encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../da/de0/a00317.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../de/d55/a00323.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['in_20a_20box_20window_3',['View In a Box Window',['../de/de9/a00322.html#view-in-a-box-window',1,'']]],
  ['in_20view_4',['Large Log File in View',['../index.html#large-log-file-in-view',1,'']]],
  ['include_20cm_20h_5',['include/cm.h',['../da/de0/a00317.html#includecmh',1,'']]],
  ['include_20common_20h_6',['include/common.h',['../da/de0/a00317.html#includecommonh',1,'']]],
  ['include_20menu_20h_20form_20h_20pick_20h_20and_20view_20h_7',['include/menu.h, form.h, pick.h, and view.h',['../da/de0/a00317.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['include_20version_20h_20and_20version_20h_8',['include/version.h and version.h',['../da/de0/a00317.html#includeversionh-and-versionh',1,'']]],
  ['indicator_20shell_20prompts_9',['Privilege Indicator Shell Prompts',['../d4/d8f/a00324.html#privilege-indicator-shell-prompts',1,'']]],
  ['inode_10',['Menu - What Happened to Delete by Inode',['../de/de9/a00322.html#menu---what-happened-to-delete-by-inode',1,'']]],
  ['input_11',['C-Keys - Diagnose Keyboard/Mouse Input',['../index.html#c-keys---diagnose-keyboardmouse-input',1,'']]],
  ['install_20tree_20sitter_20cli_12',['Install Tree-Sitter-CLI',['../de/de9/a00322.html#install-tree-sitter-cli',1,'']]],
  ['installation_13',['Finish the installation',['../de/d55/a00323.html#finish-the-installation',1,'']]],
  ['installation_20guide_14',['Installation Guide',['../de/d55/a00323.html',1,'']]],
  ['installing_20bat_15',['Installing Bat',['../db/d53/a00321.html#installing-bat',1,'']]],
  ['installing_20ripgrep_16',['Installing Ripgrep',['../db/d53/a00321.html#installing-ripgrep',1,'']]],
  ['installing_20rust_17',['Installing Rust',['../db/d53/a00321.html#installing-rust',1,'']]],
  ['installing_20rust_20on_20linux_20and_20macos_18',['Installing Rust On Linux and macOS',['../db/d53/a00321.html#installing-rust-on-linux-and-macos',1,'']]],
  ['installment_20loan_20calculator_19',['Menu - Using the Installment Loan Calculator',['../de/de9/a00322.html#menu---using-the-installment-loan-calculator',1,'']]],
  ['instead_20of_20ls_20',['Use lsd instead of ls',['../d4/d8f/a00324.html#use-lsd-instead-of-ls',1,'']]],
  ['integrating_20external_20executables_21',['Menu Form - Integrating External Executables',['../de/de9/a00322.html#menu-form---integrating-external-executables',1,'']]],
  ['intended_22',['Highlights (Pun Intended)',['../index.html#highlights-pun-intended',1,'']]],
  ['interface_20toolkit_23',['A User Interface Toolkit',['../index.html',1,'']]],
  ['interprocess_20communications_24',['Menu - Interprocess Communications',['../de/de9/a00322.html#menu---interprocess-communications',1,'']]],
  ['introduction_25',['Introduction',['../index.html#c-menu-introduction',1,'C-Menu Introduction'],['../da/de0/a00317.html#introduction',1,'Introduction'],['../d2/d41/a00318.html#introduction-1',1,'Introduction'],['../db/d53/a00321.html#introduction-2',1,'Introduction']]],
  ['issue_20on_20the_20c_20menu_20github_20repository_26',['issue on the C Menu GitHub repository',['../da/de0/a00317.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../de/d55/a00323.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_27',['issues or have questions feel free to open an issue on the C Menu GitHub repository',['../da/de0/a00317.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../de/d55/a00323.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['it_28',['Just Do It!',['../index.html#just-do-it',1,'']]],
  ['items_29',['Selecting Items',['../d2/d41/a00318.html#selecting-items',1,'']]]
];
