var searchData=
[
  ['a_20box_20window_0',['View In a Box Window',['../d2/d9b/a01433.html#view-in-a-box-window',1,'']]],
  ['a_20bug_1',['🐛 How to Report a Bug',['../d8/dd0/a01430.html#autotoc_md-how-to-report-a-bug',1,'']]],
  ['a_20feature_2',['💡 How to Suggest a Feature',['../d8/dd0/a01430.html#autotoc_md-how-to-suggest-a-feature',1,'']]],
  ['a_20pager_20for_20viewing_20files_3',['View - A pager for viewing files',['../dc/d85/a01436.html#view---a-pager-for-viewing-files',1,'']]],
  ['a_20picker_4',['Pick - A Picker',['../df/d31/a01440.html#pick---a-picker',1,'']]],
  ['a_20pull_20request_5',['4. Open a Pull Request',['../d8/dd0/a01430.html#autotoc_md4-open-a-pull-request',1,'']]],
  ['a_20regular_20expression_20file_20finder_6',['A Regular Expression File Finder',['../dc/d85/a01436.html#lf---a-regular-expression-file-finder',1,'lf - A Regular Expression File Finder'],['../d2/d95/a01449.html#lf---a-regular-expression-file-finder-1',1,'lf - A Regular Expression File Finder']]],
  ['a_20root_20shell_20alternative_7',['A Root Shell Alternative',['../dc/d85/a01436.html#rsh---a-root-shell-alternative',1,'RSH - A Root Shell Alternative'],['../d2/d95/a01449.html#rsh---a-root-shell-alternative-1',1,'RSH - A Root Shell Alternative']]],
  ['a_20use_20case_8',['RSH - A Use Case',['../dc/de6/a01426.html#rsh---a-use-case',1,'']]],
  ['a_20user_20interface_20toolkit_9',['C-Menu - A User Interface Toolkit',['../dc/d85/a01436.html',1,'']]],
  ['about_20c_20menu_20and_20r_20menu_10',['About C-Menu and R-Menu',['../db/dff/a01432.html#about-c-menu-and-r-menu',1,'']]],
  ['about_20gmtime_5fr_11',['Important note about &lt;span class=&quot;tt&quot;&gt;gmtime_r()&lt;/span&gt;',['../d3/d95/a01435.html#important-note-about-gmtime_r',1,'']]],
  ['access_20to_20rsh_12',['RESTRICT ACCESS TO RSH',['../d9/d6f/a01445.html#restrict-access-to-rsh',1,'']]],
  ['added_13',['Added',['../d2/db1/a01428.html#added',1,'']]],
  ['addendum_14',['C-Menu-Addendum',['../dc/de6/a01426.html',1,'']]],
  ['additional_20resources_15',['Additional Resources',['../db/dff/a01432.html#additional-resources',1,'']]],
  ['address_20space_16',['Demand Paged Virtual Address Space',['../df/d31/a01440.html#demand-paged-virtual-address-space',1,'']]],
  ['against_20c_20menu_17',['Running Valgrind Against C-Menu',['../dd/d08/a01448.html',1,'']]],
  ['ai_20overview_20of_20developer_20folke_18',['AI Overview of Developer Folke',['../db/dff/a01432.html#ai-overview-of-developer-folke',1,'']]],
  ['ai_20overview_20of_20developer_20norcalli_19',['AI Overview of Developer Norcalli',['../db/dff/a01432.html#ai-overview-of-developer-norcalli',1,'']]],
  ['aids_20soap_20box_20',['Visual Aids Soap-box',['../d2/d9b/a01433.html#visual-aids-soap-box',1,'']]],
  ['alacritty_21',['Alacritty',['../d8/d22/a01446.html#alacritty',1,'']]],
  ['alacritty_20and_20kitty_22',['Alacritty and Kitty',['../d7/d8b/a01431.html#alacritty-and-kitty',1,'']]],
  ['alacritty_20configuration_23',['Alacritty Configuration',['../db/dff/a01432.html#alacritty-configuration',1,'']]],
  ['also_24',['ALSO',['../d1/d3b/a01429.html#see-also',1,'SEE ALSO'],['../d9/db0/a01437.html#see-also-1',1,'SEE ALSO'],['../d5/dd0/a01438.html#see-also-2',1,'SEE ALSO'],['../d9/d6f/a01445.html#see-also-3',1,'SEE ALSO']]],
  ['alternate_20bash_20executable_25',['Alternate Bash Executable',['../db/dff/a01432.html#alternate-bash-executable',1,'']]],
  ['alternative_26',['Alternative',['../dc/d85/a01436.html#rsh---a-root-shell-alternative',1,'RSH - A Root Shell Alternative'],['../d2/d95/a01449.html#rsh---a-root-shell-alternative-1',1,'RSH - A Root Shell Alternative']]],
  ['an_20issue_20on_20the_20c_20menu_20github_20repository_27',['an issue on the C Menu GitHub repository',['../dc/de6/a01426.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../db/df2/a01425.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../db/dff/a01432.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['ancillary_20components_28',['ANCILLARY COMPONENTS',['../d1/d3b/a01429.html#ancillary-components',1,'']]],
  ['and_29',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../d2/d9b/a01433.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['and_20color_20manual_20pages_30',['View and Color Manual Pages',['../df/d31/a01440.html#view-and-color-manual-pages',1,'']]],
  ['and_20comments_31',['and comments',['../db/d78/a01427.html#user-choices-commands-and-comments',1,'User Choices, Commands, and comments'],['../d7/dfd/a01439.html#user-choices-commands-and-comments-1',1,'User Choices, Commands, and comments']]],
  ['and_20editing_32',['Form for Data Entry and Editing',['../df/d31/a01440.html#form-for-data-entry-and-editing',1,'']]],
  ['and_20editor_20settings_33',['Terminal and Editor Settings',['../d8/d22/a01446.html#terminal-and-editor-settings',1,'']]],
  ['and_20footprint_34',['Performance and Footprint',['../dc/d85/a01436.html#performance-and-footprint',1,'']]],
  ['and_20gawk_35',['High Precision Math With C-Menu and Gawk',['../d2/d9b/a01433.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['and_20kitty_36',['Alacritty and Kitty',['../d7/d8b/a01431.html#alacritty-and-kitty',1,'']]],
  ['and_20lf_37',['Menu, Form, Pick, View, C-Keys, RSH, and lf',['../df/d31/a01440.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'']]],
  ['and_20macos_38',['Installing Rust On Linux and macOS',['../db/dff/a01432.html#installing-rust-on-linux-and-macos',1,'']]],
  ['and_20optimizations_39',['Design Philosophy and Optimizations',['../d5/df9/a01441.html#design-philosophy-and-optimizations',1,'']]],
  ['and_20pop_20up_20menus_20forms_20pickers_20views_20ckeys_20etc_40',['Drop-down and Pop-up Menus, Forms, Pickers, Views, Ckeys, etc',['../d2/d9b/a01433.html#drop-down-and-pop-up-menus-forms-pickers-views-ckeys-etc',1,'']]],
  ['and_20push_41',['3. Commit and Push',['../d8/dd0/a01430.html#autotoc_md3-commit-and-push',1,'']]],
  ['and_20r_20menu_42',['About C-Menu and R-Menu',['../db/dff/a01432.html#about-c-menu-and-r-menu',1,'']]],
  ['and_20requirements_43',['and Requirements',['../d6/d65/a01443.html#platform-and-requirements',1,'Platform and Requirements'],['../index.html#platform-and-requirements-1',1,'Platform and Requirements']]],
  ['and_20serialization_44',['Asynchronous Communication and Serialization',['../d7/d32/a01444.html#asynchronous-communication-and-serialization',1,'']]],
  ['and_20user_20guide_45',['Roadmap for API Documentation and User Guide',['../db/df2/a01425.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['and_20version_20h_46',['include/version.h and version.h',['../db/df2/a01425.html#includeversionh-and-versionh',1,'']]],
  ['and_20view_20api_47',['Menu, Form, Pick, and View API',['../d2/d9b/a01433.html#menu-form-pick-and-view-api',1,'']]],
  ['and_20view_20h_48',['include/menu.h, form.h, pick.h, and view.h',['../db/df2/a01425.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_49',['any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../dc/de6/a01426.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../db/df2/a01425.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../db/dff/a01432.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['api_50',['API',['../db/df2/a01425.html',1,'API'],['../dc/d85/a01436.html#api',1,'API'],['../df/d31/a01440.html#c-menu-api',1,'C-Menu API'],['../d2/d9b/a01433.html#menu-form-pick-and-view-api',1,'Menu, Form, Pick, and View API'],['../db/dff/a01432.html#neovim-linkage-to-the-c-menu-api',1,'Neovim Linkage to the C-Menu API']]],
  ['api_20documentation_20and_20user_20guide_51',['Roadmap for API Documentation and User Guide',['../db/df2/a01425.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['api_20integration_20with_20neovim_52',['&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;',['../df/d31/a01440.html#_new-api-integration-with-neovim_',1,'']]],
  ['api_20organization_53',['API Organization',['../db/df2/a01425.html#api-organization',1,'']]],
  ['application_20builder_54',['NAME C-Menu Application Builder',['../d1/d3b/a01429.html#name-c-menu-application-builder',1,'']]],
  ['application_20menu_55',['Application Menu',['../db/d78/a01427.html#example-application-menu',1,'Example Application Menu'],['../d7/dfd/a01439.html#example-application-menu-1',1,'Example Application Menu']]],
  ['applications_20menu_56',['C-Menu Example Applications Menu',['../dc/de6/a01426.html#c-menu-example-applications-menu',1,'']]],
  ['are_20my_20header_20files_57',['Menu lf - Where Are My Header Files?',['../d2/d9b/a01433.html#menu-lf---where-are-my-header-files',1,'']]],
  ['art_20in_20snacks_20nvim_58',['To Use the Neovim Unicode Art in Snacks.nvim',['../db/dff/a01432.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['asynchronous_20communication_20and_20serialization_59',['Asynchronous Communication and Serialization',['../d7/d32/a01444.html#asynchronous-communication-and-serialization',1,'']]],
  ['authority_60',['ROOT AUTHORITY',['../d9/d6f/a01445.html#root-authority',1,'']]]
];
