var searchData=
[
  ['t_20f_20and_0',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../dd/d8b/a01363.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['t_20stop_20typing_20vi_1',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../d1/d17/a01369.html#if-you-cant-stop-typing-vi',1,'']]],
  ['t_20work_2',['Some Menu Selections Don&apos;t work',['../dd/d8b/a01363.html#some-menu-selections-dont-work',1,'']]],
  ['table_20of_20contents_3',['Table of Contents',['../de/d5c/a01358.html#table-of-contents',1,'Table of Contents'],['../d2/d1f/a01361.html#table-of-contents-1',1,'Table of Contents'],['../da/dab/a01362.html#table-of-contents-2',1,'Table of Contents'],['../dd/d8b/a01363.html#table-of-contents-3',1,'Table of Contents'],['../d7/d81/a01365.html#table-of-contents-4',1,'Table of Contents'],['../d6/dfe/a01366.html#table-of-contents-5',1,'Table of Contents'],['../d1/d17/a01369.html#table-of-contents-6',1,'Table of Contents'],['../index.html#table-of-contents-7',1,'Table of Contents']]],
  ['target_20recommended_4',['Using the Makefile target (recommended)',['../d8/dbe/a01370.html#using-the-makefile-target-recommended',1,'']]],
  ['tasks_20to_20complete_20before_200_203_200_5',['0.2.9 Tasks to Complete before 0.3.0',['../dd/d0c/a01368.html#autotoc_md029-tasks-to-complete-before-030',1,'']]],
  ['terminal_20and_20editor_20settings_6',['Terminal and Editor Settings',['../d1/d17/a01369.html#terminal-and-editor-settings',1,'']]],
  ['terminal_20configurations_7',['Terminal Configurations',['../da/dab/a01362.html#example-terminal-configurations',1,'Example Terminal Configurations'],['../d1/d17/a01369.html#terminal-configurations',1,'Terminal Configurations']]],
  ['terminal_20emulator_8',['Customize Your Terminal Emulator',['../da/dab/a01362.html#customize-your-terminal-emulator',1,'']]],
  ['test_20cases_9',['Revised interpretation of the original test cases',['../de/d1f/a01364.html#revised-interpretation-of-the-original-test-cases',1,'']]],
  ['testing_20tree_20sitter_10',['Testing Tree-Sitter',['../da/dab/a01362.html#testing-tree-sitter',1,'']]],
  ['text_11',['Text',['../dc/d4b/a01359.html#text',1,'']]],
  ['the_20c_20menu_20api_12',['Neovim Linkage to the C-Menu API',['../da/dab/a01362.html#neovim-linkage-to-the-c-menu-api',1,'']]],
  ['the_20c_20menu_20github_20repository_13',['the C Menu GitHub repository',['../de/d5c/a01358.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../df/d10/a01357.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../da/dab/a01362.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['the_20design_20works_14',['Why the Design Works',['../index.html#why-the-design-works',1,'']]],
  ['the_20horizon_15',['0.3.0 On the Horizon',['../dd/d0c/a01368.html#autotoc_md030-on-the-horizon',1,'']]],
  ['the_20icon_16',['What&apos;s the Icon?',['../dd/d8b/a01363.html#whats-the-icon',1,'']]],
  ['the_20installation_17',['Finish the installation',['../d7/d81/a01365.html#finish-the-installation',1,'']]],
  ['the_20installment_20loan_20calculator_18',['Menu - Using the Installment Loan Calculator',['../dd/d8b/a01363.html#menu---using-the-installment-loan-calculator',1,'']]],
  ['the_20makefile_20target_20recommended_19',['Using the Makefile target (recommended)',['../d8/dbe/a01370.html#using-the-makefile-target-recommended',1,'']]],
  ['the_20neovim_20unicode_20art_20in_20snacks_20nvim_20',['To Use the Neovim Unicode Art in Snacks.nvim',['../da/dab/a01362.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['the_20original_20test_20cases_21',['Revised interpretation of the original test cases',['../de/d1f/a01364.html#revised-interpretation-of-the-original-test-cases',1,'']]],
  ['the_20previous_20results_20looked_20contradictory_22',['Why the previous results looked contradictory',['../de/d1f/a01364.html#why-the-previous-results-looked-contradictory',1,'']]],
  ['the_20same_20file_20with_20view_23',['Screenshot of the Same File With View',['../d6/dfe/a01366.html#screenshot-of-the-same-file-with-view',1,'']]],
  ['through_20obscurity_24',['Security Through Obscurity',['../d1/d17/a01369.html#security-through-obscurity',1,'']]],
  ['time_20conundrum_25',['DATE/TIME CONUNDRUM',['../de/d1f/a01364.html',1,'']]],
  ['to_20colorize_20html_20color_20codes_26',['View - How to Colorize HTML Color Codes',['../dd/d8b/a01363.html#view---how-to-colorize-html-color-codes',1,'']]],
  ['to_20colorize_20manual_20pages_27',['View - How to Colorize Manual Pages',['../dd/d8b/a01363.html#view---how-to-colorize-manual-pages',1,'']]],
  ['to_20complete_20before_200_203_200_28',['0.2.9 Tasks to Complete before 0.3.0',['../dd/d0c/a01368.html#autotoc_md029-tasks-to-complete-before-030',1,'']]],
  ['to_20customize_20colors_29',['View - How to Customize Colors',['../dd/d8b/a01363.html#view---how-to-customize-colors',1,'']]],
  ['to_20delete_20by_20inode_30',['Menu - What Happened to Delete by Inode',['../dd/d8b/a01363.html#menu---what-happened-to-delete-by-inode',1,'']]],
  ['to_20get_20c_20menu_31',['to get C Menu',['../df/d10/a01357.html#how-to-get-c-menu',1,'How to get C-Menu'],['../de/d5c/a01358.html#how-to-get-c-menu-1',1,'How to get C-Menu'],['../da/dab/a01362.html#how-to-get-c-menu-2',1,'How to get C-Menu']]],
  ['to_20install_20folke_20s_20lazyvim_32',['To Install Folke&apos;s LazyVim',['../da/dab/a01362.html#to-install-folkes-lazyvim',1,'']]],
  ['to_20install_20folke_20s_20snacks_20nvim_20colorizer_33',['To Install Folke&apos;s Snacks.nvim-colorizer',['../da/dab/a01362.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['to_20install_20norcalli_20s_20nvim_20colorizer_20lua_34',['To Install Norcalli&apos;s nvim-colorizer.lua',['../da/dab/a01362.html#to-install-norcallis-nvim-colorizerlua',1,'']]],
  ['to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_35',['to open an issue on the C Menu GitHub repository',['../de/d5c/a01358.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../df/d10/a01357.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../da/dab/a01362.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['to_20run_36',['How to Run',['../d8/dbe/a01370.html#how-to-run',1,'']]],
  ['to_20the_20c_20menu_20api_37',['Neovim Linkage to the C-Menu API',['../da/dab/a01362.html#neovim-linkage-to-the-c-menu-api',1,'']]],
  ['to_20use_20the_20neovim_20unicode_20art_20in_20snacks_20nvim_38',['To Use the Neovim Unicode Art in Snacks.nvim',['../da/dab/a01362.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['to_20use_20tree_20sitter_20with_20view_39',['View - How to Use Tree-Sitter with View',['../dd/d8b/a01363.html#view---how-to-use-tree-sitter-with-view',1,'']]],
  ['toolkit_40',['C-Menu - A User Interface Toolkit',['../d7/d81/a01365.html',1,'']]],
  ['tools_41',['Diagnostic Tools',['../dc/d4b/a01359.html#diagnostic-tools',1,'']]],
  ['tree_20sitter_42',['Tree Sitter',['../da/dab/a01362.html#testing-tree-sitter',1,'Testing Tree-Sitter'],['../da/dab/a01362.html#tree-sitter',1,'Tree-Sitter'],['../d1/d17/a01369.html#tree-sitter-1',1,'Tree-Sitter'],['../dc/d4b/a01359.html#view-c-menu-source-with-tree-sitter',1,'View C-Menu Source With Tree-Sitter']]],
  ['tree_20sitter_20cli_43',['Tree Sitter CLI',['../dd/d8b/a01363.html#install-tree-sitter-cli',1,'Install Tree-Sitter-CLI'],['../da/dab/a01362.html#tree-sitter-cli',1,'Tree-Sitter-CLI']]],
  ['tree_20sitter_20cli_20on_20linux_44',['Tree-Sitter-CLI On Linux',['../da/dab/a01362.html#tree-sitter-cli-on-linux',1,'']]],
  ['tree_20sitter_20cli_20on_20macos_45',['Tree-Sitter-CLI On macOS',['../da/dab/a01362.html#tree-sitter-cli-on-macos',1,'']]],
  ['tree_20sitter_20cli_20on_20windows_46',['Tree-Sitter-CLI On Windows',['../da/dab/a01362.html#tree-sitter-cli-on-windows',1,'']]],
  ['tree_20sitter_20config_20json_47',['Tree-Sitter config.json',['../d1/d17/a01369.html#tree-sitter-configjson',1,'']]],
  ['tree_20sitter_20on_20linux_48',['Tree-Sitter On Linux',['../da/dab/a01362.html#tree-sitter-on-linux',1,'']]],
  ['tree_20sitter_20on_20macos_49',['Tree-Sitter On macOS',['../da/dab/a01362.html#tree-sitter-on-macos',1,'']]],
  ['tree_20sitter_20on_20windows_50',['Tree-Sitter On Windows',['../da/dab/a01362.html#tree-sitter-on-windows',1,'']]],
  ['tree_20sitter_20parsers_51',['Tree-Sitter Parsers',['../da/dab/a01362.html#tree-sitter-parsers',1,'']]],
  ['tree_20sitter_20parsers_20on_20linux_52',['Tree-Sitter Parsers On Linux',['../da/dab/a01362.html#tree-sitter-parsers-on-linux',1,'']]],
  ['tree_20sitter_20parsers_20on_20macos_53',['Tree-Sitter Parsers On macOS',['../da/dab/a01362.html#tree-sitter-parsers-on-macos',1,'']]],
  ['tree_20sitter_20parsers_20on_20windows_54',['Tree-Sitter Parsers On Windows',['../da/dab/a01362.html#tree-sitter-parsers-on-windows',1,'']]],
  ['tree_20sitter_20with_20view_55',['View - How to Use Tree-Sitter with View',['../dd/d8b/a01363.html#view---how-to-use-tree-sitter-with-view',1,'']]],
  ['troubleshooting_56',['Troubleshooting',['../de/d5c/a01358.html#troubleshooting',1,'']]],
  ['truecolor_20support_57',['TrueColor Support',['../dd/d8b/a01363.html#truecolor-support',1,'']]],
  ['type_20specifiers_58',['Form Line Type Specifiers',['../de/d5c/a01358.html#form-line-type-specifiers',1,'']]],
  ['type_20speecifiers_20h_20t_20f_20and_59',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../dd/d8b/a01363.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['types_60',['Types',['../de/d5c/a01358.html#form-data-types',1,'Form Data Types'],['../dc/d4b/a01359.html#form-data-types-1',1,'Form Data Types'],['../d6/dfe/a01366.html#form-data-types-2',1,'Form Data Types'],['../dd/d8b/a01363.html#menu-form---data-types',1,'Menu Form - Data Types']]],
  ['typing_20vi_61',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../d1/d17/a01369.html#if-you-cant-stop-typing-vi',1,'']]]
];
