var searchData=
[
  ['i_20rely_20on_20find_20s_20features_0',['lf is fast, but I rely on find&apos;s features',['../d2/d1f/a01361.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['icon_1',['What&apos;s the Icon?',['../d2/d1f/a01361.html#whats-the-icon',1,'']]],
  ['if_20you_20can_20t_20stop_20typing_20vi_2',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../d6/dfe/a01366.html#if-you-cant-stop-typing-vi',1,'']]],
  ['if_20you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_3',['If you encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../d2/d3f/a01356.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d8/d4e/a01355.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d9/d79/a01360.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['in_20a_20box_20window_4',['View In a Box Window',['../d2/d1f/a01361.html#view-in-a-box-window',1,'']]],
  ['in_20current_20directory_5',['Edit .c Files in Current Directory',['../df/d10/a01357.html#edit-c-files-in-current-directory',1,'']]],
  ['in_20neovim_6',['Completions in Neovim',['../da/dab/a01362.html#completions-in-neovim',1,'']]],
  ['in_20snacks_20nvim_7',['To Use the Neovim Unicode Art in Snacks.nvim',['../d9/d79/a01360.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['in_20view_8',['Large Log File in View',['../dd/d8b/a01363.html#large-log-file-in-view',1,'']]],
  ['include_20cm_20h_9',['include/cm.h',['../d8/d4e/a01355.html#includecmh',1,'']]],
  ['include_20common_20h_10',['include/common.h',['../d8/d4e/a01355.html#includecommonh',1,'']]],
  ['include_20menu_20h_20form_20h_20pick_20h_20and_20view_20h_11',['include/menu.h, form.h, pick.h, and view.h',['../d8/d4e/a01355.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['include_20version_20h_20and_20version_20h_12',['include/version.h and version.h',['../d8/d4e/a01355.html#includeversionh-and-versionh',1,'']]],
  ['indicator_20shell_20prompts_13',['Privilege Indicator Shell Prompts',['../d6/dfe/a01366.html#privilege-indicator-shell-prompts',1,'']]],
  ['initial_20release_14',['1.0.0 - Initial Release',['../d7/d81/a01365.html#autotoc_md100---initial-release',1,'']]],
  ['inode_15',['Menu - What Happened to Delete by Inode',['../d2/d1f/a01361.html#menu---what-happened-to-delete-by-inode',1,'']]],
  ['input_16',['C-Keys - Diagnose Keyboard/Mouse Input',['../dd/d8b/a01363.html#c-keys---diagnose-keyboardmouse-input',1,'']]],
  ['install_20folke_20s_20lazyvim_17',['To Install Folke&apos;s LazyVim',['../d9/d79/a01360.html#to-install-folkes-lazyvim',1,'']]],
  ['install_20folke_20s_20snacks_20nvim_20colorizer_18',['To Install Folke&apos;s Snacks.nvim-colorizer',['../d9/d79/a01360.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['install_20norcalli_20s_20nvim_20colorizer_20lua_19',['To Install Norcalli&apos;s nvim-colorizer.lua',['../d9/d79/a01360.html#to-install-norcallis-nvim-colorizerlua',1,'']]],
  ['install_20tree_20sitter_20cli_20',['Install Tree-Sitter-CLI',['../d2/d1f/a01361.html#install-tree-sitter-cli',1,'']]],
  ['installation_21',['C-Menu INSTALLATION',['../da/dab/a01362.html#c-menu-installation',1,'']]],
  ['installation_22',['Finish the installation',['../da/dab/a01362.html#finish-the-installation',1,'']]],
  ['installing_20bat_23',['Installing Bat',['../d9/d79/a01360.html#installing-bat',1,'']]],
  ['installing_20ripgrep_24',['Installing Ripgrep',['../d9/d79/a01360.html#installing-ripgrep',1,'']]],
  ['installing_20rust_25',['Installing Rust',['../d9/d79/a01360.html#installing-rust',1,'']]],
  ['installing_20rust_20on_20linux_20and_20macos_26',['Installing Rust On Linux and macOS',['../d9/d79/a01360.html#installing-rust-on-linux-and-macos',1,'']]],
  ['installment_20loan_20calculations_27',['Installment Loan Calculations',['../df/d10/a01357.html#installment-loan-calculations',1,'']]],
  ['installment_20loan_20calculator_28',['Menu - Using the Installment Loan Calculator',['../d2/d1f/a01361.html#menu---using-the-installment-loan-calculator',1,'']]],
  ['instead_20of_20ls_29',['Use lsd or eza instead of ls',['../d6/dfe/a01366.html#use-lsd-or-eza-instead-of-ls',1,'']]],
  ['integrating_20external_20executables_30',['Menu Form - Integrating External Executables',['../d2/d1f/a01361.html#menu-form---integrating-external-executables',1,'']]],
  ['integration_20with_20neovim_31',['&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;',['../dd/d8b/a01363.html#_new-api-integration-with-neovim_',1,'']]],
  ['intended_32',['Highlights (Pun Intended)',['../dd/d8b/a01363.html#highlights-pun-intended',1,'']]],
  ['interface_20toolkit_33',['C-Menu - A User Interface Toolkit',['../da/dab/a01362.html',1,'']]],
  ['interprocess_20communications_34',['Menu - Interprocess Communications',['../d2/d1f/a01361.html#menu---interprocess-communications',1,'']]],
  ['introduction_35',['Introduction',['../dd/d8b/a01363.html#c-menu-introduction',1,'C-Menu Introduction'],['../d8/d4e/a01355.html#introduction',1,'Introduction'],['../d2/d3f/a01356.html#introduction-1',1,'Introduction'],['../dc/d4b/a01359.html#introduction-2',1,'Introduction'],['../d9/d79/a01360.html#introduction-3',1,'Introduction'],['../da/dab/a01362.html#introduction-4',1,'Introduction']]],
  ['is_20fast_20but_20i_20rely_20on_20find_20s_20features_36',['lf is fast, but I rely on find&apos;s features',['../d2/d1f/a01361.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['issue_20on_20the_20c_20menu_20github_20repository_37',['issue on the C Menu GitHub repository',['../d2/d3f/a01356.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d8/d4e/a01355.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d9/d79/a01360.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_38',['issues or have questions feel free to open an issue on the C Menu GitHub repository',['../d2/d3f/a01356.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d8/d4e/a01355.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d9/d79/a01360.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['it_39',['Just Do It',['../dd/d8b/a01363.html#just-do-it',1,'']]],
  ['items_40',['Selecting Items',['../d2/d3f/a01356.html#selecting-items',1,'']]]
];
