var searchData=
[
  ['a_20box_20window_0',['View In a Box Window',['../d8/d18/a01069.html#view-in-a-box-window',1,'']]],
  ['a_20picker_1',['Pick - A Picker',['../index.html#pick---a-picker',1,'']]],
  ['a_20user_20interface_20toolkit_2',['A User Interface Toolkit',['../index.html',1,'']]],
  ['about_20c_20menu_20and_20r_20menu_3',['About C-Menu and R-Menu',['../d1/de6/a01068.html#about-c-menu-and-r-menu',1,'']]],
  ['added_4',['Added',['../d0/dfb/a01066.html#added',1,'']]],
  ['additional_20resources_5',['Additional Resources',['../d1/de6/a01068.html#additional-resources',1,'']]],
  ['address_20space_6',['Demand Paged Virtual Address Space',['../index.html#demand-paged-virtual-address-space',1,'']]],
  ['ai_20overview_20of_20developer_20folke_7',['AI Overview of Developer Folke',['../d1/de6/a01068.html#ai-overview-of-developer-folke',1,'']]],
  ['ai_20overview_20of_20developer_20norcalli_8',['AI Overview of Developer Norcalli',['../d1/de6/a01068.html#ai-overview-of-developer-norcalli',1,'']]],
  ['aids_20soap_20box_9',['Visual Aids Soap-box',['../d8/d18/a01069.html#visual-aids-soap-box',1,'']]],
  ['alacritty_10',['Alacritty',['../df/d18/a01071.html#alacritty',1,'']]],
  ['alacritty_20and_20kitty_11',['Alacritty and Kitty',['../d2/d49/a01067.html#alacritty-and-kitty',1,'']]],
  ['alacritty_20configuration_12',['Alacritty Configuration',['../d1/de6/a01068.html#alacritty-configuration',1,'']]],
  ['alternate_20bash_20executable_13',['Alternate Bash Executable',['../d1/de6/a01068.html#alternate-bash-executable',1,'']]],
  ['an_20issue_20on_20the_20c_20menu_20github_20repository_14',['an issue on the C Menu GitHub repository',['../d9/db3/a01064.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d5/d67/a01070.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['and_15',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../d8/d18/a01069.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['and_20color_20manual_20pages_16',['View and Color Manual Pages',['../index.html#view-and-color-manual-pages',1,'']]],
  ['and_20editing_17',['Form for Data Entry and Editing',['../index.html#form-for-data-entry-and-editing',1,'']]],
  ['and_20editor_20settings_18',['Terminal and Editor Settings',['../df/d18/a01071.html#terminal-and-editor-settings',1,'']]],
  ['and_20gawk_19',['High Precision Math With C-Menu and Gawk',['../d8/d18/a01069.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['and_20kitty_20',['Alacritty and Kitty',['../d2/d49/a01067.html#alacritty-and-kitty',1,'']]],
  ['and_20lf_21',['Menu, Form, Pick, View, C-Keys, RSH, and lf',['../index.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'']]],
  ['and_20macos_22',['Installing Rust On Linux and macOS',['../d1/de6/a01068.html#installing-rust-on-linux-and-macos',1,'']]],
  ['and_20r_20menu_23',['About C-Menu and R-Menu',['../d1/de6/a01068.html#about-c-menu-and-r-menu',1,'']]],
  ['and_20user_20guide_24',['Roadmap for API Documentation and User Guide',['../d9/db3/a01064.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['and_20version_20h_25',['include/version.h and version.h',['../d9/db3/a01064.html#includeversionh-and-versionh',1,'']]],
  ['and_20view_20api_26',['Menu, Form, Pick, and View API',['../d8/d18/a01069.html#menu-form-pick-and-view-api',1,'']]],
  ['and_20view_20h_27',['include/menu.h, form.h, pick.h, and view.h',['../d9/db3/a01064.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_28',['any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../d9/db3/a01064.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d5/d67/a01070.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['api_29',['API',['../d9/db3/a01064.html',1,'API'],['../index.html#c-menu-api',1,'C-Menu API'],['../d8/d18/a01069.html#menu-form-pick-and-view-api',1,'Menu, Form, Pick, and View API'],['../d1/de6/a01068.html#neovim-linkage-to-the-c-menu-api',1,'Neovim Linkage to the C-Menu API']]],
  ['api_20documentation_20and_20user_20guide_30',['Roadmap for API Documentation and User Guide',['../d9/db3/a01064.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['api_20organization_31',['API Organization',['../d9/db3/a01064.html#api-organization',1,'']]],
  ['are_20my_20header_20files_32',['Menu lf - Where Are My Header Files?',['../d8/d18/a01069.html#menu-lf---where-are-my-header-files',1,'']]],
  ['art_20in_20snacks_20nvim_33',['To Use the Neovim Unicode Art in Snacks.nvim',['../d1/de6/a01068.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['asked_20questions_34',['Frequently Asked Questions',['../d8/d18/a01069.html',1,'']]],
  ['augmenting_20c_20menu_35',['Augmenting C-Menu',['../d1/de6/a01068.html',1,'']]]
];
