var searchData=
[
  ['f_20and_0',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../d7/dde/a01384.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['faq_1',['FAQ',['../d7/dde/a01384.html',1,'']]],
  ['fast_20but_20i_20rely_20on_20find_20s_20features_2',['lf is fast, but I rely on find&apos;s features',['../d7/dde/a01384.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['feature_20enhancements_3',['1.1.0 - Feature Enhancements',['../d2/df5/a01395.html#autotoc_md110---feature-enhancements',1,'']]],
  ['features_4',['Features',['../dc/dbc/a01391.html#features',1,'Features'],['../dc/dbc/a01391.html#form-key-features',1,'Form Key Features'],['../dc/dbc/a01391.html#key-features',1,'Key Features'],['../db/d74/a01378.html#rsh-safety-features',1,'RSH Safety Features'],['../dc/dbc/a01391.html#view---other-features',1,'View - Other Features']]],
  ['features_5',['lf is fast, but I rely on find&apos;s features',['../d7/dde/a01384.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['features_20for_20lf_6',['Features for lf',['../d6/d2f/a01394.html#new-features-for-lf',1,'New Features for lf'],['../index.html#new-features-for-lf-1',1,'New Features for lf']]],
  ['feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_7',['feel free to open an issue on the C Menu GitHub repository',['../db/d74/a01378.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d3/dea/a01377.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../de/dfe/a01383.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['field_20delimiters_8',['Field Delimiters',['../db/d74/a01378.html#form-field-delimiters',1,'Form Field Delimiters'],['../d7/dde/a01384.html#menu-form---field-delimiters',1,'Menu Form - Field Delimiters']]],
  ['field_20editor_9',['Form field editor',['../db/d74/a01378.html#form-field-editor',1,'']]],
  ['fields_10',['Fields',['../d0/d9b/a01379.html#fields',1,'Fields'],['../df/d68/a01385.html#fields-1',1,'Fields']]],
  ['file_11',['File',['../d0/d9b/a01379.html#description-file',1,'Description File'],['../df/d68/a01385.html#description-file-1',1,'Description File'],['../d0/d9b/a01379.html#menu-description-file',1,'Menu Description File'],['../d5/d8e/a01390.html#menu-description-file-1',1,'Menu Description File'],['../dc/dbc/a01391.html#sample-menu-description-file',1,'Sample Menu Description File'],['../da/de3/a01398.html#suppression-file',1,'Suppression File']]],
  ['file_20example_12',['C-Menu configuration file example',['../db/d74/a01378.html#c-menu-configuration-file-example',1,'']]],
  ['file_20finder_13',['File Finder',['../d9/d40/a01387.html#lf---a-regular-expression-file-finder',1,'lf - A Regular Expression File Finder'],['../d6/d64/a01399.html#lf---a-regular-expression-file-finder-1',1,'lf - A Regular Expression File Finder']]],
  ['file_20format_14',['Menu Description File Format',['../db/d74/a01378.html#menu-description-file-format',1,'']]],
  ['file_20in_20view_15',['Large Log File in View',['../dc/dbc/a01391.html#large-log-file-in-view',1,'']]],
  ['file_20layout_16',['C-Menu File Layout',['../db/d74/a01378.html#c-menu-file-layout',1,'']]],
  ['file_20structure_17',['C-Menu&apos;s File Structure',['../d7/dde/a01384.html#c-menus-file-structure',1,'']]],
  ['file_20with_20editor_18',['Log File With Editor',['../dc/dbc/a01391.html#log-file-with-editor',1,'']]],
  ['file_20with_20view_19',['Screenshot of the Same File With View',['../dc/dbc/a01391.html#screenshot-of-the-same-file-with-view',1,'']]],
  ['files_20',['FILES',['../da/d77/a01381.html#files',1,'FILES'],['../d0/d95/a01389.html#files-1',1,'FILES']]],
  ['files_21',['Files',['../d7/d1c/a01397.html#c-menu-desktop-files',1,'C-Menu Desktop Files'],['../d3/dea/a01377.html#c-menu-header-files',1,'C-Menu Header Files'],['../d7/dde/a01384.html#menu-lf---where-are-my-header-files',1,'Menu lf - Where Are My Header Files?'],['../d7/dde/a01384.html#pick---selecting-multiple-files',1,'Pick - Selecting Multiple Files']]],
  ['files_22',['View - A pager for viewing files',['../d9/d40/a01387.html#view---a-pager-for-viewing-files',1,'']]],
  ['files_20in_20current_20directory_23',['Files in Current Directory',['../d0/d9b/a01379.html#edit-c-files-in-current-directory',1,'Edit .c Files in Current Directory'],['../d0/d9b/a01379.html#edit-c-files-in-current-directory-1',1,'Edit .c Files in Current Directory'],['../d5/d8e/a01390.html#edit-c-files-in-current-directory-2',1,'Edit .c Files in Current Directory'],['../d3/d92/a01393.html#edit-c-files-in-current-directory-3',1,'Edit .c Files in Current Directory']]],
  ['files_20using_20regular_20expressions_24',['lf - List Files Using Regular Expressions',['../dc/dbc/a01391.html#lf---list-files-using-regular-expressions',1,'']]],
  ['files_20with_20multiple_20suffixes_25',['Can lf match files with multiple suffixes',['../d7/dde/a01384.html#can-lf-match-files-with-multiple-suffixes',1,'']]],
  ['find_20s_20features_26',['lf is fast, but I rely on find&apos;s features',['../d7/dde/a01384.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['finder_27',['Finder',['../d9/d40/a01387.html#lf---a-regular-expression-file-finder',1,'lf - A Regular Expression File Finder'],['../d6/d64/a01399.html#lf---a-regular-expression-file-finder-1',1,'lf - A Regular Expression File Finder']]],
  ['finish_20the_20installation_28',['Finish the installation',['../d9/d40/a01387.html#finish-the-installation',1,'']]],
  ['fixed_29',['Fixed',['../dd/d6d/a01380.html#fixed',1,'']]],
  ['folke_30',['Folke',['../de/dfe/a01383.html#ai-overview-of-developer-folke',1,'AI Overview of Developer Folke'],['../de/dfe/a01383.html#folke',1,'Folke']]],
  ['folke_20s_20lazyvim_31',['To Install Folke&apos;s LazyVim',['../de/dfe/a01383.html#to-install-folkes-lazyvim',1,'']]],
  ['folke_20s_20snacks_20nvim_32',['Folke&apos;s Snacks.nvim',['../de/dfe/a01383.html#folkes-snacksnvim',1,'']]],
  ['folke_20s_20snacks_20nvim_20colorizer_33',['To Install Folke&apos;s Snacks.nvim-colorizer',['../de/dfe/a01383.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['fonts_34',['Fonts',['../de/dfe/a01383.html#fonts',1,'']]],
  ['footprint_35',['Performance and Footprint',['../d9/d40/a01387.html#performance-and-footprint',1,'']]],
  ['for_20api_20documentation_20and_20user_20guide_36',['Roadmap for API Documentation and User Guide',['../d3/dea/a01377.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['for_20data_20entry_20and_20editing_37',['Form for Data Entry and Editing',['../dc/dbc/a01391.html#form-for-data-entry-and-editing',1,'']]],
  ['for_20lf_38',['for lf',['../dc/dbc/a01391.html#_new-options-for-lf_',1,'&lt;b&gt;&lt;em&gt;New Options for lf&lt;/em&gt;&lt;/b&gt;'],['../d6/d2f/a01394.html#new-features-for-lf',1,'New Features for lf'],['../index.html#new-features-for-lf-1',1,'New Features for lf']]],
  ['for_20linux_20x86_5f64_39',['C-Menu Binaries for Linux x86_64',['../d9/d40/a01387.html#c-menu-binaries-for-linux-x86_64',1,'']]],
  ['for_20viewing_20files_40',['View - A pager for viewing files',['../d9/d40/a01387.html#view---a-pager-for-viewing-files',1,'']]],
  ['form_41',['Form',['../df/d68/a01385.html',1,'C-Menu Form'],['../d0/d9b/a01379.html#c-menu-form',1,'C-Menu Form'],['../d9/d40/a01387.html#form',1,'Form'],['../d6/d2f/a01394.html#form-1',1,'Form'],['../d2/df5/a01395.html#form-2',1,'Form'],['../index.html#form-3',1,'Form']]],
  ['form_20data_20types_42',['Form Data Types',['../db/d74/a01378.html#form-data-types',1,'Form Data Types'],['../d0/d9b/a01379.html#form-data-types-1',1,'Form Data Types'],['../d5/d8e/a01390.html#form-data-types-2',1,'Form Data Types'],['../dc/dbc/a01391.html#form-data-types-3',1,'Form Data Types'],['../d7/dde/a01384.html#menu-form---data-types',1,'Menu Form - Data Types']]],
  ['form_20field_20delimiters_43',['Form Field Delimiters',['../db/d74/a01378.html#form-field-delimiters',1,'Form Field Delimiters'],['../d7/dde/a01384.html#menu-form---field-delimiters',1,'Menu Form - Field Delimiters']]],
  ['form_20field_20editor_44',['Form field editor',['../db/d74/a01378.html#form-field-editor',1,'']]],
  ['form_20for_20data_20entry_20and_20editing_45',['Form for Data Entry and Editing',['../dc/dbc/a01391.html#form-for-data-entry-and-editing',1,'']]],
  ['form_20h_20pick_20h_20and_20view_20h_46',['include/menu.h, form.h, pick.h, and view.h',['../d3/dea/a01377.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['form_20integrating_20external_20executables_47',['Menu Form - Integrating External Executables',['../d7/dde/a01384.html#menu-form---integrating-external-executables',1,'']]],
  ['form_20key_20features_48',['Form Key Features',['../dc/dbc/a01391.html#form-key-features',1,'']]],
  ['form_20line_20syntax_49',['Form Line Syntax',['../db/d74/a01378.html#form-line-syntax',1,'']]],
  ['form_20line_20type_20specifiers_50',['Form Line Type Specifiers',['../db/d74/a01378.html#form-line-type-specifiers',1,'']]],
  ['form_20line_20type_20speecifiers_20h_20t_20f_20and_51',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../d7/dde/a01384.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['form_20options_52',['Form Options',['../db/d74/a01378.html#form-options',1,'']]],
  ['form_20pick_20and_20view_20api_53',['Menu, Form, Pick, and View API',['../d7/dde/a01384.html#menu-form-pick-and-view-api',1,'']]],
  ['form_20pick_20view_20c_20keys_20rsh_20and_20lf_54',['Menu, Form, Pick, View, C-Keys, RSH, and lf',['../dc/dbc/a01391.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'']]],
  ['format_55',['Menu Description File Format',['../db/d74/a01378.html#menu-description-file-format',1,'']]],
  ['forms_20pickers_20views_20ckeys_20etc_56',['Drop-down and Pop-up Menus, Forms, Pickers, Views, Ckeys, etc',['../d7/dde/a01384.html#drop-down-and-pop-up-menus-forms-pickers-views-ckeys-etc',1,'']]],
  ['forward_57',['Searching Forward',['../db/d74/a01378.html#searching-forward',1,'']]],
  ['free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_58',['free to open an issue on the C Menu GitHub repository',['../db/d74/a01378.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../d3/dea/a01377.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../de/dfe/a01383.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['from_20github_59',['Download From Github',['../d7/dde/a01384.html#download-from-github',1,'']]],
  ['from_20source_60',['Build C-Menu from Source',['../d9/d40/a01387.html#build-c-menu-from-source',1,'']]],
  ['full_20screen_20root_20shell_61',['Full Screen Root Shell',['../d0/d9b/a01379.html#full-screen-root-shell',1,'Full Screen Root Shell'],['../d5/d8e/a01390.html#full-screen-root-shell-1',1,'Full Screen Root Shell']]]
];
