var searchData=
[
  ['name_0',['NAME',['../da/dcf/a01558.html#name',1,'NAME'],['../de/d1a/a01559.html#name-1',1,'NAME'],['../d1/d9b/a01566.html#name-2',1,'NAME']]],
  ['name_20c_20menu_20application_20builder_1',['NAME C-Menu Application Builder',['../d3/d1b/a01549.html#name-c-menu-application-builder',1,'']]],
  ['navigation_2',['View Navigation',['../d9/da1/a01546.html#view-navigation',1,'']]],
  ['neovim_3',['Neovim',['../d2/d49/a01561.html#_new-api-integration-with-neovim_',1,'&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;'],['../d9/dac/a01557.html#completions-in-neovim',1,'Completions in Neovim'],['../de/d2c/a01553.html#neovim',1,'Neovim']]],
  ['neovim_20configuration_4',['Neovim Configuration',['../de/d2c/a01553.html#neovim-configuration',1,'']]],
  ['neovim_20linkage_20to_20the_20c_20menu_20api_5',['Neovim Linkage to the C-Menu API',['../de/d2c/a01553.html#neovim-linkage-to-the-c-menu-api',1,'']]],
  ['neovim_20unicode_20art_20in_20snacks_20nvim_6',['To Use the Neovim Unicode Art in Snacks.nvim',['../de/d2c/a01553.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['new_20api_20integration_20with_20neovim_7',['&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;',['../d2/d49/a01561.html#_new-api-integration-with-neovim_',1,'']]],
  ['new_20options_20for_20lf_8',['&lt;b&gt;&lt;em&gt;New Options for lf&lt;/em&gt;&lt;/b&gt;',['../d2/d49/a01561.html#_new-options-for-lf_',1,'']]],
  ['new_20theme_20as_20the_20default_9',['Setting the New Theme as the Default',['../da/daf/a01568.html#setting-the-new-theme-as-the-default',1,'']]],
  ['new_20themes_10',['Creating New Themes',['../da/daf/a01568.html#creating-new-themes',1,'']]],
  ['new_20v_20option_20for_20pick_11',['&lt;em&gt;&lt;b&gt;New&lt;/b&gt;&lt;/em&gt;: New &quot;-v&quot; option for &apos;Pick&apos;',['../de/dd5/a01564.html#new-new--v-option-for-pick',1,'']]],
  ['new_3a_20new_20v_20option_20for_20pick_12',['&lt;em&gt;&lt;b&gt;New&lt;/b&gt;&lt;/em&gt;: New &quot;-v&quot; option for &apos;Pick&apos;',['../de/dd5/a01564.html#new-new--v-option-for-pick',1,'']]],
  ['norcalli_13',['AI Overview of Developer Norcalli',['../de/d2c/a01553.html#ai-overview-of-developer-norcalli',1,'']]],
  ['norcalli_20colorizer_14',['Norcalli Colorizer',['../de/d2c/a01553.html#norcalli-colorizer',1,'']]],
  ['norcalli_20s_20nvim_20colorizer_20lua_15',['To Install Norcalli&apos;s nvim-colorizer.lua',['../de/d2c/a01553.html#to-install-norcallis-nvim-colorizerlua',1,'']]],
  ['not_20required_20but_20recommended_16',['Not Required, But Recommended',['../d9/da1/a01546.html#not-required-but-recommended',1,'']]],
  ['note_17',['NOTE',['../d1/d9b/a01566.html#note',1,'']]],
  ['note_20about_20gmtime_5fr_18',['Important note about &lt;span class=&quot;tt&quot;&gt;gmtime_r()&lt;/span&gt;',['../d7/db6/a01556.html#important-note-about-gmtime_r',1,'']]],
  ['notes_19',['Notes',['../de/dd5/a01564.html#security-notes',1,'Security Notes'],['../index.html#security-notes-1',1,'Security Notes']]],
  ['numbering_20',['View Line Numbering',['../d2/d49/a01561.html#view-line-numbering',1,'']]],
  ['nvim_21',['nvim',['../de/d2c/a01553.html#folkes-snacksnvim',1,'Folke&apos;s Snacks.nvim'],['../de/d2c/a01553.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'To Use the Neovim Unicode Art in Snacks.nvim']]],
  ['nvim_20colorizer_22',['To Install Folke&apos;s Snacks.nvim-colorizer',['../de/d2c/a01553.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['nvim_20colorizer_20lua_23',['To Install Norcalli&apos;s nvim-colorizer.lua',['../de/d2c/a01553.html#to-install-norcallis-nvim-colorizerlua',1,'']]]
];
