var searchData=
[
  ['gamma_0',['Gray Gamma',['../d7/dbf/a01239.html#gray-gamma',1,'']]],
  ['gamma_20correction_1',['3-Channel Gamma Correction',['../d7/dbf/a01239.html#autotoc_md3-channel-gamma-correction',1,'']]],
  ['gawk_2',['High Precision Math With C-Menu and Gawk',['../dc/dab/a01237.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['gdb_20debugging_20setup_3',['GDB Debugging Setup',['../d3/d07/a01241.html#gdb-debugging-setup',1,'']]],
  ['general_4',['General',['../d5/d6e/a01240.html#general',1,'General'],['../d5/d6e/a01240.html#general-1',1,'General']]],
  ['get_20c_20menu_20on_20github_5',['Get C Menu on Github',['../d0/d67/a01232.html#get-c-menu-on-github',1,'Get C-Menu on Github'],['../d6/da1/a01233.html#get-c-menu-on-github-1',1,'Get C-Menu on Github'],['../d8/d2b/a01236.html#get-c-menu-on-github-2',1,'Get C-Menu on Github'],['../d7/dbf/a01239.html#get-c-menu-on-github-3',1,'Get C-Menu on Github']]],
  ['get_20rusty_6',['Let&apos;s Get Rusty',['../d8/d2b/a01236.html#lets-get-rusty',1,'']]],
  ['getting_20started_7',['Getting Started',['../d6/da1/a01233.html#getting-started',1,'']]],
  ['ghostty_8',['Ghostty',['../d8/d2b/a01236.html#ghostty',1,'Ghostty'],['../d3/d07/a01241.html#ghostty-1',1,'Ghostty']]],
  ['ghostty_20configuration_9',['Ghostty Configuration',['../dd/dad/a01235.html#ghostty-configuration',1,'Ghostty Configuration'],['../d8/d2b/a01236.html#ghostty-configuration-1',1,'Ghostty Configuration']]],
  ['ghostty_20on_20linux_10',['Ghostty On Linux',['../d8/d2b/a01236.html#ghostty-on-linux',1,'']]],
  ['ghostty_20on_20macos_11',['Ghostty On macOS',['../d8/d2b/a01236.html#ghostty-on-macos',1,'']]],
  ['ghostty_20on_20windows_12',['Ghostty On Windows',['../d8/d2b/a01236.html#ghostty-on-windows',1,'']]],
  ['github_13',['Github',['../dc/dab/a01237.html#download-from-github',1,'Download From Github'],['../d0/d67/a01232.html#get-c-menu-on-github',1,'Get C-Menu on Github'],['../d6/da1/a01233.html#get-c-menu-on-github-1',1,'Get C-Menu on Github'],['../d8/d2b/a01236.html#get-c-menu-on-github-2',1,'Get C-Menu on Github'],['../d7/dbf/a01239.html#get-c-menu-on-github-3',1,'Get C-Menu on Github']]],
  ['github_20repository_14',['GitHub repository',['../d0/d67/a01232.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d6/da1/a01233.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../dd/dad/a01235.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d8/d2b/a01236.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../dc/dab/a01237.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-4',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d8/ddf/a01238.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-5',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../index.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-6',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['gray_20gamma_15',['Gray Gamma',['../d7/dbf/a01239.html#gray-gamma',1,'']]],
  ['guide_16',['Guide',['../d8/ddf/a01238.html',1,'Installation Guide'],['../index.html',1,'Installation Guide'],['../d0/d67/a01232.html#roadmap-for-api-documentation-and-user-guide',1,'Roadmap for API Documentation and User Guide']]],
  ['guide_17',['User guide',['../d6/da1/a01233.html',1,'']]]
];
