var searchData=
[
  ['i_20rely_20on_20find_20s_20features_0',['lf is fast, but I rely on find&apos;s features',['../dc/d60/a01461.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['icon_1',['What&apos;s the Icon?',['../dc/d60/a01461.html#whats-the-icon',1,'']]],
  ['if_20you_20can_20t_20stop_20typing_20vi_2',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../df/d2f/a01474.html#if-you-cant-stop-typing-vi',1,'']]],
  ['if_20you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_3',['If you encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../da/df6/a01454.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../dd/d1c/a01452.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d2/d2f/a01460.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['important_20note_20about_20gmtime_5fr_4',['Important note about &lt;span class=&quot;tt&quot;&gt;gmtime_r()&lt;/span&gt;',['../d7/d42/a01463.html#important-note-about-gmtime_r',1,'']]],
  ['in_20a_20box_20window_5',['View In a Box Window',['../dc/d60/a01461.html#view-in-a-box-window',1,'']]],
  ['in_20current_20directory_6',['in Current Directory',['../df/dc5/a01455.html#edit-c-files-in-current-directory',1,'Edit .c Files in Current Directory'],['../df/dc5/a01455.html#edit-c-files-in-current-directory-1',1,'Edit .c Files in Current Directory'],['../df/d5e/a01467.html#edit-c-files-in-current-directory-2',1,'Edit .c Files in Current Directory'],['../d0/da4/a01470.html#edit-c-files-in-current-directory-3',1,'Edit .c Files in Current Directory']]],
  ['in_20neovim_7',['Completions in Neovim',['../db/d8b/a01464.html#completions-in-neovim',1,'']]],
  ['in_20snacks_20nvim_8',['To Use the Neovim Unicode Art in Snacks.nvim',['../d2/d2f/a01460.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['in_20view_9',['Large Log File in View',['../df/df3/a01468.html#large-log-file-in-view',1,'']]],
  ['include_20cm_20h_10',['include/cm.h',['../dd/d1c/a01452.html#includecmh',1,'']]],
  ['include_20common_20h_11',['include/common.h',['../dd/d1c/a01452.html#includecommonh',1,'']]],
  ['include_20menu_20h_20form_20h_20pick_20h_20and_20view_20h_12',['include/menu.h, form.h, pick.h, and view.h',['../dd/d1c/a01452.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['include_20version_20h_20and_20version_20h_13',['include/version.h and version.h',['../dd/d1c/a01452.html#includeversionh-and-versionh',1,'']]],
  ['indicator_20shell_20prompts_14',['Privilege Indicator Shell Prompts',['../df/d2f/a01474.html#privilege-indicator-shell-prompts',1,'']]],
  ['initial_20release_15',['1.0.0 - Initial Release',['../d2/d48/a01472.html#autotoc_md100---initial-release',1,'']]],
  ['inode_16',['Menu - What Happened to Delete by Inode',['../dc/d60/a01461.html#menu---what-happened-to-delete-by-inode',1,'']]],
  ['input_17',['C-Keys - Diagnose Keyboard/Mouse Input',['../df/df3/a01468.html#c-keys---diagnose-keyboardmouse-input',1,'']]],
  ['input_20output_18',['INPUT/OUTPUT',['../d5/d67/a01466.html#inputoutput',1,'']]],
  ['install_19',['Install',['../d9/dae/a01453.html#install',1,'Install'],['../d9/dae/a01453.html#post-install',1,'Post Install']]],
  ['install_20folke_20s_20lazyvim_20',['To Install Folke&apos;s LazyVim',['../d2/d2f/a01460.html#to-install-folkes-lazyvim',1,'']]],
  ['install_20folke_20s_20snacks_20nvim_20colorizer_21',['To Install Folke&apos;s Snacks.nvim-colorizer',['../d2/d2f/a01460.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['install_20norcalli_20s_20nvim_20colorizer_20lua_22',['To Install Norcalli&apos;s nvim-colorizer.lua',['../d2/d2f/a01460.html#to-install-norcallis-nvim-colorizerlua',1,'']]],
  ['install_20tree_20sitter_20cli_23',['Install Tree-Sitter-CLI',['../dc/d60/a01461.html#install-tree-sitter-cli',1,'']]],
  ['installation_24',['C-Menu INSTALLATION',['../db/d8b/a01464.html#c-menu-installation',1,'']]],
  ['installation_25',['Check the Installation',['../d9/dae/a01453.html#check-the-installation',1,'']]],
  ['installation_26',['Finish the installation',['../db/d8b/a01464.html#finish-the-installation',1,'']]],
  ['installing_20bat_27',['Installing Bat',['../d2/d2f/a01460.html#installing-bat',1,'']]],
  ['installing_20ripgrep_28',['Installing Ripgrep',['../d2/d2f/a01460.html#installing-ripgrep',1,'']]],
  ['installing_20rust_29',['Installing Rust',['../d2/d2f/a01460.html#installing-rust',1,'']]],
  ['installing_20rust_20on_20linux_20and_20macos_30',['Installing Rust On Linux and macOS',['../d2/d2f/a01460.html#installing-rust-on-linux-and-macos',1,'']]],
  ['installment_20loan_20calculations_31',['Installment Loan Calculations',['../df/dc5/a01455.html#installment-loan-calculations',1,'Installment Loan Calculations'],['../df/dc5/a01455.html#installment-loan-calculations-1',1,'Installment Loan Calculations'],['../de/d36/a01462.html#installment-loan-calculations-2',1,'Installment Loan Calculations'],['../df/d5e/a01467.html#installment-loan-calculations-3',1,'Installment Loan Calculations']]],
  ['installment_20loan_20calculator_32',['Menu - Using the Installment Loan Calculator',['../dc/d60/a01461.html#menu---using-the-installment-loan-calculator',1,'']]],
  ['instead_20of_20ls_33',['Use lsd or eza instead of ls',['../df/d2f/a01474.html#use-lsd-or-eza-instead-of-ls',1,'']]],
  ['integrating_20external_20executables_34',['Menu Form - Integrating External Executables',['../dc/d60/a01461.html#menu-form---integrating-external-executables',1,'']]],
  ['integration_20with_20neovim_35',['&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;',['../df/df3/a01468.html#_new-api-integration-with-neovim_',1,'']]],
  ['intended_36',['Highlights (Pun Intended)',['../df/df3/a01468.html#highlights-pun-intended',1,'']]],
  ['interface_20toolkit_37',['C-Menu - A User Interface Toolkit',['../db/d8b/a01464.html',1,'']]],
  ['interpretation_20of_20the_20original_20test_20cases_38',['Revised interpretation of the original test cases',['../d7/d42/a01463.html#revised-interpretation-of-the-original-test-cases',1,'']]],
  ['interprocess_20communications_39',['Menu - Interprocess Communications',['../dc/d60/a01461.html#menu---interprocess-communications',1,'']]],
  ['introduction_40',['Introduction',['../df/df3/a01468.html#c-menu-introduction',1,'C-Menu Introduction'],['../dd/d1c/a01452.html#introduction',1,'Introduction'],['../d9/dae/a01453.html#introduction-1',1,'Introduction'],['../da/df6/a01454.html#introduction-2',1,'Introduction'],['../d6/d3b/a01459.html#introduction-3',1,'Introduction'],['../d2/d2f/a01460.html#introduction-4',1,'Introduction'],['../db/d8b/a01464.html#introduction-5',1,'Introduction']]],
  ['is_20c_20menu_41',['is C Menu',['../dd/d15/a01471.html#what-is-c-menu',1,'What is C-Menu?'],['../index.html#what-is-c-menu-1',1,'What is C-Menu?']]],
  ['is_20fast_20but_20i_20rely_20on_20find_20s_20features_42',['lf is fast, but I rely on find&apos;s features',['../dc/d60/a01461.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['issue_20on_20the_20c_20menu_20github_20repository_43',['issue on the C Menu GitHub repository',['../da/df6/a01454.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../dd/d1c/a01452.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d2/d2f/a01460.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_44',['issues or have questions feel free to open an issue on the C Menu GitHub repository',['../da/df6/a01454.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../dd/d1c/a01452.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d2/d2f/a01460.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['it_45',['Just Do It',['../df/df3/a01468.html#just-do-it',1,'']]],
  ['items_46',['Selecting Items',['../da/df6/a01454.html#selecting-items',1,'']]]
];
