var searchData=
[
  ['c_20keys_20diagnose_20keyboard_20mouse_20input_0',['C-Keys - Diagnose Keyboard/Mouse Input',['../index.html#c-keys---diagnose-keyboardmouse-input',1,'']]],
  ['c_20keys_20rsh_20and_20lf_1',['Menu, Form, Pick, View, C-Keys, RSH, and lf',['../index.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'']]],
  ['c_20menu_2',['C Menu',['../d4/d8f/a00324.html',1,'Augmenting C-Menu'],['../d8/d23/a00326.html#build-c-menu',1,'Build C-Menu'],['../index.html#elements-of-c-menu',1,'Elements of C-Menu']]],
  ['c_20menu_20and_20gawk_3',['High Precision Math With C-Menu and Gawk',['../de/dc8/a00325.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['c_20menu_20and_20r_20menu_4',['About C-Menu and R-Menu',['../d4/d8f/a00324.html#about-c-menu-and-r-menu',1,'']]],
  ['c_20menu_20api_5',['C Menu API',['../index.html#c-menu-api',1,'C-Menu API'],['../d4/d8f/a00324.html#neovim-linkage-to-the-c-menu-api',1,'Neovim Linkage to the C-Menu API']]],
  ['c_20menu_20bashrc_20configuration_6',['C-Menu bashrc Configuration',['../d8/dfc/a00327.html#c-menu-bashrc-configuration',1,'']]],
  ['c_20menu_20configuration_7',['C-Menu Configuration',['../d8/dfc/a00327.html#c-menu-configuration',1,'']]],
  ['c_20menu_20desktop_20files_8',['C-Menu Desktop Files',['../d8/dfc/a00327.html#c-menu-desktop-files',1,'']]],
  ['c_20menu_20environment_20variables_9',['Helpful C-Menu Environment Variables',['../d8/dfc/a00327.html#helpful-c-menu-environment-variables',1,'']]],
  ['c_20menu_20exercises_10',['C-Menu Exercises',['../index.html#c-menu-exercises',1,'']]],
  ['c_20menu_20form_11',['C-Menu Form',['../db/d53/a00321.html#c-menu-form',1,'']]],
  ['c_20menu_20github_20repository_12',['C Menu GitHub repository',['../dd/de2/a00320.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d8/d23/a00326.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['c_20menu_20header_20files_13',['C-Menu Header Files',['../dd/de2/a00320.html#c-menu-header-files',1,'']]],
  ['c_20menu_20if_20you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_14',['C Menu If you encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../dd/de2/a00320.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d8/d23/a00326.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['c_20menu_20introduction_15',['C-Menu Introduction',['../index.html#c-menu-introduction',1,'']]],
  ['c_20menu_20on_20github_16',['C Menu on Github',['../index.html#get-c-menu-on-github',1,'Get C-Menu on Github'],['../dd/de2/a00320.html#get-c-menu-on-github-1',1,'Get C-Menu on Github'],['../db/d53/a00321.html#get-c-menu-on-github-2',1,'Get C-Menu on Github'],['../d4/d8f/a00324.html#get-c-menu-on-github-3',1,'Get C-Menu on Github']]],
  ['c_20menu_20options_17',['C-Menu Options',['../db/d53/a00321.html#c-menu-options',1,'']]],
  ['c_20menu_20pick_18',['C-Menu Pick',['../db/d53/a00321.html#c-menu-pick',1,'']]],
  ['c_20menu_20s_20file_20structure_19',['C-Menu&apos;s File Structure',['../de/dc8/a00325.html#c-menus-file-structure',1,'']]],
  ['c_20menu_20startup_20with_20mm_20',['C-Menu Startup with &quot;mm&quot;',['../d8/dfc/a00327.html#c-menu-startup-with-mm',1,'']]],
  ['c_20menu_20using_20cmake_20directly_21',['Option 1 - Build C-Menu Using CMake Directly',['../d8/d23/a00326.html#option-1---build-c-menu-using-cmake-directly',1,'']]],
  ['c_20menu_20using_20makefile_22',['Option 3 - Build C-Menu Using Makefile',['../d8/d23/a00326.html#option-3---build-c-menu-using-makefile',1,'']]],
  ['c_20menu_20view_23',['C-Menu View',['../db/d53/a00321.html#c-menu-view',1,'']]],
  ['c_20menu_20with_20provided_20scripts_24',['Option 2 - Build C-Menu with Provided Scripts',['../d8/d23/a00326.html#option-2---build-c-menu-with-provided-scripts',1,'']]],
  ['calculator_25',['Menu - Using the Installment Loan Calculator',['../de/dc8/a00325.html#menu---using-the-installment-loan-calculator',1,'']]],
  ['can_20t_20stop_20typing_20vi_26',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../d8/dfc/a00327.html#if-you-cant-stop-typing-vi',1,'']]],
  ['changelog_27',['Changelog',['../de/de9/a00322.html',1,'']]],
  ['channel_20gamma_20correction_28',['3-Channel Gamma Correction',['../index.html#autotoc_md3-channel-gamma-correction',1,'']]],
  ['cli_29',['CLI',['../de/dc8/a00325.html#install-tree-sitter-cli',1,'Install Tree-Sitter-CLI'],['../d4/d8f/a00324.html#tree-sitter-cli',1,'Tree-Sitter-CLI']]],
  ['cli_20on_20linux_30',['Tree-Sitter-CLI On Linux',['../d4/d8f/a00324.html#tree-sitter-cli-on-linux',1,'']]],
  ['cli_20on_20macos_31',['Tree-Sitter-CLI On macOS',['../d4/d8f/a00324.html#tree-sitter-cli-on-macos',1,'']]],
  ['cli_20on_20windows_32',['Tree-Sitter-CLI On Windows',['../d4/d8f/a00324.html#tree-sitter-cli-on-windows',1,'']]],
  ['cm_20h_33',['include/cm.h',['../dd/de2/a00320.html#includecmh',1,'']]],
  ['cmake_20directly_34',['Option 1 - Build C-Menu Using CMake Directly',['../d8/d23/a00326.html#option-1---build-c-menu-using-cmake-directly',1,'']]],
  ['codes_35',['View - How to Colorize HTML Color Codes',['../de/dc8/a00325.html#view---how-to-colorize-html-color-codes',1,'']]],
  ['color_20codes_36',['View - How to Colorize HTML Color Codes',['../de/dc8/a00325.html#view---how-to-colorize-html-color-codes',1,'']]],
  ['color_20manual_20pages_37',['View and Color Manual Pages',['../index.html#view-and-color-manual-pages',1,'']]],
  ['colorize_20html_20color_20codes_38',['View - How to Colorize HTML Color Codes',['../de/dc8/a00325.html#view---how-to-colorize-html-color-codes',1,'']]],
  ['colorize_20manual_20pages_39',['View - How to Colorize Manual Pages',['../de/dc8/a00325.html#view---how-to-colorize-manual-pages',1,'']]],
  ['colorizer_40',['Norcalli Colorizer',['../d4/d8f/a00324.html#norcalli-colorizer',1,'']]],
  ['colorizer_41',['To Install Folke&apos;s Snacks.nvim-colorizer',['../d4/d8f/a00324.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['colorizer_20lua_42',['To Install Norcalli&apos;s nvim-colorizer.lua',['../d4/d8f/a00324.html#to-install-norcallis-nvim-colorizerlua',1,'']]],
  ['colors_43',['View - How to Customize Colors',['../de/dc8/a00325.html#view---how-to-customize-colors',1,'']]],
  ['common_20h_44',['include/common.h',['../dd/de2/a00320.html#includecommonh',1,'']]],
  ['communications_45',['Menu - Interprocess Communications',['../de/dc8/a00325.html#menu---interprocess-communications',1,'']]],
  ['compatibility_46',['Version Compatibility',['../dd/de2/a00320.html#version-compatibility',1,'']]],
  ['conclusion_47',['Conclusion',['../d4/d8f/a00324.html#conclusion',1,'']]],
  ['config_20json_48',['Tree-Sitter config.json',['../d8/dfc/a00327.html#tree-sitter-configjson',1,'']]],
  ['configuration_49',['Configuration',['../d4/d8f/a00324.html#alacritty-configuration',1,'Alacritty Configuration'],['../d8/dfc/a00327.html#c-menu-bashrc-configuration',1,'C-Menu bashrc Configuration'],['../d8/dfc/a00327.html#c-menu-configuration',1,'C-Menu Configuration'],['../index.html#configuration',1,'Configuration'],['../de/d55/a00323.html#ghostty-configuration',1,'Ghostty Configuration'],['../d4/d8f/a00324.html#ghostty-configuration-1',1,'Ghostty Configuration'],['../d4/d8f/a00324.html#kitty-configuration',1,'Kitty Configuration'],['../d4/d8f/a00324.html#neovim-configuration',1,'Neovim Configuration'],['../de/d55/a00323.html#sddm-background-configuration',1,'SDDM Background Configuration'],['../d4/d8f/a00324.html#shell-configuration',1,'Shell Configuration']]],
  ['configuration_20snippets_50',['Configuration snippets',['../d8/dfc/a00327.html',1,'']]],
  ['configurations_51',['Configurations',['../d4/d8f/a00324.html#example-terminal-configurations',1,'Example Terminal Configurations'],['../de/d55/a00323.html#exercise-1-system-configurations',1,'Exercise 1: System Configurations'],['../d8/dfc/a00327.html#terminal-configurations',1,'Terminal Configurations'],['../d4/d8f/a00324.html#useful-configurations',1,'Useful Configurations']]],
  ['contents_52',['Contents',['../index.html#table-of-contents',1,'Table of Contents'],['../db/d53/a00321.html#table-of-contents-1',1,'Table of Contents'],['../d4/d8f/a00324.html#table-of-contents-2',1,'Table of Contents'],['../de/dc8/a00325.html#table-of-contents-3',1,'Table of Contents'],['../d8/dfc/a00327.html#table-of-contents-4',1,'Table of Contents']]],
  ['correction_53',['3-Channel Gamma Correction',['../index.html#autotoc_md3-channel-gamma-correction',1,'']]],
  ['curses_20escape_20delay_54',['Curses Escape Delay',['../d8/dfc/a00327.html#curses-escape-delay',1,'']]],
  ['custom_20highlights_55',['Custom Highlights',['../d4/d8f/a00324.html#custom-highlights',1,'']]],
  ['customize_20colors_56',['View - How to Customize Colors',['../de/dc8/a00325.html#view---how-to-customize-colors',1,'']]],
  ['customize_20your_20terminal_20emulator_57',['Customize Your Terminal Emulator',['../d4/d8f/a00324.html#customize-your-terminal-emulator',1,'']]]
];
