var searchData=
[
  ['s_20features_0',['lf is fast, but I rely on find&apos;s features',['../de/dd9/a03058.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['s_20file_20structure_1',['C-Menu&apos;s File Structure',['../de/dd9/a03058.html#c-menus-file-structure',1,'']]],
  ['s_20get_20rusty_2',['s Get Rusty',['../d2/df1/a03057.html#lets-get-rusty',1,'Let&apos;s Get Rusty'],['../d1/dff/a03046.html#lets-get-rusty-1',1,'Let&apos;s Get Rusty']]],
  ['s_20lazyvim_3',['s LazyVim',['../d2/df1/a03057.html#to-install-folkes-lazyvim-1',1,'To Install Folke&apos;s LazyVim'],['../d1/dff/a03046.html#to-install-folkes-lazyvim',1,'To Install Folke&apos;s LazyVim']]],
  ['s_20life_20story_4',['Bill Waller&apos;s Life Story',['../d2/de4/a03047.html',1,'']]],
  ['s_20log_20grammar_5',['A search term, &quot;transport&quot; was entered and the file was highlighted with Tudyx&apos;s tree-sitter-log grammar, which is available at &lt;a href=&quot;https://github.com/Tudyx/tree-sitter-log.git&quot;&gt;Tudyx&apos;s log grammar&lt;/a&gt;',['../d4/d47/a03050.html#a-search-term-transport-was-entered-and-the-file-was-highlighted-with-tudyxs-tree-sitter-log-grammar-which-is-available-at-tudyxs-log-grammarhttpsgithubcomtudyxtree-sitter-loggit',1,'']]],
  ['s_20nvim_20colorizer_20lua_6',['s nvim colorizer lua',['../d2/df1/a03057.html#to-install-norcallis-nvim-colorizerlua',1,'To Install Norcalli&apos;s nvim-colorizer.lua'],['../d1/dff/a03046.html#to-install-norcallis-nvim-colorizerlua-1',1,'To Install Norcalli&apos;s nvim-colorizer.lua']]],
  ['s_20snacks_20nvim_7',['s Snacks nvim',['../d2/df1/a03057.html#folkes-snacksnvim',1,'Folke&apos;s Snacks.nvim'],['../d1/dff/a03046.html#folkes-snacksnvim-1',1,'Folke&apos;s Snacks.nvim']]],
  ['s_20snacks_20nvim_20colorizer_8',['s Snacks nvim colorizer',['../d2/df1/a03057.html#to-install-folkes-snacksnvim-colorizer',1,'To Install Folke&apos;s Snacks.nvim-colorizer'],['../d1/dff/a03046.html#to-install-folkes-snacksnvim-colorizer-1',1,'To Install Folke&apos;s Snacks.nvim-colorizer']]],
  ['s_20the_20icon_9',['What&apos;s the Icon?',['../de/dd9/a03058.html#whats-the-icon',1,'']]],
  ['s_20tree_20sitter_20log_20grammar_20which_20is_20available_20at_20tudyx_20s_20log_20grammar_10',['A search term, &quot;transport&quot; was entered and the file was highlighted with Tudyx&apos;s tree-sitter-log grammar, which is available at &lt;a href=&quot;https://github.com/Tudyx/tree-sitter-log.git&quot;&gt;Tudyx&apos;s log grammar&lt;/a&gt;',['../d4/d47/a03050.html#a-search-term-transport-was-entered-and-the-file-was-highlighted-with-tudyxs-tree-sitter-log-grammar-which-is-available-at-tudyxs-log-grammarhttpsgithubcomtudyxtree-sitter-loggit',1,'']]],
  ['safety_20features_11',['RSH Safety Features',['../d7/d8c/a03049.html#rsh-safety-features',1,'']]],
  ['same_20file_20with_20view_12',['Screenshot of the Same File With View',['../d4/d44/a03065.html#screenshot-of-the-same-file-with-view',1,'']]],
  ['sample_20menu_20description_20file_13',['Sample Menu Description File',['../d4/d44/a03065.html#sample-menu-description-file',1,'']]],
  ['saving_20the_20theme_20file_14',['Saving the Theme File',['../da/d64/a03073.html#saving-the-theme-file',1,'']]],
  ['scope_15',['Scope',['../de/d96/a03054.html#scope',1,'']]],
  ['screen_20root_20shell_16',['Screen Root Shell',['../d4/d47/a03050.html#full-screen-root-shell',1,'Full Screen (Root) Shell'],['../de/d38/a03064.html#full-screen-root-shell-1',1,'Full Screen Root Shell']]],
  ['screenshot_20of_20the_20same_20file_20with_20view_17',['Screenshot of the Same File With View',['../d4/d44/a03065.html#screenshot-of-the-same-file-with-view',1,'']]],
  ['scrolling_18',['Horizontal Scrolling',['../d7/d8c/a03049.html#horizontal-scrolling',1,'']]],
  ['sddm_20background_20configuration_19',['SDDM Background Configuration',['../d4/d90/a03056.html#sddm-background-configuration',1,'']]],
  ['search_20not_20accepting_20certain_20letters_20',['Pick search not accepting certain letters',['../de/dd9/a03058.html#pick-search-not-accepting-certain-letters',1,'']]],
  ['search_20term_20transport_20was_20entered_20and_20the_20file_20was_20highlighted_20with_20tudyx_20s_20tree_20sitter_20log_20grammar_20which_20is_20available_20at_20tudyx_20s_20log_20grammar_21',['A search term, &quot;transport&quot; was entered and the file was highlighted with Tudyx&apos;s tree-sitter-log grammar, which is available at &lt;a href=&quot;https://github.com/Tudyx/tree-sitter-log.git&quot;&gt;Tudyx&apos;s log grammar&lt;/a&gt;',['../d4/d47/a03050.html#a-search-term-transport-was-entered-and-the-file-was-highlighted-with-tudyxs-tree-sitter-log-grammar-which-is-available-at-tudyxs-log-grammarhttpsgithubcomtudyxtree-sitter-loggit',1,'']]],
  ['searching_20backward_22',['Searching Backward',['../d7/d8c/a03049.html#searching-backward',1,'']]],
  ['searching_20forward_23',['Searching Forward',['../d7/d8c/a03049.html#searching-forward',1,'']]],
  ['security_20notes_24',['Security Notes',['../d7/d5a/a03069.html#security-notes',1,'Security Notes'],['../index.html#security-notes-1',1,'Security Notes']]],
  ['security_20through_20obscurity_25',['Security Through Obscurity',['../dd/d7c/a03072.html#security-through-obscurity',1,'']]],
  ['security_20with_20rsh_26',['MAINTAINING SECURITY WITH RSH',['../df/d48/a03071.html#maintaining-security-with-rsh',1,'']]],
  ['security_20with_20rsh_27',['Maintaining Security with RSH',['../d4/d44/a03065.html#maintaining-security-with-rsh-1',1,'']]],
  ['see_20also_28',['SEE ALSO',['../d6/d2a/a03062.html#see-also-2',1,'SEE ALSO'],['../d6/dfe/a03053.html#see-also-1',1,'SEE ALSO'],['../dc/dec/a03063.html#see-also-3',1,'SEE ALSO'],['../d4/d15/a03052.html#see-also-4',1,'SEE ALSO'],['../df/d48/a03071.html#see-also-6',1,'SEE ALSO']]],
  ['see_20also_29',['See Also',['../d4/d47/a03050.html#see-also',1,'']]],
  ['see_20also_30',['See also',['../d7/d5a/a03069.html#see-also-5',1,'See also'],['../index.html#see-also-7',1,'See also']]],
  ['selecting_20items_31',['Selecting Items',['../d7/d8c/a03049.html#selecting-items',1,'']]],
  ['selecting_20multiple_20files_32',['Pick - Selecting Multiple Files',['../de/dd9/a03058.html#pick---selecting-multiple-files',1,'']]],
  ['selecting_20themes_33',['Selecting Themes',['../da/d64/a03073.html#selecting-themes',1,'']]],
  ['selections_34',['Menu Selections',['../d4/d47/a03050.html#menu-selections',1,'']]],
  ['selections_20don_20t_20work_35',['Some Menu Selections Don&apos;t work',['../de/dd9/a03058.html#some-menu-selections-dont-work',1,'']]],
  ['selections_20not_20working_36',['Menu Selections Not Working',['../de/dd9/a03058.html#menu-selections-not-working',1,'']]],
  ['serialization_37',['Asynchronous Communication and Serialization',['../d9/df4/a03070.html#asynchronous-communication-and-serialization',1,'']]],
  ['set_20up_20your_20environment_38',['Set Up Your Environment',['../df/d0c/a03055.html#autotoc_md1-set-up-your-environment',1,'1. Set Up Your Environment'],['../dc/d92/a03048.html#set-up-your-environment',1,'Set Up Your Environment']]],
  ['setting_20the_20new_20theme_20as_20the_20default_39',['Setting the New Theme as the Default',['../da/d64/a03073.html#setting-the-new-theme-as-the-default',1,'']]],
  ['settings_40',['Settings',['../dd/d7c/a03072.html#locale-settings',1,'Locale Settings'],['../dd/d7c/a03072.html#terminal-and-editor-settings',1,'Terminal and Editor Settings']]],
  ['setup_41',['GDB Debugging Setup',['../dd/d7c/a03072.html#gdb-debugging-setup',1,'']]],
  ['shell_42',['SHELL',['../d6/dfe/a03053.html#function-call-vs-direct-execution-vs-shell',1,'FUNCTION CALL VS DIRECT EXECUTION VS SHELL'],['../d4/d15/a03052.html#function-call-vs-direct-execution-vs-shell-1',1,'FUNCTION CALL VS DIRECT EXECUTION VS SHELL']]],
  ['shell_43',['Shell',['../d4/d47/a03050.html#full-screen-root-shell',1,'Full Screen (Root) Shell'],['../de/d38/a03064.html#full-screen-root-shell-1',1,'Full Screen Root Shell']]],
  ['shell_20alternative_44',['Shell Alternative',['../da/d5d/a03068.html#rsh---a-root-shell-alternative',1,'RSH - A Root Shell Alternative'],['../d3/dbd/a03075.html#rsh---a-root-shell-alternative-1',1,'RSH - A Root Shell Alternative']]],
  ['shell_20configuration_45',['Shell Configuration',['../d2/df1/a03057.html#shell-configuration',1,'Shell Configuration'],['../d1/dff/a03046.html#shell-configuration-1',1,'Shell Configuration']]],
  ['shell_20logging_46',['Shell Logging',['../dd/d7c/a03072.html#shell-logging',1,'']]],
  ['shell_20prompts_47',['Privilege Indicator Shell Prompts',['../dd/d7c/a03072.html#privilege-indicator-shell-prompts',1,'']]],
  ['sitter_48',['Sitter',['../d2/df1/a03057.html#testing-tree-sitter',1,'Testing Tree-Sitter'],['../d1/dff/a03046.html#testing-tree-sitter-1',1,'Testing Tree-Sitter'],['../dd/d7c/a03072.html#tree-sitter-2',1,'Tree-Sitter'],['../d2/df1/a03057.html#tree-sitter-1',1,'Tree-Sitter'],['../d1/dff/a03046.html#tree-sitter',1,'Tree-Sitter'],['../da/de2/a03067.html#view-c-menu-source-with-tree-sitter-1',1,'View C-Menu Source With Tree-Sitter'],['../d4/d47/a03050.html#view-c-menu-source-with-tree-sitter',1,'View C-Menu Source with Tree-Sitter']]],
  ['sitter_49',['View Source with Tree-sitter',['../d4/d47/a03050.html#view-source-with-tree-sitter',1,'']]],
  ['sitter_20cli_50',['Sitter CLI',['../de/dd9/a03058.html#install-tree-sitter-cli',1,'Install Tree-Sitter-CLI'],['../d2/df1/a03057.html#tree-sitter-cli-1',1,'Tree-Sitter-CLI'],['../d1/dff/a03046.html#tree-sitter-cli',1,'Tree-Sitter-CLI']]],
  ['sitter_20cli_20on_20linux_51',['Sitter CLI On Linux',['../d2/df1/a03057.html#tree-sitter-cli-on-linux-1',1,'Tree-Sitter-CLI On Linux'],['../d1/dff/a03046.html#tree-sitter-cli-on-linux',1,'Tree-Sitter-CLI On Linux']]],
  ['sitter_20cli_20on_20macos_52',['Sitter CLI On macOS',['../d2/df1/a03057.html#tree-sitter-cli-on-macos-1',1,'Tree-Sitter-CLI On macOS'],['../d1/dff/a03046.html#tree-sitter-cli-on-macos',1,'Tree-Sitter-CLI On macOS']]],
  ['sitter_20cli_20on_20windows_53',['Sitter CLI On Windows',['../d2/df1/a03057.html#tree-sitter-cli-on-windows',1,'Tree-Sitter-CLI On Windows'],['../d1/dff/a03046.html#tree-sitter-cli-on-windows-1',1,'Tree-Sitter-CLI On Windows']]],
  ['sitter_20cli_20you_20will_20also_20need_20to_20have_20the_20tree_20sitter_20grammars_20for_20the_20languages_20you_20want_20to_20highlight_20installed_20you_20can_20find_20the_20grammars_20on_20the_20tree_20sitter_20github_20page_3a_20tree_20sitter_20grammars_54',['- In addition to tree-sitter-cli, you will also need to have the tree-sitter grammars for the languages you want to highlight installed. You can find the grammars on the tree-sitter GitHub page: &lt;a href=&quot;https://github.com/tree-sitter-grammars&quot;&gt;Tree-Sitter Grammars&lt;/a&gt;',['../d4/d47/a03050.html#autotoc_md--in-addition-to-tree-sitter-cli-you-will-also-need-to-have-the-tree-sitter-grammars-for-the-languages-you-want-to-highlight-installed-you-can-find-the-grammars-on-the-tree-sitter-github-page-tree-sitter-grammarshttpsgithubcomtree-sitter-grammars',1,'']]],
  ['sitter_20config_20json_55',['Tree-Sitter config.json',['../dd/d7c/a03072.html#tree-sitter-configjson',1,'']]],
  ['sitter_20github_20page_3a_20tree_20sitter_20grammars_56',['- In addition to tree-sitter-cli, you will also need to have the tree-sitter grammars for the languages you want to highlight installed. You can find the grammars on the tree-sitter GitHub page: &lt;a href=&quot;https://github.com/tree-sitter-grammars&quot;&gt;Tree-Sitter Grammars&lt;/a&gt;',['../d4/d47/a03050.html#autotoc_md--in-addition-to-tree-sitter-cli-you-will-also-need-to-have-the-tree-sitter-grammars-for-the-languages-you-want-to-highlight-installed-you-can-find-the-grammars-on-the-tree-sitter-github-page-tree-sitter-grammarshttpsgithubcomtree-sitter-grammars',1,'']]],
  ['sitter_20grammars_57',['- In addition to tree-sitter-cli, you will also need to have the tree-sitter grammars for the languages you want to highlight installed. You can find the grammars on the tree-sitter GitHub page: &lt;a href=&quot;https://github.com/tree-sitter-grammars&quot;&gt;Tree-Sitter Grammars&lt;/a&gt;',['../d4/d47/a03050.html#autotoc_md--in-addition-to-tree-sitter-cli-you-will-also-need-to-have-the-tree-sitter-grammars-for-the-languages-you-want-to-highlight-installed-you-can-find-the-grammars-on-the-tree-sitter-github-page-tree-sitter-grammarshttpsgithubcomtree-sitter-grammars',1,'']]],
  ['sitter_20grammars_20for_20the_20languages_20you_20want_20to_20highlight_20installed_20you_20can_20find_20the_20grammars_20on_20the_20tree_20sitter_20github_20page_3a_20tree_20sitter_20grammars_58',['- In addition to tree-sitter-cli, you will also need to have the tree-sitter grammars for the languages you want to highlight installed. You can find the grammars on the tree-sitter GitHub page: &lt;a href=&quot;https://github.com/tree-sitter-grammars&quot;&gt;Tree-Sitter Grammars&lt;/a&gt;',['../d4/d47/a03050.html#autotoc_md--in-addition-to-tree-sitter-cli-you-will-also-need-to-have-the-tree-sitter-grammars-for-the-languages-you-want-to-highlight-installed-you-can-find-the-grammars-on-the-tree-sitter-github-page-tree-sitter-grammarshttpsgithubcomtree-sitter-grammars',1,'']]],
  ['sitter_20log_20grammar_20which_20is_20available_20at_20tudyx_20s_20log_20grammar_59',['A search term, &quot;transport&quot; was entered and the file was highlighted with Tudyx&apos;s tree-sitter-log grammar, which is available at &lt;a href=&quot;https://github.com/Tudyx/tree-sitter-log.git&quot;&gt;Tudyx&apos;s log grammar&lt;/a&gt;',['../d4/d47/a03050.html#a-search-term-transport-was-entered-and-the-file-was-highlighted-with-tudyxs-tree-sitter-log-grammar-which-is-available-at-tudyxs-log-grammarhttpsgithubcomtudyxtree-sitter-loggit',1,'']]],
  ['sitter_20on_20linux_60',['Sitter On Linux',['../d2/df1/a03057.html#tree-sitter-on-linux-1',1,'Tree-Sitter On Linux'],['../d1/dff/a03046.html#tree-sitter-on-linux',1,'Tree-Sitter On Linux']]],
  ['sitter_20on_20macos_61',['Sitter On macOS',['../d2/df1/a03057.html#tree-sitter-on-macos-1',1,'Tree-Sitter On macOS'],['../d1/dff/a03046.html#tree-sitter-on-macos',1,'Tree-Sitter On macOS']]],
  ['sitter_20on_20windows_62',['Sitter On Windows',['../d2/df1/a03057.html#tree-sitter-on-windows',1,'Tree-Sitter On Windows'],['../d1/dff/a03046.html#tree-sitter-on-windows-1',1,'Tree-Sitter On Windows']]],
  ['sitter_20parsers_63',['Sitter Parsers',['../d2/df1/a03057.html#tree-sitter-parsers',1,'Tree-Sitter Parsers'],['../d1/dff/a03046.html#tree-sitter-parsers-1',1,'Tree-Sitter Parsers']]],
  ['sitter_20parsers_20on_20linux_64',['Sitter Parsers On Linux',['../d2/df1/a03057.html#tree-sitter-parsers-on-linux',1,'Tree-Sitter Parsers On Linux'],['../d1/dff/a03046.html#tree-sitter-parsers-on-linux-1',1,'Tree-Sitter Parsers On Linux']]],
  ['sitter_20parsers_20on_20macos_65',['Sitter Parsers On macOS',['../d2/df1/a03057.html#tree-sitter-parsers-on-macos',1,'Tree-Sitter Parsers On macOS'],['../d1/dff/a03046.html#tree-sitter-parsers-on-macos-1',1,'Tree-Sitter Parsers On macOS']]],
  ['sitter_20parsers_20on_20windows_66',['Sitter Parsers On Windows',['../d2/df1/a03057.html#tree-sitter-parsers-on-windows',1,'Tree-Sitter Parsers On Windows'],['../d1/dff/a03046.html#tree-sitter-parsers-on-windows-1',1,'Tree-Sitter Parsers On Windows']]],
  ['sitter_20with_20view_67',['View - How to Use Tree-Sitter with View',['../de/dd9/a03058.html#view---how-to-use-tree-sitter-with-view',1,'']]],
  ['smart_20word_20wrapping_68',['C-Menu View - Smart Word Wrapping',['../d4/d47/a03050.html#c-menu-view---smart-word-wrapping',1,'']]],
  ['snacks_20nvim_69',['Snacks nvim',['../d2/df1/a03057.html#folkes-snacksnvim',1,'Folke&apos;s Snacks.nvim'],['../d1/dff/a03046.html#folkes-snacksnvim-1',1,'Folke&apos;s Snacks.nvim'],['../d2/df1/a03057.html#to-use-the-neovim-unicode-art-in-snacksnvim-1',1,'To Use the Neovim Unicode Art in Snacks.nvim'],['../d1/dff/a03046.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'To Use the Neovim Unicode Art in Snacks.nvim']]],
  ['snacks_20nvim_20colorizer_70',['Snacks nvim colorizer',['../d2/df1/a03057.html#to-install-folkes-snacksnvim-colorizer',1,'To Install Folke&apos;s Snacks.nvim-colorizer'],['../d1/dff/a03046.html#to-install-folkes-snacksnvim-colorizer-1',1,'To Install Folke&apos;s Snacks.nvim-colorizer']]],
  ['snippets_71',['snippets',['../dd/d7c/a03072.html',1,'']]],
  ['soap_20box_72',['Visual Aids Soap-box',['../de/dd9/a03058.html#visual-aids-soap-box',1,'']]],
  ['some_20menu_20selections_20don_20t_20work_73',['Some Menu Selections Don&apos;t work',['../de/dd9/a03058.html#some-menu-selections-dont-work',1,'']]],
  ['source_74',['Source',['../d6/deb/a03061.html#download-and-install-c-menu-source',1,'Download and Install C-Menu Source'],['../da/de2/a03067.html#rustlings-source-2',1,'Rustlings Source'],['../de/d38/a03064.html#rustlings-source-1',1,'Rustlings Source'],['../d4/d47/a03050.html#rustlings-source',1,'Rustlings Source']]],
  ['source_20with_20tree_20sitter_75',['View C-Menu Source With Tree-Sitter',['../da/de2/a03067.html#view-c-menu-source-with-tree-sitter-1',1,'']]],
  ['source_20with_20tree_20sitter_76',['View C-Menu Source with Tree-Sitter',['../d4/d47/a03050.html#view-c-menu-source-with-tree-sitter',1,'']]],
  ['source_20with_20tree_20sitter_77',['View Source with Tree-sitter',['../d4/d47/a03050.html#view-source-with-tree-sitter',1,'']]],
  ['space_78',['Demand Paged Virtual Address Space',['../d4/d44/a03065.html#demand-paged-virtual-address-space',1,'']]],
  ['specific_20environment_20variables_79',['System Specific Environment Variables',['../dd/d7c/a03072.html#system-specific-environment-variables',1,'']]],
  ['specifiers_80',['Form Line Type Specifiers',['../d7/d8c/a03049.html#form-line-type-specifiers',1,'']]],
  ['speecifiers_20h_20t_20f_20and_81',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../de/dd9/a03058.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['standard_20colors_82',['STANDARD COLORS',['../d6/dfe/a03053.html#standard-colors',1,'STANDARD COLORS'],['../dc/dec/a03063.html#standard-colors-1',1,'STANDARD COLORS'],['../d4/d15/a03052.html#standard-colors-2',1,'STANDARD COLORS']]],
  ['standards_83',['Our Standards',['../de/d96/a03054.html#our-standards',1,'']]],
  ['start_84',['Start',['../d7/d5a/a03069.html#quick-start',1,'Quick Start'],['../index.html#quick-start-1',1,'Quick Start']]],
  ['start_20up_20options_85',['Start up Options',['../de/d38/a03064.html',1,'C-Menu Start-up Options'],['../d4/d47/a03050.html#c-menu-start-up-options',1,'C-Menu Start-up Options']]],
  ['started_86',['Getting Started',['../d7/d8c/a03049.html#getting-started',1,'']]],
  ['starting_20c_20menu_87',['Starting C Menu',['../d4/d47/a03050.html#starting-c-menu',1,'Starting C-Menu'],['../d7/d8c/a03049.html#starting-c-menu-1',1,'Starting C-Menu']]],
  ['startup_20with_20mm_88',['C-Menu Startup with &quot;mm&quot;',['../dd/d7c/a03072.html#c-menu-startup-with-mm',1,'']]],
  ['static_20executables_89',['Static Executables',['../de/dd9/a03058.html#static-executables',1,'']]],
  ['stop_20typing_20vi_90',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../dd/d7c/a03072.html#if-you-cant-stop-typing-vi',1,'']]],
  ['story_91',['Bill Waller&apos;s Life Story',['../d2/de4/a03047.html',1,'']]],
  ['structure_92',['C-Menu&apos;s File Structure',['../de/dd9/a03058.html#c-menus-file-structure',1,'']]],
  ['sub_20menus_93',['Sub-Menus',['../de/d38/a03064.html#sub-menus',1,'']]],
  ['submit_20code_20pull_20request_20process_94',['🛠️ How to Submit Code (Pull Request Process)',['../df/d0c/a03055.html#️-how-to-submit-code-pull-request-process',1,'']]],
  ['suffixes_95',['Can lf match files with multiple suffixes',['../de/dd9/a03058.html#can-lf-match-files-with-multiple-suffixes',1,'']]],
  ['suggest_20a_20feature_96',['💡 How to Suggest a Feature',['../df/d0c/a03055.html#autotoc_md-how-to-suggest-a-feature',1,'']]],
  ['summary_97',['Summary',['../d4/df3/a03066.html#summary',1,'']]],
  ['support_98',['TrueColor Support',['../de/dd9/a03058.html#truecolor-support',1,'']]],
  ['suppression_20file_99',['Suppression File',['../d1/d44/a03074.html#suppression-file',1,'']]],
  ['synopsis_100',['SYNOPSIS',['../d6/dfe/a03053.html#synopsis',1,'SYNOPSIS'],['../d6/d2a/a03062.html#synopsis-1',1,'SYNOPSIS'],['../dc/dec/a03063.html#synopsis-3',1,'SYNOPSIS'],['../d4/d15/a03052.html#synopsis-2',1,'SYNOPSIS'],['../df/d48/a03071.html#synopsis-4',1,'SYNOPSIS']]],
  ['syntax_101',['SYNTAX',['../d6/dfe/a03053.html#cmenu-menu-command-syntax',1,'CMENU MENU COMMAND SYNTAX'],['../d4/d15/a03052.html#cmenu-menu-command-syntax-1',1,'CMENU MENU COMMAND SYNTAX']]],
  ['syntax_102',['Form Line Syntax',['../d7/d8c/a03049.html#form-line-syntax',1,'']]],
  ['syntax_20highlighting_103',['Menu Description With Bat Syntax Highlighting',['../d4/d47/a03050.html#menu-description-with-bat-syntax-highlighting',1,'']]],
  ['system_20configurations_104',['Exercise 1: System Configurations',['../d4/d90/a03056.html#exercise-1-system-configurations',1,'']]],
  ['system_20specific_20environment_20variables_105',['System Specific Environment Variables',['../dd/d7c/a03072.html#system-specific-environment-variables',1,'']]]
];
