var searchData=
[
  ['gamma_0',['Gray Gamma',['../da/de0/a01248.html#gray-gamma',1,'']]],
  ['gamma_20correction_1',['3-Channel Gamma Correction',['../da/de0/a01248.html#autotoc_md3-channel-gamma-correction',1,'']]],
  ['gawk_2',['High Precision Math With C-Menu and Gawk',['../d7/d04/a01246.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['gdb_20debugging_20setup_3',['GDB Debugging Setup',['../d4/d22/a01250.html#gdb-debugging-setup',1,'']]],
  ['general_4',['General',['../d3/d7b/a01249.html#general',1,'General'],['../d3/d7b/a01249.html#general-1',1,'General']]],
  ['get_20c_20menu_20on_20github_5',['Get C Menu on Github',['../d3/d07/a01241.html#get-c-menu-on-github',1,'Get C-Menu on Github'],['../d7/dc5/a01242.html#get-c-menu-on-github-1',1,'Get C-Menu on Github'],['../d1/d31/a01245.html#get-c-menu-on-github-2',1,'Get C-Menu on Github'],['../da/de0/a01248.html#get-c-menu-on-github-3',1,'Get C-Menu on Github']]],
  ['get_20rusty_6',['Let&apos;s Get Rusty',['../d1/d31/a01245.html#lets-get-rusty',1,'']]],
  ['getting_20started_7',['Getting Started',['../d7/dc5/a01242.html#getting-started',1,'']]],
  ['ghostty_8',['Ghostty',['../d1/d31/a01245.html#ghostty',1,'Ghostty'],['../d4/d22/a01250.html#ghostty-1',1,'Ghostty']]],
  ['ghostty_20configuration_9',['Ghostty Configuration',['../d4/dd5/a01244.html#ghostty-configuration',1,'Ghostty Configuration'],['../d1/d31/a01245.html#ghostty-configuration-1',1,'Ghostty Configuration']]],
  ['ghostty_20on_20linux_10',['Ghostty On Linux',['../d1/d31/a01245.html#ghostty-on-linux',1,'']]],
  ['ghostty_20on_20macos_11',['Ghostty On macOS',['../d1/d31/a01245.html#ghostty-on-macos',1,'']]],
  ['ghostty_20on_20windows_12',['Ghostty On Windows',['../d1/d31/a01245.html#ghostty-on-windows',1,'']]],
  ['github_13',['Github',['../d7/d04/a01246.html#download-from-github',1,'Download From Github'],['../d3/d07/a01241.html#get-c-menu-on-github',1,'Get C-Menu on Github'],['../d7/dc5/a01242.html#get-c-menu-on-github-1',1,'Get C-Menu on Github'],['../d1/d31/a01245.html#get-c-menu-on-github-2',1,'Get C-Menu on Github'],['../da/de0/a01248.html#get-c-menu-on-github-3',1,'Get C-Menu on Github']]],
  ['github_20repository_14',['GitHub repository',['../d3/d07/a01241.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d7/dc5/a01242.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d4/dd5/a01244.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d1/d31/a01245.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-3',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d7/d04/a01246.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-4',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../dd/d95/a01247.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-5',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../index.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-6',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['gray_20gamma_15',['Gray Gamma',['../da/de0/a01248.html#gray-gamma',1,'']]],
  ['guide_16',['Guide',['../dd/d95/a01247.html',1,'Installation Guide'],['../index.html',1,'Installation Guide'],['../d3/d07/a01241.html#roadmap-for-api-documentation-and-user-guide',1,'Roadmap for API Documentation and User Guide']]],
  ['guide_17',['User guide',['../d7/dc5/a01242.html',1,'']]]
];
