var searchData=
[
  ['i_20rely_20on_20find_20s_20features_0',['lf is fast, but I rely on find&apos;s features',['../dd/d8b/a01363.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['icon_1',['What&apos;s the Icon?',['../dd/d8b/a01363.html#whats-the-icon',1,'']]],
  ['if_20you_20can_20t_20stop_20typing_20vi_2',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../d1/d17/a01369.html#if-you-cant-stop-typing-vi',1,'']]],
  ['if_20you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_3',['If you encounter any issues or have questions feel free to open an issue on the C Menu GitHub repository',['../de/d5c/a01358.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../df/d10/a01357.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../da/dab/a01362.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['important_20note_20about_20gmtime_5fr_4',['Important note about &lt;span class=&quot;tt&quot;&gt;gmtime_r()&lt;/span&gt;',['../de/d1f/a01364.html#important-note-about-gmtime_r',1,'']]],
  ['in_20a_20box_20window_5',['View In a Box Window',['../dd/d8b/a01363.html#view-in-a-box-window',1,'']]],
  ['in_20current_20directory_6',['in Current Directory',['../dc/d4b/a01359.html#edit-c-files-in-current-directory',1,'Edit .c Files in Current Directory'],['../dc/d4b/a01359.html#edit-c-files-in-current-directory-1',1,'Edit .c Files in Current Directory']]],
  ['in_20neovim_7',['Completions in Neovim',['../d7/d81/a01365.html#completions-in-neovim',1,'']]],
  ['in_20snacks_20nvim_8',['To Use the Neovim Unicode Art in Snacks.nvim',['../da/dab/a01362.html#to-use-the-neovim-unicode-art-in-snacksnvim',1,'']]],
  ['in_20view_9',['Large Log File in View',['../d6/dfe/a01366.html#large-log-file-in-view',1,'']]],
  ['include_20cm_20h_10',['include/cm.h',['../df/d10/a01357.html#includecmh',1,'']]],
  ['include_20common_20h_11',['include/common.h',['../df/d10/a01357.html#includecommonh',1,'']]],
  ['include_20menu_20h_20form_20h_20pick_20h_20and_20view_20h_12',['include/menu.h, form.h, pick.h, and view.h',['../df/d10/a01357.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['include_20version_20h_20and_20version_20h_13',['include/version.h and version.h',['../df/d10/a01357.html#includeversionh-and-versionh',1,'']]],
  ['indicator_20shell_20prompts_14',['Privilege Indicator Shell Prompts',['../d1/d17/a01369.html#privilege-indicator-shell-prompts',1,'']]],
  ['initial_20release_15',['1.0.0 - Initial Release',['../dd/d0c/a01368.html#autotoc_md100---initial-release',1,'']]],
  ['inode_16',['Menu - What Happened to Delete by Inode',['../dd/d8b/a01363.html#menu---what-happened-to-delete-by-inode',1,'']]],
  ['input_17',['C-Keys - Diagnose Keyboard/Mouse Input',['../d6/dfe/a01366.html#c-keys---diagnose-keyboardmouse-input',1,'']]],
  ['install_20folke_20s_20lazyvim_18',['To Install Folke&apos;s LazyVim',['../da/dab/a01362.html#to-install-folkes-lazyvim',1,'']]],
  ['install_20folke_20s_20snacks_20nvim_20colorizer_19',['To Install Folke&apos;s Snacks.nvim-colorizer',['../da/dab/a01362.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['install_20norcalli_20s_20nvim_20colorizer_20lua_20',['To Install Norcalli&apos;s nvim-colorizer.lua',['../da/dab/a01362.html#to-install-norcallis-nvim-colorizerlua',1,'']]],
  ['install_20tree_20sitter_20cli_21',['Install Tree-Sitter-CLI',['../dd/d8b/a01363.html#install-tree-sitter-cli',1,'']]],
  ['installation_22',['C-Menu INSTALLATION',['../d7/d81/a01365.html#c-menu-installation',1,'']]],
  ['installation_23',['Finish the installation',['../d7/d81/a01365.html#finish-the-installation',1,'']]],
  ['installing_20bat_24',['Installing Bat',['../da/dab/a01362.html#installing-bat',1,'']]],
  ['installing_20ripgrep_25',['Installing Ripgrep',['../da/dab/a01362.html#installing-ripgrep',1,'']]],
  ['installing_20rust_26',['Installing Rust',['../da/dab/a01362.html#installing-rust',1,'']]],
  ['installing_20rust_20on_20linux_20and_20macos_27',['Installing Rust On Linux and macOS',['../da/dab/a01362.html#installing-rust-on-linux-and-macos',1,'']]],
  ['installment_20loan_20calculations_28',['Installment Loan Calculations',['../dc/d4b/a01359.html#installment-loan-calculations',1,'Installment Loan Calculations'],['../dc/d4b/a01359.html#installment-loan-calculations-1',1,'Installment Loan Calculations']]],
  ['installment_20loan_20calculator_29',['Menu - Using the Installment Loan Calculator',['../dd/d8b/a01363.html#menu---using-the-installment-loan-calculator',1,'']]],
  ['instead_20of_20ls_30',['Use lsd or eza instead of ls',['../d1/d17/a01369.html#use-lsd-or-eza-instead-of-ls',1,'']]],
  ['integrating_20external_20executables_31',['Menu Form - Integrating External Executables',['../dd/d8b/a01363.html#menu-form---integrating-external-executables',1,'']]],
  ['integration_20with_20neovim_32',['&lt;b&gt;&lt;em&gt;New API Integration With Neovim&lt;/em&gt;&lt;/b&gt;',['../d6/dfe/a01366.html#_new-api-integration-with-neovim_',1,'']]],
  ['intended_33',['Highlights (Pun Intended)',['../d6/dfe/a01366.html#highlights-pun-intended',1,'']]],
  ['interface_20toolkit_34',['C-Menu - A User Interface Toolkit',['../d7/d81/a01365.html',1,'']]],
  ['interpretation_20of_20the_20original_20test_20cases_35',['Revised interpretation of the original test cases',['../de/d1f/a01364.html#revised-interpretation-of-the-original-test-cases',1,'']]],
  ['interprocess_20communications_36',['Menu - Interprocess Communications',['../dd/d8b/a01363.html#menu---interprocess-communications',1,'']]],
  ['introduction_37',['Introduction',['../d6/dfe/a01366.html#c-menu-introduction',1,'C-Menu Introduction'],['../df/d10/a01357.html#introduction',1,'Introduction'],['../de/d5c/a01358.html#introduction-1',1,'Introduction'],['../d2/d1f/a01361.html#introduction-2',1,'Introduction'],['../da/dab/a01362.html#introduction-3',1,'Introduction'],['../d7/d81/a01365.html#introduction-4',1,'Introduction']]],
  ['is_20fast_20but_20i_20rely_20on_20find_20s_20features_38',['lf is fast, but I rely on find&apos;s features',['../dd/d8b/a01363.html#lf-is-fast-but-i-rely-on-finds-features',1,'']]],
  ['issue_20on_20the_20c_20menu_20github_20repository_39',['issue on the C Menu GitHub repository',['../de/d5c/a01358.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../df/d10/a01357.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../da/dab/a01362.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_40',['issues or have questions feel free to open an issue on the C Menu GitHub repository',['../de/d5c/a01358.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository'],['../df/d10/a01357.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../da/dab/a01362.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-2',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['it_41',['Just Do It',['../d6/dfe/a01366.html#just-do-it',1,'']]],
  ['items_42',['Selecting Items',['../de/d5c/a01358.html#selecting-items',1,'']]]
];
