var searchData=
[
  ['f_20and_0',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../de/dc8/a00325.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['features_1',['Features',['../index.html#_new-features_',1,'&lt;b&gt;&lt;em&gt;NEW Features&lt;/em&gt;&lt;/b&gt;'],['../index.html#features',1,'Features'],['../index.html#form-key-features',1,'Form Key Features'],['../index.html#key-features',1,'Key Features'],['../db/d53/a00321.html#rsh-safety-features',1,'RSH Safety Features'],['../index.html#view---other-features',1,'View - Other Features']]],
  ['feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_2',['feel free to open an issue on the C Menu GitHub repository',['../dd/de2/a00320.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d8/d23/a00326.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['field_20delimiters_3',['Field Delimiters',['../db/d53/a00321.html#form-field-delimiters',1,'Form Field Delimiters'],['../de/dc8/a00325.html#menu-form---field-delimiters',1,'Menu Form - Field Delimiters']]],
  ['file_4',['Sample Menu Description File',['../index.html#sample-menu-description-file',1,'']]],
  ['file_20example_5',['Form Description File Example',['../db/d53/a00321.html#form-description-file-example',1,'']]],
  ['file_20format_6',['Menu Description File Format',['../db/d53/a00321.html#menu-description-file-format',1,'']]],
  ['file_20in_20view_7',['Large Log File in View',['../index.html#large-log-file-in-view',1,'']]],
  ['file_20structure_8',['C-Menu&apos;s File Structure',['../de/dc8/a00325.html#c-menus-file-structure',1,'']]],
  ['file_20with_20editor_9',['Log File With Editor',['../index.html#log-file-with-editor',1,'']]],
  ['file_20with_20view_10',['Screenshot of the Same File With View',['../index.html#screenshot-of-the-same-file-with-view',1,'']]],
  ['files_11',['Files',['../d8/dfc/a00327.html#c-menu-desktop-files',1,'C-Menu Desktop Files'],['../dd/de2/a00320.html#c-menu-header-files',1,'C-Menu Header Files'],['../de/dc8/a00325.html#menu-lf---where-are-my-header-files',1,'Menu lf - Where Are My Header Files?'],['../de/dc8/a00325.html#pick---selecting-multiple-files',1,'Pick - Selecting Multiple Files']]],
  ['files_20using_20regular_20expressions_12',['lf - List Files Using Regular Expressions',['../index.html#lf---list-files-using-regular-expressions',1,'']]],
  ['finish_20the_20installation_13',['Finish the installation',['../d8/d23/a00326.html#finish-the-installation',1,'']]],
  ['fixed_14',['Fixed',['../de/de9/a00322.html#fixed',1,'']]],
  ['folke_15',['Folke',['../d4/d8f/a00324.html#ai-overview-of-developer-folke',1,'AI Overview of Developer Folke'],['../d4/d8f/a00324.html#folke',1,'Folke']]],
  ['folke_20s_20lazyvim_16',['To Install Folke&apos;s LazyVim',['../d4/d8f/a00324.html#to-install-folkes-lazyvim',1,'']]],
  ['folke_20s_20snacks_20nvim_17',['Folke&apos;s Snacks.nvim',['../d4/d8f/a00324.html#folkes-snacksnvim',1,'']]],
  ['folke_20s_20snacks_20nvim_20colorizer_18',['To Install Folke&apos;s Snacks.nvim-colorizer',['../d4/d8f/a00324.html#to-install-folkes-snacksnvim-colorizer',1,'']]],
  ['fonts_19',['Fonts',['../d4/d8f/a00324.html#fonts',1,'']]],
  ['for_20api_20documentation_20and_20user_20guide_20',['Roadmap for API Documentation and User Guide',['../dd/de2/a00320.html#roadmap-for-api-documentation-and-user-guide',1,'']]],
  ['for_20data_20entry_20and_20editing_21',['Form for Data Entry and Editing',['../index.html#form-for-data-entry-and-editing',1,'']]],
  ['for_20lf_22',['&lt;b&gt;&lt;em&gt;New Options for lf&lt;/em&gt;&lt;/b&gt;',['../index.html#_new-options-for-lf_',1,'']]],
  ['form_23',['C-Menu Form',['../db/d53/a00321.html#c-menu-form',1,'']]],
  ['form_20data_20types_24',['Form Data Types',['../index.html#form-data-types',1,'Form Data Types'],['../db/d53/a00321.html#form-data-types-1',1,'Form Data Types'],['../de/dc8/a00325.html#menu-form---data-types',1,'Menu Form - Data Types']]],
  ['form_20description_20file_20example_25',['Form Description File Example',['../db/d53/a00321.html#form-description-file-example',1,'']]],
  ['form_20field_20delimiters_26',['Form Field Delimiters',['../db/d53/a00321.html#form-field-delimiters',1,'Form Field Delimiters'],['../de/dc8/a00325.html#menu-form---field-delimiters',1,'Menu Form - Field Delimiters']]],
  ['form_20for_20data_20entry_20and_20editing_27',['Form for Data Entry and Editing',['../index.html#form-for-data-entry-and-editing',1,'']]],
  ['form_20h_20pick_20h_20and_20view_20h_28',['include/menu.h, form.h, pick.h, and view.h',['../dd/de2/a00320.html#includemenuh-formh-pickh-and-viewh',1,'']]],
  ['form_20integrating_20external_20executables_29',['Menu Form - Integrating External Executables',['../de/dc8/a00325.html#menu-form---integrating-external-executables',1,'']]],
  ['form_20key_20features_30',['Form Key Features',['../index.html#form-key-features',1,'']]],
  ['form_20line_20syntax_31',['Form Line Syntax',['../db/d53/a00321.html#form-line-syntax',1,'']]],
  ['form_20line_20type_20specifiers_32',['Form Line Type Specifiers',['../db/d53/a00321.html#form-line-type-specifiers',1,'']]],
  ['form_20line_20type_20speecifiers_20h_20t_20f_20and_33',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../de/dc8/a00325.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['form_20options_34',['Form Options',['../db/d53/a00321.html#form-options',1,'']]],
  ['form_20pick_20and_20view_20api_35',['Menu, Form, Pick, and View API',['../de/dc8/a00325.html#menu-form-pick-and-view-api',1,'']]],
  ['form_20pick_20view_20c_20keys_20rsh_20and_20lf_36',['Menu, Form, Pick, View, C-Keys, RSH, and lf',['../index.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'']]],
  ['format_37',['Menu Description File Format',['../db/d53/a00321.html#menu-description-file-format',1,'']]],
  ['forward_38',['Searching Forward',['../db/d53/a00321.html#searching-forward',1,'']]],
  ['free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_39',['free to open an issue on the C Menu GitHub repository',['../dd/de2/a00320.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.'],['../d8/d23/a00326.html#autotoc_md-enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository-1',1,'🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.']]],
  ['frequently_20asked_20questions_40',['Frequently Asked Questions',['../de/dc8/a00325.html',1,'']]],
  ['from_20github_41',['Download From Github',['../de/dc8/a00325.html#download-from-github',1,'']]]
];
