C-Menu: src/scriou.c File Reference
scriou.c File Reference
Screen IO Support for MENU.
#include <cm.h>
#include <stdbool.h>
#include <stdio.h>
#include <termios.h>
#include <unistd.h>
Functions
bool capture_shell_tioctl ()
capture_shell_tioctl() - capture shell terminal settings
bool restore_shell_tioctl ()
restore_shell_tioctl() - restore shell terminal settings
bool capture_curses_tioctl ()
capture_curses_tioctl() - capture curses terminal settings
bool restore_curses_tioctl ()
restore_curses_tioctl() - restore curses terminal settings
bool set_sane_tioctl (struct termios *t_p)
set_sane_tioctl() - set terminal to sane settings for C-MENU
bool mk_raw_tioctl (struct termios *t_p)
mk_raw_tioctl() - set terminal to raw mode
char di_getch ()
sget single character from terminal in raw mode
Variables
struct termios shell_tioctl
struct termios curses_tioctl
bool f_have_shell_tioctl = false
bool f_have_curses_tioctl = false
struct termios shell_in_tioctl curses_in_tioctl
struct termios shell_out_tioctl curses_out_tioctl
struct termios shell_err_tioctl curses_err_tioctl
Detailed Description
Screen IO Support for MENU.
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file scriou.c.
Function Documentation
capture_curses_tioctl()
bool capture_curses_tioctl ()
capture_curses_tioctl() - capture curses terminal settings
Returns
- true on success
Note
- captures terminal settings for stdin, stdout, and stderr
Definition at line 60 of file scriou.c.
{
    if (f_have_curses_tioctl)
        return true;
    tcgetattr(0, &curses_tioctl);
    f_have_curses_tioctl = true;
    return true;
}
References curses_tioctl, and f_have_curses_tioctl.
Referenced by fork_exec(), and main().
capture_shell_tioctl()
bool capture_shell_tioctl ()
capture_shell_tioctl() - capture shell terminal settings
Returns
- true on success
Note
- captures terminal settings for stdin, stdout, and stderr
Examples
/usr/local/src/cmenu/src/enterchr.c, and /usr/local/src/cmenu/src/enterstr.c.
Definition at line 40 of file scriou.c.
{
    if (f_have_shell_tioctl)
        return true;
    tcgetattr(0, &shell_tioctl);
    tcgetattr(2, &shell_err_tioctl);
    f_have_shell_tioctl = true;
    return true;
}
References f_have_shell_tioctl, and shell_tioctl.
Referenced by main().
di_getch()
char di_getch ()
sget single character from terminal in raw mode
Returns
- the character read from terminal
Note
restores terminal settings
Definition at line 122 of file scriou.c.
                {
    struct termios org_tioctl, new_tioctl;
    char buf;
    if (tcgetattr(2, &org_tioctl) == -1) {
        fprintf(stderr, "\ndi_getch: tcgetattr failed\n");
        return (0);
    }
    new_tioctl = org_tioctl;
    new_tioctl.c_lflag &= ~(ECHO | ICANON);
    new_tioctl.c_cc[VMIN] = 1;
    new_tioctl.c_cc[VTIME] = 0;
    tcsetattr(2, TCSAFLUSH, &new_tioctl);
    read(2, &buf, 1);
    tcsetattr(2, TCSAFLUSH, &org_tioctl);
    return (buf);
}
Referenced by nf_error(), and usage().
mk_raw_tioctl()
bool mk_raw_tioctl (struct termios * t_p)
mk_raw_tioctl() - set terminal to raw mode
Parameters
t_p - pointer to termios structure to modify
Returns
- true on success
Note
- unlike cfmakeraw(), this leaves ISIG enabled.
- cfmakeraw() disables ISIG, which prevents C-MENU from handling signals like Ctrl-C. Instead of using cfmakeraw(), we manually set the terminal to raw mode while leaving ISIG enabled.
- the following code is equivalent to cfmakeraw() but with ISIG left enabled:
t_p->c_iflag &= ~(IGNBRK | BRKINT | PARMRK | INPCK | ISTRIP | INLCR |
               IGNCR | ICRNL | IXON | IXOFF);
t_p->c_lflag &= ~(ECHO | ECHONL | ICANON | IEXTEN);
t_p->c_cflag &= ~(CSIZE | PARENB);
t_p->c_cflag |= CS8 | CLOCAL;
Examples
/usr/local/src/cmenu/src/enterchr.c.
Definition at line 110 of file scriou.c.
{
    tcgetattr(0, t_p);
    t_p->c_lflag |= ISIG;
    t_p->c_lflag &= ~(ECHO | ICANON);
    t_p->c_cc[VMIN] = 1;
    t_p->c_cc[VTIME] = 0;
    tcsetattr(0, TCSAFLUSH, t_p);
    return true;
}
Referenced by main().
restore_curses_tioctl()
bool restore_curses_tioctl ()
restore_curses_tioctl() - restore curses terminal settings
Returns
- true on success
Note
- restores terminal settings for stdin, stdout, and stderr
Definition at line 70 of file scriou.c.
{
    if (!f_have_curses_tioctl)
        return false;
    tcsetattr(0, TCSANOW, &curses_tioctl);
    return true;
}
References curses_tioctl, and f_have_curses_tioctl.
Referenced by exec_objects(), fork_exec(), and init_pick().
restore_shell_tioctl()
bool restore_shell_tioctl ()
restore_shell_tioctl() - restore shell terminal settings
Returns
- true on success
Note
- restores terminal settings for stdin, stdout, and stderr
Examples
/usr/local/src/cmenu/src/enterchr.c, and /usr/local/src/cmenu/src/enterstr.c.
Definition at line 51 of file scriou.c.
{
    if (!f_have_shell_tioctl)
        return false;
    tcsetattr(0, TCSANOW, &shell_tioctl);
    return true;
}
References f_have_shell_tioctl, and shell_tioctl.
Referenced by abend(), destroy_curses(), fork_exec(), handle_signal(), main(), and user_end().
set_sane_tioctl()
bool set_sane_tioctl (struct termios * t_p)
set_sane_tioctl() - set terminal to sane settings for C-MENU
Parameters
t_p - pointer to termios structure to modify
Returns
- true on success
Note
- sets terminal to sane settings for C-MENU applications
Definition at line 80 of file scriou.c.
{
    tcgetattr(0, t_p);
    t_p->c_iflag &= ~(IGNBRK | BRKINT | PARMRK | INPCK | ISTRIP | INLCR |
                      IGNCR | ICRNL | IXON | IXOFF);
    t_p->c_iflag |= IUTF8;
    t_p->c_oflag |= OPOST | OCRNL;
    t_p->c_lflag &= ~(ECHO | ECHONL | ICANON | IEXTEN);
    t_p->c_lflag |= (ISIG | ICANON | IEXTEN | ECHO | ECHOE | ECHOK);
    t_p->c_cflag &= ~(CSIZE | PARENB);
    t_p->c_cflag |= CS8 | CLOCAL | CREAD;
    tcsetattr(0, TCSANOW, t_p);
    return true;
}
Variable Documentation
curses_err_tioctl
struct termios shell_err_tioctl curses_err_tioctl
Definition at line 35 of file scriou.c.
curses_in_tioctl
struct termios shell_in_tioctl curses_in_tioctl
Definition at line 33 of file scriou.c.
curses_out_tioctl
struct termios shell_out_tioctl curses_out_tioctl
Definition at line 34 of file scriou.c.
curses_tioctl
struct termios shell_tioctl curses_tioctl
Definition at line 21 of file scriou.c.
Referenced by capture_curses_tioctl(), and restore_curses_tioctl().
f_have_curses_tioctl
bool f_have_curses_tioctl = false
Definition at line 23 of file scriou.c.
Referenced by capture_curses_tioctl(), and restore_curses_tioctl().
f_have_shell_tioctl
bool f_have_shell_tioctl = false
Definition at line 22 of file scriou.c.
Referenced by capture_shell_tioctl(), and restore_shell_tioctl().
shell_tioctl
struct termios shell_tioctl
This file contains terminal ioctl handling functions for C-MENU. It provide sane terminal settings for C-MENU applications, and restores the terminal to its original state when the C-MENU application exits.
Examples
/usr/local/src/cmenu/src/enterchr.c, and /usr/local/src/cmenu/src/enterstr.c.
Definition at line 20 of file scriou.c.
Referenced by capture_shell_tioctl(), main(), restore_shell_tioctl(), and signal_handler().