.TH "src Directory Reference" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBckeys\&.c\fP"
.br
.RI "Test Curses Keys\&. "
.ti -1c
.RI "file \fBcurskeys\&.c\fP"
.br
.RI "Test Curses Keys\&. "
.ti -1c
.RI "file \fBdwin\&.c\fP"
.br
.RI "Window support for C-Menu Menu, Form, Pick, and View\&. "
.ti -1c
.RI "file \fBenterchr\&.c\fP"
.br
.RI "Enter a single character from keyboard\&. "
.ti -1c
.RI "file \fBenterstr\&.c\fP"
.br
.RI "Enter a string from keyboard\&. "
.ti -1c
.RI "file \fBexec\&.c\fP"
.br
.RI "Functions to execute external commands\&. "
.ti -1c
.RI "file \fBfields\&.c\fP"
.br
.RI "Field Edit and Entry for C-Menu Form\&. "
.ti -1c
.RI "file \fBform\&.c\fP"
.br
.RI "Command Line Start-up for C-Menu Form\&. "
.ti -1c
.RI "file \fBform_engine\&.c\fP"
.br
.RI "The working part of C-Menu Form\&. "
.ti -1c
.RI "file \fBfutil\&.c\fP"
.br
.RI "General utility functions\&. "
.ti -1c
.RI "file \fBiloan\&.c\fP"
.br
.RI "Installment Loan Calculator\&. "
.ti -1c
.RI "file \fBinit\&.c\fP"
.br
.RI "Initialization for Menu Application Programs\&. "
.ti -1c
.RI "file \fBinit_view\&.c\fP"
.br
.RI "Initialize C-Menu View Screen IO and Input\&. "
.ti -1c
.RI "file \fBlf\&.c\fP"
.br
.RI "list files matching a regular expression "
.ti -1c
.RI "file \fBmem\&.c\fP"
.br
.RI "Create and destroy main data structures for C-Menu\&. "
.ti -1c
.RI "file \fBmenu\&.c\fP"
.br
.RI "Command line start-up for C-Menu\&. "
.ti -1c
.RI "file \fBmenu_engine\&.c\fP"
.br
.RI "The working part of C-Menu Menu\&. "
.ti -1c
.RI "file \fBmview\&.c\fP"
.br
.RI "Callable Startup for C-Menu View\&. "
.ti -1c
.RI "file \fBopts\&.c\fP"
.br
.RI "Sort and print options\&. "
.ti -1c
.RI "file \fBoptsp\&.c\fP"
.br
.RI "print option list for C-Menu "
.ti -1c
.RI "file \fBparse_menu_desc\&.c\fP"
.br
.RI "Parse menu description file and create Menu\&. "
.ti -1c
.RI "file \fBpick\&.c\fP"
.br
.RI "Command Line Entry Point for C-Menu Pick\&. "
.ti -1c
.RI "file \fBpick_engine\&.c\fP"
.br
.RI "pick from a list of choices "
.ti -1c
.RI "file \fBrsh\&.c\fP"
.br
.RI "restricted shell to run bash as root "
.ti -1c
.RI "file \fBscriou\&.c\fP"
.br
.RI "Screen IO Support for MENU\&. "
.ti -1c
.RI "file \fBsig\&.c\fP"
.br
.RI "signal handling for interrupt signals "
.ti -1c
.RI "file \fBstripansi\&.c\fP"
.br
.RI "removes ansi escape sequences beginning with "\\033["" and ending in"m" or "K" "
.ti -1c
.RI "file \fBview\&.c\fP"
.br
.RI "Command Line Start-up for C-Menu View\&. "
.ti -1c
.RI "file \fBview_engine\&.c\fP"
.br
.RI "The working part of View\&. "
.ti -1c
.RI "file \fBwhence\&.c\fP"
.br
.RI "Find the full path of a file in the directories specified by the\&. "
.in -1c
