.TH "src/enterchr.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/enterchr.c \- Enter a single character from keyboard\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <cm\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <sys/ioctl\&.h>\fP
.br
\fR#include <termios\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "Capture the current terminal settings for later restoration\&. "
.in -1c
.SH "Detailed Description"
.PP 
Enter a single character from keyboard\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBenterchr\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Capture the current terminal settings for later restoration\&. 
.PP
\fBNote\fP
.RS 4
can be used in scripts to get a single character response from a user\&. For example: response=$(\&./enterchr "Enter Y or N: ") if [ "$response" = "Y" ]; then echo "You entered Yes" else echo "You entered No" fi 

.PP
This function saves the current terminal settings into a global variable so that they can be restored later\&. It should be called before modifying the terminal settings to ensure that the original settings can be restored when the program exits or is interrupted\&. 
.RE
.PP

.PP
Definition at line \fB38\fP of file \fBenterchr\&.c\fP\&.
.nf
38                                 {
39     char c = 'Y';
40     char *msg;
41     struct termios raw_tioctl;
42     char errmsg[128];
43 
44     if (argc < 2)
45         strcpy(errmsg, "Press any key");
46     else
47         strcpy(errmsg, argv[1]);
48     capture_shell_tioctl();
49     raw_tioctl = shell_tioctl;
50     mk_raw_tioctl(&raw_tioctl);
51     tcflush(0, TCOFLUSH);
52     while (1) {
53         msg = errmsg;
54         while (*msg) {
55             write(2, msg++, 1);
56         }
57         if (read(0, &c, 1) > 0) {
58             write(1, &c, 1);
59             break;
60         }
61     }
62     restore_shell_tioctl();
63     if (c == (char)0x1b)
64         return (1);
65     return (0);
66 }
.PP
.fi

.PP
References \fBcapture_shell_tioctl()\fP, \fBerrmsg\fP, \fBmk_raw_tioctl()\fP, \fBrestore_shell_tioctl()\fP, and \fBshell_tioctl\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
