.TH "src/form_engine.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/form_engine.c \- The working part of C-Menu Form\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <common\&.h>\fP
.br
\fR#include <errno\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <sys/stat\&.h>\fP
.br
\fR#include <termios\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <wait\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBD_COMMENT\fP   '#'"
.br
.ti -1c
.RI "#define \fBD_CMD\fP   '!'"
.br
.ti -1c
.RI "#define \fBD_FIELD\fP   'F'"
.br
.ti -1c
.RI "#define \fBD_TEXT\fP   'T'"
.br
.ti -1c
.RI "#define \fBD_HELP\fP   '?'"
.br
.ti -1c
.RI "#define \fBD_HEADER\fP   'H'"
.br
.ti -1c
.RI "#define \fBD_CALC\fP   'C'"
.br
.ti -1c
.RI "#define \fBD_QUERY\fP   'Q'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBform_display_screen\fP (Init *\fBinit\fP)"
.br
.RI "Display the form on the screen, including text elements and fields, and set up the form window based on the form configuration\&. "
.ti -1c
.RI "void \fBform_display_fields\fP (Form *\fBform\fP)"
.br
.RI "Display form fields on the screen, populating field values and formatting them according to the form configuration\&. "
.ti -1c
.RI "void \fBform_display_chyron\fP (Form *\fBform\fP)"
.br
.RI "Display the chyron (status line) at the bottom of the form window, showing available commands and their corresponding function keys\&. "
.ti -1c
.RI "int \fBform_enter_fields\fP (Form *\fBform\fP)"
.br
.RI "Handle user input for field entry, allowing navigation between fields and looping until an exit action is selected\&. "
.ti -1c
.RI "int \fBform_parse_desc\fP (Form *\fBform\fP)"
.br
.RI "Parse the form description file to populate the Form data structure with field definitions, text elements, and other configuration specified in the description file\&. "
.ti -1c
.RI "int \fBform_read_data\fP (Form *\fBform\fP)"
.br
.RI "Read initial data for form fields from a specified input source, such as a file or standard input, and populate the form fields with the data\&. "
.ti -1c
.RI "int \fBform_write\fP (Form *\fBform\fP)"
.br
.RI "Write form field values to a specified output destination, such as a file or standard output, based on the form configuration and user input\&. "
.ti -1c
.RI "void \fBform_usage\fP ()"
.br
.RI "Display usage information for the form, including available options and commands, to assist users in understanding how to interact with the form\&. "
.ti -1c
.RI "int \fBform_desc_error\fP (int in_line_num, char *in_buf, char *em)"
.br
.RI "Handle errors encountered while parsing the form description file, providing detailed error messages that include the file name, line number, and the specific error encountered\&. "
.ti -1c
.RI "int \fBform_exec_cmd\fP (Form *\fBform\fP)"
.br
.RI "Execute a provider command specified in the form description file, passing form field values as arguments, and optionally redirecting output to a file\&. "
.ti -1c
.RI "int \fBform_calculate\fP (Init *\fBinit\fP)"
.br
.RI "Handle integration with an external program for calculation, allowing the user to execute a provider command and read results back into the form fields\&. "
.ti -1c
.RI "int \fBform_end_fields\fP (Init *\fBinit\fP)"
.br
.RI "Handle post-processing after field entry, allowing user to edit data, execute a provider command, or write data to an output file\&. "
.ti -1c
.RI "int \fBinit_form\fP (Init *\fBinit\fP, int argc, char **argv, int begy, int begx)"
.br
.RI "Initialize form data structure and parse description file\&. "
.ti -1c
.RI "int \fBform_engine\fP (Init *\fBinit\fP)"
.br
.RI "Form main processing loop\&. "
.ti -1c
.RI "int \fBform_yx_to_fidx\fP (Form *, int, int)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The working part of C-Menu Form\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBform_engine\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define D_CALC   'C'"

.PP
Definition at line \fB26\fP of file \fBform_engine\&.c\fP\&.
.PP
Referenced by \fBform_parse_desc()\fP\&.
.SS "#define D_CMD   '!'"

.PP
Definition at line \fB21\fP of file \fBform_engine\&.c\fP\&.
.PP
Referenced by \fBform_parse_desc()\fP\&.
.SS "#define D_COMMENT   '#'"

.PP
Definition at line \fB20\fP of file \fBform_engine\&.c\fP\&.
.PP
Referenced by \fBform_parse_desc()\fP\&.
.SS "#define D_FIELD   'F'"

.PP
Definition at line \fB22\fP of file \fBform_engine\&.c\fP\&.
.PP
Referenced by \fBform_parse_desc()\fP\&.
.SS "#define D_HEADER   'H'"

.PP
Definition at line \fB25\fP of file \fBform_engine\&.c\fP\&.
.PP
Referenced by \fBform_parse_desc()\fP\&.
.SS "#define D_HELP   '?'"

.PP
Definition at line \fB24\fP of file \fBform_engine\&.c\fP\&.
.PP
Referenced by \fBform_parse_desc()\fP\&.
.SS "#define D_QUERY   'Q'"

.PP
Definition at line \fB27\fP of file \fBform_engine\&.c\fP\&.
.PP
Referenced by \fBform_parse_desc()\fP\&.
.SS "#define D_TEXT   'T'"

.PP
Definition at line \fB23\fP of file \fBform_engine\&.c\fP\&.
.PP
Referenced by \fBform_parse_desc()\fP\&.
.SH "Function Documentation"
.PP 
.SS "int form_calculate (Init * init)"

.PP
Handle integration with an external program for calculation, allowing the user to execute a provider command and read results back into the form fields\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP A pointer to the Init structure containing form data and state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An integer status code indicating the next action for the form processing loop (e\&.g\&., P_CONTINUE, P_CANCEL, P_ACCEPT, P_HELP)\&.
.RE
.PP
This function provides integration with external programs\&. The requirements are:
.IP "1." 4
The form description file must have a line starting with 'C' to indicate that the form supports calculation\&.
.IP "2." 4
The form description file must specify the provider command using a line starting with '!' followed by the command and its arguments\&.
.IP "3." 4
The external program must be able to accept field data from a file, from standard input, or as command line parameters\&.
.IP "4." 4
The external program must output the calculated field values in a format that can be read by the form (e\&.g\&., one value per line), either to a file or to standard output\&.
.PP

.PP
The sequence of operations is as follows:

.PP
.IP "1." 4
The 'C' option causes Form to pause and display an KEY_F(5) Calculate option on the chyron\&.
.IP "2." 4
The user can then cancel the operation by pressing KEY_F(9) or activate the calculate option by pressing KEY_F(5)\&.
.IP "3." 4
Form outputs its data to file, standard output, or as command line parameters\&.
.IP "4." 4
Form executes the external program\&.
.IP "5." 4
The external program processes the data and outputs the results\&.
.IP "6." 4
Form reads the results and populates the appropriate form fields\&.
.IP "7." 4
Form presents the user with an option to edit the data, and the sequence restarts at 1\&.
.PP

.PP
This function forks and executes the provider executable as a child process, creates a pipe to read the output from the provider command, reads the output, and updates the Form fields\&. 
.PP
Definition at line \fB262\fP of file \fBform_engine\&.c\fP\&.
.nf
262                                {
263     int i, c, rc;
264     char earg_str[MAXLEN + 1];
265     char *eargv[MAXARGS];
266     char file_spec[MAXLEN];
267     bool loop = true;
268     pid_t pid;
269     int pipe_fd[2];
270 
271     form = init\->form;
272     wmove(form\->win, form\->lines \- 1, 0);
273     wclrtoeol(form\->win);
274     unset_chyron_key(form\->chyron, 18);
275     unset_chyron_key(form\->chyron, 10);
276     set_chyron_key(form\->chyron, 5, "F5 Calculate", KEY_F(5));
277 
278     while (loop) {
279         form_display_chyron(form);
280         click_y = click_x = \-1;
281         tcflush(2, TCIFLUSH);
282         c = xwgetch(form\->win, form\->chyron);
283         switch (c) {
284         case KEY_F(1):
285             return P_HELP;
286         case KEY_F(5):
287             if (form\->f_out_spec)
288                 form_write(form);
289             if (form\->f_provider_cmd) {
290                 strnz__cpy(earg_str, form\->provider_cmd, MAXLEN \- 1);
291                 for (i = 0; i < form\->fcnt; i++) {
292                     strnz__cat(earg_str, " ", MAXLEN \- 1);
293                     strnz__cat(earg_str, form\->field[i]\->accept_s, MAXLEN \- 1);
294                 }
295                 str_to_args(eargv, earg_str, MAXARGS);
296                 strnz__cpy(file_spec, eargv[0], MAXLEN \- 1);
297                 base_name(eargv[0], file_spec);
298                 if (pipe(pipe_fd) == \-1) {
299                     Perror("pipe(pipe_fd) failed in init_form");
300                     return (1);
301                 }
302                 if ((pid = fork()) == \-1) {
303                     Perror("fork() failed in init_form");
304                     return (1);
305                 }
306                 if (pid == 0) { // Child
307                     close(pipe_fd[P_READ]);
308                     dup2(pipe_fd[P_WRITE], STDOUT_FILENO);
309                     close(pipe_fd[P_WRITE]);
310                     execvp(eargv[0], eargv);
311                     ssnprintf(em0, MAXLEN, "%s, line: %d", __FILE__,
312                               __LINE__ \- 2);
313                     strnz__cpy(em1, "execvp(", MAXLEN \- 1);
314                     strnz__cat(em1, eargv[0], MAXLEN \- 1);
315                     strnz__cat(em1, ", ", MAXLEN \- 1);
316                     strnz__cat(em1, earg_str, MAXLEN \- 1);
317                     strnz__cat(em1, ")", MAXLEN \- 1);
318                     strerror_r(errno, em2, MAXLEN);
319                     display_error(em0, em1, em2, nullptr);
320                     exit(EXIT_FAILURE);
321                 } // Back to parent
322                 close(pipe_fd[P_WRITE]);
323                 form\->in_fp = fdopen(pipe_fd[P_READ], "rb");
324                 form\->f_in_pipe = true;
325                 form_read_data(form);
326                 close(pipe_fd[P_READ]);
327                 waitpid(pid, nullptr, 0);
328                 form_display_fields(form);
329                 set_chyron_key(form\->chyron, 8, "F5 Edit", KEY_F(5));
330                 set_chyron_key(form\->chyron, 10, "F10 Commit", KEY_F(10));
331                 continue;
332             }
333             break;
334         case KEY_F(8):
335             if (is_set_chyron_key(form\->chyron, 8)) {
336                 loop = false;
337                 rc = P_CONTINUE;
338                 break;
339             }
340             continue;
341         case KEY_F(9):
342             loop = false;
343             rc = P_CANCEL;
344             break;
345         case KEY_F(10):
346             loop = false;
347             rc = P_ACCEPT;
348             break;
349         case KEY_MOUSE:
350             break;
351         default:
352             break;
353         }
354     }
355     unset_chyron_key(form\->chyron, 8);
356     unset_chyron_key(form\->chyron, 5);
357     form_display_chyron(form);
358     return rc;
359 }
.PP
.fi

.PP
References \fBbase_name()\fP, \fBclick_x\fP, \fBclick_y\fP, \fBdisplay_error()\fP, \fBearg_str\fP, \fBeargv\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBform\fP, \fBform_display_chyron()\fP, \fBform_display_fields()\fP, \fBform_read_data()\fP, \fBform_write()\fP, \fBinit\fP, \fBis_set_chyron_key()\fP, \fBMAXLEN\fP, \fBPerror()\fP, \fBpipe_fd\fP, \fBset_chyron_key()\fP, \fBssnprintf()\fP, \fBstr_to_args()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBunset_chyron_key()\fP, and \fBxwgetch()\fP\&.
.PP
Referenced by \fBform_engine()\fP\&.
.SS "int form_desc_error (int in_line_num, char * in_buf, char * em)"

.PP
Handle errors encountered while parsing the form description file, providing detailed error messages that include the file name, line number, and the specific error encountered\&. 
.PP
\fBParameters\fP
.RS 4
\fIin_line_num\fP The line number in the description file where the error occurred\&. 
.br
\fIin_buf\fP The content of the line that caused the error, for context\&. 
.br
\fIem\fP A specific error message describing the nature of the error\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An integer status code indicating how the user responded to the error message (e\&.g\&., which key they pressed to acknowledge the error)\&. 
.RE
.PP

.PP
Definition at line \fB872\fP of file \fBform_engine\&.c\fP\&.
.nf
872                                                              {
873     int cmd_key;
874 
875     ssnprintf(em0, MAXLEN \- 1, "%s: %s", __FILE__, em);
876     ssnprintf(em1, MAXLEN \- 1, "Desc file: %s, line: %d", form\->mapp_spec,
877               in_line_num);
878     strnz__cpy(em2, in_buf, MAXLEN \- 1);
879     cmd_key = display_error(em0, em1, em2, nullptr);
880     return cmd_key;
881 }
.PP
.fi

.PP
References \fBcmd_key\fP, \fBdisplay_error()\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBform\fP, \fBMAXLEN\fP, \fBssnprintf()\fP, and \fBstrnz__cpy()\fP\&.
.PP
Referenced by \fBform_parse_desc()\fP\&.
.SS "void form_display_chyron (Form * form)"

.PP
Display the chyron (status line) at the bottom of the form window, showing available commands and their corresponding function keys\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBform\fP\fP A pointer to the Form structure containing form data and state\&. 
.RE
.PP

.PP
Definition at line \fB509\fP of file \fBform_engine\&.c\fP\&.
.nf
509                                      {
510     compile_chyron(form\->chyron);
511     wattron(form\->win, WA_REVERSE);
512     mvwaddstr(form\->win, form\->lines \- 1, 0, form\->chyron\->s);
513     wattroff(form\->win, WA_REVERSE);
514     wclrtoeol(form\->win);
515     wmove(form\->win, form\->lines \- 1, form\->chyron\->l);
516 }
.PP
.fi

.PP
References \fBcompile_chyron()\fP, and \fBform\fP\&.
.PP
Referenced by \fBform_accept_field()\fP, \fBform_calculate()\fP, \fBform_display_fields()\fP, and \fBform_end_fields()\fP\&.
.SS "void form_display_fields (Form * form)"

.PP
Display form fields on the screen, populating field values and formatting them according to the form configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBform\fP\fP A pointer to the Form structure containing form data and state\&. 
.RE
.PP
\fBNote\fP
.RS 4
This function iterates through the defined form fields, formats their display values based on the specified fill character and field length, and renders them on the form window\&. It also updates the chyron with available commands for user interaction\&. 
.RE
.PP

.PP
Definition at line \fB484\fP of file \fBform_engine\&.c\fP\&.
.nf
484                                      {
485     int n;
486     char fill_char = form\->fill_char[0];
487     for (n = 0; n < form\->fcnt; n++) {
488         if (form\->field[n]\->col + form\->field[n]\->len + 2 > form\->cols)
489             form\->field[n]\->len = form\->cols \- (form\->field[n]\->col + 2);
490         strnfill(form\->field[n]\->filler_s, fill_char, form\->field[n]\->len);
491         strnz(form\->field[n]\->display_s, form\->field[n]\->len);
492         form_display_field_n(form, n);
493 #ifdef DEBUG
494         wrefresh(form\->win);
495 #endif
496     }
497     form\->chyron = new_chyron();
498     set_chyron_key(form\->chyron, 1, "F1 Help", KEY_F(1));
499     set_chyron_key(form\->chyron, 9, "F9 Cancel", KEY_F(9));
500     set_chyron_key(form\->chyron, 10, "F10 Continue", KEY_F(10));
501     compile_chyron(form\->chyron);
502     form_display_chyron(form);
503     return;
504 }
.PP
.fi

.PP
References \fBcompile_chyron()\fP, \fBform\fP, \fBform_display_chyron()\fP, \fBform_display_field_n()\fP, \fBnew_chyron()\fP, \fBset_chyron_key()\fP, \fBstrnfill()\fP, and \fBstrnz()\fP\&.
.PP
Referenced by \fBform_calculate()\fP, and \fBform_display_screen()\fP\&.
.SS "unsigned int form_display_screen (Init * init)"

.PP
Display the form on the screen, including text elements and fields, and set up the form window based on the form configuration\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP A pointer to the Init structure containing form data and state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, or a non-zero value if an error occurs while creating the form window or rendering the form elements\&. 
.RE
.PP

.PP
Definition at line \fB434\fP of file \fBform_engine\&.c\fP\&.
.nf
434                                              {
435     int n;
436     char tmp_str[MAXLEN];
437 
438     form = init\->form;
439     form\->lines = 0;
440     for (n = 0; n < form\->dcnt; n++)
441         if (form\->text[n]\->line > form\->lines)
442             form\->lines = form\->text[n]\->line;
443     for (n = 0; n < form\->fcnt; n++)
444         if (form\->field[n]\->line > form\->lines)
445             form\->lines = form\->field[n]\->line;
446     form\->lines += 3;
447     if (form\->lines > (LINES \- form\->begy))
448         form\->lines = LINES \- form\->begy;
449     for (n = 0; n < form\->fcnt; n++) {
450         if (form\->field[n]\->line >= (form\->lines \- 2))
451             form\->fcnt = n;
452     }
453     form\->cols += 2;
454     if (form\->cols > (COLS \- form\->begx \- 3))
455         form\->cols = COLS \- form\->begx \- 3;
456     if (win_new(form\->lines, form\->cols, form\->begy, form\->begx, form\->title,
457                 0)) {
458         strnz__cpy(tmp_str, "kwin_new failed: ", MAXLEN \- 1);
459         strnz__cat(tmp_str, form\->title, MAXLEN \- 1);
460         Perror(tmp_str);
461         return (1);
462     }
463     // immedok(form\->win, TRUE);
464     form\->win = win_win[win_ptr];
465     form\->box = win_box[win_ptr];
466     for (n = 0; n < form\->dcnt; n++) {
467         strnz(form\->text[n]\->str, form\->cols \- 3);
468         mvwaddstr(form\->win, form\->text[n]\->line, form\->text[n]\->col,
469                   form\->text[n]\->str);
470 #ifdef DEBUG
471         wrefresh(form\->win);
472 #endif
473     }
474     form_display_fields(form);
475     return 0;
476 }
.PP
.fi

.PP
References \fBform\fP, \fBform_display_fields()\fP, \fBinit\fP, \fBMAXLEN\fP, \fBPerror()\fP, \fBstrnz()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, \fBwin_box\fP, \fBwin_new()\fP, \fBwin_ptr\fP, and \fBwin_win\fP\&.
.PP
Referenced by \fBform_engine()\fP\&.
.SS "int form_end_fields (Init * init)"

.PP
Handle post-processing after field entry, allowing user to edit data, execute a provider command, or write data to an output file\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP A pointer to the Init structure containing form data and state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An integer status code indicating the next action for the form processing loop (e\&.g\&., P_CONTINUE, P_CANCEL, P_ACCEPT, P_HELP)\&. 
.RE
.PP

.PP
Definition at line \fB180\fP of file \fBform_engine\&.c\fP\&.
.nf
180                                 {
181     bool loop = true;
182     int c, rc;
183     click_y = click_x = \-1;
184     form = init\->form;
185     wmove(form\->win, form\->lines \- 1, 0);
186     wclrtoeol(form\->win);
187     unset_chyron_key(form\->chyron, 18);
188     set_chyron_key(form\->chyron, 8, "F8 Edit", KEY_F(8));
189     set_chyron_key(form\->chyron, 10, "F10 Commit", KEY_F(10));
190     rc = \-1;
191     while (loop) {
192         if (rc == \-1) {
193             form_display_chyron(form);
194             tcflush(2, TCIFLUSH);
195             c = xwgetch(form\->win, form\->chyron);
196         }
197         switch (c) {
198         case KEY_F(1):
199             return P_HELP;
200         case KEY_F(8):
201             if (is_set_chyron_key(form\->chyron, 8)) {
202                 loop = false;
203                 rc = P_CONTINUE;
204                 break;
205             }
206             continue;
207         case KEY_F(9):
208             loop = false;
209             rc = P_CANCEL;
210             break;
211         case KEY_F(10):
212             loop = false;
213             rc = P_ACCEPT;
214             break;
215         case KEY_MOUSE:
216             continue;
217         default:
218             break;
219         }
220     }
221     unset_chyron_key(form\->chyron, 8);
222     form_display_chyron(form);
223     return rc;
224 }
.PP
.fi

.PP
References \fBclick_x\fP, \fBclick_y\fP, \fBform\fP, \fBform_display_chyron()\fP, \fBinit\fP, \fBis_set_chyron_key()\fP, \fBset_chyron_key()\fP, \fBunset_chyron_key()\fP, and \fBxwgetch()\fP\&.
.PP
Referenced by \fBform_engine()\fP\&.
.SS "int form_engine (Init * init)"

.PP
Form main processing loop\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP A pointer to the Init structure containing form data and state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 on successful completion, or a non-zero value if the user cancels the form or if an error occurs during processing\&.
.IP "1." 4
Parse the form description file to populate the form data structure\&.
.IP "2." 4
Read any initial data for the form fields from a specified input source\&.
.IP "3." 4
Display the form on the screen with the initial field values\&.
.IP "4." 4
Enter a loop to handle user input for field entry, calculation, help, and cancellation: a\&. If the user selects the accept action, perform any necessary calculations or post-processing, and then either return to field entry or exit the loop if the form is accepted\&. b\&. If the user selects the help action, display the help screen and return to the form after the user exits the help screen\&. c\&. If the user selects the cancel action, exit the loop and return a cancel status\&. 
.PP
.RE
.PP

.PP
Definition at line \fB106\fP of file \fBform_engine\&.c\fP\&.
.nf
106                             {
107     char tmp_str[MAXLEN];
108     int form_action;
109 
110     form = init\->form;
111     if (form == nullptr) {
112         Perror("FORM: form data structure is nullptr");
113     }
114     if (form_parse_desc(form)) {
115         destroy_form(init);
116         return 0;
117     }
118     form_read_data(form);
119     form_display_screen(init);
120     form\->fidx = 0;
121     form_action = 0;
122     while (1) {
123         if (form_action == 0 || form_action == P_CONTINUE)
124             form_action = form_enter_fields(form);
125         switch (form_action) {
126         case P_ACCEPT:
127             if (form\->f_calculate)
128                 form_action = form_calculate(init);
129             else
130                 form_action = form_end_fields(init);
131             if (form_action == P_HELP || form_action == P_CANCEL ||
132                 form_action == P_CONTINUE || form_action == P_END)
133                 continue;
134             if (form_action == P_ACCEPT) {
135                 form_action = P_END;
136                 continue;
137             }
138             break;
139         case P_END:
140             if (form\->f_out_spec || form\->out_spec[0] != '\\0')
141                 form_write(form);
142             if (form\->f_receiver_cmd) {
143                 form_exec_cmd(form);
144                 form_action = P_CONTINUE;
145                 continue;
146             }
147             return 0;
148         case P_HELP:
149             eargv[0] = strdup("mview");
150             strnz__cpy(tmp_str, "~/menuapp/help/form\&.help", MAXLEN \- 1);
151             expand_tilde(tmp_str, MAXLEN \- 1);
152             eargv[1] = strdup(tmp_str);
153             eargv[2] = nullptr;
154             eargc = 2;
155             zero_opt_args(init);
156             parse_opt_args(init, eargc, eargv);
157             init\->lines = 30;
158             init\->cols = 60;
159             init\->begy = menu\->begy + 1;
160             init\->begx = menu\->begx + 4;
161             strnz__cpy(init\->title, "Form Help", MAXLEN \- 1);
162             mview(init, eargc, eargv);
163             restore_wins();
164             form_action = P_CONTINUE;
165             break;
166         case P_CANCEL:
167             return P_CANCEL;
168         default:
169             form_action = P_CONTINUE;
170             break;
171         }
172     }
173     return 0;
174 }
.PP
.fi

.PP
References \fBdestroy_form()\fP, \fBeargc\fP, \fBeargv\fP, \fBexpand_tilde()\fP, \fBform\fP, \fBform_calculate()\fP, \fBform_display_screen()\fP, \fBform_end_fields()\fP, \fBform_enter_fields()\fP, \fBform_exec_cmd()\fP, \fBform_parse_desc()\fP, \fBform_read_data()\fP, \fBform_write()\fP, \fBinit\fP, \fBMAXLEN\fP, \fBmenu\fP, \fBmview()\fP, \fBparse_opt_args()\fP, \fBPerror()\fP, \fBrestore_wins()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBzero_opt_args()\fP\&.
.PP
Referenced by \fBinit_form()\fP\&.
.SS "int form_enter_fields (Form * form)"

.PP
Handle user input for field entry, allowing navigation between fields and looping until an exit action is selected\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBform\fP\fP A pointer to the Form structure containing form data and state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
An integer status code indicating the next action for the form processing loop (e\&.g\&., P_ACCEPT, P_HELP, P_CALC, P_CANCEL)\&. 
.RE
.PP
\fBNote\fP
.RS 4
This function manages user input for field entry, including navigation between fields and handling of special keys for accepting, canceling, requesting help, or performing calculations\&. The function loops until the user selects an exit action (e\&.g\&., accept or cancel)\&. 
.RE
.PP

.PP
Definition at line \fB369\fP of file \fBform_engine\&.c\fP\&.
.nf
369                                   {
370 
371     if (form\->fidx < 0)
372         return (\-1);
373     while (1) {
374         cmd_key = form_accept_field(form);
375         wrefresh(form\->win);
376 
377         switch (cmd_key) {
378 
379         case KEY_F(10):
380             return (P_ACCEPT);
381 
382         case KEY_F(1):
383             return (P_HELP);
384 
385         case KEY_F(5):
386             if (form\->f_calculate)
387                 return (P_CALC);
388             break;
389 
390         case KEY_F(9):
391             return (P_CANCEL);
392 
393         case KEY_UP:
394             if (form\->fidx != 0)
395                 form\->fidx\-\-;
396             break;
397 
398         case '\\r':
399         case KEY_ENTER:
400             if (form\->fidx < form\->fcnt \- 1)
401                 form\->fidx++;
402             else if (form\->fidx == form\->fcnt \- 1)
403                 return (P_ACCEPT);
404             break;
405 
406         case KEY_DOWN:
407             if (form\->fidx < form\->fcnt \- 1)
408                 form\->fidx++;
409             else if (form\->fidx == form\->fcnt \- 1)
410                 return (P_ACCEPT);
411             break;
412         case KEY_MOUSE:
413             break;
414         default:
415             break;
416         }
417     }
418 }
.PP
.fi

.PP
References \fBcmd_key\fP, \fBform\fP, and \fBform_accept_field()\fP\&.
.PP
Referenced by \fBform_engine()\fP\&.
.SS "int form_exec_cmd (Form * form)"

.PP
Execute a provider command specified in the form description file, passing form field values as arguments, and optionally redirecting output to a file\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBform\fP\fP A pointer to the Form structure containing form data and state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, or a non-zero value if an error occurs while constructing or executing the command\&. 
.RE
.PP

.PP
Definition at line \fB790\fP of file \fBform_engine\&.c\fP\&.
.nf
790                               {
791     char earg_str[MAXLEN + 1];
792     int i;
793     strnz__cpy(earg_str, form\->receiver_cmd, MAXLEN \- 1);
794     for (i = 0; i < form\->fcnt; i++) {
795         strnz__cat(earg_str, " ", MAXLEN \- 1);
796         strnz__cat(earg_str, form\->field[i]\->accept_s, MAXLEN \- 1);
797     }
798     if (form\->f_out_spec && form\->f_calculate) {
799         strnz__cat(earg_str, " >", MAXLEN \- 1);
800         strnz__cat(earg_str, form\->out_spec, MAXLEN \- 1);
801     }
802     shell(earg_str);
803     return 0;
804 }
.PP
.fi

.PP
References \fBearg_str\fP, \fBform\fP, \fBMAXLEN\fP, \fBshell()\fP, \fBstrnz__cat()\fP, and \fBstrnz__cpy()\fP\&.
.PP
Referenced by \fBform_engine()\fP\&.
.SS "int form_parse_desc (Form * form)"

.PP
Parse the form description file to populate the Form data structure with field definitions, text elements, and other configuration specified in the description file\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBform\fP\fP A pointer to the Form structure containing form data and state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, or a non-zero value if an error occurs while parsing the description file (e\&.g\&., file not found, invalid format, missing directives)\&. 
.RE
.PP

.PP
Definition at line \fB524\fP of file \fBform_engine\&.c\fP\&.
.nf
524                                 {
525     FILE *form_desc_fp;
526     char *token;
527     char *s;
528     int cols = 0;
529     int i, l;
530     int in_line_num = 0;
531     char in_buf[BUFSIZ];
532     char tmp_buf[BUFSIZ];
533     char *tmp_buf_p;
534     char tmp_str[BUFSIZ];
535     char delim[5];
536     char directive;
537 
538     form_desc_fp = fopen(form\->mapp_spec, "r");
539     if (form_desc_fp == nullptr) {
540         ssnprintf(em0, MAXLEN \- 1, "%s, line: %d", __FILE__, __LINE__ \- 2);
541         strnz__cpy(em1, "fopen ", MAXLEN \- 1);
542         strnz__cat(em1, form\->mapp_spec, MAXLEN \- 1);
543         strerror_r(errno, em2, MAXLEN);
544         display_error(em0, em1, em2, nullptr);
545         return (1);
546     }
547     for (i = 0; i < MAXFIELDS; i++) {
548         form\->field[i] = (Field *)calloc(1, sizeof(Field));
549         if (!form\->field[i]) {
550             sprintf(tmp_str, "FORM: calloc failed for fields");
551             abend(EXIT_FAILURE, tmp_str);
552         }
553     }
554     for (i = 0; i < MAXFIELDS; i++) {
555         form\->text[i] = (Text *)calloc(1, sizeof(Text));
556         if (!form\->field[i]) {
557             sprintf(tmp_str, "FORM: calloc failed for text");
558             abend(EXIT_FAILURE, tmp_str);
559         }
560     }
561     form\->didx = 0;
562     form\->fidx = 0;
563     form\->fcnt = 0;
564     form\->cols = 34;
565     while ((fgets(in_buf, MAXLEN, form_desc_fp)) != nullptr) {
566         s = in_buf;
567         in_line_num++;
568         l = trim(in_buf);
569         if (l == 0)
570             continue;
571         if (*s == D_COMMENT)
572             continue;
573         delim[0] = '\\n';
574         delim[1] = in_buf[1];
575         delim[2] = '\\0';
576         strnz__cpy(tmp_buf, in_buf, MAXLEN \- 1);
577         tmp_buf_p = tmp_buf;
578         if (!(token = strtok(tmp_buf_p, delim))) {
579             continue;
580         }
581         directive = *token;
582         switch ((int)directive) {
583         case D_COMMENT:
584             break;
585         case D_CALC:
586             form\->f_calculate = true;
587             break;
588         case D_QUERY:
589             form\->f_query = true;
590             break;
591         case D_CMD:
592             if (!(token = strtok(nullptr, delim))) {
593                 form_desc_error(in_line_num, in_buf,
594                                 "FORM: receiver_cmd delimiter");
595                 continue;
596             }
597             strnz__cpy(form\->receiver_cmd, token, MAXLEN \- 1);
598             break;
599         case D_HELP:
600             if (!(token = strtok(nullptr, delim))) {
601                 form_desc_error(in_line_num, in_buf,
602                                 "FORM: help_spec delimiter");
603             }
604             strnz__cpy(form\->help_spec, token, MAXLEN \- 1);
605             break;
606         case D_FIELD:
607             if (form\->field[form\->fidx] == nullptr) {
608                 sprintf(tmp_str, "FORM: calloc failed for fields");
609                 abend(EXIT_FAILURE, tmp_str);
610             }
611             if (!(token = strtok(nullptr, delim))) {
612                 form_desc_error(in_line_num, in_buf,
613                                 "FORM: line number delimiter");
614                 return 1;
615             }
616             form\->field[form\->fidx]\->line = atoi(token);
617             if (form\->field[form\->fidx]\->line < 0 ||
618                 form\->field[form\->fidx]\->line >= MAXFIELDS) {
619                 form_desc_error(in_line_num, in_buf,
620                                 "FORM: invalid line number");
621                 return 1;
622             }
623             if (!(token = strtok(nullptr, delim))) {
624                 form_desc_error(in_line_num, in_buf,
625                                 "FORM: column number delimiter");
626                 return 1;
627             }
628             form\->field[form\->fidx]\->col = atoi(token);
629             if (form\->field[form\->fidx]\->col < 0 ||
630                 form\->field[form\->fidx]\->col >= TBL_COLS) {
631                 form_desc_error(in_line_num, in_buf,
632                                 "FORM: invalid column number");
633                 break;
634             }
635             if (!(token = strtok(nullptr, delim))) {
636                 strnz__cpy(tmp_str, in_buf, MAXLEN \- 1);
637                 form_desc_error(in_line_num, tmp_str, "FORM: length delimiter");
638                 break;
639             }
640             form\->field[form\->fidx]\->len = atoi(token);
641             if (form\->field[form\->fidx]\->len < 0 ||
642                 form\->field[form\->fidx]\->len > TBL_COLS) {
643                 form_desc_error(in_line_num, in_buf, "FORM: invalid length");
644                 break;
645             }
646             if (!(token = strtok(nullptr, delim))) {
647                 form_desc_error(in_line_num, in_buf,
648                                 "FORM: validation code delimiter");
649                 break;
650             }
651             form\->field[form\->fidx]\->ff = \-1;
652             for (i = 0; i < FF_INVALID; i++) {
653                 str_to_lower(token);
654                 str_to_lower(ff_tbl[i]);
655                 if (!strcmp(token, ff_tbl[i])) {
656                     form\->field[form\->fidx]\->ff = i;
657                     break;
658                 }
659             }
660             if (form\->field[form\->fidx]\->ff < 0 ||
661                 form\->field[form\->fidx]\->ff >= FF_INVALID) {
662                 form_desc_error(in_line_num, in_buf,
663                                 "FORM: invalid format code");
664                 break;
665             }
666             cols =
667                 form\->field[form\->fidx]\->col + form\->field[form\->fidx]\->len + 1;
668             if (cols > form\->cols)
669                 form\->cols = cols;
670             form\->fidx++;
671             form\->fcnt = form\->fidx;
672             break;
673         case D_TEXT:
674             if (form\->text[form\->didx] == nullptr) {
675                 sprintf(tmp_str, "FORM: calloc failed for text");
676                 abend(EXIT_FAILURE, tmp_str);
677             }
678             if (!(token = strtok(nullptr, delim))) {
679                 form_desc_error(in_line_num, in_buf,
680                                 "FORM: line number delimiter");
681                 break;
682             }
683             form\->text[form\->didx]\->line = atoi(token);
684             if (form\->text[form\->didx]\->line < 0 ||
685                 form\->text[form\->didx]\->line >= MAXFIELDS) {
686                 form_desc_error(in_line_num, in_buf,
687                                 "FORM: invalid line number");
688                 break;
689             }
690             if (!(token = strtok(nullptr, delim))) {
691                 form_desc_error(in_line_num, in_buf,
692                                 "FORM: column number delimiter");
693                 break;
694             }
695             form\->text[form\->didx]\->col = atoi(token);
696             if (form\->text[form\->didx]\->col < 0 ||
697                 form\->text[form\->didx]\->col >= TBL_COLS) {
698                 form_desc_error(in_line_num, in_buf,
699                                 "FORM: invalid column number");
700                 break;
701             }
702             if (!(token = strtok(nullptr, delim))) {
703                 form_desc_error(in_line_num, in_buf, "FORM: text delimiter");
704                 break;
705             }
706             strnz__cpy(form\->text[form\->didx]\->str, token, MAXLEN \- 1);
707             form\->text[form\->didx]\->len = strlen(form\->text[form\->didx]\->str);
708             if (form\->text[form\->didx]\->len < 0 ||
709                 form\->text[form\->didx]\->len > TBL_COLS) {
710                 form_desc_error(in_line_num, in_buf, "FORM: invalid length");
711                 break;
712             }
713             cols =
714                 form\->text[form\->didx]\->col + form\->text[form\->didx]\->len + 1;
715             if (cols > form\->cols)
716                 form\->cols = cols;
717             form\->didx++;
718             form\->dcnt = form\->didx;
719             break;
720         case D_HEADER:
721             if ((token = strtok(nullptr, delim))) {
722                 strnz__cpy(form\->title, token, MAXLEN \- 1);
723             }
724             break;
725         default:
726             form_desc_error(in_line_num, in_buf, "invalid directive");
727             break;
728         }
729     }
730     fclose(form_desc_fp);
731     if (form\->didx < 1 && form\->fidx < 1) {
732         ssnprintf(em0, MAXLEN \- 1, "%s, line: %d", __FILE__, __LINE__);
733         ssnprintf(em1, MAXLEN \- 1, "%s", "Error in description file:");
734         ssnprintf(em2, MAXLEN \- 1, "%s", form\->mapp_spec);
735         display_error(em0, em1, em2, nullptr);
736         return (1);
737     }
738     return (0);
739 }
.PP
.fi

.PP
References \fBabend()\fP, \fBD_CALC\fP, \fBD_CMD\fP, \fBD_COMMENT\fP, \fBD_FIELD\fP, \fBD_HEADER\fP, \fBD_HELP\fP, \fBD_QUERY\fP, \fBD_TEXT\fP, \fBdisplay_error()\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBff_tbl\fP, \fBform\fP, \fBform_desc_error()\fP, \fBMAXLEN\fP, \fBssnprintf()\fP, \fBstr_to_lower()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBtrim()\fP\&.
.PP
Referenced by \fBform_engine()\fP\&.
.SS "int form_read_data (Form * form)"

.PP
Read initial data for form fields from a specified input source, such as a file or standard input, and populate the form fields with the data\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBform\fP\fP A pointer to the Form structure containing form data and state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, or a non-zero value if an error occurs while reading the data or if the specified input source is invalid or empty\&. 
.RE
.PP

.PP
Definition at line \fB745\fP of file \fBform_engine\&.c\fP\&.
.nf
745                                {
746     struct stat sb;
747     char in_buf[MAXLEN];
748     char field[MAXLEN];
749 
750     if (!form\->f_in_pipe) {
751         if (form\->f_in_spec && form\->in_spec[0] != '\\0') {
752             if ((lstat(form\->in_spec, &sb) == \-1) || (sb\&.st_size == 0) ||
753                 ((form\->in_fp = fopen(form\->in_spec, "rb")) == nullptr)) {
754                 strnz__cat(em0, form\->in_spec, MAXLEN \- 1);
755                 // if (errno)
756                 // strerror_r(errno, em1, MAXLEN \- 1);
757                 // else
758                 if (sb\&.st_size == 0)
759                     strnz__cpy(em1, "File is empty", MAXLEN \- 1);
760                 else
761                     strnz__cpy(em1, "File does not exist", MAXLEN \- 1);
762                 strnz__cpy(em2, "Fields will be blank or zero", MAXLEN \- 1);
763                 cmd_key = display_error(em0, em1, em2, nullptr);
764                 if (cmd_key == KEY_F(9))
765                     return (1);
766             }
767             if (form\->in_fp == nullptr)
768                 return (1);
769         } else
770             return (0);
771     }
772     form\->fidx = 0;
773     if (form\->in_fp != nullptr) {
774         while ((fgets(in_buf, MAXLEN, form\->in_fp)) != nullptr) {
775             if (form\->fidx < MAXFIELDS)
776                 strnz__cpy(field, in_buf, MAXLEN \- 1);
777             form_fmt_field(form, field);
778             form\->fidx++;
779         }
780         fclose(form\->in_fp);
781     }
782     return (0);
783 }
.PP
.fi

.PP
References \fBcmd_key\fP, \fBdisplay_error()\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBform\fP, \fBform_fmt_field()\fP, \fBMAXLEN\fP, \fBstrnz__cat()\fP, and \fBstrnz__cpy()\fP\&.
.PP
Referenced by \fBform_calculate()\fP, and \fBform_engine()\fP\&.
.SS "void form_usage ()"

.PP
Display usage information for the form, including available options and commands, to assist users in understanding how to interact with the form\&. 
.PP
\fBNote\fP
.RS 4
This function generates a usage message based on the options defined for the form and displays it to the user, typically when they request help or when an error occurs\&. The usage information includes details about the form's configuration, available commands, and how to navigate and interact with the form fields\&. 
.RE
.PP

.PP
Definition at line \fB858\fP of file \fBform_engine\&.c\fP\&.
.nf
858                   {
859     dump_opts_by_use("Form: usage: ", "\&.\&.f\&.");
860     (void)fprintf(stderr, "\\n");
861     Perror("press any key to continue");
862 }
.PP
.fi

.PP
References \fBdump_opts_by_use()\fP, and \fBPerror()\fP\&.
.SS "int form_write (Form * form)"

.PP
Write form field values to a specified output destination, such as a file or standard output, based on the form configuration and user input\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBform\fP\fP A pointer to the Form structure containing form data and state\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, or a non-zero value if an error occurs while writing the data or if the specified output destination is invalid\&. 
.RE
.PP

.PP
Definition at line \fB810\fP of file \fBform_engine\&.c\fP\&.
.nf
810                            {
811     int n;
812     if (form\->out_spec[0] == '\\0' || strcmp(form\->out_spec, "\-") == 0 ||
813         strcmp(form\->out_spec, "/dev/stdout") == 0) {
814         strnz__cpy(form\->out_spec, "/dev/stdout", MAXLEN \- 1);
815         close(form\->out_fd);
816         form\->out_fd = open(form\->out_spec, O_CREAT | O_RDWR | O_TRUNC, 0644);
817         if (form\->out_fd == \-1) {
818             ssnprintf(em0, MAXLEN \- 1, "%s, line: %d", __FILE__, __LINE__ \- 1);
819             strnz__cpy(em1, "open ", MAXLEN \- 1);
820             strnz__cat(em1, form\->out_spec, MAXLEN \- 1);
821             strerror_r(errno, em2, MAXLEN);
822             display_error(em0, em1, em2, nullptr);
823             return (1);
824         }
825         dup2(form\->out_fd, STDOUT_FILENO);
826         form\->out_fp = fdopen(STDOUT_FILENO, "w");
827         form\->f_out_spec = true;
828         form\->f_out_pipe = true;
829     } else {
830         if ((form\->out_fp = fopen(form\->out_spec, "w")) == nullptr) {
831             ssnprintf(em0, MAXLEN \- 1, "%s, line: %d", __FILE__, __LINE__ \- 1);
832             strerror_r(errno, em2, MAXLEN);
833             display_error(em0, em1, em2, nullptr);
834             return (1);
835         }
836     }
837     if (form\->out_fp == nullptr) {
838         ssnprintf(em0, MAXLEN \- 1, "%s, line: %d", __FILE__, __LINE__ \- 1);
839         strnz__cpy(em1, "fopen ", MAXLEN \- 1);
840         strnz__cat(em1, form\->out_spec, MAXLEN \- 1);
841         strerror_r(errno, em2, MAXLEN);
842         display_error(em0, em1, em2, nullptr);
843         return (1);
844     }
845     for (n = 0; n < form\->fcnt; n++)
846         fprintf(form\->out_fp, "%s\\n", form\->field[n]\->accept_s);
847     if (form\->out_fp != nullptr)
848         fclose(form\->out_fp);
849     return (0);
850 }
.PP
.fi

.PP
References \fBdisplay_error()\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBform\fP, \fBMAXLEN\fP, \fBssnprintf()\fP, \fBstrnz__cat()\fP, and \fBstrnz__cpy()\fP\&.
.PP
Referenced by \fBform_calculate()\fP, and \fBform_engine()\fP\&.
.SS "int form_yx_to_fidx (Form * form, int y, int x)"

.PP
Definition at line \fB419\fP of file \fBform_engine\&.c\fP\&.
.nf
419                                               {
420     for (int i = 0; i < form\->fcnt; i++) {
421         if (y == form\->field[i]\->line && x >= form\->field[i]\->col &&
422             x < form\->field[i]\->col + form\->field[i]\->len) {
423             return i;
424         }
425     }
426     return \-1; // No field found at the given coordinates
427 }
.PP
.fi

.PP
References \fBform\fP\&.
.PP
Referenced by \fBform_accept_field()\fP\&.
.SS "int init_form (Init * init, int argc, char ** argv, int begy, int begx)"

.PP
Initialize form data structure and parse description file\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP A pointer to the Init structure containing form data and state\&. 
.br
\fIargc\fP The number of command line arguments passed to the form\&. 
.br
\fIargv\fP The array of command line arguments passed to the form\&. 
.br
\fIbegy\fP The y-coordinate for the top-left corner of the form window\&. 
.br
\fIbegx\fP The x-coordinate for the top-left corner of the form window\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, or a non-zero value if an error occurs during 
.RE
.PP

.PP
Definition at line \fB53\fP of file \fBform_engine\&.c\fP\&.
.nf
53                                                                      {
54     int rc;
55     char tmp_str[MAXLEN];
56     if (init\->form != nullptr)
57         destroy_form(init);
58     init\->form = new_form(init, argc, argv, begy, begx);
59     form = init\->form;
60     if (!form\->f_mapp_spec) {
61         if (form\->mapp_spec[0] == '\\0') {
62             rc = Perror("Error: No form specification file given");
63         } else {
64             strnz__cpy(tmp_str, "form\->mapp_spec: ", MAXLEN \- 1);
65             strnz__cat(tmp_str, form\->mapp_spec, MAXLEN \- 1);
66             strnz__cat(tmp_str, " not found", MAXLEN \- 1);
67             rc = Perror(tmp_str);
68         }
69         return rc;
70     }
71     if (begy != 0)
72         form\->begy = begy;
73     if (begx != 0)
74         form\->begx = begx;
75     if ((form\->f_in_spec && (form\->in_spec[0] == '\\0')) ||
76         (strcmp(form\->in_spec, "\-") == 0) ||
77         strcmp(form\->in_spec, "/dev/stdin") == 0) {
78         strnz__cpy(form\->in_spec, "/dev/stdin", MAXLEN \- 1);
79         form\->f_in_pipe = true;
80     }
81     if (form\->title[0] == '\\0')
82         strnz__cpy(form\->title, form\->in_spec, MAXLEN \- 1);
83     rc = form_engine(init);
84     if (form\->win)
85         win_del();
86     destroy_form(init);
87     return rc;
88 }
.PP
.fi

.PP
References \fBdestroy_form()\fP, \fBform\fP, \fBform_engine()\fP, \fBinit\fP, \fBMAXLEN\fP, \fBnew_form()\fP, \fBPerror()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBwin_del()\fP\&.
.PP
Referenced by \fBenter_file_spec()\fP, \fBmain()\fP, and \fBmenu_cmd_processor()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
