.TH "src/lf.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lf.c \- list files matching a regular expression  

.SH SYNOPSIS
.br
.PP
\fR#include <cm\&.h>\fP
.br
\fR#include <dirent\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <grp\&.h>\fP
.br
\fR#include <pwd\&.h>\fP
.br
\fR#include <regex\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <sys/stat\&.h>\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "List files in a directory matching a regular expression\&. "
.in -1c
.SH "Detailed Description"
.PP 
list files matching a regular expression 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBlf\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
List files in a directory matching a regular expression\&. 
.PP
.nf
lf [options ad:e:hit:v] [dir] [re]
     \-a        List hidden files
     \-d        maximum max_depth of subdirectories to examine
     \-e        exclude files matching the regular expression
     \-h        show this help message
     \-i        ignore case in search
     \-t d      list directories (exclude files)
     \-t f      list files (exclude directories)
     \-v        show version information
    dir Directory to search
    re  Regular expression to match

.fi
.PP
 
.PP
Definition at line \fB38\fP of file \fBlf\&.c\fP\&.
.nf
38                                 {
39     char dir[MAXLEN];
40     char re[MAXLEN];
41     char ere[MAXLEN];
42     dir[0] = '\\0';
43     re[0] = '\\0';
44     ere[0] = '\\0';
45     bool f_help = false;
46     bool f_version = false;
47     int flags = 0;
48     int opt;
49     int max_depth = 3;
50 
51     while ((opt = getopt(argc, argv, "ad:e:hit:v")) != \-1) {
52         switch (opt) {
53         case 'a':
54             flags |= LF_ALL;
55             break;
56         case 'd':
57             max_depth = atoi(optarg);
58             break;
59         case 'e':
60             strnz__cpy(ere, optarg, MAXLEN \- 1);
61             flags |= LF_EXCLUDE;
62             break;
63         case 'h':
64             f_help = true;
65             break;
66         case 'i':
67             flags |= LF_ICASE;
68             break;
69         case 't':
70             switch (optarg[0]) {
71             case 'd':
72                 flags |= LF_DIRS;
73                 break;
74             case 'f':
75                 flags |= LF_FILES;
76                 break;
77             default:
78                 break;
79             }
80             break;
81         case 'v':
82             f_version = true;
83             break;
84         default:
85             exit(EXIT_FAILURE);
86         }
87     }
88     if (f_help) {
89         printf("Usage: lf [options] [directory] [regexp]\\n");
90         printf("Options:\\n");
91         printf("  \-a        List hidden files\\n");
92         printf("  \-d        maximum depth of subdirectories to examine\\n");
93         printf("  \-e        exclude files matching the regular expression\\n");
94         printf("  \-h        show this help message\\n");
95         printf("  \-i        ignore case in search\\n");
96         printf("  \-t f      list files (exclude directories)\\n");
97         printf("  \-t d      list directories (exclude files)\\n");
98         printf("  \-v        show version information\\n");
99         exit(EXIT_SUCCESS);
100     }
101     if (f_version) {
102         printf("lf version 1\&.0\\n");
103         exit(EXIT_SUCCESS);
104     }
105     struct stat sb;
106     if (optind < argc) {
107         if (stat(argv[optind], &sb) == \-1 || (sb\&.st_mode & S_IFMT) != S_IFDIR) {
108             strnz__cpy(dir, "\&.", MAXLEN \- 1);
109         } else {
110             strnz__cpy(dir, argv[optind], MAXLEN \- 1);
111             optind++;
112         }
113     }
114     if (optind < argc) {
115         strnz__cpy(re, argv[optind], MAXLEN \- 1);
116         optind++;
117     }
118     if (re[0] == '\\0')
119         strnz__cpy(re, "\&.*", MAXLEN \- 1);
120     if (dir[0] == '\\0')
121         strnz__cpy(dir, "\&.", MAXLEN \- 1);
122     flags |= LF_REGEX;
123     lf_find(dir, re, ere, max_depth, flags);
124     return true;
125 }
.PP
.fi

.PP
References \fBf_help\fP, \fBf_version\fP, \fBlf_find()\fP, \fBMAXLEN\fP, and \fBstrnz__cpy()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
