.TH "md_CHANGELOG" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CHANGELOG \- Changelog 
.PP

.SH "[Released] - 2026-02-04"
.PP
0\&.2\&.9 - 2026-03-09

.PP
Much more work on chyron integration\&. Appears to be working as intended\&. In the process, I found and fixed a number of bugs in form and one in lf\&. The debugging process is somewhat tedious following disruptive feature additions, but we are making progress\&.

.PP
Still more work on inte

.PP
0\&.2\&.9 - 2026-03-08

.PP
Continuing to work on chyron integration into Form and Pick\&. When using the Installment Loan example, the chyron has been adjusted to only include relevant options, and the key handling has been reworked to accommodate the new structure\&. For example, when the user finishes entering all the fields in the form, the chyron provides only F1 Help, F5 Calculate, and F9 Cancel, which makes sense because the form is still in edit mode and the user can continue to edit fields by using movement keys or by clicking on the fields\&. Once the user clicks calculate, the chyron changes to include F1 Help, F4 Edit, F9 Cancel, and F10 Commit\&. Upon clicking F9 Commit (or pressing the F9 key), Form will execute the appropriate action specified by the user\&.

.PP
0\&.2\&.9 - 2026-03-07

.PP
Corrected Pick Page Down and Page Up key handling, which had been broken by the integration of the chyron facility into xwgetch\&. This was a major problem, and it caused the Pick module to be completely unusable\&. I have reimplemented the key handling, and it is now working as intended\&.

.PP
Modified Pick so that the chyron only includes Page Up and Page Down options when there is more than 1 page of Pick ojbects\&. This is part of a larger effort to integrate the chyron facility into all C-Menu programs\&. The chyron facility allows C-Menu to generate dynamic chyrons based on the current state of the program, while automatically keeping track of click zones so that xwgetch can interpret mouse clicks as key codes\&. The idea is that the chyron should only include relevant options\&.

.PP
0\&.2\&.9 - 2026-03-06

.PP
Added -e exclude regular expression to lf, which allows users to exclude files from the listing based on a regular expression\&. This is a powerful feature that can be used to filter out unwanted files from the listing\&.

.PP
Replaced mouse handling in Pick, Form, and Menu with xwgetch, which reads chyron mouse selections as key codes\&. Now all mouse events are handled through a single function\&. xwgetch also handles asynchronous signal events\&.

.PP
Some code in \fBmenu_engine\&.c\fP, which handled hierarchical menu navigation, had somehow been deleted\&. This was a major problem, and it caused the menu system to be completely broken\&. I have reimplemented it, and it is now working as intended\&.

.PP
The addition of an Exercises section will provide a test bed for debugging as well as a proof-of-concept for C-Menu\&. The first project is a suite of Workstation Configuration programs for SDDM, Ghostty, Kitty, and Alacritty\&. These have been integrated into the C-Menu example main menu\&. I will continue to add more exercises along with documentation\&. The exercises will be designed to be both educational and practical, and they will cover a wide range of topics related to C-Menu development\&. One of the next projects, if time allows, will be a C-Menu based general ledger using SQLite as the backend database\&.

.PP
0\&.2\&.9 - 2026-02-27

.PP
Added a number of improvements to CMake build to accommodate C-Menu's revised file structure\&. Both CMake and straight Makefile builds produce similar results, but CMake is more flexible, easier to work with, and less prone to difficult-to-solve problems\&.

.PP
View's search function has been reworked to fix a number of issues with buffer and page management, such as off-by-one page top and bottom positioning\&.

.PP
lf (list files) - recursive option has been replaced by a depth option and lf's core logic has been reworked to enhance reliability\&. Also removed mangled lf syntax which had been used in some scripts to compensate for deficiencies in lf's option handler\&.

.PP
Many documentation updates - API/ABI documentation is substantially complete\&. Function Call Graphs, Called Graphs, and forward and backward references added\&.

.PP
Every function is documented, and most variables\&. All documentation has been consolidated into a single html file available at:

.PP
\fRC-Menu Comprehensive Reference\fP

.PP
In View, replaced calls to mbtowc() with mbrtowc() because of spurious accent marks populating the complex characters structures (cchar_t)\&. Apparently, mbtowc() is broken\&. mbrtowc() is the new and improved replacement\&.

.PP
The ANSI SGR parser and gamma correction in View is working perfectly\&. Try a setting of 2\&.2 in ~/\&.minitrc to brighten up dull documents\&.

.PP
0\&.2\&.9 - 2026-02-09

.PP
Split the large menu\&.h into Separate \&.h files for each module, which should make it easier for developers who want to work on a particular feature\&.

.PP
Modified Makefile and CMakeLists\&.txt to reflect the new file structure, and to add the new shared library libcm\&.so

.PP
Many unimplemented functions have been implemented, and the project is now in a much more complete state\&. I am still working on the documentation, but I have made significant progress on it, and I will be uploading it to the repository as I go\&.

.PP
I will look into adding a website for the project, and I will be uploading the documentation to the repository as I go\&. I am also working on a website for the project, which will be up soon\&.

.PP
.PP

.PP
[0\&.2\&.8] - 2026-02-04

.PP
Makefile

.PP
menu - \fBmenu\&.c\fP \fBmenu_engine\&.c\fP \fBparse_menu_desc\&.c\fP

.PP
form - \fBform\&.c\fP

.PP
pick - \fBpick\&.c\fP

.PP
view - \fBview\&.c\fP

.PP
ckeys - \fBckeys\&.c\fP

.PP
enterchr - \fBenterchr\&.c\fP

.PP
enterstr - \fBenterstr\&.c\fP

.PP
optsp - \fBoptsp\&.c\fP

.PP
whence - \fBwhence\&.c\fP

.PP
stripansi - \fBstripansi\&.c\fP

.PP
iloan - \fBiloan\&.c\fP

.PP
lf - \fBlf\&.c\fP

.PP
add_executable(form \fBform\&.c\fP) target_sources(form PRIVATE $<TARGET_OBJECTS:cmenu>) target_link_libraries(form cm ${LIBS})

.PP
add_executable(enterchr \fBenterchr\&.c\fP) target_link_libraries(enterchr cm ${LIBS})

.PP
add_executable(enterstr \fBenterstr\&.c\fP) target_link_libraries(enterstr cm ${LIBS})

.PP
add_executable(iloan \fBiloan\&.c\fP) target_link_libraries(iloan cm ${LIBS})

.PP
add_executable(lf \fBlf\&.c\fP) target_link_libraries(lf cm ${LIBS})

.PP
add_executable(pick \fBpick\&.c\fP) target_sources(pick PRIVATE $<TARGET_OBJECTS:cmenu>) target_link_libraries(pick cm ${LIBS})

.PP
TARGETS menu form pick view ckeys enterchr enterstr lf optsp stripansi whence cm

.PP
\fBdwin\&.c\fP \fBfutil\&.c\fP \fBscriou\&.c\fP \fBexec\&.c\fP \fBsig\&.c\fP

.PP
COMMON_SRCS \fBcurskeys\&.c\fP \fBfields\&.c\fP \fBform_engine\&.c\fP \fBinit_view\&.c\fP \fBpick_engine\&.c\fP \fBview_engine\&.c\fP \fBinit\&.c\fP \fBmem\&.c\fP \fBmview\&.c\fP \fBopts\&.c\fP)

.PP
.IP "\(bu" 2
0\&.2\&.8 - 2026-02-03
.IP "\(bu" 2
0\&.2\&.9 - 2026-02-04
.PP
.SS "Fixed"
.IP "\(bu" 2
Prevent segmentation fault upon \fRclose()\fP ([#28](link-to-pr))
.PP
.SH "[0\&.2\&.8]- 2026-02-04"
.PP
.SS "Added"
.IP "\(bu" 2
Initial release of the project ([\fRa1b2c3d\fP](link-to-commit))
.PP

.PP
: https://github.com/BillWAller/C-Menu/releases/tag/C-Menu-0.2.8 : https://github.com/BillWaller/C-Menu/releases/tag/C-Menu-0.2.8 
