.TH "src/menu.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/menu.c \- Command line start-up for C-Menu\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <common\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB__end_pgm\fP"
.br
.RI "This is the main file for C-Menu, a terminal-based application launcher and menu system\&. "
.in -1c
.SH "Detailed Description"
.PP 
Command line start-up for C-Menu\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBmenu\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line \fB21\fP of file \fBmenu\&.c\fP\&.
.nf
21                                 {
22     __atexit;
23     capture_shell_tioctl();
24     Init *init = new_init(argc, argv);
25     SIO *sio = init\->sio;
26     mapp_initialization(init, argc, argv);
27     open_curses(sio);
28     sig_prog_mode();
29     capture_curses_tioctl();
30     win_init_attrs(sio\->fg_color, sio\->bg_color, sio\->bo_color);
31 
32     new_menu(init, init\->argc, init\->argv, LINES / 14, COLS / 14);
33     menu = init\->menu;
34     parse_menu_description(init);
35     menu_engine(init);
36 
37     destroy_init(init);
38     win_del();
39     destroy_curses();
40     return 0;
41 }
.PP
.fi

.PP
References \fBcapture_curses_tioctl()\fP, \fBcapture_shell_tioctl()\fP, \fBdestroy_curses()\fP, \fBdestroy_init()\fP, \fBinit\fP, \fBmapp_initialization()\fP, \fBmenu\fP, \fBmenu_engine()\fP, \fBnew_init()\fP, \fBnew_menu()\fP, \fBopen_curses()\fP, \fBparse_menu_description()\fP, \fBsig_prog_mode()\fP, \fBsio\fP, \fBwin_del()\fP, and \fBwin_init_attrs()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "__end_pgm"

.PP
This is the main file for C-Menu, a terminal-based application launcher and menu system\&. 
.PP
\fBNote\fP
.RS 4
It operates by reading a menu description file and displaying a navigable menu in the terminal\&. Users can select applications to launch or scripts to execute\&. 

.PP
Several ancillary files provide supporting functionality, including handling terminal initialization IO settings, managing the menu structure, and rendering the interface using the NCurses library\&. 
.RE
.PP

.PP
Definition at line \fB20\fP of file \fBmenu\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
