.TH "src/scriou.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/scriou.c \- Screen IO Support for MENU\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <cm\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <termios\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBcapture_shell_tioctl\fP ()"
.br
.RI "\fBcapture_shell_tioctl()\fP - capture shell terminal settings "
.ti -1c
.RI "bool \fBrestore_shell_tioctl\fP ()"
.br
.RI "\fBrestore_shell_tioctl()\fP - restore shell terminal settings "
.ti -1c
.RI "bool \fBcapture_curses_tioctl\fP ()"
.br
.RI "\fBcapture_curses_tioctl()\fP - capture curses terminal settings "
.ti -1c
.RI "bool \fBrestore_curses_tioctl\fP ()"
.br
.RI "\fBrestore_curses_tioctl()\fP - restore curses terminal settings "
.ti -1c
.RI "bool \fBset_sane_tioctl\fP (struct termios *t_p)"
.br
.RI "\fBset_sane_tioctl()\fP - set terminal to sane settings for C-MENU "
.ti -1c
.RI "bool \fBmk_raw_tioctl\fP (struct termios *t_p)"
.br
.RI "\fBmk_raw_tioctl()\fP - set terminal to raw mode "
.ti -1c
.RI "char \fBdi_getch\fP ()"
.br
.RI "sget single character from terminal in raw mode "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct termios \fBshell_tioctl\fP"
.br
.ti -1c
.RI "struct termios \fBcurses_tioctl\fP"
.br
.ti -1c
.RI "bool \fBf_have_shell_tioctl\fP = false"
.br
.ti -1c
.RI "bool \fBf_have_curses_tioctl\fP = false"
.br
.ti -1c
.RI "struct termios shell_in_tioctl \fBcurses_in_tioctl\fP"
.br
.ti -1c
.RI "struct termios shell_out_tioctl \fBcurses_out_tioctl\fP"
.br
.ti -1c
.RI "struct termios shell_err_tioctl \fBcurses_err_tioctl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Screen IO Support for MENU\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBscriou\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "bool capture_curses_tioctl ()"

.PP
\fBcapture_curses_tioctl()\fP - capture curses terminal settings 
.PP
\fBReturns\fP
.RS 4
- true on success 
.RE
.PP
\fBNote\fP
.RS 4
- captures terminal settings for stdin, stdout, and stderr 
.RE
.PP

.PP
Definition at line \fB60\fP of file \fBscriou\&.c\fP\&.
.nf
60                              {
61     if (f_have_curses_tioctl)
62         return true;
63     tcgetattr(0, &curses_tioctl);
64     f_have_curses_tioctl = true;
65     return true;
66 }
.PP
.fi

.PP
References \fBcurses_tioctl\fP, and \fBf_have_curses_tioctl\fP\&.
.PP
Referenced by \fBfork_exec()\fP, and \fBmain()\fP\&.
.SS "bool capture_shell_tioctl ()"

.PP
\fBcapture_shell_tioctl()\fP - capture shell terminal settings 
.PP
\fBReturns\fP
.RS 4
- true on success 
.RE
.PP
\fBNote\fP
.RS 4
- captures terminal settings for stdin, stdout, and stderr 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/enterchr\&.c\fP, and \fB/usr/local/src/cmenu/src/enterstr\&.c\fP\&.
.PP
Definition at line \fB40\fP of file \fBscriou\&.c\fP\&.
.nf
40                             {
41     if (f_have_shell_tioctl)
42         return true;
43     tcgetattr(0, &shell_tioctl);
44     tcgetattr(2, &shell_err_tioctl);
45     f_have_shell_tioctl = true;
46     return true;
47 }
.PP
.fi

.PP
References \fBf_have_shell_tioctl\fP, and \fBshell_tioctl\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "char di_getch ()"

.PP
sget single character from terminal in raw mode 
.PP
\fBReturns\fP
.RS 4
- the character read from terminal 
.RE
.PP
\fBNote\fP
.RS 4
restores terminal settings 
.RE
.PP

.PP
Definition at line \fB122\fP of file \fBscriou\&.c\fP\&.
.nf
122                 {
123     struct termios org_tioctl, new_tioctl;
124     char buf;
125 
126     if (tcgetattr(2, &org_tioctl) == \-1) {
127         fprintf(stderr, "\\ndi_getch: tcgetattr failed\\n");
128         return (0);
129     }
130     new_tioctl = org_tioctl;
131     new_tioctl\&.c_lflag &= ~(ECHO | ICANON);
132     new_tioctl\&.c_cc[VMIN] = 1;
133     new_tioctl\&.c_cc[VTIME] = 0;
134     tcsetattr(2, TCSAFLUSH, &new_tioctl);
135     read(2, &buf, 1);
136     tcsetattr(2, TCSAFLUSH, &org_tioctl);
137     return (buf);
138 }
.PP
.fi

.PP
Referenced by \fBnf_error()\fP, and \fBusage()\fP\&.
.SS "bool mk_raw_tioctl (struct termios * t_p)"

.PP
\fBmk_raw_tioctl()\fP - set terminal to raw mode 
.PP
\fBParameters\fP
.RS 4
\fIt_p\fP - pointer to termios structure to modify 
.RE
.PP
\fBReturns\fP
.RS 4
- true on success 
.RE
.PP
\fBNote\fP
.RS 4
- unlike cfmakeraw(), this leaves ISIG enabled\&. 

.PP
- cfmakeraw() disables ISIG, which prevents C-MENU from handling signals like Ctrl-C\&. Instead of using cfmakeraw(), we manually set the terminal to raw mode while leaving ISIG enabled\&. 

.PP
- the following code is equivalent to cfmakeraw() but with ISIG left enabled: 
.PP
.nf
t_p\->c_iflag &= ~(IGNBRK | BRKINT | PARMRK | INPCK | ISTRIP | INLCR |
               IGNCR | ICRNL | IXON | IXOFF);
t_p\->c_lflag &= ~(ECHO | ECHONL | ICANON | IEXTEN);
t_p\->c_cflag &= ~(CSIZE | PARENB);
t_p\->c_cflag |= CS8 | CLOCAL;

.fi
.PP
 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/enterchr\&.c\fP\&.
.PP
Definition at line \fB110\fP of file \fBscriou\&.c\fP\&.
.nf
110                                         {
111     tcgetattr(0, t_p);
112     t_p\->c_lflag |= ISIG;
113     t_p\->c_lflag &= ~(ECHO | ICANON);
114     t_p\->c_cc[VMIN] = 1;
115     t_p\->c_cc[VTIME] = 0;
116     tcsetattr(0, TCSAFLUSH, t_p);
117     return true;
118 }
.PP
.fi

.PP
Referenced by \fBmain()\fP\&.
.SS "bool restore_curses_tioctl ()"

.PP
\fBrestore_curses_tioctl()\fP - restore curses terminal settings 
.PP
\fBReturns\fP
.RS 4
- true on success 
.RE
.PP
\fBNote\fP
.RS 4
- restores terminal settings for stdin, stdout, and stderr 
.RE
.PP

.PP
Definition at line \fB70\fP of file \fBscriou\&.c\fP\&.
.nf
70                              {
71     if (!f_have_curses_tioctl)
72         return false;
73     tcsetattr(0, TCSANOW, &curses_tioctl);
74     return true;
75 }
.PP
.fi

.PP
References \fBcurses_tioctl\fP, and \fBf_have_curses_tioctl\fP\&.
.PP
Referenced by \fBexec_objects()\fP, \fBfork_exec()\fP, and \fBinit_pick()\fP\&.
.SS "bool restore_shell_tioctl ()"

.PP
\fBrestore_shell_tioctl()\fP - restore shell terminal settings 
.PP
\fBReturns\fP
.RS 4
- true on success 
.RE
.PP
\fBNote\fP
.RS 4
- restores terminal settings for stdin, stdout, and stderr 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/enterchr\&.c\fP, and \fB/usr/local/src/cmenu/src/enterstr\&.c\fP\&.
.PP
Definition at line \fB51\fP of file \fBscriou\&.c\fP\&.
.nf
51                             {
52     if (!f_have_shell_tioctl)
53         return false;
54     tcsetattr(0, TCSANOW, &shell_tioctl);
55     return true;
56 }
.PP
.fi

.PP
References \fBf_have_shell_tioctl\fP, and \fBshell_tioctl\fP\&.
.PP
Referenced by \fBabend()\fP, \fBdestroy_curses()\fP, \fBfork_exec()\fP, \fBhandle_signal()\fP, \fBmain()\fP, and \fBuser_end()\fP\&.
.SS "bool set_sane_tioctl (struct termios * t_p)"

.PP
\fBset_sane_tioctl()\fP - set terminal to sane settings for C-MENU 
.PP
\fBParameters\fP
.RS 4
\fIt_p\fP - pointer to termios structure to modify 
.RE
.PP
\fBReturns\fP
.RS 4
- true on success 
.RE
.PP
\fBNote\fP
.RS 4
- sets terminal to sane settings for C-MENU applications 
.RE
.PP

.PP
Definition at line \fB80\fP of file \fBscriou\&.c\fP\&.
.nf
80                                           {
81     tcgetattr(0, t_p);
82     t_p\->c_iflag &= ~(IGNBRK | BRKINT | PARMRK | INPCK | ISTRIP | INLCR |
83                       IGNCR | ICRNL | IXON | IXOFF);
84     t_p\->c_iflag |= IUTF8;
85     t_p\->c_oflag |= OPOST | OCRNL;
86     t_p\->c_lflag &= ~(ECHO | ECHONL | ICANON | IEXTEN);
87     t_p\->c_lflag |= (ISIG | ICANON | IEXTEN | ECHO | ECHOE | ECHOK);
88     t_p\->c_cflag &= ~(CSIZE | PARENB);
89     t_p\->c_cflag |= CS8 | CLOCAL | CREAD;
90     tcsetattr(0, TCSANOW, t_p);
91     return true;
92 }
.PP
.fi

.SH "Variable Documentation"
.PP 
.SS "struct termios shell_err_tioctl curses_err_tioctl"

.PP
Definition at line \fB35\fP of file \fBscriou\&.c\fP\&.
.SS "struct termios shell_in_tioctl curses_in_tioctl"

.PP
Definition at line \fB33\fP of file \fBscriou\&.c\fP\&.
.SS "struct termios shell_out_tioctl curses_out_tioctl"

.PP
Definition at line \fB34\fP of file \fBscriou\&.c\fP\&.
.SS "struct termios \fBshell_tioctl\fP curses_tioctl"

.PP
Definition at line \fB21\fP of file \fBscriou\&.c\fP\&.
.PP
Referenced by \fBcapture_curses_tioctl()\fP, and \fBrestore_curses_tioctl()\fP\&.
.SS "bool f_have_curses_tioctl = false"

.PP
Definition at line \fB23\fP of file \fBscriou\&.c\fP\&.
.PP
Referenced by \fBcapture_curses_tioctl()\fP, and \fBrestore_curses_tioctl()\fP\&.
.SS "bool f_have_shell_tioctl = false"

.PP
Definition at line \fB22\fP of file \fBscriou\&.c\fP\&.
.PP
Referenced by \fBcapture_shell_tioctl()\fP, and \fBrestore_shell_tioctl()\fP\&.
.SS "struct termios shell_tioctl"
This file contains terminal ioctl handling functions for C-MENU\&. It provide sane terminal settings for C-MENU applications, and restores the terminal to its original state when the C-MENU application exits\&. 
.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/enterchr\&.c\fP, and \fB/usr/local/src/cmenu/src/enterstr\&.c\fP\&.
.PP
Definition at line \fB20\fP of file \fBscriou\&.c\fP\&.
.PP
Referenced by \fBcapture_shell_tioctl()\fP, \fBmain()\fP, \fBrestore_shell_tioctl()\fP, and \fBsignal_handler()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
