C-Menu: opts.c File Reference
opts.c File Reference
Sort and print options.
#include <common.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define ARRAY_SIZE(arr)
#define red "\033[0;31m"
#define green "\033[0;32m"
#define yellow "\033[0;33m"
#define blue "\033[0;34m"
#define magenta "\033[0;35m"
#define cyan "\033[0;36m"
#define white "\033[0;37m"
#define bblue "\033[34;1m"
#define reset "\033[0m"
Functions
void dump_opts_by_name ()
dump options sorted by name
void dump_opts_by_group ()
dump options sorted by group
void dump_opts_by_desc ()
dump options sorted by description
void dump_opts_by_use (char *usage, char *mask)
dump options by use mask
void dump_opts_by_short_opt ()
dump options sorted by short option
void sort_opts_by_name ()
dump options name
void sort_opts_by_group ()
sort options by group
void sort_opts_by_desc ()
sort options by description
void sort_opts_by_short_opt ()
sort options by short option
void print_opt_header ()
print option header
void print_opt (int i)
print option
int comp_opt_desc (const void *o1, const void *o2)
compare option descriptions
int comp_opt_group (const void *o1, const void *o2)
compare option groups
void dump_opts ()
dump all options
Opts * select_opt (char *name)
select option by name
int comp_opt_name (const void *o1, const void *o2)
compare option names
int comp_opt_short_opt (const void *o1, const void *o2)
compare option short options
Variables
Opts opts []
Detailed Description
Sort and print options.
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file opts.c.
Macro Definition Documentation
ARRAY_SIZE
#define ARRAY_SIZE (arr)
Value:
(sizeof((arr)) / sizeof((arr)[0]))
Definition at line 15 of file opts.c.
bblue
#define bblue "\033[34;1m"
Definition at line 39 of file opts.c.
blue
#define blue "\033[0;34m"
Definition at line 35 of file opts.c.
cyan
#define cyan "\033[0;36m"
Definition at line 37 of file opts.c.
green
#define green "\033[0;32m"
Definition at line 33 of file opts.c.
magenta
#define magenta "\033[0;35m"
Definition at line 36 of file opts.c.
red
#define red "\033[0;31m"
Definition at line 32 of file opts.c.
reset
#define reset "\033[0m"
Definition at line 40 of file opts.c.
white
#define white "\033[0;37m"
Definition at line 38 of file opts.c.
yellow
#define yellow "\033[0;33m"
Definition at line 34 of file opts.c.
Function Documentation
comp_opt_desc()
int comp_opt_desc (const void * o1, const void * o2)
compare option descriptions
Parameters
o1 - pointer to first option
o2 - pointer to second option
Returns
negative if o1 < o2, zero if o1 == o2, positive if o1 > o2
Definition at line 142 of file opts.c.
{
    return strcmp(((Opts *)o1)->desc, ((Opts *)o2)->desc);
}
Referenced by sort_opts_by_desc().
comp_opt_group()
int comp_opt_group (const void * o1, const void * o2)
compare option groups
Parameters
o1 - pointer to first option
o2 - pointer to second option
Returns
negative if o1 < o2, zero if o1 == o2, positive if o1 > o2
Definition at line 134 of file opts.c.
{
    return ((Opts *)o1)->group - ((Opts *)o2)->group;
}
Referenced by sort_opts_by_group().
comp_opt_name()
int comp_opt_name (const void * o1, const void * o2)
compare option names
Parameters
o1 - pointer to first option
o2 - pointer to second option
Returns
negative if o1 < o2, zero if o1 == o2, positive if o1 > o2
Definition at line 126 of file opts.c.
{
    return strcmp(((Opts *)o1)->name, ((Opts *)o2)->name);
}
Referenced by select_opt(), and sort_opts_by_name().
comp_opt_short_opt()
int comp_opt_short_opt (const void * o1, const void * o2)
compare option short options
Parameters
o1 - pointer to first option
o2 - pointer to second option
Returns
negative if o1 < o2, zero if o1 == o2, positive if o1 > o2
Definition at line 150 of file opts.c.
{
    return strcmp(((Opts *)o1)->short_opt, ((Opts *)o2)->short_opt);
}
Referenced by sort_opts_by_short_opt().
dump_opts()
void dump_opts ()
dump all options
Definition at line 211 of file opts.c.
                 {
    print_opt_header();
    int i = 0;
    while (opts[i].name != nullptr) {
        if (opts[i].name[0] != '\0')
            print_opt(i);
        i++;
    }
}
References opts, print_opt(), and print_opt_header().
Referenced by dump_opts_by_desc(), dump_opts_by_group(), dump_opts_by_name(), dump_opts_by_short_opt(), and main().
dump_opts_by_desc()
void dump_opts_by_desc ()
dump options sorted by description
Definition at line 155 of file opts.c.
{
    sort_opts_by_desc();
    dump_opts();
}
References dump_opts(), and sort_opts_by_desc().
dump_opts_by_group()
void dump_opts_by_group ()
dump options sorted by group
Definition at line 167 of file opts.c.
{
    sort_opts_by_group();
    dump_opts();
}
References dump_opts(), and sort_opts_by_group().
dump_opts_by_name()
void dump_opts_by_name ()
dump options sorted by name
Definition at line 161 of file opts.c.
{
    sort_opts_by_name();
    dump_opts();
}
References dump_opts(), and sort_opts_by_name().
Referenced by main().
dump_opts_by_short_opt()
void dump_opts_by_short_opt ()
dump options sorted by short option
Definition at line 173 of file opts.c.
{
    sort_opts_by_short_opt();
    dump_opts();
}
References dump_opts(), and sort_opts_by_short_opt().
Referenced by main().
dump_opts_by_use()
void dump_opts_by_use (char * usage, char * mask)
dump options by use mask
Parameters
usage - usage string
mask - use mask string
Definition at line 224 of file opts.c.
{
    int i = 0;
    int j = 0;
    printf("\nusage: %s\n\n", usage);
    print_opt_header();
    while (opts[i].name != nullptr && opts[i].name[0] != '\0') {
        for (j = 0; j < 4; j++) {
            if (mask[j] != '.' && mask[j] == opts[i].use[j])
                break;
            else
                continue;
        }
        if (j == 4) {
            i++;
            continue;
        }
        if (opts[i].name[0] != '\0')
            print_opt(i);
        i++;
    }
}
References opts, print_opt(), and print_opt_header().
Referenced by form_usage(), and main().
print_opt()
void print_opt (int i)
print option
Parameters
i - option index
Definition at line 256 of file opts.c.
                      {
    char *type;
    char *group;
    char c;
    switch (opts[i].type) {
    case OT_STRING:
        type = "str";
        break;
    case OT_INT:
        type = "int";
        break;
    case OT_BOOL:
        type = "bool";
        break;
    case OT_HEX:
        type = "hex";
        break;
    default:
        type = "   ";
    }
    switch (opts[i].group) {
    case OG_FILES:
        group = "file";
        break;
    case OG_DIRS:
        group = "dir";
        break;
    case OG_SPECS:
        group = "spec";
        break;
    case OG_MISC:
        group = "misc";
        break;
    case OG_PARMS:
        group = "prm";
        break;
    case OG_FLAGS:
        group = "flag";
        break;
    case OG_COL:
        group = "col";
        break;
    default:
        group = "   ";
    }
    if (opts[i].short_opt[0] == '\0')
        c = ' ';
    else
        c = '-';
    printf("%02d %s%-18s%s %-4s %-4s %4s %2s%1c%-3s%s%s%s%s\n", i, blue,
           opts[i].name, reset, type, group, opts[i].use, yellow, c,
           opts[i].short_opt, reset, green, opts[i].desc, reset);
    i++;
}
References opts.
Referenced by dump_opts(), and dump_opts_by_use().
print_opt_header()
void print_opt_header ()
print option header
Definition at line 247 of file opts.c.
{
    printf("   field name         type grp  mask opt description\n");
    printf(
        "   ------------------ ---- ---- ---- --- -------------------------\n");
}
Referenced by dump_opts(), and dump_opts_by_use().
select_opt()
Opts * select_opt (char * name)
select option by name
Parameters
name - option name
Returns
pointer to option, or nullptr if not found
Definition at line 201 of file opts.c.
{
    Opts *opt;
    Opts key;
    key.name = name;
    sort_opts_by_name();
    opt = bsearch(&key, opts, ARRAY_SIZE(opts), sizeof(opts[0]), comp_opt_name);
    return opt;
}
References comp_opt_name(), opts, and sort_opts_by_name().
sort_opts_by_desc()
void sort_opts_by_desc ()
sort options by description
Definition at line 189 of file opts.c.
{
    qsort(opts, ARRAY_SIZE(opts), sizeof(opts[0]), comp_opt_desc);
}
References comp_opt_desc(), and opts.
Referenced by dump_opts_by_desc().
sort_opts_by_group()
void sort_opts_by_group ()
sort options by group
Definition at line 184 of file opts.c.
{
    qsort(opts, ARRAY_SIZE(opts), sizeof(opts[0]), comp_opt_group);
}
References comp_opt_group(), and opts.
Referenced by dump_opts_by_group().
sort_opts_by_name()
void sort_opts_by_name ()
dump options name
Definition at line 179 of file opts.c.
{
    qsort(opts, ARRAY_SIZE(opts), sizeof(opts[0]), comp_opt_name);
}
References comp_opt_name(), and opts.
Referenced by dump_opts_by_name(), and select_opt().
sort_opts_by_short_opt()
void sort_opts_by_short_opt ()
sort options by short option
Definition at line 194 of file opts.c.
{
    qsort(opts, ARRAY_SIZE(opts), sizeof(opts[0]), comp_opt_short_opt);
}
References comp_opt_short_opt(), and opts.
Referenced by dump_opts_by_short_opt().
Variable Documentation
opts
Opts opts[]
Definition at line 52 of file opts.c.
            {
    {"minitrc", 0, 2, "mfpv", "a:", "configuration file spec"},
    {"blue_gamma", 1, 4, "...v", "b:", "blue_gamma (View)"},
    {"cmd", 0, 3, "...v", "c:", "view cmd, first file"},
    {"mapp_spec", 0, 0, "mfpv", "d:", "description spec"},
    {"f_erase_remainder", 2, 5, ".f..", "e",
     "erase remainder of line on enter"},
    {"fill_char", 0, 4, "..p.", "f:", "field fill_char"},
    {"green_gamma", 1, 4, "...v", "g:", "green_gamma (View)"},
    {"help", 2, 5, "mfpv", "h", "help"},
    {"in_spec", 0, 0, "..p.", "i:", "input spec"},
    {"mapp_home", 0, 1, "mfpv", "m:", "home directory"},
    {"select_max", 1, 4, ".f..", "n:", "number of selections"},
    {"out_spec", 0, 0, "..p.", "o:", "output spec"},
    {"prompt-str", 0, 3, "...v", "p:", "User supplied string"},
    {"red_gamma", 1, 4, "...v", "r:", "red_gamma (View)"},
    {"f_strip_ansi", 2, 5, "...v", "j", "always strip ansi when writing"},
    {"f_squeeze", 2, 5, "...v", "s", "squeeze multiple blank lines"},
    {"tab_stop", 1, 4, "...v", "t:", "number of spaces per tab"},
    {"brackets", 0, 4, "..p.", "u:", "brackets around fields"},
    {"f_ignore_case", 2, 5, "...v", "x", "ignore case in search"},
    {"f_at_end_remove", 2, 5, "...v", "y", "remove file at end of program"},
    {"f_at_end_clear", 2, 5, "mfpv", "z", "clear screen at end of program"},
    {"cmd_all", 0, 3, "...v", "A:", "view cmd, all files"},
    {"bg_color", 1, 4, "mfpv", "B:", "background_color"},
    {"lines", 1, 4, "mfpv", "C:", "width in columns"},
    {"f_dump_config", 0, 1, "mfpv", "D", "f_dump_config"},
    {"fg_color", 1, 4, "mfpv", "F:", "foreground_color"},
    {"help_spec", 0, 0, "mfpv", "H:", "help spec"},
    {"cols", 1, 4, "mfpv", "L:", "height in lines"},
    {"f_mutiple_cmd_args", 2, 5, "..p.", "M", "multiple command arguments"},
    {"bo_color", 1, 4, "mfpv", "O:", "border_color"},
    {"prompt-type", 0, 3, "...v",
     "P:", "prompt (S-Short, L-Long, N-None)[string]"},
    {"receiver_cmd", 0, 3, "...v", "R:", "execute receiver of piped output"},
    {"provider_cmd", 0, 3, "...v", "S:", "execute provider of piped input"},
    {"title", 0, 3, "mfpv", "T:", "title"},
    {"mapp_user", 0, 1, "mfpv", "U:", "user directory"},
    {"f_write_config", 0, 1, "mfpv", "W", "f_write_config"},
    {"begx", 1, 4, "mfpv", "X:", "begin on column"},
    {"begy", 1, 4, "mfpv", "Y:", "begin on line"},
    {"f_stop_on_error", 2, 5, "mfpv", "Z", "stop on error"},
    {"black", 0, 4, "mfpv", "", "black (#000000)"},
    {"red", 0, 4, "mfpv", "", "red (#bf0000)"},
    {"green", 0, 4, "mfpv", "", "green (#00cf00)"},
    {"yellow", 0, 4, "mfpv", "", "yellow (#efbf00)"},
    {"blue", 0, 4, "mfpv", "", "blue (#0000FF)"},
    {"magenta", 0, 4, "mfpv", "", "magenta (#9f009f)"},
    {"cyan", 0, 4, "mfpv", "", "cyan (#00dfdf)"},
    {"white", 0, 4, "mfpv", "", "white (#d0d0d0)"},
    {"orange", 0, 4, "mfpv", "", "orange (#FF5f00)"},
    {"bblack", 0, 4, "mfpv", "", "bright black (#7f7f7f)"},
    {"bred", 0, 4, "mfpv", "", "bright red (#FF3737)"},
    {"bgreen", 0, 4, "mfpv", "", "bright green (#00FF7f)"},
    {"byellow", 0, 4, "mfpv", "", "bright yellow (#FFeF00)"},
    {"bblue", 0, 4, "mfpv", "", "bright blue (#00cfFF)"},
    {"bmagenta", 0, 4, "mfpv", "", "bright magenta (#FF00FF)"},
    {"bcyan", 0, 4, "mfpv", "", "bright cyan (#00FFFF)"},
    {"bwhite", 0, 4, "mfpv", "", "bright white (#FFFFFF)"},
    {"borange", 0, 4, "mfpv", "", "bright orange (#FF7500)"},
    {"bg", 3, 6, "mfpv", "", "background (#000720)"},
    {"abg", 3, 6, "mfpv", "", "alternate background (#000f50)"},
    {"editor", 0, 1, "mfpv", "", "default editor"},
    {"mapp_data", 0, 1, "mfpv", "", "data directory"},
    {"mapp_help", 0, 1, "mfpv", "", "help directory"},
    {"mapp_msrc", 0, 1, "mfpv", "", "source directory"},
    {"", 0, 0, "", "", ""}}; // End marker
Referenced by dump_opts(), dump_opts_by_use(), print_opt(), select_opt(), sort_opts_by_desc(), sort_opts_by_group(), sort_opts_by_name(), and sort_opts_by_short_opt().