C-Menu: src/sig.c File Reference
sig.c File Reference
signal handling for interrupt signals
#include <cm.h>
#include <signal.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <termios.h>
#include <unistd.h>
Functions
void sig_dfl_mode ()
Set signal handlers to default behavior.
void sig_prog_mode ()
Set up signal handlers for interrupt signals.
void signal_handler (int sig_num)
Signal handler for interrupt signals.
bool handle_signal (int sig_num)
Handle received signals and prompt user for action.
Variables
volatile sig_atomic_t sig_received = 0
bool f_curses_open = false
Detailed Description
signal handling for interrupt signals
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file sig.c.
Function Documentation
handle_signal()
bool handle_signal (int sig_num)
Handle received signals and prompt user for action.
Definition at line 105 of file sig.c.
{
    switch (sig_num) {
    case SIGINT:
        strnz__cpy(em1, "SIGINT - Interrupt from keyboard", MAXLEN - 1);
        break;
    case SIGTERM:
        strnz__cpy(em1, "SIGTERM - Termination signal", MAXLEN - 1);
        break;
    case SIGQUIT:
        strnz__cpy(em1, "SIGQUIT - Quit from keyboard", MAXLEN - 1);
        break;
    case SIGSEGV:
        strnz__cpy(em1, "SIGSEGV - Segmentation fault", MAXLEN - 1);
        break;
    case SIGUSR1:
        strnz__cpy(em1, "SIGUSR1 - User Signal 1", MAXLEN - 1);
        break;
    default:
        strnz__cpy(em1, "unknown signal", MAXLEN - 1);
        break;
    }
    if (!f_curses_open)
        restore_shell_tioctl();
    em0[0] = '\0';
    ssnprintf(em0, MAXLEN - 1, "Caught signal %d\n", sig_num);
    strnz__cpy(em2, "Press 'q' or F9 to exit, any other key to continue",
               MAXLEN - 1);
    sig_received = 0;
    return true;
}
References em0, em1, em2, f_curses_open, MAXLEN, restore_shell_tioctl(), sig_received, ssnprintf(), and strnz__cpy().
Referenced by xwgetch().
sig_dfl_mode()
void sig_dfl_mode ()
Set signal handlers to default behavior.
Examples
/usr/local/src/cmenu/src/enterstr.c.
Definition at line 23 of file sig.c.
                    {
    struct sigaction sa;
    sa.sa_handler = SIG_DFL;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = SA_RESTART;
    sigaction(SIGINT, &sa, nullptr);
    sigaction(SIGTERM, &sa, nullptr);
    sigaction(SIGQUIT, &sa, nullptr);
    sigaction(SIGUSR1, &sa, nullptr);
    sa.sa_flags = SA_SIGINFO;
    sigaction(SIGSEGV, &sa, nullptr);
}
Referenced by abend(), destroy_curses(), fork_exec(), main(), and user_end().
sig_prog_mode()
void sig_prog_mode ()
Set up signal handlers for interrupt signals.
Upon receiving an interrupt signal (SIGINT, SIGTERM, SIGQUIT), the program will prompt the user to either exit the program or continue execution. If the user chooses to exit, a confirmation prompt will be displayed. If the user opts to continue, the program will resume normal operation.
Examples
/usr/local/src/cmenu/src/enterstr.c.
Definition at line 42 of file sig.c.
                     {
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = signal_handler;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = SA_RESTART;
    if (sigaction(SIGINT, &sa, nullptr) == -1) {
        abend(-1, "sigaction SIGINT failed");
        exit(EXIT_FAILURE);
    }
    if (sigaction(SIGTERM, &sa, nullptr) == -1) {
        abend(-1, "sigaction SIGTERM failed");
        exit(EXIT_FAILURE);
    };
    if (sigaction(SIGQUIT, &sa, nullptr) == -1) {
        abend(-1, "sigaction SIGQUIT failed");
        exit(EXIT_FAILURE);
    }
    if (sigaction(SIGUSR1, &sa, nullptr) == -1) {
        abend(-1, "sigaction SIGUSR1 failed");
        exit(EXIT_FAILURE);
    }
    sa.sa_flags = SA_SIGINFO; // Set the flag to receive siginfo_t
    if (sigaction(SIGSEGV, &sa, nullptr) == -1) {
        abend(-1, "sigaction SIGSEGV failed");
        exit(EXIT_FAILURE);
    }
}
References abend(), and signal_handler().
Referenced by exec_objects(), fork_exec(), init_pick(), and main().
signal_handler()
void signal_handler (int sig_num)
Signal handler for interrupt signals.
Definition at line 72 of file sig.c.
{
    switch (sig_num) {
    case SIGINT:
        sig_received = SIGINT;
        break;
    case SIGTERM:
        sig_received = SIGTERM;
        break;
    case SIGQUIT:
        sig_received = SIGQUIT;
        break;
    case SIGSEGV:
        tcsetattr(0, TCSANOW, &shell_tioctl);
        char *msg1 = "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
        write(STDERR_FILENO, msg1, strlen(msg1));
        char *msg2 = "________ SIGSEGV - Segmentation fault - Generating core "
                     "dump ________\n\n";
        write(STDERR_FILENO, msg2, strlen(msg2));
        struct sigaction sa;
        sa.sa_handler = SIG_DFL;
        sigemptyset(&sa.sa_mask);
        sa.sa_flags = 0;
        sigaction(SIGSEGV, &sa, NULL);
        kill(getpid(), SIGSEGV); // Re-raise the signal
        _exit(EXIT_FAILURE);
    case SIGUSR1:
        sig_received = SIGUSR1;
        break;
    default:
        return;
    }
}
References shell_tioctl, and sig_received.
Referenced by sig_prog_mode().
Variable Documentation
f_curses_open
bool f_curses_open = false
Definition at line 20 of file sig.c.
Referenced by destroy_curses(), display_error(), handle_signal(), open_curses(), and Perror().
sig_received
volatile sig_atomic_t sig_received = 0
Definition at line 18 of file sig.c.
Referenced by handle_signal(), signal_handler(), and xwgetch().