C-Menu: src/include/form.h File Reference
form.h File Reference
Form data structures, enums, types, end external declarations.
#include <cm.h>
Data Structures
struct Text
structure for form fields
struct Field
structure for form fields
struct Form
Macros
#define TBL_COLS 1024
#define MAXFIELDS 100
#define F_NOMETAS 1
#define F_NOTBLANK 2
#define F_NOECHO 4
Typedefs
typedef struct Init Init
Enumerations
enum {
P_CONTINUE , P_ACCEPT , P_HELP , P_CANCEL ,
P_REFUSE , P_CALC , P_EDIT , P_END
}
enum FieldFormat {
FF_STRING , FF_DECIMAL_INT , FF_HEX_INT , FF_FLOAT ,
FF_DOUBLE , FF_CURRENCY , FF_YYYYMMDD , FF_HHMMSS ,
FF_APR , FF_INVALID
}
Functions
int form_accept_field (Form *)
Accept input for a field.
int form_display_field (Form *)
Display current field.
int form_display_field_n (Form *, int)
Display field n.
int form_enter_fields (Form *)
Handle user input for field entry, allowing navigation between fields and looping until an exit action is selected.
int form_read_description (Form *)
int form_fmt_field (Form *, char *s)
Format field according to its format type.
int form_desc_error (int, char *, char *)
Handle errors encountered while parsing the form description file, providing detailed error messages that include the file name, line number, and the specific error encountered.
void form_help (char *)
int form_yx_to_fidx (Form *, int, int)
void form_display_chyron (Form *)
Display the chyron (status line) at the bottom of the form window, showing available commands and their corresponding function keys.
Variables
char ff_tbl [][26]
Form * form
Detailed Description
Form data structures, enums, types, end external declarations.
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file form.h.
Macro Definition Documentation
F_NOECHO
#define F_NOECHO 4
flag - do not echo field input on the screen, e.g. for password \ fields
Definition at line 22 of file form.h.
#define F_NOECHO                                                               \
    4
F_NOMETAS
#define F_NOMETAS 1
flag - no metacharacters allowed in field input
Definition at line 20 of file form.h.
Referenced by form_validate_field().
F_NOTBLANK
#define F_NOTBLANK 2
flag - field input cannot be blank
Definition at line 21 of file form.h.
Referenced by form_validate_field().
MAXFIELDS
#define MAXFIELDS 100
Definition at line 19 of file form.h.
Referenced by form_parse_desc(), and form_read_data().
TBL_COLS
#define TBL_COLS 1024
Definition at line 18 of file form.h.
Referenced by form_parse_desc().
Typedef Documentation
Init
typedef struct Init Init
Definition at line 15 of file form.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Form process types
Enumerator
P_CONTINUE 302
continue processing the form, e.g. after accepting a field
P_ACCEPT
accept the form, e.g. after accepting a field and all fields are valid
P_HELP
display the help information for the form, e.g. after accepting a field and the user requests help
P_CANCEL
cancel the form, e.g. after accepting a field and the user cancels the form
P_REFUSE
refuse the form, e.g. after accepting a field and the field value is invalid
P_CALC
calculate the form, e.g. after accepting a field and calculating the values of other fields based on the accepted field value
P_EDIT
edit the form, e.g. after accepting a field and allowing the user to edit the form fields
P_END
end the form processing, e.g. after accepting a field and all fields are valid and the form is accepted
Definition at line 27 of file form.h.
    P_ACCEPT,
    P_HELP,
    P_CANCEL,
    P_REFUSE,
    P_CALC,
    P_EDIT,
    P_END
};
FieldFormat
enum FieldFormat
Form field formats
Enumerator
FF_STRING
a string field format, e.g. for accepting a name or other text input
FF_DECIMAL_INT
a decimal integer field format, e.g. for accepting an age or other numeric input
FF_HEX_INT
a hexadecimal integer field format, e.g. for accepting a color code or other hexadecimal input
FF_FLOAT
a floating point field format, e.g. for accepting a price or other decimal input
FF_DOUBLE
a double precision floating point field format, e.g. for accepting a more precise decimal input
FF_CURRENCY
a currency field format, e.g. for accepting a price or other monetary input, formatted as a decimal number with two decimal places and a currency symbol
FF_YYYYMMDD
a date field format, e.g. for accepting a date input, formatted as a string in the format "YYYY-MM-DD"
FF_HHMMSS
a time field format, e.g. for accepting a time input, formatted as a string in the format "HH:MM:SS"
FF_APR
an APR field format, e.g. for accepting an annual percentage rate input, formatted as a decimal number with two decimal places and a percent symbol
FF_INVALID
an invalid field format, used for error handling and validation purposes Future Implementation of Additional Field Formats FF_EMAIL - an email field format, e.g. for accepting an email address input, formatted as a string that matches a regular expression for valid email addresses FF_PHONE - a phone number field format, e.g. for accepting a phone number input, formatted as a string that matches a regular expression for valid phone numbers FF_URL - a URL field format, e.g. for accepting a URL input, formatted as a string that matches a regular expression for valid
Definition at line 48 of file form.h.
                 {
    FF_STRING,
    FF_DECIMAL_INT,
    FF_HEX_INT,
    FF_FLOAT,
    FF_DOUBLE,
    FF_CURRENCY,
    FF_YYYYMMDD,
    FF_HHMMSS,
    FF_APR,
    FF_INVALID
};
Function Documentation
form_accept_field()
int form_accept_field (Form * form) extern
Accept input for a field.
Parameters
form Pointer to Form structure
Returns
int Key code of action taken
Note
Handles character input, navigation keys, and mouse events for field editing. Validates input based on field format and updates display. Returns key code of action taken (e.g., accept field, tab to next field, break out of input loop).
KEY_F(10) is the default key for accepting the field and moving to the next field
KEY_F(9) Cancels the current operation
KEY_UP, KEY_BTAB moves to the previous field
KEY_DOWN, TAB moves to the next field
KEY_END moves cursor to end of field
< Enter accepts the field and moves to the next field if form->f_erase_remainder is set, it will clear the remaining characters above and after the current cursor location
KEY_IC toggles insert mode
KEY_DC deletes character at cursor
KEY_HOME moves cursor to start of field
KEY_BACKSPACE deletes character before cursor
KEY_LEFT moves cursor left one character
KEY_RIGHT moves cursor right one character
Handles mouse events for field editing
Validates fields based on format
FF_STRING accepts all printable characters and spaces
FF_DECIMAL_INT accepts digits 0 through 9 and decimal point ('.')
FF_HEX_INT accepts digits 0 through 9 and letters A through F (case-insensitive)
FF_FLOAT accepts digits 0 through 9 and decimal point ('.') and negative operator ('-') at the start of the field
FF_DOUBLE accepts digits 0 through 9 and decimal point ('.') and negative operator ('-') at the start of the field
FF_CURRENCY accepts digits 0 through 9 and decimal point ('.') and negative operator ('-') at the start of the field
FF_YYYYMMDD accepts digits 0 through 9
FF_HHMMSS accepts digits 0 through 9
FF_APR accepts digits 0 through 9 and decimal point ('.')
Definition at line 44 of file fields.c.
{
    bool f_insert = FALSE;
    int in_key;
    char *s, *d;
    WINDOW *win = form->win;
    int flin = form->field[form->fidx]->line;
    int fcol = form->field[form->fidx]->col;
    int flen = form->field[form->fidx]->len;
    int ff = form->field[form->fidx]->ff;
    char *accept_s = form->field[form->fidx]->accept_s;
    char *filler_s = form->field[form->fidx]->filler_s;
    form_fmt_field(form, accept_s);
    click_x = click_y = -1;
    char *fstart = accept_s;
    char *fend = fstart + flen;
    int x = fcol;
    char *p = fstart = accept_s;
    char *str_end = p + strlen(p);
    in_key = 0;
    if (f_insert)
        set_chyron_key(form->chyron, 18, "OVR", KEY_IC);
    else
        set_chyron_key(form->chyron, 18, "INS", KEY_IC);
    compile_chyron(form->chyron);
    form_display_chyron(form);
    while (1) {
        if (in_key == 0) {
            mvwaddstr(win, flin, fcol, filler_s);
            mvwaddstr(win, flin, fcol, accept_s);
            wmove(win, flin, x);
            tcflush(0, TCIFLUSH);
            wmove(win, flin, x);
            in_key = xwgetch(win, form->chyron);
        }
        switch (in_key) {
        case KEY_F(10):
            form_fmt_field(form, accept_s);
            form_display_field(form);
            if (form_validate_field(form) != 0)
                continue;
            return (in_key);
        case KEY_BREAK:
        case KEY_F(9):
            form_display_field(form);
            in_key = KEY_F(9);
            return (in_key);
        case 'H':
        case KEY_F(1):
            return (in_key);
        case KEY_BTAB:
        case KEY_UP:
            form_fmt_field(form, accept_s);
            form_display_field(form);
            in_key = KEY_UP;
            return (in_key);
        case '\t':
        case KEY_DOWN:
            form_fmt_field(form, accept_s);
            form_display_field(form);
            in_key = KEY_DOWN;
            return (in_key);
        case KEY_END:
            while (*p != '\0')
                p++;
            x = fcol + (p - fstart);
            in_key = 0;
            continue;
        case '\n':
        case KEY_ENTER:
            if (form->f_erase_remainder)
                *p = '\0';
            form_fmt_field(form, accept_s);
            form_display_field(form);
            in_key = KEY_ENTER;
            return (in_key);
        case KEY_IC:
            if (f_insert) {
                f_insert = FALSE;
                set_chyron_key(form->chyron, 18, "INS", KEY_IC);
            } else {
                f_insert = TRUE;
                set_chyron_key(form->chyron, 18, "OVR", KEY_IC);
            }
            compile_chyron(form->chyron);
            form_display_chyron(form);
            in_key = 0;
            continue;
        case KEY_DC:
            s = p + 1;
            d = p;
            while (*s != '\0')
                *d++ = *s++;
            *d = '\0';
            str_end = d;
            f_insert = FALSE;
            in_key = 0;
            continue;
        case KEY_HOME:
            p = fstart;
            x = fcol;
            in_key = 0;
            continue;
        case KEY_BACKSPACE:
            if (p > fstart) {
                p--;
                x--;
            }
            s = p + 1;
            d = p;
            while (*s != '\0')
                *d++ = *s++;
            *d = '\0';
            str_end = d;
            in_key = 0;
            continue;
        case KEY_LEFT:
            if (p > fstart) {
                p--;
                x--;
            }
            in_key = 0;
            continue;
        case KEY_RIGHT:
            if (p < fend && p < str_end) {
                p++;
                x++;
            }
            in_key = 0;
            continue;
        case KEY_MOUSE:
            form->fidx = form_yx_to_fidx(form, click_y, click_x);
            x = click_x;
            flin = click_y;
            flen = form->field[form->fidx]->len;
            ff = form->field[form->fidx]->ff;
            accept_s = form->field[form->fidx]->accept_s;
            filler_s = form->field[form->fidx]->filler_s;
            form_fmt_field(form, accept_s);
            fstart = accept_s;
            fend = fstart + flen;
            p = fstart + (x - form->field[form->fidx]->col);
            str_end = fstart + strlen(fstart);
            in_key = 0;
            continue;
        default:
            if (p >= fend) {
                in_key = 0;
                continue;
            }
            switch (ff) {
            case FF_STRING:
                break;
            case FF_DECIMAL_INT:
                if ((in_key >= '0' && in_key <= '9') || in_key == '.')
                    break;
                beep();
                in_key = 0;
                continue;
            case FF_HEX_INT:
                if ((in_key >= '0' && in_key <= '9') ||
                    (in_key >= 'A' && in_key <= 'F') ||
                    (in_key >= 'a' && in_key <= 'f'))
                    break;
                beep();
                in_key = 0;
                continue;
            case FF_FLOAT:
                if ((in_key >= '0' && in_key <= '9') || in_key == '.' ||
                    (in_key == '-' && p == fstart))
                    break;
                beep();
                in_key = 0;
                continue;
            case FF_DOUBLE:
                if ((in_key >= '0' && in_key <= '9') || in_key == '.' ||
                    (in_key == '-' && p == fstart))
                    break;
                beep();
                in_key = 0;
                continue;
            case FF_CURRENCY:
                if ((in_key >= '0' && in_key <= '9') || in_key == '.' ||
                    (in_key == '-' && p == fstart))
                    break;
                beep();
                in_key = 0;
                continue;
            case FF_YYYYMMDD:
                if (in_key >= '0' && in_key <= '9')
                    break;
                beep();
                in_key = 0;
                continue;
            case FF_HHMMSS:
                if (in_key >= '0' && in_key <= '9')
                    break;
                beep();
                in_key = 0;
                continue;
            case FF_APR:
                if ((in_key >= '0' && in_key <= '9') || in_key == '.')
                    break;
                beep();
                in_key = 0;
                continue;
            default:
                Perror("form_accept_field() invalid format");
                break;
            }
            if (in_key >= ' ') {
                if (f_insert) {
                    if (str_end < fend) {
                        s = str_end - 1;
                        d = str_end;
                        while (s >= p)
                            *d-- = *s--;
                        *p++ = in_key;
                        str_end++;
                        x++;
                    }
                } else {
                    if (p < fend) {
                        if (p < str_end) {
                            *p++ = in_key;
                            x++;
                        } else if (p == str_end) {
                            *p++ = in_key;
                            *p = '\0';
                            str_end = p;
                            x++;
                        }
                    }
                }
                in_key = 0;
                continue;
            }
        }
    }
}
References click_x, click_y, compile_chyron(), FALSE, FF_APR, FF_CURRENCY, FF_DECIMAL_INT, FF_DOUBLE, FF_FLOAT, FF_HEX_INT, FF_HHMMSS, FF_STRING, FF_YYYYMMDD, form, form_display_chyron(), form_display_field(), form_fmt_field(), form_validate_field(), form_yx_to_fidx(), Perror(), set_chyron_key(), TRUE, win, and xwgetch().
Referenced by form_enter_fields().
form_desc_error()
int form_desc_error (int in_line_num, char * in_buf, char * em) extern
Handle errors encountered while parsing the form description file, providing detailed error messages that include the file name, line number, and the specific error encountered.
Parameters
in_line_num The line number in the description file where the error occurred.
in_buf The content of the line that caused the error, for context.
em A specific error message describing the nature of the error.
Returns
An integer status code indicating how the user responded to the error message (e.g., which key they pressed to acknowledge the error).
Definition at line 872 of file form_engine.c.
{
    int cmd_key;
    ssnprintf(em0, MAXLEN - 1, "%s: %s", __FILE__, em);
    ssnprintf(em1, MAXLEN - 1, "Desc file: %s, line: %d", form->mapp_spec,
              in_line_num);
    strnz__cpy(em2, in_buf, MAXLEN - 1);
    cmd_key = display_error(em0, em1, em2, nullptr);
    return cmd_key;
}
References cmd_key, display_error(), em0, em1, em2, form, MAXLEN, ssnprintf(), and strnz__cpy().
Referenced by form_parse_desc().
form_display_chyron()
void form_display_chyron (Form * form) extern
Display the chyron (status line) at the bottom of the form window, showing available commands and their corresponding function keys.
Parameters
form A pointer to the Form structure containing form data and state.
Definition at line 509 of file form_engine.c.
{
    compile_chyron(form->chyron);
    wattron(form->win, WA_REVERSE);
    mvwaddstr(form->win, form->lines - 1, 0, form->chyron->s);
    wattroff(form->win, WA_REVERSE);
    wclrtoeol(form->win);
    wmove(form->win, form->lines - 1, form->chyron->l);
}
References compile_chyron(), and form.
Referenced by form_accept_field(), form_calculate(), form_display_fields(), and form_end_fields().
form_display_field()
int form_display_field (Form * form) extern
Display current field.
Parameters
form Pointer to Form structure
Returns
0 on success, non-zero on error
Note
This function displays the current field based on the form's current field index (fidx). It retrieves the line and column information for the current field, displays any brackets if set, and then displays the field's content using the display_s string. The function ensures that the field is displayed correctly within the form's window and refreshes the display to show the updated field content.
Definition at line 345 of file fields.c.
{
    WINDOW *win = form->win;
    int flin = form->field[form->fidx]->line;
    int fcol = form->field[form->fidx]->col;
    form_display_field_brackets(form);
    mvwaddstr(win, flin, fcol, form->field[form->fidx]->filler_s);
    mvwaddstr(win, flin, fcol, form->field[form->fidx]->display_s);
    wrefresh(win);
    return 0;
}
References form, form_display_field_brackets(), and win.
Referenced by form_accept_field(), and form_display_field_n().
form_display_field_n()
int form_display_field_n (Form * form, int n) extern
Display field n.
Parameters
form Pointer to Form structure
n Field index to display
Returns
0 on success, non-zero on error
Note
This function temporarily sets the form's current field index (fidx) to n, calls form_display_field() to display that field, and then restores the original fidx value. This allows for displaying a specific field without permanently changing the form's current field index.
Definition at line 328 of file fields.c.
{
    int fidx = form->fidx;
    form->fidx = n;
    form_display_field(form);
    form->fidx = fidx;
    return 0;
}
References form, and form_display_field().
Referenced by form_display_fields().
form_enter_fields()
int form_enter_fields (Form * form) extern
Handle user input for field entry, allowing navigation between fields and looping until an exit action is selected.
Parameters
form A pointer to the Form structure containing form data and state.
Returns
An integer status code indicating the next action for the form processing loop (e.g., P_ACCEPT, P_HELP, P_CALC, P_CANCEL).
Note
This function manages user input for field entry, including navigation between fields and handling of special keys for accepting, canceling, requesting help, or performing calculations. The function loops until the user selects an exit action (e.g., accept or cancel).
Definition at line 369 of file form_engine.c.
{
    if (form->fidx < 0)
        return (-1);
    while (1) {
        cmd_key = form_accept_field(form);
        wrefresh(form->win);
        switch (cmd_key) {
        case KEY_F(10):
            return (P_ACCEPT);
        case KEY_F(1):
            return (P_HELP);
        case KEY_F(5):
            if (form->f_calculate)
                return (P_CALC);
            break;
        case KEY_F(9):
            return (P_CANCEL);
        case KEY_UP:
            if (form->fidx != 0)
                form->fidx--;
            break;
        case '\r':
        case KEY_ENTER:
            if (form->fidx < form->fcnt - 1)
                form->fidx++;
            else if (form->fidx == form->fcnt - 1)
                return (P_ACCEPT);
            break;
        case KEY_DOWN:
            if (form->fidx < form->fcnt - 1)
                form->fidx++;
            else if (form->fidx == form->fcnt - 1)
                return (P_ACCEPT);
            break;
        case KEY_MOUSE:
            break;
        default:
            break;
        }
    }
}
References cmd_key, form, form_accept_field(), P_ACCEPT, P_CALC, P_CANCEL, and P_HELP.
Referenced by form_engine().
form_fmt_field()
int form_fmt_field (Form * form, char * s) extern
Format field according to its format type.
Parameters
form Pointer to Form structure
s Input string to format
Returns
0 on success, non-zero on error
Note
This function takes the input string for the current field and formats it according to the field's specified format type (ff). It updates the accept_s and display_s strings for the field based on the formatted value. The function handles various format types, including strings, decimal integers, hexadecimal integers, floating-point numbers, currency, dates, and times. It uses helper functions for validation and formatting, such as is_valid_date(), is_valid_time(), numeric(), right_justify(), left_justify(), and strnzcpy(). The function ensures that the formatted output fits within the field's length and creates a filler string for the field as needed. The function also handles error cases, such as invalid formats, and provides feedback through error messages. It is designed to be extensible, allowing for additional format types to be added in the future as needed.
Format field according to its format type
Parameters
form Pointer to Form structure
s Input string to format
Returns
0 on success, non-zero on error
Note
takes the input string for the current field and formats it according to the field's specified format type (ff). It updates the accept_s and display_s strings for the field based on the formatted value.
handles various format types, including strings, decimal integers, hexadecimal integers, floating-point numbers, currency, dates, and times.
uses helper functions for validation and formatting, such as is_valid_date(), is_valid_time(), numeric(), right_justify(), left_justify(), and strnzcpy(). The function ensures that the formatted output fits within the field's length and creates a filler string for the field as needed. The function also handles error cases, such as invalid formats, and provides feedback through error messages. It is designed to be extensible, allowing for additional format types to be added in the future as needed.
assumes that the input string is well-formed and does not contain malicious content. Input validation and sanitization should be performed at a higher level in the application to ensure security and robustness.
The function currently does not handle localization or internationalization of number formats, such as different decimal separators or currency symbols. Future enhancements may include support for locale-specific formatting.
Error handling is basic; future versions may include more detailed error reporting and logging mechanisms.
Performance optimizations may be considered for handling large volumes of data or high-frequency updates in real-time applications.
The following variables and structures are used in this function:
char field_s[MAXLEN];
int decimal_int_n = 0;
int hex_int_n = 0;
float float_n = 0.0;
double double_n = 0.0;
double currency_n = 0.0;
struct Date { int yyyy; int mm; int dd; };
struct Time { int hh; int mm; int ss; };
supports format types: FF_STRING, FF_DECIMAL_INT, FF_HEX_INT, FF_FLOAT, FF_DOUBLE, FF_CURRENCY, FF_YYYYMMDD, FF_HHMMSS, FF_APR with appropriate formatting and validation for each type.
Handles field length and filler string creation.
As the roadmap indicates, these data types are just a start and more complex types and formats may be added in the future.
These data types are not suitable for financial, scientific, or high-precision applications. They are intended for basic data entry and display in a text-based user interface.
In the future, we will aqdd support for additional data types and formats such as: dates with time zones, timestamps, percentages, scientific notation, and custom user-defined formats.
For high precision applications, we will be integrating support for 128-bit binary coded decimal (BCD) types and arbitrary precision decimal types using libraries such as the GNU MPFR library, IBM's decNumber, Rust Decimal, or the Intel Decimal Floating-Point Math Library.
C-Menu Form converts each field's input string into internal numeric binary based on the field's specified format. The internal numberic binary is then formated and displayed, verifying the user's input and Form's interpretation of the user's input.
Definition at line 395 of file fields.c.
{
    strnz__cpy(form->field[form->fidx]->input_s, s, MAXLEN - 1);
    char *input_s = form->field[form->fidx]->input_s;
    char *accept_s = form->field[form->fidx]->accept_s;
    char *display_s = form->field[form->fidx]->display_s;
    char *filler_s = form->field[form->fidx]->filler_s;
    int ff = form->field[form->fidx]->ff;
    int fl = form->field[form->fidx]->len;
    char field_s[MAXLEN];
    int decimal_int_n = 0;
    int hex_int_n = 0;
    float float_n = 0.0;
    double double_n = 0.0;
    double currency_n = 0.0;
    struct {
        int yyyy;
        int mm;
        int dd;
    } Date;
    Date.yyyy = Date.mm = Date.dd = 0;
    struct {
        int hh;
        int mm;
        int ss;
    } Time;
    Time.hh = Time.mm = Time.ss = 0;
    strnz(accept_s, fl);
    switch (ff) {
    case FF_STRING:
        left_justify(s);
        trim(s);
        strnz__cpy(input_s, s, MAXLEN - 1);
        strnz__cpy(accept_s, s, MAXLEN - 1);
        strnz__cpy(display_s, s, MAXLEN - 1);
        break;
    case FF_DECIMAL_INT:
        sscanf(input_s, "%d", &decimal_int_n);
        sprintf(accept_s, "%d", decimal_int_n);
        sprintf(display_s, "%d", decimal_int_n);
        right_justify(display_s, fl);
        break;
    case FF_HEX_INT:
        sscanf(input_s, "%x", &hex_int_n);
        sprintf(accept_s, "%d", hex_int_n);
        sprintf(display_s, "%x", hex_int_n);
        right_justify(display_s, fl);
        break;
    case FF_FLOAT:
        sscanf(input_s, "%f", &float_n);
        sprintf(accept_s, "%f", float_n);
        sprintf(display_s, "%f", float_n);
        right_justify(display_s, fl);
        break;
    case FF_DOUBLE:
        sscanf(input_s, "%lf", &double_n);
        sprintf(accept_s, "%lf", double_n);
        sprintf(display_s, "%lf", double_n);
        right_justify(display_s, fl);
        break;
    case FF_CURRENCY:
        numeric(field_s, input_s);
        sscanf(field_s, "%lf", &currency_n);
        sprintf(accept_s, "%.2lf", currency_n);
        sprintf(display_s, "%'.2lf", currency_n);
        right_justify(display_s, fl);
        break;
    case FF_YYYYMMDD:
        Date.yyyy = Date.mm = Date.dd = 0;
        strnz__cpy(field_s, input_s, MAXLEN - 1);
        sscanf(field_s, "%4d%2d%2d", &Date.yyyy, &Date.mm, &Date.dd);
        sprintf(accept_s, "%04d%02d%02d", Date.yyyy, Date.mm, Date.dd);
        if (is_valid_date(Date.yyyy, Date.mm, Date.dd))
            sprintf(display_s, "%04d-%02d-%02d", Date.yyyy, Date.mm, Date.dd);
        break;
    case FF_HHMMSS:
        Time.hh = Time.mm = Time.ss = 0;
        strnz__cpy(field_s, input_s, MAXLEN - 1);
        sscanf(field_s, "%2d%2d%2d", &Time.hh, &Time.mm, &Time.ss);
        sprintf(accept_s, "%02d%02d%02d", Time.hh, Time.mm, Time.ss);
        if (is_valid_time(Time.hh, Time.mm, Time.ss))
            sprintf(display_s, "%02d:%02d:%02d", Time.hh, Time.mm, Time.ss);
        break;
    case FF_APR:
        sscanf(input_s, "%lf", &double_n);
        sprintf(accept_s, "%lf", double_n);
        sprintf(display_s, "%0.3lf", double_n);
        right_justify(display_s, fl);
        break;
    default:
        Perror("form_fmt_field() invalid format");
        break;
    }
    strnz(accept_s, fl);
    left_justify(accept_s);
    mk_filler(filler_s, fl);
    return 0;
}
References FF_APR, FF_CURRENCY, FF_DECIMAL_INT, FF_DOUBLE, FF_FLOAT, FF_HEX_INT, FF_HHMMSS, FF_STRING, FF_YYYYMMDD, form, is_valid_date(), is_valid_time(), left_justify(), MAXLEN, mk_filler(), numeric(), Perror(), right_justify(), strnz(), strnz__cpy(), and trim().
Referenced by form_accept_field(), and form_read_data().
form_help()
void form_help (char *) extern
form_read_description()
int form_read_description (Form *) extern
form_yx_to_fidx()
int form_yx_to_fidx (Form * form, int y, int x) extern
Definition at line 419 of file form_engine.c.
{
    for (int i = 0; i < form->fcnt; i++) {
        if (y == form->field[i]->line && x >= form->field[i]->col &&
            x < form->field[i]->col + form->field[i]->len) {
            return i;
        }
    }
    return -1; // No field found at the given coordinates
}
References form.
Referenced by form_accept_field().
Variable Documentation
ff_tbl
char ff_tbl[][26] extern
ff_tbl - a table of field format strings used in the Form description file to identify field data types the index of the field format in this table corresponds to the FieldFormat enum values, e.g. ff_tbl[FF_STRING] = "string", ff_tbl[F_DECIMAL_INT] = "decimal_int", etc. a table of field format strings used in the Form description file to identify field data types, e.g. "string", "decimal_int", "hex_int", etc. The index of the field format in this table corresponds to the FieldFormat enum values, e.g. ff_tbl[FF_STRING] = "string", ff_tbl[FF_DECIMAL_INT] = "decimal_int", etc. This table is used for parsing the form description file and determining the field formats for each field in the form.
Definition at line 26 of file fields.c.
                  {"string",   "decimal_int", "hex_int", "float", "double",
                     "currency", "yyyymmdd",    "hhmmss",  "apr",   ""};
Referenced by form_parse_desc().
form
Form* form extern
a pointer to the current form structure, used for managing and processing the form during form processing. This pointer can be updated to point to different form structures as needed, allowing for dynamic handling of multiple forms within the same application or session. The form pointer provides access to all the properties and data of the current form, enabling efficient management and processing of the form fields and text during user interactions and other events during form processing.
Definition at line 35 of file mem.c.
Referenced by form_accept_field(), form_calculate(), form_desc_error(), form_display_chyron(), form_display_field(), form_display_field_brackets(), form_display_field_n(), form_display_fields(), form_display_screen(), form_end_fields(), form_engine(), form_enter_fields(), form_exec_cmd(), form_fmt_field(), form_parse_desc(), form_read_data(), form_validate_field(), form_write(), form_yx_to_fidx(), init_form(), init_form_files(), mk_filler(), and new_form().