C-Menu: src/ckeys.c File Reference
ckeys.c File Reference
Test Curses Keys.
#include <common.h>
#include <sys/types.h>
Functions
int main (int argc, char **argv)
Variables
__end_pgm
Detailed Description
Test Curses Keys.
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file ckeys.c.
Function Documentation
main()
int main (int argc, char ** argv)
Entry point for Curses Keys test
Examples
/usr/local/src/cmenu/src/enterchr.c, /usr/local/src/cmenu/src/enterstr.c, and strings_test1.c.
Definition at line 16 of file ckeys.c.
{
    __atexit;
    int rc;
    capture_shell_tioctl();
    init = new_init(argc, argv);
    if (!init) {
        abend(-1, "malloc failed init (Init)");
    }
    SIO *sio = init->sio;
    mapp_initialization(init, argc, argv);
    open_curses(sio);
    sig_prog_mode();
    win_init_attrs(sio->fg_color, sio->bg_color, sio->bo_color);
    rc = display_curses_keys();
    win_del();
    destroy_curses();
    return (rc);
}
References abend(), capture_shell_tioctl(), destroy_curses(), display_curses_keys(), init, mapp_initialization(), new_init(), open_curses(), sig_prog_mode(), sio, win_del(), and win_init_attrs().
Variable Documentation
__end_pgm
__end_pgm
Definition at line 13 of file ckeys.c.