C-Menu: src/test/rfc3339.c File Reference
rfc3339.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
Data Structures
struct String
The String structure represents a string object with a pointer to the string and its allocated length.
Functions
String mk_string (size_t l)
Create a String struct with a dynamically allocated string.
String to_string (const char *s)
Convert C string to String struct.
void free_string (String str)
Free the dynamically allocated String.
void get_rfc3339_str (String timestamp_s)
int main ()
Detailed Description
String struct and functions fn to_string(char *s) -> String Convert C string to String struct
Parameters
s C string
Note
: The returned String struct contains a dynamically allocated copy of the input string.
: the caller is responsible for freeing the allocated memory.
See also
: free_string
Returns
: String struct
Definition in file rfc3339.c.
Function Documentation
free_string()
void free_string (String str)
Free the dynamically allocated String.
fn free_string(String str) -> String Free the memory allocated for a String struct
Parameters
str String struct to free
Note
: This function frees the memory allocated for the string in the String struct and sets its length to 0 and pointer to NULL.
Returns
: String struct with NULL pointer and length 0
Definition at line 87 of file rfc3339.c.
{
    free(str.s);
    str.l = 0;
    str.s = NULL;
    return str;
}
References String::l, and String::s.
Referenced by get_rfc3339_str(), and main().
get_rfc3339_str()
void get_rfc3339_str (String timestamp_s)
Examples
/usr/local/src/cmenu/src/test/rfc3339.c.
Definition at line 99 of file rfc3339.c.
{
    time_t now;
    struct tm *tms;
    int use_localtime = 0;
    String z_str1, z_str2;
    z_str1 = mk_string(30);
    z_str2 = mk_string(30);
    int i = 0, j;
    time(&now);
    tms = localtime((time_t *)&now);
    strftime(z_str1.s, z_str1.l, "%z", tms);
    for (j = 0; j < 6; j++) {
        if (i == 3)
            z_str2.s[i++] = ':';
        z_str2.s[i++] = z_str1.s[j];
    }
    z_str2.s[6] = '\0';
    sprintf(timestamp_s.s, "%04d-%02d-%02dT%02d:%02d:%02d%s",
            tms->tm_year + 1900, tms->tm_mon + 1, tms->tm_mday, tms->tm_hour,
            tms->tm_min, tms->tm_sec, z_str2.s);
    free_string(z_str1);
    free_string(z_str2);
}
References free_string(), String::l, mk_string(), and String::s.
Referenced by main().
main()
int main ()
Definition at line 123 of file rfc3339.c.
           {
    String timestamp_s;
    timestamp_s = mk_string(30);
    get_rfc3339_str(timestamp_s);
    printf("%s\n", timestamp_s.s);
    free_string(timestamp_s);
}
References free_string(), get_rfc3339_str(), mk_string(), and String::s.
mk_string()
String mk_string (size_t l)
Create a String struct with a dynamically allocated string.
fn mk_string(size_t l) -> String Create an empty String struct with specified length
Parameters
l Length of the string (excluding null terminator)
Note
: The returned String struct contains a dynamically allocated string of length l + 1 (including null terminator).
: the caller is responsible for freeing the allocated memory.
See also
: free_string
Returns
: String struct
Definition at line 59 of file rfc3339.c.
{
    String str;
    str.l = l + 1;
    str.s = (char *)malloc(str.l);
    str.s[0] = '\0';
    return str;
}
References String::l, and String::s.
Referenced by get_rfc3339_str(), and main().
to_string()
String to_string (const char * s)
Convert C string to String struct.
fn to_string(const char *s) -> String Convert C string to String struct
Parameters
s C string
Note
: The returned String struct contains a dynamically allocated copy of the input string.
: the caller is responsible for freeing the allocated memory.
See also
: free_string
Returns
: String struct
Definition at line 74 of file rfc3339.c.
{
    String str;
    str.l = strlen(s) + 1;
    str.s = (char *)malloc(str.l);
    strcpy(str.s, s);
    return str;
}
References String::l, and String::s.