.TH "src/snippets Directory Reference" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/snippets Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsample_menu\&.m\fP"
.br
.ti -1c
.RI "file \fBstrings_test1\&.c\fP"
.br
.RI "\fBString\fP Objects\&. "
.ti -1c
.RI "file \fBstripansi\&.c\fP"
.br
.RI "removes ansi escape sequences beginning with "\\033["" and ending in"m" or "K" "
.in -1c
