.TH "src/test Directory Reference" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolor\&.c\fP"
.br
.RI "Test program for xterm 256-color to \fBRGB\fP conversion and vice versa\&. "
.ti -1c
.RI "file \fBhex2dec\&.c\fP"
.br
.ti -1c
.RI "file \fBiso8601\&.c\fP"
.br
.RI "iso8601 Timestamp "
.ti -1c
.RI "file \fBlocate\&.c\fP"
.br
.RI "Locate a file in PATH\&. "
.ti -1c
.RI "file \fBrbox\&.c\fP"
.br
.RI "Display box with rounded corners\&. "
.ti -1c
.RI "file \fBrfc3339\&.c\fP"
.br
.ti -1c
.RI "file \fBtestfail\&.c\fP"
.br
.RI "Failure termination\&. "
.ti -1c
.RI "file \fBtestok\&.c\fP"
.br
.RI "Successful termination\&. "
.ti -1c
.RI "file \fBunicode_decode\&.c\fP"
.br
.RI "decode UTF-8 encoded string to Unicode code points "
.in -1c
