.TH "Arg" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arg \- The \fBArg\fP structure represents a string argument with a pointer to the string and its allocated length\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/cm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBs\fP"
.br
.ti -1c
.RI "size_t \fBl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBArg\fP structure represents a string argument with a pointer to the string and its allocated length\&. 
.PP
Definition at line \fB455\fP of file \fBcm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t Arg::l"
allocated length 
.PP
Definition at line \fB457\fP of file \fBcm\&.h\fP\&.
.SS "char* Arg::s"
pointer to the string argument 
.PP
Definition at line \fB456\fP of file \fBcm\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
