.TH "Argv" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Argv \- The \fBArgv\fP structure represents an argument vector, which is an array of \fBArg\fP structures, along with the number of allocated elements in the array\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/cm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBArg\fP ** \fBv\fP"
.br
.ti -1c
.RI "size_t \fBn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBArgv\fP structure represents an argument vector, which is an array of \fBArg\fP structures, along with the number of allocated elements in the array\&. 
.PP
Definition at line \fB462\fP of file \fBcm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t Argv::n"
allocated array elements 
.PP
Definition at line \fB465\fP of file \fBcm\&.h\fP\&.
.SS "\fBArg\fP** Argv::v"
pointer to an array of \fBArg\fP pointers, representing the argument vector 
.PP
Definition at line \fB463\fP of file \fBcm\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
