.TH "bug" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
.PP


.PP
.IP "\fBGlobal \fBMyLibrary::Example::test\fP (const std::string &test)
.IP "" 1c
example bug 

.PP
.IP "\fBGlobal \fBMyLibrary::SubclassExample< TemplatedClass >::virtualfunc\fP () override
.IP "" 1c
second bug 

.PP

