.TH "CCStr" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCStr \- complex character objectl with a pointer to the complex character string and its allocated length  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/cm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "cchar_t * \fBs\fP"
.br
.ti -1c
.RI "size_t \fBl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
complex character objectl with a pointer to the complex character string and its allocated length 


.PP
\fBNote\fP
.RS 4
The \fBCCStr\fP structure represents a complex character string, which is a string that can contain both regular characters and attributes (such as color, bold, etc\&.) in the ncurses library\&. This structure includes a pointer to the complex character string and its allocated length, allowing for dynamic handling of complex character strings in the terminal interface\&. 
.RE
.PP

.PP
Definition at line \fB491\fP of file \fBcm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t CCStr::l"
allocated length 
.PP
Definition at line \fB493\fP of file \fBcm\&.h\fP\&.
.SS "cchar_t* CCStr::s"
pointer to the complex character string 
.PP
Definition at line \fB492\fP of file \fBcm\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
