.TH "ChyronKey" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChyronKey
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/cm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBtext\fP [64]"
.br
.ti -1c
.RI "int \fBkeycode\fP"
.br
.ti -1c
.RI "int \fBend_pos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB116\fP of file \fBcm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int ChyronKey::end_pos"
end position of the command text in the chyron 
.PP
Definition at line \fB120\fP of file \fBcm\&.h\fP\&.
.PP
Referenced by \fBcompile_chyron()\fP, and \fBget_chyron_key()\fP\&.
.SS "int ChyronKey::keycode"
key code associated with the command 
.PP
Definition at line \fB119\fP of file \fBcm\&.h\fP\&.
.PP
Referenced by \fBget_chyron_key()\fP, and \fBset_chyron_key()\fP\&.
.SS "char ChyronKey::text[64]"
command text associated with the key code 
.PP
Definition at line \fB117\fP of file \fBcm\&.h\fP\&.
.PP
Referenced by \fBcompile_chyron()\fP, \fBis_set_chyron_key()\fP, \fBset_chyron_key()\fP, and \fBunset_chyron_key()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
