.TH "src/ckeys.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ckeys.c \- Test Curses Keys\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <common\&.h>\fP
.br
\fR#include <sys/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB__end_pgm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test Curses Keys\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBckeys\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
Entry point for Curses Keys test 
.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/enterchr\&.c\fP, \fB/usr/local/src/cmenu/src/enterstr\&.c\fP, and \fBstrings_test1\&.c\fP\&.
.PP
Definition at line \fB16\fP of file \fBckeys\&.c\fP\&.
.nf
16                                 {
17     __atexit;
18     int rc;
19     capture_shell_tioctl();
20     init = new_init(argc, argv);
21     if (!init) {
22         abend(\-1, "malloc failed init (Init)");
23     }
24     SIO *sio = init\->sio;
25     mapp_initialization(init, argc, argv);
26     open_curses(sio);
27     sig_prog_mode();
28     win_init_attrs(sio\->fg_color, sio\->bg_color, sio\->bo_color);
29     rc = display_curses_keys();
30     win_del();
31     destroy_curses();
32     return (rc);
33 }
.PP
.fi

.PP
References \fBabend()\fP, \fBcapture_shell_tioctl()\fP, \fBdestroy_curses()\fP, \fBdisplay_curses_keys()\fP, \fBinit\fP, \fBmapp_initialization()\fP, \fBnew_init()\fP, \fBopen_curses()\fP, \fBsig_prog_mode()\fP, \fBsio\fP, \fBwin_del()\fP, and \fBwin_init_attrs()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "__end_pgm"

.PP
Definition at line \fB13\fP of file \fBckeys\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
