.TH "ColorPair" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorPair
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/cm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfg\fP"
.br
.ti -1c
.RI "int \fBbg\fP"
.br
.ti -1c
.RI "int \fBpair_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBNote\fP
.RS 4
The \fBColorPair\fP structure is a simple structure that holds information about a color pair, including the foreground color index, background color index, and the color pair index\&. This structure can be used to manage and apply color pairs in the ncurses library, allowing for easy customization of the terminal's appearance\&. By using this structure, you can easily keep track of the different color pairs you have defined and apply them to various elements in your terminal interface\&. 
.RE
.PP

.PP
Definition at line \fB171\fP of file \fBcm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int ColorPair::bg"
background color index 
.PP
Definition at line \fB173\fP of file \fBcm\&.h\fP\&.
.SS "int ColorPair::fg"
foreground color index 
.PP
Definition at line \fB172\fP of file \fBcm\&.h\fP\&.
.SS "int ColorPair::pair_id"
color pair index 
.PP
Definition at line \fB174\fP of file \fBcm\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
