.TH "/srv/www/htdocs/C-Menu/doxygen-awesome-css/docs/customization.md" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/srv/www/htdocs/C-Menu/doxygen-awesome-css/docs/customization.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
