.TH "/srv/www/htdocs/C-Menu/doxygen-awesome-css/include/MyLibrary/example.hpp" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/srv/www/htdocs/C-Menu/doxygen-awesome-css/include/MyLibrary/example.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMyLibrary::Example\fP"
.br
.RI "\fBExample\fP class to demonstrate the features of the custom CSS\&. "
.ti -1c
.RI "class \fBMyLibrary::SecondExample\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMyLibrary\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMyLibrary::Color\fP { \fBMyLibrary::red\fP = 1, \fBMyLibrary::green\fP = 2, \fBMyLibrary::blue\fP = 3 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
