.TH "Field" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Field \- structure for form fields  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/form\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "int \fBcol\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "int \fBff\fP"
.br
.ti -1c
.RI "char \fBinput_s\fP [256]"
.br
.ti -1c
.RI "char \fBaccept_s\fP [256]"
.br
.ti -1c
.RI "char \fBdisplay_s\fP [256]"
.br
.ti -1c
.RI "char \fBfiller_s\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure for form fields 
.PP
Definition at line \fB114\fP of file \fBform\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char Field::accept_s[256]"
the accepted string for this field, used for storing the validated and accepted value for this field after processing the user's input during form processing 
.PP
Definition at line \fB128\fP of file \fBform\&.h\fP\&.
.SS "int Field::col"
the column number on the form window where this field should be displayed 
.PP
Definition at line \fB117\fP of file \fBform\&.h\fP\&.
.SS "char Field::display_s[256]"
the display string for this field, used for storing the formatted string that will be displayed in the field input area on the form window during form processing, based on the accepted value and the field format 
.PP
Definition at line \fB132\fP of file \fBform\&.h\fP\&.
.SS "int Field::ff"
the field format, represented as an integer corresponding to the \fBFieldFormat\fP enum values, e\&.g\&. FF_STRING, FF_DECIMAL_INT, etc\&. This is used for validating and formatting the field input values according to their specified formats\&. 
.PP
Definition at line \fB121\fP of file \fBform\&.h\fP\&.
.SS "char Field::filler_s[256]"
the filler string for this field, used for storing the string that will be used to fill the field input area on the form window during form processing, based on the field length and the fill character specified in the form structure 
.PP
Definition at line \fB137\fP of file \fBform\&.h\fP\&.
.SS "char Field::input_s[256]"
the input string for this field, used for storing the user's input value for this field during form processing 
.PP
Definition at line \fB125\fP of file \fBform\&.h\fP\&.
.SS "int Field::len"
the length of the field input area, used for display and formatting purposes 
.PP
Definition at line \fB119\fP of file \fBform\&.h\fP\&.
.SS "int Field::line"
the line number on the form window where this field should be displayed 
.PP
Definition at line \fB115\fP of file \fBform\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
