.TH "src/test/hex2dec.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/hex2dec.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line \fB4\fP of file \fBhex2dec\&.c\fP\&.
.nf
4                                 {
5     char hex[17];
6     unsigned long decimal;
7 
8     char address_s[17] = "0x5e9590";
9     unsigned long address = strtoul(address_s, NULL, 16);
10     printf("Start address: %s = %lu\\n\\n", address_s, address);
11     while (1) {
12         printf("hex: ");
13         scanf("%16s", hex);
14         decimal = strtoul(hex, NULL, 16);
15         printf("dec: %lu\\n\\n", decimal \- address);
16     }
17     return 0;
18 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
