.TH "src/test/iso8601.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/iso8601.c \- iso8601 Timestamp  

.SH SYNOPSIS
.br
.PP
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
iso8601 Timestamp 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBiso8601\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
This program prints the current time in ISO 8601 format\&. If the first argument is "-l", it prints the local time with the timezone offset\&. Otherwise, it prints the UTC time with a "Z" (Zulu) suffix\&. The output format is UTC "YYYY-MM-DDTHH:MM:SSZ", LOCAL "YYYY-MM-DDTHH:MM:SS±hhmm" 
.PP
Definition at line \fB19\fP of file \fBiso8601\&.c\fP\&.
.nf
19                                 {
20     char buf[100];
21     time_t now = time(NULL);
22     if (argc > 1 && argv[1][0] == '\-' && argv[1][1] == 'l' &&
23         argv[1][2] == '\\0') {
24         struct tm *t = localtime(&now);
25         strftime(buf, sizeof(buf), "%Y\-%m\-%dT%H:%M:%S%z", t);
26     } else {
27         struct tm *t = gmtime(&now);
28         strftime(buf, sizeof(buf), "%Y\-%m\-%dT%H:%M:%SZ", t);
29     }
30     printf("%s\\n", buf);
31     return 0;
32 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
