.TH "Line" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Line \- The \fBLine\fP strutures are attached to the \fBMenu\fP main structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/menu\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBtype\fP"
.br
.ti -1c
.RI "char * \fBraw_text\fP"
.br
.ti -1c
.RI "char * \fBchoice_text\fP"
.br
.ti -1c
.RI "char \fBchoice_letter\fP"
.br
.ti -1c
.RI "int \fBletter_pos\fP"
.br
.ti -1c
.RI "unsigned int \fBcommand_type\fP"
.br
.ti -1c
.RI "char * \fBcommand_str\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBLine\fP strutures are attached to the \fBMenu\fP main structure\&. 
.PP
Definition at line \fB55\fP of file \fBmenu\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char Line::choice_letter"
The letter that the user can press to select this menu line, if it is a choice line, used for selection purposes 
.PP
Definition at line \fB64\fP of file \fBmenu\&.h\fP\&.
.PP
Referenced by \fBfree_menu_line()\fP\&.
.SS "char* Line::choice_text"
The formatted text of the menu line, after processing any variables and formatting, used for display purposes 
.PP
Definition at line \fB61\fP of file \fBmenu\&.h\fP\&.
.PP
Referenced by \fBfree_menu_line()\fP\&.
.SS "char* Line::command_str"
The command string associated with this menu line, which may be a command to execute, a menu to display, a form to show, etc\&., depending on the command type, used to determine the specific action to take when this menu line is selected 
.PP
Definition at line \fB77\fP of file \fBmenu\&.h\fP\&.
.PP
Referenced by \fBfree_menu_line()\fP\&.
.SS "unsigned int Line::command_type"
The type of command associated with this menu line, e\&.g\&. CT_RETURNMAIN for a command that returns to the main menu, CT_EXEC for a command that executes a program, CT_HELP for a command that displays help information, etc\&., used to determine what action to take when this menu line is selected 
.PP
Definition at line \fB71\fP of file \fBmenu\&.h\fP\&.
.PP
Referenced by \fBfree_menu_line()\fP\&.
.SS "int Line::letter_pos"
The position of the choice letter in the text, for highlighting purposes, used to determine where to highlight the choice letter in the menu display 
.PP
Definition at line \fB67\fP of file \fBmenu\&.h\fP\&.
.PP
Referenced by \fBfree_menu_line()\fP\&.
.SS "char* Line::raw_text"
The raw text of the menu line, as read from the menu description file, before processing any variables or formatting 
.PP
Definition at line \fB58\fP of file \fBmenu\&.h\fP\&.
.PP
Referenced by \fBfree_menu_line()\fP\&.
.SS "unsigned int Line::type"
The type of menu line, e\&.g\&. MT_TEXT for a text line, MT_CHOICE for a choice line 
.PP
Definition at line \fB56\fP of file \fBmenu\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
