.TH "menuapp/msrc/main.h" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menuapp/msrc/main.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Applications Available on your system Communications For connecting to other systems Application Developer A Tutorial System Services \fBFormat\fP"
.br
.ti -1c
.RI "Applications Available on your system Communications For connecting to other systems Application Developer A Tutorial System Services \fBBackup\fP"
.br
.ti -1c
.RI "Applications Available on your system Communications For connecting to other systems Application Developer A Tutorial System Services \fBRestore\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Applications Available on your system Communications For connecting to other systems Application Developer A Tutorial System Services Backup"

.PP
Definition at line \fB4\fP of file \fBmain\&.h\fP\&.
.SS "Applications Available on your system Communications For connecting to other systems Application Developer A Tutorial System Services Format"

.PP
Definition at line \fB3\fP of file \fBmain\&.h\fP\&.
.SS "Applications Available on your system Communications For connecting to other systems Application Developer A Tutorial System Services Restore"

.PP
Definition at line \fB4\fP of file \fBmain\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
