.TH "md_API" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_API \- API 
.PP

.SH "Introduction"
.PP
The C-Menu API is a set of functions and tools that allow developers to extend the capabilities of C-Menu and develop custom applications that integrate with C-Menu\&.

.PP

.PP
The C-Menu API documentation is available in Neovim\&. As you are typing the function name, a list of matching signatures appears along with a brief description of each function and its parameters\&. This makes it easier to to use the API without having to leave your coding environment\&. You can select the one you want with the arrow keys and press Enter to insert it into your code\&. You can also hover over a function and press Shift-K to view the full documentation in a pop-up window\&.

.PP
\fB\fINOTE:\fP\fP Requires Neovim properly configured with support for LSP and a plugin that provides LSP functionality, such as nvim-lspconfig\&.

.PP
================ \fB\fIINCOMPLETE\fP\fP ================ 
