.TH "md_nvim_2init_8lua" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_nvim_2init_8lua \- init\&.lua 
.PP
 To use custom_highlights\&.lua, you can copy it to your nvim config directory:

.PP
For example, if your nvim config directory is located at ~/\&.config/nvim, you can run the following command:

.PP
.PP
.nf
cp custom_highlights\&.lua ~/\&.config/nvim/lua/config
.fi
.PP

.PP
and add the following line to your init\&.lua file:

.PP
.PP
.nf
require("config\&.custom_highlights")
.fi
.PP
 
