.TH "src/mem.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mem.c \- Create and destroy main data structures for C-Menu\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <common\&.h>\fP
.br
\fR#include <errno\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "Init * \fBnew_init\fP (int argc, char **argv)"
.br
.RI "Create and initialize Init structure\&. "
.ti -1c
.RI "Menu * \fBnew_menu\fP (Init *\fBinit\fP, int argc, char **argv, int begy, int begx)"
.br
.RI "Create and initialize Menu structure\&. "
.ti -1c
.RI "Pick * \fBnew_pick\fP (Init *\fBinit\fP, int argc, char **argv, int begy, int begx)"
.br
.RI "Create and initialize Pick structure\&. "
.ti -1c
.RI "Form * \fBnew_form\fP (Init *\fBinit\fP, int argc, char **argv, int begy, int begx)"
.br
.RI "Create and initialize Form structure\&. "
.ti -1c
.RI "View * \fBnew_view\fP (Init *\fBinit\fP, int argc, char **argv)"
.br
.RI "Create and initialize View structure\&. "
.ti -1c
.RI "View * \fBdestroy_view\fP (Init *\fBinit\fP)"
.br
.RI "Destroy View structure\&. "
.ti -1c
.RI "Form * \fBdestroy_form\fP (Init *\fBinit\fP)"
.br
.RI "Destroy Form structure\&. "
.ti -1c
.RI "Pick * \fBdestroy_pick\fP (Init *\fBinit\fP)"
.br
.RI "Destroy Pick structure\&. "
.ti -1c
.RI "Menu * \fBdestroy_menu\fP (Init *\fBinit\fP)"
.br
.RI "Destroy Menu structure\&. "
.ti -1c
.RI "Init * \fBdestroy_init\fP (Init *\fBinit\fP)"
.br
.RI "Destroy Init structure\&. "
.ti -1c
.RI "bool \fBinit_menu_files\fP (Init *\fBinit\fP, int argc, char **argv)"
.br
.RI "Initialize Menu file specifications\&. "
.ti -1c
.RI "bool \fBinit_pick_files\fP (Init *\fBinit\fP, int argc, char **argv)"
.br
.RI "Initialize Pick file specifications\&. "
.ti -1c
.RI "bool \fBinit_form_files\fP (Init *\fBinit\fP, int argc, char **argv)"
.br
.RI "Initialize Form file specifications\&. "
.ti -1c
.RI "bool \fBinit_view_files\fP (Init *\fBinit\fP)"
.br
.RI "Initialize Pick file specifications\&. "
.ti -1c
.RI "bool \fBverify_spec_arg\fP (char *spec, char *org_spec, char *dir, char *alt_dir, int mode)"
.br
.RI "Verify file specification argument\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBinit_cnt\fP = 0"
.br
.ti -1c
.RI "Menu * \fBmenu\fP"
.br
.ti -1c
.RI "Pick * \fBpick\fP"
.br
.ti -1c
.RI "Form * \fBform\fP"
.br
.ti -1c
.RI "View * \fBview\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Create and destroy main data structures for C-Menu\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBmem\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "Form * destroy_form (Init * init)"

.PP
Destroy Form structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.RE
.PP
\fBReturns\fP
.RS 4
nullptr 
.RE
.PP

.PP
Definition at line \fB255\fP of file \fBmem\&.c\fP\&.
.nf
255                                {
256     int i;
257 
258     if (!init\->form)
259         return nullptr;
260     for (i = 0; i < init\->form\->fidx; i++) {
261         if (init\->form\->field[i])
262             free(init\->form\->field[i]);
263         init\->form\->field[i] = nullptr;
264     }
265     for (i = 0; i < init\->form\->didx; i++) {
266         if (init\->form\->text[i])
267             free(init\->form\->text[i]);
268         init\->form\->text[i] = nullptr;
269     }
270     free(init\->form);
271     init\->form = nullptr;
272     init\->form_cnt\-\-;
273     return init\->form;
274 }
.PP
.fi

.PP
References \fBinit\fP\&.
.PP
Referenced by \fBdestroy_init()\fP, \fBenter_file_spec()\fP, \fBform_engine()\fP, and \fBinit_form()\fP\&.
.SS "Init * destroy_init (Init * init)"

.PP
Destroy Init structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.RE
.PP
\fBReturns\fP
.RS 4
nullptr 
.RE
.PP

.PP
Definition at line \fB93\fP of file \fBmem\&.c\fP\&.
.nf
93                                {
94     int i;
95     if (!init)
96         return nullptr;
97     if (init\->sio) {
98         free(init\->sio);
99         init\->sio = nullptr;
100     }
101     if (init\->menu) {
102         init\->menu = destroy_menu(init);
103         init\->menu = nullptr;
104     }
105     if (init\->view) {
106         init\->view = destroy_view(init);
107         init\->view = nullptr;
108     }
109     if (init\->form) {
110         init\->form = destroy_form(init);
111         init\->form = nullptr;
112     }
113     if (init\->pick) {
114         init\->pick = destroy_pick(init);
115         init\->pick = nullptr;
116     }
117     for (i = 0; i <= init\->argc; i++) {
118         if (init\->argv[i]) {
119             if (init\->argv[i] != nullptr)
120                 free(init\->argv[i]);
121             init\->argv[i] = nullptr;
122         }
123     }
124     if (init\->argv) {
125         if (init\->argv != nullptr)
126             free(init\->argv);
127         init\->argv = nullptr;
128     }
129     if (init != nullptr) {
130         free(init);
131         init = nullptr;
132     }
133     init_cnt\-\-;
134     return init;
135 }
.PP
.fi

.PP
References \fBdestroy_form()\fP, \fBdestroy_menu()\fP, \fBdestroy_pick()\fP, \fBdestroy_view()\fP, \fBinit\fP, and \fBinit_cnt\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "Menu * destroy_menu (Init * init)"

.PP
Destroy Menu structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.RE
.PP
\fBReturns\fP
.RS 4
nullptr 
.RE
.PP

.PP
Definition at line \fB165\fP of file \fBmem\&.c\fP\&.
.nf
165                                {
166     if (!init\->menu)
167         return (nullptr);
168     free(init\->menu);
169     init\->menu = nullptr;
170     init\->menu_cnt\-\-;
171     return init\->menu;
172 }
.PP
.fi

.PP
References \fBinit\fP\&.
.PP
Referenced by \fBdestroy_init()\fP, and \fBmenu_cmd_processor()\fP\&.
.SS "Pick * destroy_pick (Init * init)"

.PP
Destroy Pick structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.RE
.PP
\fBReturns\fP
.RS 4
nullptr 
.RE
.PP

.PP
Definition at line \fB211\fP of file \fBmem\&.c\fP\&.
.nf
211                                {
212     if (!init\->pick)
213         return nullptr;
214 
215     for (pick\->obj_idx = 0; pick\->obj_idx < pick\->obj_cnt; pick\->obj_idx++)
216         if (pick\->object[pick\->obj_idx] != nullptr)
217             free(pick\->object[pick\->obj_idx]);
218     free(pick\->object);
219     free(pick);
220     init\->pick = nullptr;
221     init\->pick_cnt\-\-;
222     return init\->pick;
223 }
.PP
.fi

.PP
References \fBinit\fP, and \fBpick\fP\&.
.PP
Referenced by \fBdestroy_init()\fP, and \fBinit_pick()\fP\&.
.SS "View * destroy_view (Init * init)"

.PP
Destroy View structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.RE
.PP
\fBReturns\fP
.RS 4
nullptr 
.RE
.PP

.PP
Definition at line \fB326\fP of file \fBmem\&.c\fP\&.
.nf
326                                {
327     int i;
328     view = init\->view;
329     for (i = 0; i <= view\->argc; i++)
330         free(view\->argv[i]);
331     free(view\->argv);
332     free(view);
333     init\->view = nullptr;
334     view = nullptr;
335     init\->view_cnt\-\-;
336     return init\->view;
337 }
.PP
.fi

.PP
References \fBinit\fP, and \fBview\fP\&.
.PP
Referenced by \fBdestroy_init()\fP, and \fBmview()\fP\&.
.SS "bool init_form_files (Init * init, int argc, char ** argv)"

.PP
Initialize Form file specifications\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP pointer to init structure 
.br
\fIargc\fP - number of arguments in argv 
.br
\fIargv\fP - Arguments may have been provided by command line ~/\&.minitrc, environment variables, or calling program interal to C-Menu 
.RE
.PP
\fBNote\fP
.RS 4
Positional args: [pick desc], [in_file], [out_file], [help_file] 
.RE
.PP

.PP
Definition at line \fB611\fP of file \fBmem\&.c\fP\&.
.nf
611                                                         {
612     char tmp_str[MAXLEN];
613     form\->f_mapp_spec =
614         verify_spec_arg(form\->mapp_spec, init\->mapp_spec, init\->mapp_msrc,
615                         "~/menuapp/msrc", R_OK);
616     form\->f_in_spec = verify_spec_arg(form\->in_spec, init\->in_spec,
617                                       init\->mapp_data, "~/menuapp/data", R_OK);
618     form\->f_out_spec =
619         verify_spec_arg(form\->out_spec, init\->out_spec, init\->mapp_data,
620                         "~/menuapp/data", W_OK | S_QUIET);
621     if (init\->provider_cmd[0] != '\\0') {
622         form\->f_provider_cmd =
623             verify_spec_arg(form\->provider_cmd, init\->provider_cmd,
624                             "~/menuapp/bin", "$PATH", X_OK | S_QUIET);
625     }
626     if (init\->cmd[0] != '\\0') {
627         form\->f_cmd = verify_spec_arg(form\->cmd, init\->cmd, "~/menuapp/bin",
628                                       "$PATH", X_OK | S_QUIET);
629     }
630     if (init\->receiver_cmd[0] != '\\0') {
631         form\->f_receiver_cmd =
632             verify_spec_arg(form\->receiver_cmd, init\->receiver_cmd,
633                             "~/menuapp/bin", "$PATH", X_OK | S_QUIET);
634     }
635     form\->f_help_spec =
636         verify_spec_arg(form\->help_spec, init\->help_spec, init\->mapp_help,
637                         "~/menuapp/help", R_OK);
638     if (optind < argc && !form\->f_mapp_spec) {
639         form\->f_mapp_spec =
640             verify_spec_arg(form\->mapp_spec, argv[optind], init\->mapp_msrc,
641                             "~/menuapp/msrc", R_OK);
642         if (form\->f_mapp_spec)
643             optind++;
644     }
645     if (optind < argc && !form\->f_in_spec) {
646         form\->f_in_spec =
647             verify_spec_arg(form\->in_spec, argv[optind], init\->mapp_data,
648                             "~/menuapp/data", R_OK);
649         if (form\->f_in_spec)
650             optind++;
651     }
652     if (optind < argc && !form\->f_out_spec) {
653         form\->f_out_spec =
654             verify_spec_arg(form\->out_spec, argv[optind], init\->mapp_data,
655                             "~/menuapp/data", W_OK | S_QUIET);
656         if (form\->f_out_spec)
657             optind++;
658     }
659     if (optind < argc && !form\->f_provider_cmd) {
660         if (argv[optind][0] != '\\0') {
661             form\->f_provider_cmd =
662                 verify_spec_arg(form\->provider_cmd, argv[optind],
663                                 "~/menuapp/bin", nullptr, X_OK | S_QUIET);
664             if (!form\->f_provider_cmd) {
665                 base_name(tmp_str, argv[optind]);
666                 form\->f_provider_cmd =
667                     locate_file_in_path(form\->provider_cmd, tmp_str);
668             }
669         }
670         optind++;
671     }
672     if (optind < argc && !form\->f_cmd) {
673         if (argv[optind][0] != '\\0') {
674             form\->f_cmd =
675                 verify_spec_arg(form\->cmd, argv[optind], "~/menuapp/bin",
676                                 nullptr, X_OK | S_QUIET);
677             if (!form\->f_cmd) {
678                 base_name(tmp_str, argv[optind]);
679                 form\->f_cmd = locate_file_in_path(form\->cmd, tmp_str);
680             }
681         }
682         optind++;
683     }
684     if (optind < argc && !form\->f_receiver_cmd) {
685         if (argv[optind][0] != '\\0') {
686             form\->f_receiver_cmd =
687                 verify_spec_arg(form\->receiver_cmd, argv[optind],
688                                 "~/menuapp/bin", nullptr, X_OK | S_QUIET);
689             if (!form\->f_receiver_cmd) {
690                 base_name(tmp_str, argv[optind]);
691                 form\->f_receiver_cmd =
692                     locate_file_in_path(form\->receiver_cmd, tmp_str);
693             }
694         }
695         optind++;
696     }
697     if (optind < argc && !form\->f_help_spec) {
698         form\->f_help_spec =
699             verify_spec_arg(form\->help_spec, init\->help_spec, init\->mapp_help,
700                             "~/menuapp/help", R_OK);
701         if (form\->f_help_spec)
702             optind++;
703     }
704     form\->f_stop_on_error = init\->f_stop_on_error;
705     form\->f_erase_remainder = init\->f_erase_remainder;
706     if (form\->title[0] == '\\0' && init\->title[0] != '\\0') {
707         strip_quotes(init\->title);
708         strnz__cpy(form\->title, init\->title, MAXLEN \- 1);
709     }
710     return true;
711 }
.PP
.fi

.PP
References \fBbase_name()\fP, \fBform\fP, \fBinit\fP, \fBlocate_file_in_path()\fP, \fBMAXLEN\fP, \fBstrip_quotes()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBverify_spec_arg()\fP\&.
.PP
Referenced by \fBnew_form()\fP\&.
.SS "bool init_menu_files (Init * init, int argc, char ** argv)"

.PP
Initialize Menu file specifications\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.br
\fIargc\fP - number of arguments in argv 
.br
\fIargv\fP - Arguments may have been provided by command line, ~/\&.minitrc, environment variables, or calling program interal to C-Menu 
.RE
.PP
\fBNote\fP
.RS 4
Positional args: [menu desc], [help file] 
.RE
.PP

.PP
Definition at line \fB461\fP of file \fBmem\&.c\fP\&.
.nf
461                                                         {
462     char tmp_str[MAXLEN];
463     // menu\->f_mapp_spec =
464     //     verify_spec_arg(menu\->mapp_spec, init\->mapp_spec, init\->mapp_msrc,
465     //                     "~/menuapp/msrc", R_OK);
466     // menu\->f_help_spec =
467     //     verify_spec_arg(menu\->help_spec, init\->help_spec, init\->mapp_help,
468     //                     "~/menuapp/help", R_OK);
469     if (optind < argc && !init\->f_mapp_spec) {
470         menu\->f_mapp_spec =
471             verify_spec_arg(menu\->mapp_spec, argv[optind], init\->mapp_msrc,
472                             "~/menuapp/msrc", R_OK);
473         if (menu\->f_mapp_spec)
474             optind++;
475     }
476     if (optind < argc && !menu\->f_help_spec) {
477         menu\->f_help_spec =
478             verify_spec_arg(menu\->help_spec, argv[optind], init\->mapp_help,
479                             "~/menuapp/help", R_OK);
480         if (menu\->f_help_spec)
481             optind++;
482     }
483     if (!menu\->f_mapp_spec) {
484         menu\->f_mapp_spec = verify_spec_arg(
485             menu\->mapp_spec, "~/menuapp/msrc/main\&.m", nullptr, nullptr, R_OK);
486         if (!menu\->f_mapp_spec) {
487             strnz__cpy(tmp_str, "menu cannot read description file ",
488                        MAXLEN \- 1);
489             strnz__cat(tmp_str, menu\->mapp_spec, MAXLEN \- 1);
490             abend(\-1, tmp_str);
491         }
492     }
493     if (!menu\->f_help_spec) {
494         menu\->f_help_spec =
495             verify_spec_arg(menu\->help_spec, "~/menuapp/help/main\&.help",
496                             nullptr, nullptr, R_OK);
497         if (!menu\->f_help_spec) {
498             strnz__cpy(tmp_str, "menu cannot read help file ", MAXLEN \- 1);
499             strnz__cat(tmp_str, menu\->help_spec, MAXLEN \- 1);
500             abend(\-1, tmp_str);
501         }
502     }
503     menu\->f_stop_on_error = init\->f_stop_on_error;
504     return true;
505 }
.PP
.fi

.PP
References \fBabend()\fP, \fBinit\fP, \fBMAXLEN\fP, \fBmenu\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBverify_spec_arg()\fP\&.
.PP
Referenced by \fBnew_menu()\fP\&.
.SS "bool init_pick_files (Init * init, int argc, char ** argv)"

.PP
Initialize Pick file specifications\&. Initialize file specifications 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.br
\fIargc\fP - number of arguments in argv 
.br
\fIargv\fP - Arguments may have been provided by command line, ~/\&.minitrc, environment variables, or calling program interal to C-Menu 
.RE
.PP
\fBNote\fP
.RS 4
Positional args: [pick desc], [in_file], [out_file], [help_file] 
.RE
.PP

.PP
Definition at line \fB515\fP of file \fBmem\&.c\fP\&.
.nf
515                                                         {
516     char tmp_str[MAXLEN];
517     pick\->f_in_spec = verify_spec_arg(pick\->in_spec, init\->in_spec,
518                                       init\->mapp_data, "~/menuapp/data", R_OK);
519     pick\->f_out_spec =
520         verify_spec_arg(pick\->out_spec, init\->out_spec, init\->mapp_data,
521                         "~/menuapp/data", W_OK | S_QUIET);
522     if (init\->provider_cmd[0] != '\\0') {
523         pick\->f_provider_cmd =
524             verify_spec_arg(pick\->provider_cmd, init\->provider_cmd,
525                             "~/menuapp/bin", "$PATH", X_OK | S_QUIET);
526     }
527     if (init\->cmd[0] != '\\0') {
528         pick\->f_cmd = verify_spec_arg(pick\->cmd, init\->cmd, "~/menuapp/bin",
529                                       "$PATH", X_OK | S_QUIET);
530     }
531     if (init\->receiver_cmd[0] != '\\0') {
532         pick\->f_receiver_cmd =
533             verify_spec_arg(pick\->receiver_cmd, init\->receiver_cmd,
534                             "~/menuapp/bin", "$PATH", X_OK | S_QUIET);
535     }
536     if (init\->title[0])
537         strnz__cpy(pick\->title, init\->title, MAXLEN \- 1);
538     pick\->f_help_spec =
539         verify_spec_arg(pick\->help_spec, init\->help_spec, init\->mapp_help,
540                         "~/menuapp/help", R_OK);
541     if (optind < argc && !pick\->f_in_spec) {
542         pick\->f_in_spec =
543             verify_spec_arg(pick\->in_spec, argv[optind], init\->mapp_data,
544                             "~/menuapp/data", R_OK);
545         if (pick\->f_in_spec)
546             optind++;
547     }
548     if (optind < argc && !pick\->f_out_spec) {
549         pick\->f_out_spec =
550             verify_spec_arg(pick\->out_spec, argv[optind], init\->mapp_data,
551                             "~/menuapp/data", W_OK | S_QUIET);
552         if (pick\->f_out_spec)
553             optind++;
554     }
555     if (optind < argc && !pick\->f_provider_cmd) {
556         if (argv[optind][0] != '\\0') {
557             pick\->f_provider_cmd =
558                 verify_spec_arg(pick\->provider_cmd, argv[optind],
559                                 "~/menuapp/bin", nullptr, X_OK | S_QUIET);
560             if (!pick\->f_provider_cmd) {
561                 base_name(tmp_str, argv[optind]);
562                 pick\->f_provider_cmd =
563                     locate_file_in_path(pick\->provider_cmd, tmp_str);
564             }
565         }
566         optind++;
567     }
568     if (optind < argc && !pick\->f_cmd) {
569         if (argv[optind][0] != '\\0') {
570             pick\->f_cmd =
571                 verify_spec_arg(pick\->cmd, argv[optind], "~/menuapp/bin",
572                                 nullptr, X_OK | S_QUIET);
573             if (!pick\->f_cmd) {
574                 base_name(tmp_str, argv[optind]);
575                 pick\->f_cmd = locate_file_in_path(pick\->cmd, tmp_str);
576             }
577         }
578         optind++;
579     }
580     if (optind < argc && !pick\->f_receiver_cmd) {
581         if (argv[optind][0] != '\\0') {
582             pick\->f_receiver_cmd =
583                 verify_spec_arg(pick\->receiver_cmd, argv[optind],
584                                 "~/menuapp/bin", nullptr, X_OK | S_QUIET);
585             if (!pick\->f_receiver_cmd) {
586                 base_name(tmp_str, argv[optind]);
587                 pick\->f_receiver_cmd =
588                     locate_file_in_path(pick\->receiver_cmd, tmp_str);
589             }
590         }
591         optind++;
592     }
593     if (optind < argc && !pick\->f_help_spec) {
594         pick\->f_help_spec =
595             verify_spec_arg(pick\->help_spec, argv[optind], init\->mapp_help,
596                             "~/menuapp/help", R_OK);
597         if (pick\->f_help_spec)
598             optind++;
599     }
600     pick\->select_max = init\->select_max;
601     pick\->f_stop_on_error = init\->f_stop_on_error;
602     pick\->f_multiple_cmd_args = init\->f_multiple_cmd_args;
603     return true;
604 }
.PP
.fi

.PP
References \fBbase_name()\fP, \fBinit\fP, \fBlocate_file_in_path()\fP, \fBMAXLEN\fP, \fBpick\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBverify_spec_arg()\fP\&.
.PP
Referenced by \fBnew_pick()\fP\&.
.SS "bool init_view_files (Init * init)"

.PP
Initialize Pick file specifications\&. Initialize file specifications 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.RE
.PP
\fBNote\fP
.RS 4
Positional args: pick desc, in_file, out_file, help_file 
.RE
.PP

.PP
Definition at line \fB716\fP of file \fBmem\&.c\fP\&.
.nf
716                                  {
717     view = init\->view;
718     view\->lines = init\->lines;
719     view\->cols = init\->cols;
720     view\->f_stop_on_error = init\->f_stop_on_error;
721     view\->f_ignore_case = init\->f_ignore_case;
722     view\->f_at_end_clear = init\->f_at_end_clear;
723     view\->f_at_end_remove = init\->f_at_end_remove;
724     view\->f_squeeze = init\->f_squeeze;
725     strnz__cpy(view\->provider_cmd, init\->provider_cmd, MAXLEN \- 1);
726     strnz__cpy(view\->receiver_cmd, init\->receiver_cmd, MAXLEN \- 1);
727     strnz__cpy(view\->cmd_all, init\->cmd_all, MAXLEN \- 1);
728     if (view\->title[0] == '\\0') {
729         if (init\->title[0] != '\\0') {
730             strnz__cpy(view\->title, init\->title, MAXLEN \- 1);
731         } else {
732             if (view\->provider_cmd[0] != '\\0')
733                 strnz__cpy(view\->title, view\->provider_cmd, MAXLEN \- 1);
734             else {
735                 if (view\->argv[0] != nullptr && view\->argv[0][0] != '\\0')
736                     strnz__cpy(view\->title, view\->argv[0], MAXLEN \- 1);
737                 else
738                     strnz__cpy(view\->title, "C\-Menu View", MAXLEN \- 1);
739             }
740         }
741     }
742     strip_quotes(view\->title);
743     if (view\->tab_stop == 0)
744         view\->tab_stop = 4;
745     return true;
746 }
.PP
.fi

.PP
References \fBinit\fP, \fBMAXLEN\fP, \fBstrip_quotes()\fP, \fBstrnz__cpy()\fP, and \fBview\fP\&.
.PP
Referenced by \fBnew_view()\fP\&.
.SS "Form * new_form (Init * init, int argc, char ** argv, int begy, int begx)"

.PP
Create and initialize Form structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.br
\fIargc\fP - number of arguments in argv 
.br
\fIargv\fP - Arguments may have been provided by command line, ~/\&.minitrc, environment variables, or calling program interal to C-Menu 
.br
\fIbegy,begx\fP - initial position of form window 
.RE
.PP

.PP
Definition at line \fB233\fP of file \fBmem\&.c\fP\&.
.nf
233                                                                       {
234     init\->form = (Form *)calloc(1, sizeof(Form));
235     if (!init\->form) {
236         abend(\-1, "calloc form failed");
237         return nullptr;
238     }
239     init\->form_cnt++;
240     form = init\->form;
241     if (!init_form_files(init, argc, argv)) {
242         abend(\-1, "init_form_files failed");
243         return nullptr;
244     }
245     strnz__cpy(form\->brackets, init\->brackets, 3);
246     strnz__cpy(form\->fill_char, init\->fill_char, MAXLEN \- 1);
247     form\->begy = begy;
248     form\->begx = begx;
249     return init\->form;
250 }
.PP
.fi

.PP
References \fBabend()\fP, \fBform\fP, \fBinit\fP, \fBinit_form_files()\fP, \fBMAXLEN\fP, and \fBstrnz__cpy()\fP\&.
.PP
Referenced by \fBinit_form()\fP\&.
.SS "Init * new_init (int argc, char ** argv)"

.PP
Create and initialize Init structure\&. 
.PP
\fBNote\fP
.RS 4
calloc initializes all fields to zero/nullptr 
.RE
.PP
\fBParameters\fP
.RS 4
\fIargc,argv\fP - arguments idiomatic directory usage: 
.PP
.nf
init\->mapp_msrc  description files
init\->mapp_help  help files
init\->mapp_data  in, out, data files
init\->mapp_user  executable scripts
init\->mapp_bin   binary executables

.fi
.PP
 
.RE
.PP
\fBNote\fP
.RS 4
Initialize file specifications in priority order: 
.PP
.nf
1 \- Default values
2 \- Configuration file
3 \- Environment variables
4 \- Command line positional arguments
5 \- Command line option arguments

.fi
.PP
 
.RE
.PP

.PP
Definition at line \fB57\fP of file \fBmem\&.c\fP\&.
.nf
57                                       {
58     int i = 0;
59     Init *init = calloc(1, sizeof(Init));
60     if (init == nullptr) {
61         abend(\-1, "calloc init failed");
62         return nullptr;
63     }
64     init\->argv = calloc(MAXARGS + 1, sizeof(char *));
65     if (init\->argv == nullptr) {
66         free(init);
67         ssnprintf(em0, MAXLEN \- 1, "%s, line: %d, errno: %d", __FILE__,
68                   __LINE__ \- 4, errno);
69         ssnprintf(em1, MAXLEN \- 1, "%s", strerror(errno));
70         ssnprintf(em2, MAXLEN \- 1, "view\->argv = calloc(%d, %d) failed\\n",
71                   (MAXARGS + 1), sizeof(char *));
72         display_error(em0, em1, em2, nullptr);
73         abend(\-1, "calloc init\->argv failed");
74         return nullptr;
75     }
76     init\->argc = argc;
77     for (i = 0; i < init\->argc; i++) {
78         init\->argv[i] = strdup(argv[i]);
79     }
80     init\->argv[i] = nullptr;
81     init\->sio = (SIO *)calloc(1, sizeof(SIO));
82     if (!init\->sio) {
83         abend(\-1, "calloc sio failed");
84         return nullptr;
85     }
86     init_cnt++;
87     return init;
88 }
.PP
.fi

.PP
References \fBabend()\fP, \fBdisplay_error()\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBinit\fP, \fBinit_cnt\fP, \fBMAXLEN\fP, and \fBssnprintf()\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "Menu * new_menu (Init * init, int argc, char ** argv, int begy, int begx)"

.PP
Create and initialize Menu structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.br
\fIargc\fP - number of arguments in argv 
.br
\fIargv\fP - Arguments may have been provided by command line, ~/\&.minitrc, environment variables, or calling program interal to C-Menu 
.br
\fIbegy,begx\fP - initial position of menu window 
.RE
.PP

.PP
Definition at line \fB145\fP of file \fBmem\&.c\fP\&.
.nf
145                                                                       {
146     init\->menu = (Menu *)calloc(1, sizeof(Menu));
147     if (!init\->menu) {
148         abend(\-1, "calloc menu failed");
149         return nullptr;
150     }
151     init\->menu_cnt++;
152     menu = init\->menu;
153     if (!init_menu_files(init, argc, argv)) {
154         abend(\-1, "init_menu_files failed");
155         return nullptr;
156     }
157     menu\->begy = begy;
158     menu\->begx = begx;
159     return init\->menu;
160 }
.PP
.fi

.PP
References \fBabend()\fP, \fBinit\fP, \fBinit_menu_files()\fP, and \fBmenu\fP\&.
.PP
Referenced by \fBmain()\fP, and \fBmenu_cmd_processor()\fP\&.
.SS "Pick * new_pick (Init * init, int argc, char ** argv, int begy, int begx)"

.PP
Create and initialize Pick structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.br
\fIargc\fP - number of arguments in argv 
.br
\fIargv\fP - Arguments may have been provided by command line, ~/\&.minitrc, environment variables, or calling program interal to C-Menu 
.br
\fIbegy,begx\fP - initial position of pick window 
.RE
.PP

.PP
Definition at line \fB182\fP of file \fBmem\&.c\fP\&.
.nf
182                                                                       {
183     init\->pick = (Pick *)calloc(1, sizeof(Pick));
184     if (!init\->pick) {
185         Perror("calloc pick failed");
186         return nullptr;
187     }
188     init\->pick_cnt++;
189     pick = init\->pick;
190     if (!init_pick_files(init, argc, argv)) {
191         abend(\-1, "init_pick_files failed");
192         return nullptr;
193     }
194     pick\->object = calloc(OBJ_MAXCNT + 1, sizeof(char *));
195     if (pick\->object == nullptr) {
196         ssnprintf(em0, MAXLEN \- 1, "%s, line: %d", __FILE__, __LINE__ \- 1);
197         ssnprintf(em1, MAXLEN \- 1,
198                   "calloc pick\->object = calloc(%d, %d) failed\\n",
199                   OBJ_MAXCNT + 1, sizeof(char *));
200         display_error(em0, em1, nullptr, nullptr);
201         abend(\-1, "User terminated program");
202     }
203     pick\->begy = begy;
204     pick\->begx = begx;
205     return init\->pick;
206 }
.PP
.fi

.PP
References \fBabend()\fP, \fBdisplay_error()\fP, \fBem0\fP, \fBem1\fP, \fBinit\fP, \fBinit_pick_files()\fP, \fBMAXLEN\fP, \fBPerror()\fP, \fBpick\fP, and \fBssnprintf()\fP\&.
.PP
Referenced by \fBinit_pick()\fP\&.
.SS "View * new_view (Init * init, int argc, char ** argv)"

.PP
Create and initialize View structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP structure 
.br
\fIargc\fP - number of arguments in argv 
.br
\fIargv\fP - Arguments may have been provided by command line, ~/\&.minitrc, environment variables, or calling program interal to C-Menu 
.RE
.PP

.PP
Definition at line \fB283\fP of file \fBmem\&.c\fP\&.
.nf
283                                                   {
284     init\->view_cnt++;
285     init\->view = (View *)calloc(1, sizeof(View));
286     if (!init\->view) {
287         free(init\->view);
288         ssnprintf(em0, MAXLEN \- 1, "%s, line: %d, errno: %d", __FILE__,
289                   __LINE__ \- 1, errno);
290         ssnprintf(em1, MAXLEN \- 1, "%s", strerror(errno));
291         ssnprintf(em2, MAXLEN \- 1, "init\->view = calloc(%d, %d) failed\\n",
292                   (argc \- optind + 1), sizeof(char *));
293         display_error(em0, em1, em2, nullptr);
294         abend(\-1, "calloc init\->view failed");
295         return false;
296     }
297     view = init\->view;
298     view\->argv = calloc((argc \- optind + 1), sizeof(char *));
299     if (view\->argv == nullptr) {
300         free(view\->argv);
301         ssnprintf(em0, MAXLEN \- 1, "%s, line: %d, errno: %d", __FILE__,
302                   __LINE__ \- 1, errno);
303         ssnprintf(em1, MAXLEN \- 1, "%s", strerror(errno));
304         ssnprintf(em2, MAXLEN \- 1, "view\->argv = calloc(%d, %d) failed\\n",
305                   (argc \- optind + 1), sizeof(char *));
306         display_error(em0, em1, em2, nullptr);
307         abend(\-1, "User terminated program");
308         return false;
309     }
310     int s = optind;
311     int d = 0;
312     while (s < argc)
313         view\->argv[d++] = strdup(argv[s++]);
314     view\->argv[d] = nullptr;
315     view\->argc = d;
316     if (!init_view_files(init)) {
317         abend(\-1, "init_view_files failed");
318         return nullptr;
319     }
320     return view;
321 }
.PP
.fi

.PP
References \fBabend()\fP, \fBdisplay_error()\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBinit\fP, \fBinit_view_files()\fP, \fBMAXLEN\fP, \fBssnprintf()\fP, and \fBview\fP\&.
.PP
Referenced by \fBmain()\fP, and \fBmview()\fP\&.
.SS "bool verify_spec_arg (char * spec, char * org_spec, char * dir, char * alt_dir, int mode)"

.PP
Verify file specification argument\&. 
.PP
\fBParameters\fP
.RS 4
\fIspec\fP - menu->spec, form->spec, etc\&. 
.br
\fIorg_spec\fP - init->\&._spec | argv[optind] 
.br
\fIdir\fP - init->\&._\&. directory 
.br
\fIalt_dir\fP - literal, "~/menuapp/data", etc\&. 
.br
\fImode\fP - R_OK, W_OK, X_OK, WC_OK, S_QUIET 
.RE
.PP
\fBNote\fP
.RS 4
mode is a bitwise OR of the following flags: S_QUIET - suppress error messages WC_OK - write create ok 
.RE
.PP
\fBReturns\fP
.RS 4
bool - true if file verified 
.RE
.PP
preserve quotes

.PP
preserve quotes
.PP
Definition at line \fB349\fP of file \fBmem\&.c\fP\&.
.nf
350                                {
351     bool f_dir = false;
352     bool f_spec = false;
353     bool f_quote = true;
354     char *s1;
355     char *s2;
356     char s1_s[MAXLEN];
357     char s2_s[MAXLEN];
358     char file_name[MAXLEN];
359     char try_spec[MAXLEN];
360     char idio_spec[MAXLEN];
361 
362     if (!org_spec[0])
363         return false;
364     idio_spec[0] = '\\0';
365     strnz__cpy(try_spec, org_spec, MAXLEN \- 1);
366     f_quote = stripz_quotes(try_spec);
367     s1 = strtok(try_spec, " \\t\\n");
368     strnz__cpy(s1_s, s1, MAXLEN \- 1);
369     s2 = strtok(nullptr, "\\n");
370     strnz__cpy(s2_s, s2, MAXLEN \- 1);
371     strnz__cpy(file_name, s1, MAXLEN \- 1);
372     strnz__cpy(try_spec, file_name, MAXLEN \- 1);
373     canonicalize_file_spec(try_spec);
374     if (try_spec[0]) {
375         expand_tilde(try_spec, MAXLEN \- 1);
376         if (try_spec[0] == '/') {
377             f_spec = verify_file(try_spec, mode);
378             if (f_quote)
380                 strnz__cpy(spec, org_spec, MAXLEN \- 1);
381             else
382                 strnz__cpy(spec, try_spec, MAXLEN \- 1);
383             return f_spec;
384         } else {
385             if (!f_dir && dir[0]) {
386                 if (strcmp(dir, "$PATH") == 0) {
387                     strnz__cpy(try_spec, file_name, MAXLEN \- 1);
388                     f_spec = locate_file_in_path(try_spec, file_name);
389                 } else {
390                     strnz__cpy(try_spec, dir, MAXLEN \- 1);
391                     expand_tilde(try_spec, MAXLEN \- 1);
392                     f_dir = verify_dir(try_spec, mode);
393                     if (f_dir) {
394                         strnz__cat(try_spec, "/", MAXLEN \- 1);
395                         strnz__cat(try_spec, file_name, MAXLEN \- 1);
396                         strnz__cpy(idio_spec, try_spec, MAXLEN \- 1);
397                         if (mode & S_WCOK)
398                             f_spec = true;
399                         else
400                             f_spec = verify_file(idio_spec, mode | S_QUIET);
401                     }
402                 }
403             }
404             if (!f_spec && alt_dir && alt_dir[0] != '\\0') {
405                 if (strcmp(alt_dir, "$PATH") == 0) {
406                     strnz__cpy(try_spec, file_name, MAXLEN \- 1);
407                     f_spec = locate_file_in_path(try_spec, file_name);
408                 } else {
409                     strnz__cpy(try_spec, alt_dir, MAXLEN \- 1);
410                     expand_tilde(try_spec, MAXLEN \- 1);
411                     f_dir = verify_dir(try_spec, mode);
412                     if (f_dir) {
413                         strnz__cat(try_spec, "/", MAXLEN \- 1);
414                         strnz__cat(try_spec, file_name, MAXLEN \- 1);
415                         if (mode & S_WCOK)
416                             f_spec = true;
417                         else
418                             f_spec = verify_file(try_spec, mode | S_QUIET);
419                     }
420                 }
421             }
422             if (!f_spec) {
423                 strnz__cpy(try_spec, "\&.", MAXLEN \- 1);
424                 strnz__cat(try_spec, "/", MAXLEN \- 1);
425                 strnz__cat(try_spec, file_name, MAXLEN \- 1);
426                 f_spec = verify_file(try_spec, mode | S_QUIET);
427             }
428             if (!f_spec && mode == W_OK) {
429                 strnz__cpy(try_spec, idio_spec, MAXLEN \- 1);
430                 FILE *fp = fopen(try_spec, "a");
431                 if (fp) {
432                     fclose(fp);
433                     f_spec = true;
434                 }
435             }
436             if (f_quote)
438                 strnz__cpy(spec, org_spec, MAXLEN \- 1);
439             else if (f_spec)
440                 strnz__cpy(spec, try_spec, MAXLEN \- 1);
441             if (try_spec[0] == '\\0' && idio_spec[0] != '\\0')
442                 strnz__cpy(spec, idio_spec, MAXLEN \- 1);
443             else
444                 strnz__cpy(spec, try_spec, MAXLEN \- 1);
445             if (s2_s[0] != '\\0') {
446                 strnz__cat(spec, " ", MAXLEN \- 1);
447                 strnz__cat(spec, s2_s, MAXLEN \- 1);
448             }
449             return f_spec;
450         }
451     }
452     return false;
453 }
.PP
.fi

.PP
References \fBcanonicalize_file_spec()\fP, \fBexpand_tilde()\fP, \fBfile_name\fP, \fBlocate_file_in_path()\fP, \fBMAXLEN\fP, \fBstripz_quotes()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBverify_dir()\fP, and \fBverify_file()\fP\&.
.PP
Referenced by \fBenter_file_spec()\fP, \fBinit_form_files()\fP, \fBinit_menu_files()\fP, and \fBinit_pick_files()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "Form* form"

.PP
Definition at line \fB35\fP of file \fBmem\&.c\fP\&.
.PP
Referenced by \fBform_accept_field()\fP, \fBform_calculate()\fP, \fBform_desc_error()\fP, \fBform_display_chyron()\fP, \fBform_display_field()\fP, \fBform_display_field_brackets()\fP, \fBform_display_field_n()\fP, \fBform_display_fields()\fP, \fBform_display_screen()\fP, \fBform_end_fields()\fP, \fBform_engine()\fP, \fBform_enter_fields()\fP, \fBform_exec_cmd()\fP, \fBform_fmt_field()\fP, \fBform_parse_desc()\fP, \fBform_read_data()\fP, \fBform_validate_field()\fP, \fBform_write()\fP, \fBform_yx_to_fidx()\fP, \fBinit_form()\fP, \fBinit_form_files()\fP, \fBmk_filler()\fP, and \fBnew_form()\fP\&.
.SS "int init_cnt = 0"

.PP
Definition at line \fB31\fP of file \fBmem\&.c\fP\&.
.PP
Referenced by \fBdestroy_init()\fP, and \fBnew_init()\fP\&.
.SS "Menu* menu"

.PP
Definition at line \fB33\fP of file \fBmem\&.c\fP\&.
.PP
Referenced by \fBform_engine()\fP, \fBinit_menu_files()\fP, \fBmain()\fP, \fBmenu_cmd_processor()\fP, \fBmenu_engine()\fP, \fBnew_menu()\fP, and \fBparse_menu_description()\fP\&.
.SS "Pick* pick"

.PP
Definition at line \fB34\fP of file \fBmem\&.c\fP\&.
.PP
Referenced by \fBdestroy_pick()\fP, \fBdisplay_page()\fP, \fBdisplay_pick_help()\fP, \fBexec_objects()\fP, \fBinit_pick()\fP, \fBinit_pick_files()\fP, \fBnew_pick()\fP, \fBopen_pick_win()\fP, \fBoutput_objects()\fP, \fBpick_display_chyron()\fP, \fBpick_engine()\fP, \fBpicker()\fP, \fBread_pick_input()\fP, \fBreverse_object()\fP, \fBsave_object()\fP, \fBtoggle_object()\fP, and \fBunreverse_object()\fP\&.
.SS "View* view"

.PP
Definition at line \fB36\fP of file \fBmem\&.c\fP\&.
.PP
Referenced by \fBbuild_prompt()\fP, \fBcat_file()\fP, \fBcmd_line_prompt()\fP, \fBdestroy_view()\fP, \fBdisplay_line()\fP, \fBenter_file_spec()\fP, \fBfmt_line()\fP, \fBget_cmd_arg()\fP, \fBget_cmd_char()\fP, \fBget_next_line()\fP, \fBget_pos_next_line()\fP, \fBget_pos_prev_line()\fP, \fBget_prev_line()\fP, \fBgo_to_eof()\fP, \fBgo_to_line()\fP, \fBgo_to_mark()\fP, \fBgo_to_percent()\fP, \fBgo_to_position()\fP, \fBinit_view_boxwin()\fP, \fBinit_view_files()\fP, \fBinit_view_full_screen()\fP, \fBlp()\fP, \fBmain()\fP, \fBmview()\fP, \fBnew_view()\fP, \fBnext_page()\fP, \fBprev_page()\fP, \fBredisplay_page()\fP, \fBremove_file()\fP, \fBresize_page()\fP, \fBscroll_down_n_lines()\fP, \fBscroll_up_n_lines()\fP, \fBsearch()\fP, \fBview_cmd_processor()\fP, \fBview_file()\fP, \fBview_init_input()\fP, and \fBwrite_view_buffer()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
