.TH "src/include/menu.h" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/menu.h \- \fBMenu\fP data structures, enums, types, end external declarations\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <cm\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBLine\fP"
.br
.RI "The \fBLine\fP strutures are attached to the \fBMenu\fP main structure\&. "
.ti -1c
.RI "struct \fBMenu\fP"
.br
.RI "The \fBMenu\fP structure is the main data structure for the menu application, containing all the information about the menu, its lines, and its display properties\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_MENU_LINES\fP   256 /** Maximum number of \fBmenu\fP \fBlines\fP in a \fBmenu\fP */"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBMT_NULL\fP = 0x320, \fBMT_TEXT\fP, \fBMT_CHOICE\fP }"
.br
.ti -1c
.RI "enum { \fBMA_INIT\fP = 350, \fBMA_RETURN\fP, \fBMA_RETURN_MAIN\fP, \fBMA_DISPLAY_MENU\fP, \fBMA_ENTER_OPTION\fP }"
.br
.ti -1c
.RI "enum { \fBCT_NULL\fP = 0x396, \fBCT_RETURNMAIN\fP, \fBCT_EXEC\fP, \fBCT_HELP\fP, \fBCT_ABOUT\fP, \fBCT_FORM\fP, \fBCT_FORM_EXEC\fP, \fBCT_FORM_WRITE\fP, \fBCT_MENU\fP, \fBCT_PICK\fP, \fBCT_VIEW\fP, \fBCT_CKEYS\fP, \fBCT_RETURN\fP, \fBCT_TOGGLE\fP, \fBCT_WRITE_CONFIG\fP, \fBCT_UNDEFINED\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBget_command_type\fP (char *)"
.br
.RI "Get command type from command string\&. "
.ti -1c
.RI "void \fBfree_menu_line\fP (\fBLine\fP *)"
.br
.RI "Free memory allocated for a menu line\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMenu\fP * \fBmenu\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMenu\fP data structures, enums, types, end external declarations\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBmenu\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_MENU_LINES   256 /** Maximum number of \fBmenu\fP \fBlines\fP in a \fBmenu\fP */"
\fBMenu\fP line types 
.PP
Definition at line \fB19\fP of file \fBmenu\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIMA_INIT \fP(350)
.TP
\f(BIMA_RETURN \fP
.TP
\f(BIMA_RETURN_MAIN \fP
.TP
\f(BIMA_DISPLAY_MENU \fP
.TP
\f(BIMA_ENTER_OPTION \fP
.PP
Definition at line \fB25\fP of file \fBmenu\&.h\fP\&.
.nf
25      {
26     MA_INIT = 350,
27     MA_RETURN,
28     MA_RETURN_MAIN,
29     MA_DISPLAY_MENU,
30     MA_ENTER_OPTION
31 };
.PP
.fi

.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BICT_NULL \fP(0x396)
.TP
\f(BICT_RETURNMAIN \fP
.TP
\f(BICT_EXEC \fP
.TP
\f(BICT_HELP \fP
.TP
\f(BICT_ABOUT \fP
.TP
\f(BICT_FORM \fP
.TP
\f(BICT_FORM_EXEC \fP
.TP
\f(BICT_FORM_WRITE \fP
.TP
\f(BICT_MENU \fP
.TP
\f(BICT_PICK \fP
.TP
\f(BICT_VIEW \fP
.TP
\f(BICT_CKEYS \fP
.TP
\f(BICT_RETURN \fP
.TP
\f(BICT_TOGGLE \fP
.TP
\f(BICT_WRITE_CONFIG \fP
.TP
\f(BICT_UNDEFINED \fP
.PP
Definition at line \fB34\fP of file \fBmenu\&.h\fP\&.
.nf
34      {
35     CT_NULL = 0x396,
36     CT_RETURNMAIN,
37     CT_EXEC,
38     CT_HELP,
39     CT_ABOUT,
40     CT_FORM,
41     CT_FORM_EXEC,
42     CT_FORM_WRITE,
43     CT_MENU,
44     CT_PICK,
45     CT_VIEW,
46     CT_CKEYS,
47     CT_RETURN,
48     CT_TOGGLE,
49     CT_WRITE_CONFIG,
50     CT_UNDEFINED
51 };
.PP
.fi

.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIMT_NULL \fP(0x320)
.TP
\f(BIMT_TEXT \fP
.TP
\f(BIMT_CHOICE \fP
.PP
Definition at line \fB22\fP of file \fBmenu\&.h\fP\&.
.nf
22 { MT_NULL = 0x320, MT_TEXT, MT_CHOICE };
.PP
.fi

.SH "Function Documentation"
.PP 
.SS "void free_menu_line (\fBLine\fP * line)\fR [extern]\fP"

.PP
Free memory allocated for a menu line\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP Pointer to \fBLine\fP structure to free 
.RE
.PP

.PP
Definition at line \fB283\fP of file \fBparse_menu_desc\&.c\fP\&.
.nf
283                                 {
284 
285     if (line\->raw_text != nullptr)
286         free(line\->raw_text);
287     if (line\->choice_text != nullptr)
288         free(line\->choice_text);
289     if (line\->command_str != nullptr)
290         free(line\->command_str);
291     line\->raw_text = nullptr;
292     line\->choice_text = nullptr;
293     line\->choice_letter = '\\0';
294     line\->letter_pos = 0;
295     line\->command_type = '\\0';
296     line\->command_str = nullptr;
297     free(line);
298 }
.PP
.fi

.PP
References \fBLine::choice_letter\fP, \fBLine::choice_text\fP, \fBLine::command_str\fP, \fBLine::command_type\fP, \fBLine::letter_pos\fP, and \fBLine::raw_text\fP\&.
.SS "unsigned int get_command_type (char * t)\fR [extern]\fP"

.PP
Get command type from command string\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP Command string 
.RE
.PP
\fBReturns\fP
.RS 4
Command type as an unsigned int 
.RE
.PP

.PP
Definition at line \fB244\fP of file \fBparse_menu_desc\&.c\fP\&.
.nf
244                                        {
245     char *s, *p;
246 
247     s = p = t;
248     while (*s != ' ' && *s != '\\0') {
249         if (*s == '/')
250             p = s + 1;
251         s++;
252     }
253     *s = '\\0';
254     if (!strcmp(p, "returnmain"))
255         return (CT_RETURNMAIN);
256     else if (!strcmp(p, "ckeys"))
257         return (CT_CKEYS);
258     else if (!strcmp(p, "exec"))
259         return (CT_EXEC);
260     else if (!strcmp(p, "help"))
261         return (CT_HELP);
262     else if (!strcmp(p, "about"))
263         return (CT_ABOUT);
264     else if (!strcmp(p, "menu"))
265         return (CT_MENU);
266     else if (!strcmp(p, "form"))
267         return (CT_FORM);
268     else if (!strcmp(p, "pick"))
269         return (CT_PICK);
270     else if (!strcmp(p, "return"))
271         return (CT_RETURN);
272     else if (!strcmp(p, "view"))
273         return (CT_VIEW);
274     else if (!strcmp(p, "?"))
275         return (CT_HELP);
276     else if (!strcmp(p, "write_config"))
277         return (CT_WRITE_CONFIG);
278     return (CT_UNDEFINED);
279 }
.PP
.fi

.PP
References \fBCT_ABOUT\fP, \fBCT_CKEYS\fP, \fBCT_EXEC\fP, \fBCT_FORM\fP, \fBCT_HELP\fP, \fBCT_MENU\fP, \fBCT_PICK\fP, \fBCT_RETURN\fP, \fBCT_RETURNMAIN\fP, \fBCT_UNDEFINED\fP, \fBCT_VIEW\fP, and \fBCT_WRITE_CONFIG\fP\&.
.PP
Referenced by \fBparse_menu_description()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBMenu\fP* menu\fR [extern]\fP"

.PP
Definition at line \fB33\fP of file \fBmem\&.c\fP\&.
.PP
Referenced by \fBform_engine()\fP, \fBinit_menu_files()\fP, \fBmain()\fP, \fBmenu_cmd_processor()\fP, \fBmenu_engine()\fP, \fBnew_menu()\fP, and \fBparse_menu_description()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
