.TH "src/mview.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mview.c \- Callable Startup for C-Menu View\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <common\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmview\fP (Init *\fBinit\fP, int argc, char **argv)"
.br
.RI "subprogram entry point for C-Menu View "
.in -1c
.SH "Detailed Description"
.PP 
Callable Startup for C-Menu View\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBmview\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int mview (Init * init, int argc, char ** argv)"

.PP
subprogram entry point for C-Menu View 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP Pointer to Init structure containing initialization parameters 
.br
\fIargc\fP Argument count from command line 
.br
\fIargv\fP Argument vector from command line 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, non-zero on failure 
.RE
.PP
\fBNote\fP
.RS 4
use this function to start the C-Menu View from another program, passing in the necessary initialization parameters through the Init structure\&. The function will handle setting up the view based on the provided parameters and will return 0 on success or a non-zero value if an error occurs during initialization\&. 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBmview\&.c\fP\&.
.nf
23                                              {
24     view = init\->view;
25     if (!view)
26         view = new_view(init, argc, argv);
27     else
28         view = init\->view;
29     if (init\->lines != 0 && view\->lines == 0)
30         view\->lines = init\->lines;
31     if (view\->lines == 0)
32         view\->lines = LINES * 3 / 4;
33     if (view\->lines > LINES \- 3)
34         view\->lines = LINES \- 3;
35     if (init\->cols != 0 && view\->lines == 0)
36         view\->cols = init\->cols;
37     if (view\->cols == 0)
38         view\->cols = COLS * 3 / 4;
39     if (view\->cols > COLS \- 3)
40         view\->cols = COLS \- 3;
41     if (init\->begy != 0 && view\->begy == 0)
42         view\->begy = init\->begy;
43     if (view\->begy == 0)
44         view\->begy = (LINES \- view\->lines) / 5;
45     if (view\->begy + view\->lines > LINES \- 2)
46         view\->begy = LINES \- view\->lines \- 2;
47     if (init\->begx != 0 && view\->begx == 0)
48         view\->begx = init\->begx;
49     if (view\->begx == 0)
50         view\->begx = (COLS \- view\->cols) / 5;
51     if (view\->begx + view\->cols > COLS \- 2)
52         view\->begx = COLS \- view\->cols \- 2;
53     view\->f_full_screen = false;
54     if (!init_view_boxwin(init, init\->title)) {
55         view_file(init);
56         win_del();
57     }
58     destroy_view(init);
59     return 0;
60 }
.PP
.fi

.PP
References \fBdestroy_view()\fP, \fBinit\fP, \fBinit_view_boxwin()\fP, \fBnew_view()\fP, \fBview\fP, \fBview_file()\fP, and \fBwin_del()\fP\&.
.PP
Referenced by \fBdisplay_pick_help()\fP, \fBexec_objects()\fP, \fBform_engine()\fP, \fBmain()\fP, \fBmenu_cmd_processor()\fP, and \fBview_display_help()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
