.TH "MyLibrary::SecondExample" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyLibrary::SecondExample
.SH SYNOPSIS
.br
.PP
.PP
\fR#include </srv/www/htdocs/C\-Menu/doxygen\-awesome\-css/include/MyLibrary/example\&.hpp>\fP
.SH "Detailed Description"
.PP 
Definition at line \fB164\fP of file \fBexample\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
