.TH "Opts" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Opts \- Table elements for options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/cm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "unsigned int \fBtype\fP"
.br
.ti -1c
.RI "unsigned int \fBgroup\fP"
.br
.ti -1c
.RI "const char * \fBuse\fP"
.br
.ti -1c
.RI "const char * \fBshort_opt\fP"
.br
.ti -1c
.RI "const char * \fBdesc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Table elements for options\&. 

Option structure\&.

.PP
\fBParameters\fP
.RS 4
\fI\fBname\fP\fP - option name 
.br
\fI\fBgroup\fP\fP - option group 
.br
\fI\fBtype\fP\fP - option type 
.br
\fI\fBuse\fP\fP - option use mask 
.br
\fI\fBshort_opt\fP\fP - option short option 
.br
\fI\fBdesc\fP\fP - option description 
.RE
.PP

.PP
Definition at line \fB194\fP of file \fBcm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "const char* Opts::desc"
brief description 
.PP
Definition at line \fB200\fP of file \fBcm\&.h\fP\&.
.SS "unsigned int Opts::group"
file, misc, param, flag, etc 
.PP
Definition at line \fB197\fP of file \fBcm\&.h\fP\&.
.SS "const char* Opts::name"
long name of the option 
.PP
Definition at line \fB195\fP of file \fBcm\&.h\fP\&.
.PP
Referenced by \fBselect_opt()\fP\&.
.SS "const char* Opts::short_opt"
command line short option, e\&.g\&. -a -b -c 
.PP
Definition at line \fB199\fP of file \fBcm\&.h\fP\&.
.SS "unsigned int Opts::type"
data type, string, int, bool 
.PP
Definition at line \fB196\fP of file \fBcm\&.h\fP\&.
.SS "const char* Opts::use"
menu, pick, form, view 
.PP
Definition at line \fB198\fP of file \fBcm\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
