.TH "src/optsp.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/optsp.c \- print option list for C-Menu  

.SH SYNOPSIS
.br
.PP
\fR#include <cm\&.h>\fP
.br
\fR#include <getopt\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAXLEN\fP   256"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdump_opts_by_short_opt\fP ()"
.br
.RI "dump options sorted by short option "
.ti -1c
.RI "void \fBdump_opts_by_name\fP ()"
.br
.RI "dump options sorted by name "
.ti -1c
.RI "bool \fBcontains\fP (char *str, char c)"
.br
.RI "check if a string contains a specified character "
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "main function for optsp "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBtmp_str\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
print option list for C-Menu 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBoptsp\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAXLEN   256"

.PP
Definition at line \fB18\fP of file \fBoptsp\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "bool contains (char * str, char c)"

.PP
check if a string contains a specified character 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP the string to check 
.br
\fIc\fP the character to look for 
.RE
.PP
\fBReturns\fP
.RS 4
true if the character is found, false otherwise 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBoptsp\&.c\fP\&.
.nf
26                                  {
27     while (*str) {
28         if (*str == c)
29             return true;
30         str++;
31     }
32     return false;
33 }
.PP
.fi

.PP
Referenced by \fBmain()\fP\&.
.SS "void dump_opts_by_name ()"

.PP
dump options sorted by name 
.PP
Definition at line \fB161\fP of file \fBopts\&.c\fP\&.
.nf
161                          {
162     sort_opts_by_name();
163     dump_opts();
164 }
.PP
.fi

.PP
References \fBdump_opts()\fP, and \fBsort_opts_by_name()\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "void dump_opts_by_short_opt ()"

.PP
dump options sorted by short option 
.PP
Definition at line \fB173\fP of file \fBopts\&.c\fP\&.
.nf
173                               {
174     sort_opts_by_short_opt();
175     dump_opts();
176 }
.PP
.fi

.PP
References \fBdump_opts()\fP, and \fBsort_opts_by_short_opt()\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "int main (int argc, char ** argv)"

.PP
main function for optsp 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP argument count 
.br
\fIargv\fP argument vector 
.RE
.PP
\fBReturns\fP
.RS 4
exit status options: -n sort by name -s sort by short option -u select only options in mask -h show help message -v show version mask: any combination in any order of m, f, p, and v, where m is menu, f is form, p is pick, and v is view 
.RE
.PP

.PP
Definition at line \fB51\fP of file \fBoptsp\&.c\fP\&.
.nf
51                                 {
52     bool f_help = false;
53     bool f_version = false;
54     int opt;
55     int i;
56     char tab[] = "mfpv";
57     char mask[] = "\&.\&.\&.\&.";
58     bool f_mask = false;
59     while ((opt = getopt(argc, argv, "hm:nsv")) != \-1) {
60         switch (opt) {
61         case 'h':
62             f_help = true;
63             break;
64         case 'm':
65             for (i = 0; i < 4; i++) {
66                 if (contains(optarg, tab[i]))
67                     mask[i] = tab[i];
68             }
69             printf("mask: %s\\n", mask);
70             f_mask = true;
71             break;
72         case 'n':
73             dump_opts_by_name();
74             break;
75         case 's':
76             dump_opts_by_short_opt();
77             break;
78         case 'v':
79             f_version = true;
80             break;
81         default:
82             exit(EXIT_FAILURE);
83         }
84     }
85     if (f_help) {
86         printf("\\nUsage: optsp [options]\\n\\n");
87         printf("Options:\\n");
88         printf(" \-n  sort by name\\n");
89         printf(" \-s  sort by short option\\n");
90         printf(" \-h  show this help message\\n");
91         printf(" \-m  mask: any combination in any order of m, f, p, and v\\n");
92         printf("\\nwhere m is menu,\\n");
93         printf("      f is form,\\n");
94         printf("      p is pick, and\\n");
95         printf("      v is view\&.\\n");
96         exit(EXIT_SUCCESS);
97     }
98     if (f_version) {
99         printf("optsp version 1\&.0\\n");
100         exit(EXIT_SUCCESS);
101     }
102     if (!f_mask)
103         dump_opts();
104     else
105         dump_opts_by_use("Usage: ", mask);
106 }
.PP
.fi

.PP
References \fBcontains()\fP, \fBdump_opts()\fP, \fBdump_opts_by_name()\fP, \fBdump_opts_by_short_opt()\fP, \fBdump_opts_by_use()\fP, \fBf_help\fP, and \fBf_version\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char tmp_str[256]"

.PP
Definition at line \fB20\fP of file \fBoptsp\&.c\fP\&.
.PP
Referenced by \fBbuild_prompt()\fP, \fBdir_name()\fP, \fBdump_config()\fP, \fBenter_file_spec()\fP, \fBexec_objects()\fP, \fBfork_exec()\fP, \fBform_display_screen()\fP, \fBform_engine()\fP, \fBform_parse_desc()\fP, \fBgo_to_line()\fP, \fBinit_form()\fP, \fBinit_form_files()\fP, \fBinit_menu_files()\fP, \fBinit_pick()\fP, \fBinit_pick_files()\fP, \fBlf_process()\fP, \fBmain()\fP, \fBmapp_initialization()\fP, \fBmenu_cmd_processor()\fP, \fBmenu_engine()\fP, \fBmvwaddstr_fill()\fP, \fBopen_curses()\fP, \fBopen_pick_win()\fP, \fBoutput_objects()\fP, \fBparse_config()\fP, \fBparse_menu_description()\fP, \fBparse_opt_args()\fP, \fBpick_display_chyron()\fP, \fBsearch()\fP, \fBstr_to_args()\fP, \fBview_cmd_processor()\fP, \fBview_display_help()\fP, \fBview_init_input()\fP, and \fBwrite_config()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
