.TH "src/parse_menu_desc.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/parse_menu_desc.c \- Parse menu description file and create Menu\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <common\&.h>\fP
.br
\fR#include <ctype\&.h>\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBparse_menu_description\fP (Init *\fBinit\fP)"
.br
.RI "Parse menu description file and create Menu\&. "
.ti -1c
.RI "unsigned int \fBget_command_type\fP (char *t)"
.br
.RI "Get command type from command string\&. "
.ti -1c
.RI "void \fBfree_menu_line\fP (Line *line)"
.br
.RI "Free memory allocated for a menu line\&. "
.in -1c
.SH "Detailed Description"
.PP 
Parse menu description file and create Menu\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBparse_menu_desc\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void free_menu_line (Line * line)"

.PP
Free memory allocated for a menu line\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP Pointer to Line structure to free 
.RE
.PP

.PP
Definition at line \fB283\fP of file \fBparse_menu_desc\&.c\fP\&.
.nf
283                                 {
284 
285     if (line\->raw_text != nullptr)
286         free(line\->raw_text);
287     if (line\->choice_text != nullptr)
288         free(line\->choice_text);
289     if (line\->command_str != nullptr)
290         free(line\->command_str);
291     line\->raw_text = nullptr;
292     line\->choice_text = nullptr;
293     line\->choice_letter = '\\0';
294     line\->letter_pos = 0;
295     line\->command_type = '\\0';
296     line\->command_str = nullptr;
297     free(line);
298 }
.PP
.fi

.SS "unsigned int get_command_type (char * t)"

.PP
Get command type from command string\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP Command string 
.RE
.PP
\fBReturns\fP
.RS 4
Command type as an unsigned int 
.RE
.PP

.PP
Definition at line \fB244\fP of file \fBparse_menu_desc\&.c\fP\&.
.nf
244                                        {
245     char *s, *p;
246 
247     s = p = t;
248     while (*s != ' ' && *s != '\\0') {
249         if (*s == '/')
250             p = s + 1;
251         s++;
252     }
253     *s = '\\0';
254     if (!strcmp(p, "returnmain"))
255         return (CT_RETURNMAIN);
256     else if (!strcmp(p, "ckeys"))
257         return (CT_CKEYS);
258     else if (!strcmp(p, "exec"))
259         return (CT_EXEC);
260     else if (!strcmp(p, "help"))
261         return (CT_HELP);
262     else if (!strcmp(p, "about"))
263         return (CT_ABOUT);
264     else if (!strcmp(p, "menu"))
265         return (CT_MENU);
266     else if (!strcmp(p, "form"))
267         return (CT_FORM);
268     else if (!strcmp(p, "pick"))
269         return (CT_PICK);
270     else if (!strcmp(p, "return"))
271         return (CT_RETURN);
272     else if (!strcmp(p, "view"))
273         return (CT_VIEW);
274     else if (!strcmp(p, "?"))
275         return (CT_HELP);
276     else if (!strcmp(p, "write_config"))
277         return (CT_WRITE_CONFIG);
278     return (CT_UNDEFINED);
279 }
.PP
.fi

.PP
Referenced by \fBparse_menu_description()\fP\&.
.SS "unsigned int parse_menu_description (Init * init)"

.PP
Parse menu description file and create Menu\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP Pointer to Init structure containing menu information 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, non-zero on failure 
.RE
.PP
'#' Comment line, ignore

.PP
'!' Choice line, parse and add to menu

.PP
':' Text line, parse and add to menu

.PP
< in_buf -> Title

.PP
'?' Help line, ignore for now

.PP
' ' Empty line, ignore
.PP
Definition at line \fB24\fP of file \fBparse_menu_desc\&.c\fP\&.
.nf
24                                                 {
25     FILE *fp;
26     char tmp_str[MAXLEN];
27     char tmp_buf[MAXLEN];
28     char in_buf[MAXLEN];
29     char *in_buf_p;
30     int Pos;
31     unsigned char ltr;
32     unsigned char fltr[127];
33     int directive;
34     int l;
35     char *s, *d, *e;
36     int actions = 0;
37     int choices = 0;
38     int in_fp_line = 0;
39     menu = init\->menu;
40     fp = fopen(menu\->mapp_spec, "r");
41     if (fp == nullptr) {
42         strnz__cat(tmp_buf, "file not found", MAXLEN);
43         abend(\-1, tmp_buf);
44         exit(\-1);
45     }
46     while ((fgets(in_buf, MAXLEN, fp)) != nullptr) {
47         if (in_buf[0] == '\\0')
48             continue;
49         in_fp_line++;
50         chrep(in_buf, '\\r', '\\0');
51         chrep(in_buf, '\\n', '\\0');
52         chrep(in_buf, '\\t', ' ');
53         in_buf_p = in_buf;
54         directive = *in_buf_p;
55         in_buf_p++;
56         strnz__cpy(tmp_buf, in_buf_p, MAXLEN);
57         trim(tmp_buf);
58         l = strlen(tmp_buf);
59         if (!l)
60             continue;
61         switch (directive) {
63         case '#':
64             break;
66         case '!':
67             if (!menu\->line_idx)
68                 break;
69             if (menu\->line[menu\->line_idx \- 1]\->type != MT_TEXT)
70                 break;
71             menu\->line_idx\-\-;
72             l = strlen(tmp_buf);
73             if (l + 1 > MAXLEN)
74                 break;
75             menu\->line[menu\->line_idx]\->command_str =
76                 (char *)malloc(MAXLEN + 1);
77             if (!menu\->line[menu\->line_idx]\->command_str) {
78                 sprintf(tmp_str,
79                         "0\-malloc(%d bytes) failed M\-L[%d]\->command_str",
80                         MAXLEN + 1, menu\->line_idx);
81                 abend(\-1, tmp_str);
82             }
83             menu\->line[menu\->line_idx]\->command_str = strdup(tmp_buf);
84             menu\->line[menu\->line_idx]\->command_type =
85                 get_command_type(tmp_buf);
86             s = menu\->line[menu\->line_idx]\->raw_text;
87             if (*s == '\-' || *s == '_') {
88                 s++;
89                 ltr = *s++;
90             } else
91                 ltr = *s;
92             l = 0;
93             while (*s++ != '\\0')
94                 l++;
95             if (l + 1 > MAXLEN)
96                 l = MAXLEN \- 1;
97             menu\->line[menu\->line_idx]\->choice_text =
98                 (char *)malloc(MAXLEN + 1);
99             if (!menu\->line[menu\->line_idx]\->choice_text) {
100                 sprintf(tmp_str,
101                         "1\-malloc(%d bytes) failed M\-L[%d]\->choice_text",
102                         MAXLEN + 1, menu\->line_idx);
103                 abend(\-1, tmp_str);
104             }
105             d = menu\->line[menu\->line_idx]\->choice_text;
106             e = d + l;
107             s = menu\->line[menu\->line_idx]\->raw_text;
108             if (*s == '\-' || *s == '_')
109                 s += 2;
110             while (*s != '\\0' && d < e)
111                 *d++ = *s++;
112             *d = (char)'\\0';
113             if (l > menu\->choice_max_len)
114                 menu\->choice_max_len = l;
115             if (menu\->line[menu\->line_idx]\->command_type == CT_RETURN)
116                 menu\->line[menu\->line_idx]\->choice_letter = 'Q';
117             else
118                 menu\->line[menu\->line_idx]\->choice_letter = ltr;
119             menu\->line[menu\->line_idx]\->type = MT_CHOICE;
120             menu\->line_idx++;
121             actions++;
122             break;
124         case ':':
125             if (choices > actions) {
126                 ssnprintf(em0, MAXLEN \- 1,
127                           "More choices than actions at line %d of",
128                           in_fp_line);
129                 strnz__cpy(em1, menu\->mapp_spec, MAXLEN \- 1);
130                 strnz__cat(em2, in_buf, MAXLEN \- 1);
131                 display_error(em0, em1, em2, nullptr);
132                 abend(\-1, "unrecoverable error");
133             }
134             chrep(tmp_buf, '\\t', ' ');
135             l = strlen(tmp_buf);
136             if (l > menu\->text_max_len)
137                 menu\->text_max_len = l;
138             if (!menu\->title[0]) { 
139                 if (l + 5 > MAXLEN)
140                     l = MAXLEN \- 5;
141                 strnz__cpy(menu\->title, tmp_buf, l);
142                 l += 4;
143                 if (l > menu\->text_max_len)
144                     menu\->text_max_len = l;
145             } else {
146                 menu\->line[menu\->line_idx] = (Line *)malloc(sizeof(Line));
147                 if (menu\->line[menu\->line_idx] == (Line *)0) {
148                     sprintf(tmp_str,
149                             "2\-malloc(%ld bytes) failed menu\->line[%d]",
150                             sizeof(Line), menu\->line_idx);
151                     abend(\-1, tmp_str);
152                 }
153                 menu\->line[menu\->line_idx]\->type = MT_TEXT;
154                 menu\->line[menu\->line_idx]\->raw_text = strdup(tmp_buf);
155                 menu\->line[menu\->line_idx]\->choice_text = nullptr;
156                 menu\->line[menu\->line_idx]\->choice_letter = '\\0';
157                 menu\->line[menu\->line_idx]\->letter_pos = 0;
158                 menu\->line[menu\->line_idx]\->command_type = '\\0';
159                 menu\->line[menu\->line_idx]\->command_str = nullptr;
160                 menu\->line_idx++;
161                 choices++;
162             }
163             break; 
164         case '?':
165             break; 
166         case ' ':
167         case '\\0':
168         case '\\n':
169             break;
170         default:
171 
172             // strnz__cpy(tmp_buf, "unrecognized operator in ", MAXLEN);
173             // abend(\-1, tmp_buf);
174         }
175     }
176     fclose(fp);
177     menu\->item_count = menu\->line_idx;
178     for (ltr = '0'; ltr < 'z'; ltr++)
179         fltr[ltr] = FALSE;
180     fltr['Q'] = TRUE;
181     for (menu\->line_idx = 0; menu\->line_idx < menu\->item_count;
182          menu\->line_idx++) {
183         ltr = menu\->line[menu\->line_idx]\->choice_letter;
184         if (ltr < '0' || ltr > 'z')
185             ltr = '0';
186         if (!fltr[ltr] ||
187             (menu\->line[menu\->line_idx]\->command_type == CT_RETURN &&
188              ltr == 'Q')) {
189             fltr[ltr] = TRUE;
190             s = menu\->line[menu\->line_idx]\->choice_text;
191             Pos = 0;
192             while (*s != '\\0') {
193                 if (*s == ltr)
194                     break;
195                 s++;
196                 Pos++;
197             }
198         } else {
199             Pos = 0;
200             while (ltr != '\\0') {
201                 Pos++;
202                 ltr = toupper(menu\->line[menu\->line_idx]\->choice_text[Pos]);
203                 if (ltr >= '0' && ltr <= 'Z')
204                     if (!fltr[ltr])
205                         break;
206             }
207             if (ltr == '\\0') {
208                 for (ltr = '0'; ltr < 'Z'; ltr++)
209                     if (!fltr[ltr])
210                         break;
211                 if (ltr > 'z') {
212                     Perror("Ran out of letters");
213                     return 0;
214                 }
215             }
216             fltr[ltr] = TRUE;
217             menu\->line[menu\->line_idx]\->choice_letter = ltr;
218         }
219         menu\->line[menu\->line_idx]\->letter_pos = Pos;
220     }
221     menu\->lines = menu\->item_count;
222     if (menu\->text_max_len > (menu\->choice_max_len + 6))
223         menu\->cols = menu\->text_max_len;
224     else
225         menu\->cols = menu\->choice_max_len + 6;
226     if (menu\->cols >= MAXLEN)
227         Perror("line too long");
228     for (menu\->line_idx = 0; menu\->line_idx < menu\->item_count;
229          menu\->line_idx++) {
230         strnz__cpy(tmp_buf, " x \- ", MAXLEN \- 1);
231         tmp_buf[1] = menu\->line[menu\->line_idx]\->choice_letter;
232         strnz__cat(tmp_buf, menu\->line[menu\->line_idx]\->choice_text,
233                    MAXLEN \- 1);
234         strnz__cpy(menu\->line[menu\->line_idx]\->choice_text, tmp_buf,
235                    MAXLEN \- 1);
236     }
237 
238     return 0;
239 }
.PP
.fi

.PP
References \fBabend()\fP, \fBchrep()\fP, \fBdisplay_error()\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBFALSE\fP, \fBget_command_type()\fP, \fBinit\fP, \fBMAXLEN\fP, \fBmenu\fP, \fBPerror()\fP, \fBssnprintf()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, \fBtrim()\fP, and \fBTRUE\fP\&.
.PP
Referenced by \fBmain()\fP, \fBmenu_cmd_processor()\fP, and \fBmenu_engine()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
