.TH "src/pick_engine.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pick_engine.c \- pick from a list of choices  

.SH SYNOPSIS
.br
.PP
\fR#include <common\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <sys/stat\&.h>\fP
.br
\fR#include <sys/wait\&.h>\fP
.br
\fR#include <termios\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpick_engine\fP (Init *\fBinit\fP)"
.br
.RI "Initializes pick interface, calculates window size and position, and enters picker loop\&. "
.ti -1c
.RI "void \fBsave_object\fP (Pick *\fBpick\fP, char *s)"
.br
.RI "Saves a string as an object in the pick structure\&. "
.ti -1c
.RI "int \fBpicker\fP (Init *\fBinit\fP)"
.br
.RI "Main loop to handle user input and interactions for pick interface\&. "
.ti -1c
.RI "void \fBdisplay_page\fP (Pick *\fBpick\fP)"
.br
.RI "Displays current page of objects in pick window\&. "
.ti -1c
.RI "void \fBreverse_object\fP (Pick *\fBpick\fP)"
.br
.RI "Reverses the display of the currently selected object in pick window\&. "
.ti -1c
.RI "void \fBunreverse_object\fP (Pick *\fBpick\fP)"
.br
.RI "Unreverses the display of the currently selected object in pick window\&. "
.ti -1c
.RI "void \fBtoggle_object\fP (Pick *\fBpick\fP)"
.br
.RI "Toggles the selection state of the currently selected object in pick window\&. "
.ti -1c
.RI "int \fBoutput_objects\fP (Pick *\fBpick\fP)"
.br
.RI "Outputs selected objects to specified output file\&. "
.ti -1c
.RI "int \fBexec_objects\fP (Init *\fBinit\fP)"
.br
.RI "Executes specified command with selected objects as arguments\&. "
.ti -1c
.RI "int \fBopen_pick_win\fP (Init *\fBinit\fP)"
.br
.RI "Initializes the pick window based on the parameters specified in the Pick structure\&. "
.ti -1c
.RI "void \fBdisplay_pick_help\fP (Init *\fBinit\fP)"
.br
.RI "Displays the help screen for the pick interface using mview\&. "
.ti -1c
.RI "void \fBpick_display_chyron\fP (Pick *\fBpick\fP)"
.br
.RI "Displays chyron with page information at bottom of pick window\&. "
.ti -1c
.RI "int \fBread_pick_input\fP (Init *\fBinit\fP)"
.br
.RI "Reads pick input from file pointer and saves objects into pick structure\&. "
.ti -1c
.RI "int \fBinit_pick\fP (Init *\fBinit\fP, int argc, char **argv, int begy, int begx)"
.br
.RI "Initializes pick structure and opens pick input file or pipe\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBtbl_col\fP"
.br
.ti -1c
.RI "int \fBtbl_line\fP"
.br
.ti -1c
.RI "int \fBtbl_page\fP"
.br
.ti -1c
.RI "int \fBtbl_cols\fP"
.br
.ti -1c
.RI "int \fBpg_lines\fP"
.br
.ti -1c
.RI "int \fBtbl_pages\fP"
.br
.ti -1c
.RI "int \fBobj_idx\fP"
.br
.ti -1c
.RI "int \fBcalculated_idx\fP"
.br
.ti -1c
.RI "int \fBpipe_fd\fP [2]"
.br
.ti -1c
.RI "char const \fBpagers_editors\fP [12][10]"
.br
.in -1c
.SH "Detailed Description"
.PP 
pick from a list of choices 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBpick_engine\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void display_page (Pick * pick)"

.PP
Displays current page of objects in pick window\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBpick\fP\fP Pointer to Pick structure containing objects and display information 
.RE
.PP
\fBNote\fP
.RS 4
Clears the pick window and displays the current page of objects based on the current table page, line, and column\&. Marks selected objects with an asterisk\&. Updates the chyron with page information at the bottom of the pick window\&. 
.RE
.PP

.PP
Definition at line \fB503\fP of file \fBpick_engine\&.c\fP\&.
.nf
503                               {
504     int y, col, pidx;
505     for (y = 0; y < pick\->pg_lines; y++) {
506         wmove(pick\->win, y, 0);
507         wclrtoeol(pick\->win);
508     }
509     pidx = pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols;
510     for (col = 0; col < pick\->tbl_cols; col++) {
511         pick\->x = col * (pick\->tbl_col_width + 1) + 1;
512         for (y = 0; y < pick\->pg_lines; y++, pidx++) {
513             if (pidx < pick\->obj_cnt) {
514                 if (pick\->f_selected[pidx])
515                     mvwaddstr(pick\->win, y, pick\->x \- 1, "*");
516                 mvwaddstr_fill(pick\->win, y, pick\->x, pick\->object[pidx],
517                                pick\->tbl_col_width);
518             }
519         }
520     }
521     pick_display_chyron(pick);
522 }
.PP
.fi

.PP
References \fBmvwaddstr_fill()\fP, \fBpick\fP, and \fBpick_display_chyron()\fP\&.
.PP
Referenced by \fBpick_engine()\fP, and \fBpicker()\fP\&.
.SS "void display_pick_help (Init * init)"

.PP
Displays the help screen for the pick interface using mview\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP Pointer to Init structure containing pick information 
.RE
.PP
\fBNote\fP
.RS 4
Initializes the help_spec field in the Pick structure with the path to the pick help file\&. Then, constructs the argument list for executing mview with the help file as an argument\&. Finally, calls mview function to display the help screen within the pick interface\&. 
.RE
.PP

.PP
Definition at line \fB845\fP of file \fBpick_engine\&.c\fP\&.
.nf
845                                    {
846     eargv[0] = strdup("view");
847     eargv[1] = strdup("~/menuapp/help/pick\&.help");
848     eargv[2] = nullptr;
849     eargc = 2;
850     zero_opt_args(init);
851     parse_opt_args(init, eargc, eargv);
852     init\->lines = 30;
853     init\->cols = 60;
854     init\->begy = pick\->begy + 1;
855     init\->begx = pick\->begx + 1;
856     strnz__cpy(init\->title, "Pick Help", MAXLEN \- 1);
857     mview(init, eargc, eargv);
858     free(eargv[0]);
859     free(eargv[1]);
860     return;
861 }
.PP
.fi

.PP
References \fBeargc\fP, \fBeargv\fP, \fBinit\fP, \fBMAXLEN\fP, \fBmview()\fP, \fBparse_opt_args()\fP, \fBpick\fP, \fBstrnz__cpy()\fP, and \fBzero_opt_args()\fP\&.
.PP
Referenced by \fBpicker()\fP\&.
.SS "int exec_objects (Init * init)"

.PP
Executes specified command with selected objects as arguments\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP Pointer to Init structure 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, 1 on failure 
.RE
.PP
\fBNote\fP
.RS 4
Parses command string and appends selected objects as arguments to the command\&. If command contains "%%", it is replaced with a space- separated list of selected objects\&. Executes the command using execvp in a child process and waits for it to finish\&. If the command is a pager or editor, it is executed within the pick interface using mview instead of execvp\&. 

.PP
If f_append_args is true, the argument containing %% is replaced with the concatenated selected objects\&. If f_append_args is false, selected objects are added as separate arguments and the original command arguments remain unchanged\&. 

.PP
margv should be null-terminated to indicate the end of arguments for execvp 

.PP
Memory allocated for arguments is freed after execution to prevent memory leaks\&. 

.PP
If execvp fails, an error message is printed and the child process exits with failure status 

.PP
The parent process waits for the child process to finish before proceeding and restores terminal settings 

.PP
If the command is a pager or editor, it is executed within the pick interface using mview instead of execvp 

.PP
The base name of the command is extracted to check if it is a pager or editor 

.PP
If the command is a pager or editor, the pick interface is used to display the command output instead of executing it in a separate terminal This allows the user to view the command output without leaving the pick interface and provides a more seamless user experience\&. 

.PP
If the command is not a pager or editor, it is executed in a separate terminal and the pick interface is restored after execution 

.PP
If the command to be executed is view, an external command is not needed, instead the mview function can be used to display the output within the pick interface 
.RE
.PP
initialize mview arguments and execute mview to display command output within pick interface

.PP
fork failed, free margv and return error

.PP
Child process to execute command

.PP
If execvp returns, it means execution failed, so free margv and print error message before exiting
.PP
Definition at line \fB663\fP of file \fBpick_engine\&.c\fP\&.
.nf
663                              {
664     int rc = \-1;
665     int margc;
666     char *margv[MAXARGS];
667     char tmp_str[MAXLEN];
668     char title[MAXLEN];
669     char sav_arg[MAXLEN];
670     char *out_s;
671     int margx = 0;
672     int i = 0;
673     pid_t pid = 0;
674     bool f_append_args = false;
675     char *s1;
676 
677     title[0] = '\\0';
678     if (pick\->cmd[0] == '\\0')
679         return \-1;
680     if (pick\->cmd[0] == '\\\\' || pick\->cmd[0] == '\\"') {
681         size_t len = strlen(pick\->cmd);
682         if (len > 1 && pick\->cmd[len \- 1] == '\\"') {
683             memmove(pick\->cmd, pick\->cmd + 1, len \- 2);
684             pick\->cmd[len \- 2] = '\\0';
685         }
686     }
687     margc = str_to_args(margv, pick\->cmd, MAXARGS \- 1);
688     tmp_str[0] = '\\0';
689     if (pick\->f_multiple_cmd_args) {
690         for (i = 0; i < pick\->obj_cnt; i++) {
691             if (pick\->f_selected[i] && margc < MAXARGS) {
692                 if (tmp_str[0] != '\\0')
693                     strnz__cat(tmp_str, " ", MAXLEN \- 1);
694                 strnz__cat(tmp_str, pick\->object[i], MAXLEN \- 1);
695             }
696         }
697         margv[margc++] = strdup(tmp_str);
698     } else {
699         f_append_args = false;
700         i = 0;
701         while (i < margc) {
702             if (strstr(margv[i], "%%") != nullptr) {
703                 tmp_str[0] = '\\0';
704                 f_append_args = true;
705                 strnz__cpy(sav_arg, margv[i], MAXLEN \- 1);
706                 margx = i;
707                 break;
708             }
709             i++;
710         }
711         for (i = 0; i < pick\->obj_cnt \- 1; i++) {
712             if (pick\->f_selected[i] && margc < MAXARGS \- 1) {
713                 if (f_append_args == true) {
714                     if (tmp_str[0] != '\\0')
715                         strnz__cat(tmp_str, " ", MAXLEN \- 1);
716                     strnz__cat(tmp_str, pick\->object[i], MAXLEN \- 1);
717                     continue;
718                 }
719                 margv[margc++] = strdup(pick\->object[i]);
720             }
721         }
722         if (f_append_args == true) {
723             if (margv[margx] != nullptr) {
724                 free(margv[margx]);
725                 margv[margx] = nullptr;
726             }
727             out_s = rep_substring(sav_arg, "%%", tmp_str);
728             if (out_s == nullptr || out_s[0] == '\\0') {
729                 i = 0;
730                 while (i < margc) {
731                     if (margv[i] != nullptr)
732                         free(margv[i]);
733                     i++;
734                 }
735                 Perror("rep_substring() failed in exec_objects");
736                 return 1;
737             }
738             strnz__cpy(title, out_s, MAXLEN \- 1);
739             margv[margx] = strdup(out_s);
740             if (out_s != nullptr) {
741                 free(out_s);
742                 out_s = nullptr;
743             }
744         }
745     }
746     strnz__cpy(tmp_str, margv[0], MAXLEN \- 1);
747     margv[margc] = nullptr;
748     s1 = tmp_str;
749     char *sp;
750     char *tok;
751     tok = strtok_r(s1, " ", &sp);
752     strnz__cpy(sav_arg, tok, MAXLEN \- 1);
753     base_name(tmp_str, sav_arg);
754     if (tmp_str[0] != '\\0' &&
755         (strcmp(tmp_str, "view") == 0 || strcmp(tmp_str, "mview") == 0)) {
758         zero_opt_args(init);
759         parse_opt_args(init, margc, margv);
760         init\->lines = 60;
761         init\->cols = 80;
762         init\->begy = pick\->begy + 1;
763         init\->begx = pick\->begx + 1;
764         if (title[0] != '\\0')
765             strnz__cpy(init\->title, title, MAXLEN \- 1);
766         else
767             strnz__cpy(init\->title, margv[margc], MAXLEN \- 1);
768         mview(init, margc, margv);
769         i = 0;
770         while (i < margc) {
771             if (margv[i] != nullptr)
772                 free(margv[i]);
773             i++;
774         }
775         return 0;
776     } else {
777         if ((pid = fork()) == \-1) {
779             i = 0;
780             while (i < margc) {
781                 if (margv[i] != nullptr)
782                     free(margv[i]);
783                 i++;
784             }
785             Perror("fork() failed in exec_objects");
786             return (1);
787         }
788         if (pid == 0) {
790             execvp(margv[0], margv);
793             strnz__cpy(tmp_str, "Can't exec pick cmd: ", MAXLEN \- 1);
794             strnz__cat(tmp_str, margv[0], MAXLEN \- 1);
795             Perror(tmp_str);
796             exit(EXIT_FAILURE);
797         }
798     }
799     waitpid(pid, nullptr, 0);
800     i = 0;
801     while (i < margc) {
802         if (margv[i] != nullptr)
803             free(margv[i]);
804         i++;
805     }
806     restore_curses_tioctl();
807     sig_prog_mode();
808     keypad(pick\->win, true);
809     restore_wins();
810     return rc;
811 }
.PP
.fi

.PP
References \fBbase_name()\fP, \fBinit\fP, \fBMAXLEN\fP, \fBmview()\fP, \fBparse_opt_args()\fP, \fBPerror()\fP, \fBpick\fP, \fBrep_substring()\fP, \fBrestore_curses_tioctl()\fP, \fBrestore_wins()\fP, \fBsig_prog_mode()\fP, \fBstr_to_args()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBzero_opt_args()\fP\&.
.PP
Referenced by \fBpick_engine()\fP\&.
.SS "int init_pick (Init * init, int argc, char ** argv, int begy, int begx)"

.PP
Initializes pick structure and opens pick input file or pipe\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP Pointer to Init structure 
.br
\fIargc\fP Argument count 
.br
\fIargv\fP Argument vector 
.br
\fIbegy\fP Beginning y coordinate for pick window 
.br
\fIbegx\fP Beginning x coordinate for pick window 
.RE
.PP
\fBNote\fP
.RS 4
If provider_cmd is specified, it takes precedence over in_spec and input file arguments 

.PP
provider_cmd is executed and its output is read as pick input 

.PP
If provider_cmd is not specified, in_spec is used to read pick input from a file or stdin 

.PP
If provider_cmd is specified, it is executed and its output is read as pick input 
.RE
.PP
Spawn Child to execute provider_cmd Close read end of pipe as Child only needs to write to pipe

.PP
Connect CHILD STDOUT to write end of pipe

.PP
STDOUT attached to write end of pipe, so close pipe fd

.PP
Return to Parent Close write end of pipe as Parent only needs to read from pipe

.PP
Open a file pointer on read end of pipe

.PP
No provider_cmd specified, so read pick input from file or stdin

.PP
Wait for provider_cmd child process to finish before proceeding

.PP
Enter pick_engine
.PP
Definition at line \fB54\fP of file \fBpick_engine\&.c\fP\&.
.nf
54                                                                      {
55     struct stat sb;
56     char *s_argv[MAXARGS];
57     char tmp_str[MAXLEN];
58     int m;
59     pid_t pid = 0;
60 
61     if (init\->pick != nullptr)
62         destroy_pick(init);
63     Pick *pick = new_pick(init, argc, argv, begy, begx);
64     if (init\->pick != pick)
65         abend(\-1, "init\->pick != pick\\n");
66     SIO *sio = init\->sio;
67     if (pick\->provider_cmd[0] != '\\0') {
68         str_to_args(s_argv, pick\->provider_cmd, MAXARGS \- 1);
69         if (pipe(pipe_fd) == \-1) {
70             Perror("pipe(pipe_fd) failed in init_pick");
71             return (1);
72         }
73         if ((pid = fork()) == \-1) {
74             Perror("fork() failed in init_pick");
75             return (1);
76         }
77         if (pid == 0) {
80             close(pipe_fd[P_READ]);
82             dup2(pipe_fd[P_WRITE], STDOUT_FILENO);
83             dup2(pipe_fd[P_WRITE], STDERR_FILENO);
85             close(pipe_fd[P_WRITE]);
86             execvp(s_argv[0], s_argv);
87             m = MAXLEN \- 24;
88             strnz__cpy(tmp_str, "Can't exec pick start cmd: ", m);
89             m \-= strlen(s_argv[0]);
90             strnz__cat(tmp_str, s_argv[0], m);
91             Perror(tmp_str);
92             exit(EXIT_FAILURE);
93         }
96         close(pipe_fd[P_WRITE]);
98         pick\->in_fp = fdopen(pipe_fd[P_READ], "rb");
99         pick\->f_in_pipe = true;
100     } else {
101         if ((pick\->in_spec[0] == '\\0') || strcmp(pick\->in_spec, "\-") == 0 ||
102             strcmp(pick\->in_spec, "/dev/stdin") == 0) {
103             strnz__cpy(pick\->in_spec, "/dev/stdin", MAXLEN \- 1);
104             pick\->in_fp = fdopen(STDIN_FILENO, "rb");
105             pick\->f_in_pipe = true;
106         }
107     }
108     if (!pick\->f_in_pipe) {
110         if (lstat(pick\->in_spec, &sb) == \-1) {
111             m = MAXLEN \- 29;
112             strnz__cpy(tmp_str, "Can\\'t stat pick input file: ", m);
113             m \-= strlen(pick\->in_spec);
114             strnz__cat(tmp_str, pick\->in_spec, m);
115             Perror(tmp_str);
116             return (1);
117         }
118         if (sb\&.st_size == 0) {
119             m = MAXLEN \- 24;
120             strnz__cpy(tmp_str, "Pick input file empty: ", m);
121             m \-= strlen(pick\->in_spec);
122             strnz__cat(tmp_str, pick\->in_spec, m);
123             Perror(tmp_str);
124             return (1);
125         }
126         if ((pick\->in_fp = fopen(pick\->in_spec, "rb")) == nullptr) {
127             m = MAXLEN \- 29;
128             strnz__cpy(tmp_str, "Can't open pick input file: ", m);
129             m \-= strlen(pick\->in_spec);
130             strnz__cat(tmp_str, pick\->in_spec, m);
131             Perror(tmp_str);
132             return (1);
133         }
134     }
135     read_pick_input(init);
136     if (pick\->f_in_pipe && pid > 0) {
138         waitpid(pid, nullptr, 0);
139         close(pipe_fd[P_READ]);
140         dup2(sio\->stdin_fd, STDIN_FILENO);
141         dup2(sio\->stdout_fd, STDOUT_FILENO);
142         restore_curses_tioctl();
143         sig_prog_mode();
144         keypad(pick\->win, true);
145     }
146     if (pick\->obj_cnt == 0) {
147         Perror("No pick objects available");
148         destroy_pick(init);
149         return (1);
150     }
152     pick_engine(init);
153     win_del();
154     destroy_pick(init);
155     return 0;
156 }
.PP
.fi

.PP
References \fBabend()\fP, \fBdestroy_pick()\fP, \fBinit\fP, \fBMAXLEN\fP, \fBnew_pick()\fP, \fBPerror()\fP, \fBpick\fP, \fBpick_engine()\fP, \fBpipe_fd\fP, \fBread_pick_input()\fP, \fBrestore_curses_tioctl()\fP, \fBsig_prog_mode()\fP, \fBsio\fP, \fBstr_to_args()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBwin_del()\fP\&.
.PP
Referenced by \fBmain()\fP, and \fBmenu_cmd_processor()\fP\&.
.SS "int open_pick_win (Init * init)"

.PP
Initializes the pick window based on the parameters specified in the Pick structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP Pointer to Init structure containing pick information 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, 1 on failure 
.RE
.PP
\fBNote\fP
.RS 4
Creates a new window for the pick interface using win_new function with the specified parameters from the Pick structure\&. If window creation fails, an error message is printed and the function returns 1\&. Otherwise, initializes the window and box pointers in the Pick structure, sets scrollok and keypad options for the window, and returns 0 on success\&. 
.RE
.PP

.PP
Definition at line \fB821\fP of file \fBpick_engine\&.c\fP\&.
.nf
821                               {
822     char tmp_str[MAXLEN];
823     pick = init\->pick;
824     if (win_new(pick\->win_lines, pick\->win_width, pick\->begy, pick\->begx,
825                 pick\->title, 0)) {
826         ssnprintf(tmp_str, MAXLEN \- 1, "win_new(%d, %d, %d, %d, %s, %b) failed",
827                   pick\->win_lines, pick\->win_width, pick\->begy, pick\->begx,
828                   pick\->title, 0);
829         Perror(tmp_str);
830 
831         return (1);
832     }
833     pick\->win = win_win[win_ptr];
834     pick\->box = win_box[win_ptr];
835     scrollok(pick\->win, FALSE);
836     keypad(pick\->win, true);
837     return 0;
838 }
.PP
.fi

.PP
References \fBFALSE\fP, \fBinit\fP, \fBMAXLEN\fP, \fBPerror()\fP, \fBpick\fP, \fBssnprintf()\fP, \fBtmp_str\fP, \fBwin_box\fP, \fBwin_new()\fP, \fBwin_ptr\fP, and \fBwin_win\fP\&.
.PP
Referenced by \fBpick_engine()\fP\&.
.SS "int output_objects (Pick * pick)"

.PP
Outputs selected objects to specified output file\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBpick\fP\fP Pointer to Pick structure containing selected objects and output file information 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, 1 on failure 
.RE
.PP
\fBNote\fP
.RS 4
If output file cannot be opened, an error message is printed and the function returns 1\&. Otherwise, selected objects are written to the output file, one per line, and the file is closed before returning 0\&. 
.RE
.PP

.PP
Definition at line \fB612\fP of file \fBpick_engine\&.c\fP\&.
.nf
612                                {
613     char tmp_str[MAXLEN];
614     int m;
615     if ((pick\->out_fp = fopen(pick\->out_spec, "w")) == nullptr) {
616         m = MAXLEN \- 30;
617         strnz__cpy(tmp_str, "Can't open pick output file: ", m);
618         m \-= strlen(pick\->in_spec);
619         strnz__cat(tmp_str, pick\->out_spec, m);
620     }
621     for (pick\->obj_idx = 0; pick\->obj_idx < pick\->obj_cnt; pick\->obj_idx++) {
622         if (pick\->f_selected[pick\->obj_idx])
623             fprintf(stdout, "%s\\n", pick\->object[pick\->obj_idx]);
624     }
625     fflush(stdout);
626     if (pick\->out_fp != nullptr)
627         fclose(pick\->out_fp);
628     return (0);
629 }
.PP
.fi

.PP
References \fBMAXLEN\fP, \fBpick\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, and \fBtmp_str\fP\&.
.PP
Referenced by \fBpick_engine()\fP\&.
.SS "void pick_display_chyron (Pick * pick)"

.PP
Displays chyron with page information at bottom of pick window\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBpick\fP\fP Pointer to Pick structure containing chyron information 
.RE
.PP
\fBNote\fP
.RS 4
Constructs a string for the chyron that includes the current page number and total pages\&. Displays the chyron at the bottom of the pick window with reverse video attribute\&. Clears any remaining space on the line after the chyron text\&. 
.RE
.PP

.PP
Definition at line \fB529\fP of file \fBpick_engine\&.c\fP\&.
.nf
529                                      {
530     int l;
531     char tmp_str[MAXLEN];
532     ssnprintf(tmp_str, MAXLEN \- 1, "%s| Page %d of %d ", pick\->chyron\->s,
533               pick\->tbl_page + 1, pick\->tbl_pages);
534     l = strlen(tmp_str);
535     wattron(pick\->win, WA_REVERSE);
536     mvwaddstr(pick\->win, pick\->pg_lines, 0, tmp_str);
537     wattroff(pick\->win, WA_REVERSE);
538     wmove(pick\->win, pick\->pg_lines, l);
539     wclrtoeol(pick\->win);
540 }
.PP
.fi

.PP
References \fBMAXLEN\fP, \fBpick\fP, \fBssnprintf()\fP, and \fBtmp_str\fP\&.
.PP
Referenced by \fBdisplay_page()\fP\&.
.SS "int pick_engine (Init * init)"

.PP
Initializes pick interface, calculates window size and position, and enters picker loop\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP Pointer to Init structure containing pick information 
.RE
.PP
\fBReturns\fP
.RS 4
Count of selected objects on success, -1 if user cancels 
.RE
.PP
\fBNote\fP
.RS 4
Initializes key command strings for chyron display and calculates pick window size and position based on terminal size and pick parameters\&. 

.PP
Opens pick window and displays first page of objects\&. Enters picker loop to handle user input and interactions\&. If user cancels selection, returns -1\&. 

.PP
If user accepts selection, returns count of selected objects\&. 
.RE
.PP
Initialize window and data structures

.PP
Initialize key command strings for chyron display

.PP
Calculate pick window size and position based on terminal size and pick parameters

.PP
Enter picker loop to handle user input and interactions
.PP
Definition at line \fB199\fP of file \fBpick_engine\&.c\fP\&.
.nf
199                             {
201     int rc;
202     int maxy, maxx, win_maxy, win_maxx;
203     int tbl_max_cols, pg_max_objs;
205 
206     getmaxyx(stdscr, maxy, maxx);
209     win_maxy = (maxy * 8) / 10;
210     if (win_maxy > (maxy \- pick\->begy) \- 2)
211         win_maxy = (maxy \- pick\->begy) \- 2;
212     win_maxx = (maxx * 9) / 10;
213     if (win_maxx > (maxx \- pick\->begx) \- 2)
214         win_maxx = (maxx \- pick\->begx) \- 2;
215     if (pick\->tbl_col_width < 4)
216         pick\->tbl_col_width = 4;
217     if (pick\->tbl_col_width > win_maxx \- 2)
218         pick\->tbl_col_width = win_maxx \- 2;
219     // populate the columns in sequence
220     if (pick\->obj_cnt <= win_maxy) {
221         pick\->tbl_lines = pick\->obj_cnt;
222         pick\->tbl_cols = 1;
223     } else {
224         tbl_max_cols = (win_maxx / (pick\->tbl_col_width + 1));
225         pg_max_objs = win_maxy * tbl_max_cols;
226         if (pick\->obj_cnt > pg_max_objs)
227             pick\->tbl_cols = tbl_max_cols;
228         else
229             pick\->tbl_cols = pick\->obj_cnt / win_maxy;
230         pick\->tbl_lines = pick\->obj_cnt / tbl_max_cols;
231     }
232     pick\->tbl_pages = (pick\->tbl_lines / (win_maxy \- 1)) + 1;
233     pick\->pg_lines = (pick\->tbl_lines / pick\->tbl_pages);
234     pick\->win_lines = pick\->pg_lines + 1;
235     pick\->tbl_page = 0;
236     if (pick\->begy == 0)
237         pick\->begy = (LINES \- pick\->win_lines) / 5;
238     else if (pick\->begy + pick\->win_lines > LINES \- 4)
239         pick\->begy = LINES \- pick\->win_lines \- 2;
240     pick\->win_width = (pick\->tbl_col_width + 1) * pick\->tbl_cols;
241 
242     pick\->chyron = new_chyron();
243     set_chyron_key(pick\->chyron, 1, "F1 Help", KEY_F(1));
244     set_chyron_key(pick\->chyron, 9, "F9 Cancel", KEY_F(9));
245     set_chyron_key(pick\->chyron, 10, "F10 Continue", KEY_F(10));
246     if (pick\->tbl_pages > 1) {
247         set_chyron_key(pick\->chyron, 11, "PgUp", KEY_PPAGE);
248         set_chyron_key(pick\->chyron, 12, "PgDn", KEY_NPAGE);
249     }
250     set_chyron_key(pick\->chyron, 13, "Toggle", 32);
251     compile_chyron(pick\->chyron);
252     if (pick\->chyron\->l > win_maxx)
253         pick\->chyron\->l = strnz(pick\->chyron\->s, win_maxx);
254     if (pick\->win_width < pick\->chyron\->l)
255         pick\->win_width = pick\->chyron\->l;
256 
257     if (pick\->begx + pick\->win_width > COLS \- 4)
258         pick\->begx = COLS \- pick\->win_width \- 2;
259     else if (pick\->begx == 0)
260         pick\->begx = (COLS \- pick\->win_width) / 2;
261 
262     rc = open_pick_win(init);
263     if (rc)
264         return (rc);
265     display_page(pick);
266     reverse_object(pick);
267     pick\->obj_idx = 0;
268     pick\->x = 1;
269     mousemask(BUTTON1_CLICKED | BUTTON1_DOUBLE_CLICKED, nullptr);
271     picker(init);
272     if (pick\->select_cnt > 0) {
273         if (pick\->f_out_spec && pick\->out_spec[0])
274             rc = output_objects(pick);
275         if (pick\->f_cmd && pick\->cmd[0])
276             rc = exec_objects(init);
277     }
278     return (rc);
279 }
.PP
.fi

.PP
References \fBcompile_chyron()\fP, \fBdisplay_page()\fP, \fBexec_objects()\fP, \fBinit\fP, \fBnew_chyron()\fP, \fBopen_pick_win()\fP, \fBoutput_objects()\fP, \fBpick\fP, \fBpicker()\fP, \fBreverse_object()\fP, \fBset_chyron_key()\fP, and \fBstrnz()\fP\&.
.PP
Referenced by \fBinit_pick()\fP\&.
.SS "int picker (Init * init)"

.PP
Main loop to handle user input and interactions for pick interface\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP Pointer to Init structure 
.RE
.PP
\fBReturns\fP
.RS 4
Number of selected objects or -1 if user cancels 
.RE
.PP
\fBNote\fP
.RS 4
Handles user input for navigating and selecting objects in the pick interface\&. 

.PP
Supports various key commands for navigation, selection, and accepting/canceling the selection\&. 

.PP
Updates the display accordingly based on user interactions\&. 

.PP
If the user cancels the selection, returns -1\&. 

.PP
If the user accepts the selection, returns the count of selected objects\&. 
.RE
.PP
'q', or KEY_F(9) cancel selection and exit picker

.PP
KEY_F(1) or 'H' Displays help screen for pick interface

.PP
't' or Space Toggles selection of current object

.PP
Enter or KEY_F(10) Accepts current selection and exits picker, returning count of selected objects

.PP
KEY_END Moves selection to last object in list

.PP
'l' or KEY_RIGHT Moves selection to next object in list

.PP
pick->obj_idx += pick->tbl_lines -> next column

.PP
'h' or KEY_LEFT or Backspace Moves selection to previous object in list

.PP
'j' or KEY_DOWN Moves selection to next object in list, 'k' or KEY_UP Moves selection to previous object in list

.PP
'k' or KEY_UP Moves selection to previous object in list

.PP
KEY_NPAGE or 'Ctrl+f' Moves selection to next page of objects,

.PP
KEY_PPAGE or 'Ctrl+b' Moves selection to previous page of objects

.PP
KEY_HOME Moves selection to first object in list

.PP
KEY_LL (lower left of numeric pad) Moves selection to last object in list

.PP
KEY_MOUSE Handles mouse events for selection and chyron key activation
.PP
Definition at line \fB316\fP of file \fBpick_engine\&.c\fP\&.
.nf
316                        {
317     int cmd_key;
318     int display_tbl_page;
319 
320     pick = init\->pick;
321     click_y = click_x = \-1;
322     cmd_key = 0;
323     while (1) {
324         tcflush(tty_fd, TCIFLUSH);
325         if (cmd_key == 0)
326             cmd_key = xwgetch(pick\->win, pick\->chyron);
327         switch (
328             cmd_key) { 
329         case 'q':
330         case 'Q':
331         case KEY_F(9):
332             return \-1;
334         case KEY_F(1):
335         case 'H':
336             display_pick_help(init);
337             display_page(pick);
338             reverse_object(pick);
339             break;
341         case ' ':
342         case 't':
343         case 'T':
344             toggle_object(pick);
345             if (pick\->select_cnt == pick\->select_max)
346                 return pick\->select_cnt;
347             break;
350         case KEY_F(10):
351         case '\\n':
352         case KEY_ENTER:
353             return pick\->select_cnt;
355         case KEY_END:
356             mvwaddstr_fill(pick\->win, pick\->y, pick\->x,
357                            pick\->object[pick\->obj_idx], pick\->tbl_col_width);
358             display_tbl_page = pick\->tbl_page;
359             pick\->obj_idx = pick\->obj_cnt \- 1;
360             pick\->tbl_page = pick\->obj_idx / (pick\->pg_lines * pick\->tbl_cols);
361             pick\->tbl_line = (pick\->obj_idx / pick\->tbl_cols) % pick\->pg_lines;
362             pick\->tbl_col = pick\->obj_idx % pick\->tbl_cols;
363             pick\->y = pick\->tbl_line;
364             if (display_tbl_page != pick\->tbl_page) {
365                 display_page(pick);
366             }
367             reverse_object(pick);
368             break;
370         case 'l':
371         case KEY_RIGHT:
372             mvwaddstr_fill(pick\->win, pick\->y, pick\->x,
373                            pick\->object[pick\->obj_idx], pick\->tbl_col_width);
375             if (pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
376                         (pick\->tbl_col + 1) * pick\->pg_lines + pick\->tbl_line <
377                     pick\->obj_cnt \- 1 &&
378                 pick\->tbl_col < pick\->tbl_cols \- 1)
379                 pick\->tbl_col++;
380             pick\->obj_idx = pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
381                             pick\->tbl_col * pick\->pg_lines + pick\->tbl_line;
382             reverse_object(pick);
383             break;
386         case 'h':
387         case KEY_LEFT:
388         case KEY_BACKSPACE:
389             mvwaddstr_fill(pick\->win, pick\->y, pick\->x,
390                            pick\->object[pick\->obj_idx], pick\->tbl_col_width);
391             if (pick\->tbl_col > 0)
392                 pick\->tbl_col\-\-;
393             pick\->obj_idx = pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
394                             pick\->tbl_col * pick\->pg_lines + pick\->tbl_line;
395             reverse_object(pick);
396             break;
399         case 'j':
400         case KEY_DOWN:
401             mvwaddstr_fill(pick\->win, pick\->y, pick\->x,
402                            pick\->object[pick\->obj_idx], pick\->tbl_col_width);
403             if (pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
404                         pick\->tbl_col * pick\->pg_lines + pick\->tbl_line <
405                     pick\->obj_cnt \- 1 &&
406                 pick\->tbl_line < pick\->pg_lines \- 1)
407                 pick\->tbl_line++;
408             pick\->obj_idx = pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
409                             pick\->tbl_col * pick\->pg_lines + pick\->tbl_line;
410             reverse_object(pick);
411             break;
413         case 'k':
414         case KEY_UP:
415             mvwaddstr_fill(pick\->win, pick\->y, pick\->x,
416                            pick\->object[pick\->obj_idx], pick\->tbl_col_width);
417             if (pick\->tbl_line > 0)
418                 pick\->tbl_line\-\-;
419             pick\->obj_idx = pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
420                             pick\->tbl_col * pick\->pg_lines + pick\->tbl_line;
421             reverse_object(pick);
422             break;
424         case KEY_NPAGE:
425         case '\\06':
426             if (pick\->tbl_pages == 1)
427                 break;
428             if (pick\->tbl_page < pick\->tbl_pages \- 1) {
429                 pick\->tbl_page++;
430                 pick\->pg_line = 0;
431                 pick\->tbl_col = 0;
432             }
433             pick\->obj_idx = pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
434                             pick\->tbl_cols * pick\->pg_line + pick\->tbl_col;
435             display_page(pick);
436             reverse_object(pick);
437             break;
440         case KEY_PPAGE:
441         case '\\02':
442             if (pick\->tbl_pages == 1)
443                 break;
444             if (pick\->tbl_page > 0)
445                 pick\->tbl_page\-\-;
446             pick\->obj_idx = pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
447                             pick\->tbl_cols * pick\->pg_line + pick\->tbl_col;
448             display_page(pick);
449             reverse_object(pick);
450             break;
452         case KEY_HOME:
453             pick\->tbl_page = 0;
454             pick\->tbl_line = 0;
455             pick\->tbl_col = 0;
456             pick\->obj_idx = pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
457                             pick\->tbl_cols * pick\->pg_line + pick\->tbl_col;
458             display_page(pick);
459             reverse_object(pick);
460             break;
463         case KEY_LL:
464             pick\->tbl_page = pick\->tbl_pages \- 1;
465             pick\->obj_idx = pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
466                             pick\->tbl_cols * pick\->pg_line + pick\->tbl_col;
467             display_page(pick);
468             reverse_object(pick);
469             break;
472         case KEY_MOUSE:
473             if (click_y == \-1 || click_x == \-1)
474                 break;
475             unreverse_object(pick);
476             pick\->y = click_y;
477             pick\->tbl_col = (click_x \- 1) / (pick\->tbl_col_width + 1);
478             if (pick\->tbl_col < 0 || pick\->tbl_col >= pick\->tbl_cols)
479                 break;
480             pick\->obj_idx = pick\->tbl_page * pick\->pg_lines * pick\->tbl_cols +
481                             pick\->tbl_col * pick\->pg_lines + pick\->y;
482             toggle_object(pick);
483             reverse_object(pick);
484             if (pick\->select_cnt == pick\->select_max)
485                 return pick\->select_cnt;
486             wrefresh(pick\->win);
487             click_y = click_x = \-1;
488             break;
489         default:
490             break;
491         }
492         cmd_key = 0;
493     }
494     return 0;
495 }
.PP
.fi

.PP
References \fBclick_x\fP, \fBclick_y\fP, \fBcmd_key\fP, \fBdisplay_page()\fP, \fBdisplay_pick_help()\fP, \fBinit\fP, \fBmvwaddstr_fill()\fP, \fBpick\fP, \fBreverse_object()\fP, \fBtoggle_object()\fP, \fBtty_fd\fP, \fBunreverse_object()\fP, and \fBxwgetch()\fP\&.
.PP
Referenced by \fBpick_engine()\fP\&.
.SS "int read_pick_input (Init * init)"

.PP
Reads pick input from file pointer and saves objects into pick structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP Pointer to Init structure containing pick information 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 if no objects were read 
.RE
.PP
\fBNote\fP
.RS 4
Reads lines from pick->in_fp and saves them as objects in the pick structure using save_object function\&. If no objects are read, returns -1\&. Otherwise, sets obj_cnt to the number of objects read and resets obj_idx to 0 before returning 0\&. 
.RE
.PP

.PP
Definition at line \fB165\fP of file \fBpick_engine\&.c\fP\&.
.nf
165                                 {
166     int i;
167 
168     Pick *pick = init\->pick;
169     pick\->select_cnt = 0;
170     pick\->obj_cnt = pick\->pg_lines = pick\->tbl_cols = 0;
171     pick\->obj_idx = pick\->tbl_page = pick\->y = pick\->tbl_col = pick\->x = 0;
172     pick\->tbl_pages = 1;
173 
174     if (pick\->in_fp) {
175         while (fgets(pick\->in_buf, sizeof(pick\->in_buf), pick\->in_fp) !=
176                nullptr)
177             save_object(pick, pick\->in_buf);
178     } else
179         for (i = 1; i < pick\->argc; i++)
180             save_object(pick, pick\->argv[i]);
181     if (pick\->in_fp != nullptr)
182         fclose(pick\->in_fp);
183     if (!pick\->obj_idx)
184         return (\-1);
185     pick\->obj_cnt = pick\->obj_idx;
186     pick\->obj_idx = 0;
187     return 0;
188 }
.PP
.fi

.PP
References \fBinit\fP, \fBpick\fP, and \fBsave_object()\fP\&.
.PP
Referenced by \fBinit_pick()\fP\&.
.SS "void reverse_object (Pick * pick)"

.PP
Reverses the display of the currently selected object in pick window\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBpick\fP\fP Pointer to Pick structure containing object and display information 
.RE
.PP
\fBNote\fP
.RS 4
Calculates the x coordinate for the currently selected object based on the current table column and column width\&. Moves the cursor to the object's position in the pick window, turns on reverse video attribute, and displays the object's text\&. Turns off reverse video attribute and refreshes the pick window to show the updated display\&. Moves the cursor back to the position before the object text for potential further interactions\&. 
.RE
.PP

.PP
Definition at line \fB550\fP of file \fBpick_engine\&.c\fP\&.
.nf
550                                 {
551     pick\->x = pick\->tbl_col * (pick\->tbl_col_width + 1) + 1;
552     pick\->tbl_line = (pick\->obj_idx / pick\->tbl_cols) % pick\->pg_lines;
553     pick\->y = pick\->tbl_line;
554     wmove(pick\->win, pick\->y, pick\->x);
555     wattron(pick\->win, WA_REVERSE);
556     mvwaddstr_fill(pick\->win, pick\->y, pick\->x, pick\->object[pick\->obj_idx],
557                    pick\->tbl_col_width);
558     wattroff(pick\->win, WA_REVERSE);
559     wrefresh(pick\->win);
560     wmove(pick\->win, pick\->y, pick\->x \- 1);
561 }
.PP
.fi

.PP
References \fBmvwaddstr_fill()\fP, and \fBpick\fP\&.
.PP
Referenced by \fBpick_engine()\fP, and \fBpicker()\fP\&.
.SS "void save_object (Pick * pick, char * s)"

.PP
Saves a string as an object in the pick structure\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBpick\fP\fP Pointer to Pick structure 
.br
\fIs\fP String to save as an object 
.RE
.PP
\fBNote\fP
.RS 4
If the current object index is less than the maximum allowed, saves the string as an object in the pick structure\&. Updates the column width if necessary and marks the object as not selected\&. Increments the object index for the next object to be saved\&. 
.RE
.PP

.PP
Definition at line \fB287\fP of file \fBpick_engine\&.c\fP\&.
.nf
287                                       {
288     int l;
289 
290     if (pick\->obj_idx < OBJ_MAXCNT \- 1) {
291         l = strlen(s);
292         if (l > OBJ_MAXLEN \- 1)
293             s[OBJ_MAXLEN \- 1] = '\\0';
294         if (l > pick\->tbl_col_width)
295             pick\->tbl_col_width = l;
296         if (l < 1)
297             l = 1;
298         pick\->object[pick\->obj_idx] = (char *)calloc(l + 1, sizeof(char));
299         strnz__cpy(pick\->object[pick\->obj_idx], s, l);
300         pick\->f_selected[pick\->obj_idx] = FALSE;
301         pick\->obj_idx++;
302     }
303 }
.PP
.fi

.PP
References \fBFALSE\fP, \fBpick\fP, and \fBstrnz__cpy()\fP\&.
.PP
Referenced by \fBread_pick_input()\fP\&.
.SS "void toggle_object (Pick * pick)"

.PP
Toggles the selection state of the currently selected object in pick window\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBpick\fP\fP Pointer to Pick structure containing object and selection information 
.RE
.PP
\fBNote\fP
.RS 4
Calculates the x coordinate for the currently selected object based on the current table column and column width\&. If the object is currently selected, it is deselected by updating the selection count, marking it as not selected, and displaying a space before the object text\&. If the object is not currently selected, it is selected by updating the selection count, marking it as selected, and displaying an asterisk before the object text\&. Refreshes the pick window to show the updated display\&. Moves the cursor back to the position before the object text for potential further interactions\&. 
.RE
.PP

.PP
Definition at line \fB592\fP of file \fBpick_engine\&.c\fP\&.
.nf
592                                {
593     pick\->x = pick\->tbl_col * (pick\->tbl_col_width + 1) + 1;
594     if (pick\->f_selected[pick\->obj_idx]) {
595         pick\->select_cnt\-\-;
596         pick\->f_selected[pick\->obj_idx] = FALSE;
597         mvwaddstr(pick\->win, pick\->y, pick\->x \- 1, " ");
598     } else {
599         pick\->select_cnt++;
600         pick\->f_selected[pick\->obj_idx] = true;
601         mvwaddstr(pick\->win, pick\->y, pick\->x \- 1, "*");
602     }
603 }
.PP
.fi

.PP
References \fBFALSE\fP, and \fBpick\fP\&.
.PP
Referenced by \fBpicker()\fP\&.
.SS "void unreverse_object (Pick * pick)"

.PP
Unreverses the display of the currently selected object in pick window\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBpick\fP\fP Pointer to Pick structure containing object and display information 
.RE
.PP
\fBNote\fP
.RS 4
Calculates the x coordinate for the currently selected object based on the current table column and column width\&. Moves the cursor to the object's position in the pick window and displays the object's text without reverse video attribute\&. Refreshes the pick window to show the updated display\&. Moves the cursor back to the position before the object text for potential further interactions\&. 
.RE
.PP

.PP
Definition at line \fB572\fP of file \fBpick_engine\&.c\fP\&.
.nf
572                                   {
573     pick\->x = pick\->tbl_col * (pick\->tbl_col_width + 1) + 1;
574     wmove(pick\->win, pick\->y, pick\->x);
575     mvwaddstr_fill(pick\->win, pick\->y, pick\->x, pick\->object[pick\->obj_idx],
576                    pick\->tbl_col_width);
577     wrefresh(pick\->win);
578     wmove(pick\->win, pick\->y, pick\->x \- 1);
579 }
.PP
.fi

.PP
References \fBmvwaddstr_fill()\fP, and \fBpick\fP\&.
.PP
Referenced by \fBpicker()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "int calculated_idx"

.PP
Definition at line \fB20\fP of file \fBpick_engine\&.c\fP\&.
.SS "int obj_idx"

.PP
Definition at line \fB20\fP of file \fBpick_engine\&.c\fP\&.
.SS "char const pagers_editors[12][10]"
\fBInitial value:\fP
.nf
= {"view", "mview", "less", "more",
           "vi",   "vim",   "nano", "nvim",
           "pico", "emacs", "edit", ""}
.PP
.fi

.PP
Definition at line \fB37\fP of file \fBpick_engine\&.c\fP\&.
.nf
37                                   {"view", "mview", "less", "more",
38                                      "vi",   "vim",   "nano", "nvim",
39                                      "pico", "emacs", "edit", ""};
.PP
.fi

.SS "int pg_lines"

.PP
Definition at line \fB19\fP of file \fBpick_engine\&.c\fP\&.
.SS "int pipe_fd[2]"

.PP
Definition at line \fB35\fP of file \fBpick_engine\&.c\fP\&.
.PP
Referenced by \fBform_calculate()\fP, \fBinit_pick()\fP, and \fBview_init_input()\fP\&.
.SS "int tbl_col"

.PP
Definition at line \fB19\fP of file \fBpick_engine\&.c\fP\&.
.SS "int tbl_cols"

.PP
Definition at line \fB19\fP of file \fBpick_engine\&.c\fP\&.
.SS "int tbl_line"

.PP
Definition at line \fB19\fP of file \fBpick_engine\&.c\fP\&.
.SS "int tbl_page"

.PP
Definition at line \fB19\fP of file \fBpick_engine\&.c\fP\&.
.SS "int tbl_pages"

.PP
Definition at line \fB19\fP of file \fBpick_engine\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
