.TH "src/test/rbox.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/rbox.c \- Display box with rounded corners\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <wchar\&.h>\fP
.br
\fR#include <locale\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBW_HO\fP   L'\\x2500'"
.br
.ti -1c
.RI "#define \fBBW_VE\fP   L'\\x2502'"
.br
.ti -1c
.RI "#define \fBBW_TL\fP   L'\\x250C'"
.br
.ti -1c
.RI "#define \fBBW_TR\fP   L'\\x2510'"
.br
.ti -1c
.RI "#define \fBBW_BL\fP   L'\\x2514'"
.br
.ti -1c
.RI "#define \fBBW_BR\fP   L'\\x2518'"
.br
.ti -1c
.RI "#define \fBBW_RTL\fP   L'\\x256d'"
.br
.ti -1c
.RI "#define \fBBW_RTR\fP   L'\\x256e'"
.br
.ti -1c
.RI "#define \fBBW_RBL\fP   L'\\x2570'"
.br
.ti -1c
.RI "#define \fBBW_RBR\fP   L'\\x256f'"
.br
.ti -1c
.RI "#define \fBBW_LT\fP   L'\\x251C'"
.br
.ti -1c
.RI "#define \fBBW_TT\fP   L'\\x252C'"
.br
.ti -1c
.RI "#define \fBBW_RT\fP   L'\\x2524'"
.br
.ti -1c
.RI "#define \fBBW_CR\fP   L'\\x253C'"
.br
.ti -1c
.RI "#define \fBBW_BT\fP   L'\\x2534'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "Uses Unicode wide box drawing characters to to draw a rectangle\&. "
.in -1c
.SH "Detailed Description"
.PP 
Display box with rounded corners\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBrbox\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BW_BL   L'\\x2514'"
Bottom left corner1 
.PP
Definition at line \fB15\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_BR   L'\\x2518'"
Bottom right corner 
.PP
Definition at line \fB16\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_BT   L'\\x2534'"
Bottom tee 
.PP
Definition at line \fB25\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_CR   L'\\x253C'"
Cross 
.PP
Definition at line \fB24\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_HO   L'\\x2500'"
Horizontal line 
.PP
Definition at line \fB11\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_LT   L'\\x251C'"
Left tee 
.PP
Definition at line \fB21\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_RBL   L'\\x2570'"
Rounded bottom left 
.PP
Definition at line \fB19\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_RBR   L'\\x256f'"
Rounded bottom right 
.PP
Definition at line \fB20\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_RT   L'\\x2524'"
Right tee 
.PP
Definition at line \fB23\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_RTL   L'\\x256d'"
Rounded top left 
.PP
Definition at line \fB17\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_RTR   L'\\x256e'"
Rounded top right 
.PP
Definition at line \fB18\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_TL   L'\\x250C'"
op left corner 
.PP
Definition at line \fB13\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_TR   L'\\x2510'"
Top right corner 
.PP
Definition at line \fB14\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_TT   L'\\x252C'"
Top tee 
.PP
Definition at line \fB22\fP of file \fBrbox\&.c\fP\&.
.SS "#define BW_VE   L'\\x2502'"
Vertical line 
.PP
Definition at line \fB12\fP of file \fBrbox\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Uses Unicode wide box drawing characters to to draw a rectangle\&. 
.PP
\fBNote\fP
.RS 4
The use case for this program is simply to determine if a specific terminal or terminal emulator can display this type of character\&. 
.RE
.PP
< Rounded top left

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Top tee

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Rounded top right

.PP
< Vertical line

.PP
< Cross

.PP
< Vertical line

.PP
< Left tee

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Right tee

.PP
< Left tee

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Cross

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Right tee

.PP
< Rounded bottom left

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Bottom tee

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Horizontal line

.PP
< Rounded bottom right
.PP
Definition at line \fB35\fP of file \fBrbox\&.c\fP\&.
.nf
35                                 {
36     setlocale(LC_CTYPE, "en_US\&.UTF\-8");
37     wchar_t box_top[] = {BW_RTL, BW_HO, BW_HO, BW_HO,  BW_TT,
38                          BW_HO,  BW_HO, BW_HO, BW_RTR, L'\\0'};
39     wchar_t box_line[] = {BW_VE, L' ', L' ', L' ',  BW_CR,
40                           L' ',  L' ', L' ', BW_VE, L'\\0'};
41     wchar_t box_middle[] = {BW_LT, BW_HO, BW_HO, BW_HO, BW_HO,
42                             BW_HO, BW_HO, BW_HO, BW_RT, L'\\0'};
43     wchar_t box_middle_cr[] = {BW_LT, BW_HO, BW_HO, BW_HO, BW_CR,
44                                BW_HO, BW_HO, BW_HO, BW_RT, L'\\0'};
45     wchar_t box_bottom[] = {BW_RBL, BW_HO, BW_HO, BW_HO,  BW_BT,
46                             BW_HO,  BW_HO, BW_HO, BW_RBR, L'\\0'};
47     wprintf(L"%ls\\n", box_top);
48     wprintf(L"%ls\\n", box_line);
49     wprintf(L"%ls\\n", box_middle_cr);
50     wprintf(L"%ls\\n", box_bottom);
51     return 0;
52 }
.PP
.fi

.PP
References \fBBW_BT\fP, \fBBW_CR\fP, \fBBW_HO\fP, \fBBW_LT\fP, \fBBW_RBL\fP, \fBBW_RBR\fP, \fBBW_RT\fP, \fBBW_RTL\fP, \fBBW_RTR\fP, \fBBW_TT\fP, and \fBBW_VE\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
