.TH "src/test/rfc3339.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/rfc3339.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <time\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBString\fP"
.br
.RI "The \fBString\fP structure represents a string object with a pointer to the string and its allocated length\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBString\fP \fBmk_string\fP (size_t l)"
.br
.RI "Create a \fBString\fP struct with a dynamically allocated string\&. "
.ti -1c
.RI "\fBString\fP \fBto_string\fP (const char *s)"
.br
.RI "Convert C string to \fBString\fP struct\&. "
.ti -1c
.RI "void \fBfree_string\fP (\fBString\fP str)"
.br
.RI "Free the dynamically allocated \fBString\fP\&. "
.ti -1c
.RI "void \fBget_rfc3339_str\fP (\fBString\fP timestamp_s)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBString\fP struct and functions fn to_string(char *s) -> \fBString\fP Convert C string to \fBString\fP struct 
.PP
\fBParameters\fP
.RS 4
\fI\fP s C string 
.RE
.PP
\fBNote\fP
.RS 4
: The returned \fBString\fP struct contains a dynamically allocated copy of the input string\&. 

.PP
: the caller is responsible for freeing the allocated memory\&. 
.RE
.PP
\fBSee also\fP
.RS 4
: \fBfree_string\fP 
.RE
.PP
\fBReturns\fP
.RS 4
: \fBString\fP struct 
.RE
.PP

.PP
Definition in file \fBrfc3339\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void free_string (\fBString\fP str)"

.PP
Free the dynamically allocated \fBString\fP\&. fn \fBfree_string(String str)\fP -> \fBString\fP Free the memory allocated for a \fBString\fP struct 
.PP
\fBParameters\fP
.RS 4
\fI\fP str \fBString\fP struct to free 
.RE
.PP
\fBNote\fP
.RS 4
: This function frees the memory allocated for the string in the \fBString\fP struct and sets its length to 0 and pointer to NULL\&. 
.RE
.PP
\fBReturns\fP
.RS 4
: \fBString\fP struct with NULL pointer and length 0 
.RE
.PP

.PP
Definition at line \fB87\fP of file \fBrfc3339\&.c\fP\&.
.nf
87                              {
88     free(str\&.s);
89     str\&.l = 0;
90     str\&.s = NULL;
91     return str;
92 }
.PP
.fi

.PP
References \fBString::l\fP, and \fBString::s\fP\&.
.PP
Referenced by \fBget_rfc3339_str()\fP, and \fBmain()\fP\&.
.SS "void get_rfc3339_str (\fBString\fP timestamp_s)"

.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/test/rfc3339\&.c\fP\&.
.PP
Definition at line \fB99\fP of file \fBrfc3339\&.c\fP\&.
.nf
99                                          {
100     time_t now;
101     struct tm *tms;
102     int use_localtime = 0;
103     String z_str1, z_str2;
104     z_str1 = mk_string(30);
105     z_str2 = mk_string(30);
106     int i = 0, j;
107 
108     time(&now);
109     tms = localtime((time_t *)&now);
110     strftime(z_str1\&.s, z_str1\&.l, "%z", tms);
111     for (j = 0; j < 6; j++) {
112         if (i == 3)
113             z_str2\&.s[i++] = ':';
114         z_str2\&.s[i++] = z_str1\&.s[j];
115     }
116     z_str2\&.s[6] = '\\0';
117     sprintf(timestamp_s\&.s, "%04d\-%02d\-%02dT%02d:%02d:%02d%s",
118             tms\->tm_year + 1900, tms\->tm_mon + 1, tms\->tm_mday, tms\->tm_hour,
119             tms\->tm_min, tms\->tm_sec, z_str2\&.s);
120     free_string(z_str1);
121     free_string(z_str2);
122 }
.PP
.fi

.PP
References \fBfree_string()\fP, \fBString::l\fP, \fBmk_string()\fP, and \fBString::s\fP\&.
.PP
Referenced by \fBmain()\fP\&.
.SS "int main ()"

.PP
Definition at line \fB123\fP of file \fBrfc3339\&.c\fP\&.
.nf
123            {
124     String timestamp_s;
125     timestamp_s = mk_string(30);
126     get_rfc3339_str(timestamp_s);
127     printf("%s\\n", timestamp_s\&.s);
128     free_string(timestamp_s);
129 }
.PP
.fi

.PP
References \fBfree_string()\fP, \fBget_rfc3339_str()\fP, \fBmk_string()\fP, and \fBString::s\fP\&.
.SS "\fBString\fP mk_string (size_t l)"

.PP
Create a \fBString\fP struct with a dynamically allocated string\&. fn \fBmk_string(size_t l)\fP -> \fBString\fP Create an empty \fBString\fP struct with specified length 
.PP
\fBParameters\fP
.RS 4
\fI\fP l Length of the string (excluding null terminator) 
.RE
.PP
\fBNote\fP
.RS 4
: The returned \fBString\fP struct contains a dynamically allocated string of length l + 1 (including null terminator)\&. 

.PP
: the caller is responsible for freeing the allocated memory\&. 
.RE
.PP
\fBSee also\fP
.RS 4
: \fBfree_string\fP 
.RE
.PP
\fBReturns\fP
.RS 4
: \fBString\fP struct 
.RE
.PP

.PP
Definition at line \fB59\fP of file \fBrfc3339\&.c\fP\&.
.nf
59                            {
60     String str;
61     str\&.l = l + 1;
62     str\&.s = (char *)malloc(str\&.l);
63     str\&.s[0] = '\\0';
64     return str;
65 }
.PP
.fi

.PP
References \fBString::l\fP, and \fBString::s\fP\&.
.PP
Referenced by \fBget_rfc3339_str()\fP, and \fBmain()\fP\&.
.SS "\fBString\fP to_string (const char * s)"

.PP
Convert C string to \fBString\fP struct\&. fn \fBto_string(const char *s)\fP -> \fBString\fP Convert C string to \fBString\fP struct 
.PP
\fBParameters\fP
.RS 4
\fI\fP s C string 
.RE
.PP
\fBNote\fP
.RS 4
: The returned \fBString\fP struct contains a dynamically allocated copy of the input string\&. 

.PP
: the caller is responsible for freeing the allocated memory\&. 
.RE
.PP
\fBSee also\fP
.RS 4
: \fBfree_string\fP 
.RE
.PP
\fBReturns\fP
.RS 4
: \fBString\fP struct 
.RE
.PP

.PP
Definition at line \fB74\fP of file \fBrfc3339\&.c\fP\&.
.nf
74                                 {
75     String str;
76     str\&.l = strlen(s) + 1;
77     str\&.s = (char *)malloc(str\&.l);
78     strcpy(str\&.s, s);
79     return str;
80 }
.PP
.fi

.PP
References \fBString::l\fP, and \fBString::s\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
