.TH "RGB" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGB \- Represents an \fBRGB\fP color with 8-bit components\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/cm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBr\fP"
.br
.ti -1c
.RI "int \fBg\fP"
.br
.ti -1c
.RI "int \fBb\fP"
.br
.ti -1c
.RI "unsigned char \fBr\fP"
.br
.ti -1c
.RI "unsigned char \fBg\fP"
.br
.ti -1c
.RI "unsigned char \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an \fBRGB\fP color with 8-bit components\&. 
.PP
Definition at line \fB140\fP of file \fBcm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int RGB::b"
blue component (0-255) 
.PP
Definition at line \fB143\fP of file \fBcm\&.h\fP\&.
.PP
Referenced by \fBapply_gamma()\fP, \fBhex_clr_str_to_rgb()\fP, \fBinit_hex_clr()\fP, \fBmain()\fP, \fBopen_curses()\fP, \fBparse_ansi_str()\fP, \fBrgb_to_curses_clr()\fP, \fBrgb_to_xterm256_idx()\fP, \fBxterm256_idx_to_rgb()\fP, and \fBxterm256_to_rgb()\fP\&.
.SS "unsigned char RGB::b"

.PP
Definition at line \fB21\fP of file \fBcolor\&.c\fP\&.
.SS "int RGB::g"
green component (0-255) 
.PP
Definition at line \fB142\fP of file \fBcm\&.h\fP\&.
.PP
Referenced by \fBapply_gamma()\fP, \fBhex_clr_str_to_rgb()\fP, \fBinit_hex_clr()\fP, \fBmain()\fP, \fBopen_curses()\fP, \fBparse_ansi_str()\fP, \fBrgb_to_curses_clr()\fP, \fBrgb_to_xterm256_idx()\fP, \fBxterm256_idx_to_rgb()\fP, and \fBxterm256_to_rgb()\fP\&.
.SS "unsigned char RGB::g"

.PP
Definition at line \fB20\fP of file \fBcolor\&.c\fP\&.
.SS "int RGB::r"
red component (0-255) 
.PP
Definition at line \fB141\fP of file \fBcm\&.h\fP\&.
.PP
Referenced by \fBapply_gamma()\fP, \fBhex_clr_str_to_rgb()\fP, \fBinit_hex_clr()\fP, \fBmain()\fP, \fBopen_curses()\fP, \fBparse_ansi_str()\fP, \fBrgb_to_curses_clr()\fP, \fBrgb_to_xterm256_idx()\fP, \fBxterm256_idx_to_rgb()\fP, and \fBxterm256_to_rgb()\fP\&.
.SS "unsigned char RGB::r"

.PP
Definition at line \fB19\fP of file \fBcolor\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
