.TH "src/sig.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sig.c \- signal handling for interrupt signals  

.SH SYNOPSIS
.br
.PP
\fR#include <cm\&.h>\fP
.br
\fR#include <signal\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <termios\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsig_dfl_mode\fP ()"
.br
.RI "Set signal handlers to default behavior\&. "
.ti -1c
.RI "void \fBsig_prog_mode\fP ()"
.br
.RI "Set up signal handlers for interrupt signals\&. "
.ti -1c
.RI "void \fBsignal_handler\fP (int sig_num)"
.br
.RI "Signal handler for interrupt signals\&. "
.ti -1c
.RI "bool \fBhandle_signal\fP (int sig_num)"
.br
.RI "Handle received signals and prompt user for action\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile sig_atomic_t \fBsig_received\fP = 0"
.br
.ti -1c
.RI "bool \fBf_curses_open\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
signal handling for interrupt signals 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBsig\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "bool handle_signal (int sig_num)"

.PP
Handle received signals and prompt user for action\&. 
.PP
Definition at line \fB105\fP of file \fBsig\&.c\fP\&.
.nf
105                                 {
106     switch (sig_num) {
107     case SIGINT:
108         strnz__cpy(em1, "SIGINT \- Interrupt from keyboard", MAXLEN \- 1);
109         break;
110     case SIGTERM:
111         strnz__cpy(em1, "SIGTERM \- Termination signal", MAXLEN \- 1);
112         break;
113     case SIGQUIT:
114         strnz__cpy(em1, "SIGQUIT \- Quit from keyboard", MAXLEN \- 1);
115         break;
116     case SIGSEGV:
117         strnz__cpy(em1, "SIGSEGV \- Segmentation fault", MAXLEN \- 1);
118         break;
119     case SIGUSR1:
120         strnz__cpy(em1, "SIGUSR1 \- User Signal 1", MAXLEN \- 1);
121         break;
122     default:
123         strnz__cpy(em1, "unknown signal", MAXLEN \- 1);
124         break;
125     }
126     if (!f_curses_open)
127         restore_shell_tioctl();
128     em0[0] = '\\0';
129     ssnprintf(em0, MAXLEN \- 1, "Caught signal %d\\n", sig_num);
130     strnz__cpy(em2, "Press 'q' or F9 to exit, any other key to continue",
131                MAXLEN \- 1);
132     sig_received = 0;
133     return true;
134 }
.PP
.fi

.PP
References \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBf_curses_open\fP, \fBMAXLEN\fP, \fBrestore_shell_tioctl()\fP, \fBsig_received\fP, \fBssnprintf()\fP, and \fBstrnz__cpy()\fP\&.
.PP
Referenced by \fBxwgetch()\fP\&.
.SS "void sig_dfl_mode ()"

.PP
Set signal handlers to default behavior\&. 
.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/enterstr\&.c\fP\&.
.PP
Definition at line \fB23\fP of file \fBsig\&.c\fP\&.
.nf
23                     {
24     struct sigaction sa;
25 
26     sa\&.sa_handler = SIG_DFL;
27     sigemptyset(&sa\&.sa_mask);
28     sa\&.sa_flags = SA_RESTART;
29     sigaction(SIGINT, &sa, nullptr);
30     sigaction(SIGTERM, &sa, nullptr);
31     sigaction(SIGQUIT, &sa, nullptr);
32     sigaction(SIGUSR1, &sa, nullptr);
33     sa\&.sa_flags = SA_SIGINFO;
34     sigaction(SIGSEGV, &sa, nullptr);
35 }
.PP
.fi

.PP
Referenced by \fBabend()\fP, \fBdestroy_curses()\fP, \fBfork_exec()\fP, \fBmain()\fP, and \fBuser_end()\fP\&.
.SS "void sig_prog_mode ()"

.PP
Set up signal handlers for interrupt signals\&. Upon receiving an interrupt signal (SIGINT, SIGTERM, SIGQUIT), the program will prompt the user to either exit the program or continue execution\&. If the user chooses to exit, a confirmation prompt will be displayed\&. If the user opts to continue, the program will resume normal operation\&. 
.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/enterstr\&.c\fP\&.
.PP
Definition at line \fB42\fP of file \fBsig\&.c\fP\&.
.nf
42                      {
43     struct sigaction sa;
44 
45     memset(&sa, 0, sizeof(sa));
46     sa\&.sa_handler = signal_handler;
47     sigemptyset(&sa\&.sa_mask);
48     sa\&.sa_flags = SA_RESTART;
49     if (sigaction(SIGINT, &sa, nullptr) == \-1) {
50         abend(\-1, "sigaction SIGINT failed");
51         exit(EXIT_FAILURE);
52     }
53     if (sigaction(SIGTERM, &sa, nullptr) == \-1) {
54         abend(\-1, "sigaction SIGTERM failed");
55         exit(EXIT_FAILURE);
56     };
57     if (sigaction(SIGQUIT, &sa, nullptr) == \-1) {
58         abend(\-1, "sigaction SIGQUIT failed");
59         exit(EXIT_FAILURE);
60     }
61     if (sigaction(SIGUSR1, &sa, nullptr) == \-1) {
62         abend(\-1, "sigaction SIGUSR1 failed");
63         exit(EXIT_FAILURE);
64     }
65     sa\&.sa_flags = SA_SIGINFO; // Set the flag to receive siginfo_t
66     if (sigaction(SIGSEGV, &sa, nullptr) == \-1) {
67         abend(\-1, "sigaction SIGSEGV failed");
68         exit(EXIT_FAILURE);
69     }
70 }
.PP
.fi

.PP
References \fBabend()\fP, and \fBsignal_handler()\fP\&.
.PP
Referenced by \fBexec_objects()\fP, \fBfork_exec()\fP, \fBinit_pick()\fP, and \fBmain()\fP\&.
.SS "void signal_handler (int sig_num)"

.PP
Signal handler for interrupt signals\&. 
.PP
Definition at line \fB72\fP of file \fBsig\&.c\fP\&.
.nf
72                                  {
73     switch (sig_num) {
74     case SIGINT:
75         sig_received = SIGINT;
76         break;
77     case SIGTERM:
78         sig_received = SIGTERM;
79         break;
80     case SIGQUIT:
81         sig_received = SIGQUIT;
82         break;
83     case SIGSEGV:
84         tcsetattr(0, TCSANOW, &shell_tioctl);
85         char *msg1 = "\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n";
86         write(STDERR_FILENO, msg1, strlen(msg1));
87         char *msg2 = "________ SIGSEGV \- Segmentation fault \- Generating core "
88                      "dump ________\\n\\n";
89         write(STDERR_FILENO, msg2, strlen(msg2));
90         struct sigaction sa;
91         sa\&.sa_handler = SIG_DFL;
92         sigemptyset(&sa\&.sa_mask);
93         sa\&.sa_flags = 0;
94         sigaction(SIGSEGV, &sa, NULL);
95         kill(getpid(), SIGSEGV); // Re\-raise the signal
96         _exit(EXIT_FAILURE);
97     case SIGUSR1:
98         sig_received = SIGUSR1;
99         break;
100     default:
101         return;
102     }
103 }
.PP
.fi

.PP
References \fBshell_tioctl\fP, and \fBsig_received\fP\&.
.PP
Referenced by \fBsig_prog_mode()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "bool f_curses_open = false"

.PP
Definition at line \fB20\fP of file \fBsig\&.c\fP\&.
.PP
Referenced by \fBdestroy_curses()\fP, \fBdisplay_error()\fP, \fBhandle_signal()\fP, \fBopen_curses()\fP, and \fBPerror()\fP\&.
.SS "volatile sig_atomic_t sig_received = 0"

.PP
Definition at line \fB18\fP of file \fBsig\&.c\fP\&.
.PP
Referenced by \fBhandle_signal()\fP, \fBsignal_handler()\fP, and \fBxwgetch()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
