.TH "SIO" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SIO \- The \fBSIO\fP structure encapsulates various aspects of the terminal's state and configuration, including color management, file pointers, and terminal device information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/cm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfg_color\fP"
.br
.ti -1c
.RI "int \fBbg_color\fP"
.br
.ti -1c
.RI "int \fBbo_color\fP"
.br
.ti -1c
.RI "double \fBred_gamma\fP"
.br
.ti -1c
.RI "double \fBgreen_gamma\fP"
.br
.ti -1c
.RI "double \fBblue_gamma\fP"
.br
.ti -1c
.RI "double \fBgray_gamma\fP"
.br
.ti -1c
.RI "char \fBblack\fP [8]"
.br
.ti -1c
.RI "char \fBred\fP [8]"
.br
.ti -1c
.RI "char \fBgreen\fP [8]"
.br
.ti -1c
.RI "char \fByellow\fP [8]"
.br
.ti -1c
.RI "char \fBblue\fP [8]"
.br
.ti -1c
.RI "char \fBmagenta\fP [8]"
.br
.ti -1c
.RI "char \fBcyan\fP [8]"
.br
.ti -1c
.RI "char \fBwhite\fP [8]"
.br
.ti -1c
.RI "char \fBorange\fP [8]"
.br
.ti -1c
.RI "char \fBbblack\fP [8]"
.br
.ti -1c
.RI "char \fBbred\fP [8]"
.br
.ti -1c
.RI "char \fBbgreen\fP [8]"
.br
.ti -1c
.RI "char \fBbyellow\fP [8]"
.br
.ti -1c
.RI "char \fBbblue\fP [8]"
.br
.ti -1c
.RI "char \fBbmagenta\fP [8]"
.br
.ti -1c
.RI "char \fBbcyan\fP [8]"
.br
.ti -1c
.RI "char \fBbwhite\fP [8]"
.br
.ti -1c
.RI "char \fBborange\fP [8]"
.br
.ti -1c
.RI "char \fBbg\fP [8]"
.br
.ti -1c
.RI "char \fBabg\fP [8]"
.br
.ti -1c
.RI "char \fBtty_name\fP [256]"
.br
.ti -1c
.RI "FILE * \fBstdin_fp\fP"
.br
.ti -1c
.RI "FILE * \fBstdout_fp\fP"
.br
.ti -1c
.RI "FILE * \fBstderr_fp\fP"
.br
.ti -1c
.RI "FILE * \fBtty_fp\fP"
.br
.ti -1c
.RI "int \fBstdin_fd\fP"
.br
.ti -1c
.RI "int \fBstdout_fd\fP"
.br
.ti -1c
.RI "int \fBstderr_fd\fP"
.br
.ti -1c
.RI "int \fBtty_fd\fP"
.br
.ti -1c
.RI "int \fBclr_cnt\fP"
.br
.ti -1c
.RI "int \fBclr_pair_cnt\fP"
.br
.ti -1c
.RI "int \fBclr_idx\fP"
.br
.ti -1c
.RI "int \fBclr_pair_idx\fP"
.br
.ti -1c
.RI "int \fBcp_default\fP"
.br
.ti -1c
.RI "int \fBcp_norm\fP"
.br
.ti -1c
.RI "int \fBcp_reverse\fP"
.br
.ti -1c
.RI "int \fBcp_box\fP"
.br
.ti -1c
.RI "int \fBcp_bold\fP"
.br
.ti -1c
.RI "int \fBcp_title\fP"
.br
.ti -1c
.RI "int \fBcp_highlight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBSIO\fP structure encapsulates various aspects of the terminal's state and configuration, including color management, file pointers, and terminal device information\&. 


.PP
\fBNote\fP
.RS 4
The \fBSIO\fP structure serves as a central repository for all relevant information needed to manage the terminal's appearance and behavior effectively, allowing for a highly customizable and visually appealing terminal experience\&. 

.PP
The \fBSIO\fP structure includes fields for managing colors, gamma correction values, color codes for different colors, file pointers and descriptors for standard input/output/error and the terminal device, as well as counters and indices for color management\&. Additionally, it contains a field for storing the name of the terminal device\&. This comprehensive structure allows for efficient management of the terminal's state and configuration in a structured way\&. 
.RE
.PP

.PP
Definition at line \fB514\fP of file \fBcm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char SIO::abg[8]"
color code for background with alpha 
.PP
Definition at line \fB541\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::bblack[8]"
color code for bold black 
.PP
Definition at line \fB531\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::bblue[8]"
color code for bold blue 
.PP
Definition at line \fB535\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::bcyan[8]"
color code for bold cyan 
.PP
Definition at line \fB537\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::bg[8]"
color code for background 
.PP
Definition at line \fB540\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::bg_color"
background color index 
.PP
Definition at line \fB516\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::bgreen[8]"
color code for bold green 
.PP
Definition at line \fB533\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::black[8]"
color code for black 
.PP
Definition at line \fB522\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::blue[8]"
color code for blue 
.PP
Definition at line \fB526\fP of file \fBcm\&.h\fP\&.
.SS "double SIO::blue_gamma"
blue gamma correction value 
.PP
Definition at line \fB520\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::bmagenta[8]"
color code for bold magenta 
.PP
Definition at line \fB536\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::bo_color"
bold color index 
.PP
Definition at line \fB517\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::borange[8]"
color code for bold orange 
.PP
Definition at line \fB539\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::bred[8]"
color code for bold red 
.PP
Definition at line \fB532\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::bwhite[8]"
color code for bold white 
.PP
Definition at line \fB538\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::byellow[8]"
color code for bold yellow 
.PP
Definition at line \fB534\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::clr_cnt"
number of colors currently in use 
.PP
Definition at line \fB551\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::clr_idx"
current color index 
.PP
Definition at line \fB553\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::clr_pair_cnt"
number of color pairs currently in use 
.PP
Definition at line \fB552\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::clr_pair_idx"
current color pair index 
.PP
Definition at line \fB554\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::cp_bold"
bold color pair index 
.PP
Definition at line \fB559\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::cp_box"
box color pair index 
.PP
Definition at line \fB558\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::cp_default"
default color pair index 
.PP
Definition at line \fB555\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::cp_highlight"
highlight color pair index 
.PP
Definition at line \fB561\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::cp_norm"
normal color pair index 
.PP
Definition at line \fB556\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::cp_reverse"
reverse color pair index 
.PP
Definition at line \fB557\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::cp_title"
title color pair index 
.PP
Definition at line \fB560\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::cyan[8]"
color code for cyan 
.PP
Definition at line \fB528\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::fg_color"
foreground color index 
.PP
Definition at line \fB515\fP of file \fBcm\&.h\fP\&.
.SS "double SIO::gray_gamma"
gray gamma correction value 
.PP
Definition at line \fB521\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::green[8]"
color code for green 
.PP
Definition at line \fB524\fP of file \fBcm\&.h\fP\&.
.SS "double SIO::green_gamma"
green gamma correction value 
.PP
Definition at line \fB519\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::magenta[8]"
color code for magenta 
.PP
Definition at line \fB527\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::orange[8]"
color code for orange 
.PP
Definition at line \fB530\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::red[8]"
color code for red 
.PP
Definition at line \fB523\fP of file \fBcm\&.h\fP\&.
.SS "double SIO::red_gamma"
red gamma correction value 
.PP
Definition at line \fB518\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::stderr_fd"
stderr file descriptor 
.PP
Definition at line \fB549\fP of file \fBcm\&.h\fP\&.
.SS "FILE* SIO::stderr_fp"
stderr stream pointer 
.PP
Definition at line \fB545\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::stdin_fd"
stdin file descriptor 
.PP
Definition at line \fB547\fP of file \fBcm\&.h\fP\&.
.SS "FILE* SIO::stdin_fp"
stdin stream pointer 
.PP
Definition at line \fB543\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::stdout_fd"
stdout file descriptor 
.PP
Definition at line \fB548\fP of file \fBcm\&.h\fP\&.
.SS "FILE* SIO::stdout_fp"
stdout stream pointer 
.PP
Definition at line \fB544\fP of file \fBcm\&.h\fP\&.
.SS "int SIO::tty_fd"
terminal device file descriptor 
.PP
Definition at line \fB550\fP of file \fBcm\&.h\fP\&.
.SS "FILE* SIO::tty_fp"
terminal device stream pointer 
.PP
Definition at line \fB546\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::tty_name[256]"
name of the terminal device 
.PP
Definition at line \fB542\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::white[8]"
color code for white 
.PP
Definition at line \fB529\fP of file \fBcm\&.h\fP\&.
.SS "char SIO::yellow[8]"
color code for yellow 
.PP
Definition at line \fB525\fP of file \fBcm\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
