.TH "src/stripansi.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/stripansi.c \- removes ansi escape sequences beginning with "\\033["" and ending in"m" or "K"  

.SH SYNOPSIS
.br
.PP
\fR#include <cm\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
removes ansi escape sequences beginning with "\\033["" and ending in"m" or "K" 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBstripansi\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
C function - strip_ansi(out_str, in_str)

.PP
This function iterates through the input string, copying characters to the output buffer while skipping over any ANSI escape sequences\&. It looks for sequences that start with "\\033[" and end with "m" or "K", and removes them from the output\&. 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP Argument count (should be 2 for the program name and input file) 
.br
\fIargv\fP Argument vector (argv[1] should be the input file name)
.RE
.PP
ANSI escape sequences start with "\\033[" and end with "m" or "K"\&. This function removes those sequences from the input string and writes the cleaned string to stdout < Buffer to hold the input string read from the file

.PP
< Buffer to hold the cleaned output string
.PP
Definition at line \fB24\fP of file \fBstripansi\&.c\fP\&.
.nf
24                                  {
25     char
26         in_buf[2048]; 
27     char out_buf[2048]; 
28     if (argc != 2) {
29         fprintf(stderr, "Usage: %s [file_with_ansi_codes]\\n", argv[0]);
30         return 1;
31     }
32     FILE *in_fp = fopen(argv[1], "r");
33     if (!in_fp) {
34         perror("Error opening file");
35         return 1;
36     }
37     while (fgets(in_buf, sizeof(in_buf), in_fp)) {
38         strip_ansi(out_buf, in_buf);
39         fputs(out_buf, stdout);
40     }
41     fclose(in_fp);
42     return 0;
43 }
.PP
.fi

.PP
References \fBstrip_ansi()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
