.TH "src/snippets/strings_test1.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/snippets/strings_test1.c \- \fBString\fP Objects\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <cm\&.h>\fP
.br
\fR#include <stddef\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBString\fP Objects\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBstrings_test1\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
\fBTest\fP
.RS 4
Test string concatenation functions This test verifies that the string concatenation functions work correctly\&. It creates two strings, concatenates them, and checks the results\&. 
.RE
.PP
\fBNote\fP
.RS 4
It is not necessary to pre-allocate spaace for str1 or str2 
.RE
.PP
< Output: Hello World

.PP
< Output: Hello World Wo
.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/enterchr\&.c\fP, \fB/usr/local/src/cmenu/src/enterstr\&.c\fP, \fB/usr/local/src/cmenu/src/test/rfc3339\&.c\fP, and \fBstrings_test1\&.c\fP\&.
.PP
Definition at line \fB17\fP of file \fBstrings_test1\&.c\fP\&.
.nf
17            {
18     String str1 = to_string("Hello");
19     String str2 = to_string(" World!");
20     string_cat(&str1, &str2);
21     printf("%s\\n", str1\&.s); 
22     printf("bytes allocated for str1\&.s: %zu\\n", str1\&.l);
23     string_ncat(&str1, &str2, 3);
24     printf("%s\\n", str1\&.s); 
25     printf("bytes allocated for str1\&.s: %zu\\n", str1\&.l);
26     free_string(str1);
27     free_string(str2);
28     return 0;
29 }
.PP
.fi

.PP
References \fBfree_string()\fP, \fBString::l\fP, \fBString::s\fP, \fBstring_cat()\fP, \fBstring_ncat()\fP, and \fBto_string()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
