.TH "String" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
String \- The \fBString\fP structure represents a string object with a pointer to the string and its allocated length\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/cm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBs\fP"
.br
.ti -1c
.RI "size_t \fBl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBString\fP structure represents a string object with a pointer to the string and its allocated length\&. 
.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/test/rfc3339\&.c\fP, and \fBstrings_test1\&.c\fP\&.
.PP
Definition at line \fB470\fP of file \fBcm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t String::l"
allocated length 
.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/test/rfc3339\&.c\fP, and \fBstrings_test1\&.c\fP\&.
.PP
Definition at line \fB472\fP of file \fBcm\&.h\fP\&.
.PP
Referenced by \fBfree_string()\fP, \fBget_rfc3339_str()\fP, \fBmain()\fP, \fBmk_string()\fP, \fBstring_cat()\fP, \fBstring_cpy()\fP, \fBstring_ncat()\fP, \fBstring_ncpy()\fP, and \fBto_string()\fP\&.
.SS "char * String::s"
pointer to the string 
.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/test/rfc3339\&.c\fP, and \fBstrings_test1\&.c\fP\&.
.PP
Definition at line \fB471\fP of file \fBcm\&.h\fP\&.
.PP
Referenced by \fBfree_string()\fP, \fBget_rfc3339_str()\fP, \fBmain()\fP, \fBmk_string()\fP, \fBstring_cat()\fP, \fBstring_cpy()\fP, \fBstring_ncat()\fP, \fBstring_ncpy()\fP, and \fBto_string()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
