.TH "/srv/www/htdocs/C-Menu/doxygen-awesome-css/include/MyLibrary/subclass-example.hpp" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/srv/www/htdocs/C-Menu/doxygen-awesome-css/include/MyLibrary/subclass-example.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include 'example\&.hpp'\fP
.br
\fR#include <iostream>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMyLibrary::SubclassExample< TemplatedClass >\fP"
.br
.RI "some subclass "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMyLibrary\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
