.TH "src/test/testfail.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/test/testfail.c \- Failure termination\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Failure termination\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBtestfail\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line \fB13\fP of file \fBtestfail\&.c\fP\&.
.nf
13            {
14     printf("test failure\\n");
15     exit(EXIT_FAILURE);
16 }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
