.TH "Text" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Text \- structure for form fields  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/form\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "int \fBcol\fP"
.br
.ti -1c
.RI "char \fBstr\fP [1024]"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure for form fields 
.PP
Definition at line \fB101\fP of file \fBform\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int Text::col"
the column number on the form window where this text string should be displayed 
.PP
Definition at line \fB104\fP of file \fBform\&.h\fP\&.
.SS "int Text::len"
the length of the text string, used for display and formatting purposes 
.PP
Definition at line \fB108\fP of file \fBform\&.h\fP\&.
.SS "int Text::line"
the line number on the form window where this text string should be displayed 
.PP
Definition at line \fB102\fP of file \fBform\&.h\fP\&.
.SS "char Text::str[1024]"
the text string to be displayed on the form window 
.PP
Definition at line \fB106\fP of file \fBform\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
