.TH "src/include/version.h" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/version.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCM_VERSION_MAJOR\fP   @PROJECT_VERSION_MAJOR @"
.br
.ti -1c
.RI "#define \fBCM_VERSION_MINOR\fP   @PROJECT_VERSION_MINOR @"
.br
.ti -1c
.RI "#define \fBCM_VERSION_PATCH\fP   @PROJECT_VERSION_PATCH @"
.br
.ti -1c
.RI "#define \fBCM_VERSION\fP   '0\&.2\&.9'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CM_VERSION   '0\&.2\&.9'"

.PP
Definition at line \fB7\fP of file \fBversion\&.h\fP\&.
.PP
Referenced by \fBdisplay_version()\fP, and \fBview_cmd_processor()\fP\&.
.SS "#define CM_VERSION_MAJOR   @PROJECT_VERSION_MAJOR @"

.PP
Definition at line \fB4\fP of file \fBversion\&.h\fP\&.
.SS "#define CM_VERSION_MINOR   @PROJECT_VERSION_MINOR @"

.PP
Definition at line \fB5\fP of file \fBversion\&.h\fP\&.
.SS "#define CM_VERSION_PATCH   @PROJECT_VERSION_PATCH @"

.PP
Definition at line \fB6\fP of file \fBversion\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
