.TH "View" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
View
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/view\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfg_color\fP"
.br
.ti -1c
.RI "int \fBbg_color\fP"
.br
.ti -1c
.RI "int \fBbo_color\fP"
.br
.ti -1c
.RI "int \fBlines\fP"
.br
.ti -1c
.RI "int \fBcols\fP"
.br
.ti -1c
.RI "int \fBbegy\fP"
.br
.ti -1c
.RI "int \fBbegx\fP"
.br
.ti -1c
.RI "char \fBprovider_cmd\fP [256]"
.br
.ti -1c
.RI "char \fBreceiver_cmd\fP [256]"
.br
.ti -1c
.RI "char \fBcmd\fP [256]"
.br
.ti -1c
.RI "char \fBcmd_all\fP [256]"
.br
.ti -1c
.RI "char \fBprompt_str\fP [256]"
.br
.ti -1c
.RI "int \fBprompt_type\fP"
.br
.ti -1c
.RI "char \fBtitle\fP [256]"
.br
.ti -1c
.RI "int \fBargc\fP"
.br
.ti -1c
.RI "char ** \fBargv\fP"
.br
.ti -1c
.RI "int \fBoptind\fP"
.br
.ti -1c
.RI "bool \fBf_ignore_case\fP"
.br
.ti -1c
.RI "bool \fBf_at_end_clear\fP"
.br
.ti -1c
.RI "bool \fBf_at_end_remove\fP"
.br
.ti -1c
.RI "bool \fBf_squeeze\fP"
.br
.ti -1c
.RI "bool \fBf_strip_ansi\fP"
.br
.ti -1c
.RI "bool \fBf_stop_on_error\fP"
.br
.ti -1c
.RI "bool \fBf_multiple_cmd_args\fP"
.br
.ti -1c
.RI "WINDOW * \fBwin\fP"
.br
.ti -1c
.RI "WINDOW * \fBbox\fP"
.br
.ti -1c
.RI "char \fBtmp_prompt_str\fP [256]"
.br
.ti -1c
.RI "int \fBcurr_argc\fP"
.br
.ti -1c
.RI "char \fBcmd_arg\fP [256]"
.br
.ti -1c
.RI "int \fBtab_stop\fP"
.br
.ti -1c
.RI "int \fBnext_cmd_char\fP"
.br
.ti -1c
.RI "bool \fBf_bod\fP"
.br
.ti -1c
.RI "bool \fBf_eod\fP"
.br
.ti -1c
.RI "bool \fBf_forward\fP"
.br
.ti -1c
.RI "bool \fBf_is_pipe\fP"
.br
.ti -1c
.RI "char \fBfile_name\fP [256]"
.br
.ti -1c
.RI "bool \fBf_redisplay_page\fP"
.br
.ti -1c
.RI "bool \fBf_displaying_help\fP"
.br
.ti -1c
.RI "bool \fBf_line_numbers\fP"
.br
.ti -1c
.RI "bool \fBf_first_iter\fP"
.br
.ti -1c
.RI "bool \fBf_search_complete\fP"
.br
.ti -1c
.RI "bool \fBf_full_screen\fP"
.br
.ti -1c
.RI "bool \fBf_timer\fP"
.br
.ti -1c
.RI "bool \fBf_cmd\fP"
.br
.ti -1c
.RI "bool \fBf_cmd_all\fP"
.br
.ti -1c
.RI "char \fBcur_file_str\fP [256]"
.br
.ti -1c
.RI "char \fBline_in_s\fP [4096]"
.br
.ti -1c
.RI "char \fBline_out_s\fP [4096]"
.br
.ti -1c
.RI "char \fBstripped_line_out\fP [4096]"
.br
.ti -1c
.RI "cchar_t \fBcmplx_buf\fP [4096]"
.br
.ti -1c
.RI "char * \fBline_out_p\fP"
.br
.ti -1c
.RI "unsigned int \fBline_number\fP"
.br
.ti -1c
.RI "char \fBline_number_s\fP [20]"
.br
.ti -1c
.RI "char * \fBline_in_beg_p\fP"
.br
.ti -1c
.RI "char * \fBline_in_end_p\fP"
.br
.ti -1c
.RI "WINDOW * \fBpad\fP"
.br
.ti -1c
.RI "int \fBcury\fP"
.br
.ti -1c
.RI "int \fBcurx\fP"
.br
.ti -1c
.RI "int \fBscroll_lines\fP"
.br
.ti -1c
.RI "int \fBcmd_line\fP"
.br
.ti -1c
.RI "int \fBmaxcol\fP"
.br
.ti -1c
.RI "int \fBpminrow\fP"
.br
.ti -1c
.RI "int \fBpmincol\fP"
.br
.ti -1c
.RI "int \fBsminrow\fP"
.br
.ti -1c
.RI "int \fBsmincol\fP"
.br
.ti -1c
.RI "int \fBsmaxrow\fP"
.br
.ti -1c
.RI "int \fBsmaxcol\fP"
.br
.ti -1c
.RI "int \fBfirst_match_x\fP"
.br
.ti -1c
.RI "int \fBlast_match_x\fP"
.br
.ti -1c
.RI "char \fBin_spec\fP [256]"
.br
.ti -1c
.RI "char \fBout_spec\fP [256]"
.br
.ti -1c
.RI "char \fBhelp_spec\fP [256]"
.br
.ti -1c
.RI "bool \fBf_in_spec\fP"
.br
.ti -1c
.RI "bool \fBf_out_spec\fP"
.br
.ti -1c
.RI "char * \fBfile_spec_ptr\fP"
.br
.ti -1c
.RI "char * \fBnext_file_spec_ptr\fP"
.br
.ti -1c
.RI "char * \fBtmp_file_name_ptr\fP"
.br
.ti -1c
.RI "off_t \fBfile_size\fP"
.br
.ti -1c
.RI "off_t \fBfile_pos\fP"
.br
.ti -1c
.RI "off_t \fBprev_file_pos\fP"
.br
.ti -1c
.RI "off_t \fBpage_top_pos\fP"
.br
.ti -1c
.RI "off_t \fBpage_bot_pos\fP"
.br
.ti -1c
.RI "off_t \fBsrch_curr_pos\fP"
.br
.ti -1c
.RI "off_t \fBsrch_beg_pos\fP"
.br
.ti -1c
.RI "off_t \fBmark_tbl\fP [256]"
.br
.ti -1c
.RI "bool \fBf_in_pipe\fP"
.br
.ti -1c
.RI "int \fBin_fd\fP"
.br
.ti -1c
.RI "int \fBout_fd\fP"
.br
.ti -1c
.RI "FILE * \fBin_fp\fP"
.br
.ti -1c
.RI "int \fBstdin_fd\fP"
.br
.ti -1c
.RI "FILE * \fBstdin_fp\fP"
.br
.ti -1c
.RI "int \fBstdout_fd\fP"
.br
.ti -1c
.RI "FILE * \fBstdout_fp\fP"
.br
.ti -1c
.RI "char * \fBbuf\fP"
.br
.ti -1c
.RI "char * \fBbuf_curr_ptr\fP"
.br
.ti -1c
.RI "char * \fBbuf_end_ptr\fP"
.br
.ti -1c
.RI "char * \fBlnbuf\fP"
.br
.ti -1c
.RI "char * \fBlnbuf_curr_ptr\fP"
.br
.ti -1c
.RI "char * \fBlnbuf_end_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB34\fP of file \fBview\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int View::argc"
command line arguments count 
.PP
Definition at line \fB50\fP of file \fBview\&.h\fP\&.
.SS "char** View::argv"
command line arguments vector 
.PP
Definition at line \fB51\fP of file \fBview\&.h\fP\&.
.SS "int View::begx"
screen column upper left corner of window 
.PP
Definition at line \fB41\fP of file \fBview\&.h\fP\&.
.SS "int View::begy"
screen line upper left corner of window 
.PP
Definition at line \fB40\fP of file \fBview\&.h\fP\&.
.SS "int View::bg_color"
background_color 
.PP
Definition at line \fB36\fP of file \fBview\&.h\fP\&.
.SS "int View::bo_color"
bold_color 
.PP
Definition at line \fB37\fP of file \fBview\&.h\fP\&.
.SS "WINDOW* View::box"
ncurses window used by \fBView\fP for box around win 
.PP
Definition at line \fB62\fP of file \fBview\&.h\fP\&.
.SS "char* View::buf"
pointer to first byte of virtual buffer 
.PP
Definition at line \fB140\fP of file \fBview\&.h\fP\&.
.SS "char* View::buf_curr_ptr"
pointer to current position in virtual buffer 
.PP
Definition at line \fB141\fP of file \fBview\&.h\fP\&.
.SS "char* View::buf_end_ptr"
pointer to first byte after end of data in virtual buffer 
.PP
Definition at line \fB142\fP of file \fBview\&.h\fP\&.
.SS "char View::cmd[256]"
command to execute in foreground, e\&.g\&. an editor 
.PP
Definition at line \fB44\fP of file \fBview\&.h\fP\&.
.SS "char View::cmd_all[256]"
\fBView\fP - command to execute at start of program 
.PP
Definition at line \fB45\fP of file \fBview\&.h\fP\&.
.SS "char View::cmd_arg[256]"
argument string 
.PP
Definition at line \fB67\fP of file \fBview\&.h\fP\&.
.SS "int View::cmd_line"
command line location on pad 
.PP
Definition at line \fB100\fP of file \fBview\&.h\fP\&.
.SS "cchar_t View::cmplx_buf[4096]"
complex character buffer 
.PP
Definition at line \fB90\fP of file \fBview\&.h\fP\&.
.SS "int View::cols"
number of columns for window size 
.PP
Definition at line \fB39\fP of file \fBview\&.h\fP\&.
.SS "char View::cur_file_str[256]"
file currently open for viewing 
.PP
Definition at line \fB86\fP of file \fBview\&.h\fP\&.
.SS "int View::curr_argc"
current argument count when processing multiple arguments 
.PP
Definition at line \fB65\fP of file \fBview\&.h\fP\&.
.SS "int View::curx"
curx is the pad column of the cursor location 
.PP
Definition at line \fB98\fP of file \fBview\&.h\fP\&.
.SS "int View::cury"
cury is the pad row of the cursor location 
.PP
Definition at line \fB97\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_at_end_clear"
obsolete, unneeded 
.PP
Definition at line \fB54\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_at_end_remove"
obsolete, unneeded 
.PP
Definition at line \fB55\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_bod"
beginning of data 
.PP
Definition at line \fB71\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_cmd"
cmd is verified 
.PP
Definition at line \fB84\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_cmd_all"
cmd_all is verified 
.PP
Definition at line \fB85\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_displaying_help"
currently didsplaying help information 
.PP
Definition at line \fB77\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_eod"
end of data 
.PP
Definition at line \fB72\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_first_iter"
first iteration of search 
.PP
Definition at line \fB79\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_forward"
motion flag forward 
.PP
Definition at line \fB73\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_full_screen"
default mode if lines and columns not specified 
.PP
Definition at line \fB81\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_ignore_case"
\fBView\fP - ignore case in search 
.PP
Definition at line \fB53\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_in_pipe"
input is from a pipe 
.PP
Definition at line \fB132\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_in_spec"
input file verified 
.PP
Definition at line \fB119\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_is_pipe"
input is from a pipe 
.PP
Definition at line \fB74\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_line_numbers"
not implemented 
.PP
Definition at line \fB78\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_multiple_cmd_args"
\fBView\fP - put multiple arguments in a single string 
.PP
Definition at line \fB59\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_out_spec"
output file verified 
.PP
Definition at line \fB120\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_redisplay_page"
flag indicating page needs to be redisplayed 
.PP
Definition at line \fB76\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_search_complete"
Entire file has been searched 
.PP
Definition at line \fB80\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_squeeze"
\fBView\fP - print one line for each group of blank lines 
.PP
Definition at line \fB56\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_stop_on_error"
obsolete, unneeded 
.PP
Definition at line \fB58\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_strip_ansi"
strip ansi escape sequences when writing buffer 
.PP
Definition at line \fB57\fP of file \fBview\&.h\fP\&.
.SS "bool View::f_timer"
time commands and display elapsed time in prompt 
.PP
Definition at line \fB82\fP of file \fBview\&.h\fP\&.
.SS "int View::fg_color"
foreground_color 
.PP
Definition at line \fB35\fP of file \fBview\&.h\fP\&.
.SS "char View::file_name[256]"
basename of file being viewed 
.PP
Definition at line \fB75\fP of file \fBview\&.h\fP\&.
.SS "off_t View::file_pos"
current file position 
.PP
Definition at line \fB125\fP of file \fBview\&.h\fP\&.
.SS "off_t View::file_size"
size of file being viewed 
.PP
Definition at line \fB124\fP of file \fBview\&.h\fP\&.
.SS "char* View::file_spec_ptr"
pointer to current file spec 
.PP
Definition at line \fB121\fP of file \fBview\&.h\fP\&.
.SS "int View::first_match_x"
first column of current search match in stripped_line_out 
.PP
Definition at line \fB112\fP of file \fBview\&.h\fP\&.
.SS "char View::help_spec[256]"
help file spec 
.PP
Definition at line \fB118\fP of file \fBview\&.h\fP\&.
.SS "int View::in_fd"
input file descriptor 
.PP
Definition at line \fB133\fP of file \fBview\&.h\fP\&.
.SS "FILE* View::in_fp"
pointer to input stream data structure 
.PP
Definition at line \fB135\fP of file \fBview\&.h\fP\&.
.SS "char View::in_spec[256]"
input file spec 
.PP
Definition at line \fB116\fP of file \fBview\&.h\fP\&.
.SS "int View::last_match_x"
last column of current search match in stripped_line_out 
.PP
Definition at line \fB114\fP of file \fBview\&.h\fP\&.
.SS "char* View::line_in_beg_p"
pointer used in matching search targets 
.PP
Definition at line \fB94\fP of file \fBview\&.h\fP\&.
.SS "char* View::line_in_end_p"
pointer used in matching search targets 
.PP
Definition at line \fB95\fP of file \fBview\&.h\fP\&.
.SS "char View::line_in_s[4096]"
raw input line from buffer 
.PP
Definition at line \fB87\fP of file \fBview\&.h\fP\&.
.SS "unsigned int View::line_number"
currently not implemented 
.PP
Definition at line \fB92\fP of file \fBview\&.h\fP\&.
.SS "char View::line_number_s[20]"
currently not implemented 
.PP
Definition at line \fB93\fP of file \fBview\&.h\fP\&.
.SS "char* View::line_out_p"
pointer to current position in line_out_s 
.PP
Definition at line \fB91\fP of file \fBview\&.h\fP\&.
.SS "char View::line_out_s[4096]"
scratch buffer 
.PP
Definition at line \fB88\fP of file \fBview\&.h\fP\&.
.SS "int View::lines"
number of lines for window size 
.PP
Definition at line \fB38\fP of file \fBview\&.h\fP\&.
.SS "char* View::lnbuf"
pointer to first byte of virtual buffer 
.PP
Definition at line \fB144\fP of file \fBview\&.h\fP\&.
.SS "char* View::lnbuf_curr_ptr"
pointer to first byte of virtual buffer 
.PP
Definition at line \fB145\fP of file \fBview\&.h\fP\&.
.SS "char* View::lnbuf_end_ptr"
pointer to first byte after end of data in virtual buffer 
.PP
Definition at line \fB146\fP of file \fBview\&.h\fP\&.
.SS "off_t View::mark_tbl[256]"
not implemented 
.PP
Definition at line \fB131\fP of file \fBview\&.h\fP\&.
.SS "int View::maxcol"
length of longest line on pad 
.PP
Definition at line \fB101\fP of file \fBview\&.h\fP\&.
.SS "int View::next_cmd_char"
index of next character in cmd string to process when building prompt 
.PP
Definition at line \fB69\fP of file \fBview\&.h\fP\&.
.SS "char* View::next_file_spec_ptr"
pointer to next file spec 
.PP
Definition at line \fB122\fP of file \fBview\&.h\fP\&.
.SS "int View::optind"
getopt pointer to non-option arguments in argv 
.PP
Definition at line \fB52\fP of file \fBview\&.h\fP\&.
.SS "int View::out_fd"
output file descriptor 
.PP
Definition at line \fB134\fP of file \fBview\&.h\fP\&.
.SS "char View::out_spec[256]"
output file spec 
.PP
Definition at line \fB117\fP of file \fBview\&.h\fP\&.
.SS "WINDOW* View::pad"
ncurses pad used by \fBView\fP 
.PP
Definition at line \fB96\fP of file \fBview\&.h\fP\&.
.SS "off_t View::page_bot_pos"
file position of last line displayed 
.PP
Definition at line \fB128\fP of file \fBview\&.h\fP\&.
.SS "off_t View::page_top_pos"
file position of top line displayed 
.PP
Definition at line \fB127\fP of file \fBview\&.h\fP\&.
.SS "int View::pmincol"
first pad column displayed in view window 
.PP
Definition at line \fB103\fP of file \fBview\&.h\fP\&.
.SS "int View::pminrow"
first pad row displayed in view window 
.PP
Definition at line \fB102\fP of file \fBview\&.h\fP\&.
.SS "off_t View::prev_file_pos"
previous file position 
.PP
Definition at line \fB126\fP of file \fBview\&.h\fP\&.
.SS "char View::prompt_str[256]"
prompt string for chyron 
.PP
Definition at line \fB46\fP of file \fBview\&.h\fP\&.
.SS "int View::prompt_type"
\fBView\fP - prompt type for chyron, e\&.g\&. 0=short, 1=long, 2=none 
.PP
Definition at line \fB47\fP of file \fBview\&.h\fP\&.
.SS "char View::provider_cmd[256]"
command provides input 
.PP
Definition at line \fB42\fP of file \fBview\&.h\fP\&.
.SS "char View::receiver_cmd[256]"
command receives output 
.PP
Definition at line \fB43\fP of file \fBview\&.h\fP\&.
.SS "int View::scroll_lines"
number of lines to scroll 
.PP
Definition at line \fB99\fP of file \fBview\&.h\fP\&.
.SS "int View::smaxcol"
screen position of last column of pad displayed in view window 
.PP
Definition at line \fB110\fP of file \fBview\&.h\fP\&.
.SS "int View::smaxrow"
screen position of last row of pad displayed in view windiow 
.PP
Definition at line \fB108\fP of file \fBview\&.h\fP\&.
.SS "int View::smincol"
screen position of first column of pad displayed in view window 
.PP
Definition at line \fB106\fP of file \fBview\&.h\fP\&.
.SS "int View::sminrow"
screen position of first row of pad displayed in view window 
.PP
Definition at line \fB104\fP of file \fBview\&.h\fP\&.
.SS "off_t View::srch_beg_pos"
file position when search started 
.PP
Definition at line \fB130\fP of file \fBview\&.h\fP\&.
.SS "off_t View::srch_curr_pos"
current search position 
.PP
Definition at line \fB129\fP of file \fBview\&.h\fP\&.
.SS "int View::stdin_fd"
standard input file descriptor 
.PP
Definition at line \fB136\fP of file \fBview\&.h\fP\&.
.SS "FILE* View::stdin_fp"
pointer to standard input stream data structure 
.PP
Definition at line \fB137\fP of file \fBview\&.h\fP\&.
.SS "int View::stdout_fd"
standard output file descriptor 
.PP
Definition at line \fB138\fP of file \fBview\&.h\fP\&.
.SS "FILE* View::stdout_fp"
pointer to standard output stream data structure 
.PP
Definition at line \fB139\fP of file \fBview\&.h\fP\&.
.SS "char View::stripped_line_out[4096]"
printable characters only 
.PP
Definition at line \fB89\fP of file \fBview\&.h\fP\&.
.SS "int View::tab_stop"
number of spaces between tab stops 
.PP
Definition at line \fB68\fP of file \fBview\&.h\fP\&.
.SS "char View::title[256]"
display on top line of box window 
.PP
Definition at line \fB49\fP of file \fBview\&.h\fP\&.
.SS "char* View::tmp_file_name_ptr"
pointer to temporary file spec 
.PP
Definition at line \fB123\fP of file \fBview\&.h\fP\&.
.SS "char View::tmp_prompt_str[256]"
temporary prompt string used when building prompt 
.PP
Definition at line \fB63\fP of file \fBview\&.h\fP\&.
.SS "WINDOW* View::win"
ncurses window used by \fBView\fP 
.PP
Definition at line \fB61\fP of file \fBview\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
