.TH "src/include/view.h" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/view.h \- \fBView\fP data structures, enums, types, end external declarations\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <ncursesw/ncurses\&.h>\fP
.br
\fR#include <signal\&.h>\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBView\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_XOPEN_SOURCE_EXTENDED\fP   1"
.br
.ti -1c
.RI "#define \fBNCURSES_WIDECHAR\fP   1"
.br
.ti -1c
.RI "#define \fBNPOS\fP   256"
.br
.ti -1c
.RI "#define \fBNMARKS\fP   256"
.br
.ti -1c
.RI "#define \fBMAXLEN\fP   256"
.br
.ti -1c
.RI "#define \fBNULSL\fP"
.br
.ti -1c
.RI "#define \fBNULL_POSITION\fP   \-1"
.br
.ti -1c
.RI "#define \fBVBUFSIZ\fP   65536"
.br
.ti -1c
.RI "#define \fBBUFSIZ\fP   8192"
.br
.ti -1c
.RI "#define \fBPAD_COLS\fP   4096"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPROMPT_TYPE\fP { \fBPT_NONE\fP, \fBPT_SHORT\fP, \fBPT_LONG\fP, \fBPT_STRING\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBget_cmd_spec\fP (\fBView\fP *, char *)"
.br
.ti -1c
.RI "void \fBgo_to_position\fP (\fBView\fP *, long)"
.br
.ti -1c
.RI "void \fBcat_file\fP (\fBView\fP *)"
.br
.RI "Concatenate File to Standard Output\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBView\fP * \fBview\fP"
.br
.ti -1c
.RI "char \fBerr_msg\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBView\fP data structures, enums, types, end external declarations\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBview\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define _XOPEN_SOURCE_EXTENDED   1"

.PP
Definition at line \fB13\fP of file \fBview\&.h\fP\&.
.SS "#define BUFSIZ   8192"

.PP
\fBExamples\fP
.in +1c
\fB/usr/local/src/cmenu/src/enterstr\&.c\fP\&.
.PP
Definition at line \fB29\fP of file \fBview\&.h\fP\&.
.PP
Referenced by \fBaccept_str()\fP, \fBform_parse_desc()\fP, and \fBmain()\fP\&.
.SS "#define MAXLEN   256"

.PP
Definition at line \fB25\fP of file \fBview\&.h\fP\&.
.SS "#define NCURSES_WIDECHAR   1"

.PP
Definition at line \fB14\fP of file \fBview\&.h\fP\&.
.SS "#define NMARKS   256"

.PP
Definition at line \fB24\fP of file \fBview\&.h\fP\&.
.PP
Referenced by \fBgo_to_mark()\fP, and \fBview_init_input()\fP\&.
.SS "#define NPOS   256"

.PP
Definition at line \fB23\fP of file \fBview\&.h\fP\&.
.SS "#define NULL_POSITION   \-1"

.PP
Definition at line \fB27\fP of file \fBview\&.h\fP\&.
.PP
Referenced by \fBbuild_prompt()\fP, \fBgo_to_mark()\fP, and \fBview_init_input()\fP\&.
.SS "#define NULSL"

.PP
Definition at line \fB26\fP of file \fBview\&.h\fP\&.
.SS "#define PAD_COLS   4096"

.PP
Definition at line \fB30\fP of file \fBview\&.h\fP\&.
.PP
Referenced by \fBcmd_line_prompt()\fP, \fBfmt_line()\fP, \fBget_cmd_arg()\fP, \fBget_next_line()\fP, \fBinit_view_boxwin()\fP, \fBinit_view_full_screen()\fP, and \fBwrite_view_buffer()\fP\&.
.SS "#define VBUFSIZ   65536"

.PP
Definition at line \fB28\fP of file \fBview\&.h\fP\&.
.PP
Referenced by \fBview_init_input()\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPROMPT_TYPE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIPT_NONE \fP
.TP
\f(BIPT_SHORT \fP
.TP
\f(BIPT_LONG \fP
.TP
\f(BIPT_STRING \fP
.PP
Definition at line \fB32\fP of file \fBview\&.h\fP\&.
.nf
32 { PT_NONE, PT_SHORT, PT_LONG, PT_STRING };
.PP
.fi

.SH "Function Documentation"
.PP 
.SS "void cat_file (\fBView\fP * view)\fR [extern]\fP"

.PP
Concatenate File to Standard Output\&. 
.PP
Definition at line \fB892\fP of file \fBview_engine\&.c\fP\&.
.nf
892                           {
893     int c;
894     while (1) {
895         get_next_char();
896         if (view\->f_eod)
897             break;
898         putchar(c);
899     }
900 }
.PP
.fi

.PP
References \fBget_next_char\fP, and \fBview\fP\&.
.SS "int get_cmd_spec (\fBView\fP * , char * )\fR [extern]\fP"

.SS "void go_to_position (\fBView\fP * , long )\fR [extern]\fP"

.PP
References \fBerr_msg\fP, and \fBMAXLEN\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char err_msg[256]\fR [extern]\fP"

.PP
Definition at line \fB82\fP of file \fBview_engine\&.c\fP\&.
.PP
Referenced by \fBABEND()\fP, and \fBgo_to_position()\fP\&.
.SS "\fBView\fP* view\fR [extern]\fP"

.PP
Definition at line \fB36\fP of file \fBmem\&.c\fP\&.
.PP
Referenced by \fBbuild_prompt()\fP, \fBcat_file()\fP, \fBcmd_line_prompt()\fP, \fBdestroy_view()\fP, \fBdisplay_line()\fP, \fBenter_file_spec()\fP, \fBfmt_line()\fP, \fBget_cmd_arg()\fP, \fBget_cmd_char()\fP, \fBget_next_line()\fP, \fBget_pos_next_line()\fP, \fBget_pos_prev_line()\fP, \fBget_prev_line()\fP, \fBgo_to_eof()\fP, \fBgo_to_line()\fP, \fBgo_to_mark()\fP, \fBgo_to_percent()\fP, \fBgo_to_position()\fP, \fBinit_view_boxwin()\fP, \fBinit_view_files()\fP, \fBinit_view_full_screen()\fP, \fBlp()\fP, \fBmain()\fP, \fBmview()\fP, \fBnew_view()\fP, \fBnext_page()\fP, \fBprev_page()\fP, \fBredisplay_page()\fP, \fBremove_file()\fP, \fBresize_page()\fP, \fBscroll_down_n_lines()\fP, \fBscroll_up_n_lines()\fP, \fBsearch()\fP, \fBview_cmd_processor()\fP, \fBview_file()\fP, \fBview_init_input()\fP, and \fBwrite_view_buffer()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
