.TH "src/view_engine.c" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/view_engine.c \- The working part of View\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <common\&.h>\fP
.br
\fR#include <ctype\&.h>\fP
.br
\fR#include <errno\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <regex\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <sys/mman\&.h>\fP
.br
\fR#include <sys/stat\&.h>\fP
.br
\fR#include <termios\&.h>\fP
.br
\fR#include <time\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCtrl\fP(c)"
.br
.ti -1c
.RI "#define \fBget_next_char\fP()"
.br
.RI "read the next characater from the virtual file "
.ti -1c
.RI "#define \fBget_prev_char\fP()"
.br
.RI "read the previous characater from the virtual file "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBview_file\fP (Init *\fBinit\fP)"
.br
.RI "Start view\&. "
.ti -1c
.RI "int \fBview_cmd_processor\fP (Init *\fBinit\fP)"
.br
.RI "Main Command Processing Loop for View\&. "
.ti -1c
.RI "int \fBget_cmd_char\fP (View *\fBview\fP, off_t *n)"
.br
.RI "Get Command Character and Numeric Argument\&. "
.ti -1c
.RI "int \fBget_cmd_arg\fP (View *\fBview\fP, char *prompt)"
.br
.RI "Get Command Argument from User Input\&. "
.ti -1c
.RI "void \fBbuild_prompt\fP (View *\fBview\fP, int prompt_type, char *prompt_str, double elapsed)"
.br
.RI "Build Prompt String\&. "
.ti -1c
.RI "void \fBcat_file\fP (View *\fBview\fP)"
.br
.RI "Concatenate File to Standard Output\&. "
.ti -1c
.RI "void \fBlp\fP (char *PrintFile)"
.br
.RI "Send File to Print Queue\&. "
.ti -1c
.RI "void \fBgo_to_mark\fP (View *\fBview\fP, int c)"
.br
.RI "Go to Mark\&. "
.ti -1c
.RI "void \fBgo_to_eof\fP (View *\fBview\fP)"
.br
.RI "Go to End of File\&. "
.ti -1c
.RI "int \fBgo_to_line\fP (View *\fBview\fP, off_t line_idx)"
.br
.RI "Go to Specific Line\&. "
.ti -1c
.RI "void \fBgo_to_percent\fP (View *\fBview\fP, int percent)"
.br
.RI "Go to Percent of File\&. "
.ti -1c
.RI "void \fBgo_to_position\fP (View *\fBview\fP, off_t go_to_pos)"
.br
.RI "Go to Specific File Position\&. "
.ti -1c
.RI "bool \fBsearch\fP (View *\fBview\fP, int *search_cmd, char *regex_pattern)"
.br
.RI "Search for Regular Expression Pattern\&. "
.ti -1c
.RI "void \fBnext_page\fP (View *\fBview\fP)"
.br
.RI "Advance to Next Page\&. "
.ti -1c
.RI "void \fBprev_page\fP (View *\fBview\fP)"
.br
.RI "display previous page "
.ti -1c
.RI "void \fBresize_page\fP (Init *\fBinit\fP)"
.br
.RI "Resize Viewing Page\&. "
.ti -1c
.RI "void \fBredisplay_page\fP (View *\fBview\fP)"
.br
.RI "Redisplay Current Page\&. "
.ti -1c
.RI "void \fBscroll_down_n_lines\fP (View *\fBview\fP, int n)"
.br
.RI "Scroll N Lines\&. "
.ti -1c
.RI "void \fBscroll_up_n_lines\fP (View *\fBview\fP, int n)"
.br
.RI "Scroll Up N Lines\&. "
.ti -1c
.RI "off_t \fBget_next_line\fP (View *\fBview\fP, off_t pos)"
.br
.RI "Get Next Line from File\&. "
.ti -1c
.RI "off_t \fBget_prev_line\fP (View *\fBview\fP, off_t pos)"
.br
.RI "Get Previous Line from File\&. "
.ti -1c
.RI "off_t \fBget_pos_next_line\fP (View *\fBview\fP, off_t pos)"
.br
.RI "Get Position of Next Line\&. "
.ti -1c
.RI "off_t \fBget_pos_prev_line\fP (View *\fBview\fP, off_t pos)"
.br
.RI "Get Position of Previous Line\&. "
.ti -1c
.RI "int \fBfmt_line\fP (View *\fBview\fP)"
.br
.RI "Format Line for Display\&. "
.ti -1c
.RI "void \fBdisplay_line\fP (View *\fBview\fP)"
.br
.RI "Display Line on Pad\&. "
.ti -1c
.RI "void \fBparse_ansi_str\fP (char *ansi_str, attr_t *attr, int *cpx)"
.br
.RI "Parse ANSI SGR Escape Sequence\&. "
.ti -1c
.RI "void \fBview_display_help\fP (Init *\fBinit\fP)"
.br
.RI "Display View Help File\&. "
.ti -1c
.RI "void \fBcmd_line_prompt\fP (View *\fBview\fP, char *s)"
.br
.RI "Display Command Line Prompt\&. "
.ti -1c
.RI "void \fBremove_file\fP (View *\fBview\fP)"
.br
.RI "Remove File\&. "
.ti -1c
.RI "int \fBwrite_view_buffer\fP (Init *\fBinit\fP, bool f_strip_ansi)"
.br
.RI "Write buffer contents to files\&. "
.ti -1c
.RI "bool \fBenter_file_spec\fP (Init *\fBinit\fP, char *file_spec)"
.br
.RI "use form to enter a file specification "
.ti -1c
.RI "int \fBa_toi\fP (char *s, bool *a_toi_error)"
.br
.RI "a safer alternative to atoi() for converting ASCII strings to integers\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBprev_regex_pattern\fP [\fBMAXLEN\fP]"
.br
.ti -1c
.RI "FILE * \fBdbgfp\fP"
.br
.ti -1c
.RI "char \fBerr_msg\fP [\fBMAXLEN\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
The working part of View\&. 


.PP
\fBAuthor\fP
.RS 4
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com 
.RE
.PP
\fBDate\fP
.RS 4
2026-02-09 
.RE
.PP

.PP
Definition in file \fBview_engine\&.c\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define Ctrl( c)"
\fBValue:\fP
.nf
((c) & 0x1f)
.PP
.fi

.PP
Definition at line \fB23\fP of file \fBview_engine\&.c\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "#define get_next_char()"
\fBValue:\fP
.nf
do {                                                                       \\
    if (view\->file_pos == view\->file_size) {                               \\
        view\->f_eod = true;                                                \\
        break;                                                             \\
    } else                                                                 \\
        view\->f_eod = false;                                               \\
    c = view\->buf[view\->file_pos++];                                       \\
} while (c == 0x0d);
.PP
.fi

.PP
read the next characater from the virtual file 
.PP
Definition at line \fB26\fP of file \fBview_engine\&.c\fP\&.
.nf
26 #define get_next_char()                                                        \\
27     do {                                                                       \\
28         if (view\->file_pos == view\->file_size) {                               \\
29             view\->f_eod = true;                                                \\
30             break;                                                             \\
31         } else                                                                 \\
32             view\->f_eod = false;                                               \\
33         c = view\->buf[view\->file_pos++];                                       \\
34     } while (c == 0x0d);
.PP
.fi

.PP
Referenced by \fBcat_file()\fP, \fBget_next_line()\fP, \fBget_pos_next_line()\fP, \fBget_pos_prev_line()\fP, \fBgo_to_line()\fP, and \fBgo_to_percent()\fP\&.
.SS "#define get_prev_char()"
\fBValue:\fP
.nf
do {                                                                       \\
    if (view\->file_pos == 0) {                                             \\
        view\->f_bod = true;                                                \\
        break;                                                             \\
    } else                                                                 \\
        view\->f_bod = false;                                               \\
    c = view\->buf[\-\-view\->file_pos];                                       \\
} while (c == 0x0d);
.PP
.fi

.PP
read the previous characater from the virtual file 
.PP
Definition at line \fB37\fP of file \fBview_engine\&.c\fP\&.
.nf
37 #define get_prev_char()                                                        \\
38     do {                                                                       \\
39         if (view\->file_pos == 0) {                                             \\
40             view\->f_bod = true;                                                \\
41             break;                                                             \\
42         } else                                                                 \\
43             view\->f_bod = false;                                               \\
44         c = view\->buf[\-\-view\->file_pos];                                       \\
45     } while (c == 0x0d);
.PP
.fi

.PP
Referenced by \fBget_next_line()\fP, \fBget_pos_next_line()\fP, \fBget_pos_prev_line()\fP, \fBgo_to_eof()\fP, and \fBgo_to_percent()\fP\&.
.SH "Function Documentation"
.PP 
.SS "int a_toi (char * s, bool * a_toi_error)"

.PP
a safer alternative to atoi() for converting ASCII strings to integers\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP is the input string 
.br
\fIa_toi_error\fP is a pointer to a boolean that will be set to true if an error occurs during conversion, or false if the conversion is successful\&. 
.RE
.PP
\fBNote\fP
.RS 4
accepts positive integers only\&. 

.PP
sets a_toi_error to (-1) on error 
.RE
.PP
\fBReturns\fP
.RS 4
converted integer value, or -1 if an error occurs 
.RE
.PP

.PP
Definition at line \fB438\fP of file \fBfutil\&.c\fP\&.
.nf
438                                       {
439     int rc = \-1;
440     *a_toi_error = false;
441     errno = 0;
442     if (s && *s != 0)
443         rc = (int)strtol(s, nullptr, 10);
444     if (rc < 0 || errno) {
445         rc = \-1;
446         *a_toi_error = true;
447     }
448     return rc;
449 }
.PP
.fi

.PP
Referenced by \fBparse_ansi_str()\fP\&.
.SS "void build_prompt (View * view, int prompt_type, char * prompt_str, double elapsed)"

.PP
Build Prompt String\&. 
.PP
Definition at line \fB779\fP of file \fBview_engine\&.c\fP\&.
.nf
780                                   {
781     char tmp_str[MAXLEN];
782     prompt_type = PT_LONG;
783     *prompt_str = '\\0';
784     if (prompt_type == PT_LONG) {
785         if (view\->f_is_pipe)
786             strnz__cat(prompt_str, "stdin", MAXLEN \- 1);
787         else
788             strnz__cat(prompt_str, view\->file_name, MAXLEN \- 1);
789     }
790     if (view\->pmincol > 0) {
791         sprintf(tmp_str, "Col %d of %d", view\->pmincol, view\->maxcol);
792         if (prompt_str[0] != '\\0')
793             strnz__cat(prompt_str, "|", MAXLEN \- 1);
794         strnz__cat(prompt_str, tmp_str, MAXLEN \- 1);
795     }
796     if (view\->argc > 1 && prompt_type == PT_LONG) {
797         sprintf(tmp_str, "File %d of %d", view\->curr_argc + 1, view\->argc);
798         if (prompt_str[0] != '\\0') {
799             strnz__cat(prompt_str, "|", MAXLEN \- 1);
800             strnz__cat(prompt_str, tmp_str, MAXLEN \- 1);
801         }
802     }
803     if (prompt_type == PT_LONG) {
804         if (view\->page_top_pos == NULL_POSITION)
805             view\->page_top_pos = view\->file_size;
806         sprintf(tmp_str, "Pos %zd\-%zd", view\->page_top_pos, view\->page_bot_pos);
807         if (prompt_str[0] != '\\0') {
808             strnz__cat(prompt_str, "|", MAXLEN \- 1);
809             strnz__cat(prompt_str, tmp_str, MAXLEN \- 1);
810         }
811         if (!view\->f_is_pipe) {
812             if (view\->file_size > 0) {
813                 sprintf(tmp_str, " of %zd", view\->file_size);
814                 strnz__cat(prompt_str, tmp_str, MAXLEN \- 1);
815             }
816         }
817     }
818     if (!view\->f_eod && prompt_type != PT_NONE) {
819         if (view\->file_size > 0 && view\->page_bot_pos != 0) {
820             sprintf(tmp_str, "(%zd%%)",
821                     (100 * view\->page_bot_pos) / view\->file_size);
822             if (prompt_str[0] != '\\0')
823                 strnz__cat(prompt_str, "|", MAXLEN \- 1);
824             strnz__cat(prompt_str, tmp_str, MAXLEN \- 1);
825         }
826     }
827     if (view\->f_eod) {
828         if (prompt_str[0] != '\\0')
829             strnz__cat(prompt_str, " ", MAXLEN \- 1);
830         strnz__cat(prompt_str, "(End)", MAXLEN \- 1);
831         if (view\->curr_argc + 1 < view\->argc) {
832             base_name(tmp_str, view\->argv[view\->curr_argc + 1]);
833             strnz__cpy(prompt_str, " Next File: ", MAXLEN \- 1);
834             strnz__cat(prompt_str, tmp_str, MAXLEN \- 1);
835         }
836     }
837     if (view\->f_timer) {
838         sprintf(tmp_str, " secs\&. %\&.6f\\n", elapsed);
839         strnz__cat(prompt_str, tmp_str, MAXLEN \- 1);
840     }
841 }
.PP
.fi

.PP
References \fBbase_name()\fP, \fBMAXLEN\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "void cat_file (View * view)"

.PP
Concatenate File to Standard Output\&. 
.PP
Definition at line \fB892\fP of file \fBview_engine\&.c\fP\&.
.nf
892                           {
893     int c;
894     while (1) {
895         get_next_char();
896         if (view\->f_eod)
897             break;
898         putchar(c);
899     }
900 }
.PP
.fi

.PP
References \fBget_next_char\fP, and \fBview\fP\&.
.SS "void cmd_line_prompt (View * view, char * s)"

.PP
Display Command Line Prompt\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBview\fP\fP is the current view data structure 
.br
\fIs\fP is the prompt string 
.RE
.PP

.PP
Definition at line \fB1729\fP of file \fBview_engine\&.c\fP\&.
.nf
1729                                           {
1730     char message_str[PAD_COLS + 1];
1731     int l;
1732     l = strnz__cpy(message_str, s, PAD_COLS);
1733     wmove(view\->win, view\->cmd_line, view\->pmincol);
1734     if (l != 0) {
1735         wclrtoeol(view\->win);
1736         wattron(view\->win, WA_REVERSE);
1737         waddstr(view\->win, " ");
1738         waddstr(view\->win, message_str);
1739         waddstr(view\->win, " ");
1740         wattroff(view\->win, WA_REVERSE);
1741         waddstr(view\->win, " ");
1742         wmove(view\->win, view\->cmd_line, view\->pmincol + l + 2);
1743     }
1744     wrefresh(view\->win);
1745 }
.PP
.fi

.PP
References \fBstrnz__cpy()\fP, and \fBview\fP\&.
.PP
Referenced by \fBlp()\fP, and \fBview_cmd_processor()\fP\&.
.SS "void display_line (View * view)"

.PP
Display Line on Pad\&. 
.PP
Definition at line \fB1460\fP of file \fBview_engine\&.c\fP\&.
.nf
1460                               {
1461     int rc;
1462     if (view\->cury < 0)
1463         view\->cury = 0;
1464     if (view\->cury > view\->scroll_lines \- 1)
1465         view\->cury = view\->scroll_lines \- 1;
1466     wmove(view\->win, view\->cury, 0);
1467     wclrtoeol(view\->win);
1468     wadd_wchstr(view\->win, view\->cmplx_buf);
1469     view\->cury++;
1470     refresh();
1471     rc = prefresh(view\->win, view\->pminrow, view\->pmincol, view\->sminrow,
1472                   view\->smincol, view\->smaxrow, view\->smaxcol);
1473     if (rc == ERR)
1474         Perror("Error refreshing screen");
1475 }
.PP
.fi

.PP
References \fBPerror()\fP, and \fBview\fP\&.
.PP
Referenced by \fBnext_page()\fP, \fBredisplay_page()\fP, \fBscroll_down_n_lines()\fP, \fBscroll_up_n_lines()\fP, and \fBsearch()\fP\&.
.SS "bool enter_file_spec (Init * init, char * file_spec)"

.PP
use form to enter a file specification 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP data structure 
.br
\fIfile_spec\fP - pointer to file specification the file_spec 
.RE
.PP
\fBReturns\fP
.RS 4
true if successful 
.RE
.PP
\fBNote\fP
.RS 4
the user must provide a character array large enough to hold file_spec without overflowing 
.RE
.PP
call form to get file_name write the name to a temporary file

.PP
read file_name from tmp_spec
.PP
Definition at line \fB1809\fP of file \fBview_engine\&.c\fP\&.
.nf
1809                                                   {
1810     char tmp_dir[MAXLEN];
1811     char tmp_str[MAXLEN];
1812     char tmp_spec[MAXLEN];
1813     int rc = false;
1814     FILE *tmp_fp;
1815     view = init\->view;
1816     strnz__cpy(tmp_dir, init\->mapp_home, MAXLEN \- 1);
1817     strnz__cat(tmp_dir, "/tmp", MAXLEN \- 1);
1818     expand_tilde(tmp_dir, MAXLEN \- 1);
1819     if (!mk_dir(tmp_dir)) {
1820         strnz__cpy(em0, "Unable to create ", MAXLEN \- 1);
1821         strnz__cat(em0, tmp_dir, MAXLEN \- 1);
1822         return false;
1823     }
1824     while (rc == false) {
1825         strnz__cpy(tmp_spec, tmp_dir, MAXLEN \- 1);
1826         strnz__cat(tmp_spec, "/tmp_XXXXXX", MAXLEN \- 1);
1827         view\->in_fd = mkstemp(tmp_spec);
1828         if (view\->in_fd == \-1) {
1829             ssnprintf(em0, MAXLEN \- 1, "%s, line: %d", __FILE__, __LINE__ \- 2);
1830             strnz__cpy(em1, "mkstemp ", MAXLEN \- 1);
1831             strnz__cat(em1, tmp_spec, MAXLEN \- 1);
1832             strerror_r(errno, em2, MAXLEN \- 1);
1833             display_error(em0, em1, nullptr, nullptr);
1834             return (false);
1835         }
1838         strnz__cpy(earg_str, "form \-d file_name\&.f \-o ", MAXLEN \- 1);
1839         strnz__cat(earg_str, tmp_spec, MAXLEN \- 1);
1840         eargc = str_to_args(eargv, earg_str, MAX_ARGS);
1841         zero_opt_args(init);
1842         parse_opt_args(init, eargc, eargv);
1843         rc = init_form(init, eargc, eargv, view\->begy + view\->lines \- 7, 4);
1844         if (rc == P_CANCEL || rc == 'q' || rc == 'Q' || rc == KEY_F(9)) {
1845             destroy_form(init);
1846             view\->f_redisplay_page = true;
1847             return (false);
1848         }
1849         destroy_form(init);
1850         close(view\->in_fd);
1852         tmp_fp = fopen(tmp_spec, "r");
1853         if (tmp_fp == nullptr) {
1854             ssnprintf(em0, MAXLEN \- 1, "%s, line: %d", __FILE__, __LINE__ \- 2);
1855             strnz__cpy(em1, "fopen ", MAXLEN \- 1);
1856             strnz__cat(em1, tmp_spec, MAXLEN \- 1);
1857             strerror_r(errno, em2, MAXLEN \- 1);
1858             display_error(em0, em1, em2, nullptr);
1859             return (false);
1860         }
1861         fgets(tmp_str, MAXLEN \- 1, tmp_fp);
1862         strnz(tmp_str, MAXLEN \- 1);
1863         fclose(tmp_fp);
1864         unlink(tmp_spec);
1865         if (!verify_spec_arg(file_spec, tmp_str, "~/menuapp/tmp", "\&.",
1866                              S_WCOK | S_QUIET)) {
1867             ssnprintf(em0, MAXLEN \- 1, "Unable to open %s for writing",
1868                       tmp_str);
1869             strnz__cpy(em1, "Try again", MAXLEN \- 1);
1870             rc = display_error(em0, em1, nullptr, nullptr);
1871             if (rc == 'y' || rc == 'Y')
1872                 continue;
1873         } else {
1874             return true;
1875         }
1876     }
1877     return true;
1878 }
.PP
.fi

.PP
References \fBdestroy_form()\fP, \fBdisplay_error()\fP, \fBearg_str\fP, \fBeargc\fP, \fBeargv\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBexpand_tilde()\fP, \fBinit\fP, \fBinit_form()\fP, \fBMAXLEN\fP, \fBmk_dir()\fP, \fBparse_opt_args()\fP, \fBssnprintf()\fP, \fBstr_to_args()\fP, \fBstrnz()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, \fBverify_spec_arg()\fP, \fBview\fP, and \fBzero_opt_args()\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "int fmt_line (View * view)"

.PP
Format Line for Display\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBview\fP\fP pointer to View structure containing line input and output buffers 
.RE
.PP
\fBReturns\fP
.RS 4
length of formatted line in characters
.RE
.PP
This function processes the input line from view->line_in_s, handling ANSI escape sequences for text attributes and colors, as well as multi-byte characters\&. It converts the input line into a formatted line suitable for display in the terminal, storing the result in view->cmplx_buf and view->stripped_line_out\&. The function returns the length of the formatted line in characters, which may be used for tracking the maximum column width of the displayed content\&. Initialize multibyte to wide char conversion

.PP
Handle ANSI escape sequences

.PP
Wide and complex characters
.PP
Definition at line \fB1488\fP of file \fBview_engine\&.c\fP\&.
.nf
1488                          {
1489     attr_t attr = WA_NORMAL;
1490     char ansi_tok[MAXLEN];
1491     int cpx = cp_norm;
1492     int i = 0, j = 0;
1493     int len = 0;
1494     const char *s;
1495     wchar_t wc = L'\\0';
1496     cchar_t cc = {0};
1497     char *in_str = view\->line_in_s;
1498     cchar_t *cmplx_buf = view\->cmplx_buf;
1499 
1500     rtrim(view\->line_out_s);
1502     mbstate_t mbstate;
1503     memset(&mbstate, 0, sizeof(mbstate));
1504     while (in_str[i] != '\\0') {
1505         if (in_str[i] == '\\033' && in_str[i + 1] == '[') {
1507             len = strcspn(&in_str[i], "mK ") + 1;
1508             memcpy(ansi_tok, &in_str[i], len + 1);
1509             ansi_tok[len] = '\\0';
1510             if (ansi_tok[0] == '\\0') {
1511                 if (i + 2 < MAXLEN)
1512                     i += 2;
1513                 continue;
1514             }
1515             if (len == 0 || in_str[i + len \- 1] == ' ') {
1516                 i += 2;
1517                 continue;
1518             } else if (in_str[i + len \- 1] == 'K') {
1519                 i += len;
1520                 continue;
1521             }
1522             parse_ansi_str(ansi_tok, &attr, &cpx);
1523             i += len;
1524         } else {
1526             if (in_str[i] == '\\033') {
1527                 i++;
1528                 continue;
1529             }
1530             s = &in_str[i];
1531             if (*s == '\\t') {
1532                 wc = L' ';
1533                 do {
1534                     setcchar(&cc, &wc, attr, cpx, nullptr);
1535                     view\->stripped_line_out[j] = ' ';
1536                     cmplx_buf[j++] = cc;
1537                 } while ((j < PAD_COLS \- 2) && (j % view\->tab_stop != 0));
1538                 i++;
1539             } else {
1540                 len = mbrtowc(&wc, s, MB_CUR_MAX, &mbstate);
1541                 if (len <= 0) {
1542                     wc = L'?';
1543                     len = 1;
1544                 }
1545                 if (setcchar(&cc, &wc, attr, cpx, nullptr) != ERR) {
1546                     if (len > 0 && (j + len) < PAD_COLS \- 1) {
1547                         view\->stripped_line_out[j] = *s;
1548                         cmplx_buf[j++] = cc;
1549                     }
1550                 }
1551                 i += len;
1552             }
1553         }
1554     }
1555     if (j > view\->maxcol)
1556         view\->maxcol = j;
1557     wc = L'\\0';
1558     setcchar(&cc, &wc, WA_NORMAL, cpx, nullptr);
1559     cmplx_buf[j] = cc;
1560     view\->stripped_line_out[j] = '\\0';
1561     return j;
1562 }
.PP
.fi

.PP
References \fBcp_norm\fP, \fBin_str\fP, \fBMAXLEN\fP, \fBparse_ansi_str()\fP, \fBrtrim()\fP, and \fBview\fP\&.
.PP
Referenced by \fBnext_page()\fP, \fBredisplay_page()\fP, \fBscroll_down_n_lines()\fP, \fBscroll_up_n_lines()\fP, and \fBsearch()\fP\&.
.SS "int get_cmd_arg (View * view, char * prompt)"

.PP
Get Command Argument from User Input\&. Basic Editing Keys for Command Line
.PP
Definition at line \fB684\fP of file \fBview_engine\&.c\fP\&.
.nf
684                                           {
685     int c;
686     int numeric_arg = false;
687     char *cmd_p;
688     char *cmd_e;
689     char prompt_s[PAD_COLS + 1];
690     char *n;
691     int rc, prompt_l;
692     prompt_l = strnz__cpy(prompt_s, prompt, view\->cols \- 4);
693     if (view\->cmd_arg[0] != '\\0')
694         return 0;
695     cmd_p = view\->cmd_arg;
696     cmd_e = view\->cmd_arg + MAXLEN \- 2;
697     wmove(view\->win, view\->cmd_line, 0);
698     if (prompt_l == 0)
699         numeric_arg = true;
700     if (prompt_l > 1) {
701         wstandout(view\->win);
702         waddch(view\->win, ' ');
703         waddstr(view\->win, prompt_s);
704         waddch(view\->win, ' ');
705         wstandend(view\->win);
706     } else {
707         if (*prompt == ':')
708             numeric_arg = true;
709         else {
710             n = prompt;
711             if (*n >= '0' && *n <= '9') {
712                 *cmd_p++ = *n;
713                 *cmd_p = '\\0';
714                 numeric_arg = true;
715             }
716         }
717         waddstr(view\->win, prompt_s);
718         wmove(view\->win, view\->cmd_line, prompt_l);
719     }
720     wclrtoeol(view\->win);
721     while (1) {
722         rc = prefresh(view\->win, view\->pminrow, view\->pmincol, view\->sminrow,
723                       view\->smincol, view\->smaxrow, view\->smaxcol);
724         if (rc == ERR)
725             Perror("Error refreshing screen");
726         c = xwgetch(view\->win, nullptr);
727         switch (c) {
729         case KEY_LEFT:
730         case KEY_BACKSPACE:
731         case '\\b':
732             if (cmd_p > view\->cmd_arg) {
733                 cmd_p\-\-;
734                 if (*cmd_p < ' ' || *cmd_p == 0x7f) {
735                     getyx(view\->win, view\->cury, view\->curx);
736                     if (view\->curx > 0) {
737                         view\->curx\-\-;
738                         wmove(view\->win, view\->cmd_line, view\->curx);
739                         waddch(view\->win, ' ');
740                         wmove(view\->win, view\->cmd_line, view\->curx);
741                     }
742                 }
743                 getyx(view\->win, view\->cury, view\->curx);
744                 if (view\->curx > 0) {
745                     view\->curx\-\-;
746                     wmove(view\->win, view\->cmd_line, view\->curx);
747                     waddch(view\->win, ' ');
748                     wmove(view\->win, view\->cmd_line, view\->curx);
749                 }
750             }
751             break;
752         case '\\n':
753         case KEY_ENTER:
754             return c;
755         case '\\033':
756         case KEY_F(9):
757             return c;
758         case KEY_MOUSE:
759             continue;
760         default:
761             *cmd_p++ = (char)c;
762             *cmd_p = '\\0';
763             if ((char)c < ' ') {
764                 waddch(view\->win, '^');
765                 c |= '@';
766             } else if ((uchar)c == 0x7f)
767                 c = '?';
768             waddch(view\->win, (char)c);
769             if (cmd_p >= cmd_e)
770                 return 0;
771             if (numeric_arg && (c < '0' || c > '9'))
772                 return \-1;
773             break;
774         }
775     }
776     return c;
777 }
.PP
.fi

.PP
References \fBMAXLEN\fP, \fBPerror()\fP, \fBstrnz__cpy()\fP, \fBview\fP, and \fBxwgetch()\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "int get_cmd_char (View * view, off_t * n)"

.PP
Get Command Character and Numeric Argument\&. 
.PP
Definition at line \fB655\fP of file \fBview_engine\&.c\fP\&.
.nf
655                                        {
656     int c = 0, i = 0;
657     char cmd_str[33];
658     cmd_str[0] = '\\0';
659     MEVENT event;
660     mousemask(BUTTON4_PRESSED | BUTTON5_PRESSED, nullptr);
661     tcflush(2, TCIFLUSH);
662     do {
663         c = xwgetch(view\->win, nullptr);
664         if (c == KEY_MOUSE) {
665             if (getmouse(&event) != OK)
666                 return (MA_ENTER_OPTION);
667             if (event\&.bstate & BUTTON4_PRESSED)
668                 return (KEY_UP);
669             else if (event\&.bstate & BUTTON5_PRESSED) {
670                 return (KEY_DOWN);
671             }
672         } else {
673             if (c >= '0' && c <= '9' && i < 32) {
674                 cmd_str[i++] = (char)c;
675                 cmd_str[i] = '\\0';
676             }
677         }
678     } while (c >= '0' && c <= '9');
679     *n = atol(cmd_str);
680     view\->cmd_arg[0] = '\\0';
681     return (c);
682 }
.PP
.fi

.PP
References \fBview\fP, and \fBxwgetch()\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "off_t get_next_line (View * view, off_t pos)"

.PP
Get Next Line from File\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBview\fP\fP struct 
.br
\fIpos\fP buffer offset 
.RE
.PP
\fBReturns\fP
.RS 4
file position of next line 
.RE
.PP
\fBNote\fP
.RS 4
gets view->line_in_s 
.RE
.PP

.PP
Definition at line \fB1350\fP of file \fBview_engine\&.c\fP\&.
.nf
1350                                            {
1351     uchar c;
1352     char *line_in_p;
1353     view\->file_pos = pos;
1354     view\->f_eod = false;
1355     do {
1356         if (view\->file_pos == view\->file_size) {
1357             view\->f_eod = true;
1358             break;
1359         }
1360         c = view\->buf[view\->file_pos++];
1361     } while (c == 0x0d);
1362     if (view\->f_eod)
1363         return view\->file_pos;
1364     line_in_p = view\->line_in_s;
1365     view\->line_in_beg_p = view\->line_in_s;
1366     view\->line_in_end_p = view\->line_in_s + PAD_COLS;
1367     while (1) {
1368         if (c == (uchar)'\\n')
1369             break;
1370         if (line_in_p >= view\->line_in_end_p)
1371             break;
1372         *line_in_p++ = c;
1373         do {
1374             if (view\->file_pos == view\->file_size) {
1375                 view\->f_eod = true;
1376                 break;
1377             }
1378             c = view\->buf[view\->file_pos++];
1379         } while (c == 0x0d);
1380         if (view\->f_eod)
1381             return view\->file_pos;
1382     }
1383     *line_in_p = '\\0';
1384     if (view\->f_squeeze) {
1385         while (1) {
1386             get_next_char();
1387             if (view\->f_eod)
1388                 break;
1389             if (c != (uchar)'\\n')
1390                 break;
1391         }
1392         get_prev_char();
1393     }
1394     return view\->file_pos;
1395 }
.PP
.fi

.PP
References \fBget_next_char\fP, \fBget_prev_char\fP, and \fBview\fP\&.
.PP
Referenced by \fBget_prev_line()\fP, \fBnext_page()\fP, \fBredisplay_page()\fP, \fBscroll_down_n_lines()\fP, \fBscroll_up_n_lines()\fP, \fBsearch()\fP, and \fBwrite_view_buffer()\fP\&.
.SS "off_t get_pos_next_line (View * view, off_t pos)"

.PP
Get Position of Next Line\&. 
.PP
Definition at line \fB1404\fP of file \fBview_engine\&.c\fP\&.
.nf
1404                                                {
1405     uchar c;
1406     if (pos == view\->file_size) {
1407         view\->f_eod = true;
1408         return view\->file_pos;
1409     } else
1410         view\->f_eod = false;
1411     view\->file_pos = pos;
1412     get_next_char();
1413     if (view\->f_eod)
1414         return view\->file_pos;
1415     if (view\->f_squeeze) {
1416         while (1) {
1417             if (c != '\\n')
1418                 break;
1419             get_next_char();
1420             if (view\->f_eod)
1421                 return view\->file_pos;
1422         }
1423         get_prev_char();
1424         if (view\->f_eod)
1425             return view\->file_pos;
1426     }
1427     while (!view\->f_eod) {
1428         if (c == '\\n')
1429             break;
1430         get_next_char();
1431     }
1432     return view\->file_pos;
1433 }
.PP
.fi

.PP
References \fBget_next_char\fP, \fBget_prev_char\fP, and \fBview\fP\&.
.PP
Referenced by \fBscroll_down_n_lines()\fP\&.
.SS "off_t get_pos_prev_line (View * view, off_t pos)"

.PP
Get Position of Previous Line\&. 
.PP
Definition at line \fB1435\fP of file \fBview_engine\&.c\fP\&.
.nf
1435                                                {
1436     uchar c;
1437     view\->file_pos = pos;
1438     if (view\->file_pos == 0) {
1439         view\->f_bod = true;
1440         return view\->file_pos;
1441     }
1442     get_prev_char();
1443     if (view\->f_bod)
1444         return view\->file_pos;
1445     if (c == '\\n') {
1446         get_prev_char();
1447         if (view\->f_bod)
1448             return view\->file_pos;
1449     }
1450     while (!view\->f_bod) {
1451         if (c == '\\n') {
1452             get_next_char();
1453             break;
1454         }
1455         get_prev_char();
1456     }
1457     return view\->file_pos;
1458 }
.PP
.fi

.PP
References \fBget_next_char\fP, \fBget_prev_char\fP, and \fBview\fP\&.
.PP
Referenced by \fBget_prev_line()\fP, \fBprev_page()\fP, and \fBscroll_up_n_lines()\fP\&.
.SS "off_t get_prev_line (View * view, off_t pos)"

.PP
Get Previous Line from File\&. 
.PP
Definition at line \fB1397\fP of file \fBview_engine\&.c\fP\&.
.nf
1397                                            {
1398     pos = get_pos_prev_line(view, pos);
1399     view\->file_pos = pos;
1400     get_next_line(view, view\->file_pos);
1401     return pos;
1402 }
.PP
.fi

.PP
References \fBget_next_line()\fP, \fBget_pos_prev_line()\fP, and \fBview\fP\&.
.PP
Referenced by \fBsearch()\fP\&.
.SS "void go_to_eof (View * view)"

.PP
Go to End of File\&. 
.PP
Definition at line \fB927\fP of file \fBview_engine\&.c\fP\&.
.nf
927                            {
928     int c;
929     view\->file_pos = view\->file_size;
930     view\->page_top_pos = view\->file_pos;
931     get_prev_char();
932     prev_page(view);
933 }
.PP
.fi

.PP
References \fBget_prev_char\fP, \fBprev_page()\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "int go_to_line (View * view, off_t line_idx)"

.PP
Go to Specific Line\&. 
.PP
Definition at line \fB935\fP of file \fBview_engine\&.c\fP\&.
.nf
935                                            {
936     char tmp_str[MAXLEN];
937     int c = 0;
938     off_t line_cnt = 0;
939     if (line_idx <= 1) {
940         go_to_position(view, 0);
941         return EOF;
942     }
943     view\->file_pos = 0;
944     view\->page_top_pos = view\->file_pos;
945     line_idx = 0;
946     view\->f_eod = false;
947     do {
948         while (c != '\\n') {
949             get_next_char();
950             if (view\->f_eod) {
951                 sprintf(tmp_str, "End of data at %ld lines", line_cnt \- 1);
952                 Perror(tmp_str);
953                 return EOF;
954             }
955         }
956         get_next_char();
957     } while (line_cnt < line_idx \- 1);
958     view\->page_top_pos = view\->file_pos;
959     prev_page(view);
960     return 0;
961 }
.PP
.fi

.PP
References \fBget_next_char\fP, \fBgo_to_position()\fP, \fBMAXLEN\fP, \fBPerror()\fP, \fBprev_page()\fP, \fBtmp_str\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "void go_to_mark (View * view, int c)"

.PP
Go to Mark\&. 
.PP
Definition at line \fB916\fP of file \fBview_engine\&.c\fP\&.
.nf
916                                    {
917     if (c == '\\'')
918         view\->file_pos = view\->mark_tbl[(NMARKS \- 1)];
919     else
920         view\->file_pos = view\->mark_tbl[c \- 'a'];
921     if (view\->file_pos == NULL_POSITION)
922         Perror("Mark not set");
923     else
924         go_to_position(view, view\->file_pos);
925 }
.PP
.fi

.PP
References \fBgo_to_position()\fP, \fBPerror()\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "void go_to_percent (View * view, int percent)"

.PP
Go to Percent of File\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBview\fP\fP data structure 
.br
\fIpercent\fP of file 
.RE
.PP

.PP
Definition at line \fB966\fP of file \fBview_engine\&.c\fP\&.
.nf
966                                             {
967     int c = 0;
968     if (view\->file_size < 0) {
969         Perror("Cannot determine file length");
970         return;
971     }
972     view\->file_pos = (percent * view\->file_size) / 100;
973     get_next_char();
974     while (c != '\\n') {
975         get_prev_char();
976         if (view\->f_bod)
977             break;
978     }
979     get_next_char();
980     next_page(view);
981 }
.PP
.fi

.PP
References \fBget_next_char\fP, \fBget_prev_char\fP, \fBnext_page()\fP, \fBPerror()\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "void go_to_position (View * view, off_t go_to_pos)"

.PP
Go to Specific File Position\&. 
.PP
Definition at line \fB983\fP of file \fBview_engine\&.c\fP\&.
.nf
983                                                  {
984     view\->file_pos = go_to_pos;
985     view\->page_bot_pos = view\->file_pos;
986     next_page(view);
987 }
.PP
.fi

.PP
References \fBnext_page()\fP, and \fBview\fP\&.
.PP
Referenced by \fBgo_to_line()\fP, and \fBgo_to_mark()\fP\&.
.SS "void lp (char * PrintFile)"

.PP
Send File to Print Queue\&. 
.PP
\fBParameters\fP
.RS 4
\fIPrintFile\fP - file to print 
.RE
.PP

.PP
Definition at line \fB903\fP of file \fBview_engine\&.c\fP\&.
.nf
903                          {
904     char *print_cmd_ptr;
905     char shell_cmd_spec[MAXLEN];
906     print_cmd_ptr = getenv("PRINTCMD");
907     if (print_cmd_ptr == nullptr || *print_cmd_ptr == '\\0')
908         print_cmd_ptr = PRINTCMD;
909     sprintf(shell_cmd_spec, "%s %s", print_cmd_ptr, PrintFile);
910     cmd_line_prompt(view, shell_cmd_spec);
911     prefresh(view\->win, view\->pminrow, view\->pmincol, view\->sminrow,
912              view\->smincol, view\->smaxrow, view\->smaxcol);
913     shell(shell_cmd_spec);
914 }
.PP
.fi

.PP
References \fBcmd_line_prompt()\fP, \fBMAXLEN\fP, \fBshell()\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "void next_page (View * view)"

.PP
Advance to Next Page\&. 
.PP
Definition at line \fB1228\fP of file \fBview_engine\&.c\fP\&.
.nf
1228                            {
1229     int i;
1230     int line_len;
1231     curs_set(0);
1232     if (view\->page_bot_pos == view\->file_size)
1233         return;
1234     view\->maxcol = 0;
1235     view\->cury = 0;
1236     view\->file_pos = view\->page_bot_pos;
1237     view\->page_top_pos = view\->file_pos;
1238     wmove(view\->win, view\->cury, 0);
1239     wclrtobot(view\->win);
1240     for (i = 0; i < view\->scroll_lines; i++) {
1241         get_next_line(view, view\->file_pos);
1242         if (view\->f_eod)
1243             break;
1244         line_len = fmt_line(view);
1245         if (line_len > view\->maxcol)
1246             view\->maxcol = line_len;
1247         display_line(view);
1248     }
1249     view\->page_bot_pos = view\->file_pos;
1250     curs_set(1);
1251 }
.PP
.fi

.PP
References \fBdisplay_line()\fP, \fBfmt_line()\fP, \fBget_next_line()\fP, and \fBview\fP\&.
.PP
Referenced by \fBgo_to_percent()\fP, \fBgo_to_position()\fP, \fBprev_page()\fP, \fBview_cmd_processor()\fP, and \fBview_file()\fP\&.
.SS "void parse_ansi_str (char * ansi_str, attr_t * attr, int * cpx)"

.PP
Parse ANSI SGR Escape Sequence\&. 
.PP
\fBParameters\fP
.RS 4
\fIansi_str\fP is the ANSI escape sequence string to parse 
.br
\fIattr\fP is a pointer to an attr_t variable where the parsed attributes will be stored 
.br
\fIcpx\fP is a pointer to an int variable where the parsed color pair index will be stored
.RE
.PP
This function parses an ANSI SGR (Select Graphic Rendition) escape sequence and updates the provided attr_t and color pair index based on the attributes specified in the ANSI string\&.

.PP
.PP
.nf
 This function converts the following SGR specification types to the
appropriate curses color pair index for use in the terminal display\&.

 RGB:

     foreground \\033[38;2;r;g;bm
     background \\033[48;2;r;g;bm

     Where r, g, b are the red, green, and blue color components
(0\-255)

 XTERM 256\-color:

     foreground \\033[38;5;xm
     background \\033[48;5;xm

     Where x is the 256\-color index (0\-255)

     uses xterm256_idx_to_rgb() to convert the 256\-color index to
RGB

 8\-color:

     foreground \\033[3cm
     background \\033[4cm

     Where c is the color code (0 for black, 1 for red, 2 for green, 3 for
yellow, 4 for blue, 5 for magenta, 6 for cyan, 7 for white)\&.

 Attributes:

     \\033[am

     Where a is the attribute code (1 for bold, 2 for dim, 3 for italic, 4
for underline, 5 for blink, 7 for reverse, 8 for invis)\&. The function also
supports resetting attributes and colors to default using \\033[0m\&.

 @sa xterm256_idx_to_rgb(), rgb_to_curses_clr(), extended_pair_content(),
get_clr_pair()
.fi
.PP
 
.PP
Definition at line \fB1617\fP of file \fBview_engine\&.c\fP\&.
.nf
1617                                                             {
1618     char *tok;
1619     char t0, t1;
1620     int len, x_idx;
1621     int fg, bg;
1622     int fg_clr, bg_clr;
1623     char *ansi_p = ansi_str + 2;
1624     extended_pair_content(*cpx, &fg_clr, &bg_clr);
1625     fg = fg_clr;
1626     bg = bg_clr;
1627     RGB rgb;
1628     tok = strtok((char *)ansi_p, ";m");
1629     bool a_toi_error = false;
1630     while (1) {
1631         if (tok == nullptr || *tok == '\\0')
1632             break;
1633         len = strlen(tok);
1634         if (len == 2) {
1635             t0 = tok[0];
1636             t1 = tok[1];
1637             if (t0 == '3' || t0 == '4') {
1638                 if (t1 == '8') {
1639                     tok = strtok(nullptr, ";m");
1640                     if (tok != nullptr) {
1641                         if (*tok == '5') {
1642                             tok = strtok(nullptr, ";m");
1643                             if (tok != nullptr) {
1644                                 x_idx = a_toi(tok, &a_toi_error);
1645                                 rgb = xterm256_idx_to_rgb(x_idx);
1646                             }
1647                         } else if (*tok == '2') {
1648                             tok = strtok(nullptr, ";m");
1649                             rgb\&.r = a_toi(tok, &a_toi_error);
1650                             tok = strtok(nullptr, ";m");
1651                             rgb\&.g = a_toi(tok, &a_toi_error);
1652                             tok = strtok(nullptr, ";m");
1653                             rgb\&.b = a_toi(tok, &a_toi_error);
1654                         }
1655                     }
1656                     if (t0 == '3')
1657                         fg_clr = rgb_to_curses_clr(&rgb);
1658                     else if (t0 == '4')
1659                         bg_clr = rgb_to_curses_clr(&rgb);
1660                 } else if (t1 == '9') {
1661                     if (t0 == '3')
1662                         fg_clr = COLOR_WHITE;
1663                     else if (t0 == '4')
1664                         bg_clr = COLOR_BLACK;
1665                 } else if (t1 >= '0' && t1 <= '7') {
1666                     if (t0 == '3') {
1667                         x_idx = a_toi(&t1, &a_toi_error);
1668                         rgb = xterm256_idx_to_rgb(x_idx);
1669                         fg_clr = rgb_to_curses_clr(&rgb);
1670                     } else if (t0 == '4') {
1671                         x_idx = a_toi(&t1, &a_toi_error);
1672                         rgb = xterm256_idx_to_rgb(x_idx);
1673                         bg_clr = rgb_to_curses_clr(&rgb);
1674                     }
1675                 }
1676             } else if (t0 == '0') {
1677                 *tok = t1;
1678                 len = 1;
1679             }
1680         }
1681         if (len == 1) {
1682             if (*tok == '0') {
1683                 *attr = WA_NORMAL;
1684                 fg_clr = COLOR_WHITE;
1685                 bg_clr = COLOR_BLACK;
1686             } else {
1687                 switch (a_toi(tok, &a_toi_error)) {
1688                 case 1:
1689                     *attr |= WA_BOLD;
1690                     break;
1691                 case 2:
1692                     *attr |= WA_DIM;
1693                     break;
1694                 case 3:
1695                     *attr |= WA_ITALIC;
1696                     break;
1697                 case 4:
1698                     *attr |= WA_UNDERLINE;
1699                     break;
1700                 case 5:
1701                     *attr |= WA_BLINK;
1702                     break;
1703                 case 7:
1704                     *attr |= WA_REVERSE;
1705                     break;
1706                 case 8:
1707                     *attr |= WA_INVIS;
1708                     break;
1709                 default:
1710                     break;
1711                 }
1712             }
1713         } else if (len == 0) {
1714             *attr = WA_NORMAL;
1715             fg_clr = COLOR_WHITE;
1716             bg_clr = COLOR_BLACK;
1717         }
1718         tok = strtok(nullptr, ";m");
1719     }
1720     if (!a_toi_error && (fg_clr != fg || bg_clr != bg)) {
1721         clr_pair_idx = get_clr_pair(fg_clr, bg_clr);
1722         *cpx = clr_pair_idx;
1723     }
1724     return;
1725 }
.PP
.fi

.PP
References \fBa_toi()\fP, \fBclr_pair_idx\fP, \fBget_clr_pair()\fP, \fBrgb_to_curses_clr()\fP, and \fBxterm256_idx_to_rgb()\fP\&.
.PP
Referenced by \fBfmt_line()\fP\&.
.SS "void prev_page (View * view)"

.PP
display previous page 
.PP
Definition at line \fB1253\fP of file \fBview_engine\&.c\fP\&.
.nf
1253                            {
1254     int i;
1255     curs_set(0);
1256     if (view\->page_top_pos == 0)
1257         return;
1258     view\->maxcol = 0;
1259     view\->cury = 0;
1260     wmove(view\->win, view\->cury, 0);
1261     view\->file_pos = view\->page_top_pos;
1262     view\->page_bot_pos = view\->file_pos;
1263     for (i = 0; i < view\->scroll_lines; i++) {
1264         get_pos_prev_line(view, view\->file_pos);
1265         if (view\->f_bod)
1266             break;
1267     }
1268     view\->page_bot_pos = view\->file_pos;
1269     next_page(view);
1270 }
.PP
.fi

.PP
References \fBget_pos_prev_line()\fP, \fBnext_page()\fP, and \fBview\fP\&.
.PP
Referenced by \fBgo_to_eof()\fP, and \fBgo_to_line()\fP\&.
.SS "void redisplay_page (View * view)"

.PP
Redisplay Current Page\&. 
.PP
Definition at line \fB1211\fP of file \fBview_engine\&.c\fP\&.
.nf
1211                                 {
1212     int i;
1213     int line_len;
1214     view\->cury = 0;
1215     wmove(view\->win, view\->cury, 0);
1216     view\->page_bot_pos = view\->page_top_pos;
1217     for (i = 0; i < view\->scroll_lines; i++) {
1218         view\->page_bot_pos = get_next_line(view, view\->page_bot_pos);
1219         if (view\->f_eod)
1220             break;
1221         line_len = fmt_line(view);
1222         if (line_len > view\->maxcol)
1223             view\->maxcol = line_len;
1224         display_line(view);
1225     }
1226 }
.PP
.fi

.PP
References \fBdisplay_line()\fP, \fBfmt_line()\fP, \fBget_next_line()\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "void remove_file (View * view)"

.PP
Remove File\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBview\fP\fP is the current view data structure 
.RE
.PP

.PP
Definition at line \fB1748\fP of file \fBview_engine\&.c\fP\&.
.nf
1748                              {
1749     char c;
1750     if (view\->f_at_end_remove) {
1751         wmove(view\->win, view\->cmd_line, 0);
1752         waddstr(view\->win, "Remove File (Y or N)\->");
1753         wclrtoeol(view\->win);
1754         c = (char)xwgetch(view\->win, nullptr);
1755         waddch(view\->win, (char)toupper(c));
1756         if (c == 'Y' || c == 'y')
1757             remove(view\->cur_file_str);
1758     }
1759 }
.PP
.fi

.PP
References \fBview\fP, and \fBxwgetch()\fP\&.
.SS "void resize_page (Init * init)"

.PP
Resize Viewing Page\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP data structure 
.RE
.PP

.PP
Definition at line \fB1171\fP of file \fBview_engine\&.c\fP\&.
.nf
1171                              {
1172     int scr_lines, scr_cols;
1173     bool f_resize = false;
1174     view = init\->view;
1175     if (view\->f_full_screen) {
1176         getmaxyx(stdscr, view\->lines, view\->cols);
1177         view\->scroll_lines = view\->lines \- 1;
1178         view\->cmd_line = view\->lines \- 1;
1179         view\->smaxrow = view\->lines \- 1;
1180         view\->smaxcol = view\->cols \- 1;
1181         wresize(view\->win, view\->lines, view\->cols);
1182         wrefresh(view\->win);
1183         wsetscrreg(view\->win, 0, view\->scroll_lines);
1184         f_resize = true;
1185     } else {
1186         getmaxyx(stdscr, scr_lines, scr_cols);
1187         if (view\->begy + view\->lines + 2 > scr_lines) {
1188             view\->lines = (scr_lines \- view\->begy) \- 2;
1189             f_resize = true;
1190         }
1191         if (view\->begx + view\->cols + 2 > scr_cols) {
1192             view\->cols = (scr_cols \- view\->begx) \- 2;
1193             f_resize = true;
1194         }
1195         if (f_resize) {
1196             view\->scroll_lines = view\->lines \- 1;
1197             view\->cmd_line = view\->lines \- 1;
1198             view\->smaxrow = view\->lines \- 1;
1199             view\->smaxcol = view\->cols \- 1;
1200             win_resize(view\->lines + 2, view\->cols + 2, view\->title);
1201             restore_wins();
1202             wsetscrreg(view\->win, 0, view\->scroll_lines);
1203         }
1204     }
1205     if (f_resize)
1206         view\->f_redisplay_page = true;
1207     else
1208         view\->f_redisplay_page = false;
1209 }
.PP
.fi

.PP
References \fBinit\fP, \fBrestore_wins()\fP, \fBview\fP, and \fBwin_resize()\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "void scroll_down_n_lines (View * view, int n)"

.PP
Scroll N Lines\&. Locate New Top of Page

.PP
Scroll

.PP
Fill in Page Bottom
.PP
Definition at line \fB1272\fP of file \fBview_engine\&.c\fP\&.
.nf
1272                                             {
1273     int i = 0;
1274     int line_len;
1275     curs_set(0);
1276     if (view\->page_bot_pos == view\->file_size)
1277         return;
1279     view\->file_pos = view\->page_top_pos;
1280     for (i = 0; i < n; i++) {
1281         view\->page_top_pos = get_pos_next_line(view, view\->file_pos);
1282         if (view\->f_eod)
1283             break;
1284     }
1285     n = i;
1287     wscrl(view\->win, n);
1289     view\->cury = view\->scroll_lines \- n;
1290     wmove(view\->win, view\->cury, 0);
1291     view\->file_pos = view\->page_bot_pos;
1292     for (i = 0; i < n; i++) {
1293         get_next_line(view, view\->file_pos);
1294         if (view\->f_eod)
1295             break;
1296         line_len = fmt_line(view);
1297         if (line_len > view\->maxcol)
1298             view\->maxcol = line_len;
1299         display_line(view);
1300     }
1301     view\->page_bot_pos = view\->file_pos;
1302     curs_set(1);
1303 }
.PP
.fi

.PP
References \fBdisplay_line()\fP, \fBfmt_line()\fP, \fBget_next_line()\fP, \fBget_pos_next_line()\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "void scroll_up_n_lines (View * view, int n)"

.PP
Scroll Up N Lines\&. Locate New Top of Page

.PP
Locate New Bottom of Page

.PP
Scroll Up

.PP
Fill in Page Top
.PP
Definition at line \fB1305\fP of file \fBview_engine\&.c\fP\&.
.nf
1305                                           {
1306     int i;
1307     int line_len;
1308     curs_set(0);
1309     if (view\->page_top_pos == 0)
1310         return;
1312     for (i = 0; i < n; i++) {
1313         if (view\->f_bod)
1314             break;
1315         view\->page_top_pos = get_pos_prev_line(view, view\->page_top_pos);
1316     }
1317     n = i;
1319     view\->f_bod = false;
1320     for (i = 0; i < n; i++) {
1321         if (view\->f_bod)
1322             break;
1323         view\->page_bot_pos = get_pos_prev_line(view, view\->page_bot_pos);
1324     }
1326     if (n < view\->scroll_lines)
1327         wscrl(view\->win, \-n);
1329     view\->cury = 0;
1330     wmove(view\->win, view\->cury, 0);
1331     view\->file_pos = view\->page_top_pos;
1332     for (i = 0; i < n; i++) {
1333         if (view\->f_eod)
1334             break;
1335         get_next_line(view, view\->file_pos);
1336         line_len = fmt_line(view);
1337         if (line_len > view\->maxcol)
1338             view\->maxcol = line_len;
1339         display_line(view);
1340     }
1341     curs_set(1);
1342     return;
1343 }
.PP
.fi

.PP
References \fBdisplay_line()\fP, \fBfmt_line()\fP, \fBget_next_line()\fP, \fBget_pos_prev_line()\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "bool search (View * view, int * search_cmd, char * regex_pattern)"

.PP
Search for Regular Expression Pattern\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBview\fP\fP Pointer to View Structure 
.br
\fIsearch_cmd\fP Search Command Character ('/' or '?') 
.br
\fIregex_pattern\fP Regular Expression Pattern to Search For 
.RE
.PP
\fBReturns\fP
.RS 4
true if a match is found and displayed, false if the search completes without finding a match or if an error occurs 
.RE
.PP
\fBNote\fP
.RS 4
The search performs extended regular expression matching, ignoring ANSI sequences and Unicode characters\&. Matches are highlighted on the screen, and the search continues until the page is full or the end of the file is reached\&. If the search wraps around the file, a message is displayed indicating that the search is complete\&. 

.PP
The search state is maintained in the view structure, allowing for repeat searches and tracking of the current search position\&. 

.PP
this function highlights all matches in the current ncurses pad, including those not displayed on the screen, and tracks the first and last match columns for prompt display\&. 

.PP
ANSI sequences and Unicode characters are stripped before matching, so matching corresponds to the visual display 
.RE
.PP
initialize iteration

.PP
get line to scan

.PP
non-matching page filler

.PP
Display matching lines

.PP
All matches on the current line are highlighted, including those not displayed on the screen\&. Track first and last match columns for prompt display\&.
.PP
Definition at line \fB1006\fP of file \fBview_engine\&.c\fP\&.
.nf
1006                                                               {
1007     char tmp_str[MAXLEN];
1008     int REG_FLAGS = 0;
1009     regmatch_t pmatch[1];
1010     regex_t compiled_regex;
1011     int reti;
1012     off_t prev_srch_pos;
1013     int line_offset;
1014     int line_len;
1015     int match_len;
1016     bool f_page = false;
1017     if (*regex_pattern == '\\0')
1018         return false;
1019     if (view\->f_ignore_case)
1020         REG_FLAGS = REG_ICASE | REG_EXTENDED;
1021     else
1022         REG_FLAGS = REG_EXTENDED;
1023     reti = regcomp(&compiled_regex, regex_pattern, REG_FLAGS);
1024     if (reti) {
1025         Perror("Invalid pattern");
1026         return false;
1027     }
1029     while (1) {
1031         if (*search_cmd == '/') {
1032             if (view\->srch_curr_pos == view\->file_size)
1033                 view\->srch_curr_pos = 0;
1034         } else {
1035             if (view\->srch_curr_pos == 0)
1036                 view\->srch_curr_pos = view\->file_size;
1037         }
1038         if (view\->srch_curr_pos == view\->srch_beg_pos) {
1039             if (view\->f_first_iter == true) {
1040                 view\->f_first_iter = false;
1041                 view\->f_search_complete = false;
1042                 if (*search_cmd == '/')
1043                     view\->cury = 0;
1044                 else
1045                     view\->cury = view\->scroll_lines + 1;
1046             } else {
1047                 view\->f_search_complete = true;
1048                 return true;
1049             }
1050         }
1052         prev_srch_pos = view\->srch_curr_pos;
1053         if (*search_cmd == '/') {
1054             if (view\->cury == view\->scroll_lines)
1055                 return true;
1056             view\->srch_curr_pos = get_next_line(view, view\->srch_curr_pos);
1057             view\->page_bot_pos = view\->srch_curr_pos;
1058         } else {
1059             if (view\->cury == 0)
1060                 return true;
1061             view\->srch_curr_pos = get_prev_line(view, view\->srch_curr_pos);
1062             view\->page_top_pos = view\->srch_curr_pos;
1063         }
1064         fmt_line(view);
1065         reti = regexec(&compiled_regex, view\->stripped_line_out,
1066                        compiled_regex\&.re_nsub + 1, pmatch, REG_FLAGS);
1067         if (reti == REG_NOMATCH) {
1068             if (f_page) {
1070                 if (*search_cmd == '?')
1071                     view\->cury \-= 2;
1072                 display_line(view);
1073                 if ((*search_cmd == '/' && view\->cury == view\->scroll_lines) ||
1074                     (*search_cmd == '?' && view\->cury == 1)) {
1075                     break;
1076                 }
1077             }
1078             continue;
1079         }
1080         if (reti) {
1081             char err_str[MAXLEN];
1082             regerror(reti, &compiled_regex, err_str, sizeof(err_str));
1083             strnz__cpy(tmp_str, "Regex match failed: ", MAXLEN \- 1);
1084             strnz__cat(tmp_str, err_str, MAXLEN \- 1);
1085             Perror(tmp_str);
1086             regfree(&compiled_regex);
1087             return false;
1088         }
1090         if (!f_page) {
1091             if (*search_cmd == '/') {
1092                 view\->page_top_pos = prev_srch_pos;
1093                 wmove(view\->win, view\->cury, 0);
1094             } else {
1095                 view\->page_bot_pos = prev_srch_pos;
1096                 wmove(view\->win, 0, 0);
1097             }
1098             wclrtobot(view\->win);
1099             f_page = true;
1100         }
1101         if (*search_cmd == '?')
1102             view\->cury \-= 2;
1103         display_line(view);
1107         view\->first_match_x = \-1;
1108         view\->last_match_x = 0;
1109         line_len = strlen(view\->stripped_line_out);
1110         line_offset = 0;
1111         while (1) {
1112             view\->curx = line_offset + pmatch[0]\&.rm_so;
1113             match_len = pmatch[0]\&.rm_eo \- pmatch[0]\&.rm_so;
1114             mvwchgat(view\->win, view\->cury \- 1, view\->curx, match_len,
1115                      WA_REVERSE, cp_norm, nullptr);
1116             if (view\->first_match_x == \-1)
1117                 view\->first_match_x = pmatch[0]\&.rm_so;
1118             view\->last_match_x = line_offset + pmatch[0]\&.rm_eo;
1119             line_offset += pmatch[0]\&.rm_eo;
1120             if (line_offset >= line_len)
1121                 break;
1122             view\->line_out_p = view\->stripped_line_out + line_offset;
1123             reti = regexec(&compiled_regex, view\->line_out_p,
1124                            compiled_regex\&.re_nsub + 1, pmatch, REG_FLAGS);
1125             if (reti == REG_NOMATCH)
1126                 break;
1127             if (reti) {
1128                 char msgbuf[100];
1129                 regerror(reti, &compiled_regex, msgbuf, sizeof(msgbuf));
1130                 sprintf(tmp_str, "Regex match failed: %s", msgbuf);
1131                 Perror(tmp_str);
1132                 regfree(&compiled_regex);
1133                 return false;
1134             }
1135             if (*search_cmd == '/') {
1136                 if (view\->cury == view\->scroll_lines) {
1137                     regfree(&compiled_regex);
1138                     return true;
1139                 }
1140             } else if (view\->cury == 1) {
1141                 regfree(&compiled_regex);
1142                 return true;
1143             }
1144         }
1145     }
1146     view\->file_pos = view\->srch_curr_pos;
1147 #ifdef DEBUG
1149     ssnprintf(view\->tmp_prompt_str, MAXLEN \- 1,
1150               "%s|%c%s|Pos %zu\-%zu|(%zd) %zu %zu", view\->file_name, *search_cmd,
1151               regex_pattern, view\->page_top_pos, view\->page_bot_pos,
1152               view\->file_size, view\->srch_beg_pos, view\->srch_curr_pos);
1153 #else
1154     if (view\->last_match_x > view\->maxcol)
1155         ssnprintf(view\->tmp_prompt_str, MAXLEN \- 1,
1156                   "%s|%c%s|Match Cols %d\-%d of %d\-%d|(%zd%%)", view\->file_name,
1157                   *search_cmd, regex_pattern, view\->first_match_x,
1158                   view\->last_match_x, view\->pmincol, view\->smaxcol \- view\->begx,
1159                   (view\->page_bot_pos * 100 / view\->file_size));
1160     else
1161         ssnprintf(view\->tmp_prompt_str, MAXLEN \- 1,
1162                   "%s|%c%s|Pos %zu\-%zu|(%zd%%)", view\->file_name, *search_cmd,
1163                   regex_pattern, view\->page_top_pos, view\->page_bot_pos,
1164                   (view\->page_bot_pos * 100 / view\->file_size));
1165 #endif
1166     regfree(&compiled_regex);
1167     return true;
1168 }
.PP
.fi

.PP
References \fBcp_norm\fP, \fBdisplay_line()\fP, \fBfmt_line()\fP, \fBget_next_line()\fP, \fBget_prev_line()\fP, \fBMAXLEN\fP, \fBPerror()\fP, \fBssnprintf()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "int view_cmd_processor (Init * init)"

.PP
Main Command Processing Loop for View\&. < Ctrl('R') or KEY_RESIZE - Handle terminal resize events

.PP
< KEY_ALTHOME - horizontal scroll to the first column

.PP
< KEY_ALTEND horizontal scroll to the last column

.PP
< 'h', Ctrl('H'), KEY_LEFT, KEY_BACKSPACE - Horizontal scroll left by two thirds of the page width

.PP
< 'l', 'L', KEY_RIGHT - Horizontal scroll right by two thirds of the page width

.PP
'k', 'K', KEY_UP, Ctrl('K') - Scroll up one line

.PP
'j', 'J', KEY_DOWN, KEY_ENTER, SPACE - scroll down one line

.PP
'b', 'B', Ctrl('B'), KEY_PPAGE - Scroll up one page

.PP
'f', 'F', Ctrl('F'), KEY_NPAGE - scroll down one page

.PP
'g', KEY_HOME - Go to the beginning of the document

.PP
KEY_LL - Go to the end of the document

.PP
'!', Execute Shell Command from within C-Menu View

.PP
'+', Set Startup Command

.PP
'-', Change View Settings

.PP
'c' - Clear Screen at End of File

.PP
'i' - Ignore Case in Search

.PP
'p' - Set Prompt Type

.PP
'l' - Long Prompt

.PP
'n' - No Prompt

.PP
's' - Squeeze Multiple Blank Lines

.PP
't' - Set Tab Stop Columns

.PP
KEY_F(1), 'H' - Display Help

.PP
Pedantic reassignment of view pointer as the init->view pointer was was reassigned during view_display_help

.PP
':' - Set a Prompt String

.PP
'n' - Repeat Previous Search

.PP
'/' or '?' - Search Forward fromk top of page

.PP
'?' - Search Backward

.PP
'o' or 'O' - Open a File

.PP
'g' or 'G' - Go to the End of the Document

.PP
'H' or KEY_F(1) - Display Help Information

.PP
Pedantic reassignment of view pointer as the init->view pointer was was reassigned during view_display_help

.PP
'm' - Set a Mark at the Current Position

.PP
'M' - Go to a Mark

.PP
'N' - Close Current File and Open Next File

.PP
'p' or '' - Go to a Percent of the File

.PP
Ctrl('Z') - Send File to Print Queue with Notation

.PP
'P' or KEY_CATAB or KEY_PRINT - Print Current File

.PP
'P' or KEY_F(9) or ESC - Close Current File and Open Next

.PP
'q' or 'Q' or KEY_F(9) or ESC - Quit the Application

.PP
'v' - Open Current File in Editor

.PP
'w' - Write the current buffer to file

.PP
'V' - Display Version Information
.PP
Definition at line \fB121\fP of file \fBview_engine\&.c\fP\&.
.nf
121                                    {
122     char tmp_str[MAXLEN];
123     int tfd;
124     int c;
125     int max_n;
126     int shift = 0;
127     int search_cmd = 0;
128     int prev_search_cmd = 0;
129     int rc, i;
130     int n = 0;
131     ssize_t bytes_written;
132     char *e;
133     char shell_cmd_spec[MAXLEN];
134     struct timespec start, end;
135     double elapsed = 0;
136     bool f_clock_started = false;
137     off_t n_cmd = 0L;
138     off_t prev_file_pos;
139     view = init\->view;
140     view\->f_timer = false;
141     view\->cmd[0] = '\\0';
142     while (1) {
143         c = view\->next_cmd_char;
144         view\->next_cmd_char = 0;
145         if (!c) {
146             if (view\->f_redisplay_page)
147                 redisplay_page(view);
148             view\->f_redisplay_page = false;
149             if (view\->f_timer && f_clock_started) {
150                 clock_gettime(CLOCK_MONOTONIC, &end);
151                 elapsed = (end\&.tv_sec \- start\&.tv_sec) +
152                           (end\&.tv_nsec \- start\&.tv_nsec) / 1e9;
153                 f_clock_started = false;
154             }
155 
156             if (view\->tmp_prompt_str[0] != '\\0') {
157                 cmd_line_prompt(view, view\->tmp_prompt_str);
158                 view\->tmp_prompt_str[0] = '\\0';
159             } else {
160                 build_prompt(view, view\->prompt_type, view\->prompt_str,
161                              elapsed);
162                 if (view\->prompt_str[0] == '\\0')
163                     cmd_line_prompt(view, ">");
164                 else
165                     cmd_line_prompt(view, view\->prompt_str);
166             }
167             rc =
168                 prefresh(view\->win, view\->pminrow, view\->pmincol, view\->sminrow,
169                          view\->smincol, view\->smaxrow, view\->smaxcol);
170             if (rc == ERR)
171                 Perror("Error refreshing pad");
172             c = get_cmd_char(view, &n_cmd);
173             if (view\->f_timer) {
174                 clock_gettime(CLOCK_MONOTONIC, &start);
175                 f_clock_started = true;
176             }
177             if (c >= '0' && c <= '9') {
178                 tmp_str[0] = (char)c;
179                 tmp_str[1] = '\\0';
180                 c = get_cmd_arg(view, tmp_str);
181             }
182         }
183         switch (c) {
184         case Ctrl('R'): 
186         case KEY_RESIZE:
187             resize_page(init);
188             break;
189         case KEY_ALTHOME: 
191             view\->pmincol = 0;
192             break;
193         case KEY_ALTEND: 
195             if (view\->maxcol > view\->cols)
196                 view\->pmincol = view\->maxcol \- view\->cols;
197             else
198                 view\->pmincol = 0;
199             break;
200         case 'h': 
202         case Ctrl('H'):
203         case KEY_LEFT:
204         case KEY_BACKSPACE:
205             if (n_cmd <= 0)
206                 n_cmd = 1;
207             shift = (view\->cols / 3) * 2;
208             max_n = view\->pmincol / shift;
209             n = (int)n_cmd;
210             if (n > max_n)
211                 n = max_n;
212             shift *= n;
213             if (view\->pmincol \- shift < 0)
214                 view\->pmincol = 0;
215             else
216                 view\->pmincol \-= shift;
217             view\->f_redisplay_page = true;
218             break;
219         case 'l': 
221         case 'L':
222         case KEY_RIGHT:
223             if (n_cmd <= 0)
224                 n_cmd = 1;
225             shift = (view\->cols / 3) * 2;
226             max_n = (view\->maxcol \- view\->pmincol) / shift;
227             n = (int)n_cmd;
228             if (n > max_n)
229                 n = max_n;
230             shift *= n;
231             if (view\->pmincol + shift <= view\->maxcol)
232                 view\->pmincol += shift;
233             else
234                 view\->pmincol = (view\->maxcol \- shift) > 0
235                                     ? (view\->maxcol \- view\->cols)
236                                     : 0;
237             view\->f_redisplay_page = true;
238             break;
239         case 'k': 
240         case 'K':
241         case KEY_UP:
242         case Ctrl('K'):
243             if (n_cmd <= 0)
244                 n_cmd = 1;
245             scroll_up_n_lines(view, n_cmd);
246             break;
248         case 'j':
249         case 'J':
250         case '\\n':
251         case ' ':
252         case KEY_DOWN:
253         case KEY_ENTER:
254             if (n_cmd <= 0)
255                 n_cmd = 1;
256             for (i = 0; i < n_cmd; i++) {
257                 scroll_down_n_lines(view, n_cmd);
258             }
259             break;
261         case KEY_PPAGE:
262         case 'b':
263         case 'B':
264         case Ctrl('B'):
265             scroll_up_n_lines(view, view\->scroll_lines);
266             break;
268         case 'f':
269         case 'F':
270         case KEY_NPAGE:
271         case Ctrl('F'):
272             next_page(view);
273             break;
275         case 'g':
276         case KEY_HOME:
277             view\->pmincol = 0;
278             go_to_line(view, 0L);
279             break;
281         case KEY_LL:
282             go_to_eof(view);
283             break;
285         case '!':
286             if (view\->f_displaying_help)
287                 break;
288             if (get_cmd_arg(view, "!") == 0) {
289                 if (!view\->f_is_pipe) {
290                     view\->prev_file_pos = view\->page_top_pos;
291                     view\->next_file_spec_ptr = view\->file_spec_ptr;
292                     str_subc(shell_cmd_spec, view\->cmd_arg, '%',
293                              view\->cur_file_str, MAXLEN \- 1);
294                     munmap(view\->buf, view\->file_size);
295                 } else
296                     strnz__cpy(shell_cmd_spec, view\->cmd_arg, MAXLEN \- 1);
297                 full_screen_shell(shell_cmd_spec);
298                 if (!view\->f_is_pipe) {
299                     view\->next_file_spec_ptr = view\->cur_file_str;
300                     return 0;
301                 }
302             }
303             break;
305         case '+':
306             if (get_cmd_arg(view, "Startup Command:") == 0)
307                 strnz__cpy(view\->cmd, view\->cmd_arg, MAXLEN \- 1);
308             break;
310         case '\-':
311             if (view\->f_displaying_help)
312                 break;
313             cmd_line_prompt(view, "(c, i, p, s, t, or h)\->");
314             c = get_cmd_char(view, &n_cmd);
315             c = tolower(c);
316             if (c >= 'A' && c <= 'Z')
317                 c += ' ';
318             switch (c) {
320             case 'c':
321                 cmd_line_prompt(view, "Clear Screen at End (Y or N)\->");
322                 if ((c = get_cmd_char(view, &n_cmd)) == 'y' || c == 'Y')
323                     view\->f_at_end_clear = true;
324                 else if (c == 'n' || c == 'N')
325                     view\->f_at_end_clear = false;
326                 break;
328             case 'i':
329                 cmd_line_prompt(view, "Ignore Case in search (Y or N)\->");
330                 if ((c = get_cmd_char(view, &n_cmd)) == 'y' || c == 'Y')
331                     view\->f_ignore_case = true;
332                 else if (c == 'n' || c == 'N')
333                     view\->f_ignore_case = false;
334                 break;
336             case 'p':
337                 cmd_line_prompt(view, "(Short Long or No prompt)\->");
338                 c = tolower(get_cmd_char(view, &n_cmd));
339                 switch (c) {
340                 case 's':
341                     view\->prompt_type = PT_SHORT;
342                     break;
344                 case 'l':
345                     view\->prompt_type = PT_LONG;
346                     break;
348                 case 'n':
349                     view\->prompt_type = PT_NONE;
350                     break;
351                 default:
352                     break;
353                 }
354                 break;
356             case 's':
357                 cmd_line_prompt(
358                     view, "view\->f_squeeze Multiple Blank lines (Y or N)\->");
359                 if ((c = get_cmd_char(view, &n_cmd)) == 'y' || c == 'Y')
360                     view\->f_squeeze = true;
361                 else if (c == 'n' || c == 'N')
362                     view\->f_squeeze = false;
363                 break;
365             case 't':
366                 sprintf(tmp_str,
367                         "Tabstop Colums Currently %d:", view\->tab_stop);
368                 i = 0;
369                 if (get_cmd_arg(view, tmp_str) == 0)
370                     i = atoi(view\->cmd_arg);
371                 if (i >= 1 && i <= 12) {
372                     view\->tab_stop = i;
373                     view\->f_redisplay_page = true;
374                 } else
375                     Perror("Tab stops not changed");
376                 break;
378             case 'H':
379             case KEY_F(1):
380                 if (!view\->f_displaying_help) {
381                     view_display_help(init);
385                     view = init\->view;
386                 }
387                 view\->next_cmd_char = '\-';
388                 break;
389             default:
390                 break;
391             }
392             break;
394         case ':':
395             view\->next_cmd_char = get_cmd_arg(view, ":");
396             break;
398         case 'n':
399             if (prev_search_cmd == 0 || view\->f_search_complete) {
400                 Perror("No previous search or search complete");
401                 break;
402             }
403             if (prev_search_cmd == '/') {
404                 view\->cury = 0;
405                 view\->srch_curr_pos = view\->page_bot_pos;
406             } else {
407                 view\->cury = view\->scroll_lines + 1;
408                 view\->srch_curr_pos = view\->page_top_pos;
409             }
410             search(view, &prev_search_cmd, prev_regex_pattern);
411             break;
413         case '/':
414             view\->f_search_complete = false;
415             strnz__cpy(tmp_str, "(forward)\->", MAXLEN \- 1);
416             search_cmd = c;
417             c = get_cmd_arg(view, tmp_str);
418             if (c == '\\n') {
419                 view\->cury = 0;
420                 view\->f_first_iter = true;
421                 view\->srch_beg_pos = view\->page_top_pos;
422                 view\->srch_curr_pos = view\->page_top_pos;
423                 search(view, &search_cmd, view\->cmd_arg);
424                 prev_search_cmd = search_cmd;
425                 strnz__cpy(prev_regex_pattern, view\->cmd_arg, MAXLEN \- 1);
426             }
427             break;
429         case '?':
430             view\->f_search_complete = false;
431             strnz__cpy(tmp_str, "(backward)\->", MAXLEN \- 1);
432             search_cmd = c;
433             c = get_cmd_arg(view, tmp_str);
434             if (c == '\\n') {
435                 view\->cury = view\->scroll_lines;
436                 view\->f_first_iter = true;
437                 view\->srch_beg_pos = view\->page_bot_pos;
438                 view\->srch_curr_pos = view\->page_bot_pos;
439                 search(view, &search_cmd, view\->cmd_arg);
440                 prev_search_cmd = search_cmd;
441                 strnz__cpy(prev_regex_pattern, view\->cmd_arg, MAXLEN \- 1);
442             }
443             break;
445         case 'o':
446         case 'O':
447         case 'e':
448         case 'E':
449             if (get_cmd_arg(view, "File name:") == 0) {
450                 strtok(view\->cmd_arg, " ");
451                 view\->next_file_spec_ptr = strdup(view\->cmd_arg);
452                 view\->f_redisplay_page = true;
453                 return 0;
454             }
455             break;
457         case 'G':
458         case KEY_END:
459             if (n_cmd <= 0)
460                 go_to_eof(view);
461             else
462                 go_to_line(view, n_cmd);
463             break;
465         case 'H':
466         case KEY_F(1):
467             if (!view\->f_displaying_help) {
468                 view_display_help(init);
472                 view = init\->view;
473                 view = init\->view;
474             }
475             break;
477         case 'm':
478             cmd_line_prompt(view, "Mark label (A\-Z)\->");
479             c = get_cmd_char(view, &n_cmd);
480             if (c == '@' || c == KEY_F(9) || c == '\\033')
481                 if (c >= 'A' && c <= 'Z')
482                     c += ' ';
483             if (c < 'a' || c > 'z')
484                 Perror("Not (a\-z)");
485             else
486                 view\->mark_tbl[c \- 'a'] = view\->page_top_pos;
487             break;
489         case 'M':
490             cmd_line_prompt(view, "Goto mark (A\-Z)\->");
491             c = get_cmd_char(view, &n_cmd);
492             if (c == '@' || c == KEY_F(9) || c == '\\033')
493                 break;
494             if (c >= 'A' && c <= 'Z')
495                 c += ' ';
496             if (c < 'a' || c > 'z')
497                 Perror("Not (A\-Z)");
498             else
499                 go_to_mark(view, c);
500             break;
502         case 'N':
503             if (n_cmd <= 0)
504                 n_cmd = 1;
505             if (view\->curr_argc + n_cmd >= view\->argc) {
506                 Perror("no more files");
507                 view\->curr_argc = view\->argc \- 1;
508             } else {
509                 view\->curr_argc++;
510                 if (view\->curr_argc < view\->argc)
511                     view\->next_file_spec_ptr = view\->argv[view\->curr_argc];
512                 return 0;
513             }
514             break;
516         case 'p':
517         case '%':
518             if (n_cmd < 0)
519                 go_to_line(view, 1);
520             if (n_cmd >= 100)
521                 go_to_eof(view);
522             else
523                 go_to_percent(view, n_cmd);
524             break;
526         case Ctrl('Z'):
527             get_cmd_arg(view, "Enter Notation:");
528             strnz__cpy(tmp_str, "/tmp/view\-XXXXXX", MAXLEN \- 1);
529             tfd = mkstemp(tmp_str);
530             strnz__cpy(view\->tmp_file_name_ptr, tmp_str, MAXLEN \- 1);
531             if (tfd == \-1) {
532                 Perror("Unable to create temporary file");
533                 break;
534             }
535             strnz__cpy(shell_cmd_spec, "echo ", MAXLEN \- 5);
536             strnz__cat(shell_cmd_spec, view\->cmd_arg, MAXLEN \- 5);
537             strnz__cat(shell_cmd_spec, view\->tmp_file_name_ptr, MAXLEN \- 5);
538             shell(shell_cmd_spec);
539             strnz__cpy(shell_cmd_spec, "cat ", MAXLEN \- 5);
540             strnz__cat(shell_cmd_spec, view\->cmd_arg, MAXLEN \- 5);
541             strnz__cat(shell_cmd_spec, ">>", MAXLEN \- 5);
542             strnz__cat(shell_cmd_spec, view\->tmp_file_name_ptr, MAXLEN \- 5);
543             shell(shell_cmd_spec);
544             lp(view\->cur_file_str);
545             prefresh(view\->win, view\->pminrow, view\->pmincol, view\->sminrow,
546                      view\->smincol, view\->smaxrow, view\->smaxcol);
547             shell(shell_cmd_spec);
548             ssnprintf(shell_cmd_spec, (size_t)(MAXLEN \- 5), "rm %s",
549                       view\->tmp_file_name_ptr);
550             strnz__cpy(shell_cmd_spec, "rm ", MAXLEN \- 5);
551             strnz__cat(shell_cmd_spec, view\->tmp_file_name_ptr, MAXLEN \- 5);
552             shell(shell_cmd_spec);
553             restore_wins();
554             view\->f_redisplay_page = true;
555             unlink(tmp_str);
556             break;
558         case Ctrl('P'):
559         case KEY_CATAB:
560         case KEY_PRINT:
561             lp(view\->cur_file_str);
562             view\->f_redisplay_page = true;
563             break;
565         case 'P':
566             if (n_cmd <= 0)
567                 n_cmd = 1;
568             if (view\->curr_argc \- n_cmd < 0) {
569                 Perror("No previous file");
570                 view\->curr_argc = 0;
571             } else {
572                 view\->curr_argc\-\-;
573                 if (view\->curr_argc >= 0)
574                     view\->next_file_spec_ptr = view\->argv[view\->curr_argc];
575                 return 0;
576             }
577             break;
579         case 'q':
580         case 'Q':
581         case KEY_F(9):
582         case '\\033':
583             view\->curr_argc = view\->argc;
584             view\->next_file_spec_ptr = nullptr;
585             return 0;
587         case 'v':
588             if (init\->editor[0] == 0) {
589                 e = getenv("DEFAULTEDITOR");
590                 if (e == nullptr || *e == '\\0')
591                     strnz__cpy(init\->editor, DEFAULTEDITOR, MAXLEN);
592                 else
593                     strnz__cpy(init\->editor, e, MAXLEN);
594             }
595             strnz__cpy(em0,
596                        "View doesn't support editing current buffer directly",
597                        MAXLEN \- 1);
598             strnz__cpy(em1, "Would you like to write the buffer to a file?",
599                        MAXLEN \- 1);
600             strnz__cpy(em2, "Enter Y for yes or any other key to cancel\&.",
601                        MAXLEN \- 1);
602             rc = display_error(em0, em1, em2, nullptr);
603             if (rc != 'y' && rc != 'Y')
604                 break;
605             if (!enter_file_spec(init, view\->out_spec)) {
606                 view\->f_redisplay_page = true;
607                 break;
608             }
609             prev_file_pos = view\->page_top_pos;
610             bytes_written = write_view_buffer(init, view\->f_strip_ansi);
611             if (bytes_written == 0) {
612                 ssnprintf(em0, MAXLEN \- 1, "%s, line: %d", __FILE__,
613                           __LINE__ \- 2);
614                 strnz__cpy(em1, "0 bytes written", MAXLEN \- 1);
615                 strerror_r(errno, em1, MAXLEN \- 1);
616                 display_error(em0, em1, nullptr, nullptr);
617                 break;
618             }
619             view\->next_file_spec_ptr = view\->in_spec;
620             strnz__cpy(shell_cmd_spec, init\->editor, MAXLEN \- 5);
621             strnz__cat(shell_cmd_spec, " ", MAXLEN \- 5);
622             strnz__cat(shell_cmd_spec, view\->in_spec, MAXLEN \- 5);
623             full_screen_shell(shell_cmd_spec);
624             view\->file_pos = view\->page_top_pos = view\->page_bot_pos =
625                 prev_file_pos;
626 
627             restore_wins();
628             view\->f_redisplay_page = true;
629             return 0;
631         case 'w':
632             if (!enter_file_spec(init, view\->out_spec)) {
633                 view\->f_redisplay_page = true;
634                 break;
635             }
636             prev_file_pos = view\->page_top_pos;
637             bytes_written = write_view_buffer(init, view\->f_strip_ansi);
638             cmd_line_prompt(view, tmp_str);
639             view\->f_redisplay_page = true;
640             break;
641         case CT_VIEW:
642             break;
644         case 'V':
645             ssnprintf(em0, MAXLEN \- 1, "C\-Menu Version: %s", CM_VERSION);
646             display_error(em0, em1, nullptr, nullptr);
647             break;
648         default:
649             break;
650         }
651         view\->cmd_arg[0] = '\\0';
652     }
653 }
.PP
.fi

.PP
References \fBbuild_prompt()\fP, \fBcmd_line_prompt()\fP, \fBCtrl\fP, \fBdisplay_error()\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBenter_file_spec()\fP, \fBfull_screen_shell()\fP, \fBget_cmd_arg()\fP, \fBget_cmd_char()\fP, \fBgo_to_eof()\fP, \fBgo_to_line()\fP, \fBgo_to_mark()\fP, \fBgo_to_percent()\fP, \fBinit\fP, \fBlp()\fP, \fBMAXLEN\fP, \fBnext_page()\fP, \fBPerror()\fP, \fBprev_regex_pattern\fP, \fBredisplay_page()\fP, \fBresize_page()\fP, \fBrestore_wins()\fP, \fBscroll_down_n_lines()\fP, \fBscroll_up_n_lines()\fP, \fBsearch()\fP, \fBshell()\fP, \fBssnprintf()\fP, \fBstr_subc()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, \fBview\fP, \fBview_display_help()\fP, and \fBwrite_view_buffer()\fP\&.
.PP
Referenced by \fBview_file()\fP\&.
.SS "void view_display_help (Init * init)"

.PP
Display View Help File\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP is the current initialization data structure\&. 
.RE
.PP
\fBNote\fP
.RS 4
The current View context is set aside by assigning the view structure to "view_save" while the help file is displayed using a new, separate view structure\&. 

.PP
The help file is specified by the VIEW_HELP_FILE macro can be set to a default help file path or overridden by the user through an environment variable\&. 

.PP
After the help file is closed, the original view is restored and the page is redisplayed\&. 

.PP
It may be necessary to reassign view after calling this function because the init->view pointer is temporarily set to nullptr during the help file display, and the original view is restored afterward\&. 

.PP
The default screen size for help can be set in the code below\&. If set to 0, mview will determine reasonable maximal size based on the terminal dimensions\&. 

.PP
The help file may contain Unicode characters and ANSI escape sequences for formatting, which will be properly handled and displayed by mview\&. 
.RE
.PP

.PP
Definition at line \fB1778\fP of file \fBview_engine\&.c\fP\&.
.nf
1778                                    {
1779     char tmp_str[MAXLEN];
1780     int eargc;
1781     char *eargv[MAXARGS];
1782     View *view_save = init\->view;
1783     init\->view = nullptr;
1784     zero_opt_args(init);
1785     eargv[0] = strdup("mview");
1786     strnz__cpy(tmp_str, VIEW_HELP_FILE, MAXLEN \- 1);
1787     expand_tilde(tmp_str, MAXLEN \- 1);
1788     eargv[1] = strdup(tmp_str);
1789     eargv[2] = nullptr;
1790     eargc = 2;
1791     parse_opt_args(init, eargc, eargv);
1792     init\->lines = 48;
1793     init\->cols = 60;
1794     init\->begy = 0;
1795     init\->begx = 0;
1796     strnz__cpy(init\->title, "View Help", MAXLEN \- 1);
1797     mview(init, eargc, eargv);
1798     init\->view = view_save;
1799     init\->view\->f_redisplay_page = true;
1800 }
.PP
.fi

.PP
References \fBeargc\fP, \fBeargv\fP, \fBexpand_tilde()\fP, \fBinit\fP, \fBMAXLEN\fP, \fBmview()\fP, \fBparse_opt_args()\fP, \fBstrnz__cpy()\fP, \fBtmp_str\fP, and \fBzero_opt_args()\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SS "int view_file (Init * init)"

.PP
Start view\&. 
.PP
Definition at line \fB84\fP of file \fBview_engine\&.c\fP\&.
.nf
84                           {
85     view = init\->view;
86     if (view\->argc < 1) {
87         view\->curr_argc = \-1;
88         view\->argc = 0;
89         view\->next_file_spec_ptr = "\-";
90     } else
91         view\->next_file_spec_ptr = view\->argv[0];
92     while (view\->curr_argc < view\->argc) {
93         if (view\->next_file_spec_ptr == nullptr ||
94             *view\->next_file_spec_ptr == '\\0') {
95             break;
96         }
97         view\->file_spec_ptr = view\->next_file_spec_ptr;
98         view\->next_file_spec_ptr = nullptr;
99         if (view_init_input(view, view\->file_spec_ptr)) {
100             if (view\->buf) {
101                 view\->f_eod = 0;
102                 view\->f_bod = 0;
103                 view\->maxcol = 0;
104                 view\->page_top_pos = 0;
105                 view\->page_bot_pos = 0;
106                 view\->file_pos = 0;
107                 next_page(view);
108                 view_cmd_processor(init);
109                 munmap(view\->buf, view\->file_size);
110             }
111         } else {
112             view\->curr_argc++;
113             if (view\->curr_argc < view\->argc) {
114                 view\->next_file_spec_ptr = view\->argv[view\->curr_argc];
115             }
116         }
117     }
118     return 0;
119 }
.PP
.fi

.PP
References \fBinit\fP, \fBnext_page()\fP, \fBview\fP, \fBview_cmd_processor()\fP, and \fBview_init_input()\fP\&.
.PP
Referenced by \fBmain()\fP, and \fBmview()\fP\&.
.SS "int write_view_buffer (Init * init, bool f_strip_ansi)"

.PP
Write buffer contents to files\&. 
.PP
\fBParameters\fP
.RS 4
\fI\fBinit\fP\fP data structure 
.br
\fIf_strip_ansi\fP strip ANSI escape sequences 
.RE
.PP
write the buffer
.PP
Definition at line \fB847\fP of file \fBview_engine\&.c\fP\&.
.nf
847                                                      {
848     ssize_t bytes_written = 0;
849     off_t pos;
850     View *view = init\->view;
851     int rc;
852     size_t l;
853     char tmp_line_s[PAD_COLS];
854 
855     if (!f_strip_ansi) {
856         strnz__cpy(em0, "Would you like to strip ansi escape sequences?",
857                    MAXLEN \- 1);
858         strnz__cpy(em1, "Enter Y for yes or any other key to cancel\&.",
859                    MAXLEN \- 1);
860         rc = display_error(em0, em1, nullptr, nullptr);
861         if (rc == 'y' || rc == 'Y')
862             f_strip_ansi = true;
863         else
864             f_strip_ansi = false;
865     }
867     pos = 0;
868     view\->out_fd = open(view\->out_spec, O_CREAT | O_TRUNC | O_WRONLY, 0644);
869     if (view\->out_fd == \-1) {
870         ssnprintf(em0, MAXLEN \- 1, "%s, line: %d", __FILE__, __LINE__ \- 2);
871         strnz__cpy(em1, "fwrite ", MAXLEN \- 1);
872         strnz__cat(em1, view\->out_spec, MAXLEN \- 1);
873         strerror_r(errno, em2, MAXLEN \- 1);
874         display_error(em0, em1, em2, nullptr);
875         return (false);
876     }
877     bytes_written = 0;
878     while (!view\->f_eod) {
879         pos = get_next_line(view, pos);
880         if (f_strip_ansi)
881             strip_ansi(tmp_line_s, view\->line_in_s);
882         else
883             strnz__cpy(tmp_line_s, view\->line_in_s, MAXLEN \- 1);
884         l = strnlf(tmp_line_s, PAD_COLS \- 1);
885         bytes_written += write(view\->out_fd, tmp_line_s, l);
886     }
887     close(view\->out_fd);
888     strnz__cpy(view\->in_spec, view\->out_spec, MAXLEN \- 1);
889     return bytes_written;
890 }
.PP
.fi

.PP
References \fBdisplay_error()\fP, \fBem0\fP, \fBem1\fP, \fBem2\fP, \fBget_next_line()\fP, \fBinit\fP, \fBMAXLEN\fP, \fBssnprintf()\fP, \fBstrip_ansi()\fP, \fBstrnlf()\fP, \fBstrnz__cat()\fP, \fBstrnz__cpy()\fP, and \fBview\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "FILE* dbgfp"

.PP
Definition at line \fB48\fP of file \fBview_engine\&.c\fP\&.
.SS "char err_msg[\fBMAXLEN\fP]"

.PP
Definition at line \fB82\fP of file \fBview_engine\&.c\fP\&.
.PP
Referenced by \fBABEND()\fP\&.
.SS "char prev_regex_pattern[\fBMAXLEN\fP]"

.PP
Definition at line \fB47\fP of file \fBview_engine\&.c\fP\&.
.PP
Referenced by \fBview_cmd_processor()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
