.TH "WCStr" 3 "Version v0.2.9" "C-Menu" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WCStr \- wide character string object with a pointer to the wide character string and its allocated length  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <src/include/cm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "wchar_t * \fBs\fP"
.br
.ti -1c
.RI "size_t \fBl\fP"
.br
.RI "allocated length "
.in -1c
.SH "Detailed Description"
.PP 
wide character string object with a pointer to the wide character string and its allocated length 


.PP
\fBNote\fP
.RS 4
The \fBWCStr\fP structure represents a wide character string with a pointer to the wide character string and its allocated length\&. 
.RE
.PP

.PP
Definition at line \fB479\fP of file \fBcm\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "size_t WCStr::l"

.PP
allocated length 
.PP
Definition at line \fB481\fP of file \fBcm\&.h\fP\&.
.SS "wchar_t* WCStr::s"
pointer to the wide character string 
.PP
Definition at line \fB480\fP of file \fBcm\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Menu from the source code\&.
