C-Menu: src/whence.c File Reference
whence.c File Reference
Find the full path of a file in the directories specified by the.
#include <cm.h>
#include <fcntl.h>
#include <getopt.h>
#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
Macros
#define TRUE 1
#define FALSE 0
#define FAIL -1
Functions
void whence_usage ()
Display usage information for the whence utility.
void whence (char *file_spec_p)
Find the full path of a file in the directories specified by the PATH environment variable.
int next_path (char *dp, char **sp)
Extract the next directory path from the PATH string.
int file_spec_parts (char *file_spec, char *file_path, char *file_name)
Split a file specification into directory and file name components.
void ABEND (char *pgmid, int rc, char *err_msg)
Exit the program with an error message.
void normalend ()
Exit the program successfully.
int main (int argc, char **argv)
Main function for whence utility.
Variables
bool f_all
bool f_display_help
bool f_verbose
char * path_p
char path_s [MAXLEN]
char * file_name [MAXLEN+1]
Detailed Description
Find the full path of a file in the directories specified by the.
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file whence.c.
Macro Definition Documentation
FAIL
#define FAIL -1
Definition at line 25 of file whence.c.
Referenced by main().
FALSE
#define FALSE 0
Definition at line 24 of file whence.c.
TRUE
#define TRUE 1
Definition at line 23 of file whence.c.
Function Documentation
ABEND()
void ABEND (char * pgmid, int rc, char * err_msg)
Exit the program with an error message.
Parameters
pgmid The name of the program
rc The return code to exit with
err_msg The error message to display
Note
This function is called to exit the program with an error status. It prints the program name, return code, and error message to the standard error stream, and then exits with the specified return code.
Definition at line 233 of file whence.c.
{
    fprintf(stderr, "%s; error %d; %s\n", pgmid, rc, err_msg);
    exit(EXIT_FAILURE);
}
References err_msg.
Referenced by main().
file_spec_parts()
int file_spec_parts (char * file_spec, char * file_path, char * file_name)
Split a file specification into directory and file name components.
Parameters
file_spec The full file specification to split
file_path A buffer to store the extracted directory path
file_name A buffer to store the extracted file name
Returns
0 on success
Note
This function takes a file specification, checks if it is a directory, and if so, it sets the file path accordingly. If the file specification is empty, it defaults to the current directory. Otherwise, it splits the file specification into the directory and file name components based on the last occurrence of a slash ('/').
Definition at line 172 of file whence.c.
{
    int i, last_slash;
    char tmp_file_spec[PATH_MAX];
    int file_spec_l;
    struct stat stat_struct;
    if (stat(file_spec, &stat_struct) != -1)
        if ((stat_struct.st_mode & S_IFMT) == S_IFDIR) {
            if (file_spec[strlen(file_path)] != '/')
                strnz__cat(file_spec, "/", MAXLEN - 1);
            strnz__cpy(file_path, file_spec, MAXLEN - 1);
            file_name[0] = '\0';
            return (0);
        }
    if (strlen(file_spec) == 0) {
        strnz__cpy(file_spec, "./", MAXLEN - 1);
        file_name[0] = '\0';
        return (0);
    }
    strnz__cpy(tmp_file_spec, file_spec, MAXLEN - 1);
    last_slash = -1;
    file_spec_l = strlen(tmp_file_spec);
    if (file_spec_l > 0) {
        i = 0;
        while (i < file_spec_l && tmp_file_spec[i] != '\0') {
            if (tmp_file_spec[i] == '/') {
                last_slash = i;
                break;
            }
            i++;
        }
    }
    if (last_slash < 0) {
        strnz__cpy(file_path, "./", MAXLEN - 1);
        if (strcmp(file_spec, ".") == 0)
            file_name[0] = '\0';
        else
            strnz__cpy(file_name, tmp_file_spec, MAXLEN - 1);
        strnz__cpy(file_spec, file_path, MAXLEN - 1);
        strnz__cat(file_spec, file_name, MAXLEN - 1);
    } else {
        tmp_file_spec[last_slash] = '\0';
        strnz__cpy(file_path, tmp_file_spec, MAXLEN - 1);
        strnz__cat(file_path, "/", MAXLEN - 1);
        if (last_slash < file_spec_l)
            last_slash++;
        strnz__cpy(file_name, tmp_file_spec + last_slash, MAXLEN - 1);
    }
    return (0);
}
References file_name, MAXLEN, strnz__cat(), and strnz__cpy().
Referenced by whence().
main()
int main (int argc, char ** argv)
Main function for whence utility.
Parameters
argc Argument count
argv Argument vector
Returns
Exit status options include: -a: Show all matches (default is to show only the first match) -h: Display help message -v: Verbose mode (implies -a)
Note
This function processes command-line arguments, retrieves the PATH environment variable, and calls the whence function for each specified file.
Definition at line 49 of file whence.c.
{
    int opt;
    if (argc < 2)
        whence_usage();
    while ((opt = getopt(argc, argv, "ahv")) != -1) {
        switch (opt) {
        case 'a':
            f_all = TRUE;
            break;
        case 'h':
            f_display_help = TRUE;
            break;
        case 'v':
            f_verbose = TRUE;
            break;
        default:
            ABEND(argv[0], FAIL, "unrecognized option");
        }
    }
    if (f_display_help) {
        whence_usage();
        normalend();
    }
    path_p = getenv("PATH");
    if (path_p == nullptr)
        ABEND(argv[0], FAIL, "PATH environment variable not set");
    if (f_verbose)
        printf("%s\n", path_p);
    while (optind < argc) {
        whence(argv[optind++]);
    }
    normalend();
}
References ABEND(), f_all, f_display_help, f_verbose, FAIL, normalend(), path_p, TRUE, whence(), and whence_usage().
next_path()
int next_path (char * dp, char ** sp)
Extract the next directory path from the PATH string.
Parameters
dp A buffer to store the extracted directory path
sp A pointer to the current position in the PATH string
Returns
The length of the extracted directory path
Note
This function takes a buffer and a pointer to the current position in the PATH string, and extracts the next directory path. If the next character in the PATH string is a colon, it treats it as an empty path and uses the current working directory. Otherwise, it copies characters until it reaches a colon or the end of the string, and returns the length of the extracted path.
Definition at line 143 of file whence.c.
{
    int dl;
    if (**sp == ':') {
        (*sp)++;
        getcwd(dp, PATH_MAX);
        return (strlen(dp));
    } else {
        dl = 0;
        while (**sp != '\0' && **sp != '\n' && **sp != '\r' && **sp != ':') {
            *dp++ = *(*sp)++;
            dl++;
        }
        *dp = '\0';
        if (**sp == ':' && *++(*sp) == '\0')
            (*sp)--;
        return (dl);
    }
}
Referenced by whence().
normalend()
void normalend ()
Exit the program successfully.
Note
This function is called to exit the program with a success status. It simply calls the exit function with EXIT_SUCCESS.
Definition at line 225 of file whence.c.
{ exit(EXIT_SUCCESS); }
Referenced by main().
whence()
void whence (char * file_spec_p)
Find the full path of a file in the directories specified by the PATH environment variable.
Parameters
file_spec_p The file specification to search for
Note
This function takes a file specification, extracts the directory and file name components, and searches through the directories specified in the PATH environment variable to find matches. It prints the full path of each match found, and if verbose mode is enabled, it also indicates whether each attempted path was found or not.
Definition at line 101 of file whence.c.
{
    char file_spec[PATH_MAX];
    char file_dir[PATH_MAX];
    char file_name[PATH_MAX];
    char try_spec[PATH_MAX];
    char try_dir[PATH_MAX];
    int path_l;
    struct stat stat_struct;
    strnz__cpy(file_spec, file_spec_p, MAXLEN - 1);
    strnz__cpy(path_s, path_p, MAXLEN - 1);
    file_spec_parts(file_spec, file_dir, file_name);
    path_p = path_s;
    path_l = next_path(try_dir, &path_p);
    while (path_l != 0) {
        strnz__cpy(try_spec, try_dir, MAXLEN - 1);
        if (try_spec[path_l] != '/')
            strnz__cat(try_spec, "/", MAXLEN - 1);
        strnz__cat(try_spec, file_name, MAXLEN - 1);
        if (f_verbose) {
            if (stat(try_spec, &stat_struct) == -1)
                printf("-      %s\n", try_spec);
            else
                printf("found  %s\n", try_spec);
        } else if (stat(try_spec, &stat_struct) == 0) {
            printf("%s\n", try_spec);
            if (!f_all)
                return;
        }
        path_l = next_path(try_dir, &path_p);
    }
}
References f_all, f_verbose, file_name, file_spec_parts(), MAXLEN, next_path(), path_p, path_s, strnz__cat(), and strnz__cpy().
Referenced by main().
whence_usage()
void whence_usage ()
Display usage information for the whence utility.
Note
This function prints the usage instructions and available options for the whence utility to the standard error stream.
Definition at line 87 of file whence.c.
                    {
    fprintf(stderr, "whence_usage: whence [options] file_name\n");
    fprintf(stderr, "       -a show all matches\n");
    fprintf(stderr, "       -h help\n");
    fprintf(stderr, "       -v verbose (implies -a)\n");
}
Referenced by main().
Variable Documentation
f_all
bool f_all
Definition at line 27 of file whence.c.
Referenced by main(), and whence().
f_display_help
bool f_display_help
Definition at line 27 of file whence.c.
Referenced by main().
f_verbose
bool f_verbose
Definition at line 27 of file whence.c.
file_name
char* file_name[MAXLEN+1]
Definition at line 30 of file whence.c.
Referenced by derive_file_spec(), file_spec_parts(), locate_file_in_path(), verify_spec_arg(), view_init_input(), and whence().
path_p
char* path_p
Definition at line 28 of file whence.c.
Referenced by main(), and whence().
path_s
char path_s[MAXLEN]
Definition at line 29 of file whence.c.
Referenced by whence().