C-Menu: dwin.c File Reference
dwin.c File Reference
Window support for C-Menu Menu, Form, Pick, and View.
#include <cm.h>
#include <errno.h>
#include <math.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <termios.h>
#include <unistd.h>
#include <wchar.h>
Enumerations
enum colors_enum {
CLR_BLACK , CLR_RED , CLR_GREEN , CLR_YELLOW ,
CLR_BLUE , CLR_MAGENTA , CLR_CYAN , CLR_WHITE ,
CLR_BBLACK , CLR_BRED , CLR_BGREEN , CLR_BYELLOW ,
CLR_BBLUE , CLR_BMAGENTA , CLR_BCYAN , CLR_BWHITE ,
CLR_BORANGE , CLR_NCOLORS
}
Functions
bool open_curses (SIO *sio)
Initialize NCurses and color settings.
void destroy_curses ()
Gracefully shut down NCurses and restore terminal settings.
int win_new (int wlines, int wcols, int wbegy, int wbegx, char *wtitle, int flag)
Create a new window with optional box and title.
void win_redraw (WINDOW *win)
Redraw the specified window.
void win_resize (int wlines, int wcols, char *title)
Resize the current window and its box, and update the title.
WINDOW * win_del ()
Delete the current window and its associated box window.
void restore_wins ()
Restore all windows after a screen resize.
void cbox (WINDOW *box)
Draw a box around the specified window.
void win_init_attrs (int fg_color, int bg_color, int bo_color)
Initialize window attributes.
int Perror (char *emsg_str)
Display a simple error message window or print to stderr.
void mvwaddstr_fill (WINDOW *w, int y, int x, char *s, int l)
For lines shorter than their display area, fill the rest with spaces.
void abend (int ec, char *s)
Abnormal program termination.
void user_end ()
Program terminated by user.
int nf_error (int ec, char *s)
Display error message and wait for key press.
void set_chyron_key (Chyron *chyron, int k, char *s, int kc)
Set chyron key.
bool is_set_chyron_key (Chyron *chyron, int k)
Check if function key label is set.
void unset_chyron_key (Chyron *chyron, int k)
Unset chyron key.
void compile_chyron (Chyron *chyron)
construct the chyron string from the chyron structure
int get_chyron_key (Chyron *chyron, int x)
Get keycode from chyron.
Chyron * new_chyron ()
Create and initialize Chyron structure.
Chyron * destroy_chyron (Chyron *chyron)
Destroy Chyron structure.
void list_colors ()
list colors to stderr
int clr_name_to_idx (char *s)
Get color index from color name.
void init_hex_clr (int idx, char *s)
Initialize extended ncurses color from HTML style hex string.
int rgb_clr_to_cube (int)
RGB hex_clr_str_to_rgb (char *s)
Convert six-digit HTML style hex color code to RGB struct.
RGB xterm256_idx_to_rgb (int idx)
Convert XTerm 256 color index to RGB color.
int rgb_to_curses_clr (RGB *rgb)
Get color index for RGB color.
int rgb_to_xterm256_idx (RGB *rgb)
Convert RGB color to XTerm 256 color index.
void apply_gamma (RGB *rgb)
Apply gamma correction to RGB color.
bool init_clr_palette (SIO *sio)
Initialize color palette based on SIO settings.
cchar_t mkccc (int cp)
Create a cchar_t with the specified color pair index.
int get_clr_pair (int fg, int bg)
Get color pair index for foreground and background colors.
int display_error (char *em0, char *em1, char *em2, char *em3)
Display an error message window or print to stderr.
int xwgetch (WINDOW *win, Chyron *chyron)
Wrapper for wgetch that handles signals and mouse events.
Variables
int click_y
int click_x
SIO * sio
RGB StdColors [16]
char const colors_text [][10]
const wchar_t bw_ho = BW_HO
const wchar_t bw_ve = BW_VE
const wchar_t bw_tl = BW_RTL
const wchar_t bw_tr = BW_RTR
const wchar_t bw_bl = BW_RBL
const wchar_t bw_br = BW_RBR
const wchar_t bw_lt = BW_LT
const wchar_t bw_rt = BW_RT
const wchar_t bw_sp = BW_SP
double GRAY_GAMMA
double RED_GAMMA
double GREEN_GAMMA
double BLUE_GAMMA
WINDOW * win
WINDOW * win_win [MAXWIN]
WINDOW * win_box [MAXWIN]
int exit_code
unsigned int cmd_key
bool f_sigwench = false
int win_attr
int box_attr
int win_ptr
int m_lines
int m_cols
int m_begy = -1
int m_begx = -1
int mouse_support
int stdin_fd
int stdout_fd
int src_line
char * src_name
char fn [MAXLEN]
char em0 [MAXLEN]
char em1 [MAXLEN]
char em2 [MAXLEN]
char em3 [MAXLEN]
int cp_norm
int cp_box
int cp_reverse
int clr_cnt = 0
int clr_idx = 0
int clr_pair_idx = 1
int clr_pair_cnt = 1
cchar_t CCC_NORM
cchar_t CCC_BOX
cchar_t CCC_REVERSE
int tty_fd
int pipe_in
int pipe_out
Detailed Description
Window support for C-Menu Menu, Form, Pick, and View.
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file dwin.c.
Enumeration Type Documentation
colors_enum
enum colors_enum
Note
Used for xterm256 color conversions
These colors can be overridden in ".minitrc"
Enumerator
CLR_BLACK
CLR_RED
CLR_GREEN
CLR_YELLOW
CLR_BLUE
CLR_MAGENTA
CLR_CYAN
CLR_WHITE
CLR_BBLACK
CLR_BRED
CLR_BGREEN
CLR_BYELLOW
CLR_BBLUE
CLR_BMAGENTA
CLR_BCYAN
CLR_BWHITE
CLR_BORANGE
CLR_NCOLORS
Definition at line 62 of file dwin.c.
Function Documentation
abend()
void abend (int ec, char * s)
Abnormal program termination.
Parameters
ec Exit code
s Error message
Definition at line 1058 of file dwin.c.
References destroy_curses(), restore_shell_tioctl(), and sig_dfl_mode().
Referenced by display_error(), form_parse_desc(), init_menu_files(), init_pick(), init_view_full_screen(), main(), mapp_initialization(), menu_cmd_processor(), new_chyron(), new_form(), new_init(), new_menu(), new_pick(), new_view(), open_curses(), parse_menu_description(), Perror(), sig_prog_mode(), and view_init_input().
apply_gamma()
void apply_gamma (RGB * rgb)
Apply gamma correction to RGB color.
Parameters
rgb Pointer to RGB color
Note
This function modifies the RGB color in place. It applies gamma correction to the RGB color based on the gamma values set in the SIO struct. If the color is a shade of gray, it applies the gray gamma correction. Otherwise, it applies the individual red, green, and blue gamma corrections.
Definition at line 507 of file dwin.c.
References RGB::b, BLUE_GAMMA, RGB::g, GRAY_GAMMA, GREEN_GAMMA, RGB::r, and RED_GAMMA.
Referenced by init_hex_clr(), and rgb_to_curses_clr().
cbox()
void cbox (WINDOW * box)
Draw a box around the specified window.
Parameters
box Pointer to the window to draw the box around
Note
This function uses NCurses functions to draw a box around the specified window. It adds the appropriate characters for the corners and edges of the box based on the current character set. Use this function when you want to visually separate a window from the rest of the screen with a border.
Definition at line 818 of file dwin.c.
References bw_bl, bw_br, bw_ho, bw_tl, bw_tr, and bw_ve.
Referenced by win_new(), and win_resize().
clr_name_to_idx()
int clr_name_to_idx (char * s)
Get color index from color name.
Parameters
s Color name
Returns
Color index or -1 if not found
Definition at line 999 of file dwin.c.
References colors_text, and str_to_lower().
Referenced by parse_config(), and parse_opt_args().
compile_chyron()
void compile_chyron (Chyron * chyron)
construct the chyron string from the chyron structure
Parameters
chyron
The chyron string is constructed by concatenating the labels of the set keys, separated by " | ". The end_pos values for each key are set to determine the zones for mouse clicks. When a mouse click occurs, the get_chyron_key function uses the end_pos values to determine which key was clicked based on the X position of the click.
Definition at line 252 of file dwin.c.
References CHYRON_KEYS, ChyronKey::end_pos, Chyron::key, Chyron::l, MAXLEN, Chyron::s, strnz__cat(), and ChyronKey::text.
Referenced by display_error(), form_accept_field(), form_display_chyron(), form_display_fields(), Perror(), and pick_engine().
destroy_chyron()
Chyron * destroy_chyron (Chyron * chyron)
Destroy Chyron structure.
Parameters
chyron pointer to Chyron structure
Returns
nullptr
Definition at line 192 of file dwin.c.
References CHYRON_KEYS, and Chyron::key.
Referenced by display_error(), and Perror().
destroy_curses()
void destroy_curses ()
Gracefully shut down NCurses and restore terminal settings.
Note
This function should be called before exiting the program to ensure that the terminal is left in a usable state. It checks if NCurses was initialized and, if so, it clears the screen, refreshes it, and ends the NCurses session. It also restores the original terminal settings using restore_shell_tioctl and resets signal handlers to their default state with sig_dfl_mode.
Definition at line 609 of file dwin.c.
References f_curses_open, restore_shell_tioctl(), and sig_dfl_mode().
Referenced by abend(), main(), open_curses(), and user_end().
display_error()
int display_error (char * em0, char * em1, char * em2, char * em3)
Display an error message window or print to stderr.
Parameters
em0 First error message line
em1 Second error message line
em2 Third error message line
em3 Fourth error message line
Returns
Key code of user command
Definition at line 847 of file dwin.c.
References abend(), cmd_key, compile_chyron(), destroy_chyron(), em0, em1, em2, em3, f_curses_open, Chyron::l, MAXLEN, new_chyron(), Chyron::s, set_chyron_key(), ssnprintf(), strnz(), strnz__cpy(), win_del(), win_new(), win_ptr, win_win, and xwgetch().
Referenced by enter_file_spec(), form_calculate(), form_desc_error(), form_parse_desc(), form_read_data(), form_write(), get_clr_pair(), init_view_boxwin(), init_view_full_screen(), lf_find(), mk_dir(), new_init(), new_pick(), new_view(), parse_menu_description(), verify_dir(), verify_file(), view_cmd_processor(), view_init_input(), write_view_buffer(), and xwgetch().
get_chyron_key()
int get_chyron_key (Chyron * chyron, int x)
Get keycode from chyron.
Parameters
chyron structure
x Mouse X position
Returns
Keycode
Note
This function uses the end_pos values set in compile_chyron to determine which key was clicked
The chyron functions provide xwgetch() with a mechanism to translate mouse click positions into key codes based on the labels set in the chyron structure. When a mouse click occurs, xwgetch() can call get_chyron_key() with the X position of the click to determine which function key was clicked, allowing for dynamic and customizable function key behavior in the chyron area of the interface.
Definition at line 287 of file dwin.c.
References ChyronKey::end_pos, Chyron::key, and ChyronKey::keycode.
Referenced by xwgetch().
get_clr_pair()
int get_clr_pair (int fg, int bg)
Get color pair index for foreground and background colors.
Parameters
fg Foreground color index
bg Background color index
Returns
Color pair index
Definition at line 394 of file dwin.c.
References clr_pair_cnt, display_error(), em0, em1, em2, MAXLEN, and ssnprintf().
Referenced by open_curses(), and parse_ansi_str().
hex_clr_str_to_rgb()
RGB hex_clr_str_to_rgb (char * s)
Convert six-digit HTML style hex color code to RGB struct.
Parameters
s six-digit HTML style hex color code
Definition at line 596 of file dwin.c.
References RGB::b, RGB::g, and RGB::r.
Referenced by init_hex_clr().
init_clr_palette()
bool init_clr_palette (SIO * sio)
Initialize color palette based on SIO settings.
Parameters
sio Pointer to SIO struct with color settings
Returns
true if successful, false if error
Note
This function initializes the xterm256 color cube and applies any color overrides specified in the SIO struct. The color strings in the SIO struct are expected to be six-digit HTML style hex color codes (e.g., "#RRGGBB"). If a color override is specified for any of the standard colors, it is applied using the init_hex_clr function. After processing all colors, the clr_cnt variable is set to 16 to indicate that the standard colors have been initialized.
Definition at line 534 of file dwin.c.
References CLR_BBLACK, CLR_BBLUE, CLR_BCYAN, CLR_BGREEN, CLR_BLACK, CLR_BLUE, CLR_BMAGENTA, CLR_BRED, CLR_BWHITE, CLR_BYELLOW, clr_cnt, CLR_CYAN, CLR_GREEN, CLR_MAGENTA, CLR_RED, CLR_WHITE, CLR_YELLOW, init_hex_clr(), and sio.
Referenced by open_curses().
init_hex_clr()
void init_hex_clr (int idx, char * s)
Initialize extended ncurses color from HTML style hex string.
Parameters
idx Color index
s Hex color string
Note
NCurses uses 0-1000 for RGB values, so the RGB values from the hex string are converted to this range before initializing the color. If the color index is less than 16, the RGB values are also stored in the StdColors array for reference.
Definition at line 579 of file dwin.c.
References apply_gamma(), RGB::b, RGB::g, hex_clr_str_to_rgb(), RGB::r, and StdColors.
Referenced by init_clr_palette().
is_set_chyron_key()
bool is_set_chyron_key (Chyron * chyron, int k)
Check if function key label is set.
Parameters
chyron structure
k Function key index (0-19)
Returns
true if set, false if not set
Definition at line 210 of file dwin.c.
References Chyron::key, and ChyronKey::text.
Referenced by form_calculate(), and form_end_fields().
list_colors()
void list_colors ()
list colors to stderr
Note
only lists the first 16, since that's how many we let the user redefine
Definition at line 1017 of file dwin.c.
References colors_text.
mkccc()
cchar_t mkccc (int cp)
Create a cchar_t with the specified color pair index.
Parameters
cp Color pair index
Returns
cchar_t with the specified color pair index and a space character as the wide character
Definition at line 625 of file dwin.c.
Referenced by open_curses().
mvwaddstr_fill()
void mvwaddstr_fill (WINDOW * w, int y, int x, char * s, int l)
For lines shorter than their display area, fill the rest with spaces.
Parameters
w Pointer to window
y Y coordinate
x X coordinate
s String to display
l Length of display area
Definition at line 979 of file dwin.c.
References MAXLEN, and tmp_str.
Referenced by display_page(), menu_cmd_processor(), picker(), reverse_object(), and unreverse_object().
new_chyron()
Chyron * new_chyron ()
Create and initialize Chyron structure.
Returns
pointer to new Chyron structure
This function allocates memory for a new Chyron structure and initializes the key pointers. Each key pointer is allocated memory for a ChyronKey structure. The Chyron structure is used to manage function key labels and their associated keycodes for mouse click handling in the chyron area of the interface.
Note
The use of calloc ensures that the allocated memory is initialized to zero, which means that the text for each key will be initialized to an empty string and the keycodes will be initialized to zero. This allows the is_set_chyron_key function to check if a key is set by checking if the first character of the text is not '\0'. If any memory allocation fails, the function will call abend to handle the error and return nullptr.
Definition at line 178 of file dwin.c.
References abend(), CHYRON_KEYS, and Chyron::key.
Referenced by display_error(), form_display_fields(), Perror(), and pick_engine().
nf_error()
int nf_error (int ec, char * s)
Display error message and wait for key press.
Parameters
ec Error code
s Error message
Definition at line 1037 of file dwin.c.
References di_getch().
open_curses()
bool open_curses (SIO * sio)
Initialize NCurses and color settings.
Parameters
sio Pointer to SIO struct with terminal and color settings
Returns
true if successful, false if error note This function initializes NCurses and sets up color pairs based on the settings in the SIO struct. It also applies gamma correction to colors. Use this function to initialize NCurses if you don't want NCurses to receive data from the stdin pipe
1. saves stdin and stdout file descriptors in SIO
2. opens a terminal device for NCurses screen IO
3. replaces STDERR_FILENO with terminal file descriptor
save stdin and stdout file descriptors
open the terminal device for reading and writing
Attach the terminal descriptor to the STDERR_FILENO
We use SCREEN and newterm because this allows us to
specify the terminal FILE
Set gamma correction values
These are read from ~/.minitrc
We need these values when initializing colors
Definition at line 306 of file dwin.c.
References abend(), RGB::b, BLUE_GAMMA, CCC_BOX, CCC_NORM, CCC_REVERSE, cp_box, cp_norm, cp_reverse, destroy_curses(), f_curses_open, RGB::g, get_clr_pair(), GRAY_GAMMA, GREEN_GAMMA, init_clr_palette(), MAXLEN, mkccc(), RGB::r, RED_GAMMA, sio, strnz__cat(), strnz__cpy(), and tmp_str.
Referenced by main().
Perror()
int Perror (char * emsg_str)
Display a simple error message window or print to stderr.
Parameters
emsg_str Error message string
Returns
Key code of user command
Definition at line 928 of file dwin.c.
References abend(), cmd_key, compile_chyron(), destroy_chyron(), f_curses_open, Chyron::l, MAXLEN, new_chyron(), Chyron::s, set_chyron_key(), ssnprintf(), strnz__cpy(), win_del(), win_new(), win_ptr, win_win, and xwgetch().
Referenced by display_curses_keys(), display_line(), exec_objects(), fork_exec(), form_accept_field(), form_calculate(), form_display_screen(), form_engine(), form_fmt_field(), form_usage(), form_validate_field(), get_cmd_arg(), go_to_line(), go_to_mark(), go_to_percent(), init_form(), init_pick(), lf_process(), menu_engine(), new_pick(), open_pick_win(), parse_menu_description(), search(), view_cmd_processor(), view_init_input(), and write_config().
restore_wins()
void restore_wins ()
Restore all windows after a screen resize.
Note
This function is used to restore the display of all windows after a screen resize event. It clears the standard screen and then iterates through all existing windows, touching and refreshing them to ensure they are redrawn correctly on the resized screen. Use this function in response to a SIGWINCH signal to handle terminal resizing gracefully.
Definition at line 797 of file dwin.c.
References win_box, win_ptr, and win_win.
Referenced by exec_objects(), fork_exec(), form_engine(), full_screen_fork_exec(), full_screen_shell(), menu_cmd_processor(), resize_page(), and view_cmd_processor().
rgb_clr_to_cube()
int rgb_clr_to_cube (int)
rgb_to_curses_clr()
int rgb_to_curses_clr (RGB * rgb)
Get color index for RGB color.
Parameters
rgb RGB color
Returns
NCurses color index
Note
Curses uses 0-1000 for RGB values
If the color does not exist, it is created along with a new color index
Definition at line 425 of file dwin.c.
References apply_gamma(), RGB::b, clr_cnt, RGB::g, and RGB::r.
Referenced by parse_ansi_str().
rgb_to_xterm256_idx()
int rgb_to_xterm256_idx (RGB * rgb)
Convert RGB color to XTerm 256 color index.
Parameters
rgb RGB color
Returns
XTerm 256 color index note This function converts an RGB color to the nearest XTerm 256 color index. It first checks if the color is a shade of gray, and if so, it uses the gray ramp. Otherwise, it calculates the nearest color in the 6x6x6 color cube.
Definition at line 453 of file dwin.c.
References RGB::b, RGB::g, and RGB::r.
set_chyron_key()
void set_chyron_key (Chyron * chyron, int k, char * s, int kc)
Set chyron key.
Parameters
chyron structure
k chyron key index (0-19)
s chyron key label
kc chyron key code
This function sets the label and keycode for a chyron key. The label is copied into the chyron structure, and the keycode is stored for later retrieval when theire is a mouse click. The compile_chyron function uses the keycode values to determine which key was clicked based on the mouse X position. If the label string is empty, the key is unset by setting the first character of the text to '\0'.
Definition at line 228 of file dwin.c.
References CHYRON_KEY_MAXLEN, Chyron::key, ChyronKey::keycode, ssnprintf(), and ChyronKey::text.
Referenced by display_error(), form_accept_field(), form_calculate(), form_display_fields(), form_end_fields(), Perror(), and pick_engine().
unset_chyron_key()
void unset_chyron_key (Chyron * chyron, int k)
Unset chyron key.
Parameters
chyron structure
k chyron_key index
Definition at line 243 of file dwin.c.
References Chyron::key, and ChyronKey::text.
Referenced by form_calculate(), and form_end_fields().
user_end()
void user_end ()
Program terminated by user.
Definition at line 1046 of file dwin.c.
References destroy_curses(), restore_shell_tioctl(), and sig_dfl_mode().
win_del()
WINDOW * win_del ()
Delete the current window and its associated box window.
Returns
nullptr
Note
This function deletes the current window and its associated box window, if they exist. It also refreshes the remaining windows to ensure the display is updated correctly. After calling this function, the global win_ptr variable is decremented to point to the previous window in the stack.
Definition at line 764 of file dwin.c.
References win_box, win_ptr, and win_win.
Referenced by display_curses_keys(), display_error(), init_form(), init_pick(), main(), menu_engine(), mview(), and Perror().
win_init_attrs()
void win_init_attrs (int fg_color, int bg_color, int bo_color)
Initialize window attributes.
Parameters
fg_color Foreground color index
bg_color Background color index
bo_color Box color index note This function initializes color pairs for the window note cp_norm and cp_box are global variables see get_clr_pair
Definition at line 159 of file dwin.c.
References cp_box, and cp_norm.
Referenced by main().
win_new()
int win_new (int wlines, int wcols, int wbegy, int wbegx, char * wtitle, int flag)
Create a new window with optional box and title.
Parameters
wlines Number of lines
wcols Number of columns
wbegy Beginning Y position
wbegx Beginning X position
wtitle Window title
flag Window flags
Note
if flag set to W_BOX, Only create win_box. This is for View which uses the box window for display and doesn't need a separate win_win
Returns
0 if successful, 1 if error
Definition at line 642 of file dwin.c.
References bw_lt, bw_rt, bw_sp, cbox(), CCC_BOX, CCC_NORM, MAXLEN, MAXWIN, strnz__cpy(), W_BOX, win_box, win_ptr, and win_win.
Referenced by display_curses_keys(), display_error(), form_display_screen(), init_view_boxwin(), menu_engine(), open_pick_win(), and Perror().
win_redraw()
void win_redraw (WINDOW * win)
Redraw the specified window.
Parameters
win Pointer to the window to redraw
Note
This function erases the contents of the specified window and then refreshes it to update the display. Use this function when you need to clear and redraw a window, such as after resizing or when updating its contents.
Definition at line 753 of file dwin.c.
References win.
win_resize()
void win_resize (int wlines, int wcols, char * title)
Resize the current window and its box, and update the title.
Parameters
wlines Number of lines
wcols Number of columns
title Window title
Note
This function resizes the current window and its associated box window to the specified number of lines and columns. It also updates the title of the box window if a title is provided. After resizing, it refreshes the windows to apply the changes.
Definition at line 713 of file dwin.c.
References bw_lt, bw_rt, bw_sp, cbox(), CCC_BOX, CCC_NORM, cp_norm, sio, TRUE, win_box, win_ptr, and win_win.
Referenced by resize_page().
xterm256_idx_to_rgb()
RGB xterm256_idx_to_rgb (int idx)
Convert XTerm 256 color index to RGB color.
Parameters
idx XTerm 256 color index
Returns
RGB color note This function converts an XTerm 256 color index to an RGB color. It first checks if the index is in the standard 16 colors, then checks if it's in the 6x6x6 color cube, and finally checks if it's in the gray ramp.
Convert XTerm 256 color index to RGB
Parameters
idx - XTerm 256 color index
Returns
RGB struct
Definition at line 474 of file dwin.c.
References RGB::b, RGB::g, RGB::r, and StdColors.
Referenced by parse_ansi_str().
xwgetch()
int xwgetch (WINDOW * win, Chyron * chyron)
Wrapper for wgetch that handles signals and mouse events.
Parameters
win Pointer to window
chyron Pointer to chyron for handling chyron line clicks
Returns
Key code or ERR if interrupted by signal
Note
This, of course, will be expanded into an event loop for message queuing
Get mouse event and check if it's a left click or double click. If the click is outside the window, ignore it. If it's on the chyron line, get the corresponding key command. Otherwise, store the click coordinates as click_y and click_x for later use.
Definition at line 1075 of file dwin.c.
References click_x, click_y, display_error(), em0, em1, em2, get_chyron_key(), handle_signal(), sig_received, and win.
Referenced by display_curses_keys(), display_error(), form_accept_field(), form_calculate(), form_end_fields(), get_cmd_arg(), get_cmd_char(), menu_cmd_processor(), Perror(), picker(), and remove_file().
Variable Documentation
BLUE_GAMMA
double BLUE_GAMMA
Initial value:
              =
1.2
Gamma correction value for blue colors. Set in .minitrc
Definition at line 113 of file dwin.c.
Referenced by apply_gamma(), and open_curses().
box_attr
int box_attr
Definition at line 123 of file dwin.c.
bw_bl
const wchar_t bw_bl = BW_RBL
bottom left corner
Definition at line 102 of file dwin.c.
Referenced by cbox().
bw_br
const wchar_t bw_br = BW_RBR
bottom right corner
Definition at line 103 of file dwin.c.
Referenced by cbox().
bw_ho
const wchar_t bw_ho = BW_HO
horizontal line
Definition at line 98 of file dwin.c.
Referenced by cbox().
bw_lt
const wchar_t bw_lt = BW_LT
left tee
Definition at line 104 of file dwin.c.
Referenced by win_new(), and win_resize().
bw_rt
const wchar_t bw_rt = BW_RT
right tee
Definition at line 105 of file dwin.c.
Referenced by win_new(), and win_resize().
bw_sp
const wchar_t bw_sp = BW_SP
tee space
Definition at line 106 of file dwin.c.
Referenced by win_new(), and win_resize().
bw_tl
const wchar_t bw_tl = BW_RTL
top left corner
Definition at line 100 of file dwin.c.
Referenced by cbox().
bw_tr
const wchar_t bw_tr = BW_RTR
top right corner
Definition at line 101 of file dwin.c.
Referenced by cbox().
bw_ve
const wchar_t bw_ve = BW_VE
vertical line
Definition at line 99 of file dwin.c.
Referenced by cbox().
CCC_BOX
cchar_t CCC_BOX
box color pair complex character
Definition at line 147 of file dwin.c.
Referenced by handle_signal(), init_view_full_screen(), open_curses(), win_new(), and win_resize().
CCC_NORM
cchar_t CCC_NORM
normal color pair complex character
Definition at line 146 of file dwin.c.
Referenced by handle_signal(), init_view_boxwin(), open_curses(), win_new(), and win_resize().
CCC_REVERSE
cchar_t CCC_REVERSE
reverse color pair complex character
Definition at line 148 of file dwin.c.
Referenced by handle_signal(), and open_curses().
click_x
int click_x
the x coordinate of a mouse click, for handling mouse
Definition at line 43 of file dwin.c.
Referenced by form_accept_field(), form_calculate(), form_end_fields(), menu_cmd_processor(), picker(), and xwgetch().
click_y
int click_y
the y coordinate of a mouse click, for handling mouse events
Definition at line 42 of file dwin.c.
Referenced by form_accept_field(), form_calculate(), form_end_fields(), menu_cmd_processor(), picker(), and xwgetch().
clr_cnt
int clr_cnt = 0
number of colors used
Definition at line 142 of file dwin.c.
Referenced by init_clr_palette(), and rgb_to_curses_clr().
clr_idx
int clr_idx = 0
current color index
Definition at line 143 of file dwin.c.
clr_pair_cnt
int clr_pair_cnt = 1
number of color pairs supported by the terminal
Definition at line 145 of file dwin.c.
Referenced by get_clr_pair().
clr_pair_idx
int clr_pair_idx = 1
current color pair index
Definition at line 144 of file dwin.c.
Referenced by parse_ansi_str().
cmd_key
unsigned int cmd_key
the command key for the current command, for error messages and other output
Definition at line 120 of file dwin.c.
Referenced by display_error(), form_desc_error(), form_enter_fields(), form_read_data(), Perror(), and picker().
colors_text
char const colors_text[][10]
Initial value:
                   = {
"black",   "red",    "green", "yellow",   "blue",   "magenta", "cyan",
"white",   "orange", "bg",    "abg",      "bblack", "bred",    "bgreen",
"byellow", "bblue",  "bcyan", "bmagenta", "bwhite", "borange", ""}
colors_text
Note
Color names for .minitrc overrides
These names are used in .minitrc to specify color overrides
The order of these names corresponds to the colors_enum values
Definition at line 94 of file dwin.c.
Referenced by clr_name_to_idx(), list_colors(), and write_config().
cp_box
int cp_box
box color pair index
Definition at line 140 of file dwin.c.
Referenced by open_curses(), and win_init_attrs().
cp_norm
int cp_norm
normal color pair index
Definition at line 139 of file dwin.c.
Referenced by fmt_line(), open_curses(), search(), win_init_attrs(), and win_resize().
cp_reverse
int cp_reverse
reverse color pair index
Definition at line 141 of file dwin.c.
Referenced by open_curses().
em0
char em0[MAXLEN]
error message string for error messages
Definition at line 135 of file dwin.c.
Referenced by display_error(), enter_file_spec(), form_calculate(), form_desc_error(), form_parse_desc(), form_read_data(), form_write(), get_clr_pair(), handle_signal(), init_view_boxwin(), init_view_full_screen(), lf_find(), mk_dir(), new_init(), new_pick(), new_view(), parse_menu_description(), verify_dir(), verify_file(), view_cmd_processor(), view_init_input(), write_view_buffer(), and xwgetch().
em1
char em1[MAXLEN]
error message string for error messages
Definition at line 136 of file dwin.c.
Referenced by display_error(), enter_file_spec(), form_calculate(), form_desc_error(), form_parse_desc(), form_read_data(), form_write(), get_clr_pair(), handle_signal(), init_view_boxwin(), init_view_full_screen(), lf_find(), mk_dir(), new_init(), new_pick(), new_view(), parse_menu_description(), verify_dir(), verify_file(), view_cmd_processor(), view_init_input(), write_view_buffer(), and xwgetch().
em2
char em2[MAXLEN]
error message string for error messages
Definition at line 137 of file dwin.c.
Referenced by display_error(), enter_file_spec(), form_calculate(), form_desc_error(), form_parse_desc(), form_read_data(), form_write(), get_clr_pair(), handle_signal(), init_view_boxwin(), init_view_full_screen(), lf_find(), mk_dir(), new_init(), new_view(), parse_menu_description(), verify_dir(), verify_file(), view_cmd_processor(), view_init_input(), write_view_buffer(), and xwgetch().
em3
char em3[MAXLEN]
error message string for error messages
Definition at line 138 of file dwin.c.
Referenced by display_error(), verify_dir(), and verify_file().
exit_code
int exit_code
the exit code for the program, for error messages and other output
Definition at line 119 of file dwin.c.
f_sigwench
bool f_sigwench = false
Definition at line 121 of file dwin.c.
fn
char fn[MAXLEN]
function name for error messages
Definition at line 134 of file dwin.c.
Referenced by file_spec_name(), locate_file_in_path(), verify_dir(), and verify_file().
GRAY_GAMMA
double GRAY_GAMMA
Initial value:
              =
1.2
Gamma correction value for gray colors. Set in .minitrc
Definition at line 107 of file dwin.c.
Referenced by apply_gamma(), and open_curses().
GREEN_GAMMA
double GREEN_GAMMA
Initial value:
               =
1.2
Gamma correction value for green colors. Set in .minitrc
Definition at line 111 of file dwin.c.
Referenced by apply_gamma(), and open_curses().
m_begx
int m_begx = -1
Definition at line 128 of file dwin.c.
m_begy
int m_begy = -1
Definition at line 127 of file dwin.c.
m_cols
int m_cols
Definition at line 126 of file dwin.c.
m_lines
int m_lines
Definition at line 125 of file dwin.c.
mouse_support
int mouse_support
Definition at line 129 of file dwin.c.
pipe_in
int pipe_in
Definition at line 150 of file dwin.c.
pipe_out
int pipe_out
Definition at line 150 of file dwin.c.
RED_GAMMA
double RED_GAMMA
Initial value:
             =
1.2
Gamma correction value for red colors. Set in .minitrc
Definition at line 109 of file dwin.c.
Referenced by apply_gamma(), and open_curses().
sio
SIO* sio
Global pointer to SIO struct for terminal and color settings
Definition at line 57 of file dwin.c.
Referenced by dump_config(), init_clr_palette(), init_pick(), main(), mapp_initialization(), open_curses(), parse_config(), parse_opt_args(), win_resize(), and write_config().
src_line
int src_line
the line number of the source file being processed, for error messages
Definition at line 132 of file dwin.c.
Referenced by verify_dir(), and verify_file().
src_name
char* src_name
the name of the source file being processed, for error messages
Definition at line 133 of file dwin.c.
Referenced by verify_dir(), and verify_file().
StdColors
RGB StdColors[16]
Initial value:
          = {
{0, 0, 0},       {128, 0, 0},   {0, 128, 0},   {128, 128, 0},
{0, 0, 128},     {128, 0, 128}, {0, 128, 128}, {192, 192, 192},
{128, 128, 128}, {255, 0, 0},   {0, 255, 0},   {255, 255, 0},
{0, 0, 255},     {255, 0, 255}, {0, 255, 255}, {255, 255, 255}}
StdColors
Note
Standard 16 colors for xterm256 color conversions
These colors can be overridden in ".minitrc"
Definition at line 85 of file dwin.c.
Referenced by init_hex_clr(), and xterm256_idx_to_rgb().
stdin_fd
int stdin_fd
Definition at line 130 of file dwin.c.
stdout_fd
int stdout_fd
Definition at line 131 of file dwin.c.
tty_fd
int tty_fd
Global file/pipe numbers
Definition at line 150 of file dwin.c.
Referenced by picker().
win
WINDOW* win
generic window pointer, used for various purposes
Definition at line 116 of file dwin.c.
Referenced by display_curses_keys(), enter_option(), form_accept_field(), form_display_field(), win_redraw(), and xwgetch().
win_attr
int win_attr
Ncurses attributes for the current window, such as color pair, bold, etc.
Definition at line 122 of file dwin.c.
Referenced by enter_option().
win_box
WINDOW* win_box[MAXWIN]
array of pointers to box windows, indexed by window ID
Definition at line 118 of file dwin.c.
Referenced by display_curses_keys(), enter_option(), form_display_screen(), menu_engine(), open_pick_win(), restore_wins(), win_del(), win_new(), and win_resize().
win_ptr
int win_ptr
Pointer to the current window pair, box and window, which can be used to keep track of the currently active window and its associated box.
Definition at line 124 of file dwin.c.
Referenced by display_curses_keys(), display_error(), enter_option(), form_display_screen(), init_view_boxwin(), menu_engine(), open_pick_win(), Perror(), restore_wins(), win_del(), win_new(), and win_resize().
win_win
WINDOW* win_win[MAXWIN]
array of pointers to windows, indexed by window ID
Definition at line 117 of file dwin.c.
Referenced by display_curses_keys(), display_error(), enter_option(), form_display_screen(), init_view_boxwin(), menu_engine(), open_pick_win(), Perror(), restore_wins(), win_del(), win_new(), and win_resize().