C-Menu: view_engine.c File Reference
view_engine.c File Reference
The working part of View.
#include <common.h>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <regex.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <termios.h>
#include <time.h>
#include <unistd.h>
Macros
#define Ctrl(c)
#define get_next_char()
read the next characater from the virtual file
#define get_prev_char()
read the previous characater from the virtual file
Functions
int view_file (Init *init)
Start view.
int view_cmd_processor (Init *init)
Main Command Processing Loop for View.
int get_cmd_char (View *view, off_t *n)
Get Command Character and Numeric Argument.
int get_cmd_arg (View *view, char *prompt)
Get Command Argument from User Input.
void build_prompt (View *view, int prompt_type, char *prompt_str, double elapsed)
Build Prompt String.
void cat_file (View *view)
Concatenate File to Standard Output.
void lp (char *PrintFile)
Send File to Print Queue.
void go_to_mark (View *view, int c)
Go to Mark.
void go_to_eof (View *view)
Go to End of File.
int go_to_line (View *view, off_t line_idx)
Go to Specific Line.
void go_to_percent (View *view, int percent)
Go to Percent of File.
void go_to_position (View *view, off_t go_to_pos)
Go to Specific File Position.
bool search (View *view, int *search_cmd, char *regex_pattern)
Search for Regular Expression Pattern.
void next_page (View *view)
Advance to Next Page.
void prev_page (View *view)
display previous page
void resize_page (Init *init)
Resize Viewing Page.
void redisplay_page (View *view)
Redisplay Current Page.
void scroll_down_n_lines (View *view, int n)
Scroll N Lines.
void scroll_up_n_lines (View *view, int n)
Scroll Up N Lines.
off_t get_next_line (View *view, off_t pos)
Get Next Line from File.
off_t get_prev_line (View *view, off_t pos)
Get Previous Line from File.
off_t get_pos_next_line (View *view, off_t pos)
Get Position of Next Line.
off_t get_pos_prev_line (View *view, off_t pos)
Get Position of Previous Line.
int fmt_line (View *view)
Format Line for Display.
void display_line (View *view)
Display Line on Pad.
void parse_ansi_str (char *ansi_str, attr_t *attr, int *cpx)
Parse ANSI SGR Escape Sequence.
void view_display_help (Init *init)
Display View Help File.
void cmd_line_prompt (View *view, char *s)
Display Command Line Prompt.
void remove_file (View *view)
Remove File.
int write_view_buffer (Init *init, bool f_strip_ansi)
Write buffer contents to files.
bool enter_file_spec (Init *init, char *file_spec)
use form to enter a file specification
int a_toi (char *s, bool *a_toi_error)
a safer alternative to atoi() for converting ASCII strings to integers.
Variables
char prev_regex_pattern [MAXLEN]
FILE * dbgfp
char err_msg [MAXLEN]
Detailed Description
The working part of View.
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file view_engine.c.
Macro Definition Documentation
Ctrl
#define Ctrl (c)
Value:
((c) & 0x1f)
Definition at line 23 of file view_engine.c.
Referenced by view_cmd_processor().
get_next_char
#define get_next_char ()
Value:
do {                                                                       \
    if (view->file_pos == view->file_size) {                               \
        view->f_eod = true;                                                \
        break;                                                             \
    } else                                                                 \
        view->f_eod = false;                                               \
    c = view->buf[view->file_pos++];                                       \
} while (c == 0x0d);
read the next characater from the virtual file
Definition at line 26 of file view_engine.c.
Referenced by cat_file(), get_next_line(), get_pos_next_line(), get_pos_prev_line(), go_to_line(), and go_to_percent().
get_prev_char
#define get_prev_char ()
Value:
do {                                                                       \
    if (view->file_pos == 0) {                                             \
        view->f_bod = true;                                                \
        break;                                                             \
    } else                                                                 \
        view->f_bod = false;                                               \
    c = view->buf[--view->file_pos];                                       \
} while (c == 0x0d);
read the previous characater from the virtual file
Definition at line 37 of file view_engine.c.
Referenced by get_next_line(), get_pos_next_line(), get_pos_prev_line(), go_to_eof(), and go_to_percent().
Function Documentation
a_toi()
int a_toi (char * s, bool * a_toi_error)
a safer alternative to atoi() for converting ASCII strings to integers.
Parameters
s is the input string
a_toi_error is a pointer to a boolean that will be set to true if an error occurs during conversion, or false if the conversion is successful.
Note
accepts positive integers only.
sets a_toi_error to (-1) on error
Returns
converted integer value, or -1 if an error occurs
Definition at line 438 of file futil.c.
Referenced by parse_ansi_str().
build_prompt()
void build_prompt (View * view, int prompt_type, char * prompt_str, double elapsed)
Build Prompt String.
Definition at line 779 of file view_engine.c.
References base_name(), MAXLEN, NULL_POSITION, PT_LONG, PT_NONE, strnz__cat(), strnz__cpy(), tmp_str, and view.
Referenced by view_cmd_processor().
cat_file()
void cat_file (View * view)
Concatenate File to Standard Output.
Definition at line 892 of file view_engine.c.
References get_next_char, and view.
cmd_line_prompt()
void cmd_line_prompt (View * view, char * s)
Display Command Line Prompt.
Parameters
view is the current view data structure
s is the prompt string
Definition at line 1729 of file view_engine.c.
References PAD_COLS, strnz__cpy(), and view.
Referenced by lp(), and view_cmd_processor().
display_line()
void display_line (View * view)
Display Line on Pad.
Definition at line 1460 of file view_engine.c.
References Perror(), and view.
Referenced by next_page(), redisplay_page(), scroll_down_n_lines(), scroll_up_n_lines(), and search().
enter_file_spec()
bool enter_file_spec (Init * init, char * file_spec)
use form to enter a file specification
Parameters
init data structure
file_spec - pointer to file specification the file_spec
Returns
true if successful
Note
the user must provide a character array large enough to hold file_spec without overflowing
call form to get file_name write the name to a temporary file
read file_name from tmp_spec
Definition at line 1809 of file view_engine.c.
References destroy_form(), display_error(), earg_str, eargc, eargv, em0, em1, em2, expand_tilde(), init, init_form(), MAX_ARGS, MAXLEN, mk_dir(), P_CANCEL, parse_opt_args(), S_QUIET, S_WCOK, ssnprintf(), str_to_args(), strnz(), strnz__cat(), strnz__cpy(), tmp_str, verify_spec_arg(), view, and zero_opt_args().
Referenced by view_cmd_processor().
fmt_line()
int fmt_line (View * view)
Format Line for Display.
Parameters
view pointer to View structure containing line input and output buffers
Returns
length of formatted line in characters
This function processes the input line from view->line_in_s, handling ANSI escape sequences for text attributes and colors, as well as multi-byte characters. It converts the input line into a formatted line suitable for display in the terminal, storing the result in view->cmplx_buf and view->stripped_line_out. The function returns the length of the formatted line in characters, which may be used for tracking the maximum column width of the displayed content.
Initialize multibyte to wide char conversion
Handle ANSI escape sequences
Wide and complex characters
Definition at line 1488 of file view_engine.c.
References cp_norm, in_str, MAXLEN, PAD_COLS, parse_ansi_str(), rtrim(), and view.
Referenced by next_page(), redisplay_page(), scroll_down_n_lines(), scroll_up_n_lines(), and search().
get_cmd_arg()
int get_cmd_arg (View * view, char * prompt)
Get Command Argument from User Input.
Basic Editing Keys for Command Line
Definition at line 684 of file view_engine.c.
References MAXLEN, PAD_COLS, Perror(), strnz__cpy(), view, and xwgetch().
Referenced by view_cmd_processor().
get_cmd_char()
int get_cmd_char (View * view, off_t * n)
Get Command Character and Numeric Argument.
Definition at line 655 of file view_engine.c.
References MA_ENTER_OPTION, view, and xwgetch().
Referenced by view_cmd_processor().
get_next_line()
off_t get_next_line (View * view, off_t pos)
Get Next Line from File.
Parameters
view struct
pos buffer offset
Returns
file position of next line
Note
gets view->line_in_s
Definition at line 1350 of file view_engine.c.
References get_next_char, get_prev_char, PAD_COLS, and view.
Referenced by get_prev_line(), next_page(), redisplay_page(), scroll_down_n_lines(), scroll_up_n_lines(), search(), and write_view_buffer().
get_pos_next_line()
off_t get_pos_next_line (View * view, off_t pos)
Get Position of Next Line.
Definition at line 1404 of file view_engine.c.
References get_next_char, get_prev_char, and view.
Referenced by scroll_down_n_lines().
get_pos_prev_line()
off_t get_pos_prev_line (View * view, off_t pos)
Get Position of Previous Line.
Definition at line 1435 of file view_engine.c.
References get_next_char, get_prev_char, and view.
Referenced by get_prev_line(), prev_page(), and scroll_up_n_lines().
get_prev_line()
off_t get_prev_line (View * view, off_t pos)
Get Previous Line from File.
Definition at line 1397 of file view_engine.c.
References get_next_line(), get_pos_prev_line(), and view.
Referenced by search().
go_to_eof()
void go_to_eof (View * view)
Go to End of File.
Definition at line 927 of file view_engine.c.
References get_prev_char, prev_page(), and view.
Referenced by view_cmd_processor().
go_to_line()
int go_to_line (View * view, off_t line_idx)
Go to Specific Line.
Definition at line 935 of file view_engine.c.
References get_next_char, go_to_position(), MAXLEN, Perror(), prev_page(), tmp_str, and view.
Referenced by view_cmd_processor().
go_to_mark()
void go_to_mark (View * view, int c)
Go to Mark.
Definition at line 916 of file view_engine.c.
References go_to_position(), NMARKS, NULL_POSITION, Perror(), and view.
Referenced by view_cmd_processor().
go_to_percent()
void go_to_percent (View * view, int percent)
Go to Percent of File.
Parameters
view data structure
percent of file
Definition at line 966 of file view_engine.c.
References get_next_char, get_prev_char, next_page(), Perror(), and view.
Referenced by view_cmd_processor().
go_to_position()
void go_to_position (View * view, off_t go_to_pos)
Go to Specific File Position.
Definition at line 983 of file view_engine.c.
References next_page(), and view.
Referenced by go_to_line(), and go_to_mark().
lp()
void lp (char * PrintFile)
Send File to Print Queue.
Parameters
PrintFile - file to print
Definition at line 903 of file view_engine.c.
References cmd_line_prompt(), MAXLEN, PRINTCMD, shell(), and view.
Referenced by view_cmd_processor().
next_page()
void next_page (View * view)
Advance to Next Page.
Definition at line 1228 of file view_engine.c.
References display_line(), fmt_line(), get_next_line(), and view.
Referenced by go_to_percent(), go_to_position(), prev_page(), view_cmd_processor(), and view_file().
parse_ansi_str()
void parse_ansi_str (char * ansi_str, attr_t * attr, int * cpx)
Parse ANSI SGR Escape Sequence.
Parameters
ansi_str is the ANSI escape sequence string to parse
attr is a pointer to an attr_t variable where the parsed attributes will be stored
cpx is a pointer to an int variable where the parsed color pair index will be stored
This function parses an ANSI SGR (Select Graphic Rendition) escape sequence and updates the provided attr_t and color pair index based on the attributes specified in the ANSI string.
 This function converts the following SGR specification types to the
appropriate curses color pair index for use in the terminal display.
 RGB:
     foreground \033[38;2;r;g;bm
     background \033[48;2;r;g;bm
     Where r, g, b are the red, green, and blue color components
(0-255)
 XTERM 256-color:
     foreground \033[38;5;xm
     background \033[48;5;xm
     Where x is the 256-color index (0-255)
     uses xterm256_idx_to_rgb() to convert the 256-color index to
RGB
 8-color:
     foreground \033[3cm
     background \033[4cm
     Where c is the color code (0 for black, 1 for red, 2 for green, 3 for
yellow, 4 for blue, 5 for magenta, 6 for cyan, 7 for white).
 Attributes:
     \033[am
     Where a is the attribute code (1 for bold, 2 for dim, 3 for italic, 4
for underline, 5 for blink, 7 for reverse, 8 for invis). The function also
supports resetting attributes and colors to default using \033[0m.
 @sa xterm256_idx_to_rgb(), rgb_to_curses_clr(), extended_pair_content(),
get_clr_pair()
Definition at line 1617 of file view_engine.c.
References a_toi(), RGB::b, clr_pair_idx, RGB::g, get_clr_pair(), RGB::r, rgb_to_curses_clr(), and xterm256_idx_to_rgb().
Referenced by fmt_line().
prev_page()
void prev_page (View * view)
display previous page
Definition at line 1253 of file view_engine.c.
References get_pos_prev_line(), next_page(), and view.
Referenced by go_to_eof(), and go_to_line().
redisplay_page()
void redisplay_page (View * view)
Redisplay Current Page.
Definition at line 1211 of file view_engine.c.
References display_line(), fmt_line(), get_next_line(), and view.
Referenced by view_cmd_processor().
remove_file()
void remove_file (View * view)
Remove File.
Parameters
view is the current view data structure
Definition at line 1748 of file view_engine.c.
References view, and xwgetch().
resize_page()
void resize_page (Init * init)
Resize Viewing Page.
Parameters
init data structure
Definition at line 1171 of file view_engine.c.
References init, restore_wins(), view, and win_resize().
Referenced by view_cmd_processor().
scroll_down_n_lines()
void scroll_down_n_lines (View * view, int n)
Scroll N Lines.
Locate New Top of Page
Scroll
Fill in Page Bottom
Definition at line 1272 of file view_engine.c.
References display_line(), fmt_line(), get_next_line(), get_pos_next_line(), and view.
Referenced by view_cmd_processor().
scroll_up_n_lines()
void scroll_up_n_lines (View * view, int n)
Scroll Up N Lines.
Locate New Top of Page
Locate New Bottom of Page
Scroll Up
Fill in Page Top
Definition at line 1305 of file view_engine.c.
References display_line(), fmt_line(), get_next_line(), get_pos_prev_line(), and view.
Referenced by view_cmd_processor().
search()
bool search (View * view, int * search_cmd, char * regex_pattern)
Search for Regular Expression Pattern.
Parameters
view Pointer to View Structure
search_cmd Search Command Character ('/' or '?')
regex_pattern Regular Expression Pattern to Search For
Returns
true if a match is found and displayed, false if the search completes without finding a match or if an error occurs
Note
The search performs extended regular expression matching, ignoring ANSI sequences and Unicode characters. Matches are highlighted on the screen, and the search continues until the page is full or the end of the file is reached. If the search wraps around the file, a message is displayed indicating that the search is complete.
The search state is maintained in the view structure, allowing for repeat searches and tracking of the current search position.
this function highlights all matches in the current ncurses pad, including those not displayed on the screen, and tracks the first and last match columns for prompt display.
ANSI sequences and Unicode characters are stripped before matching, so matching corresponds to the visual display
initialize iteration
get line to scan
non-matching page filler
Display matching lines
All matches on the current line are highlighted, including those not displayed on the screen. Track first and last match columns for prompt display.
Definition at line 1006 of file view_engine.c.
References cp_norm, display_line(), fmt_line(), get_next_line(), get_prev_line(), MAXLEN, Perror(), ssnprintf(), strnz__cat(), strnz__cpy(), tmp_str, and view.
Referenced by view_cmd_processor().
view_cmd_processor()
int view_cmd_processor (Init * init)
Main Command Processing Loop for View.
< Ctrl('R') or KEY_RESIZE - Handle terminal resize events
< KEY_ALTHOME - horizontal scroll to the first column
< KEY_ALTEND horizontal scroll to the last column
< 'h', Ctrl('H'), KEY_LEFT, KEY_BACKSPACE - Horizontal scroll left by two thirds of the page width
< 'l', 'L', KEY_RIGHT - Horizontal scroll right by two thirds of the page width
'k', 'K', KEY_UP, Ctrl('K') - Scroll up one line
'j', 'J', KEY_DOWN, KEY_ENTER, SPACE - scroll down one line
'b', 'B', Ctrl('B'), KEY_PPAGE - Scroll up one page
'f', 'F', Ctrl('F'), KEY_NPAGE - scroll down one page
'g', KEY_HOME - Go to the beginning of the document
KEY_LL - Go to the end of the document
'!', Execute Shell Command from within C-Menu View
'+', Set Startup Command
'-', Change View Settings
'c' - Clear Screen at End of File
'i' - Ignore Case in Search
'p' - Set Prompt Type
'l' - Long Prompt
'n' - No Prompt
's' - Squeeze Multiple Blank Lines
't' - Set Tab Stop Columns
KEY_F(1), 'H' - Display Help
Pedantic reassignment of view pointer as the init->view pointer was was reassigned during view_display_help
':' - Set a Prompt String
'n' - Repeat Previous Search
'/' or '?' - Search Forward fromk top of page
'?' - Search Backward
'o' or 'O' - Open a File
'g' or 'G' - Go to the End of the Document
'H' or KEY_F(1) - Display Help Information
Pedantic reassignment of view pointer as the init->view pointer was was reassigned during view_display_help
'm' - Set a Mark at the Current Position
'M' - Go to a Mark
'N' - Close Current File and Open Next File
'p' or '' - Go to a Percent of the File
Ctrl('Z') - Send File to Print Queue with Notation
'P' or KEY_CATAB or KEY_PRINT - Print Current File
'P' or KEY_F(9) or ESC - Close Current File and Open Next
'q' or 'Q' or KEY_F(9) or ESC - Quit the Application
'v' - Open Current File in Editor
'w' - Write the current buffer to file
'V' - Display Version Information
Definition at line 121 of file view_engine.c.
References build_prompt(), CM_VERSION, cmd_line_prompt(), CT_VIEW, Ctrl, DEFAULTEDITOR, display_error(), em0, em1, em2, enter_file_spec(), full_screen_shell(), get_cmd_arg(), get_cmd_char(), go_to_eof(), go_to_line(), go_to_mark(), go_to_percent(), init, KEY_ALTEND, KEY_ALTHOME, lp(), MAXLEN, next_page(), Perror(), prev_regex_pattern, PT_LONG, PT_NONE, PT_SHORT, redisplay_page(), resize_page(), restore_wins(), scroll_down_n_lines(), scroll_up_n_lines(), search(), shell(), ssnprintf(), str_subc(), strnz__cat(), strnz__cpy(), tmp_str, view, view_display_help(), and write_view_buffer().
Referenced by view_file().
view_display_help()
void view_display_help (Init * init)
Display View Help File.
Parameters
init is the current initialization data structure.
Note
The current View context is set aside by assigning the view structure to "view_save" while the help file is displayed using a new, separate view structure.
The help file is specified by the VIEW_HELP_FILE macro can be set to a default help file path or overridden by the user through an environment variable.
After the help file is closed, the original view is restored and the page is redisplayed.
It may be necessary to reassign view after calling this function because the init->view pointer is temporarily set to nullptr during the help file display, and the original view is restored afterward.
The default screen size for help can be set in the code below. If set to 0, mview will determine reasonable maximal size based on the terminal dimensions.
The help file may contain Unicode characters and ANSI escape sequences for formatting, which will be properly handled and displayed by mview.
Definition at line 1778 of file view_engine.c.
References eargc, eargv, expand_tilde(), init, MAXARGS, MAXLEN, mview(), parse_opt_args(), strnz__cpy(), tmp_str, VIEW_HELP_FILE, and zero_opt_args().
Referenced by view_cmd_processor().
view_file()
int view_file (Init * init)
Start view.
Definition at line 84 of file view_engine.c.
References init, next_page(), view, view_cmd_processor(), and view_init_input().
Referenced by main(), and mview().
write_view_buffer()
int write_view_buffer (Init * init, bool f_strip_ansi)
Write buffer contents to files.
Parameters
init data structure
f_strip_ansi strip ANSI escape sequences
write the buffer
Definition at line 847 of file view_engine.c.
References display_error(), em0, em1, em2, get_next_line(), init, MAXLEN, PAD_COLS, ssnprintf(), strip_ansi(), strnlf(), strnz__cat(), strnz__cpy(), and view.
Referenced by view_cmd_processor().
Variable Documentation
dbgfp
FILE* dbgfp
Definition at line 48 of file view_engine.c.
err_msg
char err_msg[MAXLEN]
Definition at line 82 of file view_engine.c.
Referenced by ABEND(), and go_to_position().
prev_regex_pattern
char prev_regex_pattern[MAXLEN]
Definition at line 47 of file view_engine.c.
Referenced by view_cmd_processor().