C-Menu: src/include/cm.h File Reference
cm.h File Reference
Headder for C-Menu API library, libcm.so.
#include "version.h"
#include <ncursesw/ncurses.h>
#include <signal.h>
#include <stddef.h>
#include <stdlib.h>
Data Structures
struct ChyronKey
struct Chyron
struct RGB
Represents an RGB color with 8-bit components.
struct ColorPair
struct Opts
Table elements for options.
struct Arg
The Arg structure represents a string argument with a pointer to the string and its allocated length.
struct Argv
The Argv structure represents an argument vector, which is an array of Arg structures, along with the number of allocated elements in the array.
struct String
The String structure represents a string object with a pointer to the string and its allocated length.
struct WCStr
wide character string object with a pointer to the wide character string and its allocated length
struct CCStr
complex character objectl with a pointer to the complex character string and its allocated length
struct SIO
The SIO structure encapsulates various aspects of the terminal's state and configuration, including color management, file pointers, and terminal device information.
Macros
#define _XOPEN_SOURCE_EXTENDED 1
#define NCURSES_WIDECHAR 1
#define nullptr NULL
#define MAXLEN 256
#define MAXARGS 64
#define SCR_COLS 1024
#define MAX_DEPTH 3
#define W_BOX 0x40
#define COLOR_LEN 8
#define DEFAULTSHELL "/bin/bash"
#define S_WCOK 0x1000
#define S_QUIET 0x2000
#define __end_pgm
This macro defines the function, end_pgm, that is responsible for cleaning up the terminal state and exiting the program.
#define __atexit
This macro registers the end_pgm function to be called when the program exits.
#define CHYRON_KEY_MAXLEN 64
#define CHYRON_KEYS 20
#define FG_COLOR 2
#define BG_COLOR 0
#define BO_COLOR 1
#define KEY_ALTF0 0x138
#define KEY_ALTF(n)
#define XTERM_256COLOR
#define KEY_ALTINS 0x223
#define KEY_ALTHOME 0x21e
#define KEY_ALTPGUP 0x232
#define KEY_ALTDEL 0x20e
#define KEY_ALTEND 0x219
#define KEY_ALTPGDN 0x22d
#define KEY_ALTUP 0x23d
#define KEY_ALTLEFT 0x228
#define KEY_ALTDOWN 0x214
#define KEY_ALTRIGHT 0x237
#define BW_HO L'\x2500'
#define BW_VE L'\x2502'
#define BW_TL L'\x250C'
#define BW_TR L'\x2510'
#define BW_BL L'\x2514'
#define BW_BR L'\x2518'
#define BW_RTL L'\x256d'
#define BW_RTR L'\x256e'
#define BW_RBL L'\x2570'
#define BW_RBR L'\x256f'
#define BW_LT L'\x251C'
#define BW_TT L'\x252C'
#define BW_RT L'\x2524'
#define BW_CR L'\x253C'
#define BW_BT L'\x2534'
#define BW_SP L'\x20'
#define MAXWIN 30
#define to_uppercase(c)
#define to_lowercase(c)
#define to_uppercase(c)
Typedefs
typedef unsigned char uchar
Enumerations
enum LFFlags {
LF_ALL = 1 , LF_ICASE = 2 , LF_FILES = 4 , LF_DIRS = 8 ,
LF_EXCLUDE = 16 , LF_REGEX = 32
}
Functions
int xwgetch (WINDOW *, Chyron *)
Wrapper for wgetch that handles signals and mouse events.
void dump_opts ()
dump all options
void dump_opts_by_use (char *, char *)
dump options by use mask
bool capture_shell_tioctl ()
capture_shell_tioctl() - capture shell terminal settings
bool restore_shell_tioctl ()
restore_shell_tioctl() - restore shell terminal settings
bool capture_curses_tioctl ()
capture_curses_tioctl() - capture curses terminal settings
bool restore_curses_tioctl ()
restore_curses_tioctl() - restore curses terminal settings
bool mk_raw_tioctl (struct termios *)
mk_raw_tioctl() - set terminal to raw mode
bool set_sane_tioctl (struct termios *)
set_sane_tioctl() - set terminal to sane settings for C-MENU
int win_new (int, int, int, int, char *, int)
Create a new window with optional box and title.
void win_redraw (WINDOW *)
Redraw the specified window.
void win_resize (int, int, char *)
Resize the current window and its box, and update the title.
void signal_handler (int)
Signal handler for interrupt signals.
bool handle_signal (sig_atomic_t)
void sig_prog_mode ()
Set up signal handlers for interrupt signals.
void sig_dfl_mode ()
Set signal handlers to default behavior.
bool mk_dir (char *dir)
If directory doesn't exist, make it.
int segmentation_fault ()
Function to intentionally cause a segmentation fault for testing purposes.
void destroy_curses ()
Gracefully shut down NCurses and restore terminal settings.
void sig_shell_mode ()
char di_getch ()
sget single character from terminal in raw mode
int enter_option ()
WINDOW * win_del ()
Delete the current window and its associated box window.
void destroy_win (WINDOW *)
void destroy_box (WINDOW *)
void restore_wins ()
Restore all windows after a screen resize.
void cbox (WINDOW *)
Draw a box around the specified window.
void win_init_attrs (int, int, int)
Initialize window attributes.
void win_Toggle_Attrs ()
void mvwaddstr_fill (WINDOW *, int, int, char *, int)
For lines shorter than their display area, fill the rest with spaces.
int display_curses_keys ()
Display Curses Keys Responds to curses keys and mouse events, displaying the key code and description.
void init_stdscr ()
void curskeys (WINDOW *)
void mouse_getch (int *, int *, int *, int *)
void w_mouse_getch (WINDOW *, int *, int *, int *, int *)
int a_toi (char *, bool *)
a safer alternative to atoi() for converting ASCII strings to integers.
bool chrep (char *, char, char)
Replaces all occurrences of old_chr in s with new_chr in place.
char * rep_substring (const char *, const char *, const char *)
Replace all occurrences of "tgt_s" in "org_s" with "rep_s".
size_t strip_ansi (char *, char *)
Strips ANSI SGR escape sequences (ending in 'm') from string s to d.
bool strip_quotes (char *)
removes leading and trailing double quotes if present
bool stripz_quotes (char *)
removes leading and trailing double quotes if present
int str_to_args (char **, char *, int)
Converts a string into an array of argument strings.
bool str_to_bool (const char *)
Converts String to boolean true or false.
bool str_to_lower (char *)
Converts a string to lowercase.
bool str_to_upper (char *)
Converts a string to uppercase.
bool strnfill (char *, char, int)
Fills string s with character c n.
bool str_subc (char *, char *, char, char *, int)
Replaces "ReplaceChr" in "s" with "Withstr" in "d" won't copy more than "l" bytes to "d" Replaces all occurrences of a character in a string with another string, copying the result to a destination buffer. It ensures that the total length of the resulting string does not exceed the specified limit, and that the result is null-terminated. This function is useful for simple string substitutions where you want to replace a single character with a longer string, such as replacing spaces with underscores or tabs with spaces.
size_t strnz (char *, size_t)
terminates string at New Line, Carriage Return, or max_len
size_t strnlf (char *, size_t)
terminates string with line feed
char * strnz_dup (char *, size_t)
Allocates memory for and duplicates string s up to length l or until line feed or carriage return.
size_t ssnprintf (char *, size_t, const char *,...)
ssnprintf was designed to be a safer alternative to snprintf.
size_t strnz__cpy (char *, const char *, size_t)
safer alternative to strncpy
size_t strnz__cat (char *, const char *, size_t)
safer alternative to strncat
double str_to_double (char *)
converts string to double
size_t string_cpy (String *, const String *)
Copy src String to dest String, allocating additional memory for dest String if necessary.
size_t string_cat (String *, const String *)
Concatenates src String to dest String, allocating additional memory for dest String if necessary.
size_t string_ncat (String *, const String *, size_t)
Concatenates up to n characters from src String to dest String, allocating additional memory for dest String if necessary.
size_t string_ncpy (String *, const String *, size_t)
copies up to n characters from src String to dest String, allocating additional memory for dest String if necessary
size_t trim (char *)
Trims leading and trailing spaces from string s in place.
size_t rtrim (char *)
Trims trailing spaces from string s in place.
String to_string (const char *)
Convert C string to String struct.
String mk_string (size_t)
Create a String struct with a dynamically allocated string.
String free_string (String)
Free the dynamically allocated String.
void apply_gamma (RGB *)
Apply gamma correction to RGB color.
int get_clr_pair (int, int)
Get color pair index for foreground and background colors.
int clr_name_to_idx (char *)
Get color index from color name.
int rgb_to_xterm256_idx (RGB *)
Convert RGB color to XTerm 256 color index.
bool init_clr_palette (SIO *)
Initialize color palette based on SIO settings.
bool open_curses (SIO *)
Initialize NCurses and color settings.
int rgb_clr_to_cube (int)
int rgb_to_curses_clr (RGB *)
Get color index for RGB color.
RGB xterm256_idx_to_rgb (int)
Convert XTerm 256 color index to RGB color.
int fork_exec (char **)
Fork and exec a command.
int full_screen_fork_exec (char **)
Execute a command in full screen mode.
int full_screen_shell (char *)
Execute a shell command in full screen mode.
int shell (char *)
Execute a shell command.
void get_rfc3339_s (char *, size_t)
int open_log (char *)
void write_log (char *)
void compile_chyron (Chyron *)
construct the chyron string from the chyron structure
int get_chyron_key (Chyron *, int)
Get keycode from chyron.
bool is_set_chyron_key (Chyron *, int)
Check if function key label is set.
void set_chyron_key (Chyron *, int, char *, int)
Set chyron key.
void unset_chyron_key (Chyron *, int)
Unset chyron key.
Chyron * new_chyron ()
Create and initialize Chyron structure.
Chyron * destroy_chyron (Chyron *chyron)
Destroy Chyron structure.
void abend (int, char *)
Abnormal program termination.
void display_argv_error_msg (char *, char **)
int display_error (char *, char *, char *, char *)
Display an error message window or print to stderr.
int display_ok_message (char *)
int Perror (char *)
Display a simple error message window or print to stderr.
void user_end ()
Program terminated by user.
bool lf_find (const char *, const char *, const char *, int, int)
Find files in a directory matching a regular expression.
size_t canonicalize_file_spec (char *)
Removes quotes and trims at first space.
bool construct_file_spec (char *, char *, char *, char *, char *, int)
bool file_spec_path (char *, char *)
extracts the path component of a file specification
bool file_spec_name (char *, char *)
extracts the file name component of a file specification
bool dir_name (char *, char *)
Returns the directory name of a file specification.
bool base_name (char *, char *)
Returns the base name of a file specification.
bool expand_tilde (char *, int)
Replace Leading Tilde With Home Directory.
bool locate_file_in_path (char *, char *)
Locates a file in the system PATH.
bool normalize_file_spec (char *)
replace backslashes with forward lashes
bool trim_ext (char *, char *)
trims the file extension from "filename" and copies the result to "buf"
bool trim_path (char *)
Trims trailing spaces and slashes from directory path in place.
bool verify_file (char *, int)
Verifies that the file specified by "in_spec" exists and is accessible with the permissions specified by "imode".
bool verify_file_q (char *, int)
bool verify_dir (char *, int)
Verifies that the directory specified by "spec" exists and is accessible with the permissions specified by "imode".
bool verify_dir_q (char *, int)
bool verify_spec_arg (char *, char *, char *, char *, int)
Verify file specification argument.
Variables
int click_y
int click_x
bool f_debug
unsigned int cmd_key
int cp_default
int cp_norm
int cp_box
int cp_bold
int cp_title
int cp_highlight
int cp_reverse
int clr_idx
int clr_cnt
int clr_pair_idx
int clr_pair_cnt
char const colors_text [][10]
struct termios shell_tioctl curses_tioctl
struct termios shell_in_tioctl curses_in_tioctl
struct termios shell_out_tioctl curses_out_tioctl
struct termios shell_err_tioctl curses_err_tioctl
bool f_have_shell_tioctl
bool f_have_curses_tioctl
bool f_curses_open
bool f_restore_screen
volatile sig_atomic_t sig_received
cchar_t CCC_NORM
cchar_t CCC_BOX
cchar_t CCC_REVERSE
const wchar_t bw_ho
const wchar_t bw_ve
const wchar_t bw_tl
const wchar_t bw_tr
const wchar_t bw_bl
const wchar_t bw_br
const wchar_t bw_lt
const wchar_t bw_tt
const wchar_t bw_rt
const wchar_t bw_cr
const wchar_t bw_bt
int n_lines
int n_cols
int lines
int cols
int begx
int begy
WINDOW * win
WINDOW * win_win [30]
WINDOW * win_box [30]
int win_attr
int win_attr_odd
int win_attr_even
int win_ptr
int mlines
int mcols
int mbegy
int mbegx
int mg_action
int mg_col
int mg_line
int eargc
char earg_str [256]
char * eargv [64]
int tty_fd
int dbgfd
int src_line
char * src_name
char fn [256]
char em0 [256]
char em1 [256]
char em2 [256]
char em3 [256]
int exit_code
char errmsg []
Detailed Description
Headder for C-Menu API library, libcm.so.
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file cm.h.
Macro Definition Documentation
__atexit
#define __atexit
Value:
{                                                                          \
    int rc;                                                                \
    rc = atexit(end_pgm);                                                  \
    if (rc != 0) {                                                         \
        fprintf(stderr, "\nCannot set exit function\n");                   \
        exit(EXIT_FAILURE);                                                \
    }                                                                      \
}
This macro registers the end_pgm function to be called when the program exits.
Note
It checks the return value of atexit() to ensure that the registration was successful, and if not, it prints an error message and exits with a failure status. Programs using libcm should call __atexit in their main function to ensure that the end_pgm function is registered to be called on program exit. This will help ensure that the terminal is properly restored to its original state, even if the program encounters an error or is terminated unexpectedly.
Definition at line 79 of file cm.h.
#define __atexit                                                               \
    {                                                                          \
        int rc;                                                                \
        rc = atexit(end_pgm);                                                  \
        if (rc != 0) {                                                         \
            fprintf(stderr, "\nCannot set exit function\n");                   \
            exit(EXIT_FAILURE);                                                \
        }                                                                      \
    }
Referenced by main().
__end_pgm
#define __end_pgm
Value:
static void end_pgm(void) {                                                \
    win_del();                                                             \
    destroy_curses();                                                      \
    restore_shell_tioctl();                                                \
    sig_dfl_mode();                                                        \
    exit(EXIT_FAILURE);                                                    \
}
This macro defines the function, end_pgm, that is responsible for cleaning up the terminal state and exiting the program.
Note
This function is typically registered to be called when the program exits, ensuring that the terminal is properly restored to its original state, even if the program encounters an error or is terminated unexpectedly. The end_pgm function performs the following actions:
It calls win_del() to delete any windows that may have been created during the program's execution.
It calls destroy_curses() to clean up the ncurses library and restore the terminal to its normal state.
It calls restore_shell_tioctl() to restore the terminal's input/output settings to their original state.
Finally, it calls exit(EXIT_FAILURE) to terminate the program with a failure status, indicating that the program has encountered an error or is exiting due to an unexpected condition. By defining this function and registering it to be called on program exit, you can help ensure that the terminal is properly cleaned up and restored, preventing any issues with the terminal state after the program has exited.
Definition at line 62 of file cm.h.
#define __end_pgm                                                              \
    static void end_pgm(void) {                                                \
        win_del();                                                             \
        destroy_curses();                                                      \
        restore_shell_tioctl();                                                \
        sig_dfl_mode();                                                        \
        exit(EXIT_FAILURE);                                                    \
    }
_XOPEN_SOURCE_EXTENDED
#define _XOPEN_SOURCE_EXTENDED 1
Enable wide character support
Definition at line 13 of file cm.h.
BG_COLOR
#define BG_COLOR 0
default background color
Definition at line 147 of file cm.h.
Referenced by mapp_initialization().
BO_COLOR
#define BO_COLOR 1
default bold foreground color
Definition at line 148 of file cm.h.
Referenced by mapp_initialization().
BW_BL
#define BW_BL L'\x2514'
bottom left
Definition at line 307 of file cm.h.
BW_BR
#define BW_BR L'\x2518'
bottom right
Definition at line 308 of file cm.h.
BW_BT
#define BW_BT L'\x2534'
bottom tee
Definition at line 317 of file cm.h.
Referenced by main().
BW_CR
#define BW_CR L'\x253C'
cross
Definition at line 316 of file cm.h.
Referenced by main().
BW_HO
#define BW_HO L'\x2500'
UNICODE BOX DRAWING SYMBOLS horizontal line
Definition at line 303 of file cm.h.
Referenced by main().
BW_LT
#define BW_LT L'\x251C'
left tee
Definition at line 313 of file cm.h.
Referenced by main().
BW_RBL
#define BW_RBL L'\x2570'
rounded bottom left
Definition at line 311 of file cm.h.
Referenced by main().
BW_RBR
#define BW_RBR L'\x256f'
rounded bottom right
Definition at line 312 of file cm.h.
Referenced by main().
BW_RT
#define BW_RT L'\x2524'
right tee
Definition at line 315 of file cm.h.
Referenced by main().
BW_RTL
#define BW_RTL L'\x256d'
rounded left tee
Definition at line 309 of file cm.h.
Referenced by main().
BW_RTR
#define BW_RTR L'\x256e'
rounded right tee
Definition at line 310 of file cm.h.
Referenced by main().
BW_SP
#define BW_SP L'\x20'
space
Definition at line 318 of file cm.h.
BW_TL
#define BW_TL L'\x250C'
top left
Definition at line 305 of file cm.h.
BW_TR
#define BW_TR L'\x2510'
top right
Definition at line 306 of file cm.h.
BW_TT
#define BW_TT L'\x252C'
top tee
Definition at line 314 of file cm.h.
Referenced by main().
BW_VE
#define BW_VE L'\x2502'
vertical line
Definition at line 304 of file cm.h.
Referenced by main().
CHYRON_KEY_MAXLEN
#define CHYRON_KEY_MAXLEN 64
maximum length of the command text for a key \ binding in the chyron
Definition at line 112 of file cm.h.
#define CHYRON_KEY_MAXLEN                                                      \
    64
Referenced by set_chyron_key().
CHYRON_KEYS
#define CHYRON_KEYS 20
maximum number of key bindings for the chyron
Definition at line 115 of file cm.h.
Referenced by compile_chyron(), destroy_chyron(), and new_chyron().
COLOR_LEN
#define COLOR_LEN 8
length of color code strings
Definition at line 40 of file cm.h.
Referenced by parse_config().
DEFAULTSHELL
#define DEFAULTSHELL "/bin/bash"
Definition at line 41 of file cm.h.
Referenced by shell().
FG_COLOR
#define FG_COLOR 2
default foreground color
Definition at line 146 of file cm.h.
Referenced by mapp_initialization().
KEY_ALTDEL
#define KEY_ALTDEL 0x20e
Definition at line 282 of file cm.h.
Referenced by display_curses_keys().
KEY_ALTDOWN
#define KEY_ALTDOWN 0x214
Definition at line 287 of file cm.h.
Referenced by display_curses_keys().
KEY_ALTEND
#define KEY_ALTEND 0x219
Definition at line 283 of file cm.h.
Referenced by display_curses_keys(), and view_cmd_processor().
KEY_ALTF
#define KEY_ALTF (n)
Value:
define alt function keys
Definition at line 226 of file cm.h.
Referenced by display_curses_keys(), and menu_cmd_processor().
KEY_ALTF0
#define KEY_ALTF0 0x138
Definition at line 225 of file cm.h.
KEY_ALTHOME
#define KEY_ALTHOME 0x21e
Definition at line 280 of file cm.h.
Referenced by display_curses_keys(), and view_cmd_processor().
KEY_ALTINS
#define KEY_ALTINS 0x223
EXTENDED NCURSES KEYS
Key code bindings are customarily defined in terminfo. xterm-256color tends to be the most complete, and indeed, it seems to work with Ghostty, Kitty, and Alacritty. If you want to use the altkey bindings, you may need to set your terminal's TERM environment variable to xterm-256color. Here's why:
Ghostty, Kitty, and Alacritty all come with their own terminfo files:
Ghostty with xterm-ghostty, Kitty with xterm-kitty, and Alacritty with alacritty
None of the three produced the correct extended altkey bindings when paired with the terminfo provided in their distribution, yet all three worked with xterm-256color.
The extended altkeys were not defined in any of the terminfo files, not even xterm-256color. Yet, xterm-256color produced consistent keycode bindings with all three emulators. The standard key bindings, ins, delete, up, down arrows, etc., were the same for all three terminfos, and all three emulators produced the correct key bindings for those keys.
The fact that xterm-256color produced consistent keycode bindings for the altkeys, while the other three terminfos did not, is likely due to the fact that xterm-256color is more widely used and has better support for extended key bindings, even if they are not explicitly defined in the terminfo file. It's possible that xterm-256color has some default behavior or fallback mechanism that allows it to recognize and produce key codes for the altkeys, while the other terminfos do not have such a mechanism in place. This could explain why xterm-256color produced consistent keycode bindings for the altkeys across all three emulators, while the other terminfos did not.
Definition at line 279 of file cm.h.
Referenced by display_curses_keys().
KEY_ALTLEFT
#define KEY_ALTLEFT 0x228
Definition at line 286 of file cm.h.
Referenced by display_curses_keys().
KEY_ALTPGDN
#define KEY_ALTPGDN 0x22d
Definition at line 284 of file cm.h.
Referenced by display_curses_keys().
KEY_ALTPGUP
#define KEY_ALTPGUP 0x232
Definition at line 281 of file cm.h.
Referenced by display_curses_keys().
KEY_ALTRIGHT
#define KEY_ALTRIGHT 0x237
Definition at line 288 of file cm.h.
Referenced by display_curses_keys().
KEY_ALTUP
#define KEY_ALTUP 0x23d
Definition at line 285 of file cm.h.
Referenced by display_curses_keys().
MAX_DEPTH
#define MAX_DEPTH 3
maximum depth for recursive file searching
Definition at line 28 of file cm.h.
MAXARGS
#define MAXARGS 64
maximum number of arguments
Definition at line 26 of file cm.h.
Referenced by exec_objects(), form_calculate(), init_pick(), new_init(), shell(), view_display_help(), and view_init_input().
MAXLEN
#define MAXLEN 256
maximum length for strings and buffers
Definition at line 25 of file cm.h.
MAXWIN
#define MAXWIN 30
maximum number of windows that can be created
Definition at line 348 of file cm.h.
Referenced by enter_option(), and win_new().
NCURSES_WIDECHAR
#define NCURSES_WIDECHAR 1
Enable wide character support
Definition at line 14 of file cm.h.
nullptr
#define nullptr NULL
Definition at line 22 of file cm.h.
S_QUIET
#define S_QUIET 0x2000
quiet mode flag for file validation
Definition at line 43 of file cm.h.
Referenced by enter_file_spec(), init_form_files(), init_pick_files(), mk_dir(), verify_dir(), verify_file(), and verify_spec_arg().
S_WCOK
#define S_WCOK 0x1000
write or create permitted
Definition at line 42 of file cm.h.
Referenced by enter_file_spec(), mk_dir(), verify_dir(), verify_file(), and verify_spec_arg().
SCR_COLS
#define SCR_COLS 1024
maximum number of columns in the terminal screen
Definition at line 27 of file cm.h.
to_lowercase
#define to_lowercase (c)
Value:
to_lowercase(c) - convert an uppercase letter to lowercase
Definition at line 405 of file cm.h.
to_uppercase [1/2]
#define to_uppercase (c)
Value:
to_uppercase(c) - convert a lowercase letter to uppercase
simple macro to convert a character to uppercase
Definition at line 401 of file cm.h.
to_uppercase [2/2]
#define to_uppercase (c)
Value:
to_uppercase(c) - convert a lowercase letter to uppercase
simple macro to convert a character to uppercase
Definition at line 401 of file cm.h.
W_BOX
#define W_BOX 0x40
box window flag for win_new()
Definition at line 39 of file cm.h.
Referenced by win_new().
XTERM_256COLOR
#define XTERM_256COLOR
use xterm-256color terminfo for altkey bindings
Definition at line 227 of file cm.h.
Typedef Documentation
uchar
typedef unsigned char uchar
Definition at line 349 of file cm.h.
Enumeration Type Documentation
LFFlags
enum LFFlags
Enumerator
LF_ALL 1
List all files including hidden files
LF_ICASE 2
Ignore case in search
LF_FILES 4
List files
LF_DIRS 8
List directories
LF_EXCLUDE 16
Exclude files matching regular expression
LF_REGEX 32
Exclude files matching regular expression
Definition at line 30 of file cm.h.
    LF_ICASE = 2,
    LF_FILES = 4,
    LF_DIRS = 8,
    LF_EXCLUDE = 16,
    LF_REGEX = 32,
};
Function Documentation
a_toi()
int a_toi (char * s, bool * a_toi_error) extern
a safer alternative to atoi() for converting ASCII strings to integers.
Parameters
s is the input string
a_toi_error is a pointer to a boolean that will be set to true if an error occurs during conversion, or false if the conversion is successful.
Note
accepts positive integers only.
sets a_toi_error to (-1) on error
Returns
converted integer value, or -1 if an error occurs
Definition at line 438 of file futil.c.
{
    int rc = -1;
    *a_toi_error = false;
    errno = 0;
    if (s && *s != 0)
        rc = (int)strtol(s, nullptr, 10);
    if (rc < 0 || errno) {
        rc = -1;
        *a_toi_error = true;
    }
    return rc;
}
abend()
void abend (int ec, char * s) extern
Abnormal program termination.
Parameters
ec Exit code
s Error message
Definition at line 1058 of file dwin.c.
{
    destroy_curses();
    restore_shell_tioctl();
    sig_dfl_mode();
    fprintf(stderr, "\n\nABEND: %s (code: %d)\n", s, ec);
    exit(EXIT_FAILURE);
}
References destroy_curses(), restore_shell_tioctl(), and sig_dfl_mode().
Referenced by display_error(), form_parse_desc(), init_menu_files(), init_pick(), init_view_full_screen(), main(), mapp_initialization(), menu_cmd_processor(), new_chyron(), new_form(), new_init(), new_menu(), new_pick(), new_view(), open_curses(), parse_menu_description(), Perror(), sig_prog_mode(), and view_init_input().
apply_gamma()
void apply_gamma (RGB * rgb) extern
Apply gamma correction to RGB color.
Parameters
rgb Pointer to RGB color
Note
This function modifies the RGB color in place. It applies gamma correction to the RGB color based on the gamma values set in the SIO struct. If the color is a shade of gray, it applies the gray gamma correction. Otherwise, it applies the individual red, green, and blue gamma corrections.
Definition at line 507 of file dwin.c.
{
    if (rgb->r == rgb->g && rgb->r == rgb->b) {
        if (GRAY_GAMMA > 0.0f && GRAY_GAMMA != 1.0f) {
            rgb->r = (int)(pow((rgb->r / 255.0f), 1.0f / GRAY_GAMMA) * 255.0f);
            rgb->g = rgb->r;
            rgb->b = rgb->r;
        }
        return;
    }
    if (rgb->r != 0 && RED_GAMMA > 0.0f && RED_GAMMA != 1.0f)
        rgb->r = (int)(pow((rgb->r / 255.0f), 1.0f / RED_GAMMA) * 255.0f);
    if (rgb->g != 0 && GREEN_GAMMA > 0.0f && GREEN_GAMMA != 1.0f)
        rgb->g = (int)(pow((rgb->g / 255.0f), 1.0f / GREEN_GAMMA) * 255.0f);
    if (rgb->b != 0 && BLUE_GAMMA > 0.0f && BLUE_GAMMA != 1.0f)
        rgb->b = (int)(pow((rgb->b / 255.0f), 1.0f / BLUE_GAMMA) * 255.0f);
}
References RGB::b, BLUE_GAMMA, RGB::g, GRAY_GAMMA, GREEN_GAMMA, RGB::r, and RED_GAMMA.
Referenced by init_hex_clr(), and rgb_to_curses_clr().
base_name()
bool base_name (char * buf, char * path) extern
Returns the base name of a file specification.
Parameters
buf - buffer to receive result
path - file specification
Returns
true if successful
Note
The caller is responsible for ensuring that "buf" has enough space to receive the result.
Definition at line 699 of file futil.c.
{
    if (!path || !*path || !buf)
        return false;
    char *s = path;
    char *d = buf;
    *d = '\0';
    while (*s) {
        if (*s == '/' || *s == '\\') {
            d = buf;
        } else {
            *d++ = *s;
        }
        s++;
    }
    *d = '\0';
    if (d == buf)
        return false;
    return true;
Referenced by build_prompt(), exec_objects(), form_calculate(), init_form_files(), init_pick_files(), parse_opt_args(), and view_init_input().
canonicalize_file_spec()
size_t canonicalize_file_spec (char * spec) extern
Removes quotes and trims at first space.
Parameters
spec - file specification to canonicalize
Returns
length of resulting string
Definition at line 1083 of file futil.c.
{
    if (spec == nullptr || *spec == '\0')
        return 0;
    char tmp_s[MAXLEN];
    char *s;
    s = spec;
    char *d;
    d = tmp_s;
    int l = 0;
    while (*s != '\0') {
        if (*s == ' ')
            break;
        if (*s == '\"' || *s == '\'') {
            s++;
            continue;
            ;
        }
        *d++ = *s++;
        l++;
    }
    *d = '\0';
    strnz__cpy(spec, tmp_s, MAXLEN - 1);
    l = strlen(spec);
    return l;
References MAXLEN, and strnz__cpy().
Referenced by locate_file_in_path(), verify_file(), and verify_spec_arg().
capture_curses_tioctl()
bool capture_curses_tioctl () extern
capture_curses_tioctl() - capture curses terminal settings
Returns
- true on success
Note
- captures terminal settings for stdin, stdout, and stderr
Definition at line 60 of file scriou.c.
{
    if (f_have_curses_tioctl)
        return true;
    tcgetattr(0, &curses_tioctl);
    f_have_curses_tioctl = true;
    return true;
}
References curses_tioctl, and f_have_curses_tioctl.
Referenced by fork_exec(), and main().
capture_shell_tioctl()
bool capture_shell_tioctl () extern
capture_shell_tioctl() - capture shell terminal settings
Returns
- true on success
Note
- captures terminal settings for stdin, stdout, and stderr
Examples
/usr/local/src/cmenu/src/enterchr.c, and /usr/local/src/cmenu/src/enterstr.c.
Definition at line 40 of file scriou.c.
{
    if (f_have_shell_tioctl)
        return true;
    tcgetattr(0, &shell_tioctl);
    tcgetattr(2, &shell_err_tioctl);
    f_have_shell_tioctl = true;
    return true;
}
References f_have_shell_tioctl, and shell_tioctl.
Referenced by main().
cbox()
void cbox (WINDOW * box) extern
Draw a box around the specified window.
Parameters
box Pointer to the window to draw the box around
Note
This function uses NCurses functions to draw a box around the specified window. It adds the appropriate characters for the corners and edges of the box based on the current character set. Use this function when you want to visually separate a window from the rest of the screen with a border.
Definition at line 818 of file dwin.c.
                       {
    int x, y;
    int maxx;
    int maxy;
    maxx = getmaxx(box);
    maxx--;
    mvwaddnwstr(box, 0, 0, &bw_tl, 1);
    for (x = 1; x < maxx; x++)
        waddnwstr(box, &bw_ho, 1);
    waddnwstr(box, &bw_tr, 1);
    maxy = getmaxy(box);
    maxy--;
    for (y = 1; y < maxy; y++) {
        mvwaddnwstr(box, y, 0, &bw_ve, 1);
        mvwaddnwstr(box, y, maxx, &bw_ve, 1);
    }
    mvwaddnwstr(box, maxy, 0, &bw_bl, 1);
    for (x = 1; x < maxx; x++)
        waddnwstr(box, &bw_ho, 1);
    waddnwstr(box, &bw_br, 1);
}
References bw_bl, bw_br, bw_ho, bw_tl, bw_tr, and bw_ve.
Referenced by win_new(), and win_resize().
chrep()
bool chrep (char * s, char old_chr, char new_chr) extern
Replaces all occurrences of old_chr in s with new_chr in place.
Parameters
s - string to modify
old_chr - character to replace
new_chr - character to insert
Returns
true if successful or false if string s is null
Definition at line 420 of file futil.c.
{
    if (s == nullptr)
        return false;
    while (*s != '\0') {
        if (*s == old_chr)
            *s = new_chr;
        s++;
    }
    return true;
}
Referenced by parse_menu_description().
clr_name_to_idx()
int clr_name_to_idx (char * s) extern
Get color index from color name.
Parameters
s Color name
Returns
Color index or -1 if not found
Definition at line 999 of file dwin.c.
{
    int i = 0;
    int n = 16;
    str_to_lower(s);
    while (i < n) {
        if (!strcmp(colors_text[i], s))
            break;
        i++;
    }
    if (i >= n)
        return (-1);
    return (i);
}
References colors_text, and str_to_lower().
Referenced by parse_config(), and parse_opt_args().
compile_chyron()
void compile_chyron (Chyron * chyron) extern
construct the chyron string from the chyron structure
Parameters
chyron
The chyron string is constructed by concatenating the labels of the set keys, separated by " | ". The end_pos values for each key are set to determine the zones for mouse clicks. When a mouse click occurs, the get_chyron_key function uses the end_pos values to determine which key was clicked based on the X position of the click.
Definition at line 252 of file dwin.c.
{
    int end_pos = 0;
    int i = 0;
    chyron->s[0] = '\0';
    chyron->l = 0;
    while (i < CHYRON_KEYS) {
        if (chyron->key[i]->text[0] == '\0') {
            i++;
            continue;
        }
        if (end_pos == 0)
            strnz__cat(chyron->s, " ", MAXLEN - 1);
        else
            strnz__cat(chyron->s, " | ", MAXLEN - 1);
        strnz__cat(chyron->s, chyron->key[i]->text, MAXLEN - 1);
        end_pos = strlen(chyron->s) + 1;
        chyron->key[i]->end_pos = end_pos;
        i++;
    }
    if (end_pos > 0)
        chyron->l = strnz__cat(chyron->s, " ", MAXLEN - 1);
}
References CHYRON_KEYS, ChyronKey::end_pos, Chyron::key, Chyron::l, MAXLEN, Chyron::s, strnz__cat(), and ChyronKey::text.
Referenced by display_error(), form_accept_field(), form_display_chyron(), form_display_fields(), Perror(), and pick_engine().
construct_file_spec()
bool construct_file_spec (char * , char * , char * , char * , char * , int) extern
curskeys()
void curskeys (WINDOW *) extern
destroy_box()
void destroy_box (WINDOW *) extern
destroy_chyron()
Chyron * destroy_chyron (Chyron * chyron) extern
Destroy Chyron structure.
Parameters
chyron pointer to Chyron structure
Returns
nullptr
Definition at line 192 of file dwin.c.
{
    int i;
    if (!chyron)
        return nullptr;
    for (i = 0; i < CHYRON_KEYS; i++) {
        if (chyron->key[i])
            free(chyron->key[i]);
        chyron->key[i] = nullptr;
    }
    free(chyron);
    chyron = nullptr;
    return chyron;
}
References CHYRON_KEYS, and Chyron::key.
Referenced by display_error(), and Perror().
destroy_curses()
void destroy_curses () extern
Gracefully shut down NCurses and restore terminal settings.
Note
This function should be called before exiting the program to ensure that the terminal is left in a usable state. It checks if NCurses was initialized and, if so, it clears the screen, refreshes it, and ends the NCurses session. It also restores the original terminal settings using restore_shell_tioctl and resets signal handlers to their default state with sig_dfl_mode.
Definition at line 609 of file dwin.c.
                      {
    if (f_curses_open) {
        wclear(stdscr);
        wrefresh(stdscr);
        endwin();
        f_curses_open = false;
    }
    restore_shell_tioctl();
    sig_dfl_mode();
    return;
}
References f_curses_open, restore_shell_tioctl(), and sig_dfl_mode().
Referenced by abend(), main(), open_curses(), and user_end().
destroy_win()
void destroy_win (WINDOW *) extern
di_getch()
char di_getch () extern
sget single character from terminal in raw mode
Returns
- the character read from terminal
Note
restores terminal settings
Definition at line 122 of file scriou.c.
                {
    struct termios org_tioctl, new_tioctl;
    char buf;
    if (tcgetattr(2, &org_tioctl) == -1) {
        fprintf(stderr, "\ndi_getch: tcgetattr failed\n");
        return (0);
    }
    new_tioctl = org_tioctl;
    new_tioctl.c_lflag &= ~(ECHO | ICANON);
    new_tioctl.c_cc[VMIN] = 1;
    new_tioctl.c_cc[VTIME] = 0;
    tcsetattr(2, TCSAFLUSH, &new_tioctl);
    read(2, &buf, 1);
    tcsetattr(2, TCSAFLUSH, &org_tioctl);
    return (buf);
}
Referenced by nf_error(), and usage().
dir_name()
bool dir_name (char * buf, char * path) extern
Returns the directory name of a file specification.
Parameters
buf - buffer to receive result
path - file specification
Returns
true if successful
Note
The caller is responsible for ensuring that "buf" has enough space to receive the result.
Definition at line 724 of file futil.c.
{
    if (!path || !*path || !buf)
        return false;
    char tmp_str[MAXLEN];
    strnz__cpy(tmp_str, path, MAXLEN);
    char *s = tmp_str;
    while (*s++)
        ;
    while (tmp_str < --s) {
        if (*s == '/' || *s == '\\') {
            *s = '\0';
            break;
        }
    }
    while (tmp_str < --s && (*s == '/' || *s == '\\'))
        *s = '\0';
    char *d = buf;
    *d = '\0';
    s = tmp_str;
    while (*s) {
        *d++ = *s++;
    }
    *d = '\0';
    if (d == buf)
        return false;
    return true;
References MAXLEN, strnz__cpy(), and tmp_str.
display_argv_error_msg()
void display_argv_error_msg (char * , char **) extern
display_curses_keys()
int display_curses_keys () extern
Display Curses Keys Responds to curses keys and mouse events, displaying the key code and description.
Returns
0 on success, non-zero on failure
Definition at line 23 of file curskeys.c.
{
    WINDOW *win;
    WINDOW *box;
    char Title[] = "TEST CURSES KEYS";
    int lines = 10;
    int cols = 55;
    char kstr[KSTRLEN];
    unsigned int c;
    char action[MAXLEN];
    char tmp[MAXLEN];
    MEVENT event;
    char *s;
    int maxy, maxx;
    getmaxyx(stdscr, maxy, maxx);
    int begy = (maxy - lines) / 3;
    int begx = (maxx - cols) / 2;
    mousemask(ALL_MOUSE_EVENTS | REPORT_MOUSE_POSITION | BUTTON_SHIFT |
                  BUTTON_CTRL | BUTTON_ALT,
              nullptr);
    if (win_new(lines, cols, begy, begx, Title, 0)) {
        strnz__cpy(tmp, "win_new failed: ", MAXLEN - 1);
        strnz__cat(tmp, Title, MAXLEN - 1);
        Perror(tmp);
        return 0;
    }
    win = win_win[win_ptr];
    box = win_box[win_ptr];
    keypad(win, TRUE);
    wattron(win, WA_REVERSE);
    mvwaddstr(win, lines - 1, 0, " <ALT>END to exit ");
    wattroff(win, WA_REVERSE);
    wnoutrefresh(box);
    mvwaddstr(win, 1, 4, "Press a key or activate the mouse:");
    // timeout(1000);
    c = '\0';
    while (!c) {
        kstr[0] = '\0';
        wmove(win, 1, 39);
        c = xwgetch(win, nullptr);
        s = keybound(c, 0);
        switch (c) {
        case '\0':
            break;
        case KEY_CODE_YES:
            strnz__cpy(kstr, "KEY_CODE_YES A wchar_t contains a key code",
                       KSTRLEN - 1);
            break;
        case KEY_BREAK:
            strnz__cpy(kstr, "KEY_BREAK Break key(unreliable)", KSTRLEN - 1);
            break;
        case KEY_DOWN:
            strnz__cpy(kstr, "KEY_DOWN down - arrow key", KSTRLEN - 1);
            break;
        case KEY_UP:
            strnz__cpy(kstr, "KEY_UP up - arrow key", KSTRLEN - 1);
            break;
        case KEY_LEFT:
            strnz__cpy(kstr, "KEY_LEFT left - arrow key", KSTRLEN - 1);
            break;
        case KEY_RIGHT:
            strnz__cpy(kstr, "KEY_RIGHT right - arrow key", KSTRLEN - 1);
            break;
        case KEY_HOME:
            strnz__cpy(kstr, "KEY_HOME home key", KSTRLEN - 1);
            break;
        case KEY_BACKSPACE:
            strnz__cpy(kstr, "KEY_BACKSPACE backspace key", KSTRLEN - 1);
            break;
        case KEY_F(1):
            strnz__cpy(kstr, "KEY_F(1) KEY_F(1)", KSTRLEN - 1);
            break;
        case KEY_F(2):
            strnz__cpy(kstr, "KEY_F2 KEY_F2", KSTRLEN - 1);
            break;
        case KEY_F(3):
            strnz__cpy(kstr, "KEY_F3 KEY_F3", KSTRLEN - 1);
            break;
        case KEY_F(4):
            strnz__cpy(kstr, "KEY_F4 KEY_F4", KSTRLEN - 1);
            break;
        case KEY_F(5):
            strnz__cpy(kstr, "KEY_F5 KEY_F5", KSTRLEN - 1);
            break;
        case KEY_F(6):
            strnz__cpy(kstr, "KEY_F6 KEY_F6", KSTRLEN - 1);
            break;
        case KEY_F(7):
            strnz__cpy(kstr, "KEY_F7 KEY_F7", KSTRLEN - 1);
            break;
        case KEY_F(8):
            strnz__cpy(kstr, "KEY_F8 KEY_F8", KSTRLEN - 1);
            break;
        case KEY_F(9):
            strnz__cpy(kstr, "KEY_F9 KEY_F9", KSTRLEN - 1);
            break;
        case KEY_F(10):
            strnz__cpy(kstr, "KEY_F10 KEY_F10", KSTRLEN - 1);
            break;
        case KEY_F(11):
            strnz__cpy(kstr, "KEY_F11 KEY_F11", KSTRLEN - 1);
            break;
        case KEY_F(12):
            strnz__cpy(kstr, "KEY_F12 KEY_F12", KSTRLEN - 1);
            break;
        case KEY_DL:
            strnz__cpy(kstr, "KEY_DL delete - line key", KSTRLEN - 1);
            break;
        case KEY_IL:
            strnz__cpy(kstr, "KEY_IL insert - line key", KSTRLEN - 1);
            break;
        case KEY_DC:
            strnz__cpy(kstr, "KEY_DC delete - character key", KSTRLEN - 1);
            break;
        case KEY_IC:
            strnz__cpy(kstr, "KEY_IC insert - character key", KSTRLEN - 1);
            break;
        case KEY_EIC:
            strnz__cpy(kstr, "KEY_EIC sent by rmir or smir in insert mode",
                       KSTRLEN - 1);
            break;
        case KEY_CLEAR:
            strnz__cpy(kstr, "KEY_CLEAR clear - screen or erase key",
                       KSTRLEN - 1);
            break;
        case KEY_EOS:
            strnz__cpy(kstr, "KEY_EOS clear - to - end - of - screen key",
                       KSTRLEN - 1);
            break;
        case KEY_EOL:
            strnz__cpy(kstr, "KEY_EOL clear - to - end - of - line key",
                       KSTRLEN - 1);
            break;
        case KEY_SF:
            strnz__cpy(kstr, "KEY_SF scroll - forward key", KSTRLEN - 1);
            break;
        case KEY_SR:
            strnz__cpy(kstr, "KEY_SR scroll - backward key", KSTRLEN - 1);
            break;
        case KEY_NPAGE:
            strnz__cpy(kstr, "KEY_NPAGE next - page key", KSTRLEN - 1);
            break;
        case KEY_PPAGE:
            strnz__cpy(kstr, "KEY_PPAGE previous - page key", KSTRLEN - 1);
            break;
        case KEY_STAB:
            strnz__cpy(kstr, "KEY_STAB set - tab key", KSTRLEN - 1);
            break;
        case KEY_CTAB:
            strnz__cpy(kstr, "KEY_CTAB clear - tab key", KSTRLEN - 1);
            break;
        case KEY_CATAB:
            strnz__cpy(kstr, "KEY_CATAB clear - all - tabs key", KSTRLEN - 1);
            break;
        case '\n':
            strnz__cpy(kstr, "KEY_ENTER newline key", KSTRLEN - 1);
            break;
        case KEY_ENTER:
            strnz__cpy(kstr, "KEY_ENTER enter / send key", KSTRLEN - 1);
            break;
        case KEY_SRESET:
            strnz__cpy(kstr, "KEY_SRESET Soft(partial) reset(unreliable)",
                       KSTRLEN - 1);
            break;
        case KEY_RESET:
            strnz__cpy(kstr, "KEY_RESET Reset or hard reset(unreliable)",
                       KSTRLEN - 1);
            break;
        case KEY_PRINT:
            strnz__cpy(kstr, "KEY_PRINT print key", KSTRLEN - 1);
            break;
        case KEY_LL:
            strnz__cpy(kstr, "KEY_LL lower - left key(home down)", KSTRLEN - 1);
            break;
        case KEY_A1:
            strnz__cpy(kstr, "KEY_A1 upper left of keypad", KSTRLEN - 1);
            break;
        case KEY_A3:
            strnz__cpy(kstr, "KEY_A3 upper right of keypad", KSTRLEN - 1);
            break;
        case KEY_B2:
            strnz__cpy(kstr, "KEY_B2 center of keypad", KSTRLEN - 1);
            break;
        case KEY_C1:
            strnz__cpy(kstr, "KEY_C1 lower left of keypad", KSTRLEN - 1);
            break;
        case KEY_C3:
            strnz__cpy(kstr, "KEY_C3 lower right of keypad", KSTRLEN - 1);
            break;
        case KEY_BTAB:
            strnz__cpy(kstr, "KEY_BTAB back - tab key", KSTRLEN - 1);
            break;
        case KEY_BEG:
            strnz__cpy(kstr, "KEY_BEG begin key", KSTRLEN - 1);
            break;
        case KEY_CANCEL:
            strnz__cpy(kstr, "KEY_CANCEL cancel key", KSTRLEN - 1);
            break;
        case KEY_CLOSE:
            strnz__cpy(kstr, "KEY_CLOSE close key", KSTRLEN - 1);
            break;
        case KEY_COMMAND:
            strnz__cpy(kstr, "KEY_COMMAND command key", KSTRLEN - 1);
            break;
        case KEY_COPY:
            strnz__cpy(kstr, "KEY_COPY copy key", KSTRLEN - 1);
            break;
        case KEY_CREATE:
            strnz__cpy(kstr, "KEY_CREATE create key", KSTRLEN - 1);
            break;
        case KEY_END:
            strnz__cpy(kstr, "KEY_END end key", KSTRLEN - 1);
            break;
        case KEY_EXIT:
            strnz__cpy(kstr, "KEY_EXIT exit key", KSTRLEN - 1);
            break;
        case KEY_FIND:
            strnz__cpy(kstr, "KEY_FIND find key", KSTRLEN - 1);
            break;
        case KEY_HELP:
            strnz__cpy(kstr, "KEY_HELP help key", KSTRLEN - 1);
            break;
        case KEY_MARK:
            strnz__cpy(kstr, "KEY_MARK mark key", KSTRLEN - 1);
            break;
        case KEY_MESSAGE:
            strnz__cpy(kstr, "KEY_MESSAGE message key", KSTRLEN - 1);
            break;
        case KEY_MOVE:
            strnz__cpy(kstr, "KEY_MOVE move key", KSTRLEN - 1);
            break;
        case KEY_NEXT:
            strnz__cpy(kstr, "KEY_NEXT next key", KSTRLEN - 1);
            break;
        case KEY_OPEN:
            strnz__cpy(kstr, "KEY_OPEN open key", KSTRLEN - 1);
            break;
        case KEY_OPTIONS:
            strnz__cpy(kstr, "KEY_OPTIONS options key", KSTRLEN - 1);
            break;
        case KEY_PREVIOUS:
            strnz__cpy(kstr, "KEY_PREVIOUS previous key", KSTRLEN - 1);
            break;
        case KEY_REDO:
            strnz__cpy(kstr, "KEY_REDO redo key", KSTRLEN - 1);
            break;
        case KEY_REFERENCE:
            strnz__cpy(kstr, "KEY_REFERENCE reference key", KSTRLEN - 1);
            break;
        case KEY_REFRESH:
            strnz__cpy(kstr, "KEY_REFRESH refresh key", KSTRLEN - 1);
            break;
        case KEY_REPLACE:
            strnz__cpy(kstr, "KEY_REPLACE replace key", KSTRLEN - 1);
            break;
        case KEY_RESTART:
            strnz__cpy(kstr, "KEY_RESTART restart key", KSTRLEN - 1);
            break;
        case KEY_RESUME:
            strnz__cpy(kstr, "KEY_RESUME resume key", KSTRLEN - 1);
            break;
        case KEY_SAVE:
            strnz__cpy(kstr, "KEY_SAVE save key", KSTRLEN - 1);
            break;
        case KEY_SBEG:
            strnz__cpy(kstr, "KEY_SBEG shifted begin key", KSTRLEN - 1);
            break;
        case KEY_SCANCEL:
            strnz__cpy(kstr, "KEY_SCANCEL shifted cancel key", KSTRLEN - 1);
            break;
        case KEY_SCOMMAND:
            strnz__cpy(kstr, "KEY_SCOMMAND shifted command key", KSTRLEN - 1);
            break;
        case KEY_SCOPY:
            strnz__cpy(kstr, "KEY_SCOPY shifted copy key", KSTRLEN - 1);
            break;
        case KEY_SCREATE:
            strnz__cpy(kstr, "KEY_SCREATE shifted create key", KSTRLEN - 1);
            break;
        case KEY_SDC:
            strnz__cpy(kstr, "KEY_SDC shifted delete - character key",
                       KSTRLEN - 1);
            break;
        case KEY_SDL:
            strnz__cpy(kstr, "KEY_SDL shifted delete - line key", KSTRLEN - 1);
            break;
        case KEY_SELECT:
            strnz__cpy(kstr, "KEY_SELECT select key", KSTRLEN - 1);
            break;
        case KEY_SEND:
            strnz__cpy(kstr, "KEY_SEND shifted end key", KSTRLEN - 1);
            break;
        case KEY_SEOL:
            strnz__cpy(kstr,
                       "KEY_SEOL shifted clear - to - end - of - line key",
                       KSTRLEN - 1);
            break;
        case KEY_SEXIT:
            strnz__cpy(kstr, "KEY_SEXIT shifted exit key", KSTRLEN - 1);
            break;
        case KEY_SFIND:
            strnz__cpy(kstr, "KEY_SFIND shifted find key", KSTRLEN - 1);
            break;
        case KEY_SHELP:
            strnz__cpy(kstr, "KEY_SHELP shifted help key", KSTRLEN - 1);
            break;
        case KEY_SHOME:
            strnz__cpy(kstr, "KEY_SHOME shifted home key", KSTRLEN - 1);
            break;
        case KEY_SIC:
            strnz__cpy(kstr, "KEY_SIC shifted insert - character key",
                       KSTRLEN - 1);
            break;
        case KEY_SLEFT:
            strnz__cpy(kstr, "KEY_SLEFT shifted left - arrow key", KSTRLEN - 1);
            break;
        case KEY_SMESSAGE:
            strnz__cpy(kstr, "KEY_SMESSAGE shifted message key", KSTRLEN - 1);
            break;
        case KEY_SMOVE:
            strnz__cpy(kstr, "KEY_SMOVE shifted move key", KSTRLEN - 1);
            break;
        case KEY_SNEXT:
            strnz__cpy(kstr, "KEY_SNEXT shifted next key", KSTRLEN - 1);
            break;
        case KEY_SOPTIONS:
            strnz__cpy(kstr, "KEY_SOPTIONS shifted options key", KSTRLEN - 1);
            break;
        case KEY_SPREVIOUS:
            strnz__cpy(kstr, "KEY_SPREVIOUS shifted previous key", KSTRLEN - 1);
            break;
        case KEY_SPRINT:
            strnz__cpy(kstr, "KEY_SPRINT shifted print key", KSTRLEN - 1);
            break;
        case KEY_SREDO:
            strnz__cpy(kstr, "KEY_SREDO shifted redo key", KSTRLEN - 1);
            break;
        case KEY_SREPLACE:
            strnz__cpy(kstr, "KEY_SREPLACE shifted replace key", KSTRLEN - 1);
            break;
        case KEY_SRIGHT:
            strnz__cpy(kstr, "KEY_SRIGHT shifted right - arrow key",
                       KSTRLEN - 1);
            break;
        case KEY_SRSUME:
            strnz__cpy(kstr, "KEY_SRSUME shifted resume key", KSTRLEN - 1);
            break;
        case KEY_SSAVE:
            strnz__cpy(kstr, "KEY_SSAVE shifted save key", KSTRLEN - 1);
            break;
        case KEY_SSUSPEND:
            strnz__cpy(kstr, "KEY_SSUSPEND shifted suspend key", KSTRLEN - 1);
            break;
        case KEY_SUNDO:
            strnz__cpy(kstr, "KEY_SUNDO shifted undo key", KSTRLEN - 1);
            break;
        case KEY_SUSPEND:
            strnz__cpy(kstr, "KEY_SUSPEND suspend key", KSTRLEN - 1);
            break;
        case KEY_UNDO:
            strnz__cpy(kstr, "KEY_UNDO undo key", KSTRLEN - 1);
            break;
        case KEY_ALTDEL:
            strnz__cpy(kstr, "KEY_ALTDEL alt+delete", KSTRLEN - 1);
            break;
        case KEY_ALTDOWN:
            strnz__cpy(kstr, "KEY_ALTDOWN alt+down", KSTRLEN - 1);
            break;
        case KEY_ALTEND:
            strnz__cpy(kstr, "KEY_ALTEND alt+end", KSTRLEN - 1);
            break;
        case KEY_ALTHOME:
            strnz__cpy(kstr, "KEY_ALTHOME alt+home", KSTRLEN - 1);
            break;
        case KEY_ALTINS:
            strnz__cpy(kstr, "KEY_ALTINS alt+ins", KSTRLEN - 1);
            break;
        case KEY_ALTLEFT:
            strnz__cpy(kstr, "KEY_ALTLEFT alt+left", KSTRLEN - 1);
            break;
        case KEY_ALTPGDN:
            strnz__cpy(kstr, "KEY_ALTPGDN alt+pgdn", KSTRLEN - 1);
            break;
        case KEY_ALTPGUP:
            strnz__cpy(kstr, "KEY_ALTPGUP alt+pgup", KSTRLEN - 1);
            break;
        case KEY_ALTRIGHT:
            strnz__cpy(kstr, "KEY_ALTRIGHT alt+right", KSTRLEN - 1);
            break;
        case KEY_ALTUP:
            strnz__cpy(kstr, "KEY_ALTUP alt+up", KSTRLEN - 1);
            break;
        case KEY_ALTF(1):
            strnz__cpy(kstr, "KEY_ALTF1 alt+F1", KSTRLEN - 1);
            break;
        case KEY_ALTF(2):
            strnz__cpy(kstr, "KEY_ALTF1 alt+F2", KSTRLEN - 1);
            break;
        case KEY_ALTF(3):
            strnz__cpy(kstr, "KEY_ALTF3 alt+F3", KSTRLEN - 1);
            break;
        case KEY_ALTF(4):
            strnz__cpy(kstr, "KEY_ALTF4 alt+F4", KSTRLEN - 1);
            break;
        case KEY_ALTF(5):
            strnz__cpy(kstr, "KEY_ALTF5 alt+F5", KSTRLEN - 1);
            break;
        case KEY_ALTF(6):
            strnz__cpy(kstr, "KEY_ALTF6 alt+F6", KSTRLEN - 1);
            break;
        case KEY_ALTF(7):
            strnz__cpy(kstr, "KEY_ALTF7 alt+F7", KSTRLEN - 1);
            break;
        case KEY_ALTF(8):
            strnz__cpy(kstr, "KEY_ALTF8 alt+F8", KSTRLEN - 1);
            break;
        case KEY_ALTF(9):
            strnz__cpy(kstr, "KEY_ALTF9 alt+F9", KSTRLEN - 1);
            break;
        case KEY_ALTF(10):
            strnz__cpy(kstr, "KEY_ALTF10 alt+F10", KSTRLEN - 1);
            break;
        case KEY_ALTF(11):
            strnz__cpy(kstr, "KEY_ALTF11 alt+F11", KSTRLEN - 1);
            break;
        case KEY_ALTF(12):
            strnz__cpy(kstr, "KEY_ALTF12 alt+F12", KSTRLEN - 1);
            break;
        case KEY_MOUSE:
            action[0] = '\0';
            if (getmouse(&event) == OK) {
                switch (event.bstate) {
                case BUTTON1_PRESSED:
                    strnz__cpy(action, "Button 1 pressed", KSTRLEN - 1);
                    break;
                case BUTTON1_RELEASED:
                    strnz__cpy(action, "Button 1 released", KSTRLEN - 1);
                    break;
                case BUTTON1_CLICKED:
                    strnz__cpy(action, "Button 1 clicked", KSTRLEN - 1);
                    break;
                case BUTTON1_DOUBLE_CLICKED:
                    strnz__cpy(action, "Button 1 double-clicked", KSTRLEN - 1);
                    break;
                case BUTTON2_PRESSED:
                    strnz__cpy(action, "Button 2 pressed", KSTRLEN - 1);
                    break;
                case BUTTON2_RELEASED:
                    strnz__cpy(action, "Button 2 released", KSTRLEN - 1);
                    break;
                case BUTTON2_CLICKED:
                    strnz__cpy(action, "Button 2 clicked", KSTRLEN - 1);
                    break;
                case BUTTON2_DOUBLE_CLICKED:
                    strnz__cpy(action, "Button 2 double-clicked", KSTRLEN - 1);
                    break;
                case BUTTON3_PRESSED:
                    strnz__cpy(action, "Button 3 pressed", KSTRLEN - 1);
                    break;
                case BUTTON3_RELEASED:
                    strnz__cpy(action, "Button 3 released", KSTRLEN - 1);
                    break;
                case BUTTON3_CLICKED:
                    strnz__cpy(action, "Button 3 clicked", KSTRLEN - 1);
                    break;
                case BUTTON3_DOUBLE_CLICKED:
                    strnz__cpy(action, "Button 3 double-clicked", KSTRLEN - 1);
                    break;
                case BUTTON4_PRESSED:
                    strnz__cpy(action, "Button 4 pressed", KSTRLEN - 1);
                    break;
                case BUTTON4_RELEASED:
                    strnz__cpy(action, "Button 4 released", KSTRLEN - 1);
                    break;
                case BUTTON4_CLICKED:
                    strnz__cpy(action, "Button 4 clicked", KSTRLEN - 1);
                    break;
                case BUTTON4_DOUBLE_CLICKED:
                    strnz__cpy(action, "Button 4 double-clicked", KSTRLEN - 1);
                    break;
                case BUTTON5_PRESSED:
                    strnz__cpy(action, "Scroll Up", KSTRLEN - 1);
                    break;
                default:
                    break;
                }
                mvwaddstr(win, 6, 3, "     Action:");
                mvwaddstr(win, 6, 16, action);
                wclrtoeol(win);
                strnz__cpy(tmp, "  With Key:", MAXLEN - 1);
                if (event.bstate & BUTTON_SHIFT)
                    strnz__cat(tmp, " Shift", MAXLEN - 1);
                if (event.bstate & BUTTON_CTRL)
                    strnz__cat(tmp, " Ctrl", MAXLEN - 1);
                if (event.bstate & BUTTON_ALT)
                    strnz__cat(tmp, " Alt", MAXLEN - 1);
                mvwaddstr(win, 3, 4, tmp);
                wclrtoeol(win);
                if (wenclose(win, event.y, event.x)) {
                    sprintf(tmp, "   Inside Win:  y: %3d, x: %3d",
                            event.y - begy, event.x - begx);
                } else {
                    sprintf(tmp, "  Outside Win:  y: %3d, x: %3d",
                            event.y - begy, event.x - begx);
                }
                mvwaddstr(win, 4, 4, tmp);
                wclrtoeol(win);
                wmove(win, 5, 0);
                wclrtoeol(win);
                wmove(win, 7, 0);
                wclrtoeol(win);
            }
            break;
        default:
            break;
        }
        if (c != KEY_MOUSE) {
            sprintf(tmp, "     Octal: %3o", c);
            mvwaddstr(win, 3, 4, tmp);
            wclrtoeol(win);
            sprintf(tmp, "   Decimal: %3d", c);
            mvwaddstr(win, 4, 4, tmp);
            wclrtoeol(win);
            sprintf(tmp, "       Hex: %3x", c);
            mvwaddstr(win, 5, 4, tmp);
            wclrtoeol(win);
            if (kstr[0]) {
                sprintf(tmp, "Description: %s", kstr);
            } else {
                sprintf(tmp, "      ASCII: %c", c);
            }
            mvwaddstr(win, 6, 3, tmp);
            wclrtoeol(win);
            mvwaddstr(win, 7, 2, "Key bound To: ");
            wclrtoeol(win);
            mvwaddstr(win, 7, 16, s ? s : "Not Bound");
            wrefresh(win);
        }
        if (c == KEY_ALTEND) {
            usleep(100000);
            break;
        }
        c = '\0';
    }
    wclear(win);
    wrefresh(win);
    clear();
    refresh();
    win_del();
    return 0;
}
References begx, begy, cols, KEY_ALTDEL, KEY_ALTDOWN, KEY_ALTEND, KEY_ALTF, KEY_ALTHOME, KEY_ALTINS, KEY_ALTLEFT, KEY_ALTPGDN, KEY_ALTPGUP, KEY_ALTRIGHT, KEY_ALTUP, KSTRLEN, lines, MAXLEN, Perror(), strnz__cat(), strnz__cpy(), TRUE, win, win_box, win_del(), win_new(), win_ptr, win_win, and xwgetch().
Referenced by main(), and menu_cmd_processor().
display_error()
int display_error (char * em0, char * em1, char * em2, char * em3) extern
Display an error message window or print to stderr.
Parameters
em0 First error message line
em1 Second error message line
em2 Third error message line
em3 Fourth error message line
Returns
Key code of user command
Definition at line 847 of file dwin.c.
{
    char title[MAXLEN];
    int line, pos, em_l, em0_l, em1_l, em2_l, em3_l;
    WINDOW *error_win;
    if (!f_curses_open) {
        fprintf(stderr, "\n\n%s\n%s\n%s\n%s\n\n", em0, em1, em2, em3);
        return (1);
    }
    Chyron *chyron = new_chyron();
    set_chyron_key(chyron, 1, "F1 Help", KEY_F(1));
    set_chyron_key(chyron, 9, "F9 Cancel", KEY_F(9));
    set_chyron_key(chyron, 10, "F10 Continue", KEY_F(10));
    compile_chyron(chyron);
    em_l = 0;
    em0_l = strnz(em0, COLS - 4);
    em1_l = strnz(em1, COLS - 4);
    em2_l = strnz(em2, COLS - 4);
    em3_l = strnz(em1, COLS - 4);
    if (em0_l > em_l)
        em_l = em0_l;
    if (em1_l > em_l)
        em_l = em1_l;
    if (em2_l > em_l)
        em_l = em2_l;
    if (em3_l > em_l)
        em_l = em3_l;
    if (em_l < chyron->l)
        em_l = chyron->l;
    if (em_l > (COLS - 4))
        em_l = COLS - 4;
    pos = ((COLS - em_l) - 4) / 2;
    line = (LINES - 6) / 2;
    strnz__cpy(title, "Notification", MAXLEN - 1);
    if (win_new(5, em_l + 2, line, pos, title, 0)) {
        ssnprintf(title, MAXLEN - 1, "win_new(%d, %d, %d, %d, %s, %b) failed",
                  5, em_l + 2, line, pos, title, 0);
        destroy_chyron(chyron);
        abend(-1, title);
    }
    error_win = win_win[win_ptr];
    mvwaddstr(error_win, 0, 1, em0);
    mvwaddstr(error_win, 1, 1, em1);
    mvwaddstr(error_win, 2, 1, em2);
    mvwaddstr(error_win, 3, 1, em3);
    wattron(error_win, WA_REVERSE);
    mvwaddstr(error_win, 4, 1, chyron->s);
    wattroff(error_win, WA_REVERSE);
    wmove(error_win, 4, chyron->l + 1);
    wrefresh(error_win);
    while (1) {
        cmd_key = xwgetch(error_win, chyron);
        switch (cmd_key) {
        case 'n':
        case 'N':
        case 'q':
        case 'Q':
        case 'x':
        case 'X':
        case 'y':
        case 'Y':
        case KEY_F(1):
        case KEY_F(9):
        case KEY_F(10):
            win_del();
            return (cmd_key);
        default:
            continue;
        }
    }
    win_del();
    destroy_chyron(chyron);
    return (cmd_key);
}
References abend(), cmd_key, compile_chyron(), destroy_chyron(), em0, em1, em2, em3, f_curses_open, Chyron::l, MAXLEN, new_chyron(), Chyron::s, set_chyron_key(), ssnprintf(), strnz(), strnz__cpy(), win_del(), win_new(), win_ptr, win_win, and xwgetch().
Referenced by enter_file_spec(), form_calculate(), form_desc_error(), form_parse_desc(), form_read_data(), form_write(), get_clr_pair(), init_view_boxwin(), init_view_full_screen(), lf_find(), mk_dir(), new_init(), new_pick(), new_view(), parse_menu_description(), verify_dir(), verify_file(), view_cmd_processor(), view_init_input(), write_view_buffer(), and xwgetch().
display_ok_message()
int display_ok_message (char *) extern
dump_opts()
void dump_opts () extern
dump all options
dump options to stdout
Definition at line 211 of file opts.c.
                 {
    print_opt_header();
    int i = 0;
    while (opts[i].name != nullptr) {
        if (opts[i].name[0] != '\0')
            print_opt(i);
        i++;
    }
}
References opts, print_opt(), and print_opt_header().
Referenced by dump_opts_by_desc(), dump_opts_by_group(), dump_opts_by_name(), dump_opts_by_short_opt(), and main().
dump_opts_by_use()
void dump_opts_by_use (char * usage, char * mask) extern
dump options by use mask
dump options to stdout
Parameters
usage - usage string
mask - use mask string
Definition at line 224 of file opts.c.
{
    int i = 0;
    int j = 0;
    printf("\nusage: %s\n\n", usage);
    print_opt_header();
    while (opts[i].name != nullptr && opts[i].name[0] != '\0') {
        for (j = 0; j < 4; j++) {
            if (mask[j] != '.' && mask[j] == opts[i].use[j])
                break;
            else
                continue;
        }
        if (j == 4) {
            i++;
            continue;
        }
        if (opts[i].name[0] != '\0')
            print_opt(i);
        i++;
    }
}
References opts, print_opt(), print_opt_header(), and usage().
Referenced by form_usage(), and main().
enter_option()
int enter_option () extern
References MAXWIN, mbegx, mbegy, mcols, mg_action, mg_col, mg_line, mlines, win, win_attr, win_attr_even, win_attr_odd, win_box, win_ptr, and win_win.
expand_tilde()
bool expand_tilde (char * path, int path_maxlen) extern
Replace Leading Tilde With Home Directory.
Parameters
path - path to expand
path_maxlen - maximum length of path
Note
The caller is responsible for ensuring that "path" has enough space to receive the result, and that "path_maxlen" is sufficient to hold the result. This function does not perform any bounds checking on "path", so it is the caller's responsibility to ensure that it is valid and that "path_maxlen" is appropriate for the operation.
Returns
true if successful
Definition at line 611 of file futil.c.
{
    if (path == nullptr || *path == '\0' || path_maxlen == 0)
        return false;
    char *e;
    char ts[MAXLEN];
    char *tp;
    if (!path || !*path || !path_maxlen)
        return false;
    tp = path;
    if (*tp == '~') {
        tp++;
        while (*tp == '/') {
            tp++;
        }
        e = getenv("HOME");
        if (e) {
            strnz__cpy(ts, e, path_maxlen - 1);
            strnz__cat(ts, "/", path_maxlen - 1);
            strnz__cat(ts, tp, path_maxlen - 1);
            strnz__cpy(path, ts, path_maxlen - 1);
        }
    }
    return true;
References MAXLEN, strnz__cat(), and strnz__cpy().
Referenced by enter_file_spec(), form_engine(), mapp_initialization(), menu_cmd_processor(), mk_dir(), parse_config(), verify_dir(), verify_file(), verify_spec_arg(), view_display_help(), and view_init_input().
file_spec_name()
bool file_spec_name (char * fn, char * fs) extern
extracts the file name component of a file specification
Parameters
fn - name component to return
fs - full file specification
Note
The caller is responsible for ensuring that "fn" has enough space to receive the result.
Definition at line 534 of file futil.c.
{
    if (fs == nullptr || *fs == '\0' || fn == nullptr) {
        if (fn != nullptr)
            *fn = '\0';
        return false;
    }
    char *d, *l, *s;
    l = nullptr;
    s = fs;
    while (*s != '\0') {
        if (*s == '/')
            l = s;
        s++;
    }
    if (l == nullptr)
        s = fs;
    else
        s = ++l;
    d = fn;
    while (*s != '\0')
        *d++ = *s++;
    *d = '\0';
    return true;
References fn.
file_spec_path()
bool file_spec_path (char * fp, char * fs) extern
extracts the path component of a file specification
Parameters
fp - path component to return
fs - full file specification
Returns
true if successful
Note
The caller is responsible for ensuring that "fp" has enough space to receive the result.
Definition at line 508 of file futil.c.
{
    if (fs == nullptr || *fs == '\0' || fp == nullptr) {
        if (fp != nullptr)
            *fp = '\0';
        return false;
    }
    char *d, *l, *s;
    s = fp;
    d = fs;
    l = nullptr;
    while (*s != '\0') {
        if (*s == '/')
            l = d;
        *d++ = *s++;
    }
    if (l == nullptr)
        *fp = '\0'; // no slash, so no path
    else
        *l = '\0';
    return true;
fork_exec()
int fork_exec (char ** argv) extern
Fork and exec a command.
Parameters
argv - array of arguments for the command to execute
Returns
the return code from the executed command, or -1 on error
Note
Captures and restores terminal settings around the fork and exec.
Sets signal handlers to default in the child process.
Waits for the child process to complete in the parent process.
Handles errors from fork and execvp, and reports child exit status.
Restores curses mode and keypad settings after execution.
Restores window states after execution.
Uses a temporary string buffer tmp_str for error messages.
Uses Perror for error reporting.
Uses sig_dfl_mode and sig_prog_mode for signal handling.
Uses capture_curses_tioctl and restore_curses_tioctl for terminal settings.
Uses restore_shell_tioctl for shell terminal settings.
Uses waitpid to wait for the child process.
Uses WIFEXITED, WEXITSTATUS, WIFSIGNALED, and WTERMSIG to interpret child status.
Uses keypad to manage keypad mode in curses.
Uses restore_wins to restore window states.
Uses errno for error codes.
Uses pid_t for process IDs.
Uses standard file descriptors STDIN_FILENO, STDOUT_FILENO, STDERR_FILENO.
Uses execvp for executing the command.
Uses fork for creating a new process.
Uses ssnprintf for formatting error messages.
Uses switch-case for handling fork results.
Uses default shell if SHELL environment variable is not set.
Definition at line 124 of file exec.c.
{
    char tmp_str[MAXLEN];
    pid_t pid;
    int status;
    int rc;
    if (argv[0] == 0) {
        Perror("fork_exec: missing argument for execvp");
        return (-1);
    }
    capture_curses_tioctl();
    sig_dfl_mode();
    restore_shell_tioctl();
    tmp_str[0] = '\0';
    pid = fork();
    switch (pid) {
    case -1: // parent fork failed
        restore_curses_tioctl();
        sig_prog_mode();
        keypad(stdscr, true);
        ssnprintf(tmp_str, sizeof(tmp_str), "fork failed: %s, errno: %d",
                  argv[0], errno);
        Perror(tmp_str);
        return (-1);
    case 0: // child
        restore_shell_tioctl();
        execvp(argv[0], argv);
        restore_curses_tioctl();
        sig_prog_mode();
        keypad(stdscr, true);
        ssnprintf(tmp_str, sizeof(tmp_str), "execvp failed: %s, errno: %d",
                  argv[0], errno);
        Perror(tmp_str);
        exit(-1);
    default: // parent
        rc = 0;
        restore_curses_tioctl();
        sig_prog_mode();
        waitpid(pid, &status, 0);
        if (WIFEXITED(status)) {
            rc = WEXITSTATUS(status);
            if (rc != 0) {
                keypad(stdscr, true);
                ssnprintf(tmp_str, sizeof(tmp_str),
                          "Child %s exited  with status %d", argv[0], rc);
            }
        } else {
            if (WIFSIGNALED(status)) {
                rc = WTERMSIG(status);
                keypad(stdscr, true);
                ssnprintf(tmp_str, sizeof(tmp_str),
                          "Child %s terminated by signal %d", argv[0], rc);
            } else {
                keypad(stdscr, true);
                ssnprintf(tmp_str, sizeof(tmp_str),
                          "Child %s terminated abnormally", argv[0]);
            }
        }
        break;
    }
    restore_curses_tioctl();
    sig_prog_mode();
    keypad(stdscr, true);
    restore_wins();
    if (tmp_str[0] != '\0') {
        Perror(tmp_str);
    }
    return (rc);
}
References capture_curses_tioctl(), MAXLEN, Perror(), restore_curses_tioctl(), restore_shell_tioctl(), restore_wins(), sig_dfl_mode(), sig_prog_mode(), ssnprintf(), and tmp_str.
Referenced by full_screen_fork_exec(), and shell().
free_string()
String free_string (String str) extern
Free the dynamically allocated String.
Parameters
string to free
Returns
string with nullptr pointer and length 0
Note
Frees the dynamically allocated string and sets length to 0.
fn free_string(String str) -> String Free the memory allocated for a String struct
Parameters
str String struct to free
Note
: This function frees the memory allocated for the string in the String struct and sets its length to 0 and pointer to NULL.
Returns
: String struct with NULL pointer and length 0
Definition at line 1256 of file futil.c.
{
    if (string.s == nullptr)
        return string;
    free(string.s);
    string.l = 0;
    string.s = nullptr;
    return string;
References String::l, and String::s.
Referenced by get_rfc3339_str(), and main().
full_screen_fork_exec()
int full_screen_fork_exec (char ** argv) extern
Execute a command in full screen mode.
Parameters
argv - array of arguments for the command to execute
Returns
the return code from the executed command
Note
Clear the screen,
move the cursor to the bottom, and refresh the screen before executing the command.
After the command completes, clear the screen, move the cursor to the top, refresh the screen, and restore the windows.
Definition at line 40 of file exec.c.
{
    int rc;
    fflush(stderr);
    wclear(stdscr);
    wmove(stdscr, LINES - 1, 0);
    wrefresh(stdscr);
    rc = fork_exec(argv);
    wclear(stdscr);
    wmove(stdscr, 0, 0);
    wrefresh(stdscr);
    restore_wins();
    return (rc);
}
References fork_exec(), and restore_wins().
Referenced by menu_cmd_processor().
full_screen_shell()
int full_screen_shell (char * shellCmdPtr) extern
Execute a shell command in full screen mode.
Parameters
shellCmdPtr - pointer to the shell command string
Returns
the return code from the executed shell command
Note
Clear the screen, move the cursor to the top, and refresh the screen before executing the shell command.
After the command completes, restore the windows.
Definition at line 61 of file exec.c.
{
    int rc;
    fflush(stderr);
    wclear(stdscr);
    wmove(stdscr, 0, 0);
    wrefresh(stdscr);
    rc = shell(shellCmdPtr);
    restore_wins();
    return (rc);
}
References restore_wins(), and shell().
Referenced by menu_cmd_processor(), and view_cmd_processor().
get_chyron_key()
int get_chyron_key (Chyron * chyron, int x) extern
Get keycode from chyron.
Parameters
chyron structure
x Mouse X position
Returns
Keycode
Note
This function uses the end_pos values set in compile_chyron to determine which key was clicked
The chyron functions provide xwgetch() with a mechanism to translate mouse click positions into key codes based on the labels set in the chyron structure. When a mouse click occurs, xwgetch() can call get_chyron_key() with the X position of the click to determine which function key was clicked, allowing for dynamic and customizable function key behavior in the chyron area of the interface.
Definition at line 287 of file dwin.c.
{
    int i;
    for (i = 0; chyron->key[i]->end_pos != -1; i++)
        if (x < chyron->key[i]->end_pos)
            break;
    return chyron->key[i]->keycode;
}
References ChyronKey::end_pos, Chyron::key, and ChyronKey::keycode.
Referenced by xwgetch().
get_clr_pair()
int get_clr_pair (int fg, int bg) extern
Get color pair index for foreground and background colors.
Parameters
fg Foreground color index
bg Background color index
Returns
Color pair index
Definition at line 394 of file dwin.c.
{
    int rc, i, pfg, pbg;
    for (i = 0; i < clr_pair_cnt; i++) {
        extended_pair_content(i, &pfg, &pbg);
        if (pfg == fg && pbg == bg)
            return i;
    }
    if (i >= COLOR_PAIRS) {
        ssnprintf(em0, MAXLEN - 1, "%s, line: %d", __FILE__, __LINE__ - 1);
        ssnprintf(em1, MAXLEN - 1, "NCurses COLOR_PAIRS (%d) exceeded (%d)",
                  COLOR_PAIRS, i);
        strerror_r(errno, em2, MAXLEN);
        display_error(em0, em1, em2, nullptr);
        return (EXIT_FAILURE);
    }
    if (i < COLOR_PAIRS) {
        rc = init_extended_pair(i, fg, bg);
        if (rc == ERR)
            return ERR;
    }
    if (i < COLOR_PAIRS)
        clr_pair_cnt++;
    return i;
}
References clr_pair_cnt, display_error(), em0, em1, em2, MAXLEN, and ssnprintf().
Referenced by open_curses(), and parse_ansi_str().
get_rfc3339_s()
void get_rfc3339_s (char * , size_t) extern
handle_signal()
bool handle_signal (sig_atomic_t) extern
References CCC_BOX, CCC_NORM, CCC_REVERSE, and sig_received.
Referenced by xwgetch().
init_clr_palette()
bool init_clr_palette (SIO * sio) extern
Initialize color palette based on SIO settings.
Parameters
sio Pointer to SIO struct with color settings
Returns
true if successful, false if error
Note
This function initializes the xterm256 color cube and applies any color overrides specified in the SIO struct. The color strings in the SIO struct are expected to be six-digit HTML style hex color codes (e.g., "#RRGGBB"). If a color override is specified for any of the standard colors, it is applied using the init_hex_clr function. After processing all colors, the clr_cnt variable is set to 16 to indicate that the standard colors have been initialized.
Definition at line 534 of file dwin.c.
{
    if (sio->black[0])
        init_hex_clr(CLR_BLACK, sio->black);
    if (sio->red[0])
        init_hex_clr(CLR_RED, sio->red);
    if (sio->green[0])
        init_hex_clr(CLR_GREEN, sio->green);
    if (sio->yellow[0])
        init_hex_clr(CLR_YELLOW, sio->yellow);
    if (sio->blue[0])
        init_hex_clr(CLR_BLUE, sio->blue);
    if (sio->magenta[0])
        init_hex_clr(CLR_MAGENTA, sio->magenta);
    if (sio->cyan[0])
        init_hex_clr(CLR_CYAN, sio->cyan);
    if (sio->white[0])
        init_hex_clr(CLR_WHITE, sio->white);
    if (sio->bblack[0])
        init_hex_clr(CLR_BBLACK, sio->bblack);
    if (sio->bred[0])
        init_hex_clr(CLR_BRED, sio->bred);
    if (sio->bgreen[0])
        init_hex_clr(CLR_BGREEN, sio->bgreen);
    if (sio->byellow[0])
        init_hex_clr(CLR_BYELLOW, sio->byellow);
    if (sio->bblue[0])
        init_hex_clr(CLR_BBLUE, sio->bblue);
    if (sio->bmagenta[0])
        init_hex_clr(CLR_BMAGENTA, sio->bmagenta);
    if (sio->bcyan[0])
        init_hex_clr(CLR_BCYAN, sio->bcyan);
    if (sio->bwhite[0])
        init_hex_clr(CLR_BWHITE, sio->bwhite);
    clr_cnt = 16;
    return true;
}
References CLR_BBLACK, CLR_BBLUE, CLR_BCYAN, CLR_BGREEN, CLR_BLACK, CLR_BLUE, CLR_BMAGENTA, CLR_BRED, CLR_BWHITE, CLR_BYELLOW, clr_cnt, CLR_CYAN, CLR_GREEN, CLR_MAGENTA, CLR_RED, CLR_WHITE, CLR_YELLOW, init_hex_clr(), and sio.
Referenced by open_curses().
init_stdscr()
void init_stdscr () extern
is_set_chyron_key()
bool is_set_chyron_key (Chyron * chyron, int k) extern
Check if function key label is set.
Parameters
chyron structure
k Function key index (0-19)
Returns
true if set, false if not set
Definition at line 210 of file dwin.c.
{
    if (chyron->key[k]->text[0] != '\0')
        return true;
    else
        return false;
}
References Chyron::key, and ChyronKey::text.
Referenced by form_calculate(), and form_end_fields().
lf_find()
bool lf_find (const char * base_path, const char * re, const char * ere, int max_depth, int flags) extern
Find files in a directory matching a regular expression.
Parameters
base_path directory to search
ere regular expression match to exclude
re regular expression match to include
max_depth depth of directories to scan
flags search flags
               flags = LF_ALL | LF_ICASE | LF_FILES
               flags = LF_ALL | LF_ICASE | LF_DIRS
LF_ALL      =  1,  List all files including hidden files
LF_ICASE    =  2,  Ignore case in search
LF_FILES    =  4,  list files (exclude directories)
LF_DIRS     =  8,  list directories (exclude files)
LF_EXCLUDE  =  16, exclude files matching "ere" pattern
LF_REGEX    =  32, re is a regular expression pattern to match
return true if successful, false otherwise
Definition at line 905 of file futil.c.
{
    int reti;
    regex_t compiled_re;
    regex_t compiled_ere;
    int REG_FLAGS = REG_EXTENDED;
    if (flags & LF_ICASE)
        REG_FLAGS |= REG_ICASE;
    if (flags & LF_REGEX) {
        reti = regcomp(&compiled_re, re, REG_FLAGS);
        if (reti) {
            ssnprintf(em0, MAXLEN - 1, "lf: \'%s\' Invalid pattern\n", re);
            ssnprintf(em1, MAXLEN - 1, "for example: \'.*\\.c$\'\n\n");
            regerror(reti, &compiled_re, em2, sizeof(em2));
            display_error(em0, em1, em2, nullptr);
            regfree(&compiled_re);
            return false;
        }
    }
    if (flags & LF_EXCLUDE) {
        regcomp(&compiled_ere, "^$", REG_FLAGS);
        reti = regcomp(&compiled_ere, ere, REG_FLAGS);
        if (reti) {
            ssnprintf(em0, MAXLEN - 1, "lf: \'%s\' Invalid exclude pattern\n",
                      re);
            ssnprintf(em1, MAXLEN - 1, "for example: \'.*\\.c$\'\n\n");
            regerror(reti, &compiled_ere, em2, sizeof(em2));
            display_error(em0, em1, em2, nullptr);
            regfree(&compiled_ere);
            return false;
        }
    }
    reti =
        lf_process(base_path, &compiled_re, &compiled_ere, 0, max_depth, flags);
    if (flags &= LF_REGEX)
        regfree(&compiled_re);
    if (flags & LF_EXCLUDE)
        regfree(&compiled_ere);
    if (reti)
        return false;
    return true;
References display_error(), em0, em1, em2, LF_EXCLUDE, LF_ICASE, lf_process(), LF_REGEX, MAXLEN, and ssnprintf().
Referenced by main().
locate_file_in_path()
bool locate_file_in_path (char * file_spec, char * file_name) extern
Locates a file in the system PATH.
Parameters
file_spec - buffer to receive located file specification
file_name - name of file to locate
Returns
true if file is located
Note
file_spec must be large enough to receive the result
Definition at line 859 of file futil.c.
{
    if (file_name == nullptr || *file_name == '\0' || file_spec == nullptr)
        return false;
    char path[MAXLEN];
    char fn[MAXLEN];
    char *p, *fnp, *dir;
    canonicalize_file_spec(file_name);
    strnz__cpy(fn, file_name, MAXLEN - 1);
    fnp = fn;
    while (*fnp && *fnp != '/')
        fnp++;
    if (*fnp == '/')
        return false;
    if ((p = getenv("PATH")) == nullptr)
        return false;
    strnz__cpy(path, p, MAXLEN - 1);
    dir = strtok(path, ":");
    while (dir != nullptr) {
        strnz__cpy(file_spec, dir, MAXLEN - 1);
        strnz__cat(file_spec, "/", MAXLEN - 1);
        strnz__cat(file_spec, file_name, MAXLEN - 1);
        if (access(file_spec, F_OK) == 0) {
            return true;
        }
        dir = strtok(nullptr, ":");
    }
    return false;
References canonicalize_file_spec(), file_name, fn, MAXLEN, strnz__cat(), and strnz__cpy().
Referenced by init_form_files(), init_pick_files(), main(), and verify_spec_arg().
mk_dir()
bool mk_dir (char * dir) extern
If directory doesn't exist, make it.
Parameters
dir directory name
Returns
true if directory now exists or false otherwise
Directory does not exist and unable to create
Definition at line 1063 of file futil.c.
                       {
    expand_tilde(dir, MAXLEN - 1);
    if (!verify_dir(dir, S_WCOK | S_QUIET)) {
        if (!mkdir(dir, 0755)) {
            ssnprintf(em0, MAXLEN - 1, "%s, line: %d", __FILE__, __LINE__ - 2);
            strnz__cpy(em1, "mkdir ", MAXLEN - 1);
            strnz__cat(em1, dir, MAXLEN - 1);
            strnz__cat(em1, " failed", MAXLEN - 1);
            strerror_r(errno, em2, MAXLEN - 1);
            display_error(em0, em1, em2, nullptr);
            return false;
        }
        return true;
    }
    return true;
References display_error(), em0, em1, em2, expand_tilde(), MAXLEN, S_QUIET, S_WCOK, ssnprintf(), strnz__cat(), strnz__cpy(), and verify_dir().
Referenced by enter_file_spec().
mk_raw_tioctl()
bool mk_raw_tioctl (struct termios * t_p) extern
mk_raw_tioctl() - set terminal to raw mode
Parameters
t_p - pointer to termios structure to modify
Returns
- true on success
Note
- unlike cfmakeraw(), this leaves ISIG enabled.
- cfmakeraw() disables ISIG, which prevents C-MENU from handling signals like Ctrl-C. Instead of using cfmakeraw(), we manually set the terminal to raw mode while leaving ISIG enabled.
- the following code is equivalent to cfmakeraw() but with ISIG left enabled:
t_p->c_iflag &= ~(IGNBRK | BRKINT | PARMRK | INPCK | ISTRIP | INLCR |
               IGNCR | ICRNL | IXON | IXOFF);
t_p->c_lflag &= ~(ECHO | ECHONL | ICANON | IEXTEN);
t_p->c_cflag &= ~(CSIZE | PARENB);
t_p->c_cflag |= CS8 | CLOCAL;
Examples
/usr/local/src/cmenu/src/enterchr.c.
Definition at line 110 of file scriou.c.
{
    tcgetattr(0, t_p);
    t_p->c_lflag |= ISIG;
    t_p->c_lflag &= ~(ECHO | ICANON);
    t_p->c_cc[VMIN] = 1;
    t_p->c_cc[VTIME] = 0;
    tcsetattr(0, TCSAFLUSH, t_p);
    return true;
}
Referenced by main().
mk_string()
String mk_string (size_t l) extern
Create a String struct with a dynamically allocated string.
Parameters
l length of string to create including null terminator
Returns
String struct
Note
The returned String struct contains a dynamically allocated string of he specified length
See also
free_string
Note
the caller is responsible for calling free_string to free the allocated memory.
fn mk_string(size_t l) -> String Create an empty String struct with specified length
Parameters
l Length of the string (excluding null terminator)
Note
: The returned String struct contains a dynamically allocated string of length l + 1 (including null terminator).
: the caller is responsible for freeing the allocated memory.
See also
: free_string
Returns
: String struct
Definition at line 1238 of file futil.c.
{
    if (l == 0) {
        String str;
        str.l = 0;
        str.s = nullptr;
        return str;
    }
    String str;
    str.l = l + 1;
    str.s = (char *)malloc(str.l);
    str.s[0] = '\0';
    return str;
References String::l, and String::s.
Referenced by get_rfc3339_str(), and main().
mouse_getch()
void mouse_getch (int * , int * , int * , int *) extern
mvwaddstr_fill()
void mvwaddstr_fill (WINDOW * w, int y, int x, char * s, int l) extern
For lines shorter than their display area, fill the rest with spaces.
Parameters
w Pointer to window
y Y coordinate
x X coordinate
s String to display
l Length of display area
Definition at line 979 of file dwin.c.
{
    char *d, *e;
    char tmp_str[MAXLEN];
    d = tmp_str;
    if (l > MAXLEN - 1)
        l = MAXLEN - 1;
    e = tmp_str + l;
    while (d < e)
        if (*s == '\0' || *s == '\n')
            *d++ = ' ';
        else
            *d++ = *s++;
    *d++ = '\0';
    mvwaddstr(w, y, x, tmp_str);
}
References MAXLEN, and tmp_str.
Referenced by display_page(), menu_cmd_processor(), picker(), reverse_object(), and unreverse_object().
new_chyron()
Chyron * new_chyron () extern
Create and initialize Chyron structure.
Returns
pointer to new Chyron structure
This function allocates memory for a new Chyron structure and initializes the key pointers. Each key pointer is allocated memory for a ChyronKey structure. The Chyron structure is used to manage function key labels and their associated keycodes for mouse click handling in the chyron area of the interface.
Note
The use of calloc ensures that the allocated memory is initialized to zero, which means that the text for each key will be initialized to an empty string and the keycodes will be initialized to zero. This allows the is_set_chyron_key function to check if a key is set by checking if the first character of the text is not '\0'. If any memory allocation fails, the function will call abend to handle the error and return nullptr.
Definition at line 178 of file dwin.c.
                     {
    Chyron *chyron = (Chyron *)calloc(1, sizeof(Chyron));
    if (!chyron) {
        abend(-1, "calloc chyron failed");
        return nullptr;
    }
    for (int i = 0; i < CHYRON_KEYS; i++)
        chyron->key[i] = (ChyronKey *)calloc(1, sizeof(ChyronKey));
    return chyron;
}
References abend(), CHYRON_KEYS, and Chyron::key.
Referenced by display_error(), form_display_fields(), Perror(), and pick_engine().
normalize_file_spec()
bool normalize_file_spec (char * fs) extern
replace backslashes with forward lashes
Parameters
fs - file specification to normalize
Returns
true if successful, false if fs is nullptr or empty
Definition at line 492 of file futil.c.
{
    if (fs == nullptr || *fs == '\0')
        return false;
    while (*fs != '\0') {
        if (*fs == '\\')
            *fs = '/';
        fs++;
    }
    return true;
open_curses()
bool open_curses (SIO * sio) extern
Initialize NCurses and color settings.
Parameters
sio Pointer to SIO struct with terminal and color settings
Returns
true if successful, false if error note This function initializes NCurses and sets up color pairs based on the settings in the SIO struct. It also applies gamma correction to colors. Use this function to initialize NCurses if you don't want NCurses to receive data from the stdin pipe
1. saves stdin and stdout file descriptors in SIO
2. opens a terminal device for NCurses screen IO
3. replaces STDERR_FILENO with terminal file descriptor
save stdin and stdout file descriptors
open the terminal device for reading and writing
Attach the terminal descriptor to the STDERR_FILENO
We use SCREEN and newterm because this allows us to
specify the terminal FILE
Set gamma correction values
These are read from ~/.minitrc
We need these values when initializing colors
Definition at line 306 of file dwin.c.
{
    char tmp_str[MAXLEN];
    char emsg0[MAXLEN];
    int rc;
    RGB frgb, brgb;
    if (ttyname_r(STDERR_FILENO, sio->tty_name, sizeof(sio->tty_name)) != 0) {
        strerror_r(errno, tmp_str, MAXLEN - 1);
        strnz__cpy(emsg0, "ttyname_r failed ", MAXLEN - 1);
        strnz__cat(emsg0, tmp_str, MAXLEN - 1);
        fprintf(stderr, "%s\n", tmp_str);
        exit(0);
    }
    sio->stdin_fd = dup(STDIN_FILENO);
    sio->stdout_fd = dup(STDOUT_FILENO);
    sio->tty_fp = fopen(sio->tty_name, "r+");
    if (sio->tty_fp == nullptr) {
        strerror_r(errno, tmp_str, MAXLEN - 1);
        strnz__cpy(emsg0, "fopen(sio->tty_name) failed ", MAXLEN - 1);
        strnz__cat(emsg0, tmp_str, MAXLEN - 1);
        fprintf(stderr, "%s\n", tmp_str);
        exit(0);
    }
    dup2(fileno(sio->tty_fp), STDERR_FILENO);
    SCREEN *screen = newterm(nullptr, sio->tty_fp, sio->tty_fp);
    if (screen == nullptr) {
        strerror_r(errno, tmp_str, MAXLEN - 1);
        strnz__cpy(emsg0, "newterm failed ", MAXLEN - 1);
        strnz__cat(emsg0, tmp_str, MAXLEN - 1);
        fprintf(stderr, "%s\n", tmp_str);
        exit(0);
    }
    set_term(screen);
    f_curses_open = true;
    if (!has_colors()) {
        destroy_curses();
        abend(-1, "Terminal color support required");
    }
    start_color();
    if (!can_change_color()) {
        destroy_curses();
        fprintf(stderr, "Terminal cannot change colors\n");
        fprintf(stderr, "Check TERM environment variable\n");
        fprintf(stderr, "Check terminfo for missing \"ccc\"\n");
        abend(-1, "fatal error");
    }
    init_clr_palette(sio);
    RED_GAMMA = sio->red_gamma;
    GREEN_GAMMA = sio->green_gamma;
    BLUE_GAMMA = sio->blue_gamma;
    GRAY_GAMMA = sio->gray_gamma;
    cp_norm = get_clr_pair(sio->fg_color, sio->bg_color);
    cp_reverse = get_clr_pair(sio->bg_color, sio->fg_color);
    cp_box = get_clr_pair(sio->bo_color, sio->bg_color);
    CCC_NORM = mkccc(cp_norm);
    CCC_BOX = mkccc(cp_box);
    CCC_REVERSE = mkccc(cp_reverse);
    noecho();
    cbreak();
    keypad(stdscr, true);
    idlok(stdscr, false);
    idcok(stdscr, false);
#ifdef DEBUG
    immedok(stdscr, true);
#endif
    wbkgrndset(stdscr, &CCC_NORM);
    extended_pair_content(cp_norm, &sio->fg_color, &sio->bg_color);
    extended_color_content(sio->fg_color, &frgb.r, &frgb.g, &frgb.b);
    rc = extended_color_content(sio->bg_color, &brgb.r, &brgb.g, &brgb.b);
    if (rc == ERR) {
        destroy_curses();
        abend(-1, "extended_color_content failed");
    }
    return sio;
}
References abend(), RGB::b, BLUE_GAMMA, CCC_BOX, CCC_NORM, CCC_REVERSE, cp_box, cp_norm, cp_reverse, destroy_curses(), f_curses_open, RGB::g, get_clr_pair(), GRAY_GAMMA, GREEN_GAMMA, init_clr_palette(), MAXLEN, mkccc(), RGB::r, RED_GAMMA, sio, strnz__cat(), strnz__cpy(), and tmp_str.
Referenced by main().
open_log()
int open_log (char *) extern
Perror()
int Perror (char * emsg_str) extern
Display a simple error message window or print to stderr.
Parameters
emsg_str Error message string
Returns
Key code of user command
Definition at line 928 of file dwin.c.
{
    char emsg[80];
    int emsg_max_len = 80;
    unsigned cmd_key;
    WINDOW *error_win;
    int len, line, pos;
    char title[MAXLEN];
    len = strnz__cpy(emsg, emsg_str, emsg_max_len - 1);
    if (!f_curses_open) {
        fprintf(stderr, "\n%s\n", emsg);
        return (1);
    }
    Chyron *chyron = new_chyron();
    set_chyron_key(chyron, 1, "F1 Help", KEY_F(1));
    set_chyron_key(chyron, 9, "F9 Cancel", KEY_F(9));
    set_chyron_key(chyron, 10, "F10 Continue", KEY_F(10));
    compile_chyron(chyron);
    pos = (COLS - len - 4) / 2;
    line = (LINES - 4) / 2;
    if (chyron->l > len)
        len = chyron->l;
    if (len < 39)
        len = 39;
    strnz__cpy(title, "Notification", MAXLEN - 1);
    if (win_new(2, len + 2, line, pos, title, 0)) {
        ssnprintf(title, MAXLEN - 1, "win_new(%d, %d, %d, %d, %s, %b) failed",
                  4, line, line, pos, title, 0);
        destroy_chyron(chyron);
        abend(-1, title);
    }
    error_win = win_win[win_ptr];
    mvwaddstr(error_win, 0, 1, emsg);
    wattron(error_win, WA_REVERSE);
    mvwaddstr(error_win, 1, 0, chyron->s);
    wattroff(error_win, WA_REVERSE);
    wmove(error_win, 1, chyron->l);
    wrefresh(error_win);
    cmd_key = xwgetch(error_win, chyron);
    win_del();
    destroy_chyron(chyron);
    return (cmd_key);
}
References abend(), cmd_key, compile_chyron(), destroy_chyron(), f_curses_open, Chyron::l, MAXLEN, new_chyron(), Chyron::s, set_chyron_key(), ssnprintf(), strnz__cpy(), win_del(), win_new(), win_ptr, win_win, and xwgetch().
Referenced by display_curses_keys(), display_line(), exec_objects(), fork_exec(), form_accept_field(), form_calculate(), form_display_screen(), form_engine(), form_fmt_field(), form_usage(), form_validate_field(), get_cmd_arg(), go_to_line(), go_to_mark(), go_to_percent(), init_form(), init_pick(), lf_process(), menu_engine(), new_pick(), open_pick_win(), parse_menu_description(), search(), view_cmd_processor(), view_init_input(), and write_config().
rep_substring()
char * rep_substring (const char * org_s, const char * tgt_s, const char * rep_s) extern
Replace all occurrences of "tgt_s" in "org_s" with "rep_s".
Parameters
org_s - original string
tgt_s - target substring to replace
rep_s - replacement substring
Returns
A pointer to the newly allocated string with replacements or a copy of the replacement string if original string is the same as target string This is a special case that allows for replacing the entire original string. If any parameter is nullptr, the function returns nullptr. If "tgt_s" is not found in "org_s", the function returns a copy of "org_s". If target substring is not found the function returns a copy of the original string.
Note
The function allocates memory for the return value, so the caller is responsible for freeing this memory when it is no longer needed to avoid memory leaks.
The function does not modify the original string "org_s".
The function assumes that "tgt_s" and "rep_s" are null-terminated strings. If they are not, the behavior is undefined.
The function does not perform any bounds checking on the input strings, so it is the caller's responsibility to ensure that they are valid and that the resulting string does not exceed available memory.
The function uses the standard library functions strlen, strstr, malloc, and strcpy, which may have their own limitations and behaviors that the caller should be aware of.
The function does not handle overlapping occurrences of "tgt_s" in "org_s". If "tgt_s" can overlap with itself in "org_s", the behavior may be unexpected. The caller should ensure that "tgt_s" does not contain overlapping patterns to avoid this issue.
The function does not handle cases where "tgt_s" is a substring of "rep_s", which could lead to unintended consequences if "tgt_s" appears in "rep_s". The caller should ensure that "tgt_s" and "rep_s" are distinct to avoid this issue.
Definition at line 1138 of file futil.c.
{
    if (org_s == nullptr || tgt_s == nullptr || rep_s == nullptr)
        return nullptr;
    if (*org_s == '\0' || *tgt_s == '\0' || *rep_s == '\0')
        return nullptr;
    if (strstr(org_s, tgt_s) == nullptr)
        return strdup(org_s);
    if (strstr(rep_s, tgt_s) != nullptr)
        return nullptr;
    if (tgt_s == rep_s || tgt_s == org_s || rep_s == org_s)
        return strdup(org_s);
    if (strcmp(org_s, tgt_s) == 0)
        return strdup(rep_s);
    char *out_s, *ip, *tmp;
    int tgt_l = strlen(tgt_s);
    int rep_l = strlen(rep_s);
    int head_l;
    int n = 0;
    ip = (char *)org_s;
    while ((tmp = strstr(ip, tgt_s)) != nullptr) {
        n++;
        ip = tmp + tgt_l;
    }
    out_s = malloc(strlen(org_s) + (rep_l - tgt_l) * n + 1);
    if (!out_s) {
        return nullptr;
    }
    tmp = out_s;
    ip = (char *)org_s;
    while (n--) {
        char *p = strstr(ip, tgt_s);
        head_l = p - ip;
        strnz__cpy(tmp, ip, head_l);
        tmp += head_l;
        strnz__cpy(tmp, rep_s, MAXLEN - 1);
        tmp += rep_l;
        ip += head_l + tgt_l;
    }
    strnz__cpy(tmp, ip, MAXLEN - 1);
    return out_s;
References MAXLEN, and strnz__cpy().
Referenced by exec_objects().
restore_curses_tioctl()
bool restore_curses_tioctl () extern
restore_curses_tioctl() - restore curses terminal settings
Returns
- true on success
Note
- restores terminal settings for stdin, stdout, and stderr
Definition at line 70 of file scriou.c.
{
    if (!f_have_curses_tioctl)
        return false;
    tcsetattr(0, TCSANOW, &curses_tioctl);
    return true;
}
References curses_tioctl, and f_have_curses_tioctl.
Referenced by exec_objects(), fork_exec(), and init_pick().
restore_shell_tioctl()
bool restore_shell_tioctl () extern
restore_shell_tioctl() - restore shell terminal settings
Returns
- true on success
Note
- restores terminal settings for stdin, stdout, and stderr
Examples
/usr/local/src/cmenu/src/enterchr.c, and /usr/local/src/cmenu/src/enterstr.c.
Definition at line 51 of file scriou.c.
{
    if (!f_have_shell_tioctl)
        return false;
    tcsetattr(0, TCSANOW, &shell_tioctl);
    return true;
}
References f_have_shell_tioctl, and shell_tioctl.
Referenced by abend(), destroy_curses(), fork_exec(), handle_signal(), main(), and user_end().
restore_wins()
void restore_wins () extern
Restore all windows after a screen resize.
Note
This function is used to restore the display of all windows after a screen resize event. It clears the standard screen and then iterates through all existing windows, touching and refreshing them to ensure they are redrawn correctly on the resized screen. Use this function in response to a SIGWINCH signal to handle terminal resizing gracefully.
Definition at line 797 of file dwin.c.
                    {
    int i;
    wclear(stdscr);
    touchwin(stdscr);
    wnoutrefresh(stdscr);
    for (i = 0; i <= win_ptr; i++) {
        touchwin(win_box[i]);
        wnoutrefresh(win_box[i]);
        touchwin(win_win[i]);
        wnoutrefresh(win_win[i]);
    }
}
References win_box, win_ptr, and win_win.
Referenced by exec_objects(), fork_exec(), form_engine(), full_screen_fork_exec(), full_screen_shell(), menu_cmd_processor(), resize_page(), and view_cmd_processor().
rgb_clr_to_cube()
int rgb_clr_to_cube (int) extern
References errmsg.
rgb_to_curses_clr()
int rgb_to_curses_clr (RGB * rgb) extern
Get color index for RGB color.
Parameters
rgb RGB color
Returns
NCurses color index
Note
Curses uses 0-1000 for RGB values
If the color does not exist, it is created along with a new color index
Definition at line 425 of file dwin.c.
{
    int i;
    int r, g, b;
    apply_gamma(rgb);
    rgb->r = (rgb->r * 1000) / 255;
    rgb->g = (rgb->g * 1000) / 255;
    rgb->b = (rgb->b * 1000) / 255;
    for (i = 0; i < clr_cnt; i++) {
        extended_color_content(i, &r, &g, &b);
        if (rgb->r == r && rgb->g == g && rgb->b == b) {
            return i;
        }
    }
    if (i < COLORS) {
        init_extended_color(i, rgb->r, rgb->g, rgb->b);
        clr_cnt++;
        return clr_cnt - 1;
    }
    return ERR;
}
References apply_gamma(), RGB::b, clr_cnt, RGB::g, and RGB::r.
Referenced by parse_ansi_str().
rgb_to_xterm256_idx()
int rgb_to_xterm256_idx (RGB * rgb) extern
Convert RGB color to XTerm 256 color index.
Parameters
rgb RGB color
Returns
XTerm 256 color index note This function converts an RGB color to the nearest XTerm 256 color index. It first checks if the color is a shade of gray, and if so, it uses the gray ramp. Otherwise, it calculates the nearest color in the 6x6x6 color cube.
Definition at line 453 of file dwin.c.
{
    if (rgb->r == rgb->g && rgb->g == rgb->b) {
        if (rgb->r < 8)
            return 16;
        if (rgb->r > 248)
            return 231;
        return ((rgb->r - 8) / 10) + 231;
    } else {
        int r_index = (rgb->r < 45) ? 0 : (rgb->r - 60) / 40 + 1;
        int g_index = (rgb->g < 45) ? 0 : (rgb->g - 60) / 40 + 1;
        int b_index = (rgb->b < 45) ? 0 : (rgb->b - 60) / 40 + 1;
        return 16 + (36 * r_index) + (6 * g_index) + b_index;
    }
}
References RGB::b, RGB::g, and RGB::r.
rtrim()
size_t rtrim (char * s) extern
Trims trailing spaces from string s in place.
Parameters
s - string to trim
Returns
length of trimmed string
Definition at line 68 of file futil.c.
                      {
    if (s == nullptr || *s == '\0')
        return 0;
    char *p = s;
    char *d = s;
    while (*p != '\0')
        *d++ = *p++;
    while (*(d - 1) == ' ' && d > s)
        d--;
    *d = '\0';
    return (size_t)(d - s);
}
Referenced by fmt_line().
segmentation_fault()
int segmentation_fault () extern
Function to intentionally cause a segmentation fault for testing purposes.
Returns
0 (this line will not be reached due to the segmentation fault)
Definition at line 1341 of file futil.c.
{
    int *p = NULL;
    *p = 100;
    return 0;
set_chyron_key()
void set_chyron_key (Chyron * chyron, int k, char * s, int kc) extern
Set chyron key.
Parameters
chyron structure
k chyron key index (0-19)
s chyron key label
kc chyron key code
This function sets the label and keycode for a chyron key. The label is copied into the chyron structure, and the keycode is stored for later retrieval when theire is a mouse click. The compile_chyron function uses the keycode values to determine which key was clicked based on the mouse X position. If the label string is empty, the key is unset by setting the first character of the text to '\0'.
Definition at line 228 of file dwin.c.
{
    size_t y;
    size_t x = sizeof(chyron->key[k]->text);
    y = x;
    x = y;
    if (*s != '\0')
        ssnprintf(chyron->key[k]->text, CHYRON_KEY_MAXLEN - 1, "%s", s);
    else
        chyron->key[k]->text[0] = '\0';
    chyron->key[k]->keycode = kc;
}
References CHYRON_KEY_MAXLEN, Chyron::key, ChyronKey::keycode, ssnprintf(), and ChyronKey::text.
Referenced by display_error(), form_accept_field(), form_calculate(), form_display_fields(), form_end_fields(), Perror(), and pick_engine().
set_sane_tioctl()
bool set_sane_tioctl (struct termios * t_p) extern
set_sane_tioctl() - set terminal to sane settings for C-MENU
Parameters
t_p - pointer to termios structure to modify
Returns
- true on success
Note
- sets terminal to sane settings for C-MENU applications
Definition at line 80 of file scriou.c.
{
    tcgetattr(0, t_p);
    t_p->c_iflag &= ~(IGNBRK | BRKINT | PARMRK | INPCK | ISTRIP | INLCR |
                      IGNCR | ICRNL | IXON | IXOFF);
    t_p->c_iflag |= IUTF8;
    t_p->c_oflag |= OPOST | OCRNL;
    t_p->c_lflag &= ~(ECHO | ECHONL | ICANON | IEXTEN);
    t_p->c_lflag |= (ISIG | ICANON | IEXTEN | ECHO | ECHOE | ECHOK);
    t_p->c_cflag &= ~(CSIZE | PARENB);
    t_p->c_cflag |= CS8 | CLOCAL | CREAD;
    tcsetattr(0, TCSANOW, t_p);
    return true;
}
shell()
int shell (char * shellCmdPtr) extern
Execute a shell command.
Parameters
shellCmdPtr - pointer to the shell command string
Returns
the return code from the executed shell command
Note
Executes the command string using the user's shell.
If the SHELL environment variable is not set, use /bin/sh.
Definition at line 77 of file exec.c.
{
    int Eargc;
    char *Eargv[MAXARGS];
    char *shellPtr;
    int rc;
    Eargc = 0;
    shellPtr = getenv("SHELL");
    if (shellPtr == nullptr || *shellPtr == '\0')
        shellPtr = DEFAULTSHELL;
    Eargv[Eargc++] = strdup(shellPtr);
    Eargv[Eargc++] = "-c";
    Eargv[Eargc++] = shellCmdPtr;
    Eargv[Eargc++] = nullptr;
    rc = fork_exec(Eargv);
    free(Eargv[0]);
    return (rc);
}
References DEFAULTSHELL, fork_exec(), and MAXARGS.
Referenced by form_exec_cmd(), full_screen_shell(), lp(), and view_cmd_processor().
sig_dfl_mode()
void sig_dfl_mode () extern
Set signal handlers to default behavior.
Examples
/usr/local/src/cmenu/src/enterstr.c.
Definition at line 23 of file sig.c.
                    {
    struct sigaction sa;
    sa.sa_handler = SIG_DFL;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = SA_RESTART;
    sigaction(SIGINT, &sa, nullptr);
    sigaction(SIGTERM, &sa, nullptr);
    sigaction(SIGQUIT, &sa, nullptr);
    sigaction(SIGUSR1, &sa, nullptr);
    sa.sa_flags = SA_SIGINFO;
    sigaction(SIGSEGV, &sa, nullptr);
}
Referenced by abend(), destroy_curses(), fork_exec(), main(), and user_end().
sig_prog_mode()
void sig_prog_mode () extern
Set up signal handlers for interrupt signals.
Upon receiving an interrupt signal (SIGINT, SIGTERM, SIGQUIT), the program will prompt the user to either exit the program or continue execution. If the user chooses to exit, a confirmation prompt will be displayed. If the user opts to continue, the program will resume normal operation.
Examples
/usr/local/src/cmenu/src/enterstr.c.
Definition at line 42 of file sig.c.
                     {
    struct sigaction sa;
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = signal_handler;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = SA_RESTART;
    if (sigaction(SIGINT, &sa, nullptr) == -1) {
        abend(-1, "sigaction SIGINT failed");
        exit(EXIT_FAILURE);
    }
    if (sigaction(SIGTERM, &sa, nullptr) == -1) {
        abend(-1, "sigaction SIGTERM failed");
        exit(EXIT_FAILURE);
    };
    if (sigaction(SIGQUIT, &sa, nullptr) == -1) {
        abend(-1, "sigaction SIGQUIT failed");
        exit(EXIT_FAILURE);
    }
    if (sigaction(SIGUSR1, &sa, nullptr) == -1) {
        abend(-1, "sigaction SIGUSR1 failed");
        exit(EXIT_FAILURE);
    }
    sa.sa_flags = SA_SIGINFO; // Set the flag to receive siginfo_t
    if (sigaction(SIGSEGV, &sa, nullptr) == -1) {
        abend(-1, "sigaction SIGSEGV failed");
        exit(EXIT_FAILURE);
    }
}
References abend(), and signal_handler().
Referenced by exec_objects(), fork_exec(), init_pick(), and main().
sig_shell_mode()
void sig_shell_mode () extern
signal_handler()
void signal_handler (int sig_num) extern
Signal handler for interrupt signals.
Definition at line 72 of file sig.c.
{
    switch (sig_num) {
    case SIGINT:
        sig_received = SIGINT;
        break;
    case SIGTERM:
        sig_received = SIGTERM;
        break;
    case SIGQUIT:
        sig_received = SIGQUIT;
        break;
    case SIGSEGV:
        tcsetattr(0, TCSANOW, &shell_tioctl);
        char *msg1 = "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n";
        write(STDERR_FILENO, msg1, strlen(msg1));
        char *msg2 = "________ SIGSEGV - Segmentation fault - Generating core "
                     "dump ________\n\n";
        write(STDERR_FILENO, msg2, strlen(msg2));
        struct sigaction sa;
        sa.sa_handler = SIG_DFL;
        sigemptyset(&sa.sa_mask);
        sa.sa_flags = 0;
        sigaction(SIGSEGV, &sa, NULL);
        kill(getpid(), SIGSEGV); // Re-raise the signal
        _exit(EXIT_FAILURE);
    case SIGUSR1:
        sig_received = SIGUSR1;
        break;
    default:
        return;
    }
}
References shell_tioctl, and sig_received.
Referenced by sig_prog_mode().
ssnprintf()
size_t ssnprintf (char * buf, size_t buf_size, const char * format, ...) extern
ssnprintf was designed to be a safer alternative to snprintf.
It ensures that the buffer is not overflowed by taking the buffer size as a parameter and using vsnprintf internally. It also returns the number of characters that would have been written if enough space had been available, allowing the caller to detect truncation. This function is particularly useful in situations where the formatted string may exceed the buffer size, as it prevents buffer overflows and provides a way to handle such cases gracefully.
Parameters
buf - buffer to receive formatted string
buf_size - size of buffer
format - printf-style format string
... - arguments
Returns
number of characters that would have been written if enough space had been available
Definition at line 111 of file futil.c.
{
    size_t n;
    va_list args;
    va_start(args, format);
    n = vsnprintf(buf, buf_size, format, args);
    va_end(args);
    return n;
}
Referenced by display_error(), enter_file_spec(), fork_exec(), form_calculate(), form_desc_error(), form_parse_desc(), form_write(), get_clr_pair(), handle_signal(), init_view_boxwin(), init_view_full_screen(), lf_find(), lf_process(), mapp_initialization(), menu_engine(), mk_dir(), new_init(), new_pick(), new_view(), open_pick_win(), parse_menu_description(), Perror(), pick_display_chyron(), search(), set_chyron_key(), verify_dir(), verify_file(), view_cmd_processor(), view_init_input(), and write_view_buffer().
str_subc()
bool str_subc (char * d, char * s, char ReplaceChr, char * Withstr, int l) extern
Replaces "ReplaceChr" in "s" with "Withstr" in "d" won't copy more than "l" bytes to "d" Replaces all occurrences of a character in a string with another string, copying the result to a destination buffer. It ensures that the total length of the resulting string does not exceed the specified limit, and that the result is null-terminated. This function is useful for simple string substitutions where you want to replace a single character with a longer string, such as replacing spaces with underscores or tabs with spaces.
Parameters
d - destination string
s - source string
ReplaceChr - character to replace
Withstr - string to insert
l - maximum length to copy
Returns
true if successful, false if any parameter is invalid
Note
The caller must ensure that "d" has enough space to receive the result, and that "l" is sufficient to hold the result. This function does not perform any bounds checking on "d" or "Withstr", so it is the caller's responsibility to ensure that they are valid and that "l" is appropriate for the operation.
Definition at line 353 of file futil.c.
{
    char *e;
    if (s == nullptr || d == nullptr || Withstr == nullptr || l == 0) {
        if (d != nullptr && l > 0)
            *d = '\0';
        return false;
    }
    e = d + l;
    while (*s != '\0' && d < e) {
        if (*s == ReplaceChr) {
            while (*Withstr != '\0' && d < e)
                *d++ = *Withstr++;
            s++;
        } else
            *d++ = *s++;
    }
    *d = '\0';
    return true;
}
Referenced by view_cmd_processor().
str_to_args()
int str_to_args (char ** argv, char * arg_str, int max_args) extern
Converts a string into an array of argument strings.
Note
Handles quoted strings and escaped quotes, preserving text inside quotes as individual arguments. It has been in service for many years without problems.
Parameters
argv - array of pointers to arguments
arg_str - string containing arguments
max_args - maximum number of arguments to parse
Returns
argc, a count of allocated vectors in argv
Note
the caller is responsible for deallocating the strings in argv
Definition at line 130 of file futil.c.
{
    if (arg_str == nullptr || *arg_str == '\0')
        return 0;
    int argc = 0;
    char *p = arg_str;
    char tmp_str[MAXLEN];
    int in_quotes = 0;
    char *d = tmp_str;
    while (*p != '\0' && argc < max_args) {
        while (isspace((unsigned char)*p))
            p++;
        if (*p == '\0')
            break;
        if (*p == '"') {
            in_quotes = 1;
            p++;
        }
        while (*p != '\0') {
            if (in_quotes) {
                if (*p == '\\' && *(p + 1) == '"') {
                    *d++ = '"';
                    p += 2;
                } else if (*p == '"') {
                    *d++ = '\0';
                    p++;
                    in_quotes = 0;
                    break;
                } else
                    *d++ = *p++;
            } else {
                if (isspace((unsigned char)*p)) {
                    *d++ = '\0';
                    p++;
                    break;
                } else
                    *d++ = *p++;
            }
        }
        *d = '\0';
        d = tmp_str;
        argv[argc++] = strdup(tmp_str);
    }
    argv[argc] = nullptr;
    return argc;
}
References MAXLEN, and tmp_str.
Referenced by enter_file_spec(), exec_objects(), form_calculate(), init_pick(), menu_cmd_processor(), and view_init_input().
str_to_bool()
bool str_to_bool (const char * s) extern
Converts String to boolean true or false.
Parameters
s - string to convert
Returns
boolean true or false
Definition at line 577 of file futil.c.
{
    if (s == nullptr || *s == '\0')
        return false;
    switch (s[0]) {
    case 't':
    case 'T':
    case 'y':
    case 'Y':
    case '1':
        return true;
    case 'o':
    case 'O':
        switch (s[1]) {
        case 'n':
        case 'N':
            return true;
        default:
            break;
        }
    default:
        break;
    }
    return false;
Referenced by parse_config().
str_to_double()
double str_to_double (char * s) extern
converts string to double
Parameters
s - string to convert
Returns
converted double value, or 0.0 if s is nullptr, empty, or invalid
Deprecated
If the string is invalid, this function returns 0.0, with no indication of error.
Note
The caller must ensure that the string is a valid representation of a double before calling this function.
Definition at line 565 of file futil.c.
{
    char *e;
    double d;
    if (!s || !*s)
        return false;
    d = strtod(s, &e);
    return d;
Referenced by parse_config(), and parse_opt_args().
str_to_lower()
bool str_to_lower (char * s) extern
Converts a string to lowercase.
Parameters
s - string to convert
Returns
true if successful, false if s is nullptr or empty
Definition at line 179 of file futil.c.
{
    if (s == nullptr || *s == '\0')
        return false;
    while (*s != '\0') {
        if (*s >= 'A' && *s <= 'Z')
            *s = *s + 'a' - 'A';
        s++;
    }
    return true;
}
Referenced by clr_name_to_idx(), form_parse_desc(), and prompt_str_to_int().
str_to_upper()
bool str_to_upper (char * s) extern
Converts a string to uppercase.
Parameters
s - string to convert
Returns
true if successful, false if s is nullptr or empty
Definition at line 192 of file futil.c.
{
    if (s == nullptr || *s == '\0')
        return false;
    while (*s != '\0') {
        if (*s >= 'a' && *s <= 'z')
            *s = *s + 'A' - 'a';
        s++;
    }
    return true;
}
string_cat()
size_t string_cat (String * dest, const String * src) extern
Concatenates src String to dest String, allocating additional memory for dest String if necessary.
Parameters
dest - destination String struct
src - source String struct
Returns
new length of dest String after concatenation
Note
the caller is responsible for freeing the allocated memory.
Definition at line 1286 of file futil.c.
{
    if (dest == nullptr || src == nullptr || src->s == nullptr)
        return 0;
    size_t new_len = strlen(dest->s) + strlen(src->s) + 1;
    if (dest->l < new_len) {
        dest->s = (char *)realloc(dest->s, new_len);
        dest->l = new_len;
    }
    strcat(dest->s, src->s);
    return new_len;
References String::l, and String::s.
Referenced by main().
string_cpy()
size_t string_cpy (String * dest, const String * src) extern
Copy src String to dest String, allocating additional memory for dest String if necessary.
Parameters
dest - destination String struct
src - source String struct
Returns
length of dest String
Note
the caller is responsible for freeing the allocated memory.
Definition at line 1270 of file futil.c.
{
    if (dest == nullptr || src == nullptr || src->s == nullptr)
        return 0;
    if (dest->l < src->l) {
        dest->s = (char *)realloc(dest->s, src->l);
        dest->l = src->l;
    }
    strcpy(dest->s, src->s);
    return src->l;
References String::l, and String::s.
string_ncat()
size_t string_ncat (String * dest, const String * src, size_t n) extern
Concatenates up to n characters from src String to dest String, allocating additional memory for dest String if necessary.
Parameters
dest - destination String struct
src - source String struct
n - maximum number of characters to concatenate
Returns
new length of dest String after concatenation
Note
the caller is responsible for freeing the allocated memory.
Definition at line 1304 of file futil.c.
{
    if (dest == nullptr || src == nullptr || src->s == nullptr)
        return 0;
    size_t dest_len = strlen(dest->s);
    size_t src_len = strlen(src->s);
    size_t cat_len = (n < src_len) ? n : src_len;
    size_t new_len = dest_len + cat_len + 1;
    if (dest->l < new_len) {
        dest->s = (char *)realloc(dest->s, new_len);
        dest->l = new_len;
    }
    strncat(dest->s, src->s, cat_len);
    return new_len;
References String::l, and String::s.
Referenced by main().
string_ncpy()
size_t string_ncpy (String * dest, const String * src, size_t n) extern
copies up to n characters from src String to dest String, allocating additional memory for dest String if necessary
Parameters
dest - destination String struct
src - source String struct
n - maximum number of characters to copy
Note
the caller is responsible for freeing the allocated memory.
Definition at line 1324 of file futil.c.
{
    if (dest == nullptr || src == nullptr || src->s == nullptr)
        return 0;
    size_t src_len = strlen(src->s);
    size_t cpy_len = (n < src_len) ? n : src_len;
    size_t new_len = cpy_len + 1;
    if (dest->l < new_len) {
        dest->s = (char *)realloc(dest->s, new_len);
        dest->l = new_len;
    }
    strncpy(dest->s, src->s, cpy_len);
    dest->s[cpy_len] = '\0';
    return new_len;
References String::l, and String::s.
strip_ansi()
size_t strip_ansi (char * d, char * s) extern
Strips ANSI SGR escape sequences (ending in 'm') from string s to d.
Parameters
d Destination string
s Source string
Returns
Length of stripped string
    char dest[1024];
    char src[] = "\033[31mThis is red text\033[0m
    size_t len = strip_ansi(dest, src);
    Result: dest = "This is red text", len = 17
@example stripansi.c
Note
Only handles SGR sequences ending in 'm' or 'K'
Skips non-ASCII characters
The caller must ensure that d has enough space to hold the stripped string
This function does not allocate memory; it assumes d is pre-allocated
This function processes the entire string until the null terminator
This function does not modify the source string s
Definition at line 469 of file futil.c.
{
    size_t l = 0;
    while (*s) {
        if (*s == '\033') {
            while (*s && *s != 'm' && *s != 'K')
                s++;
            if (*s == 'm' || *s == 'K')
                s++;
            continue;
        } else {
            if ((unsigned char)*s <= 127) {
                *d++ = *s++;
                l++;
            } else
                s++;
        }
    }
    *d = '\0';
    return l;
Referenced by main(), and write_view_buffer().
strip_quotes()
bool strip_quotes (char * s) extern
removes leading and trailing double quotes if present
Parameters
s - string to strip quotes from
Returns
true if successful, false if s is nullptr or empty
Definition at line 390 of file futil.c.
{
    if (s == nullptr)
        return false;
    int l = strlen(s);
    if (l > 1 && s[l - 1] == '\"') {
        memmove(s, s + 1, l - 2);
        s[l - 2] = '\0';
    }
    return true;
}
Referenced by init_form_files(), and init_view_files().
stripz_quotes()
bool stripz_quotes (char * s) extern
removes leading and trailing double quotes if present
Parameters
s - string to strip quotes from
Returns
true if quotes were removed
Note
Same as STRIP_QUOTES but returns true if quotes were removed
Definition at line 404 of file futil.c.
{
    if (s == nullptr || strlen(s) < 2)
        return false;
    int l = strlen(s);
    if (l > 1 && s[0] == '\"' && s[l - 1] == '\"') {
        memmove(s, s + 1, l - 2);
        s[l - 2] = '\0';
        return true;
    }
    return false;
}
Referenced by verify_spec_arg().
strnfill()
bool strnfill (char * s, char c, int n) extern
Fills string s with character c n.
Parameters
s - string to fill
c - character to fill with
n - number of characters to fill
Returns
true if successful, false if s is nullptr or n is non-positive
Definition at line 377 of file futil.c.
{
    if (s == nullptr || n <= 0)
        return false;
    char *e;
    e = s + n;
    while (s < e)
        *s++ = c;
    *s = '\0';
    return true;
}
Referenced by form_display_fields().
strnlf()
size_t strnlf (char * s, size_t max_len) extern
terminates string with line feed
Parameters
s string to terminate
max_len maximum length to scan
Returns
length of resulting string
Definition at line 298 of file futil.c.
{
    char *e;
    size_t len = 0;
    if (s == nullptr || *s == '\0' || max_len == 0)
        return 0;
    e = s + max_len;
    while (*s != '\0' && *s != '\n' && *s != '\r' && s < e) {
        s++;
        len++;
    }
    *s++ = '\n';
    len++;
    *s = '\0';
    return (len);
}
Referenced by write_view_buffer().
strnz()
size_t strnz (char * s, size_t max_len) extern
terminates string at New Line, Carriage Return, or max_len
Note
The use case is to ensure that strings read from files or user input do not contain embedded newlines or carriage returns.
Parameters
s string to terminate
max_len - maximum length to scan
Returns
length of resulting string
Definition at line 281 of file futil.c.
{
    char *e;
    size_t len = 0;
    if (s == nullptr || *s == '\0' || max_len == 0)
        return 0;
    e = s + max_len;
    while (*s != '\0' && *s != '\n' && *s != '\r' && s < e) {
        s++;
        len++;
    }
    *s = '\0';
    return (len);
}
Referenced by display_error(), enter_file_spec(), form_display_fields(), form_display_screen(), form_fmt_field(), and pick_engine().
strnz__cat()
size_t strnz__cat (char * d, const char * s, size_t max_len) extern
safer alternative to strncat
Note
It appends string s to d, ensuring that the total length of d does not exceed max_len, and that the resulting string is null-terminated. It also treats newline and carriage return characters as string terminators, preventing them from being included in the result. This is particularly useful when concatenating user input or file data, where embedded newlines could cause issues.
Parameters
d - destination string
s - source string
max_len - maximum length to copy
Returns
length of resulting string
Definition at line 241 of file futil.c.
{
    char *e;
    size_t len = 0;
    if (s == nullptr || d == nullptr || max_len == 0) {
        if (d != nullptr && max_len > 0)
            *d = '\0';
        return 0;
    }
    e = d + max_len;
    while (*d != '\0' && *d != '\n' && *d != '\r' && d < e) {
        d++;
        len++;
    }
    while (*s != '\0' && *s != '\n' && *s != '\r' && d < e) {
        *d++ = *s++;
        len++;
    }
    *d = '\0';
    return len;
}
Referenced by build_prompt(), compile_chyron(), derive_file_spec(), display_curses_keys(), enter_file_spec(), exec_objects(), expand_tilde(), file_spec_parts(), form_calculate(), form_display_screen(), form_exec_cmd(), form_parse_desc(), form_read_data(), form_write(), init_form(), init_menu_files(), init_pick(), lf_process(), locate_file_in_path(), menu_cmd_processor(), mk_dir(), open_curses(), output_objects(), parse_menu_description(), search(), verify_spec_arg(), view_cmd_processor(), view_init_input(), whence(), write_config(), and write_view_buffer().
strnz__cpy()
size_t strnz__cpy (char * d, const char * s, size_t max_len) extern
safer alternative to strncpy
Note
It copies string s to d, ensuring that the total length of d does not exceed max_len, and that the resulting string is null-terminated. It also treats newline and carriage return characters as string terminators, preventing them from being included in the result. This is particularly useful when copying user input or file data, where embedded newlines could cause issues.
Parameters
d - destination string
s - source string
max_len - maximum length to copy
Returns
length of resulting string
Definition at line 213 of file futil.c.
{
    char *e;
    size_t len = 0;
    if (s == nullptr || d == nullptr || max_len == 0) {
        if (d != nullptr && max_len > 0)
            *d = '\0';
        return 0;
    }
    e = d + max_len;
    while (*s != '\0' && *s != '\n' && *s != '\r' && d < e) {
        *d++ = *s++;
        len++;
    }
    *d = '\0';
    return len;
}
Referenced by build_prompt(), canonicalize_file_spec(), cmd_line_prompt(), derive_file_spec(), dir_name(), display_curses_keys(), display_error(), display_pick_help(), enter_file_spec(), exec_objects(), expand_tilde(), file_spec_parts(), form_calculate(), form_desc_error(), form_display_screen(), form_engine(), form_exec_cmd(), form_fmt_field(), form_parse_desc(), form_read_data(), form_write(), get_cmd_arg(), handle_signal(), init_form(), init_form_files(), init_menu_files(), init_pick(), init_pick_files(), init_view_boxwin(), init_view_files(), lf_process(), locate_file_in_path(), main(), mapp_initialization(), menu_cmd_processor(), mk_dir(), new_form(), open_curses(), output_objects(), parse_config(), parse_menu_description(), parse_opt_args(), Perror(), prompt_int_to_str(), rep_substring(), save_object(), search(), verify_dir(), verify_file(), verify_spec_arg(), view_cmd_processor(), view_display_help(), view_init_input(), whence(), win_new(), write_config(), and write_view_buffer().
strnz_dup()
char * strnz_dup (char * s, size_t l) extern
Allocates memory for and duplicates string s up to length l or until line feed or carriage return.
Parameters
s - string to duplicate
l - maximum length to copy
Returns
pointer to allocated memory
Definition at line 318 of file futil.c.
{
    char *p, *rs, *e;
    size_t m;
    if (s == nullptr || *s == '\0' || l == 0)
        return nullptr;
    for (p = s, m = 1; *p != '\0'; p++, m++)
        ;
    rs = p = (char *)malloc(m);
    if (rs != nullptr) {
        e = rs + l;
        while (*s != '\0' && *s != '\n' && *s != '\r' && p < e)
            *p++ = *s++;
        *p = '\0';
    }
    return rs;
}
to_string()
String to_string (const char * s) extern
Convert C string to String struct.
Parameters
s C string
Returns
String struct containing dynamically allocated copy of input string
Note
the caller is responsible for freeing the allocated memory.
fn to_string(const char *s) -> String Convert C string to String struct
Parameters
s C string
Note
: The returned String struct contains a dynamically allocated copy of the input string.
: the caller is responsible for freeing the allocated memory.
See also
: free_string
Returns
: String struct
Definition at line 1217 of file futil.c.
{
    if (s == nullptr) {
        String str;
        str.l = 0;
        str.s = nullptr;
        return str;
    }
    String str;
    str.l = strlen(s) + 1;
    str.s = (char *)malloc(str.l);
    strcpy(str.s, s);
    return str;
References String::l, and String::s.
Referenced by main().
trim()
size_t trim (char * s) extern
Trims leading and trailing spaces from string s in place.
Parameters
s - string to trim
Returns
length of trimmed string
Definition at line 83 of file futil.c.
                     {
    if (s == nullptr || *s == '\0')
        return 0;
    char *p = s;
    char *d = s;
    while (*p == ' ')
        p++;
    while (*p != '\0')
        *d++ = *p++;
    while (*(d - 1) == ' ' && d > s)
        d--;
    *d = '\0';
    return (size_t)(d - s);
}
Referenced by form_fmt_field(), form_parse_desc(), left_justify(), parse_menu_description(), and right_justify().
trim_ext()
bool trim_ext (char * buf, char * filename) extern
trims the file extension from "filename" and copies the result to "buf"
Parameters
buf - buffer to receive result
filename - filename to trim
Note
The caller is responsible for ensuring that "buf" has enough space to receive the result.
Definition at line 666 of file futil.c.
{
    if (!filename || !*filename || !buf)
        return false;
    char *s = filename;
    char *d = buf;
    *d = '\0';
    while (*s)
        s++;
    while (filename < --s) {
        if (*s == '.') {
            break;
        }
    }
    if (*s != '.') {
        while (*filename)
            *d++ = *filename++;
    } else {
        while (filename < s) {
            *d++ = *filename++;
        }
    }
    *d = '\0';
    if (d == buf)
        return false;
    return true;
trim_path()
bool trim_path (char * dir) extern
Trims trailing spaces and slashes from directory path in place.
Parameters
dir - directory path to trim
Returns
true if successful
Definition at line 639 of file futil.c.
{
    if (!dir)
        return false;
    char *p;
    if (!dir || !*dir)
        return false;
    p = dir;
    while (*p++ != '\0') {
        if (*p == ' ' || *p == '\t' || *p == '\n') {
            *p = '\0';
            break;
        }
    }
    --p;
    while (--p > dir && *p == '/') {
        if (*(p - 1) != '~')
            *p = '\0';
    }
    return true;
Referenced by derive_file_spec().
unset_chyron_key()
void unset_chyron_key (Chyron * chyron, int k) extern
Unset chyron key.
Parameters
chyron structure
k chyron_key index
Definition at line 243 of file dwin.c.
{ chyron->key[k]->text[0] = '\0'; }
References Chyron::key, and ChyronKey::text.
Referenced by form_calculate(), and form_end_fields().
user_end()
void user_end () extern
Program terminated by user.
Definition at line 1046 of file dwin.c.
                {
    destroy_curses();
    restore_shell_tioctl();
    sig_dfl_mode();
    fprintf(stderr, "Normal program exit");
    fprintf(stderr, "\n");
    exit(EXIT_SUCCESS);
}
References destroy_curses(), restore_shell_tioctl(), and sig_dfl_mode().
verify_dir()
bool verify_dir (char * spec, int imode) extern
Verifies that the directory specified by "spec" exists and is accessible with the permissions specified by "imode".
Parameters
spec - directory specification
imode - access mode F_OK - existence R_OK - read W_OK - Write X_OK - Execute S_WCOK - Write or Create S_QUIET - Suppress Error Messages
Note
S_WCOK and S_QUIET are stripped before calling faccessat
Returns
true if successful
Definition at line 763 of file futil.c.
{
    if (spec == nullptr || *spec == '\0')
        return false;
    expand_tilde(spec, MAXLEN);
    struct stat sb;
    errno = 0;
    src_line = 0;
    int mode = imode & ~(S_WCOK | S_QUIET);
    if (faccessat(AT_FDCWD, spec, mode, AT_EACCESS) != 0) {
        src_line = __LINE__ - 2;
        src_name = __FILE__;
        strnz__cpy(fn, "faccessat", MAXLEN - 1);
    } else {
        if (fstatat(AT_FDCWD, spec, &sb, 0) != 0) {
            src_line = __LINE__ - 1;
            src_name = __FILE__;
            strnz__cpy(fn, "fstatat", MAXLEN - 1);
        } else {
            if ((sb.st_mode & S_IFMT) != S_IFDIR) {
                src_line = __LINE__ - 1;
                src_name = __FILE__;
                strnz__cpy(fn, "verify_file", MAXLEN - 1);
                strnz__cpy(em2, "Not a regular file.", MAXLEN - 1);
            }
        }
    }
    if (src_line != 0) {
        if (!(mode & S_QUIET)) {
            ssnprintf(em0, MAXLEN - 1, "%s failed in %s at line %d", fn,
                      src_name, src_line);
            strnz__cpy(em1, spec, MAXLEN - 1);
            strnz__cpy(em3, "Check the file", MAXLEN - 1);
            display_error(em0, em1, em2, em3);
        }
        return false;
    }
    return true;
References display_error(), em0, em1, em2, em3, expand_tilde(), fn, MAXLEN, S_QUIET, S_WCOK, src_line, src_name, ssnprintf(), and strnz__cpy().
Referenced by mapp_initialization(), mk_dir(), and verify_spec_arg().
verify_dir_q()
bool verify_dir_q (char * , int) extern
verify_file()
bool verify_file (char * in_spec, int imode) extern
Verifies that the file specified by "in_spec" exists and is accessible with the permissions specified by "imode".
Parameters
in_spec - directory specification
imode - access mode F_OK - existence R_OK - read W_OK - Write X_OK - Execute S_WCOK - Write or Create S_QUIET - Suppress Error Messages
Note
S_WCOK and S_QUIET are stripped before calling faccessat
Returns
true if successful
Definition at line 813 of file futil.c.
{
    if (in_spec == nullptr || *in_spec == '\0')
        return false;
    struct stat sb;
    char spec[MAXLEN];
    strnz__cpy(spec, in_spec, MAXLEN - 1);
    int mode = imode & ~(S_WCOK | S_QUIET);
    errno = 0;
    src_line = 0;
    canonicalize_file_spec(spec);
    expand_tilde(spec, MAXLEN);
    if ((faccessat(AT_FDCWD, spec, mode, AT_EACCESS)) != 0) {
        src_line = __LINE__ - 1;
        src_name = __FILE__;
        strnz__cpy(fn, "faccessat", MAXLEN - 1);
    } else {
        if ((fstatat(AT_FDCWD, spec, &sb, 0)) != 0) {
            src_line = __LINE__ - 1;
            src_name = __FILE__;
            strnz__cpy(fn, "fstatat", MAXLEN - 1);
        } else {
            if ((sb.st_mode & S_IFMT) != S_IFREG) {
                src_line = __LINE__ - 1;
                src_name = __FILE__;
                strnz__cpy(fn, "verify_file", MAXLEN - 1);
                strnz__cpy(em2, "Not a regular file.", MAXLEN - 1);
            }
        }
    }
    if (src_line != 0) {
        if (imode & S_QUIET)
            return false;
        ssnprintf(em0, MAXLEN - 1, "%s failed in %s at line %d", fn, src_name,
                  src_line);
        strnz__cpy(em1, spec, MAXLEN - 1);
        strnz__cpy(em3, "Check the file", MAXLEN - 1);
        display_error(em0, em1, em2, em3);
        return false;
    }
    return true;
References canonicalize_file_spec(), display_error(), em0, em1, em2, em3, expand_tilde(), fn, MAXLEN, S_QUIET, S_WCOK, src_line, src_name, ssnprintf(), and strnz__cpy().
Referenced by verify_spec_arg().
verify_file_q()
bool verify_file_q (char * , int) extern
verify_spec_arg()
bool verify_spec_arg (char * spec, char * org_spec, char * dir, char * alt_dir, int mode) extern
Verify file specification argument.
Parameters
spec - menu->spec, form->spec, etc.
org_spec - init->._spec | argv[optind]
dir - init->._. directory
alt_dir - literal, "~/menuapp/data", etc.
mode - R_OK, W_OK, X_OK, WC_OK, S_QUIET
Note
mode is a bitwise OR of the following flags: S_QUIET - suppress error messages WC_OK - write create ok
Returns
bool - true if file verified
preserve quotes
preserve quotes
Definition at line 349 of file mem.c.
{
    bool f_dir = false;
    bool f_spec = false;
    bool f_quote = true;
    char *s1;
    char *s2;
    char s1_s[MAXLEN];
    char s2_s[MAXLEN];
    char file_name[MAXLEN];
    char try_spec[MAXLEN];
    char idio_spec[MAXLEN];
    if (!org_spec[0])
        return false;
    idio_spec[0] = '\0';
    strnz__cpy(try_spec, org_spec, MAXLEN - 1);
    f_quote = stripz_quotes(try_spec);
    s1 = strtok(try_spec, " \t\n");
    strnz__cpy(s1_s, s1, MAXLEN - 1);
    s2 = strtok(nullptr, "\n");
    strnz__cpy(s2_s, s2, MAXLEN - 1);
    strnz__cpy(file_name, s1, MAXLEN - 1);
    strnz__cpy(try_spec, file_name, MAXLEN - 1);
    canonicalize_file_spec(try_spec);
    if (try_spec[0]) {
        expand_tilde(try_spec, MAXLEN - 1);
        if (try_spec[0] == '/') {
            f_spec = verify_file(try_spec, mode);
            if (f_quote)
                strnz__cpy(spec, org_spec, MAXLEN - 1);
            else
                strnz__cpy(spec, try_spec, MAXLEN - 1);
            return f_spec;
        } else {
            if (!f_dir && dir[0]) {
                if (strcmp(dir, "$PATH") == 0) {
                    strnz__cpy(try_spec, file_name, MAXLEN - 1);
                    f_spec = locate_file_in_path(try_spec, file_name);
                } else {
                    strnz__cpy(try_spec, dir, MAXLEN - 1);
                    expand_tilde(try_spec, MAXLEN - 1);
                    f_dir = verify_dir(try_spec, mode);
                    if (f_dir) {
                        strnz__cat(try_spec, "/", MAXLEN - 1);
                        strnz__cat(try_spec, file_name, MAXLEN - 1);
                        strnz__cpy(idio_spec, try_spec, MAXLEN - 1);
                        if (mode & S_WCOK)
                            f_spec = true;
                        else
                            f_spec = verify_file(idio_spec, mode | S_QUIET);
                    }
                }
            }
            if (!f_spec && alt_dir && alt_dir[0] != '\0') {
                if (strcmp(alt_dir, "$PATH") == 0) {
                    strnz__cpy(try_spec, file_name, MAXLEN - 1);
                    f_spec = locate_file_in_path(try_spec, file_name);
                } else {
                    strnz__cpy(try_spec, alt_dir, MAXLEN - 1);
                    expand_tilde(try_spec, MAXLEN - 1);
                    f_dir = verify_dir(try_spec, mode);
                    if (f_dir) {
                        strnz__cat(try_spec, "/", MAXLEN - 1);
                        strnz__cat(try_spec, file_name, MAXLEN - 1);
                        if (mode & S_WCOK)
                            f_spec = true;
                        else
                            f_spec = verify_file(try_spec, mode | S_QUIET);
                    }
                }
            }
            if (!f_spec) {
                strnz__cpy(try_spec, ".", MAXLEN - 1);
                strnz__cat(try_spec, "/", MAXLEN - 1);
                strnz__cat(try_spec, file_name, MAXLEN - 1);
                f_spec = verify_file(try_spec, mode | S_QUIET);
            }
            if (!f_spec && mode == W_OK) {
                strnz__cpy(try_spec, idio_spec, MAXLEN - 1);
                FILE *fp = fopen(try_spec, "a");
                if (fp) {
                    fclose(fp);
                    f_spec = true;
                }
            }
            if (f_quote)
                strnz__cpy(spec, org_spec, MAXLEN - 1);
            else if (f_spec)
                strnz__cpy(spec, try_spec, MAXLEN - 1);
            if (try_spec[0] == '\0' && idio_spec[0] != '\0')
                strnz__cpy(spec, idio_spec, MAXLEN - 1);
            else
                strnz__cpy(spec, try_spec, MAXLEN - 1);
            if (s2_s[0] != '\0') {
                strnz__cat(spec, " ", MAXLEN - 1);
                strnz__cat(spec, s2_s, MAXLEN - 1);
            }
            return f_spec;
        }
    }
    return false;
}
References canonicalize_file_spec(), expand_tilde(), file_name, locate_file_in_path(), MAXLEN, S_QUIET, S_WCOK, stripz_quotes(), strnz__cat(), strnz__cpy(), verify_dir(), and verify_file().
Referenced by enter_file_spec(), init_form_files(), init_menu_files(), and init_pick_files().
w_mouse_getch()
void w_mouse_getch (WINDOW * , int * , int * , int * , int *) extern
win_del()
WINDOW * win_del () extern
Delete the current window and its associated box window.
Returns
nullptr
Note
This function deletes the current window and its associated box window, if they exist. It also refreshes the remaining windows to ensure the display is updated correctly. After calling this function, the global win_ptr variable is decremented to point to the previous window in the stack.
Definition at line 764 of file dwin.c.
                  {
    int i;
    if (win_ptr > 0) {
        wclear(win_win[win_ptr]);
        touchwin(win_win[win_ptr]);
        wnoutrefresh(win_win[win_ptr]);
        delwin(win_win[win_ptr]);
        wclear(win_box[win_ptr]);
        touchwin(win_box[win_ptr]);
        wnoutrefresh(win_box[win_ptr]);
        delwin(win_box[win_ptr]);
        touchwin(stdscr);
        wnoutrefresh(stdscr);
        for (i = 0; i < win_ptr; i++) {
            touchwin(win_box[i]);
            wnoutrefresh(win_box[i]);
            touchwin(win_win[i]);
            wnoutrefresh(win_win[i]);
        }
        win_ptr--;
    }
    return (0);
}
References win_box, win_ptr, and win_win.
Referenced by display_curses_keys(), display_error(), init_form(), init_pick(), main(), menu_engine(), mview(), and Perror().
win_init_attrs()
void win_init_attrs (int fg_color, int bg_color, int bo_color) extern
Initialize window attributes.
Parameters
fg_color Foreground color index
bg_color Background color index
bo_color Box color index note This function initializes color pairs for the window note cp_norm and cp_box are global variables see get_clr_pair
Definition at line 159 of file dwin.c.
{
    init_extended_pair(cp_norm, fg_color, bg_color);
    init_extended_pair(cp_box, bo_color, bg_color);
    return;
}
References cp_box, and cp_norm.
Referenced by main().
win_new()
int win_new (int wlines, int wcols, int wbegy, int wbegx, char * wtitle, int flag) extern
Create a new window with optional box and title.
Parameters
wlines Number of lines
wcols Number of columns
wbegy Beginning Y position
wbegx Beginning X position
wtitle Window title
flag Window flags
Note
if flag set to W_BOX, Only create win_box. This is for View which uses the box window for display and doesn't need a separate win_win
Returns
0 if successful, 1 if error
Definition at line 642 of file dwin.c.
                      {
    char box_title[MAXLEN] = "Pick Selections";
    int maxx;
    if (win_ptr < MAXWIN) {
        if (win_ptr > 0)
            wrefresh(win_win[win_ptr]);
        else
            wrefresh(stdscr);
        win_ptr++;
        if (wbegy != 0 || wbegx != 0 || wlines < LINES - 2 ||
            wcols < COLS - 2) {
            win_box[win_ptr] = newwin(wlines + 2, wcols + 2, wbegy, wbegx);
            if (win_box[win_ptr] == nullptr) {
                win_ptr--;
                return (1);
            }
            wbkgrnd(win_box[win_ptr], &CCC_BOX);
            wbkgrndset(win_box[win_ptr], &CCC_BOX);
            if (wtitle != nullptr && *wtitle != '\0')
                strnz__cpy(box_title, wtitle, MAXLEN - 1);
            cbox(win_box[win_ptr]);
            mvwaddnwstr(win_box[win_ptr], 0, 1, &bw_rt, 1);
            mvwaddnwstr(win_box[win_ptr], 0, 2, &bw_sp, 1);
            mvwaddstr(win_box[win_ptr], 0, 3, box_title);
            maxx = getmaxx(win_box[win_ptr]);
            int s = strlen(box_title);
            if ((s + 3) < maxx)
                mvwaddch(win_box[win_ptr], 0, (s + 3), ' ');
            if ((s + 4) < maxx)
                mvwaddnwstr(win_box[win_ptr], 0, (s + 4), &bw_lt, 1);
            wnoutrefresh(win_box[win_ptr]);
            wbegy += 1;
            wbegx += 1;
        } else {
            win_box[win_ptr] = newwin(wlines, wcols, wbegy, wbegx);
            if (win_box[win_ptr] == nullptr) {
                win_ptr--;
                return (1);
            }
            wbkgrnd(win_box[win_ptr], &CCC_BOX);
            wbkgrndset(win_box[win_ptr], &CCC_BOX);
        }
        if (!(flag & W_BOX)) {
            win_win[win_ptr] = newwin(wlines, wcols, wbegy, wbegx);
            if (win_win[win_ptr] == nullptr) {
                delwin(win_box[win_ptr]);
                win_ptr--;
                return (1);
            }
            wbkgrnd(win_win[win_ptr], &CCC_NORM);
            wbkgrndset(win_win[win_ptr], &CCC_NORM);
            keypad(win_win[win_ptr], true);
            idlok(win_win[win_ptr], false);
            idcok(win_win[win_ptr], false);
#ifdef DEBUG
            immedok(win_win[win_ptr], true);
#endif
        }
    }
    return (0);
}
References bw_lt, bw_rt, bw_sp, cbox(), CCC_BOX, CCC_NORM, MAXLEN, MAXWIN, strnz__cpy(), W_BOX, win_box, win_ptr, and win_win.
Referenced by display_curses_keys(), display_error(), form_display_screen(), init_view_boxwin(), menu_engine(), open_pick_win(), and Perror().
win_redraw()
void win_redraw (WINDOW * win) extern
Redraw the specified window.
Parameters
win Pointer to the window to redraw
Note
This function erases the contents of the specified window and then refreshes it to update the display. Use this function when you need to clear and redraw a window, such as after resizing or when updating its contents.
Definition at line 753 of file dwin.c.
{
    werase(win);
    wnoutrefresh(win);
}
References win.
win_resize()
void win_resize (int wlines, int wcols, char * title) extern
Resize the current window and its box, and update the title.
Parameters
wlines Number of lines
wcols Number of columns
title Window title
Note
This function resizes the current window and its associated box window to the specified number of lines and columns. It also updates the title of the box window if a title is provided. After resizing, it refreshes the windows to apply the changes.
Definition at line 713 of file dwin.c.
{
    int maxx;
    wrefresh(stdscr);
    wresize(win_box[win_ptr], wlines + 2, wcols + 2);
    wbkgrnd(win_box[win_ptr], &CCC_BOX);
    wbkgrndset(win_box[win_ptr], &CCC_BOX);
    cbox(win_box[win_ptr]);
    if (title != nullptr && *title != '\0') {
        wmove(win_box[win_ptr], 0, 1);
        waddnstr(win_box[win_ptr], (const char *)&bw_rt, 1);
        wmove(win_box[win_ptr], 0, 2);
        waddnstr(win_box[win_ptr], (const char *)&bw_sp, 1);
        mvwaddnwstr(win_box[win_ptr], 0, 1, &bw_rt, 1);
        mvwaddnwstr(win_box[win_ptr], 0, 2, &bw_sp, 1);
        mvwaddstr(win_box[win_ptr], 0, 3, title);
        maxx = getmaxx(win_box[win_ptr]);
        int s = strlen(title);
        if ((s + 3) < maxx)
            mvwaddch(win_box[win_ptr], 0, (s + 3), ' ');
        if ((s + 4) < maxx)
            mvwaddnwstr(win_box[win_ptr], 0, (s + 4), &bw_lt, 1);
    }
    wnoutrefresh(win_box[win_ptr]);
    wresize(win_win[win_ptr], wlines, wcols);
    init_extended_pair(cp_norm, sio->fg_color, sio->bg_color);
    wbkgrnd(win_win[win_ptr], &CCC_NORM);
    wbkgrndset(win_win[win_ptr], &CCC_NORM);
    wsetscrreg(win_win[win_ptr], 0, wlines - 1);
    keypad(win_win[win_ptr], TRUE);
    idlok(win_win[win_ptr], false);
    idcok(win_win[win_ptr], false);
#ifdef DEBUG
    immedok(win_win[win_ptr], true);
#endif
}
References bw_lt, bw_rt, bw_sp, cbox(), CCC_BOX, CCC_NORM, cp_norm, sio, TRUE, win_box, win_ptr, and win_win.
Referenced by resize_page().
win_Toggle_Attrs()
void win_Toggle_Attrs () extern
write_log()
void write_log (char *) extern
xterm256_idx_to_rgb()
RGB xterm256_idx_to_rgb (int idx) extern
Convert XTerm 256 color index to RGB color.
Parameters
idx XTerm 256 color index
Returns
RGB color note This function converts an XTerm 256 color index to an RGB color. It first checks if the index is in the standard 16 colors, then checks if it's in the 6x6x6 color cube, and finally checks if it's in the gray ramp.
Convert XTerm 256 color index to RGB
Parameters
idx - XTerm 256 color index
Returns
RGB struct
Definition at line 474 of file dwin.c.
{
    RGB rgb;
    if (idx > 255)
        idx = 255;
    if (idx < 0)
        idx = 0;
    rgb.r = rgb.g = rgb.b = 0;
    if (idx < 16) {
        rgb.r = StdColors[idx].r;
        rgb.g = StdColors[idx].g;
        rgb.b = StdColors[idx].b;
    } else if (idx >= 16 && idx <= 231) {
        idx -= 16;
        rgb.r = (idx / 36) % 6 * 51;
        rgb.g = (idx / 6) % 6 * 51;
        rgb.b = (idx % 6) * 51;
    } else if (idx >= 232 && idx <= 255) {
        int gray = (idx - 232) * 11;
        rgb.r = rgb.g = rgb.b = gray;
    }
    return rgb;
}
References RGB::b, RGB::g, RGB::r, and StdColors.
Referenced by parse_ansi_str().
xwgetch()
int xwgetch (WINDOW * win, Chyron * chyron) extern
Wrapper for wgetch that handles signals and mouse events.
Parameters
win Pointer to window
chyron Pointer to chyron for handling chyron line clicks
Returns
Key code or ERR if interrupted by signal
Note
This, of course, will be expanded into an event loop for message queuing
Get mouse event and check if it's a left click or double click. If the click is outside the window, ignore it. If it's on the chyron line, get the corresponding key command. Otherwise, store the click coordinates as click_y and click_x for later use.
Definition at line 1075 of file dwin.c.
{
    int c;
    MEVENT event;
    event.y = event.x = -1;
    click_y = click_x = -1;
    halfdelay(1);
    do {
        c = wgetch(win);
        if (sig_received != 0) {
            if (handle_signal(sig_received))
                c = display_error(em0, em1, em2, nullptr);
            if (c == 'q' || c == KEY_F(9))
                exit(EXIT_FAILURE);
            continue;
        }
        if (c == ERR)
            continue;
        if (c == KEY_MOUSE) {
            if (getmouse(&event) != OK) {
                c = 0;
                continue;
            }
            if (event.bstate & BUTTON1_CLICKED ||
                event.bstate & BUTTON1_DOUBLE_CLICKED) {
                if (!wenclose(win, event.y, event.x)) {
                    c = 0;
                    continue;
                }
                wmouse_trafo(win, &event.y, &event.x, false);
                if (event.y < 0 || event.x < 0 || event.x >= getmaxx(win) ||
                    event.y >= getmaxy(win)) {
                    c = 0;
                    continue;
                }
                click_y = event.y;
                click_x = event.x;
                if (chyron && event.y == getmaxy(win) - 1)
                    return get_chyron_key(chyron, event.x);
                else
                    return KEY_MOUSE;
            }
        }
    } while (c == ERR);
    return c;
}
References click_x, click_y, display_error(), em0, em1, em2, get_chyron_key(), handle_signal(), sig_received, and win.
Referenced by display_curses_keys(), display_error(), form_accept_field(), form_calculate(), form_end_fields(), get_cmd_arg(), get_cmd_char(), menu_cmd_processor(), Perror(), picker(), and remove_file().
Variable Documentation
begx
int begx extern
beginning x coordinate of the terminal
Referenced by display_curses_keys(), init_form(), init_pick(), new_form(), new_menu(), and new_pick().
begy
int begy extern
beginning y coordinate of the terminal
Referenced by display_curses_keys(), init_form(), init_pick(), new_form(), new_menu(), and new_pick().
bw_bl
const wchar_t bw_bl extern
bottom left corner
Definition at line 102 of file dwin.c.
Referenced by cbox().
bw_br
const wchar_t bw_br extern
bottom right corner
Definition at line 103 of file dwin.c.
Referenced by cbox().
bw_bt
const wchar_t bw_bt extern
bottom tee
bw_cr
const wchar_t bw_cr extern
cross
bw_ho
const wchar_t bw_ho extern
The following are the actual wchar_t variables that will hold the box drawing characters. These correspond to the above Unicode code points. By defining them as wchar_t, we can use them in the ncurses library to draw boxes and lines in the terminal. The variables are named with a "bw_" prefix to indicate that they are box (wide) drawing characters, and they will be initialized with the corresponding Unicode characters defined above. horizontal line
horizontal line
Definition at line 98 of file dwin.c.
Referenced by cbox().
bw_lt
const wchar_t bw_lt extern
left tee
Definition at line 104 of file dwin.c.
Referenced by win_new(), and win_resize().
bw_rt
const wchar_t bw_rt extern
right tee
Definition at line 105 of file dwin.c.
Referenced by win_new(), and win_resize().
bw_tl
const wchar_t bw_tl extern
top left corner
Definition at line 100 of file dwin.c.
Referenced by cbox().
bw_tr
const wchar_t bw_tr extern
top right corner
Definition at line 101 of file dwin.c.
Referenced by cbox().
bw_tt
const wchar_t bw_tt extern
top tee
bw_ve
const wchar_t bw_ve extern
vertical line
Definition at line 99 of file dwin.c.
Referenced by cbox().
CCC_BOX
cchar_t CCC_BOX extern
box color pair complex character
Definition at line 147 of file dwin.c.
Referenced by handle_signal(), init_view_full_screen(), open_curses(), win_new(), and win_resize().
CCC_NORM
cchar_t CCC_NORM extern
normal color pair complex character
Definition at line 146 of file dwin.c.
Referenced by handle_signal(), init_view_boxwin(), open_curses(), win_new(), and win_resize().
CCC_REVERSE
cchar_t CCC_REVERSE extern
reverse color pair complex character
Definition at line 148 of file dwin.c.
Referenced by handle_signal(), and open_curses().
click_x
int click_x extern
the x coordinate of a mouse click, for handling mouse
Definition at line 43 of file dwin.c.
Referenced by form_accept_field(), form_calculate(), form_end_fields(), menu_cmd_processor(), picker(), and xwgetch().
click_y
int click_y extern
the y coordinate of a mouse click, for handling mouse events
Definition at line 42 of file dwin.c.
Referenced by form_accept_field(), form_calculate(), form_end_fields(), menu_cmd_processor(), picker(), and xwgetch().
clr_cnt
int clr_cnt extern
number of colors used
Definition at line 142 of file dwin.c.
Referenced by init_clr_palette(), and rgb_to_curses_clr().
clr_idx
int clr_idx extern
current color index
Definition at line 143 of file dwin.c.
clr_pair_cnt
int clr_pair_cnt extern
number of color pairs supported by the terminal
Definition at line 145 of file dwin.c.
Referenced by get_clr_pair().
clr_pair_idx
int clr_pair_idx extern
current color pair index
Definition at line 144 of file dwin.c.
Referenced by parse_ansi_str().
cmd_key
unsigned int cmd_key extern
the command key for the current command, for error messages and other output
Definition at line 433 of file cm.h.
Referenced by display_error(), form_desc_error(), form_enter_fields(), form_read_data(), Perror(), and picker().
colors_text
char const colors_text[][10] extern
color codes for the 16 basic colors
colors_text
Note
Color names for .minitrc overrides
These names are used in .minitrc to specify color overrides
The order of these names corresponds to the colors_enum values
Definition at line 94 of file dwin.c.
{
    "black",   "red",    "green", "yellow",   "blue",   "magenta", "cyan",
    "white",   "orange", "bg",    "abg",      "bblack", "bred",    "bgreen",
    "byellow", "bblue",  "bcyan", "bmagenta", "bwhite", "borange", ""};
Referenced by clr_name_to_idx(), list_colors(), and write_config().
cols
int cols extern
current number of columns (may be less than n_cols if the terminal is resized)
Referenced by display_curses_keys(), and form_parse_desc().
cp_bold
int cp_bold extern
bold color pair index
cp_box
int cp_box extern
box color pair index
Definition at line 140 of file dwin.c.
Referenced by open_curses(), and win_init_attrs().
cp_default
int cp_default extern
default color pair index
cp_highlight
int cp_highlight extern
highlight color pair index
cp_norm
int cp_norm extern
normal color pair index
Definition at line 139 of file dwin.c.
Referenced by fmt_line(), init_view_boxwin(), init_view_full_screen(), open_curses(), search(), win_init_attrs(), and win_resize().
cp_reverse
int cp_reverse extern
reverse color pair index
Definition at line 141 of file dwin.c.
Referenced by open_curses().
cp_title
int cp_title extern
title color pair index
curses_err_tioctl
struct termios shell_err_tioctl curses_err_tioctl extern
Definition at line 35 of file scriou.c.
curses_in_tioctl
struct termios shell_in_tioctl curses_in_tioctl extern
Definition at line 33 of file scriou.c.
curses_out_tioctl
struct termios shell_out_tioctl curses_out_tioctl extern
Definition at line 34 of file scriou.c.
curses_tioctl
struct termios shell_tioctl curses_tioctl extern
Definition at line 32 of file scriou.c.
Referenced by capture_curses_tioctl(), and restore_curses_tioctl().
dbgfd
int dbgfd extern
the file descriptor for debug output, for debugging purposes
earg_str
char earg_str[256] extern
earg - general use argument string general use argument string, for external commands or error messages
Definition at line 23 of file exec.c.
Referenced by enter_file_spec(), form_calculate(), form_exec_cmd(), and menu_cmd_processor().
eargc
int eargc extern
general use argument count, for external commands or error messages
Definition at line 21 of file exec.c.
Referenced by display_pick_help(), enter_file_spec(), form_engine(), menu_cmd_processor(), and view_display_help().
eargv
char* eargv[64] extern
eargv - argument vector for external commands, or error messages
Definition at line 22 of file exec.c.
Referenced by display_pick_help(), enter_file_spec(), form_calculate(), form_engine(), menu_cmd_processor(), and view_display_help().
em0
char em0[256] extern
error message string for error messages
Definition at line 135 of file dwin.c.
Referenced by display_error(), enter_file_spec(), form_calculate(), form_desc_error(), form_parse_desc(), form_read_data(), form_write(), get_clr_pair(), handle_signal(), init_view_boxwin(), init_view_full_screen(), lf_find(), mk_dir(), new_init(), new_pick(), new_view(), parse_menu_description(), verify_dir(), verify_file(), view_cmd_processor(), view_init_input(), write_view_buffer(), and xwgetch().
em1
char em1[256] extern
error message string for error messages
Definition at line 136 of file dwin.c.
Referenced by display_error(), enter_file_spec(), form_calculate(), form_desc_error(), form_parse_desc(), form_read_data(), form_write(), get_clr_pair(), handle_signal(), init_view_boxwin(), init_view_full_screen(), lf_find(), mk_dir(), new_init(), new_pick(), new_view(), parse_menu_description(), verify_dir(), verify_file(), view_cmd_processor(), view_init_input(), write_view_buffer(), and xwgetch().
em2
char em2[256] extern
error message string for error messages
Definition at line 137 of file dwin.c.
Referenced by display_error(), enter_file_spec(), form_calculate(), form_desc_error(), form_parse_desc(), form_read_data(), form_write(), get_clr_pair(), handle_signal(), init_view_boxwin(), init_view_full_screen(), lf_find(), mk_dir(), new_init(), new_view(), parse_menu_description(), verify_dir(), verify_file(), view_cmd_processor(), view_init_input(), write_view_buffer(), and xwgetch().
em3
char em3[256] extern
error message string for error messages
Definition at line 138 of file dwin.c.
Referenced by display_error(), verify_dir(), and verify_file().
errmsg
char errmsg[] extern
Definition at line 63 of file futil.c.
Referenced by main(), and rgb_clr_to_cube().
exit_code
int exit_code extern
the exit code for the program, for error messages and other output
Definition at line 119 of file dwin.c.
f_curses_open
bool f_curses_open extern
curses mode is active
Definition at line 20 of file sig.c.
Referenced by destroy_curses(), display_error(), handle_signal(), open_curses(), and Perror().
f_debug
bool f_debug extern
a flag to indicate whether debug output should be printed, for debugging purposes
Definition at line 431 of file cm.h.
Referenced by mapp_initialization().
f_have_curses_tioctl
bool f_have_curses_tioctl extern
curses tioctl captured
Definition at line 23 of file scriou.c.
Referenced by capture_curses_tioctl(), and restore_curses_tioctl().
f_have_shell_tioctl
bool f_have_shell_tioctl extern
shell tioctl captured
Definition at line 22 of file scriou.c.
Referenced by capture_shell_tioctl(), and restore_shell_tioctl().
f_restore_screen
bool f_restore_screen extern
whether to restore the screen
fn
char fn[256] extern
function name for error messages
Definition at line 134 of file dwin.c.
Referenced by file_spec_name(), locate_file_in_path(), verify_dir(), and verify_file().
lines
int lines extern
current number of lines (may be less than n_lines if the terminal is resized)
Referenced by display_curses_keys().
mbegx
int mbegx extern
beginning x coordinate of the current window, which can be used to determine the position of the window on the terminal screen.
Referenced by enter_option().
mbegy
int mbegy extern
beginning y coordinate of the current window, which can be used to determine the position of the window on the terminal screen.
Referenced by enter_option().
mcols
int mcols extern
number of columns in the current window, which may be less than the total number of columns in the terminal if the window is resized or if multiple windows are being used.
Referenced by enter_option().
mg_action
int mg_action extern
action in progress, which can be used to keep track of the current state of the program and determine how to respond to user input or other events.
Referenced by enter_option().
mg_col
int mg_col extern
window column, which can be used to determine the current column position in the window for displaying text or other content.
Referenced by enter_option().
mg_line
int mg_line extern
window line, which can be used to determine the current line position in the window for displaying text or other content.
Referenced by enter_option().
mlines
int mlines extern
number of lines in the current window, which may be less than the total number of lines in the terminal if the window is resized or if multiple windows are being used.
Referenced by enter_option().
n_cols
int n_cols extern
number of columns in the terminal
n_lines
int n_lines extern
number of lines in the terminal
sig_received
volatile sig_atomic_t sig_received extern
Definition at line 18 of file sig.c.
Referenced by handle_signal(), handle_signal(), signal_handler(), and xwgetch().
src_line
int src_line extern
the line number of the source file being processed, for error messages
Definition at line 132 of file dwin.c.
Referenced by verify_dir(), and verify_file().
src_name
char* src_name extern
the name of the source file being processed, for error messages
Definition at line 133 of file dwin.c.
Referenced by verify_dir(), and verify_file().
tty_fd
int tty_fd extern
tty_fd - the file descriptor for the terminal, for error messages and other the file descriptor for the terminal, for error messages and other output
Global file/pipe numbers
Definition at line 150 of file dwin.c.
Referenced by picker().
win
WINDOW* win extern
generic window pointer, used for various purposes
Definition at line 116 of file dwin.c.
Referenced by display_curses_keys(), enter_option(), form_accept_field(), form_display_field(), win_redraw(), and xwgetch().
win_attr
int win_attr extern
Ncurses attributes for the current window, such as color pair, bold, etc.
Definition at line 122 of file dwin.c.
Referenced by enter_option().
win_attr_even
int win_attr_even extern
Ncurses attributes for the current window even lines, which may be different from the attributes for odd lines to create a striped effect in the window.
Referenced by enter_option().
win_attr_odd
int win_attr_odd extern
Ncurses attributes for the current window odd lines, which may be different from the attributes for even lines to create a striped effect in the window.
Referenced by enter_option().
win_box
WINDOW* win_box[30] extern
array of pointers to box windows, indexed by window ID
Definition at line 118 of file dwin.c.
Referenced by display_curses_keys(), enter_option(), form_display_screen(), menu_engine(), open_pick_win(), restore_wins(), win_del(), win_new(), and win_resize().
win_ptr
int win_ptr extern
Pointer to the current window pair, box and window, which can be used to keep track of the currently active window and its associated box.
Definition at line 124 of file dwin.c.
Referenced by display_curses_keys(), display_error(), enter_option(), form_display_screen(), init_view_boxwin(), menu_engine(), open_pick_win(), Perror(), restore_wins(), win_del(), win_new(), and win_resize().
win_win
WINDOW* win_win[30] extern
array of pointers to windows, indexed by window ID
Definition at line 117 of file dwin.c.
Referenced by display_curses_keys(), display_error(), enter_option(), form_display_screen(), init_view_boxwin(), menu_engine(), open_pick_win(), Perror(), restore_wins(), win_del(), win_new(), and win_resize().