C-Menu: src/form.c File Reference
form.c File Reference
Command Line Start-up for C-Menu Form.
#include <common.h>
Functions
int main (int argc, char **argv)
Variables
__end_pgm
Detailed Description
Command Line Start-up for C-Menu Form.
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file form.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 13 of file form.c.
{
    __atexit;
    capture_shell_tioctl();
    Init *init = new_init(argc, argv);
    SIO *sio = init->sio;
    mapp_initialization(init, argc, argv);
    open_curses(sio);
    sig_prog_mode();
    capture_curses_tioctl();
    win_init_attrs(sio->fg_color, sio->bg_color, sio->bo_color);
    init_form(init, argc, argv, LINES / 14, COLS / 14);
    destroy_init(init);
    win_del();
    destroy_curses();
    return 0;
}
References capture_curses_tioctl(), capture_shell_tioctl(), destroy_curses(), destroy_init(), init, init_form(), mapp_initialization(), new_init(), open_curses(), sig_prog_mode(), sio, win_del(), and win_init_attrs().
Variable Documentation
__end_pgm
__end_pgm
Definition at line 12 of file form.c.