C-Menu: futil.c File Reference
futil.c File Reference
General utility functions.
#include <cm.h>
#include <ctype.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <grp.h>
#include <pwd.h>
#include <regex.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <termios.h>
#include <unistd.h>
#include <wait.h>
Functions
bool lf_find (const char *base_path, const char *re, const char *ere, int max_depth, int flags)
Find files in a directory matching a regular expression.
bool lf_process (const char *base_path, regex_t *compiled_re, regex_t *compiled_ere, int depth, int max_depth, int flags)
logic for lf_find()
size_t strip_ansi (char *d, char *s)
Strips ANSI SGR escape sequences (ending in 'm') from string s to d.
int a_toi (char *s, bool *a_toi_error)
a safer alternative to atoi() for converting ASCII strings to integers.
bool chrep (char *s, char old_chr, char new_chr)
Replaces all occurrences of old_chr in s with new_chr in place.
size_t trim (char *s)
Trims leading and trailing spaces from string s in place.
size_t rtrim (char *s)
Trims trailing spaces from string s in place.
bool stripz_quotes (char *s)
removes leading and trailing double quotes if present
bool strip_quotes (char *s)
removes leading and trailing double quotes if present
bool str_to_bool (const char *s)
Converts String to boolean true or false.
int str_to_args (char **argv, char *arg_str, int max_args)
Converts a string into an array of argument strings.
double str_to_double (char *s)
converts string to double
bool str_to_lower (char *s)
Converts a string to lowercase.
bool str_to_upper (char *s)
Converts a string to uppercase.
size_t strz (char *s)
Terminates string at new line or carriage return.
size_t strnz (char *s, size_t max_len)
terminates string at New Line, Carriage Return, or max_len
size_t strnlf (char *s, size_t max_len)
terminates string with line feed
bool str_subc (char *d, char *s, char ReplaceChr, char *Withstr, int l)
Replaces "ReplaceChr" in "s" with "Withstr" in "d" won't copy more than "l" bytes to "d" Replaces all occurrences of a character in a string with another string, copying the result to a destination buffer. It ensures that the total length of the resulting string does not exceed the specified limit, and that the result is null-terminated. This function is useful for simple string substitutions where you want to replace a single character with a longer string, such as replacing spaces with underscores or tabs with spaces.
char * rep_substring (const char *org_s, const char *tgt_s, const char *rep_s)
Replace all occurrences of "tgt_s" in "org_s" with "rep_s".
bool normalize_file_spec (char *fs)
replace backslashes with forward lashes
bool file_spec_path (char *fp, char *fs)
extracts the path component of a file specification
bool file_spec_name (char *fn, char *fs)
extracts the file name component of a file specification
bool verify_file (char *in_spec, int imode)
Verifies that the file specified by "in_spec" exists and is accessible with the permissions specified by "imode".
bool verify_dir (char *spec, int imode)
Verifies that the directory specified by "spec" exists and is accessible with the permissions specified by "imode".
bool locate_file_in_path (char *file_spec, char *file_name)
Locates a file in the system PATH.
size_t canonicalize_file_spec (char *spec)
Removes quotes and trims at first space.
size_t ssnprintf (char *buf, size_t buf_size, const char *format,...)
ssnprintf was designed to be a safer alternative to snprintf.
size_t strnz__cpy (char *d, const char *s, size_t max_len)
safer alternative to strncpy
size_t strnz__cat (char *d, const char *s, size_t max_len)
safer alternative to strncat
size_t string_cpy (String *dest, const String *src)
Copy src String to dest String, allocating additional memory for dest String if necessary.
size_t string_cat (String *dest, const String *src)
Concatenates src String to dest String, allocating additional memory for dest String if necessary.
size_t string_ncat (String *dest, const String *src, size_t n)
Concatenates up to n characters from src String to dest String, allocating additional memory for dest String if necessary.
size_t string_ncpy (String *dest, const String *src, size_t n)
copies up to n characters from src String to dest String, allocating additional memory for dest String if necessary
String to_string (const char *s)
String functions provide a simple string library to facilitate string manipulation in C, allowing developers to easily create, copy, concatenate, and free strings without having to manage memory manually.
String mk_string (size_t l)
Create a String struct with a dynamically allocated string.
String free_string (String string)
Free the dynamically allocated String.
char * strnz_dup (char *s, size_t l)
Allocates memory for and duplicates string s up to length l or until line feed or carriage return.
bool strnfill (char *s, char c, int n)
Fills string s with character c n.
bool expand_tilde (char *path, int path_maxlen)
Replace Leading Tilde With Home Directory.
bool trim_path (char *dir)
Trims trailing spaces and slashes from directory path in place.
bool trim_ext (char *buf, char *filename)
trims the file extension from "filename" and copies the result to "buf"
bool base_name (char *buf, char *path)
Returns the base name of a file specification.
bool dir_name (char *buf, char *path)
Returns the directory name of a file specification.
bool mk_dir (char *dir)
If directory doesn't exist, make it.
int segmentation_fault ()
Function to intentionally cause a segmentation fault for testing purposes.
Variables
char errmsg [MAXLEN]
Detailed Description
General utility functions.
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file futil.c.
Function Documentation
a_toi()
int a_toi (char * s, bool * a_toi_error)
a safer alternative to atoi() for converting ASCII strings to integers.
Parameters
s is the input string
a_toi_error is a pointer to a boolean that will be set to true if an error occurs during conversion, or false if the conversion is successful.
Note
accepts positive integers only.
sets a_toi_error to (-1) on error
Returns
converted integer value, or -1 if an error occurs
Definition at line 438 of file futil.c.
Referenced by parse_ansi_str().
base_name()
bool base_name (char * buf, char * path)
Returns the base name of a file specification.
Parameters
buf - buffer to receive result
path - file specification
Returns
true if successful
Note
The caller is responsible for ensuring that "buf" has enough space to receive the result.
Definition at line 699 of file futil.c.
Referenced by build_prompt(), exec_objects(), form_calculate(), init_form_files(), init_pick_files(), parse_opt_args(), and view_init_input().
canonicalize_file_spec()
size_t canonicalize_file_spec (char * spec)
Removes quotes and trims at first space.
Parameters
spec - file specification to canonicalize
Returns
length of resulting string
Definition at line 1083 of file futil.c.
References MAXLEN, and strnz__cpy().
Referenced by locate_file_in_path(), verify_file(), and verify_spec_arg().
chrep()
bool chrep (char * s, char old_chr, char new_chr)
Replaces all occurrences of old_chr in s with new_chr in place.
Parameters
s - string to modify
old_chr - character to replace
new_chr - character to insert
Returns
true if successful or false if string s is null
Definition at line 420 of file futil.c.
Referenced by parse_menu_description().
dir_name()
bool dir_name (char * buf, char * path)
Returns the directory name of a file specification.
Parameters
buf - buffer to receive result
path - file specification
Returns
true if successful
Note
The caller is responsible for ensuring that "buf" has enough space to receive the result.
Definition at line 724 of file futil.c.
References MAXLEN, strnz__cpy(), and tmp_str.
expand_tilde()
bool expand_tilde (char * path, int path_maxlen)
Replace Leading Tilde With Home Directory.
Parameters
path - path to expand
path_maxlen - maximum length of path
Note
The caller is responsible for ensuring that "path" has enough space to receive the result, and that "path_maxlen" is sufficient to hold the result. This function does not perform any bounds checking on "path", so it is the caller's responsibility to ensure that it is valid and that "path_maxlen" is appropriate for the operation.
Returns
true if successful
Definition at line 611 of file futil.c.
References MAXLEN, strnz__cat(), and strnz__cpy().
Referenced by enter_file_spec(), form_engine(), mapp_initialization(), menu_cmd_processor(), mk_dir(), parse_config(), verify_dir(), verify_file(), verify_spec_arg(), view_display_help(), and view_init_input().
file_spec_name()
bool file_spec_name (char * fn, char * fs)
extracts the file name component of a file specification
Parameters
fn - name component to return
fs - full file specification
Note
The caller is responsible for ensuring that "fn" has enough space to receive the result.
Definition at line 534 of file futil.c.
References fn.
file_spec_path()
bool file_spec_path (char * fp, char * fs)
extracts the path component of a file specification
Parameters
fp - path component to return
fs - full file specification
Returns
true if successful
Note
The caller is responsible for ensuring that "fp" has enough space to receive the result.
Definition at line 508 of file futil.c.
free_string()
String free_string (String string)
Free the dynamically allocated String.
Parameters
string to free
Returns
string with nullptr pointer and length 0
Note
Frees the dynamically allocated string and sets length to 0.
Definition at line 1254 of file futil.c.
lf_find()
bool lf_find (const char * base_path, const char * re, const char * ere, int max_depth, int flags)
Find files in a directory matching a regular expression.
Parameters
base_path directory to search
ere regular expression match to exclude
re regular expression match to include
max_depth depth of directories to scan
flags search flags
               flags = LF_ALL | LF_ICASE | LF_FILES
               flags = LF_ALL | LF_ICASE | LF_DIRS
LF_ALL      =  1,  List all files including hidden files
LF_ICASE    =  2,  Ignore case in search
LF_FILES    =  4,  list files (exclude directories)
LF_DIRS     =  8,  list directories (exclude files)
LF_EXCLUDE  =  16, exclude files matching "ere" pattern
LF_REGEX    =  32, re is a regular expression pattern to match
return true if successful, false otherwise
Definition at line 905 of file futil.c.
References display_error(), em0, em1, em2, LF_EXCLUDE, LF_ICASE, lf_process(), LF_REGEX, MAXLEN, and ssnprintf().
Referenced by main().
lf_process()
bool lf_process (const char * base_path, regex_t * compiled_re, regex_t * compiled_ere, int depth, int max_depth, int flags)
logic for lf_find()
Parameters
base_path directory to search
compiled_ere compiled regular expression to exclude
compiled_re compiled regular expression to include
depth recursion counter
max_depth how deep to descend into the directory structure
flags
               flags = LF_ALL | LF_ICASE | LF_FILES
               flags = LF_ALL | LF_ICASE | LF_DIRS
LF_ALL      =  1,  List hidden files
LF_ICASE    =  2,  Ignore case in search
LF_FILES    =  4,  list files (exclude directories)
LF_DIRS     =  8,  list directories (exclude files)
LF_EXCLUDE  =  16, exclude files matching "ere" pattern
LF_REGEX    =  32, re is a regular expression pattern to match
return true if successful, false otherwise
Definition at line 966 of file futil.c.
References LF_ALL, LF_DIRS, LF_EXCLUDE, LF_FILES, lf_process(), MAXLEN, Perror(), ssnprintf(), strnz__cat(), strnz__cpy(), and tmp_str.
Referenced by lf_find(), and lf_process().
locate_file_in_path()
bool locate_file_in_path (char * file_spec, char * file_name)
Locates a file in the system PATH.
Parameters
file_spec - buffer to receive located file specification
file_name - name of file to locate
Returns
true if file is located
Note
file_spec must be large enough to receive the result
Definition at line 859 of file futil.c.
References canonicalize_file_spec(), file_name, fn, MAXLEN, strnz__cat(), and strnz__cpy().
Referenced by init_form_files(), init_pick_files(), and verify_spec_arg().
mk_dir()
bool mk_dir (char * dir)
If directory doesn't exist, make it.
Parameters
dir directory name
Returns
true if directory now exists or false otherwise
Directory does not exist and unable to create
Definition at line 1063 of file futil.c.
References display_error(), em0, em1, em2, expand_tilde(), MAXLEN, S_QUIET, S_WCOK, ssnprintf(), strnz__cat(), strnz__cpy(), and verify_dir().
Referenced by enter_file_spec().
mk_string()
String mk_string (size_t l)
Create a String struct with a dynamically allocated string.
Parameters
l length of string to create including null terminator
Returns
String struct
Note
The returned String struct contains a dynamically allocated string of he specified length
See also
free_string
Note
the caller is responsible for calling free_string to free the allocated memory.
Definition at line 1236 of file futil.c.
References String::l, and String::s.
normalize_file_spec()
bool normalize_file_spec (char * fs)
replace backslashes with forward lashes
Parameters
fs - file specification to normalize
Returns
true if successful, false if fs is nullptr or empty
Definition at line 492 of file futil.c.
rep_substring()
char * rep_substring (const char * org_s, const char * tgt_s, const char * rep_s)
Replace all occurrences of "tgt_s" in "org_s" with "rep_s".
Parameters
org_s - original string
tgt_s - target substring to replace
rep_s - replacement substring
Returns
A pointer to the newly allocated string with replacements or a copy of the replacement string if original string is the same as target string This is a special case that allows for replacing the entire original string. If any parameter is nullptr, the function returns nullptr. If "tgt_s" is not found in "org_s", the function returns a copy of "org_s". If target substring is not found the function returns a copy of the original string.
Note
allocates memory for the return value, so the caller is responsible for freeing this memory when it is no longer needed to avoid memory leaks.
Does not modify the original string "org_s".
Assumes that "tgt_s" and "rep_s" are null-terminated strings. If they are not, the behavior is undefined.
Does not perform any bounds checking on the input strings, so it is the caller's responsibility to ensure that they are valid and that the resulting string does not exceed available memory.
Uses the standard library functions strlen, strstr, malloc, and strcpy, which may have their own limitations and behaviors that the caller should be aware of.
Does not handle overlapping occurrences of "tgt_s" in "org_s". If "tgt_s" can overlap with itself in "org_s", the behavior may be unexpected. The caller should ensure that "tgt_s" does not contain overlapping patterns to avoid this issue.
Does not handle cases where "tgt_s" is a substring of "rep_s", which could lead to unintended consequences if "tgt_s" appears in "rep_s". The caller should ensure that "tgt_s" and "rep_s" are distinct to avoid this issue.
Definition at line 1137 of file futil.c.
References MAXLEN, and strnz__cpy().
Referenced by exec_objects().
rtrim()
size_t rtrim (char * s)
Trims trailing spaces from string s in place.
Parameters
s - string to trim
Returns
length of trimmed string
Definition at line 68 of file futil.c.
Referenced by fmt_line().
segmentation_fault()
int segmentation_fault ()
Function to intentionally cause a segmentation fault for testing purposes.
Note
This function is designed to intentionally cause a segmentation fault by dereferencing a null pointer. It is intended for testing purposes only and should not be used in production code. The caller should be aware that executing this function will crash the program.
Definition at line 1342 of file futil.c.
ssnprintf()
size_t ssnprintf (char * buf, size_t buf_size, const char * format, ...)
ssnprintf was designed to be a safer alternative to snprintf.
It ensures that the buffer is not overflowed by taking the buffer size as a parameter and using vsnprintf internally. It also returns the number of characters that would have been written if enough space had been available, allowing the caller to detect truncation. This function is particularly useful in situations where the formatted string may exceed the buffer size, as it prevents buffer overflows and provides a way to handle such cases gracefully.
Parameters
buf - buffer to receive formatted string
buf_size - size of buffer
format - printf-style format string
... - arguments
Returns
number of characters that would have been written if enough space had been available
Definition at line 111 of file futil.c.
Referenced by display_error(), enter_file_spec(), fork_exec(), form_calculate(), form_desc_error(), form_parse_desc(), form_write(), get_clr_pair(), handle_signal(), init_view_boxwin(), init_view_full_screen(), lf_find(), lf_process(), mapp_initialization(), menu_engine(), mk_dir(), new_init(), new_pick(), new_view(), open_pick_win(), parse_menu_description(), Perror(), pick_display_chyron(), search(), set_chyron_key(), verify_dir(), verify_file(), view_cmd_processor(), view_init_input(), and write_view_buffer().
str_subc()
bool str_subc (char * d, char * s, char ReplaceChr, char * Withstr, int l)
Replaces "ReplaceChr" in "s" with "Withstr" in "d" won't copy more than "l" bytes to "d" Replaces all occurrences of a character in a string with another string, copying the result to a destination buffer. It ensures that the total length of the resulting string does not exceed the specified limit, and that the result is null-terminated. This function is useful for simple string substitutions where you want to replace a single character with a longer string, such as replacing spaces with underscores or tabs with spaces.
Parameters
d - destination string
s - source string
ReplaceChr - character to replace
Withstr - string to insert
l - maximum length to copy
Returns
true if successful, false if any parameter is invalid
Note
The caller must ensure that "d" has enough space to receive the result, and that "l" is sufficient to hold the result. This function does not perform any bounds checking on "d" or "Withstr", so it is the caller's responsibility to ensure that they are valid and that "l" is appropriate for the operation.
Definition at line 353 of file futil.c.
Referenced by view_cmd_processor().
str_to_args()
int str_to_args (char ** argv, char * arg_str, int max_args)
Converts a string into an array of argument strings.
Note
Handles quoted strings and escaped quotes, preserving text inside quotes as individual arguments. It has been in service for many years without problems.
Parameters
argv - array of pointers to arguments
arg_str - string containing arguments
max_args - maximum number of arguments to parse
Returns
argc, a count of allocated vectors in argv
Note
the caller is responsible for deallocating the strings in argv
Definition at line 130 of file futil.c.
References MAXLEN, and tmp_str.
Referenced by enter_file_spec(), exec_objects(), form_calculate(), init_pick(), menu_cmd_processor(), and view_init_input().
str_to_bool()
bool str_to_bool (const char * s)
Converts String to boolean true or false.
Parameters
s - string to convert
Returns
boolean true or false
Definition at line 577 of file futil.c.
Referenced by parse_config().
str_to_double()
double str_to_double (char * s)
converts string to double
Parameters
s - string to convert
Returns
converted double value, or 0.0 if s is nullptr, empty, or invalid
Note
The caller must ensure that the string is a valid representation of a double before calling this function.
Definition at line 565 of file futil.c.
Referenced by parse_config(), and parse_opt_args().
str_to_lower()
bool str_to_lower (char * s)
Converts a string to lowercase.
Parameters
s - string to convert
Returns
true if successful, false if s is nullptr or empty
Definition at line 179 of file futil.c.
Referenced by clr_name_to_idx(), form_parse_desc(), and prompt_str_to_int().
str_to_upper()
bool str_to_upper (char * s)
Converts a string to uppercase.
Parameters
s - string to convert
Returns
true if successful, false if s is nullptr or empty
Definition at line 192 of file futil.c.
string_cat()
size_t string_cat (String * dest, const String * src)
Concatenates src String to dest String, allocating additional memory for dest String if necessary.
Parameters
dest - destination String struct
src - source String struct
Returns
new length of dest String after concatenation
Note
the caller is responsible for freeing the allocated memory.
Definition at line 1284 of file futil.c.
References String::l, and String::s.
string_cpy()
size_t string_cpy (String * dest, const String * src)
Copy src String to dest String, allocating additional memory for dest String if necessary.
Parameters
dest - destination String struct
src - source String struct
Returns
length of dest String
Note
the caller is responsible for freeing the allocated memory.
Definition at line 1268 of file futil.c.
References String::l, and String::s.
string_ncat()
size_t string_ncat (String * dest, const String * src, size_t n)
Concatenates up to n characters from src String to dest String, allocating additional memory for dest String if necessary.
Parameters
dest - destination String struct
src - source String struct
n - maximum number of characters to concatenate
Returns
new length of dest String after concatenation
Note
the caller is responsible for freeing the allocated memory.
Definition at line 1302 of file futil.c.
References String::l, and String::s.
string_ncpy()
size_t string_ncpy (String * dest, const String * src, size_t n)
copies up to n characters from src String to dest String, allocating additional memory for dest String if necessary
Parameters
dest - destination String struct
src - source String struct
n - maximum number of characters to copy
Note
the caller is responsible for freeing the allocated memory.
Definition at line 1322 of file futil.c.
References String::l, and String::s.
strip_ansi()
size_t strip_ansi (char * d, char * s)
Strips ANSI SGR escape sequences (ending in 'm') from string s to d.
Parameters
d Destination string
s Source string
Returns
Length of stripped string
    char dest[1024];
    char src[] = "\033[31mThis is red text\033[0m
    size_t len = strip_ansi(dest, src);
    Result: dest = "This is red text", len = 17
@example stripansi.c
Note
Only handles SGR sequences ending in 'm' or 'K'
Skips non-ASCII characters
The caller must ensure that d has enough space to hold the stripped string
This function does not allocate memory; it assumes d is pre-allocated
This function processes the entire string until the null terminator
This function does not modify the source string s
Definition at line 469 of file futil.c.
Referenced by main(), and write_view_buffer().
strip_quotes()
bool strip_quotes (char * s)
removes leading and trailing double quotes if present
Parameters
s - string to strip quotes from
Returns
true if successful, false if s is nullptr or empty
Definition at line 390 of file futil.c.
Referenced by init_form_files(), and init_view_files().
stripz_quotes()
bool stripz_quotes (char * s)
removes leading and trailing double quotes if present
Parameters
s - string to strip quotes from
Returns
true if quotes were removed
Note
Same as STRIP_QUOTES but returns true if quotes were removed
Definition at line 404 of file futil.c.
Referenced by verify_spec_arg().
strnfill()
bool strnfill (char * s, char c, int n)
Fills string s with character c n.
Parameters
s - string to fill
c - character to fill with
n - number of characters to fill
Returns
true if successful, false if s is nullptr or n is non-positive
Definition at line 377 of file futil.c.
Referenced by form_display_fields().
strnlf()
size_t strnlf (char * s, size_t max_len)
terminates string with line feed
Parameters
s string to terminate
max_len maximum length to scan
Returns
length of resulting string
Definition at line 298 of file futil.c.
Referenced by write_view_buffer().
strnz()
size_t strnz (char * s, size_t max_len)
terminates string at New Line, Carriage Return, or max_len
Note
The use case is to ensure that strings read from files or user input do not contain embedded newlines or carriage returns.
Parameters
s string to terminate
max_len - maximum length to scan
Returns
length of resulting string
Definition at line 281 of file futil.c.
Referenced by display_error(), enter_file_spec(), form_display_fields(), form_display_screen(), form_fmt_field(), and pick_engine().
strnz__cat()
size_t strnz__cat (char * d, const char * s, size_t max_len)
safer alternative to strncat
Note
It appends string s to d, ensuring that the total length of d does not exceed max_len, and that the resulting string is null-terminated. It also treats newline and carriage return characters as string terminators, preventing them from being included in the result. This is particularly useful when concatenating user input or file data, where embedded newlines could cause issues.
Parameters
d - destination string
s - source string
max_len - maximum length to copy
Returns
length of resulting string
Definition at line 241 of file futil.c.
Referenced by build_prompt(), compile_chyron(), derive_file_spec(), display_curses_keys(), enter_file_spec(), exec_objects(), expand_tilde(), file_spec_parts(), form_calculate(), form_display_screen(), form_exec_cmd(), form_parse_desc(), form_read_data(), form_write(), init_form(), init_menu_files(), init_pick(), lf_process(), locate_file_in_path(), menu_cmd_processor(), mk_dir(), open_curses(), output_objects(), parse_menu_description(), search(), verify_spec_arg(), view_cmd_processor(), view_init_input(), whence(), write_config(), and write_view_buffer().
strnz__cpy()
size_t strnz__cpy (char * d, const char * s, size_t max_len)
safer alternative to strncpy
Note
It copies string s to d, ensuring that the total length of d does not exceed max_len, and that the resulting string is null-terminated. It also treats newline and carriage return characters as string terminators, preventing them from being included in the result. This is particularly useful when copying user input or file data, where embedded newlines could cause issues.
Parameters
d - destination string
s - source string
max_len - maximum length to copy
Returns
length of resulting string
Definition at line 213 of file futil.c.
Referenced by build_prompt(), canonicalize_file_spec(), cmd_line_prompt(), derive_file_spec(), dir_name(), display_curses_keys(), display_error(), display_pick_help(), enter_file_spec(), exec_objects(), expand_tilde(), file_spec_parts(), form_calculate(), form_desc_error(), form_display_screen(), form_engine(), form_exec_cmd(), form_fmt_field(), form_parse_desc(), form_read_data(), form_write(), get_cmd_arg(), handle_signal(), init_form(), init_form_files(), init_menu_files(), init_pick(), init_pick_files(), init_view_boxwin(), init_view_files(), lf_process(), locate_file_in_path(), main(), mapp_initialization(), menu_cmd_processor(), mk_dir(), new_form(), open_curses(), output_objects(), parse_config(), parse_menu_description(), parse_opt_args(), Perror(), prompt_int_to_str(), rep_substring(), save_object(), search(), verify_dir(), verify_file(), verify_spec_arg(), view_cmd_processor(), view_display_help(), view_init_input(), whence(), win_new(), write_config(), and write_view_buffer().
strnz_dup()
char * strnz_dup (char * s, size_t l)
Allocates memory for and duplicates string s up to length l or until line feed or carriage return.
Parameters
s - string to duplicate
l - maximum length to copy
Returns
pointer to allocated memory
Definition at line 318 of file futil.c.
strz()
size_t strz (char * s)
Terminates string at new line or carriage return.
Parameters
s string to terminate
Definition at line 264 of file futil.c.
to_string()
String to_string (const char * s)
String functions provide a simple string library to facilitate string manipulation in C, allowing developers to easily create, copy, concatenate, and free strings without having to manage memory manually.
Note
The library includes functions to convert C strings to String structs, create new String structs with specified lengths, copy and concatenate String structs, and free the memory used by String structs. By using this library, developers can avoid common pitfalls of C string handling, such as buffer overflows and memory leaks, while still benefiting from the performance advantages of C.
Designed to be simple and easy to use, making it a great choice for developers who want to work with strings in C without having to worry about the complexities of manual memory management.
The String struct is defined as follows:
typedef struct {
    size_t l; // length of the string (including null terminator)
    char *s;  // pointer to the dynamically allocated string
} String;
All functions in this library that return a String struct allocate memory for the string using malloc or realloc. It is the caller's responsibility to free this memory using the free_string function when it is no longer needed to avoid memory leaks.
The String functions in this library do not perform bounds checking on the input strings or the resulting strings. It is the caller's responsibility to ensure that all input strings are valid and that the resulting strings do not exceed available memory.
The String functions in this library assume that all input strings are null-terminated. If any input string is not null-terminated, the behavior is undefined.
See also
snippets/strings_test1.c
Convert C string to String struct
Parameters
s C string
Returns
String struct containing dynamically allocated copy of input string
Note
the caller is responsible for freeing the allocated memory.
Definition at line 1215 of file futil.c.
References String::l, and String::s.
trim()
size_t trim (char * s)
Trims leading and trailing spaces from string s in place.
Parameters
s - string to trim
Returns
length of trimmed string
Definition at line 83 of file futil.c.
Referenced by form_fmt_field(), form_parse_desc(), left_justify(), parse_menu_description(), and right_justify().
trim_ext()
bool trim_ext (char * buf, char * filename)
trims the file extension from "filename" and copies the result to "buf"
Parameters
buf - buffer to receive result
filename - filename to trim
Note
The caller is responsible for ensuring that "buf" has enough space to receive the result.
Definition at line 666 of file futil.c.
trim_path()
bool trim_path (char * dir)
Trims trailing spaces and slashes from directory path in place.
Parameters
dir - directory path to trim
Returns
true if successful
Definition at line 639 of file futil.c.
Referenced by derive_file_spec().
verify_dir()
bool verify_dir (char * spec, int imode)
Verifies that the directory specified by "spec" exists and is accessible with the permissions specified by "imode".
Parameters
spec - directory specification
imode - access mode F_OK - existence R_OK - read W_OK - Write X_OK - Execute S_WCOK - Write or Create S_QUIET - Suppress Error Messages
Note
S_WCOK and S_QUIET are stripped before calling faccessat
Returns
true if successful
Definition at line 763 of file futil.c.
References display_error(), em0, em1, em2, em3, expand_tilde(), fn, MAXLEN, S_QUIET, S_WCOK, src_line, src_name, ssnprintf(), and strnz__cpy().
Referenced by mapp_initialization(), mk_dir(), and verify_spec_arg().
verify_file()
bool verify_file (char * in_spec, int imode)
Verifies that the file specified by "in_spec" exists and is accessible with the permissions specified by "imode".
Parameters
in_spec - directory specification
imode - access mode F_OK - existence R_OK - read W_OK - Write X_OK - Execute S_WCOK - Write or Create S_QUIET - Suppress Error Messages
Note
S_WCOK and S_QUIET are stripped before calling faccessat
Returns
true if successful
Definition at line 813 of file futil.c.
References canonicalize_file_spec(), display_error(), em0, em1, em2, em3, expand_tilde(), fn, MAXLEN, S_QUIET, S_WCOK, src_line, src_name, ssnprintf(), and strnz__cpy().
Referenced by verify_spec_arg().
Variable Documentation
errmsg
char errmsg[MAXLEN]
Examples
/usr/local/src/cmenu/src/enterchr.c, and /usr/local/src/cmenu/src/enterstr.c.
Definition at line 63 of file futil.c.
Referenced by main(), and rgb_clr_to_cube().