C-Menu: iloan.c File Reference
iloan.c File Reference
Installment Loan Calculator.
#include <math.h>
#include <signal.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Macros
#define FALSE 0
#define TRUE 1
Functions
void numbers (char *d, char *s)
double calculate_i (double, double, double)
double calculate_n (double, double, double)
double calculate_pmt (double, double, double)
double calculate_pv (double, double, double)
int is_numeric (char *)
void accept_str (char *s)
char * format_currency (float)
char * format_interest (float)
double accept_pv ()
double accept_n ()
double accept_i ()
double accept_pmt ()
void error_press_any_key (char *)
void ABEND (int)
int main (int argc, char **argv)
iloan is a trivial application to demonstrate how a command-line program can be integrated into C-Menu Form with simple file, argument, or pipe i-o.
Variables
char in_str [BUFSIZ+1]
int f_pv = 0
int f_n = 0
int f_i = 0
int f_pmt = 0
bool f_quiet = false
Detailed Description
Installment Loan Calculator.
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file iloan.c.
Macro Definition Documentation
FALSE
#define FALSE 0
Definition at line 18 of file iloan.c.
Referenced by form_accept_field(), format_currency(), is_numeric(), open_pick_win(), parse_menu_description(), save_object(), and toggle_object().
TRUE
#define TRUE 1
Definition at line 19 of file iloan.c.
Referenced by display_curses_keys(), form_accept_field(), format_currency(), is_numeric(), main(), menu_cmd_processor(), parse_menu_description(), and win_resize().
Function Documentation
ABEND()
void ABEND (int e)
Definition at line 402 of file iloan.c.
Referenced by main().
accept_i()
double accept_i ()
Definition at line 221 of file iloan.c.
References accept_str(), error_press_any_key(), in_str, and is_numeric().
Referenced by main().
accept_n()
double accept_n ()
Definition at line 205 of file iloan.c.
References accept_str(), error_press_any_key(), in_str, and is_numeric().
Referenced by main().
accept_pmt()
double accept_pmt ()
Definition at line 242 of file iloan.c.
References accept_str(), error_press_any_key(), in_str, and is_numeric().
Referenced by main().
accept_pv()
double accept_pv ()
Definition at line 184 of file iloan.c.
References accept_str(), error_press_any_key(), in_str, and is_numeric().
Referenced by main().
accept_str()
void accept_str (char * s)
Definition at line 349 of file iloan.c.
References BUFSIZ, and in_str.
Referenced by accept_i(), accept_n(), accept_pmt(), and accept_pv().
calculate_i()
double calculate_i (double pv, double n, double pmt)
Definition at line 291 of file iloan.c.
References error_press_any_key(), f_quiet, and format_interest().
Referenced by main().
calculate_n()
double calculate_n (double pv, double i, double pmt)
Definition at line 279 of file iloan.c.
References error_press_any_key(), f_quiet, and format_currency().
Referenced by main().
calculate_pmt()
double calculate_pmt (double pv, double n, double i)
Definition at line 328 of file iloan.c.
References error_press_any_key(), f_quiet, and format_currency().
Referenced by main().
calculate_pv()
double calculate_pv (double n, double i, double pmt)
Definition at line 266 of file iloan.c.
References error_press_any_key(), f_quiet, and format_currency().
Referenced by main().
error_press_any_key()
void error_press_any_key (char * s)
Definition at line 260 of file iloan.c.
Referenced by accept_i(), accept_n(), accept_pmt(), accept_pv(), calculate_i(), calculate_n(), calculate_pmt(), calculate_pv(), and main().
format_currency()
char * format_currency (float a)
Definition at line 354 of file iloan.c.
References FALSE, and TRUE.
Referenced by calculate_n(), calculate_pmt(), calculate_pv(), and main().
format_interest()
char * format_interest (float a)
Definition at line 393 of file iloan.c.
Referenced by calculate_i(), and main().
is_numeric()
int is_numeric (char * s)
Definition at line 340 of file iloan.c.
References FALSE, and TRUE.
Referenced by accept_i(), accept_n(), accept_pmt(), and accept_pv().
main()
int main (int argc, char ** argv)
iloan is a trivial application to demonstrate how a command-line program can be integrated into C-Menu Form with simple file, argument, or pipe i-o.
Note
Positional arguments present_value The present value of the loan (the amount borrowed). number_of_payments The total number of payments to be made. interest_rate The annual interest rate (as a percentage). payment_amount The amount of each payment.
The program calculates the missing value based on the three provided values. For example, if the present value, number of payments, and interest rate are provided, it will calculate the payment amount. If the present value, interest rate, and payment amount are provided, it will calculate the number of payments, and so on.
The program can be used in a non-interactive way by passing the four values as arguments, with the value to be calculated set to 0. For example, to calculate the payment amount for a $10,000 loan with a 5% annual interest rate and 60 monthly payments, you could run:
iloan 10000 60 5 0
This is proof-of-concept code, and is not intended for production use. It is not designed to be robust, and does not handle all edge cases or input errors. It is intended solely to demonstrate how a simple command-line program can be integrated into C-Menu Form.
In the future, more sophisticated abstractions, such as async event handlers, serialization, rpc, database, and a standardized plugin interface will be integrated into C-Menu.
Feel free to modify and enhance this code as needed, but please do not use it in production without proper testing and validation. It is provided as-is without any warranty or support. Use at your own risk.
Definition at line 74 of file iloan.c.
References ABEND(), accept_i(), accept_n(), accept_pmt(), accept_pv(), BUFSIZ, calculate_i(), calculate_n(), calculate_pmt(), calculate_pv(), error_press_any_key(), f_i, f_n, f_pmt, f_pv, f_quiet, format_currency(), format_interest(), numbers(), and tmp_str.
numbers()
void numbers (char * d, char * s)
Definition at line 407 of file iloan.c.
Referenced by main().
Variable Documentation
f_i
int f_i = 0
Definition at line 39 of file iloan.c.
Referenced by main().
f_n
int f_n = 0
Definition at line 38 of file iloan.c.
Referenced by main().
f_pmt
int f_pmt = 0
Definition at line 40 of file iloan.c.
Referenced by main().
f_pv
int f_pv = 0
Definition at line 37 of file iloan.c.
Referenced by main().
f_quiet
bool f_quiet = false
Definition at line 41 of file iloan.c.
Referenced by calculate_i(), calculate_n(), calculate_pmt(), calculate_pv(), and main().
in_str
char in_str[BUFSIZ+1]
Examples
/usr/local/src/cmenu/src/enterstr.c.
Definition at line 20 of file iloan.c.
Referenced by accept_i(), accept_n(), accept_pmt(), accept_pv(), accept_str(), fmt_line(), and main().