C-Menu: src/snippets/strings_test1.c File Reference
strings_test1.c File Reference
String Objects.
#include <cm.h>
#include <stddef.h>
Functions
int main ()
Detailed Description
String Objects.
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file strings_test1.c.
Function Documentation
main()
int main ()
Test
Test string concatenation functions This test verifies that the string concatenation functions work correctly. It creates two strings, concatenates them, and checks the results.
Note
It is not necessary to pre-allocate spaace for str1 or str2
< Output: Hello World
< Output: Hello World Wo
Examples
/usr/local/src/cmenu/src/enterchr.c, /usr/local/src/cmenu/src/enterstr.c, /usr/local/src/cmenu/src/test/rfc3339.c, and strings_test1.c.
Definition at line 17 of file strings_test1.c.
           {
    String str1 = to_string("Hello");
    String str2 = to_string(" World!");
    string_cat(&str1, &str2);
    printf("%s\n", str1.s);
    printf("bytes allocated for str1.s: %zu\n", str1.l);
    string_ncat(&str1, &str2, 3);
    printf("%s\n", str1.s);
    printf("bytes allocated for str1.s: %zu\n", str1.l);
    free_string(str1);
    free_string(str2);
    return 0;
}
References free_string(), String::l, String::s, string_cat(), string_ncat(), and to_string().