var searchData=
[
  ['icon_0',['What&apos;s the Icon?',['../d5/d77/md_FAQ.html#whats-the-icon',1,'']]],
  ['if_20you_20can_20t_20stop_20typing_20vi_1',['If You Can&apos;t Stop Typing &quot;vi&quot;',['../d7/da4/md_snippets.html#if-you-cant-stop-typing-vi',1,'']]],
  ['if_20you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_2',['🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.',['../d4/def/md_INSTALL.html#autotoc_md--enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'']]],
  ['in_20a_20box_20window_3',['View In a Box Window',['../d5/d77/md_FAQ.html#view-in-a-box-window',1,'']]],
  ['indicator_20shell_20prompts_4',['Privilege Indicator Shell Prompts',['../d7/da4/md_snippets.html#privilege-indicator-shell-prompts',1,'']]],
  ['inode_5',['Menu - What Happened to Delete by Inode',['../d5/d77/md_FAQ.html#menu---what-happened-to-delete-by-inode',1,'']]],
  ['input_6',['Input',['../d0/d30/md_README.html#c-keys---diagnose-keyboardmouse-input',1,'C-Keys - Diagnose Keyboard/Mouse Input'],['../index.html#c-keys---diagnose-keyboardmouse-input-1',1,'C-Keys - Diagnose Keyboard/Mouse Input']]],
  ['install_20c_20menu_7',['To Install C-Menu',['../d4/def/md_INSTALL.html#to-install-c-menu',1,'']]],
  ['install_20tree_20sitter_20cli_8',['Install Tree-Sitter-CLI',['../d5/d77/md_FAQ.html#install-tree-sitter-cli',1,'']]],
  ['installation_9',['Finish the installation',['../d4/def/md_INSTALL.html#finish-the-installation',1,'']]],
  ['installation_20guide_10',['Installation Guide',['../d4/def/md_INSTALL.html',1,'']]],
  ['installing_20bat_11',['Installing Bat',['../dc/db0/md_extras.html#installing-bat',1,'']]],
  ['installing_20ripgrep_12',['Installing Ripgrep',['../dc/db0/md_extras.html#installing-ripgrep',1,'']]],
  ['installing_20rust_13',['Installing Rust',['../dc/db0/md_extras.html#installing-rust',1,'']]],
  ['installing_20rust_20on_20linux_20and_20macos_14',['Installing Rust On Linux and macOS',['../dc/db0/md_extras.html#installing-rust-on-linux-and-macos',1,'']]],
  ['installment_20loan_20calculator_15',['Menu - Using the Installment Loan Calculator',['../d5/d77/md_FAQ.html#menu---using-the-installment-loan-calculator',1,'']]],
  ['instead_20of_20ls_16',['Use lsd instead of ls',['../d7/da4/md_snippets.html#use-lsd-instead-of-ls',1,'']]],
  ['integrating_20external_20executables_17',['Menu Form - Integrating External Executables',['../d5/d77/md_FAQ.html#menu-form---integrating-external-executables',1,'']]],
  ['intended_18',['Intended',['../d0/d30/md_README.html#highlights-pun-intended',1,'Highlights (Pun Intended)'],['../index.html#highlights-pun-intended-1',1,'Highlights (Pun Intended)']]],
  ['interface_20toolkit_19',['Interface Toolkit',['../d0/d30/md_README.html',1,'A User Interface Toolkit'],['../index.html',1,'A User Interface Toolkit']]],
  ['interprocess_20communications_20',['Menu - Interprocess Communications',['../d5/d77/md_FAQ.html#menu---interprocess-communications',1,'']]],
  ['introduction_21',['Introduction',['../d7/d7a/md_API.html#introduction',1,'Introduction'],['../de/d82/md_C-Menu-UG.html#introduction-1',1,'Introduction'],['../dc/db0/md_extras.html#introduction-2',1,'Introduction']]],
  ['issue_20on_20the_20c_20menu_20github_20repository_22',['🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.',['../d4/def/md_INSTALL.html#autotoc_md--enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'']]],
  ['issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_23',['🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.',['../d4/def/md_INSTALL.html#autotoc_md--enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'']]],
  ['it_24',['It',['../d0/d30/md_README.html#just-do-it',1,'Just Do It!'],['../index.html#just-do-it-1',1,'Just Do It!']]],
  ['items_25',['Selecting Items',['../de/d82/md_C-Menu-UG.html#selecting-items',1,'']]]
];
