var searchData=
[
  ['macos_0',['macOS',['../dc/db0/md_extras.html#bat-on-macos',1,'Bat On macOS'],['../dc/db0/md_extras.html#ghostty-on-macos',1,'Ghostty On macOS'],['../dc/db0/md_extras.html#installing-rust-on-linux-and-macos',1,'Installing Rust On Linux and macOS'],['../dc/db0/md_extras.html#lsd-on-macos',1,'lsd On macOS'],['../dc/db0/md_extras.html#ripgrep-on-macos',1,'Ripgrep On macOS'],['../dc/db0/md_extras.html#tree-sitter-on-macos',1,'Tree-Sitter On macOS'],['../dc/db0/md_extras.html#tree-sitter-parsers-on-macos',1,'Tree-Sitter Parsers On macOS'],['../dc/db0/md_extras.html#tree-sitter-cli-on-macos',1,'Tree-Sitter-CLI On macOS']]],
  ['maintaining_20security_20with_20rsh_1',['Maintaining Security with RSH',['../d0/d30/md_README.html#maintaining-security-with-rsh',1,'Maintaining Security with RSH'],['../index.html#maintaining-security-with-rsh-1',1,'Maintaining Security with RSH']]],
  ['makefile_2',['Option 3 - Build C-Menu Using Makefile',['../d4/def/md_INSTALL.html#option-3---build-c-menu-using-makefile',1,'']]],
  ['manual_20page_3',['Manual Page',['../d0/d30/md_README.html#example-manual-page',1,'Example Manual Page'],['../index.html#example-manual-page-1',1,'Example Manual Page']]],
  ['manual_20page_20using_20editor_4',['Manual Page Using Editor',['../d0/d30/md_README.html#example-manual-page-using-editor',1,'Example Manual Page Using Editor'],['../index.html#example-manual-page-using-editor-1',1,'Example Manual Page Using Editor']]],
  ['manual_20pages_5',['Manual Pages',['../d5/d77/md_FAQ.html#view---how-to-colorize-manual-pages',1,'View - How to Colorize Manual Pages'],['../d0/d30/md_README.html#view-and-color-manual-pages',1,'View and Color Manual Pages'],['../index.html#view-and-color-manual-pages-1',1,'View and Color Manual Pages']]],
  ['marks_6',['Why View Displays Question Marks',['../d5/d77/md_FAQ.html#why-view-displays-question-marks',1,'']]],
  ['math_20with_20c_20menu_20and_20gawk_7',['High Precision Math With C-Menu and Gawk',['../d5/d77/md_FAQ.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['menu_8',['Menu',['../dc/db0/md_extras.html#about-c-menu-and-r-menu',1,'About C-Menu and R-Menu'],['../dc/db0/md_extras.html',1,'Augmenting C-Menu'],['../d4/def/md_INSTALL.html#build-c-menu',1,'Build C-Menu'],['../d0/d30/md_README.html#elements-of-c-menu',1,'Elements of C-Menu'],['../index.html#elements-of-c-menu-1',1,'Elements of C-Menu'],['../de/d82/md_C-Menu-UG.html#menu',1,'Menu'],['../d0/d30/md_README.html#menu-1',1,'Menu'],['../index.html#menu-2',1,'Menu'],['../d4/def/md_INSTALL.html#to-install-c-menu',1,'To Install C-Menu']]],
  ['menu_20and_20gawk_9',['High Precision Math With C-Menu and Gawk',['../d5/d77/md_FAQ.html#high-precision-math-with-c-menu-and-gawk',1,'']]],
  ['menu_20and_20r_20menu_10',['About C-Menu and R-Menu',['../dc/db0/md_extras.html#about-c-menu-and-r-menu',1,'']]],
  ['menu_20api_11',['Neovim Linkage to the C-Menu API',['../dc/db0/md_extras.html#neovim-linkage-to-the-c-menu-api',1,'']]],
  ['menu_20bashrc_20configuration_12',['C-Menu bashrc Configuration',['../d7/da4/md_snippets.html#c-menu-bashrc-configuration',1,'']]],
  ['menu_20configuration_13',['C-Menu Configuration',['../d7/da4/md_snippets.html#c-menu-configuration',1,'']]],
  ['menu_20description_20file_14',['Menu Description File',['../d0/d30/md_README.html#sample-menu-description-file',1,'Sample Menu Description File'],['../index.html#sample-menu-description-file-1',1,'Sample Menu Description File']]],
  ['menu_20description_20file_20format_15',['Menu Description File Format',['../de/d82/md_C-Menu-UG.html#menu-description-file-format',1,'']]],
  ['menu_20desktop_20files_16',['C-Menu Desktop Files',['../d7/da4/md_snippets.html#c-menu-desktop-files',1,'']]],
  ['menu_20environment_20variables_17',['Helpful C-Menu Environment Variables',['../d7/da4/md_snippets.html#helpful-c-menu-environment-variables',1,'']]],
  ['menu_20example_18',['Menu Example',['../de/d82/md_C-Menu-UG.html#menu-example',1,'']]],
  ['menu_20exercises_19',['Menu Exercises',['../d0/d30/md_README.html#c-menu-exercises',1,'C-Menu Exercises'],['../index.html#c-menu-exercises-1',1,'C-Menu Exercises']]],
  ['menu_20form_20',['C-Menu Form',['../de/d82/md_C-Menu-UG.html#c-menu-form',1,'']]],
  ['menu_20form_20data_20types_21',['Menu Form - Data Types',['../d5/d77/md_FAQ.html#menu-form---data-types',1,'']]],
  ['menu_20form_20field_20delimiters_22',['Menu Form - Field Delimiters',['../d5/d77/md_FAQ.html#menu-form---field-delimiters',1,'']]],
  ['menu_20form_20integrating_20external_20executables_23',['Menu Form - Integrating External Executables',['../d5/d77/md_FAQ.html#menu-form---integrating-external-executables',1,'']]],
  ['menu_20form_20line_20type_20speecifiers_20h_20t_20f_20and_24',['Menu Form - Line Type Speecifiers (H, T, F, and ?)',['../d5/d77/md_FAQ.html#menu-form---line-type-speecifiers-h-t-f-and-',1,'']]],
  ['menu_20form_20pick_20and_20view_20api_25',['Menu, Form, Pick, and View API',['../d5/d77/md_FAQ.html#menu-form-pick-and-view-api',1,'']]],
  ['menu_20form_20pick_20view_20c_20keys_20rsh_20and_20lf_26',['Menu Form Pick View C Keys RSH and lf',['../d0/d30/md_README.html#menu-form-pick-view-c-keys-rsh-and-lf',1,'Menu, Form, Pick, View, C-Keys, RSH, and lf'],['../index.html#menu-form-pick-view-c-keys-rsh-and-lf-1',1,'Menu, Form, Pick, View, C-Keys, RSH, and lf']]],
  ['menu_20github_20repository_27',['🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.',['../d4/def/md_INSTALL.html#autotoc_md--enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'']]],
  ['menu_20html_20documentation_28',['Menu HTML Documentation',['../d0/d30/md_README.html#_new_---complete-c-menu-html-documentation',1,'&lt;b&gt;&lt;em&gt;NEW&lt;/em&gt;&lt;/b&gt; - Complete C-Menu HTML Documentation'],['../index.html#_new_---complete-c-menu-html-documentation-1',1,'&lt;b&gt;&lt;em&gt;NEW&lt;/em&gt;&lt;/b&gt; - Complete C-Menu HTML Documentation']]],
  ['menu_20if_20you_20encounter_20any_20issues_20or_20have_20questions_20feel_20free_20to_20open_20an_20issue_20on_20the_20c_20menu_20github_20repository_29',['🐸 Enjoy using C-Menu! If you encounter any issues or have questions, feel free to open an issue on the C-Menu GitHub repository.',['../d4/def/md_INSTALL.html#autotoc_md--enjoy-using-c-menu-if-you-encounter-any-issues-or-have-questions-feel-free-to-open-an-issue-on-the-c-menu-github-repository',1,'']]],
  ['menu_20interprocess_20communications_30',['Menu - Interprocess Communications',['../d5/d77/md_FAQ.html#menu---interprocess-communications',1,'']]],
  ['menu_20lf_20where_20are_20my_20header_20files_31',['Menu lf - Where Are My Header Files?',['../d5/d77/md_FAQ.html#menu-lf---where-are-my-header-files',1,'']]],
  ['menu_20options_32',['C-Menu Options',['../de/d82/md_C-Menu-UG.html#c-menu-options',1,'']]],
  ['menu_20pick_33',['C-Menu Pick',['../de/d82/md_C-Menu-UG.html#c-menu-pick',1,'']]],
  ['menu_20s_20file_20structure_34',['C-Menu&apos;s File Structure',['../d5/d77/md_FAQ.html#c-menus-file-structure',1,'']]],
  ['menu_20selections_20don_20t_20work_35',['Some Menu Selections Don&apos;t work',['../d5/d77/md_FAQ.html#some-menu-selections-dont-work',1,'']]],
  ['menu_20startup_20with_20mm_36',['C-Menu Startup with &quot;mm&quot;',['../d7/da4/md_snippets.html#c-menu-startup-with-mm',1,'']]],
  ['menu_20using_20cmake_20directly_37',['Option 1 - Build C-Menu Using CMake Directly',['../d4/def/md_INSTALL.html#option-1---build-c-menu-using-cmake-directly',1,'']]],
  ['menu_20using_20makefile_38',['Option 3 - Build C-Menu Using Makefile',['../d4/def/md_INSTALL.html#option-3---build-c-menu-using-makefile',1,'']]],
  ['menu_20using_20the_20installment_20loan_20calculator_39',['Menu - Using the Installment Loan Calculator',['../d5/d77/md_FAQ.html#menu---using-the-installment-loan-calculator',1,'']]],
  ['menu_20view_40',['C-Menu View',['../de/d82/md_C-Menu-UG.html#c-menu-view',1,'']]],
  ['menu_20what_20happened_20to_20delete_20by_20inode_41',['Menu - What Happened to Delete by Inode',['../d5/d77/md_FAQ.html#menu---what-happened-to-delete-by-inode',1,'']]],
  ['menu_20with_20provided_20scripts_42',['Option 2 - Build C-Menu with Provided Scripts',['../d4/def/md_INSTALL.html#option-2---build-c-menu-with-provided-scripts',1,'']]],
  ['mit_20license_43',['MIT License',['../da/d19/md_LICENSE.html',1,'MIT License'],['../d0/d30/md_README.html#mit-license-1',1,'MIT License'],['../index.html#mit-license-2',1,'MIT License']]],
  ['mm_44',['C-Menu Startup with &quot;mm&quot;',['../d7/da4/md_snippets.html#c-menu-startup-with-mm',1,'']]],
  ['motion_20keys_45',['Motion Keys',['../de/d82/md_C-Menu-UG.html#motion-keys',1,'']]],
  ['mouse_20input_46',['Mouse Input',['../d0/d30/md_README.html#c-keys---diagnose-keyboardmouse-input',1,'C-Keys - Diagnose Keyboard/Mouse Input'],['../index.html#c-keys---diagnose-keyboardmouse-input-1',1,'C-Keys - Diagnose Keyboard/Mouse Input']]],
  ['multiple_20executables_47',['Multiple Executables',['../d5/d77/md_FAQ.html#multiple-executables',1,'']]],
  ['multiple_20files_48',['Pick - Selecting Multiple Files',['../d5/d77/md_FAQ.html#pick---selecting-multiple-files',1,'']]],
  ['my_20header_20files_49',['Menu lf - Where Are My Header Files?',['../d5/d77/md_FAQ.html#menu-lf---where-are-my-header-files',1,'']]]
];
