C-Menu: include/common.h File Reference
common.h File Reference
Headder for C-Menu Menu, Form, Pick, and View components.
#include <ncursesw/ncurses.h>
#include <cm.h>
#include <form.h>
#include <menu.h>
#include <pick.h>
#include <view.h>
#include <stddef.h>
Data Structures
struct Init
Gathers runtime information for C-Menu Menu, Form, Pick, and View components, used for passing common data and state during initialization and processing of these componentsi.
Macros
#define _XOPEN_SOURCE_EXTENDED 1
#define NCURSES_WIDECHAR 1
#define USE_PAD TRUE
#define MIN_COLS 40
#define MAX_WIDE_LEN 1024
#define COLOR_LEN 8
#define PICK_MAX_ARG_LEN 256
#define MAX_ARGS 64
#define MAX_PICK_OBJS 1024
#define ACCEPT_PROMPT_CHAR '_'
#define MENU_HELP_FILE "help/menu.help"
#define PICK_HELP_FILE "help/pick.help"
#define VIEW_HELP_FILE "help/view.help"
#define VIEW_PRT_FILE "data/prtout"
#define DEFAULTEDITOR "vi"
#define MINITRC ".minitrc"
#define ABOUT ".about"
#define MAPP_DIR "~/menuapp"
#define PRINTCMD "lp -c -s"
#define MAXOPTS 50
#define EIGHT 8
#define F_VIEW 0x01
#define P_READ 0
#define P_WRITE 1
#define TRUE 1
#define new_cmenu()
#define destroy_cmenu()
Typedefs
typedef Menu Menu
typedef Form Form
typedef Pick Pick
typedef View View
Enumerations
enum Caller { VIEW , FORM , PICK , MENU }
enum OptType { OT_STRING , OT_INT , OT_BOOL , OT_HEX }
option types
enum OptGroup {
OG_FILES , OG_DIRS , OG_SPECS , OG_MISC ,
OG_PARMS , OG_FLAGS , OG_COL
}
option groups
enum { IC_MENU , IC_PICK , IC_FORM , IC_VIEW }
Functions
void mapp_initialization (Init *init, int, char **)
Main initialization function for MAPP - Menu Application.
Init * new_init (int, char **)
Create and initialize Init structure.
View * new_view (Init *init, int, char **)
Create and initialize View structure.
Form * new_form (Init *init, int, char **, int, int)
Create and initialize Form structure.
Pick * new_pick (Init *init, int, char **, int, int)
Create and initialize Pick structure.
Menu * new_menu (Init *init, int, char **, int, int)
Create and initialize Menu structure.
Menu * destroy_menu (Init *init)
Destroy Menu structure.
Pick * destroy_pick (Init *init)
Destroy Pick structure.
Form * destroy_form (Init *init)
Destroy Form structure.
View * destroy_view (Init *init)
Destroy View structure.
Init * destroy_init (Init *init)
Destroy Init structure.
int parse_opt_args (Init *, int, char **)
Parse command-line options and set Init struct values accordingly.
void zero_opt_args (Init *)
Initialize optional arguments in the Init struct to default values.
int write_config (Init *)
Write the current configuration to a file specified in init->minitrc.
bool derive_file_spec (char *, char *, char *)
Derive full file specification from directory and file name.
bool init_menu_files (Init *, int, char **)
Initialize Menu file specifications.
unsigned int menu_engine (Init *)
The main loop of the menu system.
unsigned int parse_menu_description (Init *)
Parse menu description file and create Menu.
int init_form (Init *, int, char **, int, int)
Initialize form data structure and parse description file.
int init_pick (Init *, int, char **, int, int)
Initializes pick structure and opens pick input file or pipe.
int open_pick_win (Init *)
Initializes the pick window based on the parameters specified in the Pick structure.
int pick_engine (Init *)
Initializes pick interface, calculates window size and position, and enters picker loop.
int view_file (Init *)
Start view.
int mview (Init *, int, char **)
subprogram entry point for C-Menu View
int init_view_full_screen (Init *)
Initialize C-Menu View in full screen mode.
int init_view_boxwin (Init *, char *)
Initialize the C-Menu View in box window mode.
bool view_init_input (View *, char *)
Initialize the input for a C-Menu View.
int cmd_processor (Init *)
Variables
Init * init
int init_cnt
char minitrc [MAXLEN]
Detailed Description
Headder for C-Menu Menu, Form, Pick, and View components.
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file common.h.
Macro Definition Documentation
_XOPEN_SOURCE_EXTENDED
#define _XOPEN_SOURCE_EXTENDED 1
Definition at line 13 of file common.h.
ABOUT
#define ABOUT ".about"
Definition at line 43 of file common.h.
ACCEPT_PROMPT_CHAR
#define ACCEPT_PROMPT_CHAR '_'
Definition at line 34 of file common.h.
COLOR_LEN
#define COLOR_LEN 8
Definition at line 30 of file common.h.
DEFAULTEDITOR
#define DEFAULTEDITOR "vi"
Definition at line 40 of file common.h.
Referenced by menu_cmd_processor(), and view_cmd_processor().
destroy_cmenu
#define destroy_cmenu ()
Value:
destroy_init(init);                                                        \
win_del();                                                                 \
destroy_curses();                                                          \
return 0;                                                                  \
}
Definition at line 66 of file common.h.
EIGHT
#define EIGHT 8
Definition at line 47 of file common.h.
F_VIEW
#define F_VIEW 0x01
Definition at line 48 of file common.h.
Referenced by init_view_boxwin().
MAPP_DIR
#define MAPP_DIR "~/menuapp"
Definition at line 44 of file common.h.
MAX_ARGS
#define MAX_ARGS 64
Definition at line 32 of file common.h.
Referenced by enter_file_spec(), and menu_cmd_processor().
MAX_PICK_OBJS
#define MAX_PICK_OBJS 1024
Definition at line 33 of file common.h.
MAX_WIDE_LEN
#define MAX_WIDE_LEN 1024
Definition at line 29 of file common.h.
MAXOPTS
#define MAXOPTS 50
Definition at line 46 of file common.h.
MENU_HELP_FILE
#define MENU_HELP_FILE "help/menu.help"
Definition at line 36 of file common.h.
MIN_COLS
#define MIN_COLS 40
Definition at line 27 of file common.h.
MINITRC
#define MINITRC ".minitrc"
Definition at line 42 of file common.h.
NCURSES_WIDECHAR
#define NCURSES_WIDECHAR 1
Definition at line 14 of file common.h.
new_cmenu
#define new_cmenu ()
Value:
__end_pgm;                                                                 \
int main(int argc, char **argv) {                                          \
    __atexit;                                                              \
    capture_shell_tioctl();                                                \
    Init *init = new_init(argc, argv);                                     \
    SIO *sio = init->sio;                                                  \
    mapp_initialization(init, argc, argv);                                 \
    open_curses(sio);                                                      \
    sig_prog_mode();                                                       \
    capture_curses_tioctl();                                               \
    win_init_attrs(sio->fg_color, sio->bg_color, sio->bo_color);
Definition at line 53 of file common.h.
P_READ
#define P_READ 0
Definition at line 49 of file common.h.
Referenced by form_calculate(), init_pick(), and view_init_input().
P_WRITE
#define P_WRITE 1
Definition at line 50 of file common.h.
Referenced by form_calculate(), init_pick(), and view_init_input().
PICK_HELP_FILE
#define PICK_HELP_FILE "help/pick.help"
Definition at line 37 of file common.h.
PICK_MAX_ARG_LEN
#define PICK_MAX_ARG_LEN 256
Definition at line 31 of file common.h.
PRINTCMD
#define PRINTCMD "lp -c -s"
Definition at line 45 of file common.h.
Referenced by lp(), and menu_cmd_processor().
TRUE
#define TRUE 1
Definition at line 51 of file common.h.
USE_PAD
#define USE_PAD TRUE
Definition at line 26 of file common.h.
VIEW_HELP_FILE
#define VIEW_HELP_FILE "help/view.help"
Definition at line 38 of file common.h.
Referenced by view_display_help().
VIEW_PRT_FILE
#define VIEW_PRT_FILE "data/prtout"
Definition at line 39 of file common.h.
Referenced by menu_cmd_processor().
Typedef Documentation
Form
typedef Form Form
Definition at line 95 of file common.h.
Menu
typedef Menu Menu
Definition at line 94 of file common.h.
Pick
typedef Pick Pick
Definition at line 96 of file common.h.
View
typedef View View
Definition at line 97 of file common.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IC_MENU
IC_PICK
IC_FORM
IC_VIEW
Definition at line 182 of file common.h.
Caller
enum Caller
Enumerator
VIEW
FORM
PICK
MENU
Definition at line 73 of file common.h.
OptGroup
enum OptGroup
option groups
Enumerator
OG_FILES
OG_DIRS
OG_SPECS
OG_MISC
OG_PARMS
OG_FLAGS
OG_COL
Definition at line 84 of file common.h.
OptType
enum OptType
option types
Enumerator
OT_STRING
OT_INT
OT_BOOL
OT_HEX
Definition at line 76 of file common.h.
Function Documentation
cmd_processor()
int cmd_processor (Init *) extern
derive_file_spec()
bool derive_file_spec (char * file_spec, char * dir, char * file_name) extern
Derive full file specification from directory and file name.
Parameters
file_spec - output full file specification
dir - directory path
file_name - file name
Returns
true if file_spec is derived, false otherwise
Note
If dir is nullptr, use MAPP_DIR environment variable or default directory ~/menuapp
file_spec should be a pre-allocated char array of size MAXLEN to hold the resulting file specification
Definition at line 796 of file init.c.
References file_name, MAXLEN, strnz__cat(), strnz__cpy(), and trim_path().
destroy_form()
Form * destroy_form (Init * init) extern
Destroy Form structure.
Parameters
init structure
Returns
nullptr
Definition at line 255 of file mem.c.
References init.
Referenced by destroy_init(), enter_file_spec(), form_engine(), and init_form().
destroy_init()
Init * destroy_init (Init * init) extern
Destroy Init structure.
Parameters
init structure
Returns
nullptr
Definition at line 93 of file mem.c.
References destroy_form(), destroy_menu(), destroy_pick(), destroy_view(), init, and init_cnt.
Referenced by main().
destroy_menu()
Menu * destroy_menu (Init * init) extern
Destroy Menu structure.
Parameters
init structure
Returns
nullptr
Definition at line 165 of file mem.c.
References init.
Referenced by destroy_init(), and menu_cmd_processor().
destroy_pick()
Pick * destroy_pick (Init * init) extern
Destroy Pick structure.
Parameters
init structure
Returns
nullptr
Definition at line 211 of file mem.c.
References init, and pick.
Referenced by destroy_init(), and init_pick().
destroy_view()
View * destroy_view (Init * init) extern
Destroy View structure.
Parameters
init structure
Returns
nullptr
Definition at line 326 of file mem.c.
References init, and view.
Referenced by destroy_init(), and mview().
init_form()
int init_form (Init * init, int argc, char ** argv, int begy, int begx) extern
Initialize form data structure and parse description file.
Parameters
init A pointer to the Init structure containing form data and state.
argc The number of command line arguments passed to the form.
argv The array of command line arguments passed to the form.
begy The y-coordinate for the top-left corner of the form window.
begx The x-coordinate for the top-left corner of the form window.
Returns
0 on success, or a non-zero value if an error occurs during
Definition at line 53 of file form_engine.c.
References begx, begy, destroy_form(), form, form_engine(), init, MAXLEN, new_form(), Perror(), strnz__cat(), strnz__cpy(), tmp_str, and win_del().
Referenced by enter_file_spec(), main(), and menu_cmd_processor().
init_menu_files()
bool init_menu_files (Init * init, int argc, char ** argv) extern
Initialize Menu file specifications.
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
Note
Positional args: [menu desc], [help file]
Definition at line 461 of file mem.c.
References abend(), init, MAXLEN, menu, strnz__cat(), strnz__cpy(), tmp_str, and verify_spec_arg().
Referenced by new_menu().
init_pick()
int init_pick (Init * init, int argc, char ** argv, int begy, int begx) extern
Initializes pick structure and opens pick input file or pipe.
Parameters
init Pointer to Init structure
argc Argument count
argv Argument vector
begy Beginning y coordinate for pick window
begx Beginning x coordinate for pick window
Note
If provider_cmd is specified, it takes precedence over in_spec and input file arguments
provider_cmd is executed and its output is read as pick input
If provider_cmd is not specified, in_spec is used to read pick input from a file or stdin
If provider_cmd is specified, it is executed and its output is read as pick input
Spawn Child to execute provider_cmd Close read end of pipe as Child only needs to write to pipe
Connect CHILD STDOUT to write end of pipe
STDOUT attached to write end of pipe, so close pipe fd
Return to Parent Close write end of pipe as Parent only needs to read from pipe
Open a file pointer on read end of pipe
No provider_cmd specified, so read pick input from file or stdin
Wait for provider_cmd child process to finish before proceeding
Enter pick_engine
Definition at line 54 of file pick_engine.c.
References abend(), begx, begy, destroy_pick(), init, MAXARGS, MAXLEN, new_pick(), P_READ, P_WRITE, Perror(), pick, pick_engine(), pipe_fd, read_pick_input(), restore_curses_tioctl(), sig_prog_mode(), sio, str_to_args(), strnz__cat(), strnz__cpy(), tmp_str, and win_del().
Referenced by main(), and menu_cmd_processor().
init_view_boxwin()
int init_view_boxwin (Init * init, char * title) extern
Initialize the C-Menu View in box window mode.
Note
sets up the view structure for box window mode, adjusts dimensions based on screen size, and creates a new pad for the view. It also configures various parameters such as scroll lines, command line position, and tab size.
Parameters
init Pointer to the Init structure containing view settings.
title Title for the box window.
Returns
0 on success, -1 on failure.
Definition at line 69 of file init_view.c.
References CCC_NORM, display_error(), em0, em1, em2, F_VIEW, init, MAXLEN, PAD_COLS, ssnprintf(), strnz__cpy(), view, win_new(), win_ptr, and win_win.
Referenced by mview().
init_view_full_screen()
int init_view_full_screen (Init * init) extern
Initialize C-Menu View in full screen mode.
Note
This function sets up the view structure for full screen mode and creates a new pad for the view.
Parameters
init Pointer to the Init structure containing view settings.
Returns
0 on success, -1 on failure.
Definition at line 28 of file init_view.c.
References abend(), CCC_BOX, display_error(), em0, em1, em2, init, MAXLEN, PAD_COLS, ssnprintf(), and view.
Referenced by main().
mapp_initialization()
void mapp_initialization (Init * init, int argc, char ** argv) extern
Main initialization function for MAPP - Menu Application.
Parameters
init - pointer to Init struct to be initialized
argc - argument count from main()
argv - argument vector from main()
1. Read environment variables and set defaults
2. Parse configuration file
3. Parse command-line options
4. Set up SIO struct with colors and other settings
5. Handle special options like help and version
< background color
< foreground color
< border color
< clear screen on exit (obsolete)
< erase remainder on enter
< field enclosure brackets
< field fill character
< view prompt type
< menu specification file
< generally /home/user/.minitrc
< command-line options override config file
Definition at line 64 of file init.c.
References abend(), BG_COLOR, BO_COLOR, display_version(), dump_config(), expand_tilde(), f_debug, f_dump_config, f_help, f_version, f_write_config, FG_COLOR, init, MAXLEN, parse_config(), parse_opt_args(), PT_LONG, sio, ssnprintf(), strnz__cpy(), tmp_str, verify_dir(), and write_config().
Referenced by main().
menu_engine()
unsigned int menu_engine (Init * init) extern
The main loop of the menu system.
Parameters
init A pointer to an Init structure containing initialization data for the menu system.
Returns
an integer indicating the action taken by the user, such as returning to the main menu or exiting the menu system.
Note
displays the menu and processes user input until the user exits the menu or returns to the main menu.
Definition at line 28 of file menu_engine.c.
References init, MA_DISPLAY_MENU, MA_ENTER_OPTION, MA_INIT, MA_RETURN, MAXLEN, menu, menu_cmd_processor(), MT_CHOICE, parse_menu_description(), Perror(), ssnprintf(), tmp_str, win_box, win_del(), win_new(), win_ptr, and win_win.
Referenced by main(), and menu_cmd_processor().
mview()
int mview (Init * init, int argc, char ** argv) extern
subprogram entry point for C-Menu View
Parameters
init Pointer to Init structure containing initialization parameters
argc Argument count from command line
argv Argument vector from command line
Returns
0 on success, non-zero on failure
Note
use this function to start the C-Menu View from another program, passing in the necessary initialization parameters through the Init structure. The function will handle setting up the view based on the provided parameters and will return 0 on success or a non-zero value if an error occurs during initialization.
Definition at line 23 of file mview.c.
References destroy_view(), init, init_view_boxwin(), new_view(), view, view_file(), and win_del().
Referenced by display_pick_help(), exec_objects(), form_engine(), main(), menu_cmd_processor(), and view_display_help().
new_form()
Form * new_form (Init * init, int argc, char ** argv, int begy, int begx) extern
Create and initialize Form structure.
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
begy,begx - initial position of form window
Definition at line 233 of file mem.c.
References abend(), begx, begy, form, init, init_form_files(), MAXLEN, and strnz__cpy().
Referenced by init_form().
new_init()
Init * new_init (int argc, char ** argv) extern
Create and initialize Init structure.
Note
calloc initializes all fields to zero/nullptr
Parameters
argc,argv - arguments idiomatic directory usage:
init->mapp_msrc  description files
init->mapp_help  help files
init->mapp_data  in, out, data files
init->mapp_user  executable scripts
init->mapp_bin   binary executables
Note
Initialize file specifications in priority order:
1 - Default values
2 - Configuration file
3 - Environment variables
4 - Command line positional arguments
5 - Command line option arguments
Definition at line 57 of file mem.c.
References abend(), display_error(), em0, em1, em2, init, init_cnt, MAXARGS, MAXLEN, and ssnprintf().
Referenced by main().
new_menu()
Menu * new_menu (Init * init, int argc, char ** argv, int begy, int begx) extern
Create and initialize Menu structure.
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
begy,begx - initial position of menu window
Definition at line 145 of file mem.c.
References abend(), begx, begy, init, init_menu_files(), and menu.
Referenced by main(), and menu_cmd_processor().
new_pick()
Pick * new_pick (Init * init, int argc, char ** argv, int begy, int begx) extern
Create and initialize Pick structure.
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
begy,begx - initial position of pick window
Definition at line 182 of file mem.c.
References abend(), begx, begy, display_error(), em0, em1, init, init_pick_files(), MAXLEN, OBJ_MAXCNT, Perror(), pick, and ssnprintf().
Referenced by init_pick().
new_view()
View * new_view (Init * init, int argc, char ** argv) extern
Create and initialize View structure.
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
Definition at line 283 of file mem.c.
References abend(), display_error(), em0, em1, em2, init, init_view_files(), MAXLEN, ssnprintf(), and view.
Referenced by main(), and mview().
open_pick_win()
int open_pick_win (Init * init) extern
Initializes the pick window based on the parameters specified in the Pick structure.
Parameters
init Pointer to Init structure containing pick information
Returns
0 on success, 1 on failure
Note
Creates a new window for the pick interface using win_new function with the specified parameters from the Pick structure. If window creation fails, an error message is printed and the function returns 1. Otherwise, initializes the window and box pointers in the Pick structure, sets scrollok and keypad options for the window, and returns 0 on success.
Definition at line 821 of file pick_engine.c.
References FALSE, init, MAXLEN, Perror(), pick, ssnprintf(), tmp_str, win_box, win_new(), win_ptr, and win_win.
Referenced by pick_engine().
parse_menu_description()
unsigned int parse_menu_description (Init * init) extern
Parse menu description file and create Menu.
Parameters
init Pointer to Init structure containing menu information
Returns
0 on success, non-zero on failure
'#' Comment line, ignore
'!' Choice line, parse and add to menu
':' Text line, parse and add to menu
< in_buf -> Title
'?' Help line, ignore for now
' ' Empty line, ignore
Definition at line 24 of file parse_menu_desc.c.
References abend(), chrep(), CT_RETURN, display_error(), em0, em1, em2, FALSE, get_command_type(), init, MAXLEN, menu, MT_CHOICE, MT_TEXT, Perror(), ssnprintf(), strnz__cat(), strnz__cpy(), tmp_str, trim(), and TRUE.
Referenced by main(), menu_cmd_processor(), and menu_engine().
parse_opt_args()
int parse_opt_args (Init * init, int argc, char ** argv) extern
Parse command-line options and set Init struct values accordingly.
Parameters
init - pointer to Init struct
argc - argument count
argv - argument vector Return index of first non-option argument
Note
Accepts both short and long options
Definition at line 158 of file init.c.
References base_name(), clr_name_to_idx(), f_dump_config, f_help, f_version, f_write_config, HELP_SPEC, IN_SPEC, init, MAPP_DATA_DIR, MAPP_HELP, MAPP_HELP_DIR, MAPP_MSRC, MAPP_SPEC, MAXLEN, OUT_SPEC, prompt_str_to_int(), sio, str_to_double(), strnz__cpy(), and tmp_str.
Referenced by display_pick_help(), enter_file_spec(), exec_objects(), form_engine(), mapp_initialization(), menu_cmd_processor(), and view_display_help().
pick_engine()
int pick_engine (Init * init) extern
Initializes pick interface, calculates window size and position, and enters picker loop.
Parameters
init Pointer to Init structure containing pick information
Returns
Count of selected objects on success, -1 if user cancels
Note
Initializes key command strings for chyron display and calculates pick window size and position based on terminal size and pick parameters.
Opens pick window and displays first page of objects. Enters picker loop to handle user input and interactions. If user cancels selection, returns -1.
If user accepts selection, returns count of selected objects.
Initialize window and data structures
Initialize key command strings for chyron display
Calculate pick window size and position based on terminal size and pick parameters
Enter picker loop to handle user input and interactions
Definition at line 199 of file pick_engine.c.
References compile_chyron(), display_page(), exec_objects(), init, new_chyron(), open_pick_win(), output_objects(), pick, picker(), reverse_object(), set_chyron_key(), and strnz().
Referenced by init_pick().
view_file()
int view_file (Init * init) extern
Start view.
Definition at line 84 of file view_engine.c.
References init, next_page(), view, view_cmd_processor(), and view_init_input().
Referenced by main(), and mview().
view_init_input()
bool view_init_input (View * view, char * file_name) extern
Initialize the input for a C-Menu View.
This function initializes the input for view, which can be a file, standard input, or a provider command to be initiated by view. It handles different input sources and sets up the necessary file descriptors and memory mapping for efficient access.
Parameters
view Pointer to the View structure to be initialized.
file_name Name of the input file or "-" for standard input.
Returns
true on success, false on failure.
Note
if a provider command is specified, set up a pipe to read its output. A child process is spawned, and view, the parent process, reads from the pipe.
If input is from a pipe or standard input, clone it to a temporary file. This allows for memory-mapping the input later. It does not support real-time updates to the input, but it allows for efficient access to the data.
Open the input file for reading and get its size.
Definition at line 146 of file init_view.c.
References abend(), base_name(), display_error(), em0, em1, em2, expand_tilde(), file_name, MAXARGS, MAXLEN, NMARKS, NULL_POSITION, P_READ, P_WRITE, Perror(), pipe_fd, ssnprintf(), str_to_args(), strnz__cat(), strnz__cpy(), tmp_str, VBUFSIZ, and view.
Referenced by view_file().
write_config()
int write_config (Init * init) extern
Write the current configuration to a file specified in init->minitrc.
Parameters
init - pointer to Init struct containing current configuration
Returns
0 on success, -1 on failure
Note
The configuration is written in key=value format, one per line
Lines beginning with '#' are comments and are ignored when reading the config file
The file is created if it does not exist, and overwritten if it does exist
Definition at line 689 of file init.c.
References colors_text, init, MAXLEN, Perror(), prompt_int_to_str(), sio, strnz__cat(), strnz__cpy(), and tmp_str.
Referenced by mapp_initialization(), and menu_cmd_processor().
zero_opt_args()
void zero_opt_args (Init * init) extern
Initialize optional arguments in the Init struct to default values.
Parameters
init - pointer to Init struct to be initialized This function sets all optional argument fields in the Init struct to their default values before parsing command-line options or configuration file. This ensures that any fields not specified by the user will have known default values.
Definition at line 132 of file init.c.
References init.
Referenced by display_pick_help(), enter_file_spec(), exec_objects(), form_engine(), menu_cmd_processor(), and view_display_help().
Variable Documentation
init
Init* init extern
Definition at line 184 of file common.h.
Referenced by destroy_form(), destroy_init(), destroy_menu(), destroy_pick(), destroy_view(), display_pick_help(), dump_config(), enter_file_spec(), exec_objects(), form_calculate(), form_display_screen(), form_end_fields(), form_engine(), init_form(), init_form_files(), init_menu_files(), init_pick(), init_pick_files(), init_view_boxwin(), init_view_files(), init_view_full_screen(), main(), mapp_initialization(), menu_cmd_processor(), menu_engine(), mview(), new_form(), new_init(), new_menu(), new_pick(), new_view(), open_pick_win(), parse_config(), parse_menu_description(), parse_opt_args(), pick_engine(), picker(), read_pick_input(), resize_page(), view_cmd_processor(), view_display_help(), view_file(), write_config(), write_view_buffer(), and zero_opt_args().
init_cnt
int init_cnt extern
Definition at line 31 of file mem.c.
Referenced by destroy_init(), and new_init().
minitrc
char minitrc[MAXLEN] extern
number of Init data structures allocated