C-Menu: src/mem.c File Reference
mem.c File Reference
Create and destroy main data structures for C-Menu.
#include <common.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
Functions
Init * new_init (int argc, char **argv)
Create and initialize Init structure.
Menu * new_menu (Init *init, int argc, char **argv, int begy, int begx)
Create and initialize Menu structure.
Pick * new_pick (Init *init, int argc, char **argv, int begy, int begx)
Create and initialize Pick structure.
Form * new_form (Init *init, int argc, char **argv, int begy, int begx)
Create and initialize Form structure.
View * new_view (Init *init, int argc, char **argv)
Create and initialize View structure.
View * destroy_view (Init *init)
Destroy View structure.
Form * destroy_form (Init *init)
Destroy Form structure.
Pick * destroy_pick (Init *init)
Destroy Pick structure.
Menu * destroy_menu (Init *init)
Destroy Menu structure.
Init * destroy_init (Init *init)
Destroy Init structure.
bool init_menu_files (Init *init, int argc, char **argv)
Initialize Menu file specifications.
bool init_pick_files (Init *init, int argc, char **argv)
Initialize Pick file specifications.
bool init_form_files (Init *init, int argc, char **argv)
Initialize Form file specifications.
bool init_view_files (Init *init)
Initialize Pick file specifications.
bool verify_spec_arg (char *spec, char *org_spec, char *dir, char *alt_dir, int mode)
Verify file specification argument.
Variables
int init_cnt = 0
Menu * menu
Pick * pick
Form * form
View * view
Detailed Description
Create and destroy main data structures for C-Menu.
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file mem.c.
Function Documentation
destroy_form()
Form * destroy_form (Init * init)
Destroy Form structure.
Parameters
init structure
Returns
nullptr
Definition at line 255 of file mem.c.
{
    int i;
    if (!init->form)
        return nullptr;
    for (i = 0; i < init->form->fidx; i++) {
        if (init->form->field[i])
            free(init->form->field[i]);
        init->form->field[i] = nullptr;
    }
    for (i = 0; i < init->form->didx; i++) {
        if (init->form->text[i])
            free(init->form->text[i]);
        init->form->text[i] = nullptr;
    }
    free(init->form);
    init->form = nullptr;
    init->form_cnt--;
    return init->form;
}
References init.
Referenced by destroy_init(), enter_file_spec(), form_engine(), and init_form().
destroy_init()
Init * destroy_init (Init * init)
Destroy Init structure.
Parameters
init structure
Returns
nullptr
Definition at line 93 of file mem.c.
{
    int i;
    if (!init)
        return nullptr;
    if (init->sio) {
        free(init->sio);
        init->sio = nullptr;
    }
    if (init->menu) {
        init->menu = destroy_menu(init);
        init->menu = nullptr;
    }
    if (init->view) {
        init->view = destroy_view(init);
        init->view = nullptr;
    }
    if (init->form) {
        init->form = destroy_form(init);
        init->form = nullptr;
    }
    if (init->pick) {
        init->pick = destroy_pick(init);
        init->pick = nullptr;
    }
    for (i = 0; i <= init->argc; i++) {
        if (init->argv[i]) {
            if (init->argv[i] != nullptr)
                free(init->argv[i]);
            init->argv[i] = nullptr;
        }
    }
    if (init->argv) {
        if (init->argv != nullptr)
            free(init->argv);
        init->argv = nullptr;
    }
    if (init != nullptr) {
        free(init);
        init = nullptr;
    }
    init_cnt--;
    return init;
}
References destroy_form(), destroy_menu(), destroy_pick(), destroy_view(), init, and init_cnt.
Referenced by main().
destroy_menu()
Menu * destroy_menu (Init * init)
Destroy Menu structure.
Parameters
init structure
Returns
nullptr
Definition at line 165 of file mem.c.
{
    if (!init->menu)
        return (nullptr);
    free(init->menu);
    init->menu = nullptr;
    init->menu_cnt--;
    return init->menu;
}
References init.
Referenced by destroy_init(), and menu_cmd_processor().
destroy_pick()
Pick * destroy_pick (Init * init)
Destroy Pick structure.
Parameters
init structure
Returns
nullptr
Definition at line 211 of file mem.c.
{
    if (!init->pick)
        return nullptr;
    for (pick->obj_idx = 0; pick->obj_idx < pick->obj_cnt; pick->obj_idx++)
        if (pick->object[pick->obj_idx] != nullptr)
            free(pick->object[pick->obj_idx]);
    free(pick->object);
    free(pick);
    init->pick = nullptr;
    init->pick_cnt--;
    return init->pick;
}
References init, and pick.
Referenced by destroy_init(), and init_pick().
destroy_view()
View * destroy_view (Init * init)
Destroy View structure.
Parameters
init structure
Returns
nullptr
Definition at line 326 of file mem.c.
{
    int i;
    view = init->view;
    for (i = 0; i <= view->argc; i++)
        free(view->argv[i]);
    free(view->argv);
    free(view);
    init->view = nullptr;
    view = nullptr;
    init->view_cnt--;
    return init->view;
}
References init, and view.
Referenced by destroy_init(), and mview().
init_form_files()
bool init_form_files (Init * init, int argc, char ** argv)
Initialize Form file specifications.
Parameters
init pointer to init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line ~/.minitrc, environment variables, or calling program interal to C-Menu
Note
Positional args: [pick desc], [in_file], [out_file], [help_file]
Definition at line 611 of file mem.c.
{
    char tmp_str[MAXLEN];
    form->f_mapp_spec =
        verify_spec_arg(form->mapp_spec, init->mapp_spec, init->mapp_msrc,
                        "~/menuapp/msrc", R_OK);
    form->f_in_spec = verify_spec_arg(form->in_spec, init->in_spec,
                                      init->mapp_data, "~/menuapp/data", R_OK);
    form->f_out_spec =
        verify_spec_arg(form->out_spec, init->out_spec, init->mapp_data,
                        "~/menuapp/data", W_OK | S_QUIET);
    if (init->provider_cmd[0] != '\0') {
        form->f_provider_cmd =
            verify_spec_arg(form->provider_cmd, init->provider_cmd,
                            "~/menuapp/bin", "$PATH", X_OK | S_QUIET);
    }
    if (init->cmd[0] != '\0') {
        form->f_cmd = verify_spec_arg(form->cmd, init->cmd, "~/menuapp/bin",
                                      "$PATH", X_OK | S_QUIET);
    }
    if (init->receiver_cmd[0] != '\0') {
        form->f_receiver_cmd =
            verify_spec_arg(form->receiver_cmd, init->receiver_cmd,
                            "~/menuapp/bin", "$PATH", X_OK | S_QUIET);
    }
    form->f_help_spec =
        verify_spec_arg(form->help_spec, init->help_spec, init->mapp_help,
                        "~/menuapp/help", R_OK);
    if (optind < argc && !form->f_mapp_spec) {
        form->f_mapp_spec =
            verify_spec_arg(form->mapp_spec, argv[optind], init->mapp_msrc,
                            "~/menuapp/msrc", R_OK);
        if (form->f_mapp_spec)
            optind++;
    }
    if (optind < argc && !form->f_in_spec) {
        form->f_in_spec =
            verify_spec_arg(form->in_spec, argv[optind], init->mapp_data,
                            "~/menuapp/data", R_OK);
        if (form->f_in_spec)
            optind++;
    }
    if (optind < argc && !form->f_out_spec) {
        form->f_out_spec =
            verify_spec_arg(form->out_spec, argv[optind], init->mapp_data,
                            "~/menuapp/data", W_OK | S_QUIET);
        if (form->f_out_spec)
            optind++;
    }
    if (optind < argc && !form->f_provider_cmd) {
        if (argv[optind][0] != '\0') {
            form->f_provider_cmd =
                verify_spec_arg(form->provider_cmd, argv[optind],
                                "~/menuapp/bin", nullptr, X_OK | S_QUIET);
            if (!form->f_provider_cmd) {
                base_name(tmp_str, argv[optind]);
                form->f_provider_cmd =
                    locate_file_in_path(form->provider_cmd, tmp_str);
            }
        }
        optind++;
    }
    if (optind < argc && !form->f_cmd) {
        if (argv[optind][0] != '\0') {
            form->f_cmd =
                verify_spec_arg(form->cmd, argv[optind], "~/menuapp/bin",
                                nullptr, X_OK | S_QUIET);
            if (!form->f_cmd) {
                base_name(tmp_str, argv[optind]);
                form->f_cmd = locate_file_in_path(form->cmd, tmp_str);
            }
        }
        optind++;
    }
    if (optind < argc && !form->f_receiver_cmd) {
        if (argv[optind][0] != '\0') {
            form->f_receiver_cmd =
                verify_spec_arg(form->receiver_cmd, argv[optind],
                                "~/menuapp/bin", nullptr, X_OK | S_QUIET);
            if (!form->f_receiver_cmd) {
                base_name(tmp_str, argv[optind]);
                form->f_receiver_cmd =
                    locate_file_in_path(form->receiver_cmd, tmp_str);
            }
        }
        optind++;
    }
    if (optind < argc && !form->f_help_spec) {
        form->f_help_spec =
            verify_spec_arg(form->help_spec, init->help_spec, init->mapp_help,
                            "~/menuapp/help", R_OK);
        if (form->f_help_spec)
            optind++;
    }
    form->f_stop_on_error = init->f_stop_on_error;
    form->f_erase_remainder = init->f_erase_remainder;
    if (form->title[0] == '\0' && init->title[0] != '\0') {
        strip_quotes(init->title);
        strnz__cpy(form->title, init->title, MAXLEN - 1);
    }
    return true;
}
References base_name(), form, init, locate_file_in_path(), MAXLEN, strip_quotes(), strnz__cpy(), tmp_str, and verify_spec_arg().
Referenced by new_form().
init_menu_files()
bool init_menu_files (Init * init, int argc, char ** argv)
Initialize Menu file specifications.
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
Note
Positional args: [menu desc], [help file]
Definition at line 461 of file mem.c.
{
    char tmp_str[MAXLEN];
    // menu->f_mapp_spec =
    //     verify_spec_arg(menu->mapp_spec, init->mapp_spec, init->mapp_msrc,
    //                     "~/menuapp/msrc", R_OK);
    // menu->f_help_spec =
    //     verify_spec_arg(menu->help_spec, init->help_spec, init->mapp_help,
    //                     "~/menuapp/help", R_OK);
    if (optind < argc && !init->f_mapp_spec) {
        menu->f_mapp_spec =
            verify_spec_arg(menu->mapp_spec, argv[optind], init->mapp_msrc,
                            "~/menuapp/msrc", R_OK);
        if (menu->f_mapp_spec)
            optind++;
    }
    if (optind < argc && !menu->f_help_spec) {
        menu->f_help_spec =
            verify_spec_arg(menu->help_spec, argv[optind], init->mapp_help,
                            "~/menuapp/help", R_OK);
        if (menu->f_help_spec)
            optind++;
    }
    if (!menu->f_mapp_spec) {
        menu->f_mapp_spec = verify_spec_arg(
            menu->mapp_spec, "~/menuapp/msrc/main.m", nullptr, nullptr, R_OK);
        if (!menu->f_mapp_spec) {
            strnz__cpy(tmp_str, "menu cannot read description file ",
                       MAXLEN - 1);
            strnz__cat(tmp_str, menu->mapp_spec, MAXLEN - 1);
            abend(-1, tmp_str);
        }
    }
    if (!menu->f_help_spec) {
        menu->f_help_spec =
            verify_spec_arg(menu->help_spec, "~/menuapp/help/main.help",
                            nullptr, nullptr, R_OK);
        if (!menu->f_help_spec) {
            strnz__cpy(tmp_str, "menu cannot read help file ", MAXLEN - 1);
            strnz__cat(tmp_str, menu->help_spec, MAXLEN - 1);
            abend(-1, tmp_str);
        }
    }
    menu->f_stop_on_error = init->f_stop_on_error;
    return true;
}
References abend(), init, MAXLEN, menu, strnz__cat(), strnz__cpy(), tmp_str, and verify_spec_arg().
Referenced by new_menu().
init_pick_files()
bool init_pick_files (Init * init, int argc, char ** argv)
Initialize Pick file specifications.
Initialize file specifications
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
Note
Positional args: [pick desc], [in_file], [out_file], [help_file]
Definition at line 515 of file mem.c.
{
    char tmp_str[MAXLEN];
    pick->f_in_spec = verify_spec_arg(pick->in_spec, init->in_spec,
                                      init->mapp_data, "~/menuapp/data", R_OK);
    pick->f_out_spec =
        verify_spec_arg(pick->out_spec, init->out_spec, init->mapp_data,
                        "~/menuapp/data", W_OK | S_QUIET);
    if (init->provider_cmd[0] != '\0') {
        pick->f_provider_cmd =
            verify_spec_arg(pick->provider_cmd, init->provider_cmd,
                            "~/menuapp/bin", "$PATH", X_OK | S_QUIET);
    }
    if (init->cmd[0] != '\0') {
        pick->f_cmd = verify_spec_arg(pick->cmd, init->cmd, "~/menuapp/bin",
                                      "$PATH", X_OK | S_QUIET);
    }
    if (init->receiver_cmd[0] != '\0') {
        pick->f_receiver_cmd =
            verify_spec_arg(pick->receiver_cmd, init->receiver_cmd,
                            "~/menuapp/bin", "$PATH", X_OK | S_QUIET);
    }
    if (init->title[0])
        strnz__cpy(pick->title, init->title, MAXLEN - 1);
    pick->f_help_spec =
        verify_spec_arg(pick->help_spec, init->help_spec, init->mapp_help,
                        "~/menuapp/help", R_OK);
    if (optind < argc && !pick->f_in_spec) {
        pick->f_in_spec =
            verify_spec_arg(pick->in_spec, argv[optind], init->mapp_data,
                            "~/menuapp/data", R_OK);
        if (pick->f_in_spec)
            optind++;
    }
    if (optind < argc && !pick->f_out_spec) {
        pick->f_out_spec =
            verify_spec_arg(pick->out_spec, argv[optind], init->mapp_data,
                            "~/menuapp/data", W_OK | S_QUIET);
        if (pick->f_out_spec)
            optind++;
    }
    if (optind < argc && !pick->f_provider_cmd) {
        if (argv[optind][0] != '\0') {
            pick->f_provider_cmd =
                verify_spec_arg(pick->provider_cmd, argv[optind],
                                "~/menuapp/bin", nullptr, X_OK | S_QUIET);
            if (!pick->f_provider_cmd) {
                base_name(tmp_str, argv[optind]);
                pick->f_provider_cmd =
                    locate_file_in_path(pick->provider_cmd, tmp_str);
            }
        }
        optind++;
    }
    if (optind < argc && !pick->f_cmd) {
        if (argv[optind][0] != '\0') {
            pick->f_cmd =
                verify_spec_arg(pick->cmd, argv[optind], "~/menuapp/bin",
                                nullptr, X_OK | S_QUIET);
            if (!pick->f_cmd) {
                base_name(tmp_str, argv[optind]);
                pick->f_cmd = locate_file_in_path(pick->cmd, tmp_str);
            }
        }
        optind++;
    }
    if (optind < argc && !pick->f_receiver_cmd) {
        if (argv[optind][0] != '\0') {
            pick->f_receiver_cmd =
                verify_spec_arg(pick->receiver_cmd, argv[optind],
                                "~/menuapp/bin", nullptr, X_OK | S_QUIET);
            if (!pick->f_receiver_cmd) {
                base_name(tmp_str, argv[optind]);
                pick->f_receiver_cmd =
                    locate_file_in_path(pick->receiver_cmd, tmp_str);
            }
        }
        optind++;
    }
    if (optind < argc && !pick->f_help_spec) {
        pick->f_help_spec =
            verify_spec_arg(pick->help_spec, argv[optind], init->mapp_help,
                            "~/menuapp/help", R_OK);
        if (pick->f_help_spec)
            optind++;
    }
    pick->select_max = init->select_max;
    pick->f_stop_on_error = init->f_stop_on_error;
    pick->f_multiple_cmd_args = init->f_multiple_cmd_args;
    return true;
}
References base_name(), init, locate_file_in_path(), MAXLEN, pick, strnz__cpy(), tmp_str, and verify_spec_arg().
Referenced by new_pick().
init_view_files()
bool init_view_files (Init * init)
Initialize Pick file specifications.
Initialize file specifications
Parameters
init structure
Note
Positional args: pick desc, in_file, out_file, help_file
Definition at line 716 of file mem.c.
{
    view = init->view;
    view->lines = init->lines;
    view->cols = init->cols;
    view->f_stop_on_error = init->f_stop_on_error;
    view->f_ignore_case = init->f_ignore_case;
    view->f_at_end_clear = init->f_at_end_clear;
    view->f_at_end_remove = init->f_at_end_remove;
    view->f_squeeze = init->f_squeeze;
    strnz__cpy(view->provider_cmd, init->provider_cmd, MAXLEN - 1);
    strnz__cpy(view->receiver_cmd, init->receiver_cmd, MAXLEN - 1);
    strnz__cpy(view->cmd_all, init->cmd_all, MAXLEN - 1);
    if (view->title[0] == '\0') {
        if (init->title[0] != '\0') {
            strnz__cpy(view->title, init->title, MAXLEN - 1);
        } else {
            if (view->provider_cmd[0] != '\0')
                strnz__cpy(view->title, view->provider_cmd, MAXLEN - 1);
            else {
                if (view->argv[0] != nullptr && view->argv[0][0] != '\0')
                    strnz__cpy(view->title, view->argv[0], MAXLEN - 1);
                else
                    strnz__cpy(view->title, "C-Menu View", MAXLEN - 1);
            }
        }
    }
    strip_quotes(view->title);
    if (view->tab_stop == 0)
        view->tab_stop = 4;
    return true;
}
References init, MAXLEN, strip_quotes(), strnz__cpy(), and view.
Referenced by new_view().
new_form()
Form * new_form (Init * init, int argc, char ** argv, int begy, int begx)
Create and initialize Form structure.
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
begy,begx - initial position of form window
Definition at line 233 of file mem.c.
{
    init->form = (Form *)calloc(1, sizeof(Form));
    if (!init->form) {
        abend(-1, "calloc form failed");
        return nullptr;
    }
    init->form_cnt++;
    form = init->form;
    if (!init_form_files(init, argc, argv)) {
        abend(-1, "init_form_files failed");
        return nullptr;
    }
    strnz__cpy(form->brackets, init->brackets, 3);
    strnz__cpy(form->fill_char, init->fill_char, MAXLEN - 1);
    form->begy = begy;
    form->begx = begx;
    return init->form;
}
References abend(), form, init, init_form_files(), MAXLEN, and strnz__cpy().
Referenced by init_form().
new_init()
Init * new_init (int argc, char ** argv)
Create and initialize Init structure.
Note
calloc initializes all fields to zero/nullptr
Parameters
argc,argv - arguments idiomatic directory usage:
init->mapp_msrc  description files
init->mapp_help  help files
init->mapp_data  in, out, data files
init->mapp_user  executable scripts
init->mapp_bin   binary executables
Note
Initialize file specifications in priority order:
1 - Default values
2 - Configuration file
3 - Environment variables
4 - Command line positional arguments
5 - Command line option arguments
Definition at line 57 of file mem.c.
{
    int i = 0;
    Init *init = calloc(1, sizeof(Init));
    if (init == nullptr) {
        abend(-1, "calloc init failed");
        return nullptr;
    }
    init->argv = calloc(MAXARGS + 1, sizeof(char *));
    if (init->argv == nullptr) {
        free(init);
        ssnprintf(em0, MAXLEN - 1, "%s, line: %d, errno: %d", __FILE__,
                  __LINE__ - 4, errno);
        ssnprintf(em1, MAXLEN - 1, "%s", strerror(errno));
        ssnprintf(em2, MAXLEN - 1, "view->argv = calloc(%d, %d) failed\n",
                  (MAXARGS + 1), sizeof(char *));
        display_error(em0, em1, em2, nullptr);
        abend(-1, "calloc init->argv failed");
        return nullptr;
    }
    init->argc = argc;
    for (i = 0; i < init->argc; i++) {
        init->argv[i] = strdup(argv[i]);
    }
    init->argv[i] = nullptr;
    init->sio = (SIO *)calloc(1, sizeof(SIO));
    if (!init->sio) {
        abend(-1, "calloc sio failed");
        return nullptr;
    }
    init_cnt++;
    return init;
}
References abend(), display_error(), em0, em1, em2, init, init_cnt, MAXLEN, and ssnprintf().
Referenced by main().
new_menu()
Menu * new_menu (Init * init, int argc, char ** argv, int begy, int begx)
Create and initialize Menu structure.
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
begy,begx - initial position of menu window
Definition at line 145 of file mem.c.
{
    init->menu = (Menu *)calloc(1, sizeof(Menu));
    if (!init->menu) {
        abend(-1, "calloc menu failed");
        return nullptr;
    }
    init->menu_cnt++;
    menu = init->menu;
    if (!init_menu_files(init, argc, argv)) {
        abend(-1, "init_menu_files failed");
        return nullptr;
    }
    menu->begy = begy;
    menu->begx = begx;
    return init->menu;
}
References abend(), init, init_menu_files(), and menu.
Referenced by main(), and menu_cmd_processor().
new_pick()
Pick * new_pick (Init * init, int argc, char ** argv, int begy, int begx)
Create and initialize Pick structure.
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
begy,begx - initial position of pick window
Definition at line 182 of file mem.c.
{
    init->pick = (Pick *)calloc(1, sizeof(Pick));
    if (!init->pick) {
        Perror("calloc pick failed");
        return nullptr;
    }
    init->pick_cnt++;
    pick = init->pick;
    if (!init_pick_files(init, argc, argv)) {
        abend(-1, "init_pick_files failed");
        return nullptr;
    }
    pick->object = calloc(OBJ_MAXCNT + 1, sizeof(char *));
    if (pick->object == nullptr) {
        ssnprintf(em0, MAXLEN - 1, "%s, line: %d", __FILE__, __LINE__ - 1);
        ssnprintf(em1, MAXLEN - 1,
                  "calloc pick->object = calloc(%d, %d) failed\n",
                  OBJ_MAXCNT + 1, sizeof(char *));
        display_error(em0, em1, nullptr, nullptr);
        abend(-1, "User terminated program");
    }
    pick->begy = begy;
    pick->begx = begx;
    return init->pick;
}
References abend(), display_error(), em0, em1, init, init_pick_files(), MAXLEN, Perror(), pick, and ssnprintf().
Referenced by init_pick().
new_view()
View * new_view (Init * init, int argc, char ** argv)
Create and initialize View structure.
Parameters
init structure
argc - number of arguments in argv
argv - Arguments may have been provided by command line, ~/.minitrc, environment variables, or calling program interal to C-Menu
Definition at line 283 of file mem.c.
{
    init->view_cnt++;
    init->view = (View *)calloc(1, sizeof(View));
    if (!init->view) {
        free(init->view);
        ssnprintf(em0, MAXLEN - 1, "%s, line: %d, errno: %d", __FILE__,
                  __LINE__ - 1, errno);
        ssnprintf(em1, MAXLEN - 1, "%s", strerror(errno));
        ssnprintf(em2, MAXLEN - 1, "init->view = calloc(%d, %d) failed\n",
                  (argc - optind + 1), sizeof(char *));
        display_error(em0, em1, em2, nullptr);
        abend(-1, "calloc init->view failed");
        return false;
    }
    view = init->view;
    view->argv = calloc((argc - optind + 1), sizeof(char *));
    if (view->argv == nullptr) {
        free(view->argv);
        ssnprintf(em0, MAXLEN - 1, "%s, line: %d, errno: %d", __FILE__,
                  __LINE__ - 1, errno);
        ssnprintf(em1, MAXLEN - 1, "%s", strerror(errno));
        ssnprintf(em2, MAXLEN - 1, "view->argv = calloc(%d, %d) failed\n",
                  (argc - optind + 1), sizeof(char *));
        display_error(em0, em1, em2, nullptr);
        abend(-1, "User terminated program");
        return false;
    }
    int s = optind;
    int d = 0;
    while (s < argc)
        view->argv[d++] = strdup(argv[s++]);
    view->argv[d] = nullptr;
    view->argc = d;
    if (!init_view_files(init)) {
        abend(-1, "init_view_files failed");
        return nullptr;
    }
    return view;
}
References abend(), display_error(), em0, em1, em2, init, init_view_files(), MAXLEN, ssnprintf(), and view.
Referenced by main(), and mview().
verify_spec_arg()
bool verify_spec_arg (char * spec, char * org_spec, char * dir, char * alt_dir, int mode)
Verify file specification argument.
Parameters
spec - menu->spec, form->spec, etc.
org_spec - init->._spec | argv[optind]
dir - init->._. directory
alt_dir - literal, "~/menuapp/data", etc.
mode - R_OK, W_OK, X_OK, WC_OK, S_QUIET
Note
mode is a bitwise OR of the following flags: S_QUIET - suppress error messages WC_OK - write create ok
Returns
bool - true if file verified
preserve quotes
preserve quotes
Definition at line 349 of file mem.c.
{
    bool f_dir = false;
    bool f_spec = false;
    bool f_quote = true;
    char *s1;
    char *s2;
    char s1_s[MAXLEN];
    char s2_s[MAXLEN];
    char file_name[MAXLEN];
    char try_spec[MAXLEN];
    char idio_spec[MAXLEN];
    if (!org_spec[0])
        return false;
    idio_spec[0] = '\0';
    strnz__cpy(try_spec, org_spec, MAXLEN - 1);
    f_quote = stripz_quotes(try_spec);
    s1 = strtok(try_spec, " \t\n");
    strnz__cpy(s1_s, s1, MAXLEN - 1);
    s2 = strtok(nullptr, "\n");
    strnz__cpy(s2_s, s2, MAXLEN - 1);
    strnz__cpy(file_name, s1, MAXLEN - 1);
    strnz__cpy(try_spec, file_name, MAXLEN - 1);
    canonicalize_file_spec(try_spec);
    if (try_spec[0]) {
        expand_tilde(try_spec, MAXLEN - 1);
        if (try_spec[0] == '/') {
            f_spec = verify_file(try_spec, mode);
            if (f_quote)
                strnz__cpy(spec, org_spec, MAXLEN - 1);
            else
                strnz__cpy(spec, try_spec, MAXLEN - 1);
            return f_spec;
        } else {
            if (!f_dir && dir[0]) {
                if (strcmp(dir, "$PATH") == 0) {
                    strnz__cpy(try_spec, file_name, MAXLEN - 1);
                    f_spec = locate_file_in_path(try_spec, file_name);
                } else {
                    strnz__cpy(try_spec, dir, MAXLEN - 1);
                    expand_tilde(try_spec, MAXLEN - 1);
                    f_dir = verify_dir(try_spec, mode);
                    if (f_dir) {
                        strnz__cat(try_spec, "/", MAXLEN - 1);
                        strnz__cat(try_spec, file_name, MAXLEN - 1);
                        strnz__cpy(idio_spec, try_spec, MAXLEN - 1);
                        if (mode & S_WCOK)
                            f_spec = true;
                        else
                            f_spec = verify_file(idio_spec, mode | S_QUIET);
                    }
                }
            }
            if (!f_spec && alt_dir && alt_dir[0] != '\0') {
                if (strcmp(alt_dir, "$PATH") == 0) {
                    strnz__cpy(try_spec, file_name, MAXLEN - 1);
                    f_spec = locate_file_in_path(try_spec, file_name);
                } else {
                    strnz__cpy(try_spec, alt_dir, MAXLEN - 1);
                    expand_tilde(try_spec, MAXLEN - 1);
                    f_dir = verify_dir(try_spec, mode);
                    if (f_dir) {
                        strnz__cat(try_spec, "/", MAXLEN - 1);
                        strnz__cat(try_spec, file_name, MAXLEN - 1);
                        if (mode & S_WCOK)
                            f_spec = true;
                        else
                            f_spec = verify_file(try_spec, mode | S_QUIET);
                    }
                }
            }
            if (!f_spec) {
                strnz__cpy(try_spec, ".", MAXLEN - 1);
                strnz__cat(try_spec, "/", MAXLEN - 1);
                strnz__cat(try_spec, file_name, MAXLEN - 1);
                f_spec = verify_file(try_spec, mode | S_QUIET);
            }
            if (!f_spec && mode == W_OK) {
                strnz__cpy(try_spec, idio_spec, MAXLEN - 1);
                FILE *fp = fopen(try_spec, "a");
                if (fp) {
                    fclose(fp);
                    f_spec = true;
                }
            }
            if (f_quote)
                strnz__cpy(spec, org_spec, MAXLEN - 1);
            else if (f_spec)
                strnz__cpy(spec, try_spec, MAXLEN - 1);
            if (try_spec[0] == '\0' && idio_spec[0] != '\0')
                strnz__cpy(spec, idio_spec, MAXLEN - 1);
            else
                strnz__cpy(spec, try_spec, MAXLEN - 1);
            if (s2_s[0] != '\0') {
                strnz__cat(spec, " ", MAXLEN - 1);
                strnz__cat(spec, s2_s, MAXLEN - 1);
            }
            return f_spec;
        }
    }
    return false;
}
References canonicalize_file_spec(), expand_tilde(), file_name, locate_file_in_path(), MAXLEN, stripz_quotes(), strnz__cat(), strnz__cpy(), verify_dir(), and verify_file().
Referenced by enter_file_spec(), init_form_files(), init_menu_files(), and init_pick_files().
Variable Documentation
form
Form* form
Definition at line 35 of file mem.c.
Referenced by form_accept_field(), form_calculate(), form_desc_error(), form_display_chyron(), form_display_field(), form_display_field_brackets(), form_display_field_n(), form_display_fields(), form_display_screen(), form_end_fields(), form_engine(), form_enter_fields(), form_exec_cmd(), form_fmt_field(), form_parse_desc(), form_read_data(), form_validate_field(), form_write(), form_yx_to_fidx(), init_form(), init_form_files(), mk_filler(), and new_form().
init_cnt
int init_cnt = 0
Definition at line 31 of file mem.c.
Referenced by destroy_init(), and new_init().
menu
Menu* menu
Definition at line 33 of file mem.c.
Referenced by form_engine(), init_menu_files(), main(), menu_cmd_processor(), menu_engine(), new_menu(), and parse_menu_description().
pick
Pick* pick
Definition at line 34 of file mem.c.
Referenced by destroy_pick(), display_page(), display_pick_help(), exec_objects(), init_pick(), init_pick_files(), new_pick(), open_pick_win(), output_objects(), pick_display_chyron(), pick_engine(), picker(), read_pick_input(), reverse_object(), save_object(), toggle_object(), and unreverse_object().
view
View* view
Definition at line 36 of file mem.c.
Referenced by build_prompt(), cat_file(), cmd_line_prompt(), destroy_view(), display_line(), enter_file_spec(), fmt_line(), get_cmd_arg(), get_cmd_char(), get_next_line(), get_pos_next_line(), get_pos_prev_line(), get_prev_line(), go_to_eof(), go_to_line(), go_to_mark(), go_to_percent(), go_to_position(), init_view_boxwin(), init_view_files(), init_view_full_screen(), lp(), main(), mview(), new_view(), next_page(), prev_page(), redisplay_page(), remove_file(), resize_page(), scroll_down_n_lines(), scroll_up_n_lines(), search(), view_cmd_processor(), view_file(), view_init_input(), and write_view_buffer().