C-Menu: parse_menu_desc.c File Reference
parse_menu_desc.c File Reference
Parse menu description file and create Menu.
#include <common.h>
#include <ctype.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
Functions
unsigned int parse_menu_description (Init *init)
Parse menu description file and create Menu.
unsigned int get_command_type (char *t)
Get command type from command string.
void free_menu_line (Line *line)
Free memory allocated for a menu line.
Detailed Description
Parse menu description file and create Menu.
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file parse_menu_desc.c.
Function Documentation
free_menu_line()
void free_menu_line (Line * line)
Free memory allocated for a menu line.
Parameters
line Pointer to Line structure to free
Definition at line 283 of file parse_menu_desc.c.
References Line::choice_letter, Line::choice_text, Line::command_str, Line::command_type, Line::letter_pos, and Line::raw_text.
get_command_type()
unsigned int get_command_type (char * t)
Get command type from command string.
Parameters
t Command string
Returns
Command type as an unsigned int
Definition at line 244 of file parse_menu_desc.c.
References CT_ABOUT, CT_CKEYS, CT_EXEC, CT_FORM, CT_HELP, CT_MENU, CT_PICK, CT_RETURN, CT_RETURNMAIN, CT_UNDEFINED, CT_VIEW, and CT_WRITE_CONFIG.
Referenced by parse_menu_description().
parse_menu_description()
unsigned int parse_menu_description (Init * init)
Parse menu description file and create Menu.
Parameters
init Pointer to Init structure containing menu information
Returns
0 on success, non-zero on failure
'#' Comment line, ignore
'!' Choice line, parse and add to menu
':' Text line, parse and add to menu
< in_buf -> Title
'?' Help line, ignore for now
' ' Empty line, ignore
Definition at line 24 of file parse_menu_desc.c.
References abend(), chrep(), CT_RETURN, display_error(), em0, em1, em2, FALSE, get_command_type(), init, MAXLEN, menu, MT_CHOICE, MT_TEXT, Perror(), ssnprintf(), strnz__cat(), strnz__cpy(), tmp_str, trim(), and TRUE.
Referenced by main(), menu_cmd_processor(), and menu_engine().