C-Menu: src/include/pick.h File Reference
pick.h File Reference
Pick data structures, enums, types, end external declarations.
#include <cm.h>
Data Structures
struct Pick
Pick data structure.
Macros
#define OBJ_MAXLEN 80
#define OBJ_MAXCNT 1024
Functions
void save_object (Pick *, char *)
Saves a string as an object in the pick structure.
void display_page (Pick *)
Displays current page of objects in pick window.
void reverse_object (Pick *)
Reverses the display of the currently selected object in pick window.
void toggle_object (Pick *)
Toggles the selection state of the currently selected object in pick window.
int output_objects (Pick *)
Outputs selected objects to specified output file.
int mpick (int, char **, int, int, int, int, char *, int)
Variables
Pick * pick
Detailed Description
Pick data structures, enums, types, end external declarations.
Author
Bill Waller Copyright (c) 2025 MIT License billxwaller@gmail.com
Date
2026-02-09
Definition in file pick.h.
Macro Definition Documentation
OBJ_MAXCNT
#define OBJ_MAXCNT 1024
Definition at line 17 of file pick.h.
Referenced by new_pick(), and save_object().
OBJ_MAXLEN
#define OBJ_MAXLEN 80
Pick structures, enums, and data types
Definition at line 16 of file pick.h.
Referenced by save_object().
Function Documentation
display_page()
void display_page (Pick * pick) extern
Displays current page of objects in pick window.
Parameters
pick Pointer to Pick structure containing objects and display information
Note
Clears the pick window and displays the current page of objects based on the current table page, line, and column. Marks selected objects with an asterisk. Updates the chyron with page information at the bottom of the pick window.
Definition at line 503 of file pick_engine.c.
{
    int y, col, pidx;
    for (y = 0; y < pick->pg_lines; y++) {
        wmove(pick->win, y, 0);
        wclrtoeol(pick->win);
    }
    pidx = pick->tbl_page * pick->pg_lines * pick->tbl_cols;
    for (col = 0; col < pick->tbl_cols; col++) {
        pick->x = col * (pick->tbl_col_width + 1) + 1;
        for (y = 0; y < pick->pg_lines; y++, pidx++) {
            if (pidx < pick->obj_cnt) {
                if (pick->f_selected[pidx])
                    mvwaddstr(pick->win, y, pick->x - 1, "*");
                mvwaddstr_fill(pick->win, y, pick->x, pick->object[pidx],
                               pick->tbl_col_width);
            }
        }
    }
    pick_display_chyron(pick);
}
References mvwaddstr_fill(), pick, and pick_display_chyron().
Referenced by pick_engine(), and picker().
mpick()
int mpick (int , char ** , int , int , int , int , char * , int) extern
output_objects()
int output_objects (Pick * pick) extern
Outputs selected objects to specified output file.
Parameters
pick Pointer to Pick structure containing selected objects and output file information
Returns
0 on success, 1 on failure
Note
If output file cannot be opened, an error message is printed and the function returns 1. Otherwise, selected objects are written to the output file, one per line, and the file is closed before returning 0.
Definition at line 612 of file pick_engine.c.
{
    char tmp_str[MAXLEN];
    int m;
    if ((pick->out_fp = fopen(pick->out_spec, "w")) == nullptr) {
        m = MAXLEN - 30;
        strnz__cpy(tmp_str, "Can't open pick output file: ", m);
        m -= strlen(pick->in_spec);
        strnz__cat(tmp_str, pick->out_spec, m);
    }
    for (pick->obj_idx = 0; pick->obj_idx < pick->obj_cnt; pick->obj_idx++) {
        if (pick->f_selected[pick->obj_idx])
            fprintf(stdout, "%s\n", pick->object[pick->obj_idx]);
    }
    fflush(stdout);
    if (pick->out_fp != nullptr)
        fclose(pick->out_fp);
    return (0);
}
References MAXLEN, pick, strnz__cat(), strnz__cpy(), and tmp_str.
Referenced by pick_engine().
reverse_object()
void reverse_object (Pick * pick) extern
Reverses the display of the currently selected object in pick window.
Parameters
pick Pointer to Pick structure containing object and display information
Note
Calculates the x coordinate for the currently selected object based on the current table column and column width. Moves the cursor to the object's position in the pick window, turns on reverse video attribute, and displays the object's text. Turns off reverse video attribute and refreshes the pick window to show the updated display. Moves the cursor back to the position before the object text for potential further interactions.
Definition at line 550 of file pick_engine.c.
{
    pick->x = pick->tbl_col * (pick->tbl_col_width + 1) + 1;
    pick->tbl_line = (pick->obj_idx / pick->tbl_cols) % pick->pg_lines;
    pick->y = pick->tbl_line;
    wmove(pick->win, pick->y, pick->x);
    wattron(pick->win, WA_REVERSE);
    mvwaddstr_fill(pick->win, pick->y, pick->x, pick->object[pick->obj_idx],
                   pick->tbl_col_width);
    wattroff(pick->win, WA_REVERSE);
    wrefresh(pick->win);
    wmove(pick->win, pick->y, pick->x - 1);
}
References mvwaddstr_fill(), and pick.
Referenced by pick_engine(), and picker().
save_object()
void save_object (Pick * pick, char * s) extern
Saves a string as an object in the pick structure.
Parameters
pick Pointer to Pick structure
s String to save as an object
Note
If the current object index is less than the maximum allowed, saves the string as an object in the pick structure. Updates the column width if necessary and marks the object as not selected. Increments the object index for the next object to be saved.
Definition at line 287 of file pick_engine.c.
{
    int l;
    if (pick->obj_idx < OBJ_MAXCNT - 1) {
        l = strlen(s);
        if (l > OBJ_MAXLEN - 1)
            s[OBJ_MAXLEN - 1] = '\0';
        if (l > pick->tbl_col_width)
            pick->tbl_col_width = l;
        if (l < 1)
            l = 1;
        pick->object[pick->obj_idx] = (char *)calloc(l + 1, sizeof(char));
        strnz__cpy(pick->object[pick->obj_idx], s, l);
        pick->f_selected[pick->obj_idx] = FALSE;
        pick->obj_idx++;
    }
}
References FALSE, OBJ_MAXCNT, OBJ_MAXLEN, pick, and strnz__cpy().
Referenced by read_pick_input().
toggle_object()
void toggle_object (Pick * pick) extern
Toggles the selection state of the currently selected object in pick window.
Parameters
pick Pointer to Pick structure containing object and selection information
Note
Calculates the x coordinate for the currently selected object based on the current table column and column width. If the object is currently selected, it is deselected by updating the selection count, marking it as not selected, and displaying a space before the object text. If the object is not currently selected, it is selected by updating the selection count, marking it as selected, and displaying an asterisk before the object text. Refreshes the pick window to show the updated display. Moves the cursor back to the position before the object text for potential further interactions.
Definition at line 592 of file pick_engine.c.
{
    pick->x = pick->tbl_col * (pick->tbl_col_width + 1) + 1;
    if (pick->f_selected[pick->obj_idx]) {
        pick->select_cnt--;
        pick->f_selected[pick->obj_idx] = FALSE;
        mvwaddstr(pick->win, pick->y, pick->x - 1, " ");
    } else {
        pick->select_cnt++;
        pick->f_selected[pick->obj_idx] = true;
        mvwaddstr(pick->win, pick->y, pick->x - 1, "*");
    }
}
References FALSE, and pick.
Referenced by picker().
Variable Documentation
pick
Pick* pick extern
pointer to Pick data structure
Definition at line 34 of file mem.c.
Referenced by destroy_pick(), display_page(), display_pick_help(), exec_objects(), init_pick(), init_pick_files(), new_pick(), open_pick_win(), output_objects(), pick_display_chyron(), pick_engine(), picker(), read_pick_input(), reverse_object(), save_object(), toggle_object(), and unreverse_object().