C-Menu: pick_engine.c File Reference
pick_engine.c File Reference
pick from a list of choices
#include <common.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <termios.h>
#include <unistd.h>
Functions
int pick_engine (Init *init)
Initializes pick interface, calculates window size and position, and enters picker loop.
void save_object (Pick *pick, char *s)
Saves a string as an object in the pick structure.
int picker (Init *init)
Main loop to handle user input and interactions for pick interface.
void display_page (Pick *pick)
Displays current page of objects in pick window.
void reverse_object (Pick *pick)
Reverses the display of the currently selected object in pick window.
void unreverse_object (Pick *pick)
Unreverses the display of the currently selected object in pick window.
void toggle_object (Pick *pick)
Toggles the selection state of the currently selected object in pick window.
int output_objects (Pick *pick)
Outputs selected objects to specified output file.
int exec_objects (Init *init)
Executes specified command with selected objects as arguments.
int open_pick_win (Init *init)
Initializes the pick window based on the parameters specified in the Pick structure.
void display_pick_help (Init *init)
Displays the help screen for the pick interface using mview.
void pick_display_chyron (Pick *pick)
Displays chyron with page information at bottom of pick window.
int read_pick_input (Init *init)
Reads pick input from file pointer and saves objects into pick structure.
int init_pick (Init *init, int argc, char **argv, int begy, int begx)
Initializes pick structure and opens pick input file or pipe.
Variables
int tbl_col
int tbl_line
int tbl_page
int tbl_cols
int pg_lines
int tbl_pages
int obj_idx
int calculated_idx
int pipe_fd [2]
char const pagers_editors [12][10]
Detailed Description
pick from a list of choices
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file pick_engine.c.
Function Documentation
display_page()
void display_page (Pick * pick)
Displays current page of objects in pick window.
Parameters
pick Pointer to Pick structure containing objects and display information
Note
Clears the pick window and displays the current page of objects based on the current table page, line, and column. Marks selected objects with an asterisk. Updates the chyron with page information at the bottom of the pick window.
Definition at line 503 of file pick_engine.c.
References mvwaddstr_fill(), pick, and pick_display_chyron().
Referenced by pick_engine(), and picker().
display_pick_help()
void display_pick_help (Init * init)
Displays the help screen for the pick interface using mview.
Parameters
init Pointer to Init structure containing pick information
Note
Initializes the help_spec field in the Pick structure with the path to the pick help file. Then, constructs the argument list for executing mview with the help file as an argument. Finally, calls mview function to display the help screen within the pick interface.
Definition at line 845 of file pick_engine.c.
References eargc, eargv, init, MAXLEN, mview(), parse_opt_args(), pick, strnz__cpy(), and zero_opt_args().
Referenced by picker().
exec_objects()
int exec_objects (Init * init)
Executes specified command with selected objects as arguments.
Parameters
init Pointer to Init structure
Returns
0 on success, 1 on failure
Note
Parses command string and appends selected objects as arguments to the command. If command contains "%%", it is replaced with a space- separated list of selected objects. Executes the command using execvp in a child process and waits for it to finish. If the command is a pager or editor, it is executed within the pick interface using mview instead of execvp.
If f_append_args is true, the argument containing %% is replaced with the concatenated selected objects. If f_append_args is false, selected objects are added as separate arguments and the original command arguments remain unchanged.
margv should be null-terminated to indicate the end of arguments for execvp
Memory allocated for arguments is freed after execution to prevent memory leaks.
If execvp fails, an error message is printed and the child process exits with failure status
The parent process waits for the child process to finish before proceeding and restores terminal settings
If the command is a pager or editor, it is executed within the pick interface using mview instead of execvp
The base name of the command is extracted to check if it is a pager or editor
If the command is a pager or editor, the pick interface is used to display the command output instead of executing it in a separate terminal This allows the user to view the command output without leaving the pick interface and provides a more seamless user experience.
If the command is not a pager or editor, it is executed in a separate terminal and the pick interface is restored after execution
If the command to be executed is view, an external command is not needed, instead the mview function can be used to display the output within the pick interface
initialize mview arguments and execute mview to display command output within pick interface
fork failed, free margv and return error
Child process to execute command
If execvp returns, it means execution failed, so free margv and print error message before exiting
Definition at line 663 of file pick_engine.c.
References base_name(), init, MAXARGS, MAXLEN, mview(), parse_opt_args(), Perror(), pick, rep_substring(), restore_curses_tioctl(), restore_wins(), sig_prog_mode(), str_to_args(), strnz__cat(), strnz__cpy(), tmp_str, and zero_opt_args().
Referenced by pick_engine().
init_pick()
int init_pick (Init * init, int argc, char ** argv, int begy, int begx)
Initializes pick structure and opens pick input file or pipe.
Parameters
init Pointer to Init structure
argc Argument count
argv Argument vector
begy Beginning y coordinate for pick window
begx Beginning x coordinate for pick window
Note
If provider_cmd is specified, it takes precedence over in_spec and input file arguments
provider_cmd is executed and its output is read as pick input
If provider_cmd is not specified, in_spec is used to read pick input from a file or stdin
If provider_cmd is specified, it is executed and its output is read as pick input
Spawn Child to execute provider_cmd Close read end of pipe as Child only needs to write to pipe
Connect CHILD STDOUT to write end of pipe
STDOUT attached to write end of pipe, so close pipe fd
Return to Parent Close write end of pipe as Parent only needs to read from pipe
Open a file pointer on read end of pipe
No provider_cmd specified, so read pick input from file or stdin
Wait for provider_cmd child process to finish before proceeding
Enter pick_engine
Definition at line 54 of file pick_engine.c.
References abend(), begx, begy, destroy_pick(), init, MAXARGS, MAXLEN, new_pick(), P_READ, P_WRITE, Perror(), pick, pick_engine(), pipe_fd, read_pick_input(), restore_curses_tioctl(), sig_prog_mode(), sio, str_to_args(), strnz__cat(), strnz__cpy(), tmp_str, and win_del().
Referenced by main(), and menu_cmd_processor().
open_pick_win()
int open_pick_win (Init * init)
Initializes the pick window based on the parameters specified in the Pick structure.
Parameters
init Pointer to Init structure containing pick information
Returns
0 on success, 1 on failure
Note
Creates a new window for the pick interface using win_new function with the specified parameters from the Pick structure. If window creation fails, an error message is printed and the function returns 1. Otherwise, initializes the window and box pointers in the Pick structure, sets scrollok and keypad options for the window, and returns 0 on success.
Definition at line 821 of file pick_engine.c.
References FALSE, init, MAXLEN, Perror(), pick, ssnprintf(), tmp_str, win_box, win_new(), win_ptr, and win_win.
Referenced by pick_engine().
output_objects()
int output_objects (Pick * pick)
Outputs selected objects to specified output file.
Parameters
pick Pointer to Pick structure containing selected objects and output file information
Returns
0 on success, 1 on failure
Note
If output file cannot be opened, an error message is printed and the function returns 1. Otherwise, selected objects are written to the output file, one per line, and the file is closed before returning 0.
Definition at line 612 of file pick_engine.c.
References MAXLEN, pick, strnz__cat(), strnz__cpy(), and tmp_str.
Referenced by pick_engine().
pick_display_chyron()
void pick_display_chyron (Pick * pick)
Displays chyron with page information at bottom of pick window.
Parameters
pick Pointer to Pick structure containing chyron information
Note
Constructs a string for the chyron that includes the current page number and total pages. Displays the chyron at the bottom of the pick window with reverse video attribute. Clears any remaining space on the line after the chyron text.
Definition at line 529 of file pick_engine.c.
References MAXLEN, pick, ssnprintf(), and tmp_str.
Referenced by display_page().
pick_engine()
int pick_engine (Init * init)
Initializes pick interface, calculates window size and position, and enters picker loop.
Parameters
init Pointer to Init structure containing pick information
Returns
Count of selected objects on success, -1 if user cancels
Note
Initializes key command strings for chyron display and calculates pick window size and position based on terminal size and pick parameters.
Opens pick window and displays first page of objects. Enters picker loop to handle user input and interactions. If user cancels selection, returns -1.
If user accepts selection, returns count of selected objects.
Initialize window and data structures
Initialize key command strings for chyron display
Calculate pick window size and position based on terminal size and pick parameters
Enter picker loop to handle user input and interactions
Definition at line 199 of file pick_engine.c.
References compile_chyron(), display_page(), exec_objects(), init, new_chyron(), open_pick_win(), output_objects(), pick, picker(), reverse_object(), set_chyron_key(), and strnz().
Referenced by init_pick().
picker()
int picker (Init * init)
Main loop to handle user input and interactions for pick interface.
Parameters
init Pointer to Init structure
Returns
Number of selected objects or -1 if user cancels
Note
Handles user input for navigating and selecting objects in the pick interface.
Supports various key commands for navigation, selection, and accepting/canceling the selection.
Updates the display accordingly based on user interactions.
If the user cancels the selection, returns -1.
If the user accepts the selection, returns the count of selected objects.
'q', or KEY_F(9) cancel selection and exit picker
KEY_F(1) or 'H' Displays help screen for pick interface
't' or Space Toggles selection of current object
Enter or KEY_F(10) Accepts current selection and exits picker, returning count of selected objects
KEY_END Moves selection to last object in list
'l' or KEY_RIGHT Moves selection to next object in list
pick->obj_idx += pick->tbl_lines -> next column
'h' or KEY_LEFT or Backspace Moves selection to previous object in list
'j' or KEY_DOWN Moves selection to next object in list, 'k' or KEY_UP Moves selection to previous object in list
'k' or KEY_UP Moves selection to previous object in list
KEY_NPAGE or 'Ctrl+f' Moves selection to next page of objects,
KEY_PPAGE or 'Ctrl+b' Moves selection to previous page of objects
KEY_HOME Moves selection to first object in list
KEY_LL (lower left of numeric pad) Moves selection to last object in list
KEY_MOUSE Handles mouse events for selection and chyron key activation
Definition at line 316 of file pick_engine.c.
References click_x, click_y, cmd_key, display_page(), display_pick_help(), init, mvwaddstr_fill(), pick, reverse_object(), toggle_object(), tty_fd, unreverse_object(), and xwgetch().
Referenced by pick_engine().
read_pick_input()
int read_pick_input (Init * init)
Reads pick input from file pointer and saves objects into pick structure.
Parameters
init Pointer to Init structure containing pick information
Returns
0 on success, -1 if no objects were read
Note
Reads lines from pick->in_fp and saves them as objects in the pick structure using save_object function. If no objects are read, returns -1. Otherwise, sets obj_cnt to the number of objects read and resets obj_idx to 0 before returning 0.
Definition at line 165 of file pick_engine.c.
References init, pick, and save_object().
Referenced by init_pick().
reverse_object()
void reverse_object (Pick * pick)
Reverses the display of the currently selected object in pick window.
Parameters
pick Pointer to Pick structure containing object and display information
Note
Calculates the x coordinate for the currently selected object based on the current table column and column width. Moves the cursor to the object's position in the pick window, turns on reverse video attribute, and displays the object's text. Turns off reverse video attribute and refreshes the pick window to show the updated display. Moves the cursor back to the position before the object text for potential further interactions.
Definition at line 550 of file pick_engine.c.
References mvwaddstr_fill(), and pick.
Referenced by pick_engine(), and picker().
save_object()
void save_object (Pick * pick, char * s)
Saves a string as an object in the pick structure.
Parameters
pick Pointer to Pick structure
s String to save as an object
Note
If the current object index is less than the maximum allowed, saves the string as an object in the pick structure. Updates the column width if necessary and marks the object as not selected. Increments the object index for the next object to be saved.
Definition at line 287 of file pick_engine.c.
References FALSE, OBJ_MAXCNT, OBJ_MAXLEN, pick, and strnz__cpy().
Referenced by read_pick_input().
toggle_object()
void toggle_object (Pick * pick)
Toggles the selection state of the currently selected object in pick window.
Parameters
pick Pointer to Pick structure containing object and selection information
Note
Calculates the x coordinate for the currently selected object based on the current table column and column width. If the object is currently selected, it is deselected by updating the selection count, marking it as not selected, and displaying a space before the object text. If the object is not currently selected, it is selected by updating the selection count, marking it as selected, and displaying an asterisk before the object text. Refreshes the pick window to show the updated display. Moves the cursor back to the position before the object text for potential further interactions.
Definition at line 592 of file pick_engine.c.
References FALSE, and pick.
Referenced by picker().
unreverse_object()
void unreverse_object (Pick * pick)
Unreverses the display of the currently selected object in pick window.
Parameters
pick Pointer to Pick structure containing object and display information
Note
Calculates the x coordinate for the currently selected object based on the current table column and column width. Moves the cursor to the object's position in the pick window and displays the object's text without reverse video attribute. Refreshes the pick window to show the updated display. Moves the cursor back to the position before the object text for potential further interactions.
Definition at line 572 of file pick_engine.c.
References mvwaddstr_fill(), and pick.
Referenced by picker().
Variable Documentation
calculated_idx
int calculated_idx
Definition at line 20 of file pick_engine.c.
obj_idx
int obj_idx
Definition at line 20 of file pick_engine.c.
pagers_editors
char const pagers_editors[12][10]
Initial value:
= {"view", "mview", "less", "more",
           "vi",   "vim",   "nano", "nvim",
           "pico", "emacs", "edit", ""}
Definition at line 37 of file pick_engine.c.
pg_lines
int pg_lines
Definition at line 19 of file pick_engine.c.
pipe_fd
int pipe_fd[2]
Definition at line 35 of file pick_engine.c.
Referenced by form_calculate(), init_pick(), and view_init_input().
tbl_col
int tbl_col
Definition at line 19 of file pick_engine.c.
tbl_cols
int tbl_cols
Definition at line 19 of file pick_engine.c.
tbl_line
int tbl_line
Definition at line 19 of file pick_engine.c.
tbl_page
int tbl_page
Definition at line 19 of file pick_engine.c.
tbl_pages
int tbl_pages
Definition at line 19 of file pick_engine.c.