C-Menu: src/test/color.c File Reference
color.c File Reference
Test program for xterm 256-color to RGB conversion and vice versa.
#include <stdio.h>
Data Structures
struct RGB
Represents an RGB color with 8-bit components.
Functions
RGB xterm256_to_rgb (int code)
Converts an xterm 256-color code to its corresponding RGB color.
int rgb_to_xterm256 (unsigned char r, unsigned char g, unsigned char b)
Converts an RGB color to the nearest xterm 256-color code.
int main (int argc, char *argv[])
Detailed Description
Test program for xterm 256-color to RGB conversion and vice versa.
This program defines two functions: xterm256_to_rgb to convert an xterm 256-color code to its corresponding RGB color, and rgb_to_xterm256 to convert an RGB color to the nearest xterm 256-color code. The main function tests these conversions by iterating through all 256 xterm color codes, converting them to RGB, and then converting back to xterm codes, printing the results.
Author
Bill Waller
Date
2025-12
Definition in file color.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 92 of file color.c.
{
    RGB rgb;
    RGB rgb2;
    int i, idx;
    for (i = 0; i < 256; i++) {
        rgb = xterm256_to_rgb(i);
        idx = rgb_to_xterm256(rgb.r, rgb.g, rgb.b);
        rgb2 = xterm256_to_rgb(idx);
        printf("idx %-3d (%3d, %3d, %3d) #%02x%02x%02x %-3d (%3d, %3d, %3d) "
               "#%02x%02x%02x\n",
               i, rgb.r, rgb.g, rgb.b, rgb.r, rgb.g, rgb.b, idx, rgb2.r, rgb2.g,
               rgb2.b, rgb2.r, rgb2.g, rgb2.b);
    }
    return 0;
}
References RGB::b, RGB::g, RGB::r, rgb_to_xterm256(), and xterm256_to_rgb().
rgb_to_xterm256()
int rgb_to_xterm256 (unsigned char r, unsigned char g, unsigned char b)
Converts an RGB color to the nearest xterm 256-color code.
Parameters
r The red component (0-255).
g The green component (0-255).
b The blue component (0-255).
Returns
The nearest xterm 256-color code (0-255).
xterm Color cube
Definition at line 77 of file color.c.
{
    if (r == g && g == b) {
        if (r < 8)
            return 16;
        if (r > 248)
            return 231;
        return ((r - 8) / 10) + 232;
    } else {
        int r_index = (r < 45) ? 0 : (r - 60) / 40 + 1;
        int g_index = (g < 45) ? 0 : (g - 60) / 40 + 1;
        int b_index = (b < 45) ? 0 : (b - 60) / 40 + 1;
        return 16 + (36 * r_index) + (6 * g_index) + b_index;
    }
}
Referenced by main().
xterm256_to_rgb()
RGB xterm256_to_rgb (int code)
Converts an xterm 256-color code to its corresponding RGB color.
Parameters
code The xterm 256-color code (0-255).
Returns
An RGB struct representing the corresponding color. 16 color standard palette 216 color xterm cube 24 color grayscale
16 color standard palette
216 (6x6x6) color xterm cube
24 color grayscale
Definition at line 31 of file color.c.
{
    RGB color;
    if (code < 16) {
        static const RGB standard_colors[16] = {
            {0, 0, 0},       {128, 0, 0},   {0, 128, 0},   {128, 128, 0},
            {0, 0, 128},     {128, 0, 128}, {0, 128, 128}, {192, 192, 192},
            {128, 128, 128}, {255, 0, 0},   {0, 255, 0},   {255, 255, 0},
            {0, 0, 255},     {255, 0, 255}, {0, 255, 255}, {255, 255, 255}};
        color = standard_colors[code];
    } else if (code >= 16 && code <= 231) {
        int index = code - 16;
        int r = (index / 36) % 6;
        int g = (index / 6) % 6;
        int b = index % 6;
        if (r > 0)
            color.r = r * 40 + 55;
        else
            color.r = 0;
        if (g > 0)
            color.g = g * 40 + 55;
        else
            color.g = 0;
        if (b > 0)
            color.b = b * 40 + 55;
        else
            color.b = 0;
    } else if (code >= 232 && code <= 255) {
        int gray = (code - 232) * 10 + 8;
        color.r = gray;
        color.g = gray;
        color.b = gray;
    } else {
        // Invalid code
        color.r = color.g = color.b = 0;
    }
    return color;
}
References RGB::b, RGB::g, and RGB::r.
Referenced by main().