C-Menu: exec.c File Reference
exec.c File Reference
Functions to execute external commands.
#include <cm.h>
#include <errno.h>
#include <fcntl.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <termios.h>
#include <unistd.h>
Functions
int full_screen_fork_exec (char **argv)
Execute a command in full screen mode.
int full_screen_shell (char *shellCmdPtr)
Execute a shell command in full screen mode.
int shell (char *shellCmdPtr)
Execute a shell command.
int fork_exec (char **argv)
Fork and exec a command.
void abend (int ec, char *s)
Abnormal program termination.
void user_end ()
Program terminated by user.
int nf_error (int ec, char *s)
Display error message and wait for key press.
Variables
int eargc
char * eargv [MAXARGS]
char earg_str [MAXLEN]
Detailed Description
Functions to execute external commands.
Author
Bill Waller Copyright (c) 2025 MIT License billx.nosp@m.wall.nosp@m.er@gm.nosp@m.ail..nosp@m.com
Date
2026-02-09
Definition in file exec.c.
Function Documentation
abend()
void abend (int ec, char * s)
Abnormal program termination.
Parameters
ec Exit code
s Error message
Definition at line 1066 of file dwin.c.
{
    destroy_curses();
    restore_shell_tioctl();
    sig_dfl_mode();
    fprintf(stderr, "\n\nABEND: %s (code: %d)\n", s, ec);
    exit(EXIT_FAILURE);
}
References destroy_curses(), restore_shell_tioctl(), and sig_dfl_mode().
Referenced by display_error(), form_parse_desc(), init_menu_files(), init_pick(), init_view_full_screen(), main(), mapp_initialization(), menu_cmd_processor(), new_chyron(), new_form(), new_init(), new_menu(), new_pick(), new_view(), open_curses(), parse_menu_description(), Perror(), sig_prog_mode(), and view_init_input().
fork_exec()
int fork_exec (char ** argv)
Fork and exec a command.
Parameters
argv - array of arguments for the command to execute
Returns
the return code from the executed command, or -1 on error
Note
Captures and restores terminal settings around the fork and exec.
Sets signal handlers to default in the child process.
Waits for the child process to complete in the parent process.
Handles errors from fork and execvp, and reports child exit status.
Restores curses mode and keypad settings after execution.
Restores window states after execution.
Uses a temporary string buffer tmp_str for error messages.
Uses Perror for error reporting.
Uses sig_dfl_mode and sig_prog_mode for signal handling.
Uses capture_curses_tioctl and restore_curses_tioctl for terminal settings.
Uses restore_shell_tioctl for shell terminal settings.
Uses waitpid to wait for the child process.
Uses WIFEXITED, WEXITSTATUS, WIFSIGNALED, and WTERMSIG to interpret child status.
Uses keypad to manage keypad mode in curses.
Uses restore_wins to restore window states.
Uses errno for error codes.
Uses pid_t for process IDs.
Uses standard file descriptors STDIN_FILENO, STDOUT_FILENO, STDERR_FILENO.
Uses execvp for executing the command.
Uses fork for creating a new process.
Uses ssnprintf for formatting error messages.
Uses switch-case for handling fork results.
Uses default shell if SHELL environment variable is not set.
Definition at line 124 of file exec.c.
{
    char tmp_str[MAXLEN];
    pid_t pid;
    int status;
    int rc;
    if (argv[0] == 0) {
        Perror("fork_exec: missing argument for execvp");
        return (-1);
    }
    capture_curses_tioctl();
    sig_dfl_mode();
    restore_shell_tioctl();
    tmp_str[0] = '\0';
    pid = fork();
    switch (pid) {
    case -1: // parent fork failed
        restore_curses_tioctl();
        sig_prog_mode();
        keypad(stdscr, true);
        ssnprintf(tmp_str, sizeof(tmp_str), "fork failed: %s, errno: %d",
                  argv[0], errno);
        Perror(tmp_str);
        return (-1);
    case 0: // child
        restore_shell_tioctl();
        execvp(argv[0], argv);
        restore_curses_tioctl();
        sig_prog_mode();
        keypad(stdscr, true);
        ssnprintf(tmp_str, sizeof(tmp_str), "execvp failed: %s, errno: %d",
                  argv[0], errno);
        Perror(tmp_str);
        exit(-1);
    default: // parent
        rc = 0;
        restore_curses_tioctl();
        sig_prog_mode();
        waitpid(pid, &status, 0);
        if (WIFEXITED(status)) {
            rc = WEXITSTATUS(status);
            if (rc != 0) {
                keypad(stdscr, true);
                ssnprintf(tmp_str, sizeof(tmp_str),
                          "Child %s exited  with status %d", argv[0], rc);
            }
        } else {
            if (WIFSIGNALED(status)) {
                rc = WTERMSIG(status);
                keypad(stdscr, true);
                ssnprintf(tmp_str, sizeof(tmp_str),
                          "Child %s terminated by signal %d", argv[0], rc);
            } else {
                keypad(stdscr, true);
                ssnprintf(tmp_str, sizeof(tmp_str),
                          "Child %s terminated abnormally", argv[0]);
            }
        }
        break;
    }
    restore_curses_tioctl();
    sig_prog_mode();
    keypad(stdscr, true);
    restore_wins();
    if (tmp_str[0] != '\0') {
        Perror(tmp_str);
    }
    return (rc);
}
References capture_curses_tioctl(), Perror(), restore_curses_tioctl(), restore_shell_tioctl(), restore_wins(), sig_dfl_mode(), sig_prog_mode(), and ssnprintf().
Referenced by full_screen_fork_exec(), and shell().
full_screen_fork_exec()
int full_screen_fork_exec (char ** argv)
Execute a command in full screen mode.
Parameters
argv - array of arguments for the command to execute
Returns
the return code from the executed command
Note
Clear the screen,
move the cursor to the bottom, and refresh the screen before executing the command.
After the command completes, clear the screen, move the cursor to the top, refresh the screen, and restore the windows.
Definition at line 40 of file exec.c.
{
    int rc;
    fflush(stderr);
    wclear(stdscr);
    wmove(stdscr, LINES - 1, 0);
    wrefresh(stdscr);
    rc = fork_exec(argv);
    wclear(stdscr);
    wmove(stdscr, 0, 0);
    wrefresh(stdscr);
    restore_wins();
    return (rc);
}
References fork_exec(), and restore_wins().
Referenced by menu_cmd_processor().
full_screen_shell()
int full_screen_shell (char * shellCmdPtr)
Execute a shell command in full screen mode.
Parameters
shellCmdPtr - pointer to the shell command string
Returns
the return code from the executed shell command
Note
Clear the screen, move the cursor to the top, and refresh the screen before executing the shell command.
After the command completes, restore the windows.
Definition at line 61 of file exec.c.
{
    int rc;
    fflush(stderr);
    wclear(stdscr);
    wmove(stdscr, 0, 0);
    wrefresh(stdscr);
    rc = shell(shellCmdPtr);
    restore_wins();
    return (rc);
}
References restore_wins(), and shell().
Referenced by menu_cmd_processor(), and view_cmd_processor().
nf_error()
int nf_error (int ec, char * s)
Display error message and wait for key press.
Parameters
ec Error code
s Error message
Definition at line 1045 of file dwin.c.
{
    fprintf(stderr, "ERROR: %s code: %d\n", s, ec);
    fprintf(stderr, "Press a key to continue");
    di_getch();
    fprintf(stderr, "\n");
    return ec;
}
References di_getch().
shell()
int shell (char * shellCmdPtr)
Execute a shell command.
Parameters
shellCmdPtr - pointer to the shell command string
Returns
the return code from the executed shell command
Note
Executes the command string using the user's shell.
If the SHELL environment variable is not set, use /bin/sh.
Definition at line 77 of file exec.c.
{
    int Eargc;
    char *Eargv[MAXARGS];
    char *shellPtr;
    int rc;
    Eargc = 0;
    shellPtr = getenv("SHELL");
    if (shellPtr == nullptr || *shellPtr == '\0')
        shellPtr = DEFAULTSHELL;
    Eargv[Eargc++] = strdup(shellPtr);
    Eargv[Eargc++] = "-c";
    Eargv[Eargc++] = shellCmdPtr;
    Eargv[Eargc++] = nullptr;
    rc = fork_exec(Eargv);
    free(Eargv[0]);
    return (rc);
}
References fork_exec().
Referenced by form_exec_cmd(), full_screen_shell(), lp(), and view_cmd_processor().
user_end()
void user_end ()
Program terminated by user.
Definition at line 1054 of file dwin.c.
                {
    destroy_curses();
    restore_shell_tioctl();
    sig_dfl_mode();
    fprintf(stderr, "Normal program exit");
    fprintf(stderr, "\n");
    exit(EXIT_SUCCESS);
}
References destroy_curses(), restore_shell_tioctl(), and sig_dfl_mode().
Variable Documentation
earg_str
char earg_str[MAXLEN]
Definition at line 23 of file exec.c.
Referenced by enter_file_spec(), and menu_cmd_processor().
eargc
int eargc
Definition at line 21 of file exec.c.
Referenced by display_pick_help(), enter_file_spec(), form_engine(), and menu_cmd_processor().
eargv
char* eargv[MAXARGS]
Definition at line 22 of file exec.c.
Referenced by display_pick_help(), enter_file_spec(), form_engine(), and menu_cmd_processor().